### ISSUE TITLE
[consoleApp] Adding a New IDP via provisioning tab of a saml web application fails

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#10089]
**Describe the issue:**
Cannot add a New IDP via Provisioning tab of a saml web app

**How to reproduce:**

1.Access https://localhost:9443/console
2.Login as super admin
3.Navigate to Develop > Applications > New Application > Web Application > SAML and add a saml application
4.In the edit view go for the provisioning tab
5. Click + New IDP
6. Input IDP details as attached in the image
7. Click Finish

**Observation**
None of the fields are marked as mandatory therefore created the IDP as in the attached image. UI error is getting displayed and update is not successful

**Environment information**
Mssql 2019
uniqueid jdbc primary US
IS 5.11.0 beta3 
ubuntu 16.04
Chrome Version 85.0.4183.121

![console17](https://user-images.githubusercontent.com/31848014/97257779-f3a95f80-183c-11eb-8ff8-3a920dda5ab7.png)

![console18](https://user-images.githubusercontent.com/31848014/97257798-fc019a80-183c-11eb-9646-b7fdf6ac775e.png)

**Comment by thivi** [comment]
```
Caused by: org.h2.jdbc.JdbcBatchUpdateException: NULL not allowed for column "CONNECTOR_NAME"; SQL statement:
INSERT INTO SP_PROVISIONING_CONNECTOR (TENANT_ID, IDP_NAME, CONNECTOR_NAME, APP_ID,IS_JIT_ENABLED, BLOCKING, RULE_ENABLED) VALUES (?,?,?,?,?,?,?) [23502-199]
	at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1298)
	at sun.reflect.GeneratedMethodAccessor196.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy54.executeBatch(Unknown Source)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.updateOutboundProvisioningConfiguration(ApplicationDAOImpl.java:1185)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.addApplicationConfigurations(ApplicationDAOImpl.java:537)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.updateApplication(ApplicationDAOImpl.java:490)
	... 58 more
```
The following error can be observed in the console. This could be due to a connector not being chosen. So this field should be made mandatory in the UI.

**Comment by ShanikaWickramasinghe** [comment]
Observing the same issue with 5.11.0 beta3 when trying to add a New IDP for a OpenID web application via provisiong tab.
Create a openid web app > Edit view > provisioning > Outboud provisiong > + New Identity provider > add details > Finish
