### ISSUE TITLE
SAMPLES: Photo editor and viewer samples doesn't work 

### ISSUE THREAD

**Issue by tsuresh** [wso2/product-is#10094]
**Is your suggestion related to a missing or misleading document? Please describe.**
The mentioned samples which are given in the doc doesn't work. War file successfully gets deployed to Tomcat Server but it doesn't start and it gives an error "FAIL - Application at context path [/photo-edit (2)] could not be started"
Doc: https://is.docs.wso2.com/en/5.11.0/learn/deploying-the-sample-app/#deploying-the-photo-editor-and-photo-viewer-webapps

This issue affects the following doc as well
https://is.docs.wso2.com/en/5.11.0/learn/configuring-access-delegation-with-uma/

**Describe the improvement**
Please fix the issue in the given sample applications and test it against Apache Tomcat 8

**Testing Environment**
Ubuntu 18
apache-tomcat-8.5.59

**Comment by piraveena** [comment]
Could see the below logs in tomcat server. 

`org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file+ error in ubuntu
`
```
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
		at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
		at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
		at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
		at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
		at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
		at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
		at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
		at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
		at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
		at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
		at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
		at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
		at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
		at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
		at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
		at org.wso2.photo.view.DCRUtility.performDCR(DCRUtility.java:47)
```

This was due to some permission issue in the photo-edit folder when the files having some permissions.
