### ISSUE TITLE
NPE thrown continuously in the logs for wso2-is 5.10.0 from OAuthCacheKey.java

### ISSUE THREAD

**Issue by hari819** [wso2/product-is#10202]
we are using 5.10.0 version of IS
The following NullPointer exception is continuously seen in logs,  we are not sure when it is getting triggered, as of now users are able to login/logout ,  could you please guide us 

`[2020-10-08 06:52:01,455] [989c1c7d-6a08-4993-bff4-6bdc773353b3]  INFO {org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl} - Successfully recovered 'CON_APP_KEY' constraint violation with the attempt : 1
**[2020-10-08 06:55:09,678] [550b18f3-54e6-4d73-a679-e84f18cf5963] ERROR {org.wso2.carbon.identity.oauth2.OAuth2Service} - Error occurred while issuing the access token for Client ID : ******, User ID null, Scope : [] and Grant Type : refresh_token **java.lang.NullPointerException**
        at org.wso2.carbon.identity.oauth.cache.**OAuthCacheKey.hashCode(OAuthCacheKey.java:47)**
        at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111)
        at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102)
        at org.wso2.carbon.caching.impl.CacheImpl.removeLocal(CacheImpl.java:540)
        at org.wso2.carbon.caching.impl.CacheImpl.remove(CacheImpl.java:521)
        at org.wso2.carbon.identity.application.common.cache.BaseCache.clearCacheEntry(BaseCache.java:207)**
        **at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.clearCache(RefreshGrantHandler.java:424)
        at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.removeIfCached(RefreshGrantHandler.java:227)
        at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.isLatestRefreshToken(RefreshGrantHandler.java:218)
        at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.validateRefreshTokenInRequest(RefreshGrantHandler.java:188)
        at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.validateGrant(RefreshGrantHandler.java:86)
        at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.issue(AccessTokenIssuer.java:234)
        at org.wso2.carbon.identity.oauth2.OAuth2Service.issueAccessToken(OAuth2Service.java:250)
        at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:318)
        at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:94)**
        at jdk.internal.reflect.GeneratedMethodAccessor1034.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
`

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [ IS 5.10.0]
 - OS: 5.10.0 docker image
 - Database: [oracle]
 - Userstore: [ JDBC]

---
thanks,
Hari

**Comment by rksk** [comment]
Same as https://github.com/wso2/product-is/issues/9272
