### ISSUE TITLE
Theming via extensions is not working in Latest WUM IS 5.10

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#10428]
**Describe the issue:**
When try to customize the authentication endpoint by overriding via extensions it gives the below error
```
[2020-10-26 12:49:23,470] [173b3d1f-d83d-4699-9693-386d60f060e1] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/authenticationendpoint].[default]} - Servlet.service() for servlet [default] in context with path [/authenticationendpoint] threw exception [javax.servlet.ServletException: java.lang.IllegalStateException: Cannot create a session after the response has been committed] with root cause java.lang.IllegalStateException: Cannot create a session after the response has been committed
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2998)
	at org.apache.catalina.connector.Request.getSession(Request.java:2445)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:908)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:244)
	at org.apache.catalina.core.ApplicationHttpRequest.getSession(ApplicationHttpRequest.java:582)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:244)at 
```
The reason for this in `login.jsp`, header.jsp extension in checked wrongly like this
```
     <%
        File headerFile = new File(getServletContext().getRealPath("extensions/product-title.jsp"));
        if (headerFile.exists()) {
    %>
        <jsp:include page="extensions/header.jsp"/>
    <% } else { %>
        <jsp:directive.include file="includes/header.jsp"/>
    <% } %>
```
**How to reproduce:**
Followed the steps in https://www.youtube.com/watch?v=pjLWJM6G-eE and https://is.docs.wso2.com/en/5.10.0/develop/customizing-identity-server-uis/#create-styling

**Comment by emswbandara** [comment]
@inthirakumaaran can we close this issue? is it fixed in public?

**Comment by inthirakumaaran** [comment]
This is already fixed in the public.
