### ISSUE TITLE
Password recovery flow breaks when a wrong answer is given for security questions

### ISSUE THREAD

**Issue by kushanb** [wso2/product-is#10462]
**Describe the issue:**

The password recovery flow breaks when a wrong answer is given for the security question is given. An error is displayed and an exception gets thrown in the terminal.

**How to reproduce:**
1. Login to console as admin
2. Go to Manage > Account Management > Account Recovery
3. Enable security question based password recovery and update
4. Logout from console
5. Login to My Account from the account to be tested 
6. Go to Security and setup the security questions
7. Logout from My Account 
8. Go to forgot password on the login screen 
9. Enter username for an account to recover the password, select "Recover with Security Questions" and click submit
10. Enter the answer for the security question incorrectly 

**Observation:**

1. The below error is displayed

<img width="798" alt="Screenshot 2020-11-11 at 17 12 07" src="https://user-images.githubusercontent.com/19253380/98807688-0927a780-2441-11eb-9eaf-d847f7d97396.png">

2. Confirm form resubmission page is displayed when Go back is pressed

3. The below exception is thrown in the terminal

```
[2020-11-11 17:11:54,257] [7703e130-512f-4509-a9c1-227f6dfed85d] ERROR {org.wso2.carbon.identity.recovery.endpoint.impl.ValidateAnswerApiServiceImpl} - Error occurred in the server while performing the task. java.lang.UnsupportedOperationException: User Functionality properties are not configured.
	at org.wso2.carbon.identity.recovery.handler.ConfigStoreFunctionalityLockPropertyHandler.getConfigStoreProperties(ConfigStoreFunctionalityLockPropertyHandler.java:71)
	at org.wso2.carbon.identity.recovery.password.SecurityQuestionPasswordRecoveryManager.handleAnswerVerificationFailInFunctionalityLockMode(SecurityQuestionPasswordRecoveryManager.java:765)
	at org.wso2.carbon.identity.recovery.password.SecurityQuestionPasswordRecoveryManager.validateUserChallengeQuestions(SecurityQuestionPasswordRecoveryManager.java:479)
	at org.wso2.carbon.identity.recovery.endpoint.impl.ValidateAnswerApiServiceImpl.validateAnswerPost(ValidateAnswerApiServiceImpl.java:29)
	at org.wso2.carbon.identity.recovery.endpoint.ValidateAnswerApi.validateAnswerPost(ValidateAnswerApi.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:123)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0-Beta6 Snapshot
 - OS: Mac
 - Database: MySQL8
 - Userstore: JDBC

**Comment by kushanb** [comment]
**Related Issues:**
https://github.com/wso2/product-is/issues/9662

**Comment by pulasthi7** [comment]
This should be fixed with 
https://github.com/wso2-extensions/identity-governance/pull/455

**Comment by sachiniWettasinghe** [comment]
Tested with the latest 5.11.0-Beta6 Snapshot (with https://github.com/wso2-extensions/identity-governance/pull/455) and this is not getting reproduced. Hence this issue can be closed.

**Comment by RidmiR** [comment]
I was able to reproduce this issue in 5.11.0-Beta6 Snapshot with the same error log observed as well. 

Environment information
Product Version: 5.11.0-Beta6 Snapshot
OS: Mac
Database: M2
Userstore: LDAP
