### ISSUE TITLE
NPE when updatedTime registry property is missing

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#10476]
**How to reproduce:**
- Delete (or set as null) the "timestamp" property at "/repository/components/org.wso2.carbon.user.mgt/updatedTime"
- Restart the server

The following log can be seen.
```
ERROR {org.wso2.carbon.core.internal.permission.update.PermissionUpdater} - Error when updating the permission cache for tenant : -1234 java.lang.NullPointerException
at org.wso2.carbon.core.internal.permission.update.PermissionUpdater.update(PermissionUpdater.java:72)
at org.wso2.carbon.core.internal.permission.update.PermissionUpdateServiceComponent.activate(PermissionUpdateServiceComponent.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```
We can delete the "updatedTime" resource itself from the "/repository/components/org.wso2.carbon.user.mgt" path as a workaround. So the resource will be created on the next startup.

**Environment information** 
 - Product Version:  IS 5.10.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
