### ISSUE TITLE
Getting 500 status code for scim2/Roles endpoint intermittently

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#10477]
**Describe the issue:**
When a fresh pack was built (IS 5.11.0-beta6-SNAPSHOT), https://localhost:9443/scim2/Roles endpoints gave a `500` error code.

Enabling charon logs lead to the following stack trace.

```
[2020-11-12 03:26:12,310] [f28e05cb-5c36-4776-9ee7-65656ef92a9d] DEBUG {org.wso2.charon3.core.protocol.endpoints.AbstractResourceManager} - Error occurred while listing roles. org.wso2.charon3.core.exceptions.CharonException: Error occurred while listing roles.
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManager.listRoles(SCIMRoleManager.java:322)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManager.listRolesWithGET(SCIMRoleManager.java:179)
	at org.wso2.charon3.core.protocol.endpoints.RoleResourceManager.listWithGETRole(RoleResourceManager.java:165)
	at org.wso2.carbon.identity.scim2.provider.resources.RoleResource.getRoles(RoleResource.java:213)
	at sun.reflect.GeneratedMethodAccessor204.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:666)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:123)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.identity.role.mgt.core.IdentityRoleManagementClientException: Invalid scenario. Multiple roles found for the given role name: Internal/system and tenantDomain: carbon.super
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.batchProcessRoleNames(RoleDAOImpl.java:1301)
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.getRoleIDsByNames(RoleDAOImpl.java:1271)
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.buildRolesList(RoleDAOImpl.java:356)
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.processListRolesQuery(RoleDAOImpl.java:330)
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.getRoles(RoleDAOImpl.java:283)
	at org.wso2.carbon.identity.role.mgt.core.internal.RoleManagementServiceImpl.getRoles(RoleManagementServiceImpl.java:68)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManager.listRoles(SCIMRoleManager.java:314)
	... 62 more
```
```bash
Caused by: org.wso2.carbon.identity.role.mgt.core.IdentityRoleManagementClientException: Invalid scenario. Multiple roles found for the given role name: Internal/system and tenantDomain: carbon.super
```

**NOTE**
When I discarded the existing pack and ran a freshly unzipped pack, the issue went away.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-beta6-SNAPSHOT
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

**Comment by brionmario** [comment]
cc @ashensw

**Comment by IsuraD** [comment]
This is handled by logging a warning message. Ideally, it is required to find how duplicates records are inserted. Please reopen if you observe the same error again. (warn message)
