### ISSUE TITLE
OIDC hybrid flow error after reusing authz code

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#10508]
After getting the token using code received from the hybrid flow reuse the code and the token is revoked. The  initiate another hybrid token call it ends up in an error.

```
https://example-app.com/redirect#error_description=Error+occurred+when+processing+the+authorization+request.+Returning+an+error+back+to+client.&state=test&error=server_error&session_state=4922087ccf949dece261e9ff694cb31eee314c67e136c91322f6860c15bd9663.utndEQiMvMWOZRo_9hztzg
```

Appears to be a caching issue as this works after a restart.

**Steps to reproduce:**
1. Do an OIDC hybrid flow call 
```
https://localhost:9443/t/abc.com/oauth2/authorize?client_id=g1r3dHEco7gtsaXkTmroBC6cxHYa&redirect_uri=https://example-app.com/redirect&scope=openid&state=test&nonce=X3Tp9p6NH3&response_type=code%20id_token%20token
```

2. Do a token call with authz code grant with the received authz code.
3. Repeat step 2.
4. Repeat step 1.
the following error will be shown

```
https://example-app.com/redirect#error_description=Error+occurred+when+processing+the+authorization+request.+Returning+an+error+back+to+client.&state=test&error=server_error&session_state=4922087ccf949dece261e9ff694cb31eee314c67e136c91322f6860c15bd9663.utndEQiMvMWOZRo_9hztzg
```

**Expected behaviour**
Step 4 should succeed.

**Stacktrace**
```
[2020-11-13 16:14:32,698] [c1266816-ccd0-4690-a9f6-de45d8cf5f57] ERROR {org.wso2.carbon.identity.oauth2.OAuth2Service} - Error occurred when processing the authorization request. Returning an error back to client. java.lang.IllegalArgumentException: Invalid Access Token. Access token is not ACTIVE.
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getAccessTokenDOFromTokenIdentifier(OAuth2Util.java:1599)
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getAccessTokenDOfromTokenIdentifier(OAuth2Util.java:1568)
	at org.wso2.carbon.identity.oauth2.authz.handlers.util.ResponseTypeHandlerUtil.getAccessTokenDO(ResponseTypeHandlerUtil.java:407)
	at org.wso2.carbon.identity.oauth2.authz.handlers.util.ResponseTypeHandlerUtil.addUserAttributesToCache(ResponseTypeHandlerUtil.java:381)
	at org.wso2.carbon.identity.oauth2.authz.handlers.util.ResponseTypeHandlerUtil.buildIdToken(ResponseTypeHandlerUtil.java:355)
	at org.wso2.carbon.identity.oauth2.authz.handlers.util.ResponseTypeHandlerUtil.buildIDTokenResponseDTO(ResponseTypeHandlerUtil.java:333)
	at org.wso2.carbon.identity.oauth2.authz.handlers.HybridResponseTypeHandler.issue(HybridResponseTypeHandler.java:71)
	at org.wso2.carbon.identity.oauth2.authz.AuthorizationHandlerManager.handleAuthorization(AuthorizationHandlerManager.java:105)
	at org.wso2.carbon.identity.oauth2.OAuth2Service.authorize(OAuth2Service.java:105)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.authorize(OAuth2AuthzEndpoint.java:2288)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleUserConsent(OAuth2AuthzEndpoint.java:964)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleApproveAlwaysWithPromptForNewConsent(OAuth2AuthzEndpoint.java:2202)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleConsent(OAuth2AuthzEndpoint.java:1857)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.doUserAuthorization(OAuth2AuthzEndpoint.java:1829)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleSuccessfulAuthentication(OAuth2AuthzEndpoint.java:714)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleAuthenticationResponse(OAuth2AuthzEndpoint.java:685)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.authorize(OAuth2AuthzEndpoint.java:248)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleAuthFlowThroughFramework(OAuth2AuthzEndpoint.java:2480)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleInitialAuthorizationRequest(OAuth2AuthzEndpoint.java:835)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.authorize(OAuth2AuthzEndpoint.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:137)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/10932

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1526
