### ISSUE TITLE
The user self sign up integration test is failing for IS-KM 

### ISSUE THREAD

**Issue by chamathns** [wso2/product-is#10510]
**Describe the issue:**

The user self sign up integration test is failing with the following exception.

```
ERROR - [CXFServlet] Servlet.service() for servlet [CXFServlet] in context with path [/api/identity/user/v1.0] threw exception
2020-11-10 11:59:42,344 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - java.lang.NullPointerException: null
2020-11-10 11:59:42,344 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - at org.wso2.carbon.context.PrivilegedCarbonContext.getOSGiService(PrivilegedCarbonContext.java:369) ~[org.wso2.carbon.utils_4.6.1.jar:?]
2020-11-10 11:59:42,344 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - at org.wso2.carbon.identity.user.endpoint.util.Utils.getUserSelfRegistrationManager(Utils.java:59) ~[classes/:?]
2020-11-10 11:59:42,344 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - at org.wso2.carbon.identity.user.endpoint.impl.MeApiServiceImpl.mePost(MeApiServiceImpl.java:98) ~[classes/:?]
2020-11-10 11:59:42,344 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - at org.wso2.carbon.identity.user.endpoint.MeApi.mePost(MeApi.java:63) ~[classes/:?]
2020-11-10 11:59:42,344 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
2020-11-10 11:59:42,344 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
```
The issue occurs because the `org.wso2.carbon.identity.recovery` feature requires a mandatory feature called `org.wso2.carbon.identity.user.functionality.mgt`.

**Approach to Resolve:**
Add the `org.wso2.carbon.identity.user.functionality.mgt` feature as an **importFeatureDef** in the `org.wso2.carbon.identity.recovery` feature pom.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
