### ISSUE TITLE
JIT silent provisioning of federated users fails when the default password policy is enabled

### ISSUE THREAD

**Issue by hefesita** [wso2/product-is#10597]
**Describe the issue:**
JIT silent provisioning of federated users fails when the default password policy is enabled

**How to reproduce:**
Enable silent JIT (without asking consent or password from users) for a federate IDP, enable also the default password policies, the user is not provisioned:
Caused by: org.wso2.carbon.identity.event.IdentityEventException: 'Password pattern policy violated. Password should contain a digit[0-9], a lower case letter[a-z], an upper case letter[A-Z], one of !@#$%&* characters'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:103)
        at org.wso2.carbon.identity.password.policy.util.Utils.handleEventException(Utils.java:36)
        at org.wso2.carbon.identity.password.policy.handler.PasswordPolicyValidationHandler.handleEvent(PasswordPolicyValidationHandler.java:168)
        at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56)
        at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.handleEvent(IdentityMgtEventListener.java:604)
        ... 76 more
Caused by: org.wso2.carbon.identity.mgt.policy.PolicyViolationException: 'Password pattern policy violated. Password should contain a digit[0-9], a lower case letter[a-z], an upper case letter[A-Z], one of !@#$%&* characters'
        at org.wso2.carbon.identity.mgt.policy.PolicyRegistry.enforcePasswordPolicies(PolicyRegistry.java:39)
        at org.wso2.carbon.identity.password.policy.handler.PasswordPolicyValidationHandler.handleEvent(PasswordPolicyValidationHandler.java:166)
        ... 78 more

**Expected behavior:**
User should be provisioned

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.9.0
 - OS: Linux
 - Database: PostgreSQL

 - Userstore: LDAP

---

**Comment by senthalan** [comment]
Seems like a valid bug, The [generatePassword](https://github.com/wso2/carbon-identity-framework/blob/v5.18.189/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/provisioning/impl/DefaultProvisioningHandler.java#L145) method in DefaultProvisioningHandler has to generate a valid password according to the policy or we need to skip the policy check on this case.
