### ISSUE TITLE
Improvement on the debug level logging in case of error when validating the SP configurations

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#10630]
in the current implementation, the validation logic throws exception without any useful information.
```
Caused by: org.wso2.carbon.identity.application.common.IdentityApplicationManagementValidationException: Validation Error
	at org.wso2.carbon.identity.application.mgt.ApplicationMgtValidator.validateSPConfigurations(ApplicationMgtValidator.java:88)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.updateApplication(ApplicationManagementServiceImpl.java:547)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementAdminService.updateApplication(ApplicationManagementAdminService.java:341)
	... 79 more
```
https://github.com/wso2/carbon-identity-framework/blob/d8ebf42510163048971298e54d4e35c3901c9e67/components/application-mgt/org.wso2.carbon.identity.application.common/src/main/java/org/wso2/carbon/identity/application/common/IdentityApplicationManagementValidationException.java#L34

This needed to improved. Otherwise, it is hard to understand why the request failed.

Related: https://github.com/wso2/product-is/issues/9386

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
