### ISSUE TITLE
Error While listing tenants from tenant management API when MSSQL server is used

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#10654]
**Describe the issue:**
$Subject
**How to reproduce:**
1. Configure MSSQL as the DATABASE for shared and identity datasources.
2. Use following sample curl to retrieve tenants
```
curl --location --request GET 'https://localhost:9443/api/server/v1/tenants' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Cookie: JSESSIONID=9FBB2FC351EA0D202DD661C7CF0599777A57FC538B104861AB863F09E085679567B4A8A1EEE43ADA3E5D4864B7272F21C74F32ECC645D59862B100B3B9863A7727C81A1FAF074C577403BB252848E8118F9DDE1A1E0D036A6D71E9F89930CDE7428C8835EA89144400099AEE56E947A9AACBFB0886239CAC2E42F617970812EF; JSESSIONID=63272E27CEDE3744BA0F51558BEB94CF'
```
3. 500 Server error response is returned.
4. Observed following in the backend. 
```
[2020-12-01 17:35:04,447] [88445a1f-4423-4728-b23f-c13dd7250483] ERROR {org.wso2.carbon.user.core.tenant.TenantManager} - Error while loading tenant from DB: Database driver could not be identified or not supported.
[2020-12-01 17:35:04,457] [88445a1f-4423-4728-b23f-c13dd7250483] ERROR {org.wso2.carbon.identity.api.server.tenant.management.v1.core.ServerTenantManagementService} - errorCode: TM-65001 | message: Server encountered an error while listing the tenants. org.wso2.carbon.stratos.common.exception.TenantManagementServerException: Error in retrieving the tenant information.
	at org.wso2.carbon.tenant.mgt.services.TenantMgtImpl.listTenants(TenantMgtImpl.java:126)
	at org.wso2.carbon.identity.api.server.tenant.management.v1.core.ServerTenantManagementService.listTenants(ServerTenantManagementService.java:118)
	at org.wso2.carbon.identity.api.server.tenant.management.v1.impl.TenantsApiServiceImpl.retrieveTenants(TenantsApiServiceImpl.java:68)
	at org.wso2.carbon.identity.api.server.tenant.management.v1.TenantsApi.retrieveTenants(TenantsApi.java:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:137)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:98)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:123)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.user.core.UserStoreException: Error while loading tenant from DB: Database driver could not be identified or not supported.
	at org.wso2.carbon.user.core.tenant.JDBCTenantManager.getTenantQueryResultSet(JDBCTenantManager.java:1191)
	at org.wso2.carbon.user.core.tenant.JDBCTenantManager.listTenants(JDBCTenantManager.java:480)
	at org.wso2.carbon.tenant.mgt.services.TenantMgtImpl.listTenants(TenantMgtImpl.java:121)
```
**Expected behavior:**
Tenants should be listed.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.12.0-M2-SNAPSHOT]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

**Comment by Dinithi-Hasanika** [comment]
This issue is in IS 5.11 as well.

**Comment by RushanNanayakkara** [comment]
did you get the U2 updates before testing?
