### ISSUE TITLE
Error in building react-js sample application

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2/product-is#11121]
**Describe the issue:**

When building the react-js sample application, the below error is noticed in logs.

```
user:~/Documents/wso2/react-js-app » npm install && npm start

> fsevents@1.2.13 install /Users/user/Documents/wso2/react-js-app/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

node:internal/modules/cjs/loader:903
  throw err;
  ^

Error: Cannot find module 'nan'
Require stack:
- /Users/user/Documents/wso2/react-js-app/node_modules/watchpack-chokidar2/node_modules/fsevents/[eval]
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at [eval]:1:1
    at Script.runInThisContext (node:vm:132:18)
    at Object.runInThisContext (node:vm:309:38)
    at node:internal/process/execution:77:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:76:60) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/user/Documents/wso2/react-js-app/node_modules/watchpack-chokidar2/node_modules/fsevents/[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Darwin 20.1.0
gyp ERR! command "/usr/local/Cellar/node/15.0.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Documents/wso2/react-js-app/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v15.0.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> fsevents@1.2.13 install /Users/user/Documents/wso2/react-js-app/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

node:internal/modules/cjs/loader:903
  throw err;
  ^

Error: Cannot find module 'nan'
Require stack:
- /Users/user/Documents/wso2/react-js-app/node_modules/webpack-dev-server/node_modules/fsevents/[eval]
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at [eval]:1:1
    at Script.runInThisContext (node:vm:132:18)
    at Object.runInThisContext (node:vm:309:38)
    at node:internal/process/execution:77:19
    at [eval]-wrapper:6:22
    at evalScript (node:internal/process/execution:76:60) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/user/Documents/wso2/react-js-app/node_modules/webpack-dev-server/node_modules/fsevents/[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Darwin 20.1.0
gyp ERR! command "/usr/local/Cellar/node/15.0.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Documents/wso2/react-js-app/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v15.0.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> core-js-pure@3.8.2 postinstall /Users/user/Documents/wso2/react-js-app/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

added 864 packages from 528 contributors and audited 864 packages in 13.928s

49 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

> @asgardeo/react-js-app-sample@0.1.1 start /Users/user/Documents/wso2/react-js-app
> webpack-dev-server --mode development --inline --hot --open

ℹ ｢wds｣: Generating SSL Certificate
ℹ ｢wds｣: Project is running at https://localhost:5000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/user/Documents/wso2/react-js-app/dist
ℹ ｢wds｣: 404s will fallback to /index.html
ℹ ｢wdm｣: Hash: f5942e41ca06ad16ceab
Version: webpack 4.43.0
Time: 3584ms
Built at: 01/28/2021 10:14:24 PM
      Asset      Size  Chunks                   Chunk Names
 index.html   1.2 KiB          [emitted]
    main.js  1.72 MiB    main  [emitted]        main
main.js.map  1.96 MiB    main  [emitted] [dev]  main
Entrypoint main = main.js main.js.map
[1] multi (webpack)-dev-server/client?https://localhost:5000 (webpack)/hot/dev-server.js ./src/app.js 52 bytes {main} [built]
[./node_modules/@asgardio/oidc-js/dist/asgardio-oidc.production.esm.js] 146 KiB {main} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[./node_modules/react-json-view/dist/main.js] 150 KiB {main} [built]
[./node_modules/react/index.js] 190 bytes {main} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[./node_modules/webpack-dev-server/client/index.js?https://localhost:5000] (webpack)-dev-server/client?https://localhost:5000 4.29 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {main} [built]
[./src/app.js] 11.6 KiB {main} [built]
    + 47 hidden modules
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 1.31 KiB {HtmlWebpackPlugin_0} [built]
ℹ ｢wdm｣: Compiled successfully.
```

**Environment information:**
 - OS: Mac
 - Node version: v15.0.1
 - NPM version: 6.14.8

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by madurangasiriwardena** [comment]
This is observed in the first time build only.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
