### ISSUE TITLE
NPE in device grant flow when doing SSO with openid scope

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11143]
**Describe the issue:**
Once the user submits a valid user code, from UserAuthenticationEndpoint [1], we forward the request to OAuth2AuthzEndpoint [2] in the following way.
```
private OAuth2AuthzEndpoint oAuth2AuthzEndpoint = new OAuth2AuthzEndpoint();
...
return oAuth2AuthzEndpoint.authorize(commonAuthRequestWrapper, response);
```

Ideally, we have considered OAuth2AuthzEndpoint as a singleton class and kept OpenIDConnectClaimFilter as a class variable. But in this flow, we are creating a new object of OAuth2AuthzEndpoint and do not set OpenIDConnectClaimFilter. Therefore, an NPE occurs if we try to complete the device grant flow with OIDC since OpenIDConnectClaimFilter is null.

The same is done in CibaAuthzHandler [3] as well. We will have to fix it too.

**How to reproduce:**
- Try device grant flow with openid scope when you are having an authenticated session on the browser (this does not happen when you are logging in here since the claim filter will be used in another http request then)
- 500 error is shown in the browser with the following stack trace in logs once you submit the user code
```
ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/oauth2].[OAuth2Endpoints]} - Servlet.service() for servlet [OAuth2Endpoints] in context with path [/oauth2] threw exception java.lang.NullPointerException
        at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handlePreConsent(OAuth2AuthzEndpoint.java:2022)
        at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handlePreConsentIncludingExistingConsents(OAuth2AuthzEndpoint.java:1977)
        at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleApproveAlwaysWithPromptForNewConsent(OAuth2AuthzEndpoint.java:2221)
        at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleConsent(OAuth2AuthzEndpoint.java:1885)
        at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.doUserAuthorization(OAuth2AuthzEndpoint.java:1857)
        at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleSuccessfulAuthentication(OAuth2AuthzEndpoint.java:713)
        at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleAuthenticationResponse(OAuth2AuthzEndpoint.java:684)
        at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.authorize(OAuth2AuthzEndpoint.java:247)
        at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleAuthFlowThroughFramework(OAuth2AuthzEndpoint.java:2506)
        at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleInitialAuthorizationRequest(OAuth2AuthzEndpoint.java:856)
        at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.authorize(OAuth2AuthzEndpoint.java:245)
        at org.wso2.carbon.identity.oauth.endpoint.device.UserAuthenticationEndpoint.deviceAuthorize(UserAuthenticationEndpoint.java:102)
  ```

**Environment information** 
 - Product Version: IS 5.10.0
 
 [1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/7286fdd575bb13de7cc382b1f3f7d774813e6d7e/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/device/UserAuthenticationEndpoint.java
 [2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/954f7998b913132dc0b0ae8ac68093b8bc0cd68d/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/authz/OAuth2AuthzEndpoint.java
 [3] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/b0ee8c721631468fbb3e85003875c9facd6070f0/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/ciba/CibaAuthzHandler.java

**Comment by rksk** [comment]
Discussed this with @mefarazath. We can make the openIDConnectClaimFilter in OAuth2AuthzEndpoint as a quick solution. But the ultimate solution for this would be to avoid creating new instances of the OAuth2AuthzEndpoint but refactor the OAuth2AuthzEndpoint and create another service layer. So we can invoke that through a wrapper when we need to dispatch a request from anywhere.

This is already done in the identity framework to cater to the requirement of dispatching requests from inbound authenticators to the framework. 

Both CommonAuthenticationHandler and the CommonAuthenticationServlet invokes the service layer while external components like OAuth2AuthzEndpoint invokes the CommonAuthenticationHandler to dispatch requests [3].

[1] https://github.com/wso2/carbon-identity-framework/blob/ffb500264bab3a92eb5f494098a4933504015168/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/servlet/CommonAuthenticationServlet.java
[2] https://github.com/wso2/carbon-identity-framework/blob/ffb500264bab3a92eb5f494098a4933504015168/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/CommonAuthenticationHandler.java
[3] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/954f7998b913132dc0b0ae8ac68093b8bc0cd68d/components/org.wso2.carbon.identity.oauth.endpoint/src/main/java/org/wso2/carbon/identity/oauth/endpoint/authz/OAuth2AuthzEndpoint.java#L2460-L2461

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
