### ISSUE TITLE
Use basic/client authentication for internal API calls instead of Mutual SSL

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11251]
**Is your suggestion related to an experience ? Please describe.**
Mutual SSL is still being used for some internal API calls such as fetching context properties from the authentication portal. Ref [1].

Mutual SSL stops working when it comes to SSL termination.

Since SSL termination is a general thing now, this issue is a frequent issue when using the identifier first authenticator or adaptive script prompt() function.

There are workarounds like configuring internal communication. It also gets complicated due to hostname verification and all.

Therefore, it is a necessity to have improvement, where all the internal communications are done over basic authentication. 

[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint.util/src/main/java/org/wso2/carbon/identity/application/authentication/endpoint/util/AuthContextAPIClient.java#L62

**Comment by ruwanta** [comment]
The solution here is to carry the authentication information in another header after termination. 
Using basic authentication is big security risk even for internal communication.

**Comment by rksk** [comment]
> The solution here is to carry the authentication information in another header after termination.
> Using basic authentication is big security risk even for internal communication.

@ruwanta, sorry, actually what I meant was client authentication. We already use client authentication for other flows like account recovery. 

https://github.com/wso2-extensions/identity-carbon-auth-rest/blob/9b7a3179bbf233ca4e8cbd0d4f7f24942bbf35e3/components/org.wso2.carbon.identity.auth.service/src/main/java/org/wso2/carbon/identity/auth/service/handler/impl/ClientAuthenticationHandler.java

**Comment by rksk** [comment]
Marked as a bug since it's hard to work with LBs and always needs to configure internal communication. It also needs changing etc/hosts because hostname has to be matching with CN for mutual SSL to succees. Updating etc/hosts cause other API calls to fail since they are trying to connect to 443, but internally identity server is listening to 9443. This chain goes on...

**Comment by rksk** [comment]
**Workaround**

We can configure the web application to communicate internally without going through the load balancer by uncommenting the following section in <IS_HOME>/repository/deployment/server/webapps/authenticationendpoint/WEB-INF/web.xml.
```
    <context-param>
        <param-name>AuthenticationRESTEndpointURL</param-name>
        <param-value>https://localhost:9443/api/identity/auth/v1.1/</param-value>
    </context-param>
```
Now it will fail due to SSL Hostname Verification since the certificate is having a different CN. To address that, we can disable hostname verification for these internal calls only by adding the following to deployment.toml.
```
[identity.auth_framework]
endpoint.hostname_verification_enabled = false
```

**Comment by ruwanta** [comment]
All internal communication should happen on SSL, we can not allow unencrypted data. SSL termination does not interfere with internal SSL+mTLS communication as they are supposed to use different certs.

**Comment by rksk** [comment]
Hi @ruwanta, The suggestion is not to disable SSL, but to use a unified authentication mechanism for all the internal communication. Currently, all of the followings are used by different UI components for internal API call authentication.

- Client authentication [1]
- MTLS
- Basic auth with admin credentials (for SOAP calls)

The suggestion is to avoid using MTLS due to the following concerns in addition to external LBs interfering MTLS.
- We have observed multiple users are having issues with MTLS and spent a lot of time with SSL debugging to troubleshoot different kinds of issues
- If someone wants to set `certificateVerification` property to "none" at the tomcat connector level in order to avoid browser prompting for client certificate (when there is a client cert installed on the browser), it can not be done at the moment since it breaks the internal calls which use MTLS for authentication

[1] https://github.com/wso2-extensions/identity-carbon-auth-rest/blob/9b7a3179bbf233ca4e8cbd0d4f7f24942bbf35e3/components/org.wso2.carbon.identity.auth.service/src/main/java/org/wso2/carbon/identity/auth/service/handler/impl/ClientAuthenticationHandler.java

**Comment by deshankoswatte** [comment]
A simple method to reproduce this issue is as follows.

- Attach the configuration below to the deployment.toml file located in the _<IS_HOME>/repository/conf_ directory.
```
[transport.https.sslHostConfig.properties]
certificateVerification = "none"
```
- Restart the WSO2 Identity Server.
- Configure identifier-first authentication as the first step followed with basic authentication as the second step for a specific service provider.
- Access the application. The issue will be reproduced as soon as the username is submitted from the identifier-first page.

A sample stacktrace for the issue is as follows.
```
[2022-03-28 11:35:30,724] [ca757182-2467-4d91-9578-19a0b9eb64ec] ERROR {org.wso2.carbon.identity.application.authentication.endpoint.util.AuthContextAPIClient} - Sending GET request to URL : https://localhost:9443/api/identity/auth/v1.1/context/7a828c8b-8030-49f9-a01b-2a86762974bb, failed. java.io.IOException: Server returned HTTP response code: 401 for URL: https://localhost:9443/api/identity/auth/v1.1/context/7a828c8b-8030-49f9-a01b-2a86762974bb
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.wso2.carbon.identity.application.authentication.endpoint.util.AuthContextAPIClient.getContextProperties(AuthContextAPIClient.java:70)
...
[2022-03-28 11:35:30,736] [ca757182-2467-4d91-9578-19a0b9eb64ec] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/authenticationendpoint].[jsp]} - Servlet.service() for servlet [jsp] threw exception java.lang.IllegalStateException: Cannot create a session after the response has been committed
	at org.apache.catalina.connector.Request.doGetSession(Request.java:3049)
	at org.apache.catalina.connector.Request.getSession(Request.java:2493)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:908)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:244)
	at org.apache.catalina.core.ApplicationHttpRequest.getSession(ApplicationHttpRequest.java:585)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:244)
	at org.apache.catalina.core.ApplicationHttpRequest.getSession(ApplicationHttpRequest.java:585)
	at org.apache.catalina.core.ApplicationHttpRequest.getSession(ApplicationHttpRequest.java:529)
...
```
**Note: This was tested in a 5.12.0-Alpha pack.**
