### ISSUE TITLE
TenantRegistrationConfirmation is not working with tenant qualified urls config is enabled

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#11380]
**Describe the issue:**
When we try to register tenant using tenant ask password flow with tenant qualified url config, https://github.com/wso2/product-is/issues/8047, flow is not woking. 

```
POST /api/server/v1/tenants HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW5Ad3NvMi5jb206YWRtaW4=
User-Agent: PostmanRuntime/7.26.5
Accept: */*
Postman-Token: 70179777-d55f-45ae-b114-700fd9c6678b
Host: localhost:9443
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 557
{
    "domain": "wso21.com",
    "owners": [
        {
            "username": "piraveena@wso2.com",
            "email": "piraveena@wso2.com",
            "firstname": "kim",
            "lastname": "kim",
            "provisioningMethod": "invite-via-email",
            "additionalClaims": [
                {
                    "claim": "http://wso2.org/claims/telephone",
                    "value": "+94 562 8723"
                },
                {
                    "claim": "http://wso2.org/claims/country",
                    "value": "Srilanka"
                }
            ]
        }
    ]
}
```

This is becuase, we create tenants in super tenant.  we always send tenant domain parameter in the email body.

`https://localhost:9443/accountrecoveryendpoint/confirmrecovery.do?confirmation=7c5d771c-46a5-4bca-8218-aa071756f28c&userstoredomain=PRIMARY&username=piraveena18%40gmail.com&tenantdomain=wso2.io&callback=https://localhost:9443/t/wso2.io/admin-portal`

But if tenant qualified urls are enabled, then we take the tenant domain from the path param. Here the path param is not found. So it will be treated as **carbon.super** if tenant qualified config is enabled. But the tenantdomain of the user is **wso2.io**. So it will fail during tenant validation.

```
[2021-03-03 09:42:17,200] [6e4afa20-f14f-4087-9c8a-59a16b5fbe3a] DEBUG {org.wso2.carbon.identity.recovery.endpoint.impl.ValidateCodeApiServiceImpl} - Client Error while validating the confirmation code org.wso2.carbon.identity.recovery.IdentityRecoveryClientException: Invalid tenant domain: wso2.io
	at org.wso2.carbon.identity.recovery.password.NotificationPasswordRecoveryManager.getValidatedUser(NotificationPasswordRecoveryManager.java:754)
	at org.wso2.carbon.identity.recovery.endpoint.impl.ValidateCodeApiServiceImpl.validateCodePost(ValidateCodeApiServiceImpl.java:32)
	at org.wso2.carbon.identity.recovery.endpoint.ValidateCodeApi.validateCodePost(ValidateCodeApi.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```

https://github.com/wso2-extensions/identity-governance/blob/v1.4.91/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/password/NotificationPasswordRecoveryManager.java#L753

**How to 
reproduce:**

1. Enable tenanted url configuration.
2. Try Tenantregistration confirmation flow.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [ IS 5.12.0-m11]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [LDAP]

---

**Comment by piraveena** [comment]
related to https://github.com/wso2/product-is/issues/11363
