### ISSUE TITLE
Unable to build identity-apps repository 

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#11483]
**Describe the issue:**
Unable to build the `https://github.com/wso2/identity-apps` repository locally due to a heap memory issue.

**How to reproduce:**

1. Clone Identity apps repository.
2. Install node
3. Execute npm run build:dev which results in ` FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory` error. If I start the `console` app after this, that also does not work and eventually times out when I try to access `https://localhost:9001/console`
```
@wso2is/console: <--- Last few GCs --->
@wso2is/console: [8959:0x1046c6000]   354459 ms: Scavenge 3922.8 (4108.3) -> 3913.4 (4100.7) MB, 1.5 / 0.0 ms  (average mu = 0.200, current mu = 0.098) allocation failure
@wso2is/console: [8959:0x1046c6000]   355007 ms: Mark-sweep 3932.2 (4115.9) -> 3913.4 (4094.4) MB, 519.1 / 0.0 ms  (average mu = 0.148, current mu = 0.093) allocation failure scavenge might not succeed
@wso2is/console: [8959:0x1046c6000]   355032 ms: Scavenge 3930.5 (4109.7) -> 3921.1 (4102.1) MB, 1.5 / 0.0 ms  (average mu = 0.148, current mu = 0.093) allocation failure
@wso2is/console: <--- JS stacktrace --->
@wso2is/console: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
@wso2is/console:  1: 0x1012e4da5 node::Abort() (.cold.1) [/usr/local/bin/node]
@wso2is/console:  2: 0x1000a6239 node::Abort() [/usr/local/bin/node]
@wso2is/console:  3: 0x1000a639f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
@wso2is/console:  4: 0x1001e9007 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
@wso2is/console:  5: 0x1001e8fa3 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
@wso2is/console:  6: 0x100397e95 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
@wso2is/console:  7: 0x10039995a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
@wso2is/console:  8: 0x100395029 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
@wso2is/console:  9: 0x1003928c1 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
@wso2is/console: 10: 0x1003a115a v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
@wso2is/console: 11: 0x1003a11e1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
@wso2is/console: 12: 0x10036eb87 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
@wso2is/console: 13: 0x1006ed8d8 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
@wso2is/console: 14: 0x100a7a239 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
@wso2is/console: > @wso2is/console@1.2.94 test /Users/wso2/tharindub/repositories/public/identity-apps/apps/console
@wso2is/console: > npx jest --passWithNoTests
@wso2is/console: ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
@wso2is/console: ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
@wso2is/console: ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
@wso2is/console: ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
@wso2is/console: ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
@wso2is/console: ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
@wso2is/console: PASS src/extensions/components/tests/example.test.tsx (19.771 s)
@wso2is/console:   Test Suite - Sample Extension Component.
@wso2is/console:     ✓ Test proper rendering of Sample Extension component (63 ms)
@wso2is/console: PASS src/features/remote-repository-configuration/tests/remote-fetch-status.test.tsx (24.169 s)
@wso2is/console:   UTC-4.0 - [Remote Fetch Configuration] - Configuration Status
@wso2is/console:     ✓ UTC-4.1 - Test proper rendering of Remote Fetch Configuration Status (132 ms)
@wso2is/console:     ✓ UTC-4.2 - Test trigger confirguration button click event (28 ms)
@wso2is/console:   console.error
@wso2is/console:     Warning: Received `true` for a non-boolean attribute `compact`.
@wso2is/console:    
@wso2is/console:     If you want to write it to the DOM, pass a string instead: compact="true" or compact={value.toString()}.
@wso2is/console:         in div (created by MenuItem)
@wso2is/console:         in MenuItem (created by RemoteFetchStatus)
@wso2is/console:         in div (created by Menu)
@wso2is/console:         in Menu (created by RemoteFetchStatus)
@wso2is/console:         in RemoteFetchStatus
@wso2is/console:         in Provider
@wso2is/console:       at console.error (../../node_modules/@testing-library/react/dist/act-compat.js:53:34)
@wso2is/console:       at printWarning (../../node_modules/react-dom/cjs/react-dom.development.js:88:30)
@wso2is/console:       at error (../../node_modules/react-dom/cjs/react-dom.development.js:60:5)
@wso2is/console:       at validateProperty$1 (../../node_modules/react-dom/cjs/react-dom.development.js:5557:9)
@wso2is/console:       at warnUnknownProperties (../../node_modules/react-dom/cjs/react-dom.development.js:5595:21)
@wso2is/console:       at validateProperties$2 (../../node_modules/react-dom/cjs/react-dom.development.js:5619:3)
@wso2is/console:       at validatePropertiesInDevelopment (../../node_modules/react-dom/cjs/react-dom.development.js:5662:5)
@wso2is/console:   console.warn
@wso2is/console:     Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
@wso2is/console:    
@wso2is/console:     * Move data fetching code or side effects to componentDidUpdate.
@wso2is/console:     * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
@wso2is/console:     * Rename co
```

Tried increasing the heap memory by setting the env variable `export NODE_OPTIONS=--max-old-space-size=8192`. Still build fails.

**Expected behavior:**
Build should be healthy and I should be able to access console and myaccount applications.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: Mac OSX Catalina 10.15.5
 - Node: Tried 10, 12, 14, 15

**Comment by tharindu-bandara** [comment]
I had an investigation with the help of @brionmario. When checked out to 1.2.83 -> execute `npm clean-all` and try to build, then this issue resolves. So it should be a change introduced lately.

**Comment by brionmario** [comment]
Should be resolved with https://github.com/wso2/product-is/issues/13931.
