### ISSUE TITLE
NPE printed continuously in IS Analytics worker node

### ISSUE THREAD

**Issue by sachiniWettasinghe** [wso2/product-is#11510]
The following error is continuously printed in the IS-Analytics worker node.

`[2021-02-04 20:29:53,634] ERROR {org.wso2.siddhi.core.stream.StreamJunction} - Error in 'IS_ANALYTICS_LONG_SESSION' after consuming events from Stream 'LeadersLastSevenDaysStream', null. Hence, dropping event 'StreamEvent{ timestamp=1612499393625, beforeWindowData=[true], onAfterWindowData=null, outputData=[1611894593625], type=CURRENT, next=null}' java.lang.NullPointerException [2021-02-04 20:29:53,634] ERROR {org.wso2.siddhi.core.stream.StreamJunction} - Error in 'IS_ANALYTICS_LONG_SESSION' after consuming events from Stream 'LeadersLastSevenDaysStream', null. Hence, dropping event 'StreamEvent{ timestamp=1612499393625, beforeWindowData=[true], onAfterWindowData=null, outputData=[1611894593625], type=CURRENT, next=null}' java.lang.NullPointerException  at org.wso2.siddhi.core.table.holder.IndexEventHolder.overwrite(IndexEventHolder.java:243)  at org.wso2.siddhi.core.util.collection.operator.OverwriteTableIndexOperator.tryUpdate(OverwriteTableIndexOperator.java:48)  at org.wso2.siddhi.core.table.InMemoryTable.updateOrAdd(InMemoryTable.java:126)  at org.wso2.siddhi.core.table.Table.updateOrAddEvents(Table.java:317)  at org.wso2.siddhi.core.query.output.callback.UpdateOrInsertTableCallback.send(UpdateOrInsertTableCallback.java:78)  at org.wso2.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:97)  at org.wso2.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:46)  at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98)  at org.wso2.siddhi.core.query.input.stream.join.JoinProcessor.process(JoinProcessor.java:117)  at org.wso2.siddhi.core.query.processor.stream.window.LengthWindowProcessor.process(LengthWindowProcessor.java:137)  at org.wso2.siddhi.core.query.processor.stream.window.WindowProcessor.processEventChunk(WindowProcessor.java:65)  at org.wso2.siddhi.core.query.processor.stream.AbstractStreamProcessor.process(AbstractStreamProcessor.java:123)  at org.wso2.siddhi.core.query.input.stream.join.JoinProcessor.process(JoinProcessor.java:123)  at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:187)  at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:97)  at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:122)  at org.wso2.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:181)  at org.wso2.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:405)  at org.wso2.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)  at org.wso2.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:97)  at org.wso2.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:46)  at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98)  at org.wso2.siddhi.core.query.processor.filter.FilterProcessor.process(FilterProcessor.java:65)  at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:187)  at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:97)  at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:122)  at org.wso2.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:181)  at org.wso2.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:405)  at org.wso2.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)  at org.wso2.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:97)  at org.wso2.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:46)  at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98)  at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:187)  at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:97)  at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:122)  at org.wso2.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:181)  at org.wso2.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:405)  at org.wso2.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)  at org.wso2.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:97)  at org.wso2.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:46)  at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:98)  at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:187)  at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:97)  at org.wso2.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:133)  at org.wso2.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:204)  at org.wso2.siddhi.core.trigger.PeriodicTrigger$1.run(PeriodicTrigger.java:81)  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)  at java.lang.Thread.run(Thread.java:748) `

**Affected Product versions**
IS - 5.9.0
IS analytics - 5.8.0

**Comment by sachiniWettasinghe** [comment]
Duplicate of https://github.com/wso2/product-is/issues/11516.
