### ISSUE TITLE
Error when post a confirmation self up user request

### ISSUE THREAD

**Issue by Ketchup31** [wso2/product-is#11521]
Hello,

When i try to as resent email confirmation I get an error with WSO2is: v5.11.0.17 (Docker).

I did not set any consent and did not checked enable captcha.

Steps to reproduce.
Enable self-registration with email confirmation from the resident idp config of the management console.
Self-register as a new user.
Open mail received with confirmation link
Click on link from the email

```

If clicking the button doesn't seem to work, you can copy and paste the following link into your browser.

https://identity.glab.local/accountrecoveryendpoint/confirmregistration.do?confirmation=0164c804-5c58-437f-90a1-92245578564e&userstoredomain=PRIMARY&username=tata&tenantdomain=carbon.super&callback=https%3A%2F%2Fidentity.glab.local%3A443%2Fauthenticationendpoint%2Flogin.do%3Fclient_id%3DMY_ACCOUNT%26code_challenge%3D3jvvZ8_vnuEL6Cql3lldWGqQWz60_MFurWYIG5BLPig%26code_challenge_method%3DS256%26commonAuthCallerPath%3D%2Foauth2%2Fauthorize%26forceAuth%3Dfalse%26passiveAuth%3Dfalse%26redirect_uri%3Dhttps%3A%2F%2Fidentity.glab.local%2Fmyaccount%2Flogin%26response_mode%3Dform_post%26response_type%3Dcode%26scope%3DSYSTEM+openid%26tenantDomain%3Dcarbon.super%26sessionDataKey%3D005d8383-7728-4136-b47f-24f5ac418aeb%26relyingParty%3DMY_ACCOUNT%26type%3Doidc%26sp%3DMy+Account%26isSaaSApp%3Dtrue%26failedUsername%3Dtoto%26errorCode%3D17005%26authenticators%3DBasicAuthenticator%3ALOCAL%26authFailure%3Dtrue%26authFailureMsg%3Daccount.confirmation.pending

Then, the error hereunder:

[2021-03-26 23:37:17,811] [f4d0f36c-2be6-43c1-89c2-eaef253202d0] DEBUG {org.wso2.carbon.identity.auth.service.handler.HandlerManager} - Created singleton instance for org.wso2.carbon.identity.auth.service.handler.HandlerManager
[2021-03-26 23:37:17,812] [f4d0f36c-2be6-43c1-89c2-eaef253202d0] DEBUG {org.wso2.carbon.identity.auth.service.handler.HandlerManager} - Get first priority handler for the given handler list.
[2021-03-26 23:37:17,813] [f4d0f36c-2be6-43c1-89c2-eaef253202d0] DEBUG {org.wso2.carbon.identity.auth.service.handler.HandlerManager} - Get first priority handler : DefaultAuthenticationManager(org.wso2.carbon.identity.auth.service.AuthenticationManager)
[2021-03-26 23:37:17,814] [f4d0f36c-2be6-43c1-89c2-eaef253202d0] DEBUG {org.wso2.carbon.identity.application.authentication.framework.util.LoginContextManagementUtil} - Service Provider tenant domain: carbon.super
[2021-03-26 23:37:17,814] [f4d0f36c-2be6-43c1-89c2-eaef253202d0] DEBUG {org.wso2.carbon.identity.application.authentication.framework.cache.AuthenticationContextCache} - Found a valid AuthenticationContextCacheEntry corresponding to the session data key : 005d8383-7728-4136-b47f-24f5ac418aeb from the cache.
[2021-03-26 23:37:24,683] [23f30de3-a5c7-470e-86cf-8db3c45ef792] DEBUG {org.wso2.carbon.identity.auth.service.handler.HandlerManager} - Created singleton instance for org.wso2.carbon.identity.auth.service.handler.HandlerManager
[2021-03-26 23:37:24,684] [23f30de3-a5c7-470e-86cf-8db3c45ef792] DEBUG {org.wso2.carbon.identity.auth.service.handler.HandlerManager} - Get first priority handler for the given handler list.
[2021-03-26 23:37:24,684] [23f30de3-a5c7-470e-86cf-8db3c45ef792] DEBUG {org.wso2.carbon.identity.auth.service.handler.HandlerManager} - Get first priority handler : DefaultAuthenticationManager(org.wso2.carbon.identity.auth.service.AuthenticationManager)
[2021-03-26 23:37:24,829] [23f30de3-a5c7-470e-86cf-8db3c45ef792] DEBUG {org.wso2.carbon.identity.mgt.endpoint.util.client.ApiClient} - Initiating api request for
path=https://localhost:9443/api/identity/user/v1.0/validate-code,
method=POST,
headerParams={Accept=application/json, Content-Type=application/json},
formParams=,
accept=application/json,
contentType=application/json
[2021-03-26 23:37:24,835] [b22c6da1-231c-4c0c-8d94-06e639844919] DEBUG {org.wso2.carbon.identity.auth.service.handler.HandlerManager} - Created singleton instance for org.wso2.carbon.identity.auth.service.handler.HandlerManager
[2021-03-26 23:37:24,835] [b22c6da1-231c-4c0c-8d94-06e639844919] DEBUG {org.wso2.carbon.identity.auth.service.handler.HandlerManager} - Get first priority handler for the given handler list.
[2021-03-26 23:37:24,835] [b22c6da1-231c-4c0c-8d94-06e639844919] DEBUG {org.wso2.carbon.identity.auth.service.handler.HandlerManager} - Get first priority handler : DefaultAuthenticationManager(org.wso2.carbon.identity.auth.service.AuthenticationManager)
[2021-03-26 23:37:24,836] [b22c6da1-231c-4c0c-8d94-06e639844919] DEBUG {org.wso2.carbon.identity.auth.valve.AuthenticationValve} - AuthenticationValve hit on secured resource : /api/identity/user/v1.0/validate-code
[2021-03-26 23:37:24,836] [b22c6da1-231c-4c0c-8d94-06e639844919] DEBUG {org.wso2.carbon.identity.auth.service.AuthenticationManager} - Context Path : /api/identity/user/v1.0 started to authenticate.
[2021-03-26 23:37:24,844] [b22c6da1-231c-4c0c-8d94-06e639844919] DEBUG {org.wso2.carbon.identity.auth.service.handler.HandlerManager} - Created singleton instance for org.wso2.carbon.identity.auth.service.handler.HandlerManager
[2021-03-26 23:37:24,844] [b22c6da1-231c-4c0c-8d94-06e639844919] DEBUG {org.wso2.carbon.identity.auth.service.handler.HandlerManager} - Get first priority handler for the given handler list and the context
[2021-03-26 23:37:24,845] [b22c6da1-231c-4c0c-8d94-06e639844919] DEBUG {org.wso2.carbon.identity.auth.service.handler.HandlerManager} - Get first priority handler : ClientAuthentication(org.wso2.carbon.identity.auth.service.handler.impl.ClientAuthenticationHandler)
[2021-03-26 23:37:24,845] [b22c6da1-231c-4c0c-8d94-06e639844919] DEBUG {org.wso2.carbon.identity.auth.service.AuthenticationManager} - AuthenticationHandler found : org.wso2.carbon.identity.auth.service.handler.impl.ClientAuthenticationHandler.
[2021-03-26 23:37:24,845] [b22c6da1-231c-4c0c-8d94-06e639844919] DEBUG {org.wso2.carbon.identity.auth.service.handler.impl.ClientAuthenticationHandler} - Client Authentication Successful for the application: dashboard
[2021-03-26 23:37:24,845] [b22c6da1-231c-4c0c-8d94-06e639844919] DEBUG {org.wso2.carbon.identity.auth.service.AuthenticationManager} - AuthenticationResult : SUCCESS.
[2021-03-26 23:37:24,869] [b22c6da1-231c-4c0c-8d94-06e639844919] DEBUG {org.wso2.carbon.identity.user.endpoint.impl.ResendCodeApiServiceImpl} - Client Error while confirming self up user org.wso2.carbon.identity.recovery.IdentityRecoveryClientException: Invalid Code '%s.'
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:78)
        at org.wso2.carbon.identity.recovery.util.Utils.handleClientException(Utils.java:352)
        at org.wso2.carbon.identity.recovery.store.JDBCRecoveryDataStore.load(JDBCRecoveryDataStore.java:177)
        at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.validateSelfRegistrationCode(UserSelfRegistrationManager.java:658)
        at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.confirmUserSelfRegistration(UserSelfRegistrationManager.java:614)
        at org.wso2.carbon.identity.user.endpoint.impl.ValidateCodeApiServiceImpl.validateCodePost(ValidateCodeApiServiceImpl.java:57)
        at org.wso2.carbon.identity.user.endpoint.ValidateCodeApi.validateCodePost(ValidateCodeApi.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:215)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107)
        at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:98)
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:123)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)

[2021-03-26 23:37:24,951] [23f30de3-a5c7-470e-86cf-8db3c45ef792] DEBUG {org.wso2.carbon.identity.mgt.endpoint.util.client.ApiClient} - Response from the POST request made to url https://localhost:9443/api/identity/user/v1.0/validate-code
Response: status=400, statusMessage=Bad Request

```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
