### ISSUE TITLE
IS Analytics 5.8.0 Dashboard - Error retrieving roles from idp client admin roles.

### ISSUE THREAD

**Issue by Manasha11** [wso2/product-is#11700]
**Describe the issue:**
Getting following error while starting the IS Analytics dashboard server, related to the roles retrieval process from the IS-KM server.

```
[2021-04-28 12:39:38,655] ERROR {org.eclipse.equinox.ds} - [SCR] Exception while activating instance org.wso2.carbon.status.dashboard.core.internal.services.PermissionGrantServiceComponent@612ed333 of component org.wso2.carbon.status.dashboard.core.internal.services.PermissionGrantServiceComponent  java.lang.reflect.InvocationTargetException
	...
Caused by: feign.RetryableException: Read timed out executing GET https://<hostname>/scim2/Groups
	...
	at org.wso2.carbon.analytics.idp.client.external.ExternalIdPClient.getAdminRole(ExternalIdPClient.java:186)
	at org.wso2.carbon.status.dashboard.core.internal.roles.provider.RolesProvider.readSysAdminConfigs(RolesProvider.java:97)
	at org.wso2.carbon.status.dashboard.core.internal.roles.provider.RolesProvider.getSysAdminRolesList(RolesProvider.java:53)
	...
Caused by: java.net.SocketTimeoutException: Read timed out
	...
```
When the External IDP client of the analytics component calls the scim2/groups endpoint to get all the available roles of the IDP side, if there are a number of userstores, the call gets timed out due to a thread death.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
