### ISSUE TITLE
SCIM2 Group patch adding a user to a group without display property returns a 500 response

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#11858]
**Describe the issue:**
If a SCIM2 Group patch request is sent to add members to a group without defining `display` property for a member, it returns a 500 response code.

**How to reproduce:**

```
curl -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"add","value":{"members":[{"display": "sajith","value": "054fcb2c-a175-4b8f-b995-27a4fd0cdf0d"}]}}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Groups/ae87b351-4640-413f-bbae-2e14ff35005c | jq
```
Response:
```
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:Error"
  ],
  "detail": "Error in performing the patch operation on group resource.",
  "status": "500"
}
```
Log:
```
ERROR {org.wso2.charon3.core.protocol.endpoints.AbstractResourceManager} - Error in performing the patch operation on group resource. org.wso2.charon3.core.exceptions.CharonException: Error in performing the patch operation on group resource.
	at org.wso2.charon3.core.protocol.endpoints.GroupResourceManager.updateWithPATCH(GroupResourceManager.java:671)
	at org.wso2.carbon.identity.scim2.provider.resources.GroupResource.processRequest(GroupResource.java:523)
	at org.wso2.carbon.identity.scim2.provider.resources.GroupResource.patchGroup(GroupResource.java:427)
...
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.appendDomainToMembers(SCIMUserManager.java:3381)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.doUpdateGroup(SCIMUserManager.java:2760)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.updateGroup(SCIMUserManager.java:2723)
	at org.wso2.charon3.core.protocol.endpoints.GroupResourceManager.updateWithPATCH(GroupResourceManager.java:651)
	... 59 more
```

**Expected behavior:**
It should return a 400 response code with the reason.

**Environment information** 
 - Product Version: IS 5.10.0

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/product-is/issues/12758
