### ISSUE TITLE
Internal_hostname is not honored in authentication endpoint

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#11878]
**Describe the issue:**
With the introduction of `Internal_hostname` configuration in IS 5.11, it's expected to use the hostname configured in `Internal_hostname` for every internal communication. However, while the Internal_hostname is configured,
```
[server]
Internal_hostname = "internal.com"
```
It's not honored for the backend API requests made by the authentication endpoint and the `hostname` is used to build the URL.

**Workaround**
1. Navigate to <IS_HOME>/repository/deployment/server/webapps/authenticationendpoint/WEB-INF/web.xml and find the element below.
  ```
  <!--context-param>
      <param-name>AuthenticationRESTEndpointURL</param-name>
      <param-value>https://localhost:9443/api/identity/auth/v1.1/</param-value>
  </context-param-->
  ```
2. Uncomment and update it with the `internal_hostname`.
  ```
  <context-param>
      <param-name>AuthenticationRESTEndpointURL</param-name>
      <param-value>https://internal.com:9443/api/identity/auth/v1.1/</param-value>
  </context-param>
  ```

**How to reproduce:**
1. Configure a separate `Internal_hostname` other than the `hostname`
2. Perform the authentication flow with identifier-first as the first step (the identifier-first authenticator makes a backend request to `api/identity/auth/v1.1/context`).
3. Check the hostname used for the backend API requests made by the authentication endpoint.
4. If the `hostname` is `localhost1` and if it's unreachable, the following exception will be thrown.
    ```
    ERROR {org.wso2.carbon.identity.application.authentication.endpoint.util.AuthContextAPIClient} - Sending GET request to URL : https://localhost1:9443/api/identity/auth/v1.1/context/dfb799b7-ae01-4097-95ac-76a2d6a67d85, failed. java.net.UnknownHostException: localhost1
	    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:196)
	    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
	    at java.net.Socket.connect(Socket.java:606)
	    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:287)
	    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	    at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	    at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:292)
	    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:395)
	    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	    at org.wso2.carbon.identity.application.authentication.endpoint.util.AuthContextAPIClient.getContextProperties(AuthContextAPIClient.java:69)
	    at org.apache.jsp.login_jsp._jspService(login_jsp.java:408)
	    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
	    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477)
	    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	    at org.wso2.carbon.identity.application.authentication.endpoint.util.filter.AuthenticationEndpointFilter.doFilter(AuthenticationEndpointFilter.java:87)
	    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	    at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	    at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	    at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	    at org.wso2.carbon.identity.application.authentication.endpoint.util.filter.AuthenticationEndpointFilter.doFilter(AuthenticationEndpointFilter.java:188)
	    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	    at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	    at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107)
	    at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:98)
	    at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	    at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102)
	    at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	    at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	    at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	    at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	    at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	    at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	    at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	    at java.lang.Thread.run(Thread.java:748)
    ```

**Expected behavior:**
If the `Internal_hostname` is configured, it should be used for internal communications, instead of `hostname`.

**Environment information**
 - Product Version: IS 5.11.0

**Related Issues**
#8194

**Comment by mifrazmurthaja** [comment]
The same issue exists when the prompt is used in adaptive functions. Further, #12577 should also be considered when fixing this.

**Comment by nilasini** [comment]
@mifrazmurthaja could u please share the steps you followed to reproduce the issue when using prompt in adaptive script.

**Comment by mifrazmurthaja** [comment]
It's the same steps mentioned above, but need to use the prompt method in the adaptive script [1].

[1] https://is.docs.wso2.com/en/5.11.0/references/adaptive-authentication-js-api-reference/#prompttemplateid-data-eventhandlers

**Comment by nipunaupeksha** [comment]
The same issue occurred with IS 5.11.0.191 and the internal_hostname is not getting honoured due to this following code snippet which uses the server url instead(identity-apps/apps/authentication-portal/src/main/webapp/retry.jsp).
```
if (StringUtils.isBlank(authAPIURL)) {
   authAPIURL = IdentityUtil.getServerURL(SERVER_AUTH_URL, true, true);
}
if (!authAPIURL.endsWith("/")) {
   authAPIURL += "/";
}
authAPIURL += DATA_AUTH_ERROR_URL + errorKey;
```

**Comment by Tiffany-silva** [comment]
A similar issue was observed with IS 5.11.0.289 where the `internal_hostname` is not honoured in the `handle-multiple-sessions.jsp` due to the following,
```
if (StringUtils.isBlank(authAPIURL)) {
        authAPIURL = IdentityUtil.getServerURL("/api/identity/auth/v1.1/", true, true);
    }
    if (!authAPIURL.endsWith("/")) {
        authAPIURL += "/";
    }
    authAPIURL += "context/" + request.getParameter("promptId");
    String contextProperties = AuthContextAPIClient.getContextProperties(authAPIURL);
```
It is important to address and rectify all similar occurences where this issue may have been overlooked to ensure a comprehensive solution.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
