### ISSUE TITLE
[Migration 5.11.0] Add step to disable group and role separation when starting the server in migration mode. 

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#11899]
In the 5.11.0 migration document[1], the step to disable group and role separation when starting the server in migration mode should be added.

i.e. When starting the server with the following command(migration mode).
```
sh wso2server.sh -Dmigrate -Dcomponent=identity
```
The group and role separation feature should be disabled by adding the following configuration.
```
[authorization_manager.properties]
GroupAndRoleSeparationEnabled = false
```
After the migration is complete and the server is started in the normal mode(without -Dmigrate -Dcomponent=identity), the above configuration can be removed. Please note this is an important step, if not carried out the migration would fail(the GroupsAndRolesMigrator step fails).

[1]https://is.docs.wso2.com/en/latest/setup/migrating-to-5110/

**Comment by tharakawijekoon** [comment]
This issue is addressed in document[1]

> Before proceeding with the migration, change the following property to false in the <IS_HOME>/repository/conf/deployment.toml file.
[super_admin]
create_admin_account = false 

[1]https://is.docs.wso2.com/en/latest/setup/migrating-preparing-for-migration/

**Comment by mifrazmurthaja** [comment]
We need to add the property mentioned [above](https://github.com/wso2/product-is/issues/11899#issue-916246773) as well during the migration, otherwise, the migration fails with the exception below.
````
 Could not check authorization. 
Caused by Error occurred while getting hybrid role list of groups : [admin] in domain: PRIMARY org.wso2.carbon.user.core.UserStoreException: Error occurred while getting hybrid role list of groups : [admin] in domain: PRIMARY
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.callSecure(JDBCAuthorizationManager.java:1495)
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.isUserAuthorized(JDBCAuthorizationManager.java:207)
	at org.wso2.carbon.registry.core.jdbc.realm.RegistryAuthorizationManager.isUserAuthorized(RegistryAuthorizationManager.java:200)
	at org.wso2.carbon.registry.core.utils.AuthorizationUtils.authorize(AuthorizationUtils.java:52)
	at org.wso2.carbon.registry.core.jdbc.Repository.addEmptyCollection(Repository.java:1161)
	at org.wso2.carbon.registry.core.jdbc.Repository.add(Repository.java:1013)
	at org.wso2.carbon.registry.core.jdbc.Repository.put(Repository.java:305)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:717)
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73)
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816)
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813)
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:292)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505)
	at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:591)
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840)
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:808)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$900(UserRegistry.java:73)
	at org.wso2.carbon.registry.core.session.UserRegistry$10.run(UserRegistry.java:798)
	at org.wso2.carbon.registry.core.session.UserRegistry$10.run(UserRegistry.java:795)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:795)
	at org.wso2.carbon.identity.application.mgt.ApplicationMgtUtil.storePermissions(ApplicationMgtUtil.java:361)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.doAddApplication(ApplicationManagementServiceImpl.java:1875)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.createApplication(ApplicationManagementServiceImpl.java:2134)
	at org.wso2.carbon.is.migration.util.TenantPortalMigratorUtil.createApplication(TenantPortalMigratorUtil.java:157)
	at org.wso2.carbon.is.migration.util.TenantPortalMigratorUtil.initiatePortals(TenantPortalMigratorUtil.java:113)
	at org.wso2.carbon.is.migration.service.v5100.migrator.TenantPortalMigrator.migrate(TenantPortalMigrator.java:67)
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:85)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.callSecure(JDBCAuthorizationManager.java:1485)
	... 62 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager$2.run(JDBCAuthorizationManager.java:1488)
	... 64 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while getting hybrid role list of groups : [admin] in domain: PRIMARY
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:210)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetRoleListOfUser(AbstractUserStoreManager.java:8443)
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.isUserAuthorized(JDBCAuthorizationManager.java:284)
	... 68 more
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:196)
	... 70 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:199)
	... 72 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while getting hybrid role list of groups : [admin] in domain: PRIMARY
	at org.wso2.carbon.user.core.hybrid.HybridRoleManager.getHybridRoleListOfGroups(HybridRoleManager.java:775)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getHybridRoleListOfGroups(AbstractUserStoreManager.java:1089)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserRoles(AbstractUserStoreManager.java:8474)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetRoleListOfUser(AbstractUserStoreManager.java:8452)
	... 77 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "um_hybrid_group_role" does not exist
  Position: 41
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy53.executeQuery(Unknown Source)
	at org.wso2.carbon.user.core.hybrid.HybridRoleManager.getHybridRoleListOfGroups(HybridRoleManager.java:755)
	... 80 more

[2021-08-06 07:27:04,055] [] ERROR {org.wso2.carbon.is.migration.MigrationClientImpl} - Migration process was stopped. org.wso2.carbon.identity.core.migrate.MigrationClientException: Error occurred while initiating portal for tenant dom.com.
	at org.wso2.carbon.is.migration.service.v5100.migrator.TenantPortalMigrator.migrate(TenantPortalMigrator.java:70)
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:85)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error while storing permissions for application User Portal
	at org.wso2.carbon.identity.application.mgt.ApplicationMgtUtil.storePermissions(ApplicationMgtUtil.java:388)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.doAddApplication(ApplicationManagementServiceImpl.java:1875)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.createApplication(ApplicationManagementServiceImpl.java:2134)
	at org.wso2.carbon.is.migration.util.TenantPortalMigratorUtil.createApplication(TenantPortalMigratorUtil.java:157)
	at org.wso2.carbon.is.migration.util.TenantPortalMigratorUtil.initiatePortals(TenantPortalMigratorUtil.java:113)
	at org.wso2.carbon.is.migration.service.v5100.migrator.TenantPortalMigrator.migrate(TenantPortalMigrator.java:67)
	... 30 more
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: Unable to put resource Could not check authorization. 
Caused by Error occurred while getting hybrid role list of groups : [admin] in domain: PRIMARY
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:299)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505)
	at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:591)
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840)
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:808)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$900(UserRegistry.java:73)
	at org.wso2.carbon.registry.core.session.UserRegistry$10.run(UserRegistry.java:798)
	at org.wso2.carbon.registry.core.session.UserRegistry$10.run(UserRegistry.java:795)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:795)
	at org.wso2.carbon.identity.application.mgt.ApplicationMgtUtil.storePermissions(ApplicationMgtUtil.java:361)
	... 35 more
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: Could not check authorization. 
Caused by Error occurred while getting hybrid role list of groups : [admin] in domain: PRIMARY
	at org.wso2.carbon.registry.core.utils.AuthorizationUtils.authorize(AuthorizationUtils.java:58)
	at org.wso2.carbon.registry.core.jdbc.Repository.addEmptyCollection(Repository.java:1161)
	at org.wso2.carbon.registry.core.jdbc.Repository.add(Repository.java:1013)
	at org.wso2.carbon.registry.core.jdbc.Repository.put(Repository.java:305)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:717)
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73)
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816)
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813)
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:292)
	... 48 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while getting hybrid role list of groups : [admin] in domain: PRIMARY
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.callSecure(JDBCAuthorizationManager.java:1495)
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.isUserAuthorized(JDBCAuthorizationManager.java:207)
	at org.wso2.carbon.registry.core.jdbc.realm.RegistryAuthorizationManager.isUserAuthorized(RegistryAuthorizationManager.java:200)
	at org.wso2.carbon.registry.core.utils.AuthorizationUtils.authorize(AuthorizationUtils.java:52)
	... 59 more
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.callSecure(JDBCAuthorizationManager.java:1485)
	... 62 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager$2.run(JDBCAuthorizationManager.java:1488)
	... 64 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while getting hybrid role list of groups : [admin] in domain: PRIMARY
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:210)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetRoleListOfUser(AbstractUserStoreManager.java:8443)
	at org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager.isUserAuthorized(JDBCAuthorizationManager.java:284)
	... 68 more
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:196)
	... 70 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:199)
	... 72 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while getting hybrid role list of groups : [admin] in domain: PRIMARY
	at org.wso2.carbon.user.core.hybrid.HybridRoleManager.getHybridRoleListOfGroups(HybridRoleManager.java:775)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getHybridRoleListOfGroups(AbstractUserStoreManager.java:1089)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserRoles(AbstractUserStoreManager.java:8474)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetRoleListOfUser(AbstractUserStoreManager.java:8452)
	... 77 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "um_hybrid_group_role" does not exist
  Position: 41
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy53.executeQuery(Unknown Source)
	at org.wso2.carbon.user.core.hybrid.HybridRoleManager.getHybridRoleListOfGroups(HybridRoleManager.java:755)
	... 80 more
````

**Comment by ashendes** [comment]
Tracked in https://github.com/wso2/product-is/issues/14200
