### ISSUE TITLE
Claim Management API does not validate inputs

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12030]
**Describe the issue:**
During claim creation, it allows passing null for claim attributes. But then all the flows start to fail due to null values.

Also, we have marked some of the properties as optional in the swagger doc. But if we don't pass them in the creation request, they get null values and run into the same issue.

**How to reproduce:**
Create a local claim with `null` for `displayOrder` OR not specifying the property.
```
{
  "claimURI": "http://wso2.org/claims/testClaim3",
  "description": "Claim for testing - testClaim3",
  "displayOrder": null,
  "displayName": "testClaim3",
  "readOnly": false,
  "regEx": "",
  "required": false,
  "supportedByDefault": false,
  "attributeMapping": [
    {
      "mappedAttribute": "testClaim3n",
      "userstore": "PRIMARY"
    }
  ],
  "properties": []
}
```
Try viewing user list or profiles in the management console

```
Caused by: java.lang.NumberFormatException: For input string: "null"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.wso2.carbon.identity.claim.metadata.mgt.util.ClaimMetadataUtils.convertLocalClaimToClaimMapping(ClaimMetadataUtils.java:235)
	at org.wso2.carbon.identity.claim.metadata.mgt.DefaultClaimMetadataStore.getAllSupportClaimMappingsByDefault(DefaultClaimMetadataStore.java:549)
	at org.wso2.carbon.identity.user.profile.mgt.UserProfileAdmin.getAllSupportedClaims(UserProfileAdmin.java:609)
	at org.wso2.carbon.identity.user.profile.mgt.UserProfileAdmin.getUserProfiles(UserProfileAdmin.java:267)
	... 141 more
```

**Expected behavior:**
The claim creation should be failed or null values should be replaced with default values

**Environment information**
 - Product Version: IS 5.10.0
 
[1] https://is.docs.wso2.com/en/latest/develop/claim-management-rest-api/#/management/addLocalClaim

**Comment by rksk** [comment]
It is really great if we can address https://github.com/wso2/product-is/issues/7002 as well with the same effort. Because the REST APIs also allowing to create claims without a mapped attribute for PRIMARY. This also could lead to break a production environment due to human error.

**Comment by piyarathnalakmali** [comment]
This is already fixed in the public by [wso2/identity-api-server #119](https://github.com/wso2/identity-api-server/pull/119)
