### ISSUE TITLE
Analytics configuration inconsistency for 5.11.0

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12172]
The doc [1], asks to add the following config.
```
[identity_mgt.analyticsLoginDataPublisherV110] 
enable=true
```
But that name is incorrect and it should be the following.
```
[identity_mgt.analytics_login_data_publisher_v110] 
enable=true
```
Still, this does not work with IS Analytics 5.8.0 due to the following error on the worker side.
```
ERROR {org.wso2.carbon.databridge.core.internal.queue.QueueWorker} - Dropping wrongly formatted event sent org.wso2.carbon.databridge.core.exception.EventConversionException: Error when converting org.wso2.is.analytics.stream.OverallAuthentication:1.1.0 of event bundle with events 1
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.createEventList(ThriftEventConverter.java:188)
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.toEventList(ThriftEventConverter.java:90)
	at org.wso2.carbon.databridge.core.internal.queue.QueueWorker.run(QueueWorker.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.databridge.core.exception.EventConversionException: No StreamDefinition for streamId org.wso2.is.analytics.stream.OverallAuthentication:1.1.0 present in cache 
	at org.wso2.carbon.databridge.receiver.thrift.converter.ThriftEventConverter.createEventList(ThriftEventConverter.java:171)
	... 7 more
```

In the doc [2], it still talks about the following and it works without an issue
```
[identity_mgt.analytics_login_data_publisher] 
enable=true
```

[1] https://is.docs.wso2.com/en/latest/learn/prerequisites-to-publish-statistics/
[2] https://is.docs.wso2.com/en/latest/learn/configuring-identity-analytics/

**Comment by rksk** [comment]
Additionally, the following is not required to add since it is enabled by default in 5.11.0
```
[[event_listener]]
id = "authn_data_publisher_proxy"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityMessageHandler"
name = "org.wso2.carbon.identity.data.publisher.application.authentication.AuthnDataPublisherProxy" 
order = 11 
```

[1] https://is.docs.wso2.com/en/latest/learn/configuring-identity-analytics/
