### ISSUE TITLE
Intermittent failures are observed when adding loading XACML policies in to the server through the SOAP APIs.

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#12198]
**Describe the issue:**

Intermittent failures are observed when adding loading XACML policies into the server through the SOAP APIs.

```
TID: [-1234] [] [2021-07-26 08:26:02,413] [64658a3b-cbb3-4b41-adf1-db453f8ecba6] ERROR {org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule} - Error while persisting policy org.wso2.carbon.registry.core.exceptions.RegistryException: An exception occurred while executing handler chain. null
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2529)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:946)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:591)
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73)
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816)
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813)
	at org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule.addPolicy(RegistryPolicyStoreManageModule.java:95)
	at org.wso2.carbon.identity.entitlement.policy.store.PolicyStoreManager.addPolicy(PolicyStoreManager.java:74)
	at org.wso2.carbon.identity.entitlement.policy.publisher.CarbonPDPPublisher.publish(CarbonPDPPublisher.java:56)
	at org.wso2.carbon.identity.entitlement.policy.publisher.PolicyPublishExecutor.publish(PolicyPublishExecutor.java:200)
	at org.wso2.carbon.identity.entitlement.policy.publisher.PolicyPublishExecutor.run(PolicyPublishExecutor.java:87)
	at org.wso2.carbon.identity.entitlement.policy.publisher.PolicyPublisher.publishPolicy(PolicyPublisher.java:145)
	at org.wso2.carbon.identity.entitlement.EntitlementPolicyAdminService.publishToPDP(EntitlementPolicyAdminService.java:555)
	at org.wso2.carbon.identity.entitlement.EntitlementPolicyAdminService.addOrUpdatePolicy(EntitlementPolicyAdminService.java:786)
	at org.wso2.carbon.identity.entitlement.EntitlementPolicyAdminService.addPolicy(EntitlementPolicyAdminService.java:77)
.....
.....
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.registry.core.caching.CachingHandler.removeFromCache(CachingHandler.java:274)
	at org.wso2.carbon.registry.core.caching.CachingHandler.clearCache(CachingHandler.java:202)
	at org.wso2.carbon.registry.core.caching.CachingHandler.clearCache(CachingHandler.java:98)
	at org.wso2.carbon.registry.core.caching.CachingHandler.put(CachingHandler.java:341)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505)
	... 81 more
```
This issue seems to be occurring when there are a high number of policies in a PAP or PDP and adding a new policy to these collections triggers this behavior.

Policies are added initially from the filesystem and there are around 500+ policies in the system.

**Environment information** **:**
 - Product Version: [IS 5.10.0]

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
