### ISSUE TITLE
Userstore migration fails in IS 5.11

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#12252]
**Describe the issue:**
The secondary userstore migration fails when migrating to IS 5.11 when encrypting the userstore password since the cipher object is initialized [1] without considering the encryption algorithm (AES doesn't use certificates).
````
TID: [-1234] [] [2021-08-05 15:30:08,187] [] ERROR {org.wso2.carbon.is.migration.service.v540.migrator.UserStorePasswordMigrator} - Error while updating secondary user store password for super tenant org.wso2.carbon.core.util.CryptoException: Error during encryption
	at org.wso2.carbon.is.migration.util.SecondaryUserstoreCryptoUtil.encrypt(SecondaryUserstoreCryptoUtil.java:124)
	at org.wso2.carbon.is.migration.util.SecondaryUserstoreCryptoUtil.encrypt(SecondaryUserstoreCryptoUtil.java:138)
	at org.wso2.carbon.is.migration.util.SecondaryUserstoreCryptoUtil.encryptAndBase64Encode(SecondaryUserstoreCryptoUtil.java:152)
	at org.wso2.carbon.is.migration.util.EncryptionUtil.getNewEncryptedUserstorePassword(EncryptionUtil.java:77)
	at org.wso2.carbon.is.migration.service.v540.migrator.UserStorePasswordMigrator.updatePassword(UserStorePasswordMigrator.java:151)
	at org.wso2.carbon.is.migration.service.v540.migrator.UserStorePasswordMigrator.updateSuperTenantConfigs(UserStorePasswordMigrator.java:109)
	at org.wso2.carbon.is.migration.service.v540.migrator.UserStorePasswordMigrator.migrate(UserStorePasswordMigrator.java:60)
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:76)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.security.InvalidKeyException: Key for algorithm RSA not suitable for symmetric enryption.
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineInit(Unknown Source)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineInit(Unknown Source)
	at javax.crypto.Cipher.init(Cipher.java:1249)
	at javax.crypto.Cipher.init(Cipher.java:1189)
	at org.wso2.carbon.is.migration.util.SecondaryUserstoreCryptoUtil.encrypt(SecondaryUserstoreCryptoUtil.java:109)
````
[1] https://github.com/wso2-extensions/identity-migration-resources/blob/v1.0.160/components/org.wso2.is.migration/migration-service/src/main/java/org/wso2/carbon/is/migration/util/SecondaryUserstoreCryptoUtil.java#L109

**How to reproduce:**
Migrate to IS 5.11 having secondary userstores, following the [document](https://is.docs.wso2.com/en/5.11.0/setup/migrating-to-5110/).

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2-extensions/identity-migration-resources/pull/202
