### ISSUE TITLE
Issue with federated user login/jit provisioning when "CheckAccountExist" flag is "false"

### ISSUE THREAD

**Issue by lakshithakasun** [wso2/product-is#12471]
**Describe the issue:**

CheckAccountExist = false

When above configuration in identity.xml file is applied and try a federated user login flow (with or without JIT provisioning) it gives following error.

[2021-09-03 14:56:15,101] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} -   Error while handling post authentication event for user: xxx.yyyy in tenant: ppp.qqq 
org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException:  Error while handling post authentication event for user: xxx.yyyy in tenant: ppp.qqq 
	at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.handlePostAuthentication(AbstractApplicationAuthenticator.java:175) 
	at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.process(AbstractApplicationAuthenticator.java:105) 
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:516) 
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handleResponse(DefaultStepHandler.java:485) 
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:184) 
	at org.wso2.identity.sample.ExtendedStepBasedSequenceHandler.handle(ExtendedStepBasedSequenceHandler.java:362) 
	at org.wso2.identity.sample.ExtendedAuthenticationRequestHandler.handle(ExtendedAuthenticationRequestHandler.java:107) 
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:248) 
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53) 
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647) 
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) 
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) 
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) 
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) 
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) 
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) 
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:72) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) 
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) 
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492) 
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165) 
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104) 
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80) 
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100) 
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:65) 
	at org.wso2.carbon.ui.valve.XSSValve.invoke(XSSValve.java:94) 
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) 
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47) 
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57) 
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47) 
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) 
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159) 
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025) 
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) 
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) 
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452) 
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1201) 
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654) 
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1782) 
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1741) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 
	at java.lang.Thread.run(Thread.java:748) 
Caused by: org.wso2.carbon.identity.event.IdentityEventException: Error while retrieving account lock claim value 
	at org.wso2.carbon.identity.recovery.handler.AccountConfirmationValidationHandler.handleEvent(AccountConfirmationValidationHandler.java:88) 
	at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56) 
	at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.handlePostAuthentication(AbstractApplicationAuthenticator.java:170) 
	... 57 more 
Caused by: org.wso2.carbon.user.core.UserStoreException: 30007 - UserNotFound: User xxx.yyyy does not exist in: PRIMARY 
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:188) 
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValues(AbstractUserStoreManager.java:1005) 
	at org.wso2.carbon.identity.recovery.handler.AccountConfirmationValidationHandler.handleEvent(AccountConfirmationValidationHandler.java:84) 
	... 59 more 
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException 
	at java.security.AccessController.doPrivileged(Native Method) 
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:178) 
	... 61 more 
Caused by: java.lang.reflect.InvocationTargetException 
	at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source) 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.lang.reflect.Method.invoke(Method.java:498) 
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:181) 
	... 63 more 
Caused by: org.wso2.carbon.user.core.UserStoreException: 30007 - UserNotFound: User xxx.yyyy does not exist in: PRIMARY 
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValues(AbstractUserStoreManager.java:1021) 
	... 67 more 

**How to reproduce:**
1. Create a federated IDP
2. Set the federated IDP to a Service provider as the federated authentication under the "Local & Outbound Authentication Configuration"
3. Try to login to the application configured using federated authentication
4. You will see above exception in wso2carbon.log

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [ IS 5.7.0] WUM level - 1629088246185
 - Userstore: [LDAP]

---

### Optional Fields

**Related places that the issue occurs:**
https://github.com/wso2-support/identity-governance/blob/2975b4e3bfaa40ea434f84651964c2be0d125491/components/org.wso2.carbon.identity.recovery/src/main/java/org/wso2/carbon/identity/recovery/handler/AccountConfirmationValidationHandler.java#L78

https://github.com/wso2-support/identity-local-auth-basicauth/blob/b24b5a0cc3d69c04123090909892f96dd74e6554/components/org.wso2.carbon.identity.application.authenticator.basicauth/src/main/java/org/wso2/carbon/identity/application/authenticator/basicauth/BasicAuthenticator.java#L379

**Comment by piraveena** [comment]
@ashendes can you close this issue if all the support and public PRs are merged?

**Comment by piraveena** [comment]
@ShanChathusanda93 can we close this issue if all are done?

**Comment by ShanChathusanda93** [comment]
Latest master pack does not contain the issue. This cannot ne reproduced. @ashendes could you please verify the same? Then we can close the issue.
