### ISSUE TITLE
Supporting PKCS12

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#12616]
**Describe the issue:**
 The carbon.xml has the following comment regarding the Keystore types.

<Type>PKCS12</Type>

When we use PKCS12 Keystore and tested some flows like login to user-portal, SAML and OIDC sample apps, code grant and could not find any issue in them. But when running integration tests by changing all places related to jks to pkcs12, we could see test failures in some OIDC and OAuth2 test cases. In most of the failing test cases, We could see the following error.

```
[ERROR] testSendAuthenticationRequestFromRP2(org.wso2.identity.integration.test.oidc.OIDCAuthCodeGrantSSOTestCase)  Time elapsed: 2.336 s  <<< FAILURE!
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at org.wso2.identity.integration.test.oidc.OIDCAuthCodeGrantSSOTestCase.testSendAuthenticationRequest(OIDCAuthCodeGrantSSOTestCase.java:194)
	at org.wso2.identity.integration.test.oidc.OIDCAuthCodeGrantSSOTestCase.testSendAuthenticationRequestFromRP2(OIDCAuthCodeGrantSSOTestCase.java:148)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at org.wso2.identity.integration.test.oidc.OIDCAuthCodeGrantSSOTestCase.testSendAuthenticationRequest(OIDCAuthCodeGrantSSOTestCase.java:194)
	at org.wso2.identity.integration.test.oidc.OIDCAuthCodeGrantSSOTestCase.testSendAuthenticationRequestFromRP2(OIDCAuthCodeGrantSSOTestCase.java:148)
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at org.wso2.identity.integration.test.oidc.OIDCAuthCodeGrantSSOTestCase.testSendAuthenticationRequest(OIDCAuthCodeGrantSSOTestCase.java:194)
	at org.wso2.identity.integration.test.oidc.OIDCAuthCodeGrantSSOTestCase.testSendAuthenticationRequestFromRP2(OIDCAuthCodeGrantSSOTestCase.java:148)
So it is needed to further check what's the cause for these test failures and decide whether we can say IS support PKCS12.
```

We need to fix this and document this.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
