### ISSUE TITLE
Password policy validation issue when workflow approval is enabled

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12639]
**How to reproduce:**
- Have default values for password regex in userstore (`^[\S]{5,30}$`)
- Enable Password Policy Feature in resident IdP with default values (max length 12 chars)
- Enable workflow approval for self-registration (https://www.youtube.com/watch?v=DZJV1gqSDMc)
- Register a user with a password that contains `13` characters (which violates password policy in resident IdP, but allowed in userstore regex)
- Now try to approve this user

The user vanishes and the workflow status is FAILED. The following log is written.
```
Caused by: org.wso2.carbon.identity.mgt.policy.PolicyViolationException: Password cannot have more than 12 characters
 at org.wso2.carbon.identity.mgt.policy.PolicyRegistry.enforcePasswordPolicies(PolicyRegistry.java:39)
 at org.wso2.carbon.identity.password.policy.handler.PasswordPolicyValidationHandler.handleEvent(PasswordPolicyValidationHandler.java:174)
 ... 82 more
```

This occurs when the user is registered with a password that violates the password policy under the resident identity provider. Because during the user self-registration (with workflows enabled), the password is checked against the PasswordJavaRegEx parameter of the particular userstore. But the policy defined under resident IdP is validated only after the user is actually going to be created after the approval.

**Workaround**
Set password policy in userstore to match with the one in resident IdP or disable the "Enable Password Policy Feature" under resident IdP entirely.
```
<Property name="PasswordJavaRegEx">^((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%&amp;*])).{6,12}$</Property>
<Property name="PasswordJavaScriptRegEx">^((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%&amp;*])).{6,12}$</Property>
<Property name="PasswordJavaRegExViolationErrorMsg">Password pattern policy violated. Password should contain a digit[0-9], a lower case letter[a-z], an upper case letter[A-Z], one of !@#$%&amp;* characters and length between 6-12.</Property>
```

**Expected behavior:**
The password policy defined at the userstore level and also the resident IdP should be evaluated even when the workflow approval is enabled.

**Environment information** 
 - Product Version: IS 5.10.0

**Comment by rksk** [comment]
fixed with https://github.com/wso2/product-is/issues/9698
