### ISSUE TITLE
EmailEventAdapter does not use TLSv1.2 to connect to the SMTP server

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#12701]
**Describe the issue:**
EmailEventAdapter does not use TLSv1.2 to connect to the SMTP server

**How to reproduce:**

- Configure the EmailEventAdapter in <IS_HOME>/repository/conf/output-event-adapters.xml file to use TLSv1.2.
```
<property key="mail.smtp.ssl.protocols">TLSv1.2</property>
```
- Try out a flow that triggers an Email.
- The following error would be observed.
```
javax.mail.MessagingException: Can't send command to SMTP host;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:1420)
	at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:1408)
	at com.sun.mail.smtp.SMTPTransport.ehlo(SMTPTransport.java:847)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:384)
	at javax.mail.Service.connect(Service.java:297)
	at javax.mail.Service.connect(Service.java:156)
	at javax.mail.Service.connect(Service.java:105)
	at javax.mail.Transport.send0(Transport.java:168)
	at javax.mail.Transport.send(Transport.java:98)
	at org.wso2.carbon.event.output.adapter.email.EmailEventAdapter$EmailSender.run(EmailEventAdapter.java:346)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:171)
	at sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98)
	at sun.security.ssl.TransportContext.kickstart(TransportContext.java:220)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:428)
	at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:804)
	at sun.security.ssl.SSLSocketImpl.access$200(SSLSocketImpl.java:73)
	at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1166)
	at com.sun.mail.util.TraceOutputStream.write(TraceOutputStream.java:101)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:1418)
	... 14 more
```

**Expected behavior:**
The above error should not occur and the server should be able to connect to the mail server with tlsv1.2. This issue occurs because the JavaMail version used is 1.4, it needs to be updated to a newer version. In certain versions of IS(eg 5.7.0, 5.10.0), the above issue is not observed.

**Environment information** **:**
 - Product Version: [IS_ 5.8.0]

**Comment by bhagyasakalanka** [comment]
To fix this issue, We update the axiom jar in WSO2IS-5.8.0. Public already has a newer version of axiom. So no need to do any fix for public
