### ISSUE TITLE
Workflow triggering fails in Postgres due to autocommit behavior

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#12854]
**Describe the issue:**
In https://github.com/wso2/product-is/issues/10032, it was suggested to enable defaultAutoCommit for bps data source. 

At [1], the connection is created with `shouldApplyTransaction = false`. Therefore, when it tries to commit the transaction at line no 342, it fails since defaultAutoCommit is enabled.

**How to reproduce:**
- Configure BPS DB in Postgresql 11 with the following configs
```
[bps_database.config]
username = "postgres"
password = "wso2carbon"
url = "jdbc:postgresql://localhost:5432/testdb"
driver = "org.postgresql.Driver"

[bps_database.config.pool_options]
maxActive = "80"
maxWait = "60000"
minIdle = "5"
testOnBorrow = true
validationQuery="SELECT 1; COMMIT"
validationInterval="30000"
defaultAutoCommit=true
removeAbandoned=true
```
- Configure a workflow engagement 
- Try a flow that triggers a workflow
- The workflow is not triggered and the following stack trace is logged

```
ERROR {org.wso2.carbon.identity.core.persistence.JDBCPersistenceManager} - An error occurred while commit transactions. org.postgresql.util.PSQLException: Cannot commit when autoCommit is enabled.
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:866)
	at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:152)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:40)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
	at com.sun.proxy.$Proxy52.commit(Unknown Source)
	at org.wso2.carbon.identity.core.persistence.JDBCPersistenceManager.commitTransaction(JDBCPersistenceManager.java:205)
	at org.wso2.carbon.identity.core.util.IdentityDatabaseUtil.commitTransaction(IdentityDatabaseUtil.java:119)
	at org.wso2.carbon.identity.workflow.mgt.dao.WorkflowDAO.getWorkflowParams(WorkflowDAO.java:338)
```

**Suggested solution**
Change [1] as below.
```
Connection connection = IdentityDatabaseUtil.getDBConnection();
```
So it will use `shouldApplyTransaction=true` and autoCommit will be set to false at [2].

**Environment information**
 - Product Version: 5.11.0
 - Database: Postgresql 11

Note: Can not use Postgresql 12 or 13 due to https://github.com/wso2/product-is/issues/10414

[1] https://github.com/wso2/carbon-identity-framework/blob/7a53e756835492955a295ac1c0b8df905bcff299/components/workflow-mgt/org.wso2.carbon.identity.workflow.mgt/src/main/java/org/wso2/carbon/identity/workflow/mgt/dao/WorkflowDAO.java#L323
[2] https://github.com/wso2/carbon-identity-framework/blob/7a53e756835492955a295ac1c0b8df905bcff299/components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/persistence/JDBCPersistenceManager.java#L175

**Comment by ashensw** [comment]
`IdentityDatabaseUtil.commitTransaction(connection)` [1] should not be needed for this method since this is a SELECT statement. 

[1] https://github.com/wso2/carbon-identity-framework/blob/7a53e756835492955a295ac1c0b8df905bcff299/components/workflow-mgt/org.wso2.carbon.identity.workflow.mgt/src/main/java/org/wso2/carbon/identity/workflow/mgt/dao/WorkflowDAO.java#L342

**Comment by nilasini** [comment]
@ChanikaRuchini Can we close this issue?

**Comment by ChanikaRuchini** [comment]
@nilasini public fix is done. I'll close the issue.
