### ISSUE TITLE
The latest forget-me tool is not working

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#12930]
**Describe the issue:**
When we run the latest forgetMe tool, getting the below errors

Get this error first. By reverting this PR https://github.com/wso2/identity-anonymization-tool/commit/9adc714c2d4eb3945e45f0f4ff3348594dd7f869, was able to sort out the below issue
```

[org.wso2.carbon.config.ConfigProviderFactory] DEBUG : initialize securevault instance from configuration file: /Users/user/Documents/patch/log4j/public/fix/v3/wso2is-5.12.0-alpha10-SNAPSHOT/repository/components/tools/forget-me/conf/../../../../conf/datasources
Exception in thread "main" java.lang.NoClassDefFoundError: org/yaml/snakeyaml/constructor/BaseConstructor
	at org.wso2.carbon.secvault.SecureVaultFactory.getSecureVault(SecureVaultFactory.java:49)
	at org.wso2.carbon.config.ConfigProviderFactory.getSecureVault(ConfigProviderFactory.java:102)
	at org.wso2.carbon.config.ConfigProviderFactory.getConfigProvider(ConfigProviderFactory.java:49)
	at org.wso2.carbon.privacy.forgetme.sql.instructions.DatasourceProcessorConfigReader.readProcessorConfig(DatasourceProcessorConfigReader.java:48)
	at org.wso2.carbon.privacy.forgetme.sql.instructions.DatasourceProcessorConfigReader.readProcessorConfig(DatasourceProcessorConfigReader.java:35)
	at org.wso2.carbon.privacy.forgetme.ConfigReader.loadExtensions(ConfigReader.java:213)
	at org.wso2.carbon.privacy.forgetme.ConfigReader.readSystemConfig(ConfigReader.java:112)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:201)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:141)
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.constructor.BaseConstructor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)


```

After reverting the SnakeYaml related changes, getting the below errors. This could be related to some carbon-Datasource related changes

```
[org.wso2.carbon.secvault.SecureVaultUtils] DEBUG : Loading Secure Vault Configurations from the file: /Users/user/Documents/patch/log4j/public/fix/v4/wso2is-5.12.0-alpha10-SNAPSHOT/repository/components/tools/forget-me/conf/../../../../conf/datasources
Exception in thread "main" org.wso2.carbon.privacy.forgetme.runtime.ForgetMeExecutionException: Error in reading config of the processor : rdbms, from the path : /Users/user/Documents/patch/log4j/public/fix/v4/wso2is-5.12.0-alpha10-SNAPSHOT/repository/components/tools/forget-me/conf/../../../../conf/datasources
	at org.wso2.carbon.privacy.forgetme.ConfigReader.loadExtensions(ConfigReader.java:219)
	at org.wso2.carbon.privacy.forgetme.ConfigReader.readSystemConfig(ConfigReader.java:112)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:201)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:141)
Caused by: org.wso2.carbon.privacy.forgetme.sql.exception.SQLModuleException: Error occurred while initializing the data source.
	at org.wso2.carbon.privacy.forgetme.sql.instructions.DatasourceProcessorConfigReader.readProcessorConfig(DatasourceProcessorConfigReader.java:51)
	at org.wso2.carbon.privacy.forgetme.sql.instructions.DatasourceProcessorConfigReader.readProcessorConfig(DatasourceProcessorConfigReader.java:35)
	at org.wso2.carbon.privacy.forgetme.ConfigReader.loadExtensions(ConfigReader.java:213)
	... 3 more
Caused by: org.wso2.carbon.config.ConfigurationException: Error while loading securevault service
	at org.wso2.carbon.config.ConfigProviderFactory.getSecureVault(ConfigProviderFactory.java:105)
	at org.wso2.carbon.config.ConfigProviderFactory.getConfigProvider(ConfigProviderFactory.java:49)
	at org.wso2.carbon.privacy.forgetme.sql.instructions.DatasourceProcessorConfigReader.readProcessorConfig(DatasourceProcessorConfigReader.java:48)
	... 5 more
Caused by: org.wso2.carbon.secvault.exception.SecureVaultException: Failed to read filepath : /Users/user/Documents/patch/log4j/public/fix/v4/wso2is-5.12.0-alpha10-SNAPSHOT/repository/components/tools/forget-me/conf/../../../../conf/datasources
	at org.wso2.carbon.secvault.SecureVaultUtils.resolveFileToString(SecureVaultUtils.java:228)
	at org.wso2.carbon.secvault.SecureVaultUtils.getSecureVaultConfig(SecureVaultUtils.java:88)
	at org.wso2.carbon.secvault.SecureVaultFactory.getSecureVault(SecureVaultFactory.java:49)
	at org.wso2.carbon.config.ConfigProviderFactory.getSecureVault(ConfigProviderFactory.java:102)
	... 7 more
Caused by: java.io.IOException: Is a directory
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.nio.file.Files.read(Files.java:3105)
	at java.nio.file.Files.readAllBytes(Files.java:3158)

```

**How to reproduce:**

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
Fixed by reverting these two PRs 
https://github.com/wso2/identity-anonymization-tool/pull/149
https://github.com/wso2/identity-anonymization-tool/pull/147
