### ISSUE TITLE
Outbound provisioning manager triggers two POST requests during user creation

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#12944]
**Describe the issue:**
When the user is created through self-sign up flow, the Outbound provisioning manager triggers two POST requests to the external IDP. This happens intermittently due to a race condition.

- The user gets created initially and the outbound provisioning connector triggers the user creation request.
- After the user creation, the listeners that are present in the Identity server update the user's Identity claims such as http://wso2.org/claims/identity/accountState, http://wso2.org/claims/identity/accountLocked, http://wso2.org/claims/identity/lockedReason, etc. 
- Since the user who is created is modified by the listeners, there are multiple provisioning requests received by the outbound provisioning manager to update the last modified time claim.
- If the provisioning thread for user creation has not yet completed when the update request from the listeners reach, then the provisioning identifier would not stored[1] as a result another POST request is triggered[2]

**How to reproduce:**
- Configure outbound provisioning using the doc [3].
- Self-sign up to the server[4].
- Intermittently there would be two POST requests sent to the external IDP.
- one with the full payload having all attributes.
```
{"emails":["tharaka@email.com"],"addresses":[{"type":"country","value":"Sri Lanka"}],"password":"123abc","meta":{"created":"2022-01-07T00:54:43"},"schemas":["urn:scim:schemas:core:1.0"],"name":{"familyName":"Wijekoon","givenName":"Tharaka"},"userName":"PRIMARY/test110"}
```
- second one with no attributes.
```
{"password":"123abc","schemas":["urn:scim:schemas:core:1.0"],"userName":"PRIMARY/test110"}
```
Thereafter the following error would be seen(the entry has already been added when the initial provisioning thread completes).
```
TID: [-1234] [] [2022-01-07 06:24:52,823] [5969a37d-44c9-451a-8372-01627e7666da] ERROR {org.wso2.carbon.identity.provisioning.ProvisioningThread} -  Provisioning for Entity test110 For operation = POST org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error occurred while adding Provisioning entity for tenant -1234
	at org.wso2.carbon.identity.provisioning.dao.ProvisioningManagementDAO.addProvisioningEntity(ProvisioningManagementDAO.java:95)
	at org.wso2.carbon.identity.provisioning.dao.CacheBackedProvisioningMgtDAO.addProvisioningEntity(CacheBackedProvisioningMgtDAO.java:58)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.storeProvisionedEntityIdentifier(ProvisioningThread.java:129)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:83)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_C20 ON PUBLIC.IDP_PROVISIONING_ENTITY(ENTITY_TYPE, TENANT_ID, ENTITY_LOCAL_USERSTORE, ENTITY_NAME, PROVISIONING_CONFIG_ID) VALUES 87"; SQL statement:
INSERT INTO IDP_PROVISIONING_ENTITY (PROVISIONING_CONFIG_ID, ENTITY_TYPE, ENTITY_LOCAL_USERSTORE, ENTITY_NAME, ENTITY_VALUE, TENANT_ID, ENTITY_LOCAL_ID) VALUES (?, ?, ?, ?, ?, ?,?) [23505-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:220)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:196)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:546)
	at org.h2.command.dml.Insert.insertRows(Insert.java:180)
	at org.h2.command.dml.Insert.update(Insert.java:132)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy55.execute(Unknown Source)
	at org.wso2.carbon.identity.provisioning.dao.ProvisioningManagementDAO.addProvisioningEntity(ProvisioningManagementDAO.java:90)
	... 8 more
``` 
**Expected behavior:**
There should only be a single POST request sent to the external IDP for user creation. 

**Environment information**
 - Product Version: [5.11.0]

**Related issues:**
https://github.com/wso2/product-is/issues/12926

[1]https://github.com/wso2/carbon-identity-framework/blob/master/components/provisioning/org.wso2.carbon.identity.provisioning/src/main/java/org/wso2/carbon/identity/provisioning/ProvisioningThread.java#L83
[2]https://github.com/wso2/carbon-identity-framework/blob/master/components/provisioning/org.wso2.carbon.identity.provisioning/src/main/java/org/wso2/carbon/identity/provisioning/OutboundProvisioningManager.java#L439-L440
[3]https://is.docs.wso2.com/en/latest/learn/outbound-provisioning-with-scim/
[4]https://is.docs.wso2.com/en/latest/learn/self-registration/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
