### ISSUE TITLE
Error logs on terminal when User login to user-portal in 5.10.0 latest update with DB2 Identity DB

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#13146]
**Describe the issue:**

- Configure IS 5.10.0 latest update with DB2 

- Do this alternation in DB2:

```
alter table IDN_AUTH_SESSION_APP_INFO add USER_ID varchar(100)
```
```
alter table IDN_AUTH_SESSION_APP_INFO add IDP_NAME varchar(100)
```

- Start IS and tries to log in to user-portal.
- User will be logged in, records will be added to IDN_AUTH_SESSION_APP_INFO table also.
- But the following error get printed in the terminal

```
[2022-02-22 13:39:02,200] [78df47eb-e362-494b-9e14-4481daa016d4] ERROR {org.wso2.carbon.identity.rest.api.user.application.v1.core.ApplicationService} - errorCode: APP-15001 | message: Server Encountered an error while retrieving applications. org.wso2.carbon.identity.application.common.IdentityApplicationManagementServerException: Error while getting application basic information for discoverable applications in tenantDomain: carbon.super
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getDiscoverableApplicationBasicInfo(ApplicationDAOImpl.java:4879)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getDiscoverableApplicationBasicInfo(ApplicationDAOImpl.java:4684)
	at org.wso2.carbon.identity.application.mgt.dao.impl.CacheBackedApplicationDAO.getDiscoverableApplicationBasicInfo(CacheBackedApplicationDAO.java:406)
	at org.wso2.carbon.identity.application.mgt.internal.impl.DiscoverableApplicationManagerImpl.getDiscoverableApplicationBasicInfo(DiscoverableApplicationManagerImpl.java:38)
	at org.wso2.carbon.identity.rest.api.user.application.v1.core.ApplicationService.getApplications(ApplicationService.java:106)
	at org.wso2.carbon.identity.rest.api.user.application.v1.impl.MeApiServiceImpl.getApplications(MeApiServiceImpl.java:44)
	at org.wso2.carbon.identity.rest.api.user.application.v1.MeApi.getApplications(MeApi.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:125)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:59)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:124)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: [jcc][10145][10844][4.9.78] Invalid parameter 2: Parameter index is out of range. ERRORCODE=-4461, SQLSTATE=42815
	at com.ibm.db2.jcc.am.fd.a(fd.java:676)
	at com.ibm.db2.jcc.am.fd.a(fd.java:60)
	at com.ibm.db2.jcc.am.fd.a(fd.java:103)
	at com.ibm.db2.jcc.am.fn.e(fn.java:5021)
	at com.ibm.db2.jcc.am.fn.d(fn.java:5014)
	at com.ibm.db2.jcc.am.fn.c(fn.java:933)
	at com.ibm.db2.jcc.am.fn.setInt(fn.java:926)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy57.setInt(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.NamedPreparedStatement.setInt(NamedPreparedStatement.java:127)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getDiscoverableApplicationBasicInfo(ApplicationDAOImpl.java:4869)
	... 59 more

```
---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
