### ISSUE TITLE
Getting CryptoException: An error occurred while encrypting data

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13154]
**Describe the issue:**
Getting CryptoException: Error occurred while initializing and encrypting using Cipher object with algorithm: 'AES/GCM/NoPadding when trying to up the latest 5.11.0 pack on top of Almalinux latest OS

**Environment**
AlmaLinux Latest OS
jdk1.8.0_131
maven 5.14.0-1024-oem
5.11.0 latest wum pack (wso2is-5.11.0-55731413-22fd-4d9d-ad77-82c53f7e09a5)

**Note**
This issue was not observed with jdk-11.0.13. This could be reproduced with jdk1.8.0_131. 
Also this issue was not observed with jdk 8 upper version jdk1.8.0_291

**How to reproduce:**
1. Setup AlmaLinux latest version with a docker image
2. Install JDK 1.8 and setup JAVA_HOME
3. Get a latest 5.11.0 pack (wso2is-5.11.0-55731413-22fd-4d9d-ad77-82c53f7e09a5)
4. Navigate to product-home/bin
5. Run the sh wso2server.sh file

**Observation**

Getting the below exception in the backend console when the server is starting up

```
[2022-02-23 21:43:35,131] []  INFO {org.wso2.carbon.identity.oauth.uma.xacml.service.internal.AppUMAServiceComponents} - XACML UMA Handler activated successfully.
[2022-02-23 21:43:35,380] []  INFO {org.wso2.carbon.identity.oauth.config.OAuthServerConfiguration} - The default OAuth token issuer will be used. No custom token generator is set.
[2022-02-23 21:43:36,034] [] ERROR {org.wso2.carbon.identity.workflow.impl.internal.WorkflowImplServiceComponent} - Error occured while adding default bps profile. org.wso2.carbon.identity.workflow.impl.WorkflowImplException: Error while encrypting the passwords of BPS Profile: embeded_bps
	at org.wso2.carbon.identity.workflow.impl.dao.BPSProfileDAO.addProfile(BPSProfileDAO.java:61)
	at org.wso2.carbon.identity.workflow.impl.WorkflowImplServiceImpl.addBPSProfile(WorkflowImplServiceImpl.java:89)
	at org.wso2.carbon.identity.workflow.impl.internal.WorkflowImplServiceComponent.addDefaultBPSProfile(WorkflowImplServiceComponent.java:146)
	at org.wso2.carbon.identity.workflow.impl.internal.WorkflowImplServiceComponent.activate(WorkflowImplServiceComponent.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:1071)
	at org.wso2.carbon.identity.workflow.mgt.internal.WorkflowMgtServiceComponent.activate(WorkflowMgtServiceComponent.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: org.wso2.carbon.core.util.CryptoException: An error occurred while encrypting data.
	at org.wso2.carbon.core.util.CryptoUtil.encrypt(CryptoUtil.java:146)
	at org.wso2.carbon.core.util.CryptoUtil.encrypt(CryptoUtil.java:160)
	at org.wso2.carbon.core.util.CryptoUtil.encryptAndBase64Encode(CryptoUtil.java:242)
	at org.wso2.carbon.identity.workflow.impl.dao.BPSProfileDAO.encryptPassword(BPSProfileDAO.java:282)
	at org.wso2.carbon.identity.workflow.impl.dao.BPSProfileDAO.addProfile(BPSProfileDAO.java:59)
	... 75 more
Caused by: org.wso2.carbon.crypto.api.CryptoException: Error occurred while initializing and encrypting using Cipher object with algorithm: 'AES/GCM/NoPadding'.
	at org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider.encryptWithGCMMode(SymmetricKeyInternalCryptoProvider.java:246)
	at org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider.encrypt(SymmetricKeyInternalCryptoProvider.java:168)
	at org.wso2.carbon.crypto.impl.DefaultCryptoService.encrypt(DefaultCryptoService.java:534)
	at org.wso2.carbon.core.util.CryptoUtil.encrypt(CryptoUtil.java:144)
	... 79 more
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.init(Cipher.java:1393)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider.encryptWithGCMMode(SymmetricKeyInternalCryptoProvider.java:232)
	... 82 more

[2022-02-23 21:43:36,740] []  INFO {org.wso2.carbon.identity.local.auth.api.core.internal.AuthAPIServiceComponent} - Auth API Service Component  is activated.
[2022-02-23 21:43:37,404] []  INFO {org.wso2.carbon.identity.application.authentication.framework.store.SessionDataStore} - Thread pool size for temporary authentication context data delete task: 20
[2022-02-23 21:43:38,423] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher deployment held back and in inactive state :EmailPublisher.xml, Stream validation exception : Stream id_gov_notify_stream:1.0.0 does not exist
[2022-02-23 21:43:38,438] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration deleted from the file system : IsAnalytics-Publisher-wso2event-AuthenticationData-1.1.0.xml
[2022-02-23 21:43:38,438] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher undeployed successfully : IsAnalytics-Publisher-wso2event-AuthenticationData-1.1.0.xml
[2022-02-23 21:43:38,439] [] ERROR {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Unable to decrypt the encrypted field: password for adaptor type: wso2event
[2022-02-23 21:43:38,459] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration saved in the filesystem : IsAnalytics-Publisher-wso2event-AuthenticationData-1.1.0.xml
[2022-02-23 21:43:38,462] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher deployment held back and in inactive state :IsAnalytics-Publisher-wso2event-AuthenticationData-1.1.0.xml, Stream validation exception : Stream org.wso2.is.analytics.stream.OverallAuthentication:1.1.0 does not exist
[2022-02-23 21:43:38,463] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration deleted from the file system : IsAnalytics-Publisher-wso2event-AuthenticationData.xml
[2022-02-23 21:43:38,463] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher undeployed successfully : IsAnalytics-Publisher-wso2event-AuthenticationData.xml
[2022-02-23 21:43:38,464] [] ERROR {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Unable to decrypt the encrypted field: password for adaptor type: wso2event
[2022-02-23 21:43:38,466] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration saved in the filesystem : IsAnalytics-Publisher-wso2event-AuthenticationData.xml
[2022-02-23 21:43:38,467] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher deployment held back and in inactive state :IsAnalytics-Publisher-wso2event-AuthenticationData.xml, Stream validation exception : Stream org.wso2.is.analytics.stream.OverallAuthentication:1.0.0 does not exist
[2022-02-23 21:43:38,467] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration deleted from the file system : IsAnalytics-Publisher-wso2event-OauthTokenIssueRefresh.xml
[2022-02-23 21:43:38,468] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher undeployed successfully : IsAnalytics-Publisher-wso2event-OauthTokenIssueRefresh.xml
[2022-02-23 21:43:38,468] [] ERROR {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Unable to decrypt the encrypted field: password for adaptor type: wso2event
[2022-02-23 21:43:38,471] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration saved in the filesystem : IsAnalytics-Publisher-wso2event-OauthTokenIssueRefresh.xml
[2022-02-23 21:43:38,472] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher deployment held back and in inactive state :IsAnalytics-Publisher-wso2event-OauthTokenIssueRefresh.xml, Stream validation exception : Stream org.wso2.is.analytics.stream.OauthTokenIssuance:1.0.0 does not exist
[2022-02-23 21:43:38,472] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration deleted from the file system : IsAnalytics-Publisher-wso2event-OauthTokenRevocation.xml
[2022-02-23 21:43:38,473] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher undeployed successfully : IsAnalytics-Publisher-wso2event-OauthTokenRevocation.xml
[2022-02-23 21:43:38,473] [] ERROR {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Unable to decrypt the encrypted field: password for adaptor type: wso2event
[2022-02-23 21:43:38,476] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration saved in the filesystem : IsAnalytics-Publisher-wso2event-OauthTokenRevocation.xml
[2022-02-23 21:43:38,477] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher deployment held back and in inactive state :IsAnalytics-Publisher-wso2event-OauthTokenRevocation.xml, Stream validation exception : Stream org.wso2.is.analytics.stream.OauthTokenRevocation:1.0.0 does not exist
[2022-02-23 21:43:38,478] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration deleted from the file system : IsAnalytics-Publisher-wso2event-OauthTokenValidation.xml
[2022-02-23 21:43:38,478] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher undeployed successfully : IsAnalytics-Publisher-wso2event-OauthTokenValidation.xml
[2022-02-23 21:43:38,479] [] ERROR {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Unable to decrypt the encrypted field: password for adaptor type: wso2event
[2022-02-23 21:43:38,481] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration saved in the filesystem : IsAnalytics-Publisher-wso2event-OauthTokenValidation.xml
[2022-02-23 21:43:38,482] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher deployment held back and in inactive state :IsAnalytics-Publisher-wso2event-OauthTokenValidation.xml, Stream validation exception : Stream org.wso2.is.analytics.stream.OauthTokenValidation:1.0.0 does not exist
[2022-02-23 21:43:38,483] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration deleted from the file system : IsAnalytics-Publisher-wso2event-RoleData.xml
[2022-02-23 21:43:38,484] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher undeployed successfully : IsAnalytics-Publisher-wso2event-RoleData.xml
[2022-02-23 21:43:38,485] [] ERROR {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Unable to decrypt the encrypted field: password for adaptor type: wso2event
[2022-02-23 21:43:38,489] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration saved in the filesystem : IsAnalytics-Publisher-wso2event-RoleData.xml
[2022-02-23 21:43:38,490] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher deployment held back and in inactive state :IsAnalytics-Publisher-wso2event-RoleData.xml, Stream validation exception : Stream org.wso2.is.analytics.stream.OverallRoleData:1.0.0 does not exist
[2022-02-23 21:43:38,491] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration deleted from the file system : IsAnalytics-Publisher-wso2event-SessionData.xml
[2022-02-23 21:43:38,492] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher undeployed successfully : IsAnalytics-Publisher-wso2event-SessionData.xml
[2022-02-23 21:43:38,492] [] ERROR {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Unable to decrypt the encrypted field: password for adaptor type: wso2event
[2022-02-23 21:43:38,496] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration saved in the filesystem : IsAnalytics-Publisher-wso2event-SessionData.xml
[2022-02-23 21:43:38,497] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher deployment held back and in inactive state :IsAnalytics-Publisher-wso2event-SessionData.xml, Stream validation exception : Stream org.wso2.is.analytics.stream.OverallSession:1.0.0 does not exist
[2022-02-23 21:43:38,498] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration deleted from the file system : IsAnalytics-Publisher-wso2event-UserData.xml
[2022-02-23 21:43:38,498] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher undeployed successfully : IsAnalytics-Publisher-wso2event-UserData.xml
[2022-02-23 21:43:38,498] [] ERROR {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Unable to decrypt the encrypted field: password for adaptor type: wso2event
[2022-02-23 21:43:38,501] []  INFO {org.wso2.carbon.event.publisher.core.internal.util.helper.EventPublisherConfigurationFilesystemInvoker} - Event Publisher configuration saved in the filesystem : IsAnalytics-Publisher-wso2event-UserData.xml
[2022-02-23 21:43:38,502] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher deployment held back and in inactive state :IsAnalytics-Publisher-wso2event-UserData.xml, Stream validation exception : Stream org.wso2.is.analytics.stream.OverallUserData:1.0.0 does not exist
[2022-02-23 21:43:38,512] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher undeployed successfully : EmailPublisher.xml
[2022-02-23 21:43:38,520] []  INFO {org.wso2.carbon.event.stream.core.internal.EventJunction} - WSO2EventConsumer added to the junction. Stream:id_gov_notify_stream:1.0.0
[2022-02-23 21:43:38,524] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher configuration successfully deployed and in active state : EmailPublisher
[2022-02-23 21:43:38,525] []  INFO {org.wso2.carbon.event.stream.core.EventStreamDeployer} - Stream definition is deployed successfully  : id_gov_notify_stream:1.0.0
[2022-02-23 21:43:38,525] []  INFO {org.wso2.carbon.event.stream.core.EventStreamDeployer} - Stream definition is deployed successfully  : id_gov_sms_notify_stream:1.0.0
[2022-02-23 21:43:38,528] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher undeployed successfully : IsAnalytics-Publisher-wso2event-OauthTokenIssueRefresh.xml
[2022-02-23 21:43:38,530] []  INFO {org.wso2.carbon.event.stream.core.internal.EventJunction} - WSO2EventConsumer added to the junction. Stream:org.wso2.is.analytics.stream.OauthTokenIssuance:1.0.0
[2022-02-23 21:43:38,533] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher configuration successfully deployed and in active state : IsAnalytics-Publisher-wso2event-OauthTokenIssueRefresh
[2022-02-23 21:43:38,534] []  INFO {org.wso2.carbon.event.stream.core.EventStreamDeployer} - Stream definition is deployed successfully  : org.wso2.is.analytics.stream.OauthTokenIssuance:1.0.0
[2022-02-23 21:43:38,535] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher undeployed successfully : IsAnalytics-Publisher-wso2event-OauthTokenRevocation.xml
[2022-02-23 21:43:38,536] []  INFO {org.wso2.carbon.event.stream.core.internal.EventJunction} - WSO2EventConsumer added to the junction. Stream:org.wso2.is.analytics.stream.OauthTokenRevocation:1.0.0
[2022-02-23 21:43:38,536] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher configuration successfully deployed and in active state : IsAnalytics-Publisher-wso2event-OauthTokenRevocation
[2022-02-23 21:43:38,537] []  INFO {org.wso2.carbon.event.stream.core.EventStreamDeployer} - Stream definition is deployed successfully  : org.wso2.is.analytics.stream.OauthTokenRevocation:1.0.0
[2022-02-23 21:43:38,538] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher undeployed successfully : IsAnalytics-Publisher-wso2event-OauthTokenValidation.xml
[2022-02-23 21:43:38,539] []  INFO {org.wso2.carbon.event.stream.core.internal.EventJunction} - WSO2EventConsumer added to the junction. Stream:org.wso2.is.analytics.stream.OauthTokenValidation:1.0.0
[2022-02-23 21:43:38,539] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher configuration successfully deployed and in active state : IsAnalytics-Publisher-wso2event-OauthTokenValidation
[2022-02-23 21:43:38,540] []  INFO {org.wso2.carbon.event.stream.core.EventStreamDeployer} - Stream definition is deployed successfully  : org.wso2.is.analytics.stream.OauthTokenValidation:1.0.0
[2022-02-23 21:43:38,541] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher undeployed successfully : IsAnalytics-Publisher-wso2event-AuthenticationData.xml
[2022-02-23 21:43:38,543] []  INFO {org.wso2.carbon.event.stream.core.internal.EventJunction} - WSO2EventConsumer added to the junction. Stream:org.wso2.is.analytics.stream.OverallAuthentication:1.0.0
[2022-02-23 21:43:38,543] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher configuration successfully deployed and in active state : IsAnalytics-Publisher-wso2event-AuthenticationData
[2022-02-23 21:43:38,543] []  INFO {org.wso2.carbon.event.stream.core.EventStreamDeployer} - Stream definition is deployed successfully  : org.wso2.is.analytics.stream.OverallAuthentication:1.0.0
[2022-02-23 21:43:38,545] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher undeployed successfully : IsAnalytics-Publisher-wso2event-AuthenticationData-1.1.0.xml
[2022-02-23 21:43:38,546] []  INFO {org.wso2.carbon.event.stream.core.internal.EventJunction} - WSO2EventConsumer added to the junction. Stream:org.wso2.is.analytics.stream.OverallAuthentication:1.1.0
[2022-02-23 21:43:38,547] []  INFO {org.wso2.carbon.event.publisher.core.EventPublisherDeployer} - Event Publisher configuration successfully deployed and in active state : IsAnalytics-Publisher-wso2event-AuthenticationData-1.1.0
[2022-02-23 21:43:38,547] []  INFO {org.wso2.carbon.event.stream.core.EventStreamDeployer} - Stream definition is deployed successfully  : org.wso2.is.analytics.stream.OverallAuthentication:1.1.0


```
Attaching the wso2carbon.log for further reference

[wso2carbon.log](https://github.com/wso2/product-is/files/8127997/wso2carbon.log)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
