### ISSUE TITLE
Fail to start carbon server java.io.FileNotFoundException: Server startup script not found when running integration tests

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13155]
**Description**
Integration test suite run fails with error Fail to start carbon server java.io.FileNotFoundException: Server startup script not found when running integration tests against Almalinux latest OS

**Environment**
AlmaLinux Latest OS
jdk1.8.0_131
maven 5.14.0-1024-oem
5.11.0 latest wum pack (wso2is-5.11.0-55731413-22fd-4d9d-ad77-82c53f7e09a5)

**How to reproduce:**

1. Setup AlmaLinux latest version with a docker image
2. Install JDK 1.8 and setup JAVA_HOME
3. Get a latest 5.11.0 pack (wso2is-5.11.0-55731413-22fd-4d9d-ad77-82c53f7e09a5)
4. Install maven
5. Build the repositories carbon, kernel,orbit,identity-inbound-auth-oauth to get the dependencies
6. Clone product-is support branch for 5.11.0
7. Execute mvn clean install -Dmaven.test.skip=true from root pom
8. Replace the pack generated in /modules/distribution/target with a latest wum updated 5.11.0 pack
9. Navigate to modules/integration/tests-integration/tests-backend
10. Execute nohup mvn clean install 

`Downloaded from wso2-nexus: https://maven.wso2.org/nexus/content/groups/wso2-public/org/apache/maven/surefire/surefire-testng/2.22.1/surefire-testng-2.22.1.jar (44 kB at 24 kB/s)
Downloaded from wso2-nexus: https://maven.wso2.org/nexus/content/groups/wso2-public/org/apache/maven/surefire/surefire-testng-utils/2.22.1/surefire-testng-utils-2.22.1.jar (27 kB at 17 kB/s)
Downloaded from wso2-nexus: https://maven.wso2.org/nexus/content/groups/wso2-public/org/apache/maven/surefire/surefire-grouper/2.22.1/surefire-grouper-2.22.1.jar (40 kB at 23 kB/s)
Downloaded from wso2-nexus: https://maven.wso2.org/nexus/content/groups/wso2-public/org/apache/maven/surefire/common-java5/2.22.1/common-java5-2.22.1.jar (51 kB at 28 kB/s)
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/.m2/repository/org/apache/activemq/activemq-all/5.9.1/activemq-all-5.9.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/.m2/repository/org/slf4j/slf4j-log4j12/1.7.28/slf4j-log4j12-1.7.28.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/.m2/repository/org/slf4j/slf4j-simple/1.7.28/slf4j-simple-1.7.28.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/.m2/repository/slf4j/wso2/slf4j/1.5.10.wso2v1/slf4j-1.5.10.wso2v1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
INFO  [org.wso2.carbon.automation.extensions.servers.carbonserver.CarbonServerManager] - Extracting carbon zip file.. 
ERROR [org.wso2.carbon.automation.extensions.servers.carbonserver.CarbonServerExtension] - Fail to start carbon server 
java.io.FileNotFoundException: Server startup script not found at /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/carbontmp1645642024900/wso2is-5.11.0/bin
	at org.wso2.carbon.automation.engine.frameworkutils.TestFrameworkUtils.getStartupScriptFileName(TestFrameworkUtils.java:78)
	at org.wso2.carbon.automation.extensions.servers.carbonserver.CarbonServerManager.instrumentForCoverage(CarbonServerManager.java:427)
	at org.wso2.carbon.automation.extensions.servers.carbonserver.CarbonServerManager.setUpCarbonHome(CarbonServerManager.java:212)
	at org.wso2.carbon.automation.extensions.servers.carbonserver.TestServerManager.startServer(TestServerManager.java:107)
	at org.wso2.carbon.automation.extensions.servers.carbonserver.CarbonServerExtension.onExecutionStart(CarbonServerExtension.java:50)
	at org.wso2.identity.integration.common.extension.server.IdentityServerExtension.onExecutionStart(IdentityServerExtension.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.automation.engine.extensions.TestNGExtensionExecutor.executeExtensible(TestNGExtensionExecutor.java:75)
	at org.wso2.carbon.automation.engine.testlisteners.TestExecutionListener.onExecutionStart(TestExecutionListener.java:47)
	at org.testng.TestNG.runExecutionListeners(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:983)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
ERROR [org.wso2.carbon.automation.engine.testlisteners.TestExecutionListener] - Execution error occurred in TestExecutionListener:-
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.automation.engine.extensions.TestNGExtensionExecutor.executeExtensible(TestNGExtensionExecutor.java:75)
	at org.wso2.carbon.automation.engine.testlisteners.TestExecutionListener.onExecutionStart(TestExecutionListener.java:47)
	at org.testng.TestNG.runExecutionListeners(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:983)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.RuntimeException: Fail to start carbon server 
	at org.wso2.carbon.automation.extensions.servers.carbonserver.CarbonServerExtension.handleException(CarbonServerExtension.java:70)
	at org.wso2.carbon.automation.extensions.servers.carbonserver.CarbonServerExtension.onExecutionStart(CarbonServerExtension.java:54)
	at org.wso2.identity.integration.common.extension.server.IdentityServerExtension.onExecutionStart(IdentityServerExtension.java:56)
	... 15 more
Caused by: java.io.FileNotFoundException: Server startup script not found at /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/carbontmp1645642024900/wso2is-5.11.0/bin
	at org.wso2.carbon.automation.engine.frameworkutils.TestFrameworkUtils.getStartupScriptFileName(TestFrameworkUtils.java:78)
	at org.wso2.carbon.automation.extensions.servers.carbonserver.CarbonServerManager.instrumentForCoverage(CarbonServerManager.java:427)
	at org.wso2.carbon.automation.extensions.servers.carbonserver.CarbonServerManager.setUpCarbonHome(CarbonServerManager.java:212)
	at org.wso2.carbon.automation.extensions.servers.carbonserver.TestServerManager.startServer(TestServerManager.java:107)
	at org.wso2.carbon.automation.extensions.servers.carbonserver.CarbonServerExtension.onExecutionStart(CarbonServerExtension.java:50)
	... 16 more
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:11 min
[INFO] Finished at: 2022-02-23T18:47:09Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project org.wso2.carbon.identity.integration.backend.test: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] Error on initializing test environment 
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Error on initializing test environment 
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:656)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] Scanning for projects...
[INFO] 
[INFO] ---< org.wso2.is:org.wso2.carbon.identity.integration.backend.test >----
[INFO] Building Identity Test Back-end Module 5.11.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] Deleting /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.6.0:process (default) @ org.wso2.carbon.identity.integration.backend.test ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Preparing remote bundle org.apache:apache-jar-resource-bundle:1.4
[INFO] Copying 3 resources from 1 bundle.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ org.wso2.carbon.identity.integration.backend.test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/shanika/product-is/modules/integration/tests-integration/tests-backend/src/main/resources
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:copy-resources (copy-resources-jks) @ org.wso2.carbon.identity.integration.backend.test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/tobeCopied/wso2is-5.11.0/repository/resources/security
[INFO] 
[INFO] --- maven-resources-plugin:2.6:copy-resources (copy-axis2files) @ org.wso2.carbon.identity.integration.backend.test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/tobeCopied/wso2is-5.11.0/repository/conf/axis2
[INFO] 
[INFO] --- maven-resources-plugin:2.6:copy-resources (copy-resources-mar) @ org.wso2.carbon.identity.integration.backend.test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/tobeCopied/wso2is-5.11.0/repository/deployment/client/modules
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:copy-dependencies (default) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] Copying emma-2.1.5320.jar to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/emma/emma-2.1.5320.jar
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:copy-dependencies (copy-secVerifier) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] Copying SecVerifier-4.6.1.aar to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/security-verifier/SecVerifier.aar
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:copy-dependencies (copy­jacoco­dependencies) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] Copying org.jacoco.agent-0.8.2-runtime.jar to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/jacoco/org.jacoco.agent-0.8.2-runtime.jar
[INFO] Copying org.jacoco.agent-0.8.4.jar to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/jacoco/org.jacoco.agent-0.8.4.jar
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:unpack (unpack-mar-jks) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] Configured Artifact: org.wso2.is:wso2is:5.11.0:zip
[INFO] Unpacking /root/.m2/repository/org/wso2/is/wso2is/5.11.0/wso2is-5.11.0.zip to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/tobeCopied with includes "**/*.jks,**/*.mar,**/axis2_client.xml" and excludes ""
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:copy-dependencies (copy-travelocity) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] Copying org.wso2.sample.is.sso.agent-4.3.5.war to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/test-classes/samples/org.wso2.sample.is.sso.agent.war
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:copy-dependencies (copy-playground2) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] Copying playground2-4.3.5.war to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/test-classes/samples/playground2.war
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:copy-dependencies (copy-passivests) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] Copying PassiveSTSSampleApp-4.3.5.war to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/test-classes/samples/PassiveSTSSampleApp.war
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:unpack (unpack-travelocity-openid) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] Configured Artifact: org.wso2.samples.is:org.wso2.sample.is.sso.agent:?:war
[INFO] Unpacking /root/.m2/repository/org/wso2/samples/is/org.wso2.sample.is.sso.agent/4.3.5/org.wso2.sample.is.sso.agent-4.3.5.war to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/test-classes/samples/org.wso2.sample.is.sso.agent with includes "" and excludes ""
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:unpack (unpack-playground2) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] Configured Artifact: org.wso2.samples.is:playground2:?:war
[INFO] Unpacking /root/.m2/repository/org/wso2/samples/is/playground2/4.3.5/playground2-4.3.5.war to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/test-classes/samples/playground2 with includes "" and excludes ""
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:unpack (unpack-passivests) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] Configured Artifact: org.wso2.samples.is:PassiveSTSSampleApp:?:war
[INFO] Unpacking /root/.m2/repository/org/wso2/samples/is/PassiveSTSSampleApp/4.3.5/PassiveSTSSampleApp-4.3.5.war to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/test-classes/samples/PassiveSTSSampleApp with includes "" and excludes ""
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:copy (copy-sample-authenticator-webapp) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] Configured Artifact: org.wso2.samples.is:org.wso2.carbon.identity.sample.extension.auth.endpoint:?:war
[INFO] Copying org.wso2.carbon.identity.sample.extension.auth.endpoint-4.3.5.war to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/test-classes/samples/authenticators/sample-auth.war
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:copy (copy-sample-authenticator) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] Configured Artifact: org.wso2.samples.is:org.wso2.carbon.identity.sample.extension.authenticators:?:jar
[INFO] Copying org.wso2.carbon.identity.sample.extension.authenticators-4.3.5.jar to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/test-classes/samples/authenticators/org.wso2.carbon.identity.sample.extension.authenticators.jar
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:copy (copy-resources-dropins) @ org.wso2.carbon.identity.integration.backend.test ---
[INFO] Configured Artifact: org.wso2.is:org.wso2.carbon.identity.test.integration.service:5.11.0:jar
[INFO] Copying org.wso2.carbon.identity.test.integration.service-5.11.0.jar to /home/shanika/product-is/modules/integration/tests-integration/tests-backend/target/test-classes/samples/userMgt/org.wso2.carbon.identity.test.integration.service.jar
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ org.wso2.carbon.identity.integration.backend.test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 294 resources
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (packaging-sample-war-artifacts-without-slf4j) @ org.wso2.carbon.identity.integration.backend.test ---
[WARNING] Parameter tasks is deprecated, use target instead
[INFO] Executing tasks
`

Attaching the logs

[nohup.zip](https://github.com/wso2/product-is/files/8128091/nohup.zip)

**Comment by ShanikaWickramasinghe** [comment]
THis was cused due to a configuration issue. Hence closing the issue
