### ISSUE TITLE
[Federation][MFA][Google+TOTP/FIDO] Authentication error when using Google in 1st step and TOTP/FIDO in 2nd step

### ISSUE THREAD

**Issue by deshalw** [wso2/product-is#13200]
**Describe the issue:**
```Authentication Error! Something went wrong during the authentication process. Please try signing in again.``` displayed when trying to sign in using a google account, while MFA is enabled.

**How to reproduce:**
1. Set up a SP, setup Google Authenticator in an IdP
2. Add Google as a sign-in option to step 1
3. Add TOTP/ FIDO as the second step
4. Try to log in to the SP using a google account

**Expected behavior:**
User should be allowed to log in using Google account and prompted to setup TOTP if not done already.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12 Alpha 13
 - OS: Windows 10
 - Database: MySQL
 - Userstore: JDBC
 - Browser: Firefox 97

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by deshalw** [comment]
Error Log:

```[2022-03-05 00:04:18,502] []  INFO {org.wso2.identity.apps.common.internal.AppsCommonServiceComponent} - My Account URL : https://localhost:9443/myaccount
[2022-03-05 00:04:18,502] []  INFO {org.wso2.identity.apps.common.internal.AppsCommonServiceComponent} - Console URL : https://localhost:9443/console
[2022-03-05 00:04:18,503] []  INFO {org.wso2.identity.apps.common.internal.AppsCommonServiceComponent} - Identity apps common service component activated successfully.
[2022-03-05 00:16:33,342] [df73255a-4bc3-4a0d-956f-8cd1b6d89553]  INFO {org.opensaml.core.config.InitializationService} - Initializing OpenSAML using the Java Services API
[2022-03-05 00:17:06,509] [7f23cea7-5062-47cc-b66d-2c7061bacdd9] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! Authentication failed!. Cannot get the username from first step.
[2022-03-05 00:17:12,340] [4ec45b23-0b2f-4f30-86c3-93e3c815ab34] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework org.wso2.carbon.identity.application.authentication.framework.exception.FrameworkException: No authenticator can handle the request in step :  2
        at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handleResponse(DefaultStepHandler.java:551)
        at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:215)
        at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:186)
        at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:114)
        at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:186)
        at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:279)
        at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:57)
        at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doGet(CommonAuthenticationServlet.java:47)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:95)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:117)
        at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
        at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:119)
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:118)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:61)
        at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

[2022-03-05 00:18:05,088] [9d005b7f-9c89-4317-b474-ef8b19be2b57] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! Authentication failed!. Cannot get the username from first step.
[2022-03-05 00:19:09,168] [2e358f17-1548-425b-9ced-f9c97b4898ca]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Initializing of policy store is started at :  Sat Mar 05 00:19:09 IST 2022
[2022-03-05 00:19:09,185] [2e358f17-1548-425b-9ced-f9c97b4898ca]  INFO {org.wso2.carbon.identity.entitlement.policy.store.DefaultPolicyDataStore} - Using Global policy combining algorithm that is defined in configuration file.
[2022-03-05 00:19:09,194] [2e358f17-1548-425b-9ced-f9c97b4898ca]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Start retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@13870ceb at : Sat Mar 05 00:19:09 IST 2022
[2022-03-05 00:19:09,205] [2e358f17-1548-425b-9ced-f9c97b4898ca]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Finish retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@13870ceb at : Sat Mar 05 00:19:09 IST 2022
[2022-03-05 00:19:09,213] [2e358f17-1548-425b-9ced-f9c97b4898ca]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Initializing of policy store is finished at :  Sat Mar 05 00:19:09 IST 2022
[2022-03-05 00:19:09,591] [2e358f17-1548-425b-9ced-f9c97b4898ca]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Initializing of policy store is started at :  Sat Mar 05 00:19:09 IST 2022
[2022-03-05 00:19:09,599] [2e358f17-1548-425b-9ced-f9c97b4898ca]  INFO {org.wso2.carbon.identity.entitlement.policy.store.DefaultPolicyDataStore} - Using Global policy combining algorithm that is defined in configuration file.
[2022-03-05 00:19:09,611] [2e358f17-1548-425b-9ced-f9c97b4898ca]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Start retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@13870ceb at : Sat Mar 05 00:19:09 IST 2022
[2022-03-05 00:19:09,621] [2e358f17-1548-425b-9ced-f9c97b4898ca]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Finish retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@13870ceb at : Sat Mar 05 00:19:09 IST 2022
[2022-03-05 00:19:09,621] [2e358f17-1548-425b-9ced-f9c97b4898ca]  INFO {org.wso2.carbon.identity.entitlement.policy.finder.CarbonPolicyFinder} - Initializing of policy store is finished at :  Sat Mar 05 00:19:09 IST 2022
[2022-03-05 00:19:09,694] [2e358f17-1548-425b-9ced-f9c97b4898ca]  INFO {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} - 'admin@carbon.super [-1234]' logged in at [2022-03-05 00:19:09,694+0530]
[2022-03-05 00:20:53,892] [034f6eda-12b7-4b54-b3eb-70329bdbaec3]  WARN {org.wso2.carbon.identity.application.authentication.framework.handler.claims.impl.DefaultClaimHandler} - Subject claim could not be found amongst locally mapped unfiltered remote claims
[2022-03-05 00:20:53,895] [034f6eda-12b7-4b54-b3eb-70329bdbaec3]  WARN {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.PostAuthenticatedSubjectIdentifierHandler} - Subject claim could not be found. Defaulting to Name Identifier.
[2022-03-05 00:21:29,598] [359b2ee4-6ad1-46c4-9d2b-b327ea346daa]  INFO {org.wso2.carbon.identity.oauth.config.OAuthServerConfiguration} - An instance of org.wso2.carbon.identity.oauth2.token.JWTTokenIssuer is created for Identity OAuth token generation.
[2022-03-05 00:21:29,609] [359b2ee4-6ad1-46c4-9d2b-b327ea346daa]  INFO {org.opensaml.core.config.InitializationService} - Initializing OpenSAML using the Java Services API
[2022-03-05 00:21:55,122] [cc1e5c68-1a16-4417-9356-9dfe61056f80] ERROR {org.wso2.carbon.identity.sso.saml.validators.IdPInitSSOAuthnRequestValidator} - A SAML Service Provider with the Issuer 'myAccount' is not registered. Service Provider should be registered in advance
[2022-03-05 00:22:39,617] [971bb8d7-8afc-4ce1-8349-5c1cae68846c] ERROR {org.wso2.carbon.identity.sso.saml.validators.IdPInitSSOAuthnRequestValidator} - A SAML Service Provider with the Issuer 'My Account' is not registered. Service Provider should be registered in advance
[2022-03-05 00:23:01,669] [e43cd52c-a0b6-454a-94db-231166d67b1b] ERROR {org.wso2.carbon.identity.sso.saml.validators.IdPInitSSOAuthnRequestValidator} - A SAML Service Provider with the Issuer 'MyAccount' is not registered. Service Provider should be registered in advance
[2022-03-05 00:26:04,763] [01628410-f081-4f3f-aba0-a23b1193ad97] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! Authentication failed!. Cannot get the username from first step.
[2022-03-05 00:26:14,573] [ecc26bd4-4aa3-44aa-84a3-2467dc3e7e23] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Context does not exist. Probably due to invalidated cache. Requested client: 127.0.0.1, URI :GET:/commonauth, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0 , Referer: https://accounts.google.com/
[2022-03-05 00:26:14,575] [ecc26bd4-4aa3-44aa-84a3-2467dc3e7e23]  WARN {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Authentication context is null, redirect parameter filtering will not be done for null
[2022-03-05 00:27:32,272] [8181d05c-a4cc-4c1f-963a-a331e833e96c] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Context does not exist. Probably due to invalidated cache. Requested client: 127.0.0.1, URI :GET:/commonauth, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0 , Referer: https://localhost:9443/authenticationendpoint/login.do?commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&tenantDomain=carbon.super&sessionDataKey=ecc8a81a-d5f4-4f8e-bed0-75de547e633e&relyingParty=travelocity.com&type=samlsso&sp=travelocity.com&isSaaSApp=false&authenticators=GoogleOIDCAuthenticator%3AtestIDP1%3BBasicAuthenticator%3ALOCAL
[2022-03-05 00:27:32,274] [8181d05c-a4cc-4c1f-963a-a331e833e96c]  WARN {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Authentication context is null, redirect parameter filtering will not be done for ecc8a81a-d5f4-4f8e-bed0-75de547e633e
[2022-03-05 00:29:28,242] [b54091ea-04a6-4d5a-ab3b-0176687c6330] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Context does not exist. Probably due to invalidated cache. Requested client: 127.0.0.1, URI :GET:/commonauth, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0 , Referer: https://localhost:9443/authenticationendpoint/login.do?commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&tenantDomain=carbon.super&sessionDataKey=ecc8a81a-d5f4-4f8e-bed0-75de547e633e&relyingParty=travelocity.com&type=samlsso&sp=travelocity.com&isSaaSApp=false&authenticators=GoogleOIDCAuthenticator%3AtestIDP1%3BBasicAuthenticator%3ALOCAL
[2022-03-05 00:29:28,243] [b54091ea-04a6-4d5a-ab3b-0176687c6330]  WARN {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Authentication context is null, redirect parameter filtering will not be done for ecc8a81a-d5f4-4f8e-bed0-75de547e633e
[2022-03-05 00:43:37,808] [ee4fafb4-2c53-478b-9da8-ce352f19b6e7] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! Authentication failed!. Cannot get the username from first step.```

**Comment by IsuraD** [comment]
It is required to enable JIT provisioning in google IDP to work TOTP. Can you check the behavior by enabling JIT.

**Comment by deshalw** [comment]
Checking this scenario again

**Comment by deshalw** [comment]
This issue could not be reproduced when JIT provisioning was enabled in the IdP. Therefore closing the issue.
