### ISSUE TITLE
Test failure in ConditionalAuthenticationTestCase

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#13267]
**Describe the issue:**
Test failure found in ConditionalAuthenticationTestCase. Couldn't find the exact root cause and it seems like a `ThreadDeath` issue. No other issue found with the conditional authenticator and disabled the test case temporary to run the builder with #12413.

Stacktrace:
```
2022-03-15T20:33:05.3078212Z [ERROR] Tests run: 1845, Failures: 7, Errors: 0, Skipped: 57, Time elapsed: 6,200.977 s <<< FAILURE! - in TestSuite
2022-03-15T20:33:05.3082016Z [ERROR] testStart(org.wso2.identity.integration.test.rest.api.user.application.v1.UserDiscoverableApplicationSuccessTest)  Time elapsed: 0.265 s  <<< FAILURE!
2022-03-15T20:33:05.3083022Z java.lang.Exception: Transport error: 401 Error: 
2022-03-15T20:33:05.3084092Z 	at org.wso2.identity.integration.test.rest.api.user.application.v1.UserDiscoverableApplicationSuccessTest.testStart(UserDiscoverableApplicationSuccessTest.java:79)
2022-03-15T20:33:05.3086343Z 
2022-03-15T20:33:05.3088198Z [ERROR] testEnd(org.wso2.identity.integration.test.rest.api.user.application.v1.UserDiscoverableApplicationSuccessTest)  Time elapsed: 0.009 s  <<< FAILURE!
2022-03-15T20:33:05.3089030Z java.lang.Exception: Transport error: 401 Error: 
2022-03-15T20:33:05.3090579Z 
2022-03-15T20:33:05.3092946Z [ERROR] testEnd(org.wso2.identity.integration.test.rest.api.user.application.v1.UserDiscoverableApplicationSuccessTest)  Time elapsed: 0 s  <<< FAILURE!
2022-03-15T20:33:05.3093744Z java.lang.NullPointerException
2022-03-15T20:33:05.3095872Z 
2022-03-15T20:33:05.3098199Z [ERROR] testEnd(org.wso2.identity.integration.test.rest.api.user.application.v1.UserDiscoverableApplicationFailureTest)  Time elapsed: 0.001 s  <<< FAILURE!
2022-03-15T20:33:05.3099181Z java.lang.NullPointerException
2022-03-15T20:33:05.3100939Z 
2022-03-15T20:33:05.3102871Z [ERROR] testEnd(org.wso2.identity.integration.test.rest.api.user.application.v1.UserDiscoverableApplicationFailureTest)  Time elapsed: 0.003 s  <<< FAILURE!
2022-03-15T20:33:05.3103506Z java.lang.NullPointerException
2022-03-15T20:33:05.3104731Z 
2022-03-15T20:33:05.3106453Z [ERROR] testInit(org.wso2.identity.integration.test.auth.ConditionalAuthenticationTestCase)  Time elapsed: 23.695 s  <<< FAILURE!
2022-03-15T20:33:05.3107440Z java.lang.Exception: org.json.JSONObject$Null cannot be cast to java.lang.String
2022-03-15T20:33:05.3108503Z 	at org.wso2.identity.integration.test.auth.ConditionalAuthenticationTestCase.createServiceProviderInSecondaryIS(ConditionalAuthenticationTestCase.java:464)
2022-03-15T20:33:05.3109677Z 	at org.wso2.identity.integration.test.auth.ConditionalAuthenticationTestCase.testInit(ConditionalAuthenticationTestCase.java:142)
2022-03-15T20:33:05.3110360Z 
2022-03-15T20:33:05.3110850Z [ERROR] atEnd(org.wso2.identity.integration.test.auth.ConditionalAuthenticationTestCase)  Time elapsed: 0.177 s  <<< FAILURE!
2022-03-15T20:33:05.3112036Z org.apache.axis2.AxisFault: Exception occurred while trying to invoke service method removeOAuthApplicationData
2022-03-15T20:33:05.3112873Z 	at org.wso2.identity.integration.test.auth.ConditionalAuthenticationTestCase.atEnd(ConditionalAuthenticationTestCase.java:156)
2022-03-15T20:33:05.3113709Z 
```

when running only with ConditionalAuthenticationTestCase:
```
ERROR {org.wso2.carbon.identity.application.authentication.framework.config.model.graph.JsGraphBuilder} - Error in executing the javascript for service provider : testOauthApp, Javascript Fragment : 
function (context) {
            var fName = context.steps[1].subject.localClaims['http://wso2.org/claims/givenname'];
            var lName = context.steps[1].subject.localClaims['http://wso2.org/claims/lastname'];
            var displayName = fName + ' '+ lName + ' by Javascript';
            context.steps[1].subject.localClaims['http://wso2.org/claims/displayName'] = displayName;
        } java.lang.ThreadDeath
	at java.lang.Thread.stop(Thread.java:853)
	at org.wso2.carbon.identity.application.authentication.framework.config.model.graph.JSExecutionSupervisor$MonitoringTask.run(JSExecutionSupervisor.java:165)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
```

**How to reproduce:**
- Execute product is backend tests.

**Comment by piraveena** [comment]
@sumedhe Is this fixed after that?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
