### ISSUE TITLE
Roles are not listed in Console

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#13309]
**Describe the issue:**

When trying to view roles, via console getting a blank page and error logs are printed in the backend. This is reproducible only in FireFox browser
<img width="1666" alt="Screenshot 2022-03-23 at 15 33 53" src="https://user-images.githubusercontent.com/17597293/159674556-ae698b82-c0b7-43d3-acc9-bd7bd245ad5c.png">

```
[2022-03-23 15:23:15,070] [2bcd08c8-8122-4d95-818d-ec1e66606175] DEBUG {org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl} - Adding the roleID: ae63f91f-c8f2-4476-b676-04e8c821bde6 for the role: Internal/everyone in the tenantDomain: carbon.super
[2022-03-23 15:23:15,077] [1dd3ee9c-7e97-41c8-94d7-a6b300c09500] DEBUG {org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl} - Adding the roleID: a216f990-a6a9-4eb6-b4a7-435a785e892c for the role: Internal/system in the tenantDomain: carbon.super
[2022-03-23 15:23:17,516] [95be587c-e394-4ea8-a900-d5eb92e5b591] DEBUG {org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl} - Adding the roleID: bf30ce15-f080-47e4-a884-29594dcd555f for the role: Internal/everyone in the tenantDomain: carbon.super
[2022-03-23 15:23:17,517] [1dd3ee9c-7e97-41c8-94d7-a6b300c09500] DEBUG {org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl} - Adding the roleID: 578bfa6a-fa8e-4ac0-b752-2727f87c0759 for the role: Internal/everyone in the tenantDomain: carbon.super
[2022-03-23 15:23:18,212] [2bcd08c8-8122-4d95-818d-ec1e66606175] DEBUG {org.wso2.carbon.identity.role.mgt.core.RoleManagementEventPublisherProxy} - Event: POST_GET_ROLES_EVENT is published for the role management operation in the tenant with the tenantId: null
[2022-03-23 15:23:19,622] [2bcd08c8-8122-4d95-818d-ec1e66606175] DEBUG {org.wso2.carbon.identity.role.mgt.core.internal.RoleManagementServiceImpl} - admin@carbon.super get roles successfully.
[2022-03-23 15:23:20,057] [1dd3ee9c-7e97-41c8-94d7-a6b300c09500] DEBUG {org.wso2.carbon.identity.role.mgt.core.RoleManagementEventPublisherProxy} - Event: POST_GET_ROLES_EVENT is published for the role management operation in the tenant with the tenantId: null
[2022-03-23 15:23:21,326] [1dd3ee9c-7e97-41c8-94d7-a6b300c09500] DEBUG {org.wso2.carbon.identity.role.mgt.core.internal.RoleManagementServiceImpl} - admin@carbon.super get roles successfully.
[2022-03-23 15:23:21,326] [95be587c-e394-4ea8-a900-d5eb92e5b591] DEBUG {org.wso2.carbon.identity.role.mgt.core.RoleManagementEventPublisherProxy} - Event: POST_GET_ROLES_EVENT is published for the role management operation in the tenant with the tenantId: null
[2022-03-23 15:23:21,327] [95be587c-e394-4ea8-a900-d5eb92e5b591] DEBUG {org.wso2.carbon.identity.role.mgt.core.internal.RoleManagementServiceImpl} - admin@carbon.super get roles successfully.
[2022-03-23 15:28:17,992] [781401b9-0b28-4731-be54-bea48955d885] ERROR {org.wso2.charon3.core.protocol.endpoints.AbstractResourceManager} - Error occurred while listing roles. org.wso2.charon3.core.exceptions.CharonException: Error occurred while listing roles.
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManager.listRoles(SCIMRoleManager.java:331)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManager.listRolesWithGET(SCIMRoleManager.java:188)
	at org.wso2.charon3.core.protocol.endpoints.RoleResourceManager.listWithGETRole(RoleResourceManager.java:165)
	at org.wso2.carbon.identity.scim2.provider.resources.RoleResource.getRoles(RoleResource.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:659)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:117)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:106)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:144)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:61)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.identity.role.mgt.core.IdentityRoleManagementClientException: Invalid scenario. Multiple roles found for the given role name: Internal/system and tenantDomain: carbon.super
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.batchProcessRoleNames(RoleDAOImpl.java:1395)
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.getRoleIDsByNames(RoleDAOImpl.java:1365)
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.buildRolesList(RoleDAOImpl.java:354)
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.processListRolesQuery(RoleDAOImpl.java:340)
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.getRoles(RoleDAOImpl.java:293)

```

**How to reproduce:**

1. Login to Console
2. Go to Mange > Roles
3. Click Roles
4. View logs

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.12.0-Alpha17 snapshot
 - OS:  Mac
 - Database: MySQL 8.0.28/ H2
 - Userstore: JDBC- MySQL 8.0.28 / Embedded LDAP
 - Browser: Firefox

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by piraveena** [comment]
From the Console app, there are 4 requests GET Roles api concurrently. Due to this, there are 4 calls to the backend concurrently.  In the IDN_SCIM_GROUP table, there are 3 entries created for the Internal/System role and Internal/everyone role since we don't have any unique key constraints in the  DB level. 

<img width="1092" alt="Screenshot 2022-03-23 at 20 20 11" src="https://user-images.githubusercontent.com/17597293/159727543-b899c944-f282-47b3-84d8-35700739a459.png">


This issue is internmittent. If the 4 API calls don't happen simultaneously, then this issue won't be reproducible. Becuase, we add the roles to IDN_SCIM_GROUP only if they don't exist in the DB from here https://github.com/wso2/carbon-identity-framework/blob/v5.20.344/components/role-mgt/org.wso2.carbon.identity.role.mgt.core/src/main/java/org/wso2/carbon/identity/role/mgt/core/dao/RoleDAOImpl.java#L357

**This needs two fixes:**
- [ ] Stop making 4 calls for Roles API from console
- [ ] Have a DB constraint to prevent concurrent db entries for the same internal role
