### ISSUE TITLE
Getting 400 Bad Request when trying session extending API with commonAuthId Cookie passed as a header

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13300]
**How to reproduce:**
1. Try sending session identifier as a cookie API request as mentioned in https://github.com/wso2/docs-is/blob/master/en/docs/develop/idp-session-extender-endpoint.md
2. Login to management console and get the value for the cookie 

**Flow 01** 

3. Block third party cookies from chrome browser settings

![Screenshot from 2022-03-22 23-14-48](https://user-images.githubusercontent.com/31848014/159552736-0aa29604-719f-45a6-a6d6-f93d8439dd85.png)

4. Pass the cookie value for commonAuthId copied in step 2 as a header as below

```
curl --location --request GET 'https://localhost:9443/identity/extend-session' \
--header 'Cookie: e39c94ec-6d8c-4b4d-a1e6-1d08efc41b9b' \
--header 'Authorization: Basic YWRtaW46YWRtaW4='
```
Getting Response as

![Screenshot from 2022-03-23 11-21-07](https://user-images.githubusercontent.com/31848014/159632843-46472b5e-119a-4c2f-abc8-9c88bda17249.png)
![Screenshot from 2022-03-23 11-21-21](https://user-images.githubusercontent.com/31848014/159632853-ba1080bc-e35f-4929-9186-a2dbcffca152.png)

![Screenshot from 2022-03-23 11-21-27](https://user-images.githubusercontent.com/31848014/159632869-e654e4b7-0904-477f-8f90-7792622d1f7c.png)
**Flow 02**

5. Allow third party cookies from the browser settings

![Screenshot from 2022-03-23 00-09-21](https://user-images.githubusercontent.com/31848014/159552595-4bb18034-eb47-4175-85e9-640a65d6aff1.png)

7. Try the same above API request passing the cookie value for commonAuthId
8. Getting the same error with 400 response

Backend Logs

```
[2022-03-23 00:01:05,728] [adc017a7-a0bb-43c6-80a4-6ff525e6b342] ERROR {org.wso2.carbon.identity.application.authentication.framework.inbound.IdentityServlet} - Failed to create IdentityRequest org.wso2.carbon.identity.application.authentication.framework.session.extender.exception.SessionExtenderClientException: No session identifier parameter or cookie present in request.
	at org.wso2.carbon.identity.application.authentication.framework.session.extender.request.SessionExtenderRequestFactory.create(SessionExtenderRequestFactory.java:100)
	at org.wso2.carbon.identity.application.authentication.framework.inbound.IdentityServlet.process(IdentityServlet.java:69)
	at org.wso2.carbon.identity.application.authentication.framework.inbound.IdentityServlet.service(IdentityServlet.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:72)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:117)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:119)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:120)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:61)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

https://user-images.githubusercontent.com/31848014/159552100-04661ea9-3951-490d-84bb-4be60c1659bc.mp4

**Env**
IS 5.12.0 alpha 16
chrome 99

**Comment by piraveena** [comment]
Could reproduce the error. 

```
 curl --location --request GET 'https://localhost:9443/t/carbon.super/identity/extend-session' \
--header 'Cookie: 23739d65-79dc-49f1-a697-4f0eccaa18d5' 

```

Response:
``` 
{
    "traceId": "97122d99-578b-420b-9586-806a54081a37",
    "code": "ISE-60001",
    "description": "No session identifier parameter or cookie present in request.",
    "message": "Invalid request."
}
```

**Comment by piraveena** [comment]
The request should be as below:

```
curl --location --request GET 'https://localhost:9443/t/carbon.super/identity/extend-session' \
--header 'Cookie: commonAuthId=66d673e2-8294-4bfa-92c6-5a66bc9f3930'
```
