### ISSUE TITLE
ERROR {org.wso2.carbon.identity.rest.api.user.session.v1.core.SessionManagementService} - errorCode: USM-15001 When SSO for Myaccount with Postgres 14

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13317]
**How to reproduce:**
1. Configure postgres 14 as the primary database

```
[user_store]
type = "database_unique_id"

[database.identity_db]
#type = "Postgres" 
url = "jdbc:postgresql://localhost:5432/alpha16db1"
username = "postgres"
password = "wso2carbon"
driver = "org.postgresql.Driver"
[database.identity_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1; COMMIT"
validationInterval="30000"
defaultAutoCommit=false

[database.shared_db]
#type = "Postgres" 
url = "jdbc:postgresql://localhost:5432/alpha16db1"
username = "postgres"
password = "wso2carbon"
driver = "org.postgresql.Driver"
[database.shared_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1; COMMIT"
validationInterval="30000"
defaultAutoCommit=false
```

3. Login to Console (Via Firefox or chrome 99)
4. Click on user profile
5. Click on Myaccount to SSO for myaccount

**Actual behavior:**
Getting Below UI error and backend error

![Screenshot from 2022-03-24 12-17-26](https://user-images.githubusercontent.com/31848014/159859092-0f119c28-8115-4263-b898-2444f25a5d65.png)

https://user-images.githubusercontent.com/31848014/159859532-be938f53-8088-488f-b2e6-c4d033a16230.mp4

```
[2022-03-24 12:23:59,551] [a97b8b47-b625-4db4-94d7-827f3cfc7ad8] ERROR {org.wso2.carbon.identity.rest.api.user.session.v1.core.SessionManagementService} - errorCode: USM-15001 | message: Server encountered an error while retrieving session information. org.wso2.carbon.identity.application.authentication.framework.exception.session.mgt.SessionManagementServerException: Unable to retrieve session information
	at org.wso2.carbon.identity.application.authentication.framework.dao.impl.UserSessionDAOImpl.generateApplicationFromAppID(UserSessionDAOImpl.java:125)
	at org.wso2.carbon.identity.application.authentication.framework.dao.impl.UserSessionDAOImpl.getSession(UserSessionDAOImpl.java:62)
	at org.wso2.carbon.identity.application.authentication.framework.internal.impl.UserSessionManagementServiceImpl.getActiveSessionList(UserSessionManagementServiceImpl.java:361)
	at org.wso2.carbon.identity.application.authentication.framework.internal.impl.UserSessionManagementServiceImpl.getSessionsByUserId(UserSessionManagementServiceImpl.java:176)
	at org.wso2.carbon.identity.rest.api.user.session.v1.core.SessionManagementService.getSessionsByUserId(SessionManagementService.java:145)
	at org.wso2.carbon.identity.rest.api.user.session.v1.core.SessionManagementService.getSessionsBySessionId(SessionManagementService.java:88)
	at org.wso2.carbon.identity.rest.api.user.session.v1.impl.MeApiServiceImpl.getSessionsOfLoggedInUser(MeApiServiceImpl.java:42)
	at org.wso2.carbon.identity.rest.api.user.session.v1.MeApi.getSessionsOfLoggedInUser(MeApi.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:117)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:106)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:144)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:61)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: integer = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 48
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:109)
	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy54.executeQuery(Unknown Source)
	at org.wso2.carbon.identity.application.authentication.framework.dao.impl.UserSessionDAOImpl.generateApplicationFromAppID(UserSessionDAOImpl.java:114)
	... 62 more

```

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 5.12.0 alpha 16
postgres 14

**Comment by ShanikaWickramasinghe** [comment]
Closing the issue as this is reported with postgres 11.5 version and fix will be available with 5.12.0 alpha 17
