### ISSUE TITLE
TOTP authenticator doesn't work when IS is clustered

### ISSUE THREAD

**Issue by danushkaf** [wso2/product-is#1336]
**Description:**
TOTP Authenticator doesn't work when IS has multiple nodes fronted by a LB.(Clustered)

**Suggested Labels:**
TOTP

**Affected Product Version:**
TOTP 2.0.1 +

**Steps to reproduce:**
Create clustered IS with two nodes. Then configure TOTP. And try to login to a service provider with totp.
If sticky sessions are not enabled then this will be easily reproduced. If sticky sessions are enabled then after basic auth is succeeded, before get the verification code, stop the server that served the first request.

**Related Issues:**
Reason might be in totp authenticator getContextIdentifier returns jsessionID instead of sessionDataKey.

**Comment by IndunilRathnayake** [comment]
This is fixed in IS 5.4.0-M3 with https://github.com/wso2/carbon-identity-framework/pull/993

**Comment by IndunilRathnayake** [comment]
This fixes following issues.

[2017-09-11 19:02:14,813] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Exception in Authentication Frameworkjava.lang.NullPointerException    at org.wso2.carbon.identity.application.authentication.framework.context.AuthenticationContext.getProperty(AuthenticationContext.java:209)    at org.wso2.carbon.identity.application.authenticator.totp.TOTPAuthenticator.generateTOTPToken(TOTPAuthenticator.java:252)    at org.wso2.carbon.identity.application.authenticator.totp.TOTPAuthenticator.process(TOTPAuthenticator.java:61)    at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:465)    at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handleResponse(DefaultStepHandler.java:439)......
--

**Comment by IndunilRathnayake** [comment]
Public Jira : https://wso2.org/jira/browse/IDENTITY-6425
