### ISSUE TITLE
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: samples/flask/cert/wso2.crt While Running Python SDK

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13406]
**How to reproduce:**
1. Setup Python SDK as mentioned in guide https://docs.google.com/document/d/1n-7DswTz4YJJl4T2wbpylBSa4pPL0UTQ_p3eDPh0VMU/edit#
2. Up the sample with command 
    python3 app.py

I have replaced the wso2.crt with tenants crt as well and tried. But still getting the same error

Getting below Error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/asgardeo_auth/models/op_Configuration.py", line 20, in __init__
    resp = requests.get(url=well_known_url,
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 227, in cert_verify
    raise IOError("Could not find a suitable TLS CA certificate bundle, "
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: samples/flask/cert/wso2.crt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 22, in <module>
    identity_auth = FlaskAsgardeoAuth(auth_config=auth_config)
  File "/usr/local/lib/python3.8/dist-packages/asgardeo_auth/asgardeo_auth.py", line 46, in __call__
    cls._instance = super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/asgardeo_auth/Integration/flask_client/flask_asgardeo_auth.py", line 22, in __init__
    super().__init__(auth_config, framework)
  File "/usr/local/lib/python3.8/dist-packages/asgardeo_auth/asgardeo_auth.py", line 59, in __init__
    self.op_configuration = OPConfiguration(
  File "/usr/local/lib/python3.8/dist-packages/asgardeo_auth/models/op_Configuration.py", line 49, in __init__
    raise AsgardeoAuthError(
asgardeo_auth.exception.asgardeo_auth_error.AsgardeoAuthError: Initialized OpenID Provider configuration from default configuration. Because failed to access wellknown endpoint: https://localhost:9443/t/wso2.com/oauth2/token/.well-known/openid-configuration

```
![Screenshot from 2022-04-05 14-44-59](https://user-images.githubusercontent.com/31848014/161721425-57b096c4-0df2-4b23-9037-94d3f036fc97.png)

**Environment**
IS 5.12.0 alpha 18
Ubuntu 20
JDK 11

**Comment by ShanikaWickramasinghe** [comment]
@Sathiyakugan Can you have a look on this

**Comment by minolih** [comment]
The invalid path issue gets resolved when the relative certificate path is changed in the conf file as "cert/wso2.crt" from the path given below. 
https://github.com/asgardeo/asgardeo-auth-python-sdk/blob/effbc221659e187da4c67a02600dd042621e431b/samples/flask/conf.py#L13. 

But the flow cannot be tested as there is an SSL error.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
