### ISSUE TITLE
StackOverflowError due to certain order of toml configs

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#13485]
**Describe the issue:**
A StackOverflowError happens when there are two headers like below where the second one is a sub-element of the first one in the deployment.toml. 

```
WARN {org.wso2.config.mapper.ConfigParser} - Overriding files in configuration directory /tmp/wso2is-5.11.0
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:69)
	at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)
Caused by: java.lang.StackOverflowError
	at java.util.HashMap$EntrySpliterator.<init>(HashMap.java:1693)
	at java.util.HashMap$EntrySet.spliterator(HashMap.java:1035)
	at java.util.Collection.stream(Collection.java:581)
	at net.consensys.cava.toml.MutableTomlTable.keyPathSet(MutableTomlTable.java:71)
	at net.consensys.cava.toml.MutableTomlTable.lambda$keyPathSet$1(MutableTomlTable.java:80)
```

**Scenario 1**
```
[oauth.oidc]
extensions.claim_callback_handler = "com.sample.iam..CustomSAMLAssertionClaimsCallback"

[oauth.oidc.extensions]
user_info_response_builder = "com.sample.iam.UserInfoJsonResponse"
```

This can be solved by changing the order of two blocks or arranging them under a single header like below.
```
[oauth.oidc]
extensions.claim_callback_handler = "com.sample.iam..CustomSAMLAssertionClaimsCallback"
extensions.user_info_response_builder = "com.sample.iam.UserInfoJsonResponse"
```

**Scenario 2**
```
[user_store]
type = "database_unique_id"
properties.UseCaseSensitiveUsernameForCacheKeys = false

[user_store.properties]
UsernameWithEmailJavaScriptRegEx = '^([A-Za-z0-9_\+\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$'  
```

This can be solved by arranging them under a single header like below.
```
[user_store]
type = "database_unique_id"
properties.UseCaseSensitiveUsernameForCacheKeys = false
properties.UsernameWithEmailJavaScriptRegEx = '^([A-Za-z0-9_\+\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$'  
```

Or like below.
```
[user_store]
type = "database_unique_id"

[user_store.properties]
UseCaseSensitiveUsernameForCacheKeys = false
UsernameWithEmailJavaScriptRegEx = '^([A-Za-z0-9_\+\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$'  
```

**Expected behavior:**
It should be able to parse the toml or show an error message with the reason. This needs to be fixed from https://github.com/apache/incubator-tuweni it seems.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
