### ISSUE TITLE
NullPointerException when running migration 5.9.0 to 5.10.0 for migration 1.0.181 on postgresql 11.15  and windows

### ISSUE THREAD

**Issue by lbuyse** [wso2/product-is#13609]
**Describe the issue:**
Trying to migrate wso2is 5.9.0 db to 5.10.0 with wso2is-migration-1.0.181 on postgresql 11.15 and windows with a -DdryRun
but having nullpointerexception : 

`
...
[2022-05-03 10:39:55,795] []  INFO {org.wso2.carbon.core.multitenancy.eager.TenantLoadingConfig} - Using tenant lazy loading policy...
[2022-05-03 10:39:55,809] []  INFO {org.wso2.carbon.core.internal.permission.update.PermissionUpdater} - Permission cache updated for tenant -1234
[2022-05-03 10:39:56,685] []  INFO {org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent} - Executing Migration client : org.wso2.carbon.is.migration.MigrationClientImpl
[2022-05-03 10:39:56,714] []  INFO {org.wso2.carbon.is.migration.config.Config} -  WSO2 Product Migration Service Task : Loading Migration Configs, PATH:C:\Development\Servers\wso2is-5.10.0\migration-resources\migration-config.yaml
[2022-05-03 10:39:56,770] []  INFO {org.wso2.carbon.is.migration.config.Config} -  WSO2 Product Migration Service Task : Successfully loaded the config file.
[2022-05-03 10:39:56,770] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,771] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,771] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,771] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,772] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,772] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,772] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,773] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,773] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,774] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,774] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,774] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,777] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - Migration Versions List.........................
[2022-05-03 10:39:56,777] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - 5.0.0 to 5.0.0-SP1
[2022-05-03 10:39:56,778] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - 5.0.0-SP1 to 5.1.0
[2022-05-03 10:39:56,778] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - 5.1.0 to 5.2.0
[2022-05-03 10:39:56,779] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - 5.2.0 to 5.3.0
[2022-05-03 10:39:56,779] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - 5.3.0 to 5.4.0
[2022-05-03 10:39:56,780] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - 5.4.0 to 5.5.0
[2022-05-03 10:39:56,781] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - 5.5.0 to 5.6.0
[2022-05-03 10:39:56,781] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - 5.6.0 to 5.7.0
[2022-05-03 10:39:56,781] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - 5.7.0 to 5.8.0
[2022-05-03 10:39:56,781] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - 5.8.0 to 5.9.0
[2022-05-03 10:39:56,781] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - 5.9.0 to 5.10.0
[2022-05-03 10:39:56,782] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - 5.10.0 to 5.11.0
[2022-05-03 10:39:56,782] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - 5.11.0 to 5.12.0
[2022-05-03 10:39:56,783] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} -  WSO2 Product Migration Service Task : Start Version : 5.0.0 to 5.0.0-SP1
[2022-05-03 10:39:56,783] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} -  WSO2 Product Migration Service Task : Start Version : 5.0.0-SP1 to 5.1.0
[2022-05-03 10:39:56,783] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} -  WSO2 Product Migration Service Task : Start Version : 5.1.0 to 5.2.0
[2022-05-03 10:39:56,784] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} -  WSO2 Product Migration Service Task : Start Version : 5.2.0 to 5.3.0
[2022-05-03 10:39:56,784] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} -  WSO2 Product Migration Service Task : Start Version : 5.3.0 to 5.4.0
[2022-05-03 10:39:56,785] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} -  WSO2 Product Migration Service Task : Start Version : 5.4.0 to 5.5.0
[2022-05-03 10:39:56,785] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} -  WSO2 Product Migration Service Task : Start Version : 5.5.0 to 5.6.0
[2022-05-03 10:39:56,785] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} -  WSO2 Product Migration Service Task : Start Version : 5.6.0 to 5.7.0
[2022-05-03 10:39:56,786] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} -  WSO2 Product Migration Service Task : Start Version : 5.7.0 to 5.8.0
[2022-05-03 10:39:56,786] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} -  WSO2 Product Migration Service Task : Start Version : 5.8.0 to 5.9.0
[2022-05-03 10:39:56,787] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} -  WSO2 Product Migration Service Task : Start Version : 5.9.0 to 5.10.0
[2022-05-03 10:39:56,886] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 5.10.0, Migration Step : ScopeDataMigrator of order : 1 is starting...........................
[2022-05-03 10:39:56,887] []  INFO {org.wso2.carbon.is.migration.service.v5100.migrator.ScopeDataMigrator} - Dry run capability not implemented in org.wso2.carbon.is.migration.service.v5100.migrator.ScopeDataMigrator migrator.
[2022-05-03 10:39:56,887] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 5.10.0, Migration Step : MigrationValidator of order : 2 is starting...........................
[2022-05-03 10:39:56,888] []  INFO {org.wso2.carbon.is.migration.service.v5100.migrator.MigrationValidator} - Dry run capability not implemented in org.wso2.carbon.is.migration.service.v5100.migrator.MigrationValidator migrator.
[2022-05-03 10:39:56,889] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 5.10.0, Migration Step : SchemaMigrator of order : 3 is starting...........................
[2022-05-03 10:39:56,889] []  INFO {org.wso2.carbon.is.migration.service.SchemaMigrator} - Dry run capability not implemented in org.wso2.carbon.is.migration.service.SchemaMigrator migrator.
[2022-05-03 10:39:56,890] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 5.10.0, Migration Step : SchemaMigrator of order : 4 is starting...........................
[2022-05-03 10:39:56,890] []  INFO {org.wso2.carbon.is.migration.service.SchemaMigrator} - Dry run capability not implemented in org.wso2.carbon.is.migration.service.SchemaMigrator migrator.
[2022-05-03 10:39:56,890] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 5.10.0, Migration Step : SchemaMigrator of order : 5 is starting...........................
[2022-05-03 10:39:56,891] []  INFO {org.wso2.carbon.is.migration.service.SchemaMigrator} - Dry run capability not implemented in org.wso2.carbon.is.migration.service.SchemaMigrator migrator.
[2022-05-03 10:39:56,891] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 5.10.0, Migration Step : OAuth2ScopesMigrator of order : 6 is starting...........................
[2022-05-03 10:39:56,891] []  INFO {org.wso2.carbon.is.migration.service.v5100.migrator.OAuth2ScopesMigrator} - Dry run capability not implemented in org.wso2.carbon.is.migration.service.v5100.migrator.OAuth2ScopesMigrator migrator.
[2022-05-03 10:39:56,892] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 5.10.0, Migration Step : ClaimDataMigrator of order : 7 is starting...........................
[2022-05-03 10:39:56,892] []  INFO {org.wso2.carbon.is.migration.service.ClaimDataMigrator} - Dry run capability not implemented in org.wso2.carbon.is.migration.service.ClaimDataMigrator migrator.
[2022-05-03 10:39:56,892] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 5.10.0, Migration Step : EmailTemplateDataMigrator of order : 8 is starting...........................
[2022-05-03 10:39:56,893] []  INFO {org.wso2.carbon.is.migration.service.EmailTemplateDataMigrator} - Dry run capability not implemented in org.wso2.carbon.is.migration.service.EmailTemplateDataMigrator migrator.
[2022-05-03 10:39:56,893] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 5.10.0, Migration Step : SchemaMigrator of order : 9 is starting...........................
[2022-05-03 10:39:56,893] []  INFO {org.wso2.carbon.is.migration.service.SchemaMigrator} - Dry run capability not implemented in org.wso2.carbon.is.migration.service.SchemaMigrator migrator.
[2022-05-03 10:39:56,893] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 5.10.0, Migration Step : UserIDMigrator of order : 10 is starting...........................
[2022-05-03 10:39:56,893] []  INFO {org.wso2.carbon.is.migration.service.v5100.migrator.UserIDMigrator} - Executing dry run for org.wso2.carbon.is.migration.service.v5100.migrator.UserIDMigrator
[2022-05-03 10:39:56,954] [] ERROR {org.wso2.carbon.is.migration.MigrationClientImpl} - Migration process was stopped. java.lang.NullPointerException
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:98)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at org.wso2.carbon.is.migration.util.ReportUtil.commit(ReportUtil.java:83)
        at org.wso2.carbon.is.migration.util.ReportUtil.commit(ReportUtil.java:74)
        at org.wso2.carbon.is.migration.service.v5100.migrator.UserIDMigrator.dryRun(UserIDMigrator.java:287)
        at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:50)
        at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:76)
        at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:149)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
        at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
        at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
        at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

[2022-05-03 10:39:56,961] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,961] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,962] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,962] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,963] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,963] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,964] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,964] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-05-03 10:39:56,965] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................`

**How to reproduce:**
run migration tool on wso2is 5.10.0 with 5.9.0 postgresql db with '.\wso2server.bat -Dmigrate -Dcomponent=identity -DdryRun'

migration-config.yaml : 

`migrationEnable: "true"

# Migration Start Version
currentVersion: "5.9.0"
# Migration End Version
migrateVersion: "5.10.0"

continueOnError: "true"
batchUpdate: "true"
ignoreForInactiveTenants: "true"

migrateTenantRange: "false"
migrationStartingTenantID: "0"
migrationEndingTenantID: "0"
...`

**Expected behavior:**
No nullpointerexception

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.10.0, IS 5.9.0 , wso2is-migration-1.0.181
 - OS: Windows
 - Database: postgresql 11.15
 - Userstore: JDBC 

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by lbuyse** [comment]
Oh yes , forgot , java version is 1.8.0_331 : 
`[2022-05-03 11:02:11,310] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Starting WSO2 Carbon...
[2022-05-03 11:02:11,311] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Operating System : Windows 11 10.0, amd64
[2022-05-03 11:02:11,311] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Home        : C:\Program Files\Java\jdk1.8.0_331\jre
[2022-05-03 11:02:11,311] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Version     : 1.8.0_331
[2022-05-03 11:02:11,311] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java VM          : Java HotSpot(TM) 64-Bit Server VM 25.331-b09,Oracle Corporation
[2022-05-03 11:02:11,311] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Carbon Home      : C:\Development\Servers\wso2is-5.10.0
[2022-05-03 11:02:11,312] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Temp Dir    : C:\Development\Servers\wso2is-5.10.0\tmp
[2022-05-03 11:02:11,312] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - User             : lbuyse, nl-BE, Europe/Paris`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
