### ISSUE TITLE
Error while storing session data for user in JIT provisioning flow when the primary user store domain name is changed

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#13665]
**Describe the issue:**
When the primary user store domain name is changed, the following error occurs in the JIT provisioning flow.
```
[2022-05-11 15:05:20,594] [faf28829-5cc2-4f9f-be59-1daeb294b544] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework org.wso2.carbon.identity.application.authentication.framework.exception.FrameworkException: Error while storing session details of the authenticated user to the database
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.concludeFlow(DefaultAuthenticationRequestHandler.java:528)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:207)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:250)
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53)
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doGet(CommonAuthenticationServlet.java:43)
......
......
Caused by: org.wso2.carbon.identity.application.authentication.framework.exception.UserSessionException: Error while storing session data for user: WSO2.ORG/tharakaw of user store domain: null in tenant domain: carbon.super
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.storeSessionData(DefaultAuthenticationRequestHandler.java:695)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.concludeFlow(DefaultAuthenticationRequestHandler.java:526)
	... 57 more
Caused by: org.wso2.carbon.identity.application.authentication.framework.exception.UserSessionException: Unable to get the unique id of the user: WSO2.ORG/tharakaw.
	at org.wso2.carbon.identity.application.authentication.framework.util.FrameworkUtils.resolveUserIdFromUsername(FrameworkUtils.java:2640)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.storeSessionData(DefaultAuthenticationRequestHandler.java:688)
	... 58 more
```
**How to reproduce:**

1. Change the primary user store domain name by adding the following configuration.
[user_store]
type = "database_unique_id"
domain_name ="wso2.org"
2. Register a federated IDP and configure silent JIT provisioning.
3. Configure a service provider to use the federated IDP and make sure the "Assert identity using mapped local subject identifier" option is selected under the "Local & Outbound Authentication Configuration"
4. login to the service provider, and the above error would be observed.

**Expected behavior:**
The users should be able to log in without any errors event when the primary user store domain name is changed.

The issue occurs because when the domain passed is null, by default we have assumed that the user store domain is "PRIMARY"[1]. However, it is possible to change the primary user store domain name.

[1]https://github.com/wso2/carbon-identity-framework/blob/v5.18.187/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/util/FrameworkUtils.java#L2573

**Environment information** **:**
 - Product Version: [IS-5.11.0]

**Comment by somindatommy** [comment]
Closing this issue since the public has been fixed.
