### ISSUE TITLE
ErrorCode: SECRETM_65001 | message: Error while retrieving secret in a Migrated setup from 5.11.0 latest U2 pack to 5.12.0 beta3

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13679]
**How to reproduce:**
1. Get IS 5.11.0 GA pack from website and get it updated to latest u2 level 143
2. Get IS 5.12.0 beta 3 pack
3. Configure primary userstore for unique id jdbc US and db type as postgres 14.1
4. Get the migration client version v1.0.183
5. Run the migration client (Note:- Sample data such as SP(oidc,saml), IDP (fb), scope, roles, groups, users, secondory US, tenant, sample apps users and roles registered under a new tenant were created in the old IS pack before the migration. 

5.12.0 beta 3

```
[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"
offset = "1"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.identity_db]
#type = "Postgres" 
url = "jdbc:postgresql://localhost:5432/migrt2"
username = "postgres"
password = "wso2carbon"
driver = "org.postgresql.Driver"
[database.identity_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1; COMMIT"
validationInterval="30000"
defaultAutoCommit=false

[database.shared_db]
#type = "Postgres" 
url = "jdbc:postgresql://localhost:5432/migrt2"
username = "postgres"
password = "wso2carbon"
driver = "org.postgresql.Driver"
[database.shared_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1; COMMIT"
validationInterval="30000"
defaultAutoCommit=false

[system_applications]
read_only_apps = []

[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"

[keystore.internal]
file_name = "internal.jks"
type = "JKS"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"

```
7. Get the callback urls updated from managemnt console for myaccount and console to correct reg ex
8. Update the resident IDP > ibound auth > oauth > Identity Provider Entity ID to correct offset
9. Access console in the migrated pack
10. Go to Develop > Secrets > Try to list the secrets

Getting below error when listing secrets

![Screenshot from 2022-05-13 12-19-48](https://user-images.githubusercontent.com/31848014/168228605-ddad81b8-4e1b-44ed-8989-e1f35f835b2a.png)

```
[2022-05-13 12:19:39,616] [49ad1023-9b6e-4f79-a393-2bfdfac6771c] ERROR {org.wso2.carbon.identity.api.server.secret.management.v1.core.SecretManagementService} - errorCode: SECRETM_65001 | message: Error while retrieving secret for for the name: %s. org.wso2.carbon.identity.secret.mgt.core.exception.SecretManagementServerException: Secret management feature is not enabled
	at org.wso2.carbon.identity.secret.mgt.core.util.SecretUtils.handleServerException(SecretUtils.java:67)
	at org.wso2.carbon.identity.secret.mgt.core.SecretManagerImpl.validateSecretManagerEnabled(SecretManagerImpl.java:416)
	at org.wso2.carbon.identity.secret.mgt.core.SecretManagerImpl.getSecrets(SecretManagerImpl.java:111)
	at org.wso2.carbon.identity.api.server.secret.management.v1.core.SecretManagementService.getSecretsList(SecretManagementService.java:172)
	at org.wso2.carbon.identity.api.server.secret.management.v1.impl.SecretsApiServiceImpl.getSecretsList(SecretsApiServiceImpl.java:68)
	at org.wso2.carbon.identity.api.server.secret.management.v1.SecretsApi.getSecretsList(SecretsApi.java:139)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:117)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:106)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:133)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:61)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
Attaching wso2carboon.log

[wso2carbon.log](https://github.com/wso2/product-is/files/8684868/wso2carbon.log)

Such a issue is not available when you list secrets from console in a fresh default 5.12.0 beta 3 pack

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 IS 5.11.0 Latest U2 (143) to 5.12.0 beta 3 migration
postgres 14.1

**Comment by ShanikaWickramasinghe** [comment]
Observed this issue against DB2 11.5 env as well when migrated from 5.11.0 GA to 5.12.0 Beta3

**Comment by ashendes** [comment]
This was not observed during the 6.0.0 migration testing effort.
