### ISSUE TITLE
Cannot request an OAuth2 Access Token when the user_type = "LOCAL" in the WSO2 Identity Server 6.0.0

### ISSUE THREAD

**Issue by Achintha444** [wso2/product-is#13748]
**Describe the issue:**
When trying to request an OAuth 2 access token using the received SAML2 assertion it returns  _response code 400 for URL: https://localhost:9443/oauth2/token_  when the user type is LOCAL (this is the user_type in the deployment.toml file under the [oauth.grant_type.saml_bearer] tag). But this works in the previous WSO2 Identity Server version (5.11.0)  

**How to reproduce:**
- configure a OAuth/OpenID Connect service provider
- deploy the Travelocity sample application using tomcat8 (https://github.com/wso2/samples-is/releases)
- Modify the service provider you just created. Modify the following fields of the SAML configuration and click Update.
  Select the Enable Audience Restriction and Enable Recipient Validation fields and enter the following values:
  
  Audience : https://localhost:9443/oauth2/token
  
  Recipient : https://localhost:9443/oauth2/token
- Open the travelocity.properties file found in the <TOMCAT_HOME>/webapps/travelocity.com/WEB-INF/classes folder and edit the following configurations and restart the tomcat server.

  EnableOAuth2SAML2Grant=true
  OAuth2.ClientId=(enter the client id )
  OAuth2.ClientSecret= (enter the client secret )
- Add the following configuration to the <IS_HOME>/repository/conf/deployment.toml
  [oauth.grant_type.saml_bearer]
  user_type= "LOCAL" 
  
  change user_type field to "FEDERATED" when changing the user type
- acess travelocity.com site using tomcat8
- Click _Click here to login with SAML from Identity Server (Post binding or Redirect Binding)._ 
- Enter the username and password and click SIGN IN.
- Click Request OAuth2 Access Token to receive the access token.

_For more information - https://is.docs.wso2.com/en/latest/learn/setting-up-a-saml2-bearer-assertion-profile-for-oauth-2.0/#configure-oauthopenid-and-saml-sso_

**Expected behavior:**

<img width="810" alt="LOCAL - 5 11" src="https://user-images.githubusercontent.com/46097917/170254355-652760a9-59d0-42b6-addd-76c4dadfdfa6.png">

but it gives 

<img width="810" alt="Screenshot 2022-05-25 at 17 00 58" src="https://user-images.githubusercontent.com/46097917/170254511-5d41b8e6-8e05-440c-8895-3daaefd92dbc.png">

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - IS 6.0.0
 - Mac
 - DB2 11.5
 - JDBC
 - Firefox 91.0
 - Oracle JDK 11

---

**PS**
But this works when the user_type is set to FEDERATED (this is the same behaviour version 5.11.0 shows for this confiuration)

**Comment by Achintha444** [comment]
This is an extension of the above issue

**Describe the issue:**
As mentioned above when user_type = "FEDERATED" the access token was returned. But when trying to access the _Users SCIM endpoint_ using

  curl -v -k --header "Authorization: Bearer <token-id>" https://localhost:9443/wso2/scim/Users

It returned error 

  _{"Errors":[{"code":"500","description":"User is not authorized to perform provisioning"}]}_

This was done from the admin account.

**Expected behavior:**
This process supposed to return the details of the Users in the Identity Server.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Same as above

**Comment by piraveena** [comment]
> This is an extension of the above issue
> 
> **Describe the issue:** As mentioned above when user_type = "FEDERATED" the access token was returned. But when trying to access the _Users SCIM endpoint_ using
> 
> curl -v -k --header "Authorization: Bearer " https://localhost:9443/wso2/scim/Users
> 
> It returned error
> 
> _{"Errors":[{"code":"500","description":"User is not authorized to perform provisioning"}]}_
> 
> This was done from the admin account.
> 
> **Expected behavior:** This process supposed to return the details of the Users in the Identity Server.
> 
> **Environment information** (_Please complete the following information; remove any unnecessary fields_) **:**
> 
> * Same as above

@Achintha444 the API URL `https://localhost:9443/wso2/scim/Users` you used to get the scim2 users is invalid. It is invoking scim1 api.

Also, please note that
@Achintha444 only the ManagementApp can access the management REST APIs. Please refer to this issue https://github.com/wso2/product-is/issues/12852. An app can be configured as a management app during the creation time.

If the app is not a management app, server will respond as below.
```

{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "detail": "Operation is not permitted. You do not have permissions to make this request.",
    "status": 403
}
```

**Comment by piraveena** [comment]
SAML Bearer token flow is failing with below debug logs when user type is LOCAL
```
e domain :PRIMARY. Tenant domain : carbon.super . Authenticated subjectIdentifier : 29f12271-5ed2-4cb4-bc7d-ab3db3e45382
[2022-06-15 12:02:43,035] [6ad82c8a-2571-4215-98bb-f23c51635669] DEBUG {org.wso2.carbon.identity.oauth2.token.handlers.grant.saml.SAML2BearerGrantHandler} - Checking whether the user exists in local user store
[2022-06-15 12:02:43,042] [6ad82c8a-2571-4215-98bb-f23c51635669] DEBUG {org.wso2.carbon.identity.oauth2.token.handlers.grant.saml.SAML2BearerGrantHandler} - User 29f12271-5ed2-4cb4-bc7d-ab3db3e45382 doesn't exist in local user store.
[2022-06-15 12:02:43,043] [6ad82c8a-2571-4215-98bb-f23c51635669] DEBUG {org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer} - Error occurred while validating grant org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: User not found in local user store
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.saml.SAML2BearerGrantHandler.setLocalUser(SAML2BearerGrantHandler.java:1327)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.saml.SAML2BearerGrantHandler.setUserInMessageContext(SAML2BearerGrantHandler.java:1231)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.saml.SAML2BearerGrantHandler.setValuesInMessageContext(SAML2BearerGrantHandler.java:519)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.saml.SAML2BearerGrantHandler.validateGrant(SAML2BearerGrantHandler.java:199)
	at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.issue(AccessTokenIssuer.java:312)
	at org.wso2.carbon.identity.oauth2.OAuth2Service.issueAccessToken(OAuth2Service.java:319)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:321)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:142)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.wso2.carbon.webapp.mgt.filter.AuthorizationHeaderFilter.doFilter(AuthorizationHeaderFilter.java:128)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:117)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:119)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:109)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:61)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

[2022-06-15 12:02:43,057] [6ad82c8a-2571-4215-98bb-f23c51635669] DEBUG {org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer} - Invalid Grant provided by the client Id: jFcwyOAl22BmciZhwgbmufqfKJwa
[2022-06-15 12:02:43,058] [6ad82c8a-2571-4215-98bb-f23c51635669] DEBUG {org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer} - OAuth-Error-Code=invalid_grant client-id=jFcwyOAl22BmciZhwgbmufqfKJwa grant-type=urn:ietf:params:oauth:grant-type:saml2-bearer scope=
[2022-06-15 12:02:43,059] [6ad82c8a-2571-4215-98bb-f23c51635669] DEBUG {org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer} - Triggering access token post issuer listeners for client: jFcwyOAl22BmciZhwgbmufqfKJwa
[2022-06-15 12:04
```

**Comment by Achintha444** [comment]
Doc issue is submitted regarding this issue as well
https://github.com/wso2/product-is/issues/13975
