### ISSUE TITLE
ERROR {org.wso2.carbon.is.migration.MigrationClientImpl} - Migration process was stopped. while scanning a simple key  in 'reader', line 367 when generating dry run reports in migration

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13854]
**How to reproduce:**
1. Get IS 5.11.0 U2 updated for latest level 151
2. Get IS 6.0.0 m3 pack
3. Point for mssql 2019

```
[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"
offset = "1"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.identity_db]

url = "jdbc:sqlserver://localhost:1433;databaseName=migrt4;SendStringParametersAsUnicode=false"
username = "sa"
password = "MyPassword001"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
[database.identity_db.pool_options]
maxActive = "80"
maxWait="6000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false

[database.shared_db]
url = "jdbc:sqlserver://localhost:1433;databaseName=migrt4;SendStringParametersAsUnicode=false"
username = "sa"
password = "MyPassword001"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
[database.shared_db.pool_options]
maxActive = "80"
maxWait="6000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false



[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

[system_applications]
read_only_apps = []

```
4. Create some data using 5.11.0 pack (apps,users,roles,groups,scopes,workflows etc)
5. Get the migration resources and copy it for relavent places https://github.com/wso2-extensions/identity-migration-resources/releases/tag/v1.0.185
6. In migration-config.yaml file uncomment the paramater reportPath ( it was present in 5 places. uncommented from all the 5 places and added the absolute path as below) as instructed in the doc https://is.docs.wso2.com/en/latest/setup/migrating-userstore-managers/

`       reportPath:/home/shanika/WSO2/5.12.0/MigrationTesting/dryrunreport/reportpath
`
`reportPath: /home/shanika/WSO2/5.12.0/MigrationTesting/dryrunreport/reportpath`

tried both above ways

7. Run  the migration client with dry run

`sh wso2server.sh -Dmigrate -Dcomponent=identity -DdryRun
`

Getting below exception

```
ce {super-tenant}
[2022-06-06 19:45:51,237] []  INFO {org.wso2.carbon.core.deployment.DeploymentInterceptor} - Deploying Axis2 service: mex-ut {super-tenant}
[2022-06-06 19:45:51,241] []  INFO {org.wso2.carbon.core.deployment.DeploymentInterceptor} - Deploying Axis2 service: mex-ut2 {super-tenant}
[2022-06-06 19:45:51,925] []  INFO {org.wso2.carbon.core.init.CarbonServerManager} - Repository       : /home/shanika/WSO2/5.12.0/MigrationTesting/dryrunreport/600/wso2is-6.0.0-m3/repository/deployment/server/
[2022-06-06 19:45:51,970] []  INFO {org.wso2.carbon.core.multitenancy.eager.TenantLoadingConfig} - Using tenant lazy loading policy...
[2022-06-06 19:45:51,996] []  INFO {org.wso2.carbon.core.internal.permission.update.PermissionUpdater} - Permission cache updated for tenant -1234
[2022-06-06 19:45:52,226] []  INFO {org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent} - Executing Migration client : org.wso2.carbon.is.migration.MigrationClientImpl
[2022-06-06 19:45:52,243] []  INFO {org.wso2.carbon.is.migration.config.Config} -  WSO2 Product Migration Service Task : Loading Migration Configs, PATH:/home/shanika/WSO2/5.12.0/MigrationTesting/dryrunreport/600/wso2is-6.0.0-m3/migration-resources/migration-config.yaml
[2022-06-06 19:45:52,288] [] ERROR {org.wso2.carbon.is.migration.MigrationClientImpl} - Migration process was stopped. while scanning a simple key
 in 'reader', line 367, column 8:
           reportPath:/home/shanika/WSO2/5. ... 
           ^
could not find expected ':'
 in 'reader', line 368, column 8:
           # If migrating only few tenants, ... 
           ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465)
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:199)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:199)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:410)
	at org.wso2.carbon.is.migration.util.Utility.loadMigrationConfig(Utility.java:94)
	at org.wso2.carbon.is.migration.config.Config.getInstance(Config.java:64)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:39)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

[2022-06-06 19:45:52,294] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-06-06 19:45:52,294] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-06-06 19:45:52,295] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-06-06 19:45:52,295] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-06-06 19:45:52,295] []  INFO 
```
Attaching carbon.log

[wso2carbon.log](https://github.com/wso2/product-is/files/8845107/wso2carbon.log)

attaching migration-config.yaml
[yaml.zip](https://github.com/wso2/product-is/files/8845247/yaml.zip)

Needs to get the migration guide updated with the correct information if the way I have included the reportPath: is wrong

A report was not generated in the given folder path

**Env**
mssql 2019
IS 5.11.0 U2 151 to IS 6.0.0 m3
migration client v185
jdbc
java 1.8

**Comment by ashendes** [comment]
The paths need to be given as string values.

**Comment by ShanikaWickramasinghe** [comment]
Was able to get the dry run reports generated. There are 3 items missing in the migration guide on how to do this successfully without en counting above reported errors. Hence created a doc issue to get the migration guide fixed. https://github.com/wso2/product-is/issues/13924. Hence closing the issue


- [ ] Mention you need to pass the reportPath as a string value
- [ ]  Mention you need to define reportPath under a parameter config
- [ ]  Mention that you need to uncomment and include reportPath in the migration-config.yaml uner each migrator that you wants to get the reports generated ( At the moment there are 5 occurences in the migration-config.yaml to uncomment)
