### ISSUE TITLE
IllegalStateException: The write format 2 is larger than the supported format 1, and the file was not opened in read-only mode when running H2 Migration Tool

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#13939]
**How to reproduce:**
1. Clone https://github.com/wso2/samples-is/tree/master/h2-migration-tool > master branch
2. Get IS 5.11.0 update level 157 pack and IS 6.0.0 m4 pack
3. Up another IS server with offset 2 to be used as external ldap
4. Point the ldap in both the old and new IS pack

```
[user_store]
type = "read_write_ldap_unique_id"
connection_url = "ldap://localhost:10391"
connection_name = "uid=admin,ou=system"
connection_password = "admin"
base_dn = "dc=wso2,dc=org"      #refers the base dn on which the user and group search bases will be generated

[database.identity_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2IDENTITY_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
username = "wso2carbon"
password = "wso2carbon"

[database.shared_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
username = "wso2carbon"
password = "wso2carbon"

```
5. Create some data (users,roles,groups,apps,idp,scope) from 5.11.0 pack
6. Down the 5.11.0 pack
7. Run the h2 migration tool 
`bash migration.sh
`
8. Will ask for old db and new db paths. Input them

Getting below exception after input the database paths

```
Welcome to the H2 DB Migration Tool!

Provide a directory path for the old db files and a directory path to store the new files.

Enter the path to the previous database files: eg. <file-path>/old-databases, <OLD_IS_HOME>/repository/database 
/home/shanika/WSO2/IS600/MigrationTesting/fixverify/embeddedh2/5110wum/wum157/wso2is-5.11.0/repository/database

Enter the path to store the newly created files: eg. <file-path>/new-databases 
/home/shanika/WSO2/IS600/MigrationTesting/fixverify/embeddedh2/migrateddb
--2022-06-15 14:43:14--  https://repo1.maven.org/maven2/com/h2database/h2/2.1.210/h2-2.1.210.jar
Resolving repo1.maven.org (repo1.maven.org)... 151.101.40.209
Connecting to repo1.maven.org (repo1.maven.org)|151.101.40.209|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2531599 (2.4M) [application/java-archive]
Saving to: ‘h2-2.1.210.jar’

h2-2.1.210.jar                   100%[==========================================================>]   2.41M   101KB/s    in 33s     

2022-06-15 14:43:48 (75.8 KB/s) - ‘h2-2.1.210.jar’ saved [2531599/2531599]

--2022-06-15 14:43:48--  https://repo1.maven.org/maven2/com/h2database/h2/1.4.199/h2-1.4.199.jar
Resolving repo1.maven.org (repo1.maven.org)... 146.75.92.209
Connecting to repo1.maven.org (repo1.maven.org)|146.75.92.209|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2178179 (2.1M) [application/java-archive]
Saving to: ‘h2-1.4.199.jar’

h2-1.4.199.jar                   100%[==========================================================>]   2.08M   330KB/s    in 7.6s    

2022-06-15 14:43:57 (279 KB/s) - ‘h2-1.4.199.jar’ saved [2178179/2178179]

Exporting database...
Exception in thread "main" org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:205)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.h2.tools.Script.process(Script.java:118)
	at org.h2.tools.Script.runTool(Script.java:100)
	at org.h2.tools.Script.main(Script.java:45)
Caused by: java.lang.IllegalStateException: The write format 2 is larger than the supported format 1, and the file was not opened in read-only mode [1.4.199/5]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:705)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:401)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	... 19 more

```
![Screenshot from 2022-06-15 14-43-52](https://user-images.githubusercontent.com/31848014/173792366-59bc37d9-dc94-408a-8c10-534e0a3dbfd4.png)
![Screenshot from 2022-06-15 14-44-34](https://user-images.githubusercontent.com/31848014/173792397-eccb8245-c043-4049-86b7-c33091a625a9.png)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 5.11.0 update level 157 to IS 6.0.0 m4 migration
migration client v 187
embedded H2

**Comment by ShanikaWickramasinghe** [comment]
Closing the Issue as a issue created to get the migration guide fixed related to this issue https://github.com/wso2/product-is/issues/13965
