### ISSUE TITLE
Request path authentication fails when SSO session binding is enabled

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#13946]
**Describe the issue:**
At [1], it checks whether there are no cookies in the request assuming the flow should break if the commonauthId cookie is unavailable. But another functionality was added later that the commonauthId is read from a query param as well [2]. When the request path authenticator is executed and there are no cookies against the IdP domain, the [1] becomes true, and the flow breaks. But it could be continued and flow can be completed successfully since the commonAuthId comes as a param there.

**How to reproduce:**
- Create a service provider
- Enable basic request path authentication
- Enable SSO session based token binding
- Disable login consent
- Initiate a request path authentication request in an incognito browser
- Following error is returned to the client app
```
error_description=Server+error+occurred+while+performing+authorization&error=server_error
```
- Following can be seen in the debug logs
```
DEBUG {org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint} - Server error occurred while performing authorization org.apache.oltu.oauth2.common.exception.OAuthSystemException: Failed to retrieve token binding value.
	at org.wso2.carbon.identity.oauth2.token.bindings.impl.SSOSessionBasedTokenBinder.retrieveTokenBindingValueFromRequest(SSOSessionBasedTokenBinder.java:93)
	at org.wso2.carbon.identity.oauth2.token.bindings.impl.SSOSessionBasedTokenBinder.getOrGenerateTokenBindingValue(SSOSessionBasedTokenBinder.java:80)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleSuccessAuthorization(OAuth2AuthzEndpoint.java:1100)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleUserConsent(OAuth2AuthzEndpoint.java:987)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleApproveAlwaysWithPromptForNewConsent(OAuth2AuthzEndpoint.java:2231)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleConsent(OAuth2AuthzEndpoint.java:1886)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.doUserAuthorization(OAuth2AuthzEndpoint.java:1858)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleSuccessfulAuthentication(OAuth2AuthzEndpoint.java:731)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleAuthenticationResponse(OAuth2AuthzEndpoint.java:702)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.authorize(OAuth2AuthzEndpoint.java:255)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleAuthFlowThroughFramework(OAuth2AuthzEndpoint.java:2509)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleInitialAuthorizationRequest(OAuth2AuthzEndpoint.java:854)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.authorize(OAuth2AuthzEndpoint.java:253)

```

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/41e6c1db068fb04cc5e92ffa918df6c1587be858/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/bindings/impl/SSOSessionBasedTokenBinder.java#L92
[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/41e6c1db068fb04cc5e92ffa918df6c1587be858/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/bindings/impl/SSOSessionBasedTokenBinder.java#L98

**Comment by ShamodyaHashantha** [comment]
The same issue still occurs in the 5.10.0 version.

[1] ([https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/35d2b91f19d322dd2e923025d1c90c257cee024d/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/bindings/impl/SSOSessionBasedTokenBinder.java#L78)](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/35d2b91f19d322dd2e923025d1c90c257cee024d/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/bindings/impl/SSOSessionBasedTokenBinder.java#L78](https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/35d2b91f19d322dd2e923025d1c90c257cee024d/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/bindings/impl/SSOSessionBasedTokenBinder.java#L78)%5D(https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/35d2b91f19d322dd2e923025d1c90c257cee024d/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/bindings/impl/SSOSessionBasedTokenBinder.java#L78))
