### ISSUE TITLE
Need to Add a Descriptive Error Message when Disabling a Federated IDP that is already Referred by a SP

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#13958]
**Describe the issue:**
When a federated IDP is already configured as the federated authenticator of a SP, we are not allowing a user to disable that IDP, by validating and throwing an error at [1]. Currently we are getting the following error at the UI:

<img width="520" alt="image" src="https://user-images.githubusercontent.com/47671237/174219002-6ca09e7c-7ac2-46bc-9259-5a19514569fd.png">

 with the following error log at the console.
```
[2022-06-17 08:57:21,652] [54a486ba-14bf-4ca4-b63b-48894f3cc9be] ERROR {org.wso2.carbon.idp.mgt.IdentityProviderManager} - Error while updating IdP with name NEW-TEST org.wso2.carbon.idp.mgt.IdentityProviderManagementException: Error in disabling identity provider as it is referred by service providers.
	at org.wso2.carbon.identity.application.mgt.listener.ApplicationIdentityProviderMgtListener.validateIdpDisable(ApplicationIdentityProviderMgtListener.java:184)
	at org.wso2.carbon.identity.application.mgt.listener.ApplicationIdentityProviderMgtListener.doPreUpdateIdP(ApplicationIdentityProviderMgtListener.java:90)
	at org.wso2.carbon.idp.mgt.IdentityProviderManager.updateIdP(IdentityProviderManager.java:2319)
	at org.wso2.carbon.idp.mgt.IdentityProviderManagementService.updateIdP(IdentityProviderManagementService.java:373)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
...

[2022-06-17 08:57:21,705] [54a486ba-14bf-4ca4-b63b-48894f3cc9be] ERROR {org.wso2.carbon.idp.mgt.ui.client.IdentityProviderMgtServiceClient} - Error in updating the Identity Provider for a given tenant org.wso2.carbon.idp.mgt.stub.IdentityProviderMgtServiceIdentityProviderManagementExceptionException: IdentityProviderMgtServiceIdentityProviderManagementExceptionException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
...
```

**How to reproduce:**
1. Go to management console --> Identity Providers --> Add and create a new IDP with some dummy details.
2. Create a Service Provider by Service Providers --> Add.
3. Go to Local & Outbound Authentication Configuration of this SP and under Federated Authentication select the newly added IDP.
4. Go back to Identity Providers --> List and click disable icon of the created IDP.
5. Note that the above error box will popup. 

**Expected behavior:**
The error popup should display a meaningful message. Can display the original error message shown in the console: `Error in disabling identity provider as it is referred by service providers.` instead of the current error text.

[1] https://github.com/wso2/carbon-identity-framework/blob/2043d9d344f205252bb0105126d90c61f821f0a5/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/listener/ApplicationIdentityProviderMgtListener.java#L90

Related issue: https://github.com/wso2/product-is/issues/13771

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
