### ISSUE TITLE
Issue in migrating  from version 5.9 to 5.11

### ISSUE THREAD

**Issue by moazGalbat** [wso2/product-is#14051]
I'm trying to migrate from version 5.9 to 5.11 using latest (identity migration resource)[https://github.com/wso2-extensions/identity-migration-resources/releases/tag/v1.0.189]
all step completed succesfully except for ClaimDataMigrator and it shows the following error:

[2022-06-29 00:15:35,151] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 5.11.0, Migration Step : ClaimDataMigrator of order : 12 is starting........................... 
[2022-06-29 00:15:35,628] [] ERROR {org.wso2.carbon.is.migration.service.ClaimDataMigrator} - Error while migrating claim data org.wso2.carbon.identity.claim.metadata.mgt.exception.ClaimMetadataClientException: Invalid Claim URI : http://wso2.org/claims/identity/accountState for Claim Dialect : http://wso2.org/claims
	at org.wso2.carbon.identity.claim.metadata.mgt.dao.ClaimDAO.getClaimId(ClaimDAO.java:169)
	at org.wso2.carbon.identity.claim.metadata.mgt.dao.ExternalClaimDAO.addExternalClaim(ExternalClaimDAO.java:76)
	at org.wso2.carbon.identity.claim.metadata.mgt.dao.CacheBackedExternalClaimDAO.addExternalClaim(CacheBackedExternalClaimDAO.java:71)
	at org.wso2.carbon.is.migration.service.ClaimDataMigrator.addExternalClaimMapping(ClaimDataMigrator.java:329)
	at org.wso2.carbon.is.migration.service.ClaimDataMigrator.migrateClaimData(ClaimDataMigrator.java:218)
	at org.wso2.carbon.is.migration.service.ClaimDataMigrator.migrate(ClaimDataMigrator.java:102)
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:85)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:149)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

**Environment information** 
 - Product Version: [IS 5.9.0]
 - Database: [MySQL]
 - Userstore: [customUserStore]

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
