### ISSUE TITLE
Getting Could not load Logmanager "org.apache.juli.ClassLoaderLogManager" error in the server startup

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#14052]
**Describe the issue:**
Getting below error in the server startup
```
hasinthaindrajee@Hasinthas-MacBook-Pro bin % sh wso2server.sh 
JAVA_HOME environment variable is set to /Library/Java/JavaVirtualMachines/jdk-11.0.8.jdk/Contents/Home
CARBON_HOME environment variable is set to /Users/hasinthaindrajee/Downloads/wso2is-6.0.0-alpha
Using Java memory options: -Xms256m -Xmx1024m
Could not load Logmanager "org.apache.juli.ClassLoaderLogManager"
java.lang.ClassNotFoundException: org.apache.juli.ClassLoaderLogManager
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    at java.logging/java.util.logging.LogManager$1.run(LogManager.java:239)
    at java.logging/java.util.logging.LogManager$1.run(LogManager.java:223)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.logging/java.util.logging.LogManager.<clinit>(LogManager.java:223)
    at java.logging/sun.util.logging.internal.LoggingProviderImpl.demandJULLoggerFor(LoggingProviderImpl.java:408)
    at java.logging/sun.util.logging.internal.LoggingProviderImpl.demandLoggerFor(LoggingProviderImpl.java:436)
    at java.base/jdk.internal.logger.DefaultLoggerFinder.getLogger(DefaultLoggerFinder.java:157)
    at java.base/jdk.internal.logger.LazyLoggers.getLoggerFromFinder(LazyLoggers.java:389)
    at java.base/jdk.internal.logger.LazyLoggers.getLazyLogger(LazyLoggers.java:444)
    at java.base/jdk.internal.logger.LazyLoggers.getLogger(LazyLoggers.java:414)
    at java.base/java.lang.System.getLogger(System.java:1660)
    at jdk.management.agent/sun.management.jmxremote.ConnectorBootstrap.<clinit>(ConnectorBootstrap.java:866)
    at jdk.management.agent/jdk.internal.agent.Agent.startLocalManagementAgent(Agent.java:318)
    at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:450)
    at jdk.management.agent/jdk.internal.agent.Agent.startAgent(Agent.java:599)
Error: Could not find or load main class org.wso2.carbon.bootstrap.Bootstrap Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.bootstrap.Bootstrap
```

**Expected behavior:**
Server should run in JDK11 without any issues

**Environment information**  **:**
 - Product Version:  IS 6.0.0,
 - OS: Mac-M1
 - JDK - 11.0.8

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by hasinthaindrajee** [comment]
This looks like due to a permission issue. This issue occurs when I start the pack in the download directory itself. When I moved to a different location it started properly.

**Comment by piraveena** [comment]
Tested and Could not reproduce this issue with M1 architecture mac with JDK11. Closing this issue based on above comment
