### ISSUE TITLE
[Migration 5.11.0] Add support to configure internal/admin role created during 5.11.0 migration

### ISSUE THREAD

**Issue by mevan-karu** [wso2/product-is#14085]
**Describe the issue:**
During 5.11.0 migration we're creating the admin role for super-tenant admin with the same name configured in the `AdminRole` in `repository/conf/user-mgt.xml` in the `internal` domain as `internal/admin` [1]. But in case if the old setup already has an `internal/admin` role, there will be a conflict during the migration.   

**How to reproduce:**
1. Get a 5.10.0 pack.
2. Populate some user data, role data. 
3. Create a new role named `internal/admin`.
4. Get a 5.11.0 pack and start the migration [2].
5. You should get the following migration error while running the migration.
```
TID: [-1234] [] [2022-01-28 15:33:04,317] [] ERROR {org.wso2.carbon.is.migration.MigrationClientImpl} - Migration process was stopped. org.wso2.carbon.identity.core.migrate.MigrationClientException:  WSO2 Product Migration Service Task : Error while migrating external role permissions.
        at org.wso2.carbon.is.migration.service.v5110.migrator.GroupsAndRolesMigrator.migrate(GroupsAndRolesMigrator.java:146)
        at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)
...
Caused by: org.wso2.carbon.user.core.UserStoreException: 30012 - RoleExistingRole name: admin exists in the system. Please pick another role name.
        at org.wso2.carbon.user.core.common.AbstractUserStoreManager.handleRoleAlreadyExistException(AbstractUserStoreManager.java:7606)
        at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doAddInternalRole(AbstractUserStoreManager.java:7573)
```

**Expected behavior:**
Customer should be able to rename the new admin role during the migration.

**Suggested solution**
- Configure a new admin role name for the new setup by configuring the `<AdminRole>` configuration in `repository/conf/user-mgt.xml`.
- Introduce a new configuration to migration client to configure the old admin group name(ie. `AdminRole` configured in old IS setup's `repository/conf/user-mgt.xml/user-mgt.xml`). 
- Update the migration client logic in here [3] to retrieve the old admin group and bind permissions to the new role.

[1] https://github.com/wso2-extensions/identity-migration-resources/blob/master/components/org.wso2.is.migration/migration-service/src/main/java/org/wso2/carbon/is/migration/service/v5110/migrator/GroupsAndRolesMigrator.java#L164-L169
[2] https://is.docs.wso2.com/en/latest/setup/migration-guide/
[3] https://github.com/wso2-extensions/identity-migration-resources/blob/master/components/org.wso2.is.migration/migration-service/src/main/java/org/wso2/carbon/is/migration/service/v5110/migrator/GroupsAndRolesMigrator.java#L172-L176

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
