### ISSUE TITLE
Username and Password not accepted error related to email sending comes by default when locking a user account via console

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14094]
**How to reproduce:**

1. Access console
2. Add a new user
3. Enable the toggle to Lock the user

In the back-end console observed below error log

```
icyFinder} - Initializing of policy store is finished at :  Sun Jul 03 21:30:22 IST 2022
[2022-07-03 21:30:24,779] [2af9fd93-f58b-438c-99e6-fe67388ca14e] ERROR {org.wso2.carbon.event.output.adapter.email.EmailEventAdapter} - Exception occurred when sending email to shanikanishadhi1992@gmail.com. 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials i4-20020a17090332c400b0016a214e4afasm19352268plr.125 - gsmtp
javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials i4-20020a17090332c400b0016a214e4afasm19352268plr.125 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:965)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:876)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:780)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.wso2.carbon.event.output.adapter.email.EmailEventAdapter$EmailSender.run(EmailEventAdapter.java:367)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[2022-07-03 21:30:24,779] [2af9fd93-f58b-438c-99e6-fe67388ca14e] ERROR {org.wso2.carbon.event.output.adapter.email.EmailEventAdapter} - Event dropped at Output Adapter 'EmailPublisher' for tenant id '1', Error in message format, 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials i4-20020a17090332c400b0016a214e4afasm19352268plr.125 - gsmtp
javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials i4-20020a17090332c400b0016a214e4afasm19352268plr.125 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:965)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:876)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:780)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.wso2.carbon.event.output.adapter.email.EmailEventAdapter$EmailSender.run(EmailEventAdapter.java:367)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)


```

Have we enabled email sending by default when locking a user account. I didnt add email sender configs to toml file as I remembered I didnt notice such a email sending error earlier when locking a user account

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
IS 6.0.0 alpha 2
h2 default

**Comment by piraveena** [comment]
This is happening becuase, there are dummy values added in the default.json file. When the account is locked, email notification will be sent.  So you need to configure those urls. Even if you didn't configure it, and email notification are sent for account locking, you will again get this error. 
So you have two options:
1. You need to configure correct email id
2. Do not send emails when account is locked.

If you don't want to send emails for account locking, you can go with option2. Else, you can configure correct email. This is expected behaviour when email notifications are configured and the sending email account is invalid or not available.
