### ISSUE TITLE
Runinng the pack windows as a service fails due to NoClassDefFound Error against OpenJDK 17.0.2.1 and Oracle JDK 17.0.3.1

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14148]
**How to reproduce:**

1. Follow https://is.docs.wso2.com/en/latest/setup/installing-as-a-windows-service/
2. carbon_home set for IS-Home
3. JAVA_HOME is set
4. Download YASJW 12.14 version
5. Replace the wrapper.conf with IS packs wrapper.conf (steps  mentioned in above link)
6. run RunConsole.bat

Getting below Error backend

![image](https://user-images.githubusercontent.com/31848014/177822115-108c5c61-06d0-4bde-952e-0edc953d0e3e.png)
```

C:\yajsw-stable-12.14\yajsw-stable-12.14\bat>call setenv.bat
"java" -Xmx30m -Dwrapper_home="C:\yajsw-stable-12.14\yajsw-stable-12.14\bat\/.." -Djna_tmpdir="C:\yajsw-stable-12.14\yajsw-stable-12.14\bat\/../tmp" -Djava.net.preferIPv4Stack=true --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED -jar "C:\yajsw-stable-12.14\yajsw-stable-12.14\bat\/../wrapper.jar" -c "C:\yajsw-stable-12.14\yajsw-stable-12.14\bat\/../conf/wrapper.conf"
YAJSW: yajsw-stable-12.14
OS   : Windows 11/10.0/amd64
JVM  : Oracle Corporation/17.0.2/C:\shanika\jdk\openjdk\openjdk-17.0.2_windows-x64_bin\jdk-17.0.2/64
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
        at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
        at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
        at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
        at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
        at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:209)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:107)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:85)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
        at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
        at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:59)
        at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
        at groovy.lang.Binding.<init>(Binding.java:33)
        at org.rzo.yajsw.config.groovy.ConfigurationBinding.<init>(ConfigurationBinding.java:17)
        at org.rzo.yajsw.config.groovy.GInterpolator.<init>(GInterpolator.java:31)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.rzo.yajsw.config.YajswConfigurationImpl.createGInterpolatornew(YajswConfigurationImpl.java:422)
        at org.rzo.yajsw.config.YajswConfigurationImpl.init(YajswConfigurationImpl.java:174)
        at org.rzo.yajsw.config.YajswConfigurationImpl.<init>(YajswConfigurationImpl.java:139)
        at org.rzo.yajsw.config.YajswConfigurationImpl.<init>(YajswConfigurationImpl.java:122)
        at org.rzo.yajsw.wrapper.WrappedProcessFactory.createProcess(WrappedProcessFactory.java:45)
        at org.rzo.yajsw.wrapper.WrappedProcessFactory.createProcessList(WrappedProcessFactory.java:61)
        at org.rzo.yajsw.WrapperExe.doConsole(WrapperExe.java:640)
        at org.rzo.yajsw.WrapperExe.executeCommand(WrapperExe.java:156)
        at org.rzo.yajsw.WrapperExe.main(WrapperExe.java:124)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.rzo.yajsw.boot.WrapperExeBooter.main(WrapperExeBooter.java:49)
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.rzo.yajsw.boot.WrapperExeBooter.main(WrapperExeBooter.java:49)
Caused by: java.lang.IllegalAccessError: class org.rzo.yajsw.wrapper.AbstractWrappedProcess (in unnamed module @0x100fc185) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x100fc185
        at org.rzo.yajsw.wrapper.AbstractWrappedProcess.<clinit>(AbstractWrappedProcess.java:242)
        at org.rzo.yajsw.wrapper.WrappedProcessFactory.createProcess(WrappedProcessFactory.java:38)
        at org.rzo.yajsw.wrapper.WrappedProcessFactory.createProcess(WrappedProcessFactory.java:46)
        at org.rzo.yajsw.wrapper.WrappedProcessFactory.createProcessList(WrappedProcessFactory.java:61)
        at org.rzo.yajsw.WrapperExe.doConsole(WrapperExe.java:640)
        at org.rzo.yajsw.WrapperExe.executeCommand(WrapperExe.java:156)
        at org.rzo.yajsw.WrapperExe.main(WrapperExe.java:124)
        ... 5 more
```

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
openjdk 17.0.2.1 and oracle JDK 17.0.3.1
YAJSW 12.14
windows 11
IS 6.0.0 alpha 3 snapshot

**Comment by Thumimku** [comment]
1. Search for ```if %JAVA_VERSION% GEQ 110 set JAVA_VER_BASED_OPTS=```
2. You will find several --add-opens command as values
3. Add as first command like
`if %JAVA_VERSION% GEQ 110 set JAVA_VER_BASED_OPTS=--add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED .......`

**Comment by ShanikaWickramasinghe** [comment]
Getting the same Error with those steps too

**Comment by ShanikaWickramasinghe** [comment]
@Thumimku 171 line is as below

if %JAVA_VERSION% GEQ 110 set JAVA_VER_BASED_OPTS=--add-opens=if %JAVA_VERSION% GEQ 110 set JAVA_VER_BASED_OPTS=--add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens java.rmi/sun.rmi.transport=ALL-UNNAMED  --add-opens=java.base/java.io=ALL-UNNAMED

**Comment by Thumimku** [comment]
if %JAVA_VERSION% GEQ 110 set JAVA_VER_BASED_OPTS=--add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens java.rmi/sun.rmi.transport=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED

**Comment by ShanikaWickramasinghe** [comment]
Tried the above command and it didnt work

**Comment by ShanikaWickramasinghe** [comment]
Getting the same error for installService.bat command too in https://is.docs.wso2.com/en/latest/setup/installing-as-a-windows-service/. Pls check this too with the planned fix

![image](https://user-images.githubusercontent.com/31848014/177930599-e5faca48-494c-4412-95d7-a0cee16c232e.png)

**Comment by Thumimku** [comment]
can try using updated YAJSW, (https://sourceforge.net/projects/yajsw/files/yajsw/yajsw-stable-13.03/)

**Comment by ShanikaWickramasinghe** [comment]
With YAJSW 13.03
Oracle JDK 17.0.3.1
windows 11

**with wso2server.bat file line no 171 replaced as above command out put** 

![image](https://user-images.githubusercontent.com/31848014/177979758-34d95c06-a737-42c0-89b0-8b0b40ea1127.png)

![image](https://user-images.githubusercontent.com/31848014/177980285-8d12d97f-4a44-4e62-ae6a-e55ff974cef4.png)

![image](https://user-images.githubusercontent.com/31848014/177980355-b5f8c96c-b76f-4062-b92a-cd8dc3f9bf47.png)

**without replacing the wso2server.bat file line no 171 ( with default file) output**

![image](https://user-images.githubusercontent.com/31848014/177983641-e40f72e9-aeaf-4e80-a79a-8e4337947b6d.png)
![image](https://user-images.githubusercontent.com/31848014/177983711-10313df1-bee5-4a11-a992-97d6da342da8.png)

**Comment by ThumulaPerera** [comment]
With YAJSW 12.16
Oracle JDK 17.0.3.1
windows 10

![12.16](https://user-images.githubusercontent.com/42399179/177985308-7a7f144e-d0e1-405a-8cc3-6d104fe3e65e.PNG)

**Comment by ThumulaPerera** [comment]
With YAJSW 13.01 (beta)
Oracle JDK 17.0.3.1
windows 10
![13.01](https://user-images.githubusercontent.com/42399179/177987746-64ee51bd-6000-4662-820e-a992530a3f91.PNG)

**Comment by ThumulaPerera** [comment]
@ShanikaWickramasinghe @Thumimku 

The issue can be resolved by following the below steps.

1. Download the latest version (13.03) of YAJSW from [here](https://sourceforge.net/projects/yajsw/files/yajsw/yajsw-stable-13.03/yajsw-stable-13.03.zip/download).
2. Extract the constent of yajsw-stable-13.03.zip to <YAJSW_HOME>
3. Copy the wrapper.conf file found in the <IS_HOME>/bin/yajsw/ directory and paste it in the <YAJSW_HOME>/conf/ directory.
4. Delete the `wrapper.java.additional.4 = -XX:MaxPermSize=256m` line in wrapper.conf file
5. Rename the subsequent `wrapper.java.additional`  variables to be in consecutive order. 
       i.e. Rename `wrapper.java.additional.5` to `wrapper.java.additional.4`. Rename `wrapper.java.additional.6` to `wrapper.java.additional.5` and so on.

Refer the following extract from the final wrapper.conf file
![conf](https://user-images.githubusercontent.com/42399179/177993263-c79b2267-d8cc-40ee-b281-f5e985d3fd2d.PNG)

6. Set the `carbon_home` env variable 
7. Open a Windows command prompt and go to the <YAJSW_HOME>/bat/ directory.
8. Start the wrapper in console mode: `runConsole.bat`

The observed commandline output was as follows
![output-log-part1](https://user-images.githubusercontent.com/42399179/177995405-fdd09d71-b0fb-4737-9e5a-5cc33562783e.PNG)
![output-log-part2](https://user-images.githubusercontent.com/42399179/177995430-bcfb09af-13b1-4fed-8368-2582183bfb24.PNG)
![output-log-part3](https://user-images.githubusercontent.com/42399179/177995461-e9211108-a5cb-42ea-a9aa-95bdaa1d16a1.PNG)
![output-log-part4](https://user-images.githubusercontent.com/42399179/177995478-d03f92fb-b247-4676-904a-aee2e13fe0b4.PNG)
![output-log-part5](https://user-images.githubusercontent.com/42399179/177995499-dcdbbc9f-759c-401d-bd8c-c56b655b4f76.PNG)
![output-log-part6](https://user-images.githubusercontent.com/42399179/177995520-d17ead18-8526-4eb5-b0a8-d3d0e7f49b14.PNG)
![output-log-part7](https://user-images.githubusercontent.com/42399179/177995582-2927173c-6fbe-41dc-9a17-4105c4c74783.PNG)
![output-log-part8](https://user-images.githubusercontent.com/42399179/177995596-65595c4e-749b-4ec8-8424-ca217002a6d3.PNG)

**Comment by ShanikaWickramasinghe** [comment]
@ThumulaPerera pls attach the fixed wrapper.conf file for this git issue. Also did you do any change for the wso2server.bat file. Attach that too.

**Comment by ThumulaPerera** [comment]
wrapper.conf file
[wrapper.zip](https://github.com/wso2/product-is/files/9072391/wrapper.zip)

No changes were done to the wso2server.bat file

**Comment by ShanikaWickramasinghe** [comment]
Tested the attached fixed wrapper.conf with windows 11, Orac;e JDK 17.0.3.1, YAJSW 13.03.
Pack got started successfully with the fix.

Observed 1 error log among the startup logs. Check attached image 1. What could be the reason for that @Thumimku @ThumulaPerera 

```
error evaluating java_home : No such property: java_home for class: Script1
system.env 58
```


![image](https://user-images.githubusercontent.com/31848014/178006331-8ce10338-b68c-482b-8f1b-99fe8943a08b.png)

![image](https://user-images.githubusercontent.com/31848014/178006454-a2270bf8-2a4b-403d-8e13-cb77d0772f04.png)

Attaching logs

**Comment by ShanikaWickramasinghe** [comment]
@Thumimku for this issue, are we fixing the wrapper.conf file sending it inbuilt in the pack or are we asking the users to get the script fixed manually. If we sending the fixed wrapper inbuilt in the pack can you pls point the reated PR and get the issue closed

**Comment by Thumimku** [comment]
> @Thumimku for this issue, are we fixing the wrapper.conf file and sending it inbuilt in the pack or are we asking the users to get the script fixed manually. If we sending the fixed wrapper inbuilt in the pack can you pls point the reated PR and get the issue closed or else create a doc issue adding the required manual configs for the user and get it pointed for this and get this issue closed

PR : https://github.com/wso2/carbon-identity-framework/pull/4111

**Comment by piraveena** [comment]
@ThumulaPerera / @Thumimku  Can you attach the relevant doc PR?

**Comment by ShanikaWickramasinghe** [comment]
@piraveena @Thumimku As this is a pack start up problem and a user cannot even start the pack without the changes we did for wrapper.conf why we are not sending this fixed wrapper.conf by default inbuilt with the pack. A user might not check the doc always for problems like startups. Doesn't it required to support the pack start with the default conf file sent inside the pack.

**Comment by azam4u121** [comment]
I am facing the issue when starting the service on yajsw-13.05. When I run the command runconsole.bat, the WSO2 carbon works fine.

![Image](https://github.com/user-attachments/assets/2e014dd1-9b4f-4dec-a858-720332384e83)
