### ISSUE TITLE
org.h2.message.DbException.getJdbcSQLException(DbException.java:527) when keep the server idle for 3-4 hrs running the server windows as a service

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14161]
**How to reproduce:**
1. Get IS 6.0.0 alpha 3 pack 
2. Set carbon_home as a a env variable and JAVA_HOME as a env variable
3. Run the pack windows as a service from https://is.docs.wso2.com/en/latest/setup/installing-as-a-windows-service/

**runConsole.bat**

4. Pack will get started successfully
5. Keep the pack idle for around 3 to 4 hrs running the server
6. Observed below error logs 

```
.framework.store.SessionDataStore} - Error while storing session data org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_6 ON PUBLIC.IDN_AUTH_SESSION_STORE(SESSION_ID, SESSION_TYPE, TIME_CREATED, OPERATION) VALUES ( /* key:150 */ '0cb5284c-83ab-46d9-9e13-5970ef9f62f4', 'OIDCSessionDataCache', 1657300224501682000, 'STORE')"; SQL statement:
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|INSERT INTO IDN_AUTH_SESSION_STORE(SESSION_ID, SESSION_TYPE, OPERATION, SESSION_OBJECT, TIME_CREATED, EXPIRY_TIME, TENANT_ID) VALUES (?,?,?,?,?,?,?) [23505-210]
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.message.DbException.getJdbcSQLException(DbException.java:527)
checkRemainConc C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv 1
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:26|executeWithTimeout script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.message.DbException.get(DbException.java:227)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.message.DbException.get(DbException.java:203)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:194)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.command.dml.Insert.insertRows(Insert.java:174)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.command.dml.Insert.update(Insert.java:135)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:61)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.command.CommandContainer.update(CommandContainer.java:174)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.command.Command.executeUpdate(Command.java:252)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at jdk.internal.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at java.base/java.lang.reflect.Method.invoke(Method.java:568)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at jdk.proxy7/jdk.proxy7.$Proxy54.executeUpdate(Unknown Source)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.wso2.carbon.identity.application.authentication.framework.store.SessionDataStore.persistSessionData(SessionDataStore.java:535)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.wso2.carbon.identity.application.authentication.framework.store.SessionDataStore.storeSessionData(SessionDataStore.java:373)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.wso2.carbon.identity.application.authentication.framework.store.SessionDataStore.storeSessionData(SessionDataStore.java:362)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.wso2.carbon.identity.oidc.session.cache.OIDCSessionDataCache.addToCache(OIDCSessionDataCache.java:59)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.wso2.carbon.identity.oidc.session.servlet.OIDCLogoutServlet.addSessionDataToCache(OIDCLogoutServlet.java:816)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.wso2.carbon.identity.oidc.session.servlet.OIDCLogoutServlet.processLogoutRequest(OIDCLogoutServlet.java:387)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.wso2.carbon.identity.oidc.session.servlet.OIDCLogoutServlet.doGet(OIDCLogoutServlet.java:225)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:72)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:26|   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:112)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:145)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:110)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|   at java.base/java.lang.Thread.run(Thread.java:833)
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:27|
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:27|executing script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv
FINEST|20128/0|WSO2 Carbon|22-07-09 01:10:28|org.ops4j.pax.logging.pax-logging-api [log4j2] ERROR : Unable to delete file C:\wso2is-6.0.0-alpha3-SNAPSHOT\repository\logs\wso2carbon.log: java.nio.file.FileSystemException C:\wso2is-6.0.0-alpha3-SNAPSHOT\repository\logs\wso2carbon.log: The process cannot access the file because it is being used by another process
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executed script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv null
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|script done: null
checkRemainConc C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv 1
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executeWithTimeout script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executing script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executed script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv null
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|script done: null
checkRemainConc C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv 1
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executeWithTimeout script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executing script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executed script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv null
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|script done: null
checkRemainConc C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv 1
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executeWithTimeout script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executing script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executed script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv null
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|script done: null
checkRemainConc C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv 1
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executeWithTimeout script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executing script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executed script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv null
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|script done: null
checkRemainConc C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv 1
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executeWithTimeout script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executing script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executed script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv null
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|script done: null
checkRemainConc C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv 1
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executeWithTimeout script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executing script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|executed script: C:\yajsw-stable-13.03\yajsw-stable-13.03\bat\/../scripts/trayMessage.gv null
INFO|wrapper|WSO2 Carbon|22-07-09 01:10:36|script done: null
```

![image](https://user-images.githubusercontent.com/31848014/178040123-acf97d9f-2bed-4743-8a36-4564ef5092b1.png)
![image](https://user-images.githubusercontent.com/31848014/178040158-5f38f69c-32ce-44d9-b0e6-8d887e6da4bd.png)
![image](https://user-images.githubusercontent.com/31848014/178040226-18c12eee-f1f9-4b55-ba0b-06b824e2a913.png)

**Env**
windows 11
YAJSW 13.03
oracle jdk 17.0.3.1
H2 default
IS 6.0.0 alpha 3 snapshot

**Comment by ShanikaWickramasinghe** [comment]
Kept a server idle on Linux (ubuntu 20) and checked whether this DB exception is reproducible there too. But didnt got this error in Linux. This could be a environment specific issue for windows. Decreasing the issue priority as its not observable in Linux. Will get the issue updated if I face this again in windows

**Comment by ShanikaWickramasinghe** [comment]
windows 11
JAJSW 13.03
windows as a service server was idle for around 4hrs
oracle JDK 17.0.3.1

Accessed console > List a created app > sign in methods > update
Accessed managemnt console > list a created app > outbound configs > update

Hit a enter in the terminal and observe the logs. Observed below error log
This time DB exception was not there. Observed only the below attached error

![image](https://user-images.githubusercontent.com/31848014/178337789-0f834386-ce2a-4644-a0ff-b05ebd6f0e14.png)

**Comment by piraveena** [comment]
The log files may be accessible by other services in windows, and the files might be locked. When the time changes to next day, we need to rename the existing carbon log file. That could be the reason. Please check whether the files are not accessed by any other services or opened in windows.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
