### ISSUE TITLE
Server 500 error with organisation management API. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#14170]
**Describe the issue:**
Server 500 error with organisation management API. DB : MSSQL

<img width="1040" alt="Screenshot 2022-07-09 at 11 52 50" src="https://user-images.githubusercontent.com/39077751/178094732-174600c2-7ba0-4099-b713-f213f237ae5b.png">

```
2022-07-09 11:47:28,828] [e00a742d-3baf-4010-8924-7227bcf01fad] ERROR {org.wso2.carbon.identity.organization.management.authz.service.handler.OrganizationManagementAuthzHandler} - Error occurred while evaluating authorization of user for organization management.org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s' SELECT COUNT(UM_RESOURCE_ID) FROM UM_ORG_PERMISSION WHERE UM_ORG_PERMISSION.UM_ID IN ( SELECT UM_PERMISSION_ID FROM UM_ORG_ROLE_PERMISSION WHERE UM_ORG_ROLE_PERMISSION.UM_ROLE_ID IN ( SELECT UM_ORG_ROLE_USER.UM_ROLE_ID FROM UM_ORG_ROLE_USER LEFT JOIN UM_ORG_ROLE ON UM_ORG_ROLE_USER.UM_ROLE_ID = UM_ORG_ROLE.UM_ROLE_ID WHERE UM_USER_ID = :ID; AND UM_ORG_ID = :NAME;) ) AND UM_RESOURCE_ID IN (:PERMISSION_1;, :PERMISSION_2;, :PERMISSION_3;, :PERMISSION_4;, :PERMISSION_5;, :PERMISSION_6;)
[2022-07-09 11:47:28,972] [e00a742d-3baf-4010-8924-7227bcf01fad] ERROR {org.wso2.carbon.tomcat.ext.valves.CompositeValve} - Could not handle request: /o/10084a8d-113f-4211-a0d5-efe36b082211/api/server/v1/identity-providers java.lang.IllegalStateException: Cannot forward after response has been committed
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:324)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:129)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:132)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:134)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834) 
```

**How to reproduce:**
1. Get IS pack Build version: https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/4139/
2. Add the following configuration to <IS-HOME>/repository/conf/deployment.toml

```
[multi_tenancy.stratos]
public_cloud_setup=false

[[organization_context.rewrite]]
base_path = "/api/"
sub_paths = ["/api/server/v1/identity-providers", "/api/server/v1/organizations", "/api/server/v1/applications"]
```
3. Execute  “sh bin/enableadaptive.sh” before starting the pack
4. Execute the API for Create organization
```
Request:
curl --location --request POST 'https://localhost:9443/o/10084a8d-113f-4211-a0d5-efe36b082211/api/server/v1/organizations' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
  "name": "test1",
  "description": "this is a construction company",
  "type": "TENANT",
  "parentId": "ROOT",
  "attributes": [
    {
      "key": "Country",
      "value": "Sri Lanka"
    },
    {
      "key": "Language",
      "value": "Sinhala"
    }
  ]
}'
```

**Expected behavior:**
Create organization.
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/4139/
 - OS: MAC
 - Database: MSSQL
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by dewniMW** [comment]
@sadilchamishka please confirm if this is fixed with https://github.com/wso2-extensions/identity-organization-management/pull/82

**Comment by dewniMW** [comment]
Maybe fixed with https://github.com/wso2-extensions/identity-organization-management/pull/82

**Comment by Sachin-Mamoru** [comment]
I'll check this issue

**Comment by Sachin-Mamoru** [comment]
> **This issue is Fixed**


> OS: MAC
> Database: MSSQL
> Userstore: JDBC
