### ISSUE TITLE
Creating a LDAP userstore with missing Group Search base returns 201

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#14245]
**Describe the issue:**
We can create a LDAP userstore using the `userstores` rest API. When creating we can exclude some properties. When we create a userstore without the search base, the API returns 201 and creates the userstore but following error can be seen.
```
rver/userstores/DEMO.xml
[2022-07-15 11:48:31,219] [] ERROR {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Cannot create org.wso2.carbon.user.core.ldap.UniqueIDReadWriteLDAPUserStoreManager java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.createSecondaryUserStoreManager(AbstractUserStoreManager.java:9185)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addSecondaryUserStoreManager(AbstractUserStoreManager.java:9257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:205)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:202)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addSecondaryUserStoreManager(AbstractUserStoreManager.java:9243)
	at org.wso2.carbon.user.core.common.UserStoreDeploymentManager.deploy(UserStoreDeploymentManager.java:71)
	at org.wso2.carbon.identity.user.store.configuration.deployer.UserStoreConfigurationDeployer.deploy(UserStoreConfigurationDeployer.java:168)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:153)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.user.core.UserStoreException: Required GroupSearchBase property is not set at the LDAP configurations
	at org.wso2.carbon.user.core.ldap.UniqueIDReadOnlyLDAPUserStoreManager.checkRequiredUserStoreConfigurations(UniqueIDReadOnlyLDAPUserStoreManager.java:249)
	at org.wso2.carbon.user.core.ldap.UniqueIDReadWriteLDAPUserStoreManager.checkRequiredUserStoreConfigurations(UniqueIDReadWriteLDAPUserStoreManager.java:2206)
	at org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager.<init>(ReadOnlyLDAPUserStoreManager.java:226)
	at org.wso2.carbon.user.core.ldap.UniqueIDReadOnlyLDAPUserStoreManager.<init>(UniqueIDReadOnlyLDAPUserStoreManager.java:165)
	at org.wso2.carbon.user.core.ldap.UniqueIDReadWriteLDAPUserStoreManager.<init>(UniqueIDReadWriteLDAPUserStoreManager.java:125)
	... 33 more
```

**How to reproduce:**
- Use the following curl [1] to create a userstore.

**Expected behavior:**
API request should fail.

```
curl -L -X POST 'https://localhost:9443/t/carbon.super/api/server/v1/userstores' -H 'Access-Control-Allow-Origin: https://localhost:9443' -H 'Accept: application/json' -H 'Referer;' -H 'Authorization: Basic YWRtaW46YWRtaW4=' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36' -H 'Content-Type: application/json' -H 'Cookie: JSESSIONID=A87E5C5B1D6BDA5794AA13177B13F8A5' --data-raw '{
  "typeId": "VW5pcXVlSURSZWFkV3JpdGVMREFQVXNlclN0b3JlTWFuYWdlcg",
  "name": "ahome-customer",
  "description": "Connects to the Guradio-Home customer user base",
  "properties": [
    {
      "name": "BulkImportSupported",
      "value": "true"
    },
    {
      "name": "UserDNPattern",
      "value": ""
    },
    {
      "name": "GroupNameListFilter",
      "value": "(objectClass=groupOfNames)"
    },
    {
      "name": "BackLinksEnabled",
      "value": "false"
    },
    {
      "name": "defaultRealmName",
      "value": "guardio.com"
    },
    {
      "name": "PasswordJavaScriptRegEx",
      "value": "^[\\S]{5,30}$"
    },
    {
      "name": "MaxUserNameListLength",
      "value": "100"
    },
    {
      "name": "WriteGroups",
      "value": "true"
    },
    {
      "name": "LDAPInitialContextFactory",
      "value": "com.sun.jndi.ldap.LdapCtxFactory"
    },
    {
      "name": "ConnectionRetryDelay",
      "value": "120000"
    },
    {
      "name": "StartTLSEnabled",
      "value": "false"
    },
    {
      "name": "EmptyRolesAllowed",
      "value": "true"
    },
    {
      "name": "UserNameJavaScriptRegEx",
      "value": "^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$"
    },
    {
      "name": "ConnectionPoolingEnabled",
      "value": "false"
    },
    {
      "name": "ClaimOperationsSupported",
      "value": "true"
    },
    {
      "name": "MaxRoleNameListLength",
      "value": "100"
    },
    {
      "name": "ConnectionURL",
      "value": "ldap://localhost:10389"
    },
    {
      "name": "Disabled",
      "value": "false"
    },
    {
      "name": "MultiAttributeSeparator",
      "value": ","
    },
    {
      "name": "RoleDNPattern",
      "value": ""
    },
    {
      "name": "RetryAttempts",
      "value": "0"
    },
    {
      "name": "PasswordJavaRegEx",
      "value": "^[\\S]{5,30}$"
    },
    {
      "name": "ReadOnly",
      "value": "false"
    },
    {
      "name": "DomainName",
      "value": "ahome-customer"
    },
    {
      "name": "UserNameJavaRegEx",
      "value": "^[a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}"
    },
    {
      "name": "UserEntryObjectClass",
      "value": "identityPerson"
    },
    {
      "name": "UserRolesCacheEnabled",
      "value": "true"
    },
    {
      "name": "MembershipAttributeRange",
      "value": "0"
    },
    {
      "name": "UserNameSearchFilter",
      "value": "(&(objectClass=person)(uid=?))"
    },
    {
      "name": "UserNameListFilter",
      "value": "(objectClass=person)"
    },
    {
      "name": "UserNameAttribute",
      "value": "uid"
    },
    {
      "name": "UserIDAttribute",
      "value": "scimId"
    },
    {
      "name": "UserSearchBase",
      "value": "ou=users,dc=guardio,dc=com"
    },
    {
      "name": "MembershipAttribute",
      "value": "member"
    },
    {
      "name": "Class",
      "value": "org.wso2.carbon.user.core.ldap.UniqueIDReadWriteLDAPUserStoreManager"
    },
    {
      "name": "LDAPConnectionTimeout",
      "value": "5000"
    },
    {
      "name": "MemberOfAttribute",
      "value": ""
    },
    {
      "name": "ReadGroups",
      "value": "true"
    },
    {
      "name": "Description",
      "value": "demo LDAP userstore."
    },
    {
      "name": "DisplayNameAttribute",
      "value": ""
    },
    {
      "name": "java.naming.ldap.attributes.binary",
      "value": ""
    },
    {
      "name": "GroupNameAttribute",
      "value": "cn"
    },
    {
      "name": "ReadTimeout",
      "value": "5000"
    },
    {
      "name": "ConnectionName",
      "value": "uid=admin,ou=system"
    },
    {
      "name": "GroupNameSearchFilter",
      "value": "(&(objectClass=groupOfNames)(cn=?))"
    },
    {
      "name": "GroupEntryObjectClass",
      "value": "groupOfNames"
    },
    {
      "name": "UserIdSearchFilter",
      "value": "(&(objectClass=person)(uid=?))"
    },
    {
      "name": "ConnectionPassword",
      "value": "admin"
    },
    {
      "name": "CountRetrieverClass",
      "value": ""
    },
    {
      "name": "RoleNameJavaRegEx",
      "value": "[a-zA-Z0-9._-|//]{3,30}$"
    },
    {
      "name": "RoleNameJavaScriptRegEx",
      "value": "^[\\S]{3,30}$"
    },
    {
      "name": "UserDNCacheEnabled",
      "value": "true"
    },
    {
      "name": "UsernameJavaRegExViolationErrorMsg",
      "value": "Username pattern policy violated."
    },
    {
      "name": "PasswordJavaRegExViolationErrorMsg",
      "value": "Password pattern policy violated."
    },
    {
      "name": "kdcEnabled",
      "value": "false"
    },
    {
      "name": "PasswordHashMethod",
      "value": "PLAIN_TEXT"
    },
    {
      "name": "UserCacheExpiryMilliseconds",
      "value": ""
    }
  ]
}
'
```

**Comment by ImalshaG** [comment]
According to the documentation https://is.docs.wso2.com/en/latest/setup/configuring-a-read-write-ldap-user-store/#properties-used-in-read-write-ldap-user-store-manager, the above mentioned `GroupSearchBase` property is not mandatory only when the `ReadGroups` property is set to false.
In the above scenario since `ReadGroups` property is set to true, Groups are read from the userstore. Therefore it is mandatory to set the group related properties, hence getting the above error.
