### ISSUE TITLE
Login to the console and myaccount fails after migrating from 5.3.0 latest wum to IS 6.0.0

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14312]
**How to reproduce:**
1. Get IS 5.3.0 latest wum (wso2is-5.3.0+1650694972746.full)
2. Get IS 6.0.0 pack from https://wso2.org/jenkins/view/products/job/products/job/product-is/4156/
3. Set up mysql 8.0.29 and point the datasources (master,metrics,bps) in IS 5.3.0 pack
4. In user-mgt xml enable jdbc US and disable default ldap US
5. Do steps in https://is.docs.wso2.com/en/5.9.0/setup/migrating-preparing-for-migration/ to disable versioning in registry configs
6. Up the IS 5.3.0 pack and create some data
7. In IS 6.0.0 deployment toml add below configs

```
[user_store]
type = "database"

[system_applications]
read_only_apps = []

[authorization_manager.properties]
GroupAndRoleSeparationEnabled = false

[encryption]
key = "16CFCF87C5DBF990E593669AA8CE286D"

```
8. In migration-config .yaml below configs are set as below 

```
name: "KeyStorePasswordMigrator"
    order: 9
    parameters:
      schema: "identity"
      currentEncryptionAlgorithm: "RSA"
      migratedEncryptionAlgorithm: "RSA/ECB/OAEPwithSHA1andMGF1Padding"
      transformToSymmetric: "false"

 name: "EncryptionAdminFlowMigrator"
     order: 1
     parameters:
       currentEncryptionAlgorithm: "RSA/ECB/OAEPwithSHA1andMGF1Padding"
       migratedEncryptionAlgorithm: "AES/GCM/NoPadding"
       schema: "identity"
   -
     name: "EncryptionUserFlowMigrator"
     order: 2
     parameters:
       currentEncryptionAlgorithm: "RSA/ECB/OAEPwithSHA1andMGF1Padding"
       migratedEncryptionAlgorithm: "AES/GCM/NoPadding"
       schema: "identity"

```
9. Get the migration client https://github.com/wso2-extensions/identity-migration-resources/releases/tag/v1.0.194
10. Run the migration client

Migration client got executed succesfully without any errors in the backend
Without changing any config in the deployment toml (US type set to "database" and GroupAndRoleSeparationEnabled = false) try to login to managemnt console and console.

Can login to management console. But console and myaccount login gets failed. Attaching debug logs

![Screenshot from 2022-07-19 22-59-17](https://user-images.githubusercontent.com/31848014/179812835-6941284b-7838-4441-8327-41bdd4bd9a1f.png)

```
[2022-07-19 22:47:23,433] [70649578-7a17-465a-ba27-49cca2b4f1e4] DEBUG {org.wso2.carbon.identity.application.authentication.framework.util.LoginContextManagementUtil} - Service Provider tenant domain: carbon.super
[2022-07-19 22:47:23,433] [70649578-7a17-465a-ba27-49cca2b4f1e4] DEBUG {org.wso2.carbon.identity.application.authentication.framework.cache.AuthenticationContextCache} - Found a valid AuthenticationContextCacheEntry corresponding to the session data key : 576bf1ad-0fb0-4a1b-bd63-d14a0f620de8 from the cache. 
[2022-07-19 22:47:23,434] [70649578-7a17-465a-ba27-49cca2b4f1e4] DEBUG {org.wso2.carbon.identity.application.authentication.framework.util.LoginContextManagementUtil} - Setting response for the valid request.
[2022-07-19 22:47:23,448] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.cache.AuthenticationContextCache} - Found a valid AuthenticationContextCacheEntry corresponding to the session data key : 576bf1ad-0fb0-4a1b-bd63-d14a0f620de8 from the cache. 
[2022-07-19 22:47:23,448] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Context id: 576bf1ad-0fb0-4a1b-bd63-d14a0f620de8 is active in the thread with id: 180
[2022-07-19 22:47:23,449] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler} - In authentication flow
[2022-07-19 22:47:23,449] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler} - Executing the Step Based Authentication...
[2022-07-19 22:47:23,449] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler} - Authentication Graph not defined for the application. Performing Step based authentication. Service Provider :Console
[2022-07-19 22:47:23,450] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler} - Executing the Step Based Authentication...
[2022-07-19 22:47:23,450] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler} - Starting Step: 1
[2022-07-19 22:47:23,450] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - No current authenticated IDPs in the authentication context. Continuing with the previous authenticated IDPs
[2022-07-19 22:47:23,451] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - No previous authenticated IDPs found in the authentication context.
[2022-07-19 22:47:23,451] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.util.FrameworkUtils} - Finding already authenticated IdPs of the step {order:1}
[2022-07-19 22:47:23,451] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.util.FrameworkUtils} - No authenticators found.
[2022-07-19 22:47:23,452] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Receive a response from the external party
[2022-07-19 22:47:23,452] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - BasicAuthenticator can handle the request.
[2022-07-19 22:47:23,457] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Listing users who having value as PRIMARY/admin for the claim http://wso2.org/claims/username
[2022-07-19 22:47:23,458] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Switching to list users using username
[2022-07-19 22:47:23,464] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Filtered users: [admin]
[2022-07-19 22:47:23,484] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Domain found in claim value. Searching only in the PRIMARY for possible matches
[2022-07-19 22:47:23,486] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - List of filtered users for: PRIMARY : []
[2022-07-19 22:47:23,487] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Users count matching to claim: http://wso2.org/claims/username and value: admin is: 0
[2022-07-19 22:47:23,488] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Listing users who having value as admin for the claim http://wso2.org/claims/username
[2022-07-19 22:47:23,488] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Switching to list users using username
[2022-07-19 22:47:23,490] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Filtered users: [admin]
[2022-07-19 22:47:23,527] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.user.core.common.UserIdResolverCache} - Cache: user_id_from_user_name_cache which is under USER_ID_RESOLVER_CACHE_MANAGER, found the entry: 39485f4f-0761-11ed-9fbe-0242ac110002 for the key: admin successfully.
[2022-07-19 22:47:23,544] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.user.core.common.UserIdResolverCache} - Cache: user_id_from_user_name_cache which is under USER_ID_RESOLVER_CACHE_MANAGER, found the entry: 39485f4f-0761-11ed-9fbe-0242ac110002 for the key: admin successfully.
[2022-07-19 22:47:23,546] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Authentication failure. Wrong username or password is provided.
[2022-07-19 22:47:23,551] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator} - Error occurred during the authentication process, hence retrying. org.wso2.carbon.identity.application.authentication.framework.exception.InvalidCredentialsException: User authentication failed due to invalid credentials
	at org.wso2.carbon.identity.application.authenticator.basicauth.BasicAuthenticator.processAuthenticationResponse(BasicAuthenticator.java:676)
	at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.process(AbstractApplicationAuthenticator.java:92)
	at org.wso2.carbon.identity.application.authenticator.basicauth.BasicAuthenticator.process(BasicAuthenticator.java:164)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:579)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handleResponse(DefaultStepHandler.java:548)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:215)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:187)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:116)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:187)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:281)
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:57)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:72)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:112)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:149)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:110)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

[2022-07-19 22:47:23,564] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - BasicAuthenticator returned: INCOMPLETE
[2022-07-19 22:47:23,564] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - BasicAuthenticator is redirecting
[2022-07-19 22:47:23,565] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler} - Step is not complete yet. Redirecting to outside.
[2022-07-19 22:47:23,565] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler} - Handling post authentication
[2022-07-19 22:47:23,565] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler} - Sequence is not completed yet. Hence skipping post authentication
[2022-07-19 22:47:23,565] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Context id: 576bf1ad-0fb0-4a1b-bd63-d14a0f620de8 left the thread with id: 180
[2022-07-19 22:47:23,566] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.cache.AuthenticationContextCache} - Authentication context is stored with details [ Context Id : 576bf1ad-0fb0-4a1b-bd63-d14a0f620de8, Cache type : AuthenticationContextCache, Operation : STORE ]
[2022-07-19 22:47:23,589] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.store.SessionDataStore} - Persisted SessionContextData to DB. key : 576bf1ad-0fb0-4a1b-bd63-d14a0f620de8 type : AuthenticationContextCache
[2022-07-19 22:47:23,590] [095cf9ef-3c71-40c0-8422-1076bf981db9] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Context with id: 576bf1ad-0fb0-4a1b-bd63-d14a0f620de8 added to the cache.
[2022-07-19 22:47:23,986] [75af2a51-e420-42a3-928c-10969f6c2d2d] DEBUG {org.wso2.carbon.identity.application.authentication.framework.util.LoginContextManagementUtil} - Service Provider tenant domain: carbon.super
[2022-07-19 22:47:23,987] [75af2a51-e420-42a3-928c-10969f6c2d2d] DEBUG {org.wso2.carbon.identity.application.authentication.framework.cache.AuthenticationContextCache} - Found a valid AuthenticationContextCacheEntry corresponding to the session data key : 576bf1ad-0fb0-4a1b-bd63-d14a0f620de8 from the cache. 
[2022-07-19 22:47:23,987] [75af2a51-e420-42a3-928c-10969f6c2d2d] DEBUG {org.wso2.carbon.identity.application.authentication.framework.util.LoginContextManagementUtil} - Setting response for the valid request.

```

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
mysql 8.0.29
IS 5.3.0 latest wum to IS 6.0.0

**Comment by ShanikaWickramasinghe** [comment]
@ashendes After the migration if I change the userstore type for type = "database_unique_id" can login to console and myaccount successfully. But if we keep the US type as "database" and try the login, login is failing. In the doc issues that we created related to this we have asked the customers to switch to unique id jdbc US type **if required** https://github.com/wso2/product-is/issues/14200#issue-1301628952. But due to major breaking issues like this dont we need to communicate for the customers that to work with console and myaccount  switching to unquie id US type is mandotory. cc @piraveena @ashendes WDYT 
![Screenshot from 2022-07-20 09-32-37](https://user-images.githubusercontent.com/31848014/179894217-983871d7-b729-4d82-a918-978df5a32827.png)

**Comment by ashendes** [comment]
This is being tracked in https://github.com/wso2/product-is/issues/14200.
