### ISSUE TITLE
Unable to get the MaxSearchQueryTime from the realm configuration. The default value: 10000 is used instead. java.lang.NumberFormatException: null after migrating from 5.3.0 to IS 6.0.0

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14316]
**How to reproduce:**
1. Get IS 5.3.0 latest wum (wso2is-5.3.0+1650694972746.full)
2. Get IS 6.0.0 pack from https://wso2.org/jenkins/view/products/job/products/job/product-is/4156/
3. Set up mysql 8.0.29 and point the datasources (master,metrics,bps) in IS 5.3.0 pack
4. In user-mgt xml enable jdbc US and disable default ldap US
5. Do steps in https://is.docs.wso2.com/en/5.9.0/setup/migrating-preparing-for-migration/ to disable versioning in registry configs
6. Up the IS 5.3.0 pack and create some data
7. In IS 6.0.0 deployment toml add below configs

```
[user_store]
type = "database"

[system_applications]
read_only_apps = []

[authorization_manager.properties]
GroupAndRoleSeparationEnabled = false

[encryption]
key = "16CFCF87C5DBF990E593669AA8CE286D"

```
8. In migration-config .yaml below configs are set as below 

```
name: "KeyStorePasswordMigrator"
    order: 9
    parameters:
      schema: "identity"
      currentEncryptionAlgorithm: "RSA"
      migratedEncryptionAlgorithm: "RSA/ECB/OAEPwithSHA1andMGF1Padding"
      transformToSymmetric: "false"

 name: "EncryptionAdminFlowMigrator"
     order: 1
     parameters:
       currentEncryptionAlgorithm: "RSA/ECB/OAEPwithSHA1andMGF1Padding"
       migratedEncryptionAlgorithm: "AES/GCM/NoPadding"
       schema: "identity"
   -
     name: "EncryptionUserFlowMigrator"
     order: 2
     parameters:
       currentEncryptionAlgorithm: "RSA/ECB/OAEPwithSHA1andMGF1Padding"
       migratedEncryptionAlgorithm: "AES/GCM/NoPadding"
       schema: "identity"

```
9. Get the migration client https://github.com/wso2-extensions/identity-migration-resources/releases/tag/v1.0.194
10. Run the migration client

Migration client got executed succesfully without any errors in the backend

11. Now stop the server and change the US type for unique id jdbc and start the pack again
(Without changing GroupAndRoleSeparationEnabled = false) 

Debug logs enabled for authentication framework and user-core components. Even though pack got started successfully Observing below exeception when starting the pack after changing to unique id jdbc

```
[2022-07-20 12:19:40,966] [] DEBUG {org.wso2.carbon.user.core.tenant.TenantUniqueIdCache} - TENANT_UNIQUE_ID_CACHE which is under TENANT_UNIQUE_ID_CACHE_MANAGER, is cleared successfully
[2022-07-20 12:19:40,971] [] DEBUG {org.wso2.carbon.user.core.common.DefaultRealm} - Default realm cache timeout set to: 30 minutes.
[2022-07-20 12:19:41,032] [] DEBUG {org.wso2.carbon.user.core.common.DefaultRealm} - Start initializing class with the first option
[2022-07-20 12:19:41,035] [] DEBUG {org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager} - ReadGroups is enabled for PRIMARY
[2022-07-20 12:19:41,037] [] DEBUG {org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager} - Unable to get the MaxSearchQueryTime from the realm configuration. The default value: 10000 is used instead. java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:614)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.getSQLQueryTimeoutLimit(JDBCUserStoreManager.java:4788)
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:171)
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:291)
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.<init>(JDBCUserStoreManager.java:275)
	at org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager.<init>(UniqueIDJDBCUserStoreManager.java:131)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.wso2.carbon.user.core.common.DefaultRealm.createObjectWithOptions(DefaultRealm.java:356)
	at org.wso2.carbon.user.core.common.DefaultRealm.initializeObjects(DefaultRealm.java:231)
	at org.wso2.carbon.user.core.common.DefaultRealm.init(DefaultRealm.java:136)
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:276)
	at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:102)
	at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:115)
	at org.wso2.carbon.user.core.internal.Activator.startDeploy(Activator.java:80)
	at org.wso2.carbon.user.core.internal.BundleCheckActivator.start(BundleCheckActivator.java:61)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:598)
	at org.eclipse.osgi.container.Module.start(Module.java:462)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

[2022-07-20 12:19:41,044] [] DEBUG {org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager} - WriteGroups is enabled for PRIMARY
[2022-07-20 12:19:41,045] [] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - User Roles Cache is configured to:true
[2022-07-20 12:19:41,047] [] DEBUG {org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager} - Started 1658299781047
[2022-07-20 12:19:41,048] [] DEBUG {org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager} - The jdbcDataSource being used by JDBCUserStoreManager :: 1106343998

```
![Screenshot from 2022-07-20 12-27-34](https://user-images.githubusercontent.com/31848014/179917116-02a9dbf4-45cc-46f3-bdb0-a31517cc6db0.png)

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
mysql 8.0.29
IS 5.3.0 latest wum to IS 6.0.0
oracle jdk 11.0.13
ubuntu 20

**Comment by ashendes** [comment]
This is happening because the userstore property `MaxSearchQueryTime` is not provided in the userstore config by default. This does not adversely affect the product as it gets set to a default value given in the code if its not available as a config.

This debug log can avoided by setting a custom value to this property in the TOML file.
```
[[user_store.properties]]
MaxSearchQueryTime=5000
```
