### ISSUE TITLE
OrganizationManagementServerException: Unable to retrieve the organizations. when Navigating to Organizations Section against MSSQL 2019

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14365]
**How to reproduce:**
1. Get pack https://github.com/wso2/product-is/releases/tag/v6.0.0-alpha3
2. Set up MSSQL 2019 as the database type and uniqueid jdbc US as the userstore type
3. Login to console as admin
4. Go to Manage > Organizations section

Getting a error as below in UI and backend

![Screenshot from 2022-07-22 16-27-26](https://user-images.githubusercontent.com/31848014/180425785-d119107d-d08f-4293-8e2c-a87991892af2.png)

https://user-images.githubusercontent.com/31848014/180425944-828aef87-16fb-4d2a-a0b8-ba91096001cd.mp4

```

[2022-07-22 16:27:22,413] [e453f2db-0b90-4750-b26f-9d3abc791e25] ERROR {org.wso2.carbon.identity.organization.management.endpoint.service.OrganizationManagementService} - errorCode: ORG-65002 | message: Server encountered an error while retrieving the organizations. org.wso2.carbon.identity.organization.management.service.exception.OrganizationManagementServerException: Unable to retrieve the organizations.
	at org.wso2.carbon.identity.organization.management.service.util.Utils.handleServerException(Utils.java:81)
	at org.wso2.carbon.identity.organization.management.service.dao.impl.OrganizationManagementDAOImpl.getOrganizations(OrganizationManagementDAOImpl.java:398)
	at org.wso2.carbon.identity.organization.management.service.OrganizationManagerImpl.getOrganizations(OrganizationManagerImpl.java:247)
	at org.wso2.carbon.identity.organization.management.endpoint.service.OrganizationManagementService.getOrganizations(OrganizationManagementService.java:100)
	at org.wso2.carbon.identity.organization.management.endpoint.impl.OrganizationsApiServiceImpl.organizationsGet(OrganizationsApiServiceImpl.java:43)
	at org.wso2.carbon.identity.organization.management.endpoint.OrganizationsApi.organizationsGet(OrganizationsApi.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:112)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:136)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:134)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s' SELECT DISTINCT UM_ORG.UM_ID, UM_ORG.UM_ORG_NAME, UM_ORG.UM_CREATED_TIME FROM UM_ORG INNER JOIN UM_ORG_ROLE ON UM_ORG_ROLE.UM_ORG_ID = UM_ORG.UM_ID INNER JOIN UM_ORG_ROLE_USER ON UM_ORG_ROLE.UM_ROLE_ID = UM_ORG_ROLE_USER.UM_ROLE_ID INNER JOIN UM_ORG_ROLE_PERMISSION ON UM_ORG_ROLE.UM_ROLE_ID = UM_ORG_ROLE_PERMISSION.UM_ROLE_ID INNER JOIN UM_ORG_PERMISSION ON UM_ORG_ROLE_PERMISSION.UM_PERMISSION_ID = UM_ORG_PERMISSION.UM_ID WHERE UM_ORG_ROLE_USER.UM_USER_ID = :USER_ID; AND UM_ORG_PERMISSION.UM_RESOURCE_ID IN (:PERMISSION_1;, :PERMISSION_2;, :PERMISSION_3;, :PERMISSION_4;, :PERMISSION_5;, :PERMISSION_6;) AND UM_ORG.UM_ID IN (SELECT O.UM_ID FROM UM_ORG O JOIN UM_ORG_HIERARCHY OH ON O.UM_ID = OH.UM_ID WHERE OH.UM_PARENT_ID = (SELECT UM_ID FROM UM_ORG WHERE UM_ID = :ID;) AND OH.DEPTH = 1) ORDER BY UM_ORG.UM_CREATED_TIME DESC LIMIT :LIMIT;
	at org.wso2.carbon.database.utils.jdbc.NamedJdbcTemplate.executeQuery(NamedJdbcTemplate.java:169)
	at org.wso2.carbon.identity.organization.management.service.dao.impl.OrganizationManagementDAOImpl.getOrganizations(OrganizationManagementDAOImpl.java:371)
	... 60 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'LIMIT'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:258)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1537)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:436)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:387)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7024)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2350)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:219)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:199)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:309)
	at jdk.internal.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at jdk.proxy6/jdk.proxy6.$Proxy54.executeQuery(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.NamedPreparedStatement.executeQuery(NamedPreparedStatement.java:246)
	at org.wso2.carbon.database.utils.jdbc.NamedJdbcTemplate.executeQuery(NamedJdbcTemplate.java:154)
	... 61 more




```
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
MSSQL 2019
Oracle JDK 17.0.3.1
IS 6.0.0 alpha 3

**Comment by Sachin-Mamoru** [comment]
Will look in to this issue

**Comment by ShanikaWickramasinghe** [comment]
Attaching the deployment.toml

```
[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.identity_db]

url = "jdbc:sqlserver://localhost:1433;databaseName=july22db1;SendStringParametersAsUnicode=false"
username = "sa"
password = "MyPassword001"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
[database.identity_db.pool_options]
maxActive = "80"
maxWait="6000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false

[database.shared_db]
url = "jdbc:sqlserver://localhost:1433;databaseName=july22db1;SendStringParametersAsUnicode=false"
username = "sa"
password = "MyPassword001"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
[database.shared_db.pool_options]
maxActive = "80"
maxWait="6000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false

[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

[multi_tenancy.stratos]
public_cloud_setup=false


[system_applications]
read_only_apps = []

```
