### ISSUE TITLE
Exception is thrown when two different database types are configured for identity and session databases

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#14387]
**Describe the issue:**
$subject

**How to reproduce:**
1. Configure a separate database for session-mgt as instructed in [here](https://github.com/Buddhimah/docs-is/blob/2ebf7b0a700988b74edb45b2c869fb15ab7347c7/en/docs/setup/configuring-a-seperate-session-store.md). If your identity database type is H2, then configure a different db type for session mgt (Ex: mssql).
2. Start the server and login to any application (Ex: myaccount).
3. Below stacktrace can be seen in the terminal.
```
Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s'INSERT INTO IDN_AUTH_SESSION_META_DATA(SESSION_ID,PROPERTY_TYPE,`VALUE`)VALUES (?,?,?)
	at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.executeBatchInsert(JdbcTemplate.java:346)
	at org.wso2.carbon.identity.application.authentication.framework.store.UserSessionStore.storeSessionMetaData(UserSessionStore.java:714)
	... 57 more
Caused by: java.sql.BatchUpdateException: Incorrect syntax near '`'.
```

**Analysis**

It can be seen that, a wrong database query is selected while inserting records to `IDN_AUTH_SESSION_META_DATA`. Server has picked the H2 db related query instead of the mssql one [1]. The query is selected upon the response of `isH2DB()` method [2]. Inside  JdbcUtils class `isDBTypeOf(String dbType)` is called and the `JDBCTemplate` is create according to the identity datasource [3]. However this template should be `JdbcUtils.Database.SESSION` for the separate session db scenario [4].

[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/SQLQueries.java#L121-L125
[2] https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/UserSessionStore.java#L714
[3] https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/util/JdbcUtils.java#L146
[4] https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/UserSessionStore.java#L712

**Comment by ThaminduDilshan** [comment]
Different Utility class can be seen here
https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/util/JdbcUtils.java#L101

**Comment by ThaminduDilshan** [comment]
Will be fixed with https://github.com/wso2/carbon-identity-framework/pull/3959 [[commit](https://github.com/wso2/carbon-identity-framework/pull/3959/commits/a79cf87d9d601406f07254db0ff83211d1e9fe94)]
