### ISSUE TITLE
Error occurred while executing :   ALTER TABLE UM_USER ADD UNIQUE(UM_USER_ID);  when migrating from 5.3.0 to 6.0.0 with oracle 19c

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#14537]
**Describe the issue:**
1. Get 5.3.0 pack wso2is-5.3.0+1601997504472.full and u2 update it for wso2is-5.3.0.25)
2. Get https://wso2.org/jenkins/view/products/job/products/job/product-is/org.wso2.is$wso2is/4201/
3. Get https://github.com/wso2-extensions/identity-migration-resources/releases/tag/v1.0.203
4. 5.3.0 pack had data user, role, local claim, challenge question, app(oauth), app(saml), idp (google), secondory userstore (mysql8),workflow > Under super tenant
5. 5.3.0 pack had a tenant and data created under tenant > user, role, local claim, app(oauth), app(saml)
6. Set  transformToSymmetric: "true"
7. Replace wso2carbon.jks of old pack as internal.jks to new pack
8. Run migration client

Getting below exception

```
[2022-08-04 19:57:39,986] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 6.0.0, Migration Step : SchemaMigrator of order : 7 is starting........................... 
[2022-08-04 19:57:39,987] []  INFO {org.wso2.carbon.is.migration.service.SchemaMigrator} -  WSO2 Product Migration Service Task : Executing Identity Migration Scripts.
[2022-08-04 19:57:41,791] []  INFO {org.wso2.carbon.is.migration.service.SchemaMigrator} -  WSO2 Product Migration Service Task : Identity DB Migration script executed successfully.
[2022-08-04 19:57:41,792] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 6.0.0, Migration Step : SchemaMigrator of order : 8 is starting........................... 
[2022-08-04 19:57:41,793] []  INFO {org.wso2.carbon.is.migration.service.SchemaMigrator} -  WSO2 Product Migration Service Task : Executing Identity Migration Scripts.
[2022-08-04 19:58:28,918] [] ERROR {org.wso2.carbon.is.migration.service.SchemaMigrator} - Error occurred while executing SQL script for migrating database java.lang.Exception: Error occurred while executing :   ALTER TABLE UM_USER ADD UNIQUE(UM_USER_ID); 
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:318)
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:234)
	at org.wso2.carbon.is.migration.service.SchemaMigrator.migrate(SchemaMigrator.java:89)
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:85)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:151)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.sql.SQLSyntaxErrorException: ORA-01735: invalid ALTER TABLE option

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:630)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:564)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1231)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:772)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:299)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:512)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:123)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1200)
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1820)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1472)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:2505)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:2460)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:328)
	at jdk.internal.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy57.execute(Unknown Source)
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:273)
	... 32 more
Caused by: Error : 1735, Position : 42, Sql = ALTER TABLE UM_USER ADD UNIQUE(UM_USER_ID); , OriginalSql =   ALTER TABLE UM_USER ADD UNIQUE(UM_USER_ID); , Error Msg = ORA-01735: invalid ALTER TABLE option

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:637)
	... 50 more

[2022-08-04 19:58:29,000] [] ERROR {org.wso2.carbon.is.migration.service.SchemaMigrator} - An error occurred while rolling back transactions. java.lang.Exception: Error occurred while executing SQL script for migrating database
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:244)
	at org.wso2.carbon.is.migration.service.SchemaMigrator.migrate(SchemaMigrator.java:89)
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:85)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:151)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.Exception: Error occurred while executing :   ALTER TABLE UM_USER ADD UNIQUE(UM_USER_ID); 
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:318)
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:234)
	... 31 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-01735: invalid ALTER TABLE option

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:630)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:564)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1231)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:772)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:299)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:512)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:123)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1200)
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1820)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1472)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:2505)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:2460)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:328)
	at jdk.internal.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy57.execute(Unknown Source)
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:273)
	... 32 more
Caused by: Error : 1735, Position : 42, Sql = ALTER TABLE UM_USER ADD UNIQUE(UM_USER_ID); , OriginalSql =   ALTER TABLE UM_USER ADD UNIQUE(UM_USER_ID); , Error Msg = ORA-01735: invalid ALTER TABLE option

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:637)
	... 50 more

[2022-08-04 19:58:29,004] [] ERROR {org.wso2.carbon.is.migration.MigrationClientImpl} - Migration process was stopped. org.wso2.carbon.identity.core.migrate.MigrationClientException: Error occurred while executing SQL script for migrating database
	at org.wso2.carbon.is.migration.service.SchemaMigrator.migrate(SchemaMigrator.java:100)
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:85)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:151)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.Exception: Error occurred while executing SQL script for migrating database
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:244)
	at org.wso2.carbon.is.migration.service.SchemaMigrator.migrate(SchemaMigrator.java:89)
	... 30 more
Caused by: java.lang.Exception: Error occurred while executing :   ALTER TABLE UM_USER ADD UNIQUE(UM_USER_ID); 
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:318)
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:234)
	... 31 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-01735: invalid ALTER TABLE option

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:630)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:564)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1231)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:772)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:299)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:512)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:123)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1200)
	at oracle.jdbc.driver.OracleStatement.executeSQLStatement(OracleStatement.java:1820)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1472)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:2505)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:2460)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:328)
	at jdk.internal.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy57.execute(Unknown Source)
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:273)
	... 32 more
Caused by: Error : 1735, Position : 42, Sql = ALTER TABLE UM_USER ADD UNIQUE(UM_USER_ID); , OriginalSql =   ALTER TABLE UM_USER ADD UNIQUE(UM_USER_ID); , Error Msg = ORA-01735: invalid ALTER TABLE option

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:637)
	... 50 more

[2022-08-04 19:58:29,007] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-08-04 19:58:29,007] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-08-04 19:58:29,008] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-08-04 19:58:29,008] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-08-04 19:58:29,008] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-08-04 19:58:29,008] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-08-04 19:58:29,008] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-08-04 19:58:29,009] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-08-04 19:58:29,009] []  INFO {org.wso2.carbon.is.migration.MigrationClientImpl} - ............................................................................................
[2022-08-04 19:58:33,200] []  WARN {org.wso2.carbon.core.internal.StartupFi
```
 
![Screenshot from 2022-08-04 20-09-05](https://user-images.githubusercontent.com/31848014/182875080-1eefdc89-76e7-468f-87c9-1696482a8097.png)
![Screenshot from 2022-08-04 20-09-08](https://user-images.githubusercontent.com/31848014/182875106-c621f9cc-8863-4560-94b0-411ad9c2b027.png)

https://user-images.githubusercontent.com/31848014/182875344-88e29e12-633c-41f0-a9c2-28284a5d7951.mp4

5.3.0 conf and deployment.toml and mirgration yaml attached

[resources.zip](https://github.com/wso2/product-is/files/9260681/resources.zip)

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
5.3.0 to 6.0.0
oracle 19c

**Comment by ShanikaWickramasinghe** [comment]
@sandushi Pls verify this migration again after the fix and update the issue with the status

**Comment by sandushi** [comment]
The issue was fixed from this https://github.com/wso2-extensions/identity-migration-resources/pull/246

And locally tested the change, The step 8 is successfully completed.
![Screenshot from 2022-08-04 20-50-28](https://user-images.githubusercontent.com/36092400/182884723-41ad66db-2f86-470c-9d28-e83e5ec6cd08.png)


But observed and another error in step 8 as below.
![Screenshot from 2022-08-04 20-37-35](https://user-images.githubusercontent.com/36092400/182884933-f6790aca-1599-44e7-b4ba-a30e10ab0b1e.png)

@ashendes Please check on this error while adding the PRIMARY KEY to IDN_FED_AUTH_SESSION_MAPPING table.

**Comment by ashendes** [comment]
@sandushi https://github.com/wso2-extensions/identity-migration-resources/pull/247 will fix the issue in step 8.

**Comment by sandushi** [comment]
This oracle issues are fixed and with the latest changes, migration from IS 5.11.0 to IS 6.0.0 with oracle 19 was successful.

[Untitled_ Aug 7, 2022 2_55 PM.webm](https://user-images.githubusercontent.com/36092400/183284499-74bf2eb0-5fb1-4b41-aed5-3119f6166b14.webm)

The logs are attached in this below zip file.
[migration-log.zip](https://github.com/wso2/product-is/files/9276535/migration-log.zip)
