### ISSUE TITLE
Getting an Error message when navigating to User -Attributes in application (SP)

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#14678]
**Describe the issue:**
When clicking on the "User Attribute " Tab any new application in 1st attempt, gets below Error

<img width="1504" alt="Screenshot 2022-08-09 at 19 12 51" src="https://user-images.githubusercontent.com/39120228/183666386-d190a4e8-61dc-4e8c-a31c-faf008cedba6.png">

**How to reproduce:**
1. Startup Identity Server
2. Go to Console > Develop 
3. Add new any application 
4. Click on the "User Attribute" Tab

**Note: This will only appear on 1st attempt** 

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  wso2is-6.0.0-rc2-snapshot
 - OS: Mac 12.4 (21F79) - Apple M1 Pro
 - Database: H2
 - Userstore: 

---

```
ERROR {org.wso2.charon3.core.protocol.endpoints.AbstractResourceManager} - Error occurred while listing roles. org.wso2.charon3.core.exceptions.CharonException: Error occurred while listing roles.
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManager.listRoles(SCIMRoleManager.java:325)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManager.listRolesWithGET(SCIMRoleManager.java:189)
	at org.wso2.charon3.core.protocol.endpoints.RoleResourceManager.listWithGETRole(RoleResourceManager.java:166)
	at org.wso2.carbon.identity.scim2.provider.resources.RoleResource.getRoles(RoleResource.java:182)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:659)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:116)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:152)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:135)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.wso2.carbon.identity.role.mgt.core.IdentityRoleManagementServerException: Error while adding the the roleID: d7a350e5-4b8b-4e4c-8aae-dee6d7e3108e for the role: Internal/system in the tenantDomain: carbon.super
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.addRoleID(RoleDAOImpl.java:251)
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.buildRolesList(RoleDAOImpl.java:366)
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.processListRolesQuery(RoleDAOImpl.java:346)
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.getRoles(RoleDAOImpl.java:299)
	at org.wso2.carbon.identity.role.mgt.core.internal.RoleManagementServiceImpl.getRoles(RoleManagementServiceImpl.java:95)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManager.listRoles(SCIMRoleManager.java:314)
	... 65 more
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_8C ON PUBLIC.IDN_SCIM_GROUP(TENANT_ID NULLS FIRST, ROLE_NAME NULLS FIRST, ATTR_NAME NULLS FIRST) VALUES ( /* key:10 */ -1234, 'Internal/system', 'urn:ietf:params:scim:schemas:core:2.0:id')"; SQL statement:
INSERT INTO IDN_SCIM_GROUP (TENANT_ID, ROLE_NAME, ATTR_NAME, ATTR_VALUE) VALUES ( ? ,  ? ,  ? ,  ? ) [23505-210]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:527)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.index.Index.getDuplicateKeyException(Index.java:525)
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
	at org.h2.command.dml.Insert.insertRows(Insert.java:174)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:61)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at jdk.internal.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy54.executeUpdate(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.NamedPreparedStatement.executeUpdate(NamedPreparedStatement.java:252)
	at org.wso2.carbon.identity.role.mgt.core.dao.RoleDAOImpl.addRoleID(RoleDAOImpl.java:244)
	... 70 more
```

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by NilukaSripalim** [comment]
Duplicate due to https://github.com/wso2/product-is/issues/14561

**Comment by NilukaSripalim** [comment]
[Screen Recording 2022-08-10 at 11.22.35.zip](https://github.com/wso2/product-is/files/9297173/Screen.Recording.2022-08-10.at.11.22.35.zip)

**Comment by ShanikaWickramasinghe** [comment]
Observed a similar charon exception which is tracked in https://github.com/wso2/product-is/issues/14682. But didnt got something went wrong in attributes section

**Comment by ShanikaWickramasinghe** [comment]
Was able to get this issue reproduced with latest pack

1. Get a fresh pack https://wso2.org/jenkins/job/products/job/product-is/4220/artifact/modules/distribution/target/wso2is-6.0.0.zip
2. Unzip 
3. Up the pack
4. Create a Traditional web app and click allow origin
5. Go to attributes tab

This issue will reproduce in a fresh pack only during the 1 st time after you unzip newly

![Screenshot from 2022-08-10 12-14-54](https://user-images.githubusercontent.com/31848014/183834053-01a2675d-b252-4609-8a58-bdf4c6097f48.png)

Browser Firefox 103.0
Linux Ubuntu 20
