### ISSUE TITLE
Migrating from IS 5.3.0 to 6.0.0 : Error while retrieving the CORS configuration of admin user

### ISSUE THREAD

**Issue by Yasasr1** [wso2/product-is#14717]
**How to reproduce:**

1. Configure MSSQL as the database for IS 5.3.0
2. Follow the steps in the [docs](https://is.docs.wso2.com/en/6.0.0/deploy/migrate/migrate-to-600/) to migrate from 5.3.0 to 6.0.0.
3. wait until the migration is completed and try to open the management console [https://localhost:9443/carbon/admin/login.jsp](https://localhost:9443/carbon/admin/login.jsp)
4. following error is logged in console

This issue can be resolved by restarting the server

```
[2022-08-15 10:41:50,920] [fc8bc0be-5030-44fc-a4eb-4fe6b8b0e852] ERROR {org.wso2.carbon.identity.cors.valve.CORSValve} - CORS management service error when intercepting an HTTP request. org.wso2.carbon.identity.cors.mgt.core.exception.CORSManagementServiceServerException: CMS-65006
	at org.wso2.carbon.identity.cors.service.internal.impl.CORSManagerImpl.getCORSConfiguration(CORSManagerImpl.java:76)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:71)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:165)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:111)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.wso2.carbon.identity.cors.mgt.core.exception.CORSManagementServiceServerException: Server encountered an error while retrieving the CORS configuration of carbon.super.
	at org.wso2.carbon.identity.cors.mgt.core.internal.util.ErrorUtils.handleServerException(ErrorUtils.java:56)
	at org.wso2.carbon.identity.cors.mgt.core.dao.impl.CORSConfigurationDAOImpl.getCORSConfigurationByTenantDomain(CORSConfigurationDAOImpl.java:76)
	at org.wso2.carbon.identity.cors.mgt.core.dao.impl.CacheBackedCORSConfigurationDAO.getCORSConfigurationByTenantDomain(CacheBackedCORSConfigurationDAO.java:66)
	at org.wso2.carbon.identity.cors.mgt.core.internal.impl.CORSManagementServiceImpl.getCORSConfiguration(CORSManagementServiceImpl.java:198)
	at org.wso2.carbon.identity.cors.service.internal.impl.CORSManagerImpl.getCORSConfiguration(CORSManagerImpl.java:73)
	... 22 more
Caused by: org.wso2.carbon.identity.configuration.mgt.core.exception.ConfigurationManagementServerException: Error while getting the resource : TENANT_CORS_CONFIGURATION.
	at org.wso2.carbon.identity.configuration.mgt.core.util.ConfigurationUtils.handleServerException(ConfigurationUtils.java:92)
	at org.wso2.carbon.identity.configuration.mgt.core.dao.impl.ConfigurationDAOImpl.getResourceByName(ConfigurationDAOImpl.java:368)
	at org.wso2.carbon.identity.configuration.mgt.core.dao.impl.CachedBackedConfigurationDAO.getResourceByName(CachedBackedConfigurationDAO.java:90)
	at org.wso2.carbon.identity.configuration.mgt.core.ConfigurationManagerImpl.getResource(ConfigurationManagerImpl.java:191)
	at org.wso2.carbon.identity.cors.mgt.core.dao.impl.CORSConfigurationDAOImpl.getResource(CORSConfigurationDAOImpl.java:123)
	at org.wso2.carbon.identity.cors.mgt.core.dao.impl.CORSConfigurationDAOImpl.getCORSConfigurationByTenantDomain(CORSConfigurationDAOImpl.java:67)
	... 25 more
Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s'SELECT
  R.ID,
  R.TENANT_ID,
  R.NAME,
  R.LAST_MODIFIED,
  R.HAS_FILE,
  R.HAS_ATTRIBUTE,
  T.NAME AS RESOURCE_TYPE,
  T.DESCRIPTION AS DESCRIPTION,
  F.ID AS FILE_ID,
  A.ID AS ATTR_ID,
  A.ATTR_KEY AS ATTR_KEY,
  A.ATTR_VALUE AS ATTR_VALUE
FROM
  IDN_CONFIG_RESOURCE AS R
  INNER JOIN IDN_CONFIG_TYPE AS T ON R.TYPE_ID = T.ID
  LEFT JOIN IDN_CONFIG_ATTRIBUTE AS A ON (
    R.HAS_ATTRIBUTE = TRUE
    AND A.RESOURCE_ID = R.ID
  )
  LEFT JOIN IDN_CONFIG_FILE AS F ON (
    R.HAS_FILE = TRUE
    AND F.RESOURCE_ID = R.ID
  )
WHERE
  R.NAME = ?
  AND R.TENANT_ID = ?
  AND R.TYPE_ID = ?
	at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.executeQuery(JdbcTemplate.java:169)
	at org.wso2.carbon.identity.configuration.mgt.core.dao.impl.ConfigurationDAOImpl.getResourceByName(ConfigurationDAOImpl.java:328)
	... 29 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'TRUE'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1676)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:615)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:537)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7730)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3786)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:456)
	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy50.executeQuery(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.executeQuery(JdbcTemplate.java:154)
	... 30 more
```

**Environment information:**
 - Product Version: IS 6.0.0
 - OS: Mac
 - Database: MSSQL
 - Userstore: JDBC

**Comment by ashendes** [comment]
This occurs only when the server is running in migration mode. The server is not intended to function in the migration mode, hence we should recommend the user to restart the server in the normal mode in the docs.

**Comment by Akila94** [comment]
This issue also can occur after restarting the server in normal mode if an incompatible DB driver is used. This [issue](https://github.com/wso2-enterprise/wso2-iam-internal/issues/664) addressed that issue. The solution is to use the latest compatible DB driver.
