### ISSUE TITLE
Cipher tool uses default keystore configs instead of values set in deployment.toml

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#14739]
**Describe the issue:**
When the cipher tool is executed after configuring the keystores in the deployment.toml but without starting the server once, the cipher tool is still trying to use the default values in the carbon.xml which are not yet updated with the new values defined in the deployment.toml

Two workarounds are mentioned in the Workaround section below, but it is not applicable when deploying with automation tools or containerized deployments. Because these deployments take a fresh copy of the product, add the artifacts and configurations and then run the cipher tool before starting the server.

**How to reproduce:**
- Create a new keystore with the following command and place it in <IS_HOME>/repository/resources/security directory
```
keytool -genkey -alias internal -keyalg RSA -keysize 2048 -keystore internal.jks -dname "CN=internal.local, OU=Home,O=Home,L=SL,S=WS,C=LK" -storepass internal -keypass internal
```
- Add the following to deployment.toml 
```
[keystore.internal]
file_name = "internal.jks"
type = "JKS"
password = "internal"
alias = "internal"
key_password = "internal"
```
- Avoid starting the server which will populate the carbon.xml with above config change
- Execute `./bin/ciphertool.sh -Dchange` command and provide the new keystore password when `Internal KeyStore Password` is requested
- It will fail with following log which says password for wso2carbon.jks is incorrect
```
[Please Enter Internal KeyStore Password of Carbon Server : ]
Exception in thread "main" org.wso2.ciphertool.exception.CipherToolException: Error loading keyStore from ' /tmp/wso2is-5.11.0/repository/resources/security/wso2carbon.jks '
	at org.wso2.ciphertool.utils.KeyStoreUtil.getKeyStore(KeyStoreUtil.java:89)
	at org.wso2.ciphertool.utils.KeyStoreUtil.initializeCipher(KeyStoreUtil.java:55)
	at org.wso2.ciphertool.CipherTool.main(CipherTool.java:61)
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
	at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:795)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at org.wso2.ciphertool.utils.KeyStoreUtil.getKeyStore(KeyStoreUtil.java:84)
	... 2 more
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:793)
	... 5 more
```

**Expected behavior:**
It should use the internal keystore defined in the deployment.toml for cipher tool.

**Workaround:**
In addition to the deployment.toml, update the `InternalKeyStore` section of the carbon.xml as well before running the cipher tool OR start the server once to populate values from deployment.toml to carbon.xml before running the cipher tool.

**Environment information** 
 - Product Version: >= IS 5.9.0

**Comment by hwupathum** [comment]
Need to fix the same issue in IS 6.0.0 as well
