### ISSUE TITLE
Error while Identity Migration from 5.10.0 to 6.0.0 with Postgresql

### ISSUE THREAD

**Issue by daoxxx** [wso2/product-is#14905]
**Describe the issue:**
While performing migration from 5.10.0 to 6.0.0 script stumbles upon the following error:

```
[2022-09-20 13:19:28,961] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 5.11.0, Migration Step :
 UserPortalDataMigrator of order : 9 is starting...........................                                                                                   
[2022-09-20 13:19:28,961] []  INFO {org.wso2.carbon.is.migration.service.SchemaMigrator} -  WSO2 Product Migration Service Task : Executing Identity Migration
 Scripts.                                                                                                                                                     
[2022-09-20 13:19:28,967] [] ERROR {org.wso2.carbon.is.migration.service.SchemaMigrator} - Error occurred while executing SQL script for migrating database ja
va.lang.Exception: Error occurred while executing :  UPDATE sp_app SET app_name = 'My Account', is_saas_app = 1, description = 'This is the my account applica
tion.' WHERE ID = (SELECT APP_ID FROM SP_INBOUND_AUTH WHERE INBOUND_AUTH_KEY = 'USER_PORTAL' AND TENANT_ID = -1234)                                           
        at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:318)                                                            
        at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:234)                                                      
        at org.wso2.carbon.is.migration.service.SchemaMigrator.migrate(SchemaMigrator.java:89)                                                                
        at org.wso2.carbon.is.migration.service.v5110.migrator.UserPortalDataMigrator.migrate(UserPortalDataMigrator.java:42)                                 
        at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)                                                                    
        at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:76)                                                              
        at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:151)                                
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                     
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                   
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                           
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                                         
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)                                                         
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)                                                 
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)                                                    
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)                                                           
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)                                                          
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)                                                                            
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)                                                                     
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)                                 
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)                                                    
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)                                                              
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
        at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
        at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
        at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "application_name_constraint"
  Подробности: Key (app_name, tenant_id)=(My Account, -1234) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
        at com.sun.proxy.$Proxy53.execute(Unknown Source)
        at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:273)
        ... 33 more

[2022-09-20 13:19:28,990] [] ERROR {org.wso2.carbon.is.migration.service.SchemaMigrator} - An error occurred while rolling back transactions. java.lang.Except
ion: Error occurred while executing SQL script for migrating database
        at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:244)
        at org.wso2.carbon.is.migration.service.SchemaMigrator.migrate(SchemaMigrator.java:89)
        at org.wso2.carbon.is.migration.service.v5110.migrator.UserPortalDataMigrator.migrate(UserPortalDataMigrator.java:42)
        at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)
        at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:76)
        at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:151)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
        at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
        at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
        at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.Exception: Error occurred while executing :  UPDATE sp_app SET app_name = 'My Account', is_saas_app = 1, description = 'This is the my ac
count application.' WHERE ID = (SELECT APP_ID FROM SP_INBOUND_AUTH WHERE INBOUND_AUTH_KEY = 'USER_PORTAL' AND TENANT_ID = -1234)
        at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:318)
        at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:234)
        ... 32 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "application_name_constraint"
  Подробности: Key (app_name, tenant_id)=(My Account, -1234) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
        at com.sun.proxy.$Proxy53.execute(Unknown Source)
        at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:273)
        ... 33 more

[2022-09-20 13:19:28,993] [] ERROR {org.wso2.carbon.is.migration.MigrationClientImpl} - Migration process was stopped. org.wso2.carbon.identity.core.migrate.M
igrationClientException: Error occurred while executing SQL script for migrating database
        at org.wso2.carbon.is.migration.service.SchemaMigrator.migrate(SchemaMigrator.java:100)
        at org.wso2.carbon.is.migration.service.v5110.migrator.UserPortalDataMigrator.migrate(UserPortalDataMigrator.java:42)
        at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)
        at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:76)
        at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:151)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
        at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
        at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
        at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.Exception: Error occurred while executing SQL script for migrating database
        at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:244)
        at org.wso2.carbon.is.migration.service.SchemaMigrator.migrate(SchemaMigrator.java:89)
        ... 31 more
Caused by: java.lang.Exception: Error occurred while executing :  UPDATE sp_app SET app_name = 'My Account', is_saas_app = 1, description = 'This is the my ac
count application.' WHERE ID = (SELECT APP_ID FROM SP_INBOUND_AUTH WHERE INBOUND_AUTH_KEY = 'USER_PORTAL' AND TENANT_ID = -1234)
        at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:318)
        at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:234)
        ... 32 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "application_name_constraint"
  Подробности: Key (app_name, tenant_id)=(My Account, -1234) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
        at com.sun.proxy.$Proxy53.execute(Unknown Source)
        at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:273)
        ... 33 more

```
IS is running after restart but on the "Service Providers" page there're both User portal and Myaccount applications. Also custom SPs are tripled.
And Console and Myaccout applications ain't available: empty web pages after authentications

**How to reproduce""

<details> 
  <summary>migration-config.yaml</summary>

```

migrationEnable: "true"

# Migration Start Version
currentVersion: "5.10.0"
# Migration End Version
migrateVersion: "6.0.0"

continueOnError: "false"
batchUpdate: "true"
ignoreForInactiveTenants: "true"

migrateTenantRange: "false"
migrationStartingTenantID: "0"
migrationEndingTenantID: "0"

versions:
 -
  version: "5.0.0-SP1"
  migratorConfigs:
   -
    name: "SchemaMigrator"
    order: 1
    parameters:
      location: "step1"
      schema: "identity"
 -
  version: "5.1.0"
  migratorConfigs:
   -
    name: "IdentityDataCleaner"
    order: 1
    parameters:
      schema: "identity"
   -
    name: "SchemaMigrator"
    order: 2
    parameters:
      location: "step1"
      schema: "identity"
   -
    name: "SchemaMigrator"
    order: 3
    parameters:
      location: "step1"
      schema: "um"
   -
    name: "IdentityDataMigrator"
    order: 4
    parameters:
      schema: "identity"
   -
    name: "UMDataMigrator"
    order: 5
    parameters:
      schema: "um"
   -
    name: "RegistryDataMigrator"
    order: 6
    parameters:
      schema: "um"
 -
  version: "5.2.0"
  migratorConfigs:
   -
    name: "SchemaMigrator"
    order: 1
    parameters:
      location: "step1"
      schema: "identity"
   -
    name: "SchemaMigrator"
    order: 2
    parameters:
      location: "step1"
      schema: "um"
 -
  version: "5.3.0"
  migratorConfigs:
   -
    name: "SchemaMigrator"
    order: 1
    parameters:
      location: "step1"
      schema: "identity"
   -
    name: "UserStorePasswordMigrator"
    order: 2
    parameters:
      schema: "identity"
   -
    name: "ClaimDataMigrator"
    order: 3
    parameters:
      schema: "um"
   -
    name: "PermissionDataMigrator"
    order: 4
    parameters:
      schema: "um"
   -
    name: "EmailTemplateDataMigrator"
    order: 5
    parameters:
      schema: "identity"
   -
    name: "ChallengeQuestionDataMigrator"
    order: 6
    parameters:
      schema: "identity"
   -
    name: "ResidentIdpMetadataMigrator"
    order: 7
    parameters:
      schema: "identity"
   -
    name: "OIDCScopeDataMigrator"
    order: 8
    parameters:
      schema: "identity"
 -
  version: "5.4.0"
  migratorConfigs:
   -
    name: "PermissionMigrator"
    order: 1
    parameters:
      schema: "um"
   -
    name: "SchemaMigrator"
    order: 2
    parameters:
      location: "step1"
      schema: "identity"
   -
    name: "SchemaMigrator"
    order: 3
    parameters:
      location: "step1"
      schema: "um"
   -
    name: "UserStorePasswordMigrator"
    order: 4
    parameters:
      schema: "identity"
   -
    name: "ClaimDataMigrator"
    order: 5
    parameters:
      schema: "um"
   -
    name: "OAuthDataMigrator"
    order: 6
    parameters:
      schema: "identity"
   -
    name: "SchemaMigrator"
    order: 7
    parameters:
      location: "step2"
      schema: "identity"
 -
  version: "5.5.0"
  migratorConfigs:
   -
    name: "SchemaMigrator"
    order: 1
    parameters:
      location: "step1"
      schema: "identity"
   -
    name: "SchemaMigrator"
    order: 2
    parameters:
      location: "step1"
      schema: "consent"
   -
    name: "OAuthDataMigrator"
    order: 3
    parameters:
      batchSize: 10000
      schema: "identity"
   -
    name: "BPSProfileDataMigrator"
    order: 4
    parameters:
      schema: "identity"
   -
    name: "UserStorePasswordMigrator"
    order: 5
    parameters:
      schema: "identity"
   -
    name: "SysLogPropertiesMigrator"
    order: 6
   -
    name: "SchemaMigrator"
    order: 7
    parameters:
      location: "step2"
      schema: "identity"
   -
    name: "PolicySubscriberDataMigrator"
    order: 8
    parameters:
      schema: "identity"
   -
    name: "KeyStorePasswordMigrator"
    order: 9
    parameters:
      schema: "identity"
      currentEncryptionAlgorithm: "RSA"
      migratedEncryptionAlgorithm: "RSA/ECB/OAEPwithSHA1andMGF1Padding"
      transformToSymmetric: "true"
   -
    name: "SecurityPolicyPasswordMigrator"
    order: 10
    parameters:
      schema: "identity"
   -
    name: "EventPublisherMigrator"
    order: 11
 -
  version: "5.6.0"
  migratorConfigs:
    -
      name: "SchemaMigrator"
      order: 1
      parameters:
        location: "step1"
        schema: "identity"
    -
      name: "SpClaimDialectSchemaMigrator"
      order: 2
      parameters:
        location: "step2"
        schema: "identity"
    -
      name: "ClaimDataMigrator"
      order: 3
    -
      name: "SessionDataMigrator"
      order: 4
      parameters:
        schema: "identity"
 -
  version: "5.7.0"
  migratorConfigs:
    -
      name: "SchemaMigrator"
      order: 1
      parameters:
        location: "step1"
        schema: "uma"
    -
      name: "SchemaMigrator"
      order: 2
      parameters:
        location: "step1"
        schema: "identity"
    -
      name: "SchemaMigrator"
      order: 3
      parameters:
        location: "step1"
        schema: "consent"
    -
      name: "OAuthDataMigrator"
      order: 4
      parameters:
        batchSize: 10000
        schema: "identity"
    -
      name: "OIDCScopeDataMigrator"
      order: 5
 -
  version: "5.8.0"
  migratorConfigs:
    -
      name: "SchemaMigrator"
      order: 1
      parameters:
        location: "step1"
        schema: "identity"
    -
      name: "IDPIDColumnAdditionInH2Migrator"
      order: 2
      parameters:
        schema: "identity"
    -
      name: "UMAPermissionTicketSchemaMigrator"
      order: 3
      parameters:
        location: "step2"
        schema: "uma"
    -
      name: "SchemaMigrator"
      order: 4
      parameters:
        location: "step3"
        schema: "identity"
    -
      name: "OAuthDataMigrator"
      order: 5
      parameters:
        schema: "identity"
 -
   version: "5.9.0"
   migratorConfigs:
   -
     name: "SchemaMigrator"
     order: 1
     parameters:
       location: "step1"
       schema: "identity"
   -
     name: "ClaimDataMigrator"
     order: 2
 -
   version: "5.10.0"
   migratorConfigs:
   -
     name: "ScopeDataMigrator"
     order: 1
   -
     name: "MigrationValidator"
     order: 2
   -
     name: "SchemaMigrator"
     order: 3
     parameters:
       location: "step1"
       schema: "identity"
   -
     name: "SchemaMigrator"
     order: 4
     parameters:
       location: "step1"
       schema: "um"
   -
     name: "SchemaMigrator"
     order: 5
     parameters:
       location: "step2"
       schema: "identity"
   -
     name: "OAuth2ScopesMigrator"
     order: 6
   -
     name: "ClaimDataMigrator"
     order: 7
   -
     name: "EmailTemplateDataMigrator"
     order: 8
   -
     name: "SchemaMigrator"
     order: 9
     parameters:
       location: "step2"
       schema: "um"
   -
     name: "UserIDMigrator"
     order: 10
     parameters:
       # Migrate all the tenants and all the user store domains in it.
       migrateAll: true
       # Absolute path for the dry report. This is required in the dry run mode.
       reportPath: /home/dao/wso2is_email/wso2is-6.0.0/migration-report/report.txt
       # If migrating only few tenants, this configuration should be repeated for each tenant. (Optional)
       # tenant1:
         # Domain name of the tenant. (Mandatory)
         # tenantDomain: carbon.super
         # Number of users to be updated in each iteration. (Optional)
         # increment: 100
         # Where should the migration should start from (Offset). This is useful if the migration stopped middle and needs to restart. (Optional)
         # startingPoint: 0
         # Whether SCIM enabled for user stores in this tenant. (Optional)
         # scimEnabled: false
         # List of comma separated domain names which should be migrated in this domain. (Optional)
         # migratingDomains: "PRIMARY"
         # Mark whether user IDs should be updated even though there is already an ID there. (Optional)
         # forceUpdateUserId: true
   -
     name: "TenantPortalMigrator"
     order: 11

 -
   version: "5.11.0"
   migratorConfigs:
   -
     name: "EncryptionAdminFlowMigrator"
     order: 1
     parameters:
       currentEncryptionAlgorithm: "RSA/ECB/OAEPwithSHA1andMGF1Padding"
       migratedEncryptionAlgorithm: "AES/GCM/NoPadding"
       schema: "identity"
   -
     name: "EncryptionUserFlowMigrator"
     order: 2
     parameters:
       currentEncryptionAlgorithm: "RSA/ECB/OAEPwithSHA1andMGF1Padding"
       migratedEncryptionAlgorithm: "AES/GCM/NoPadding"
       schema: "identity"
   -
    name: "SchemaMigrator"
    order: 3
    parameters:
      location: "step1"
      schema: "um"
   -
     name: "GroupsAndRolesMigrator"
     order: 4
     parameters:
       # Absolute path for the dry report. This is required in the dry run mode.
       reportPath: /home/dao/wso2is_email/wso2is-6.0.0/migration-report/report.txt
       # Admin role of the current version. This is required only if changing the name of admin role in migrate Version.
       # currentAdminRoleName:
   - name: "ConfigurationManagementSchemaMigrator"
     order: 5
     parameters:
       location: "step1"
       schema: "identity"
   - name: "SchemaMigrator"
     order: 6
     parameters:
       location: "step2"
       schema: "identity"
   - name: "SchemaMigrator"
     order: 7
     parameters:
       location: "step3"
       schema: "um"
   - name: "SchemaMigrator"
     order: 8
     parameters:
       location: "step3"
       schema: "identity"
   - name: "UserPortalDataMigrator"
     order: 9
     parameters:
       location: "step4"
       schema: "identity"
   - name: "UserPortalDataMigrator"
     order: 10
     parameters:
       location: "step4"
       schema: "um"
   - name: "TokenBindingValidationMigrator"
     order: 11
     parameters:
       # Absolute path for the dry report. This is required in the dry run mode.
       reportPath: /home/dao/wso2is_email/wso2is-6.0.0/migration-report/report.txt
   - name: "ClaimDataMigrator"
     order: 12
   - name: "SchemaMigrator"
     order: 13
     parameters:
       location: "step5"
       schema: "identity"
   - name: "SchemaMigrator"
     order: 14
     parameters:
       location: "step5"
       schema: "um"
   - name: "EmailTemplateDataMigrator"
     order: 15
   - name: "SchemaMigrator"
     order: 16
     parameters:
       location: "step6"
       schema: "identity"
   - name: "SchemaMigrator"
     order: 17
     parameters:
       location: "step6"
       schema: "um"
   - name: "SCIMGroupRoleMigrator"
     order: 18
 -
   version: "6.0.0"
   migratorConfigs:
   -
     name: "ApplicationAccessURLMigrator"
     order: 1
     parameters:
       # Absolute path for the dry report. This is required in the dry run mode.
       reportPath: /home/dao/wso2is_email/wso2is-6.0.0/migration-report/report.txt

   - name: "SchemaMigrator"
     order: 2
     parameters:
       location: "step1"
       schema: "identity"

   - name: "SchemaMigrator"
     order: 3
     parameters:
       location: "step2"
       schema: "identity"

   - name: "SchemaMigrator"
     order: 4
     parameters:
       location: "step3"
       schema: "consent"

   - name: "SchemaMigrator"
     order: 5
     parameters:
       location: "step4"
       schema: "identity"

   - name: "ClaimDataMigrator"
     order: 6
     parameters:
       overrideExistingClaims: "true"
       useOwnClaimDataFile: "true"

   - name: "SchemaMigrator"
     order: 7
     parameters:
       location: "step5"
       schema: "identity"

   - name: "SchemaMigrator"
     order: 8
     parameters:
       location: "step5"
       schema: "um"

   - name: "SchemaMigrator"
     order: 9
     parameters:
       location: "step6"
       schema: "identity"

   - name: "SchemaMigrator"
     order: 10
     parameters:
       location: "step7"
       schema: "identity"

   - name: "SchemaMigrator"
     order: 11
     parameters:
       location: "step7"
       schema: "consent"

   - name: "SchemaMigrator"
     order: 12
     parameters:
       location: "step7"
       schema: "um"

   - name: "RecoveryDataMigrator"
     order: 13

   - name: "SCIMGroupSchemaMigrator"
     order: 14
     parameters:
       location: "step8"
       schema: "identity"
       # Absolute path for the dry report. This is required in the dry run mode.
       reportPath: /home/dao/wso2is_email/wso2is-6.0.0/migration-report/report.txt

   - name: "SystemAppMigrator"
     order: 15
     parameters:
        consoleRedirectUrl: "regexp=(https://localhost:9443/console|https://localhost:9443/t/(.*)/console)"
        consoleAccessUrl: "https://localhost:9443/console"
        myaccountRedirectUrl: "regexp=(https://localhost:9443/myaccount|https://localhost:9443/t/(.*)/myaccount)"
        myaccountAccessUrl: "https://localhost:9443/myaccount"
        accessTokenBindingType: "cookie"

   - name: "AppInboundAuthMigrator"
     order: 16

   - name: "OIDCScopeDataMigrator"
     order: 17

```

</details>

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.10.0
 - OS: Linux
 - Database: Postgresql 11
 - Userstore: JDBC

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
