### ISSUE TITLE
Number format exception when assigning roles

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#1495]
Precondition: 
1.at least 2 users admin/non-admin users should exist
2.both users should have registered service providers

Setup
1.JDBC User Store.
2.MSSQL Data store.
3.Email as a user name.
4.IS.5.3.0 as a key-manager WUM staging standalone pack ( WUM Update 30th November.)

Note: when a service provider is created a role is also assigned. And a non admin user with Role Management permission can view all roles created. 
Ex:Application/HybridServiceProvider_123 

Steps
1.create a role as an admin user
2.assign a role to self from the roles list by selecting a role that is created when a SP is added.
rom user store chain.
[2017-12-05 15:42:01,645] ERROR {org.wso2.carbon.apimgt.keymgt.listeners.KeyManagerUserOperationListener} -  Error occurred while invalidating the Gateway Token Cache of Gateway 'Production and Sandbox'
org.apache.axis2.AxisFault: API gateway URL is malformed
	at org.wso2.carbon.apimgt.impl.utils.APIAuthenticationAdminClient.loginGateway(APIAuthenticationAdminClient.java:172)
	at org.wso2.carbon.apimgt.impl.utils.APIAuthenticationAdminClient.setup(APIAuthenticationAdminClient.java:131)
	at org.wso2.carbon.apimgt.impl.utils.APIAuthenticationAdminClient.<init>(APIAuthenticationAdminClient.java:57)
	at org.wso2.carbon.apimgt.keymgt.listeners.KeyManagerUserOperationListener.getApiAuthenticationAdminClient(KeyManagerUserOperationListener.java:197)
	at org.wso2.carbon.apimgt.keymgt.listeners.KeyManagerUserOperationListener.removeGatewayKeyCache(KeyManagerUserOperationListener.java:182)
	at org.wso2.carbon.apimgt.keymgt.listeners.KeyManagerUserOperationListener.doPreUpdateRoleListOfUser(KeyManagerUserOperationListener.java:125)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.updateRoleListOfUserInternal(AbstractUserStoreManager.java:1988)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.access$300(AbstractUserStoreManager.java:75)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$6.run(AbstractUserStoreManager.java:1867)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$6.run(AbstractUserStoreManager.java:1864)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.updateRoleListOfUser(AbstractUserStoreManager.java:1864)
	at org.wso2.carbon.user.mgt.UserRealmProxy.updateRolesOfUser(UserRealmProxy.java:1939)
	at org.wso2.carbon.user.mgt.UserAdmin.addRemoveRolesOfUser(UserAdmin.java:561)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212)
	at org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic(RPCMessageReceiver.java:117)
	at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40)
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:169)
	at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:82)
	at org.wso2.carbon.core.transports.local.CarbonLocalTransportSender.finalizeSendWithToAddress(CarbonLocalTransportSender.java:45)
	at org.apache.axis2.transport.local.LocalTransportSender.invoke(LocalTransportSender.java:77)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:430)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.wso2.carbon.user.mgt.stub.UserAdminStub.addRemoveRolesOfUser(UserAdminStub.java:5666)
	at org.wso2.carbon.user.mgt.ui.UserAdminClient.addRemoveRolesOfUser(UserAdminClient.java:254)
	at org.apache.jsp.user.edit_002duser_002droles_002dfinish_002dajaxprocessor_jsp._jspService(edit_002duser_002droles_002dfinish_002dajaxprocessor_jsp.java:229)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:61)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:91)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:60)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.MalformedURLException: For input string: "{port}"
	at java.net.URL.<init>(URL.java:623)
	at java.net.URL.<init>(URL.java:486)
	at java.net.URL.<init>(URL.java:435)
	at org.wso2.carbon.apimgt.impl.utils.APIAuthenticationAdminClient.loginGateway(APIAuthenticationAdminClient.java:170)
	... 88 more
Caused by: java.lang.NumberFormatException: For input string: "{port}"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:217)
	at java.net.URL.<init>(URL.java:618)
	... 91 more

**Comment by shavantha** [comment]
even though the IS as KM pack was started as a standalone pack and the api-mgt.xml was not changed from its default configs, this issue should not be thrown

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
