### ISSUE TITLE
XACML fails if userstores are not defined in uppercase.

### ISSUE THREAD

**Issue by nipunaupeksha** [wso2/product-is#15112]
**Describe the issue:**
When XACML policies are used with the userstores which has domain names with either uppercase, lowercase or mixed case, they will only work with the userstores with uppercase domain names. For domain names with lowercase we need to replace them with uppercase to use the XACML policies. 

**How to reproduce:**
1. Create an SP (e.g. travelocity.com) and  for `Local and Outbound Authentication Configuration` check `Enable Authorization`
2. Create a secondary JDBC userstore(e.g. using postgres) and provide `Temporary` as its domain name.
3. Create a new XACML policy and publish it. For example, use `authn_user_store_based_policy_template` and for the SP name type `travelocity.com` and for userstore type `Temporary`.
4. Create a user in the secondary userstore.
5. Try to log in with the SP. Which will give `Authentication attempt failed.` error in UI.
6. Then change the userstore name to `TEMPORARY` in the XACML policy we defined and publish it again.
7. After that, when you try to log in with the SP it will work.
8. Following debug log can be seen when trying out step 5.
```
[2022-10-28 23:38:34,913] [1961d4b6-4a4d-4464-ba83-5d1f727d24db] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Error occurred while evaluating post authentication org.wso2.carbon.identity.application.authentication.framework.exception.PostAuthenticationFailedException: Error while trying to evaluate authorization
	at org.wso2.carbon.identity.application.authz.xacml.handler.impl.XACMLBasedAuthorizationHandler.handle(XACMLBasedAuthorizationHandler.java:130)
...
Caused by: org.wso2.carbon.identity.application.authentication.framework.exception.PostAuthenticationFailedException: XACML policy evaluation failed for user
	at org.wso2.carbon.identity.application.authz.xacml.handler.impl.XACMLBasedAuthorizationHandler.handle(XACMLBasedAuthorizationHandler.java:124)
	... 66 more
```

**Expected behavior:**
When using the userstore domain name in the XACML policies it should work.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0 (U2 193)
 - OS: Mac
 - Userstore: Postgres (Secondary userstore)

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/2026

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
