### ISSUE TITLE
Downloadable avis.com and travelocity.com should be updated in 5.4.0 doc

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1519]
Downloadable avis.com and travelocity.com should be updated in 5.4.0 doc [1].

[1] https://docs.wso2.com/display/IS540/Customizing+Login+Pages+for+Service+Providers#CustomizingLoginPagesforServiceProviders-Configuringtwoserviceproviders

Downloadable wars in below step is not up todate. Hence it gives a SAML assertion error.

**Configuring two service providers**
1. Copy the travelocity.com.war and avis.com.war files to your application server (Tomcat 7 was used for this sample scenario).

This error does not come when you use the war which you create by building the 5.4.0 sample in here [2]

[2] https://docs.wso2.com/display/IS540/Downloading+a+Sample

```
Dec 13, 2017 2:30:31 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [jsp] in context with path [/avis.com] threw exception [Signature validation failed for SAML2 Response] with root cause
org.wso2.carbon.identity.sso.agent.SSOAgentException: Signature validation failed for SAML2 Response
	at org.wso2.carbon.identity.sso.agent.saml.SAML2SSOManager.validateSignature(SAML2SSOManager.java:685)
	at org.wso2.carbon.identity.sso.agent.saml.SAML2SSOManager.processSSOResponse(SAML2SSOManager.java:436)
	at org.wso2.carbon.identity.sso.agent.saml.SAML2SSOManager.processResponse(SAML2SSOManager.java:301)
	at org.wso2.carbon.identity.sso.agent.SSOAgentFilter.doFilter(SSOAgentFilter.java:97)
	at org.wso2.sample.is.sso.agent.SSOAgentSampleFilter.doFilter(SSOAgentSampleFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:947)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by shavidissa** [comment]
Thank you! Updated the docs so that the user has to clone the samples repo for 5.4 before starting.

[1] https://docs.wso2.com/display/IS540/Customizing+Login+Pages+for+Service+Providers
