### ISSUE TITLE
Misguiding error message in SCIMUserOperationListener

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#15316]
**Describe the issue:**
`Error while reading isSCIMEnabled` message is written from SCIMUserOperationListener [1] [2] [3] for any UserStoreException which is misguiding. It should be a generic message since the stacktrace will include the rest of the information.

Eg:
```
ERROR {org.apache.axis2.rpc.receivers.RPCInOnlyMessageReceiver} - Error while reading isSCIMEnabled from user store manager org.wso2.carbon.user.core.UserStoreException: Error while reading isSCIMEnabled from user store manager
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:254)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4758)
	at org.wso2.carbon.um.ws.service.UserStoreManagerService.addUser(UserStoreManagerService.java:57)
	...
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:235)
	... 67 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:238)
	... 69 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error while reading isSCIMEnabled from user store manager
	at org.wso2.carbon.identity.scim2.common.listener.SCIMUserOperationListener.doPostAddUserWithID(SCIMUserOperationListener.java:133)
	at org.wso2.carbon.identity.mgt.listener.IdentityUserIdResolverListener.doPostAddUser(IdentityUserIdResolverListener.java:165)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:5066)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4792)
	... 74 more
Caused by: org.wso2.carbon.user.core.UserStoreException: 30007 - UserNotFound: User 9423 does not exist in: test.com
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.setUserClaimValue(AbstractUserStoreManager.java:4229)
	at org.wso2.carbon.identity.scim2.common.listener.SCIMUserOperationListener.doPostAddUserWithID(SCIMUserOperationListener.java:128)
	... 77 more
```

[1] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/14c650b33f7509d1ba2d9635356e3960fde10dc4/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java#L107
[2] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/14c650b33f7509d1ba2d9635356e3960fde10dc4/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java#L132
[3] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/14c650b33f7509d1ba2d9635356e3960fde10dc4/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/listener/SCIMUserOperationListener.java#L537

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
