### ISSUE TITLE
SCIM2 requests fails for users with '+' in their user ID

### ISSUE THREAD

**Issue by isuruirj** [wso2/product-is#15317]
**Describe the issue:**
java.net.URISyntaxException occurs when performing any SCIM operation if the user id used in the request URL is having '+' sign.

```[2023-01-03 21:34:24,053] ERROR {org.wso2.carbon.identity.auth.valve.AuthenticationValve} -  Error while normalizing the request URI to process the authentication: 
java.net.URISyntaxException: Illegal character in path at index 31: /scim2/Users/portal2.automation MariamFaroukDEV@gmail.com
	at java.net.URI$Parser.fail(URI.java:2873)
	at java.net.URI$Parser.checkChars(URI.java:3046)
	at java.net.URI$Parser.parseHierarchical(URI.java:3130)
	at java.net.URI$Parser.parse(URI.java:3088)
	at java.net.URI.<init>(URI.java:588)
	at org.wso2.carbon.identity.auth.service.util.AuthConfigurationUtil.getNormalizedRequestURI(AuthConfigurationUtil.java:224)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:69)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1201)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1782)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1741)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
```
**How to reproduce:**

- In an updated IS-5.7.0 pack, change the mapped attribute of the user id to username or another attribute.
- create a new user with '+' in their userid.
- perform SCIM GET/PATCH..... operation 

`curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"add","value":{"nickName":"shaggy"}}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users/abc+def`

`curl -v -k --user admin:admin 'https://localhost:9443/scim2/Users/abc+def'`

**Expected behavior:**
Should be able to perform SCIM operations without any failures.

**Environment information**  **:**
 - Product Version:[ IS 5.7.0]

**Comment by lashinijay** [comment]
**Analysis of the issue**

- It is expected from users to invoke API only after URL encoding them. Therefore Ideally this issue will not be happening after the usernames with `+` are properly encoded in the URL.
- However, when analyzing this issue it was discovered that there are two issues in this flow even if the URL is properly encoded. 
- The first issue is, the URIs are normalized in the `Authentication Valve` twice causing a `URISyntaxException`.
[https://github.com/wso2-extensions/identity-carbon-auth-rest/blob/master/components/org.wso2.carbon.identity.auth.service/src/main/java/org/wso2/carbon/identity/auth/service/factory/AuthenticationRequestBuilderFactory.java#L86-L87](https://github.com/wso2-extensions/identity-carbon-auth-rest/blob/master/components/org.wso2.carbon.identity.auth.service/src/main/java/org/wso2/carbon/identity/auth/service/factory/AuthenticationRequestBuilderFactory.java#L86-L87)
Eg: URL encoded value of `abc+def` is `abc%2Bdef`, when this is normalized for the first time it will be decoded to the expected value of `abc+def` and after normalized for the second time it will return `abc def` causing an issue as this an invalid URI syntax.
- The second issue is, there is an issue with resolving users with username even the special characters such as `+` are not present in the username. The following error was thrown.
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "detail": "User abc+def does not exist in: PRIMARY",
    "status": "404"
}
```

**Comment by lashinijay** [comment]
**This issue will not be fixed in the master branch**

With [this PR](https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/227) it will only resolve the issue in invoking URL normalization twice in the `Authentication valve` level. However, with that fix, failing to execute the SCIM request after claim mapping will not be fixed. As we have migrated to `unique ID user stores` from IS-5.10, mapping user id to other attributes is not a recommended approach unless the customer is plugging an existing user store into the product. Hence the mentioned flow will not be supported in the WSO2 IS latest products.
