### ISSUE TITLE
Unable to host IS-6.1.0 webapps externally

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#15721]
**Describe the issue:**

When hosting the authenticationendpoint and accountrecoveryendpoint apps on a different server according to the official documentation [1] and trying to login to a service provider an error message is received when loading the login page and a NPE is printed on the log:

![image](https://user-images.githubusercontent.com/55197812/231472575-3d076b01-b15a-4d1a-8a33-46cf53db1936.png)

```
SEVERE [http-nio-8080-exec-59] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [default] in context with path [/authenticationendpoint] threw exception
	java.lang.NullPointerException
		at org.wso2.carbon.identity.core.DefaultServiceURLBuilder.fetchPort(DefaultServiceURLBuilder.java:318)
		at org.wso2.carbon.identity.core.DefaultServiceURLBuilder.build(DefaultServiceURLBuilder.java:90)
		at org.wso2.carbon.identity.application.authentication.endpoint.util.filter.AuthParameterFilter.buildAPIPath(AuthParameterFilter.java:134)
		at org.wso2.carbon.identity.application.authentication.endpoint.util.filter.AuthParameterFilter.getServletRequestWithParams(AuthParameterFilter.java:114)
		at org.wso2.carbon.identity.application.authentication.endpoint.util.filter.AuthParameterFilter.doFilter(AuthParameterFilter.java:82)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:750)
```
As per the above stacktrace, at [5] the `IdentityCoreServiceComponent.getConfigurationContextService()` method returns `null` hence the NPE.

This configuration seems to be loaded from the XML files on <IS_HOME>/repository/conf/axis2 directory on a normal setup, but on this kind of setup the external server should be able to load this configuration into context and avoid the NPE.

**How to reproduce:**
- Install an external Tomcat server.
- Deploy the `authenticationendpoint` and `accountrecoveryendpoint` apps on the external server by following the steps at [3] & [4]. Kindly notice that this scripts are outdated and there are other dependencies that needed to be copied manually to prevent `java.lang.ClassNotFoundException`s. Please consider to update this scripts as well.
- Configure the IS to point the external server by following the steps at [1].
- Configure the `authenticationendpoint` and `accountrecoveryendpoint` apps on an external server by following the steps at [1] & [2]. Kindly notice that the 6.1.0 docs [1] only explains the steps to host the `authenticationendpoint` app externally, for the `accountrecoveryendpoint` app you need to refer to 5.11.0 docs [2].
- Start the IS and Tomcat servers.
- Try to login to a service provider configured on IS.

**Expected behavior:**

Webapps should work without issues regardless of the server where they are hosted on.

**Environment information:**
 - Product Version: IS 6.1.0

---
[1] https://is.docs.wso2.com/en/latest/references/extend/host-authentication-endpoint-on-a-different-server/
[2] https://is.docs.wso2.com/en/5.11.0/develop/hosting-authentication-endpoint-on-a-different-server/
[3] https://github.com/wso2/samples-is/blob/master/host-endpoints-externally/setup-authentication-endpoint.sh
[4] https://github.com/wso2/samples-is/blob/master/host-endpoints-externally/setup-accountrecovery-endpoint.sh
[5] https://github.com/wso2/carbon-identity-framework/blob/v5.25.92/components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/DefaultServiceURLBuilder.java#L317

**Comment by Thisara-Welmilla** [comment]
Hi Juan,

Please find the U2 entry [1] and ETA below.

Best Case : 2023-04-28
Most Likely : 2023-05-05
Worst Case : 2023-05-12

Since the ETA is shared we are closing the issue. Feel free to re-open the issue if you need further assistance on this.

[1] https://identity-internal-gateway.cloud.wso2.com/t/wso2internal928/umt/update?updateId=6942&type=viewUpdate

Best Regards,
Thisara

**Comment by sadilchamishka** [comment]
The NPE can be avoided by uncommenting the below config in the ./webapps/authenticationendpoint/WEB-INF/web.xml file
 <context-param>
    <param-name>AuthenticationRESTEndpointURL</param-name>
    <param-value>https://localhost:9443/api/identity/auth/v1.1/</param-value>
</context-param>

Also, you won't need to manually add the missing jar files in order to avoid the class not found exceptions. Run the below script when hosting the authenticationendpoint in the external server.
https://github.com/ImalshaG/samples-is/blob/login-portal-script/host-endpoints-externally/setup-authentication-endpoint.sh

But still there is one jar is missing. Copy the $IS_HOME/lib/runtimes/cxf3/org.wso2.carbon.identity.mgt.endpoint.util-5.25.92.jar and paste into the 
./webapps/authenticationendpoint/WEB-INF/lib folder.

**Comment by sadilchamishka** [comment]
For the account recovery portal the [script](https://github.com/wso2/samples-is/blob/master/host-endpoints-externally/setup-accountrecovery-endpoint.sh) is updated. Hence no need to manually copy the jars.

The configuration mentioned in this [doc](https://is.docs.wso2.com/en/5.10.0/develop/hosting-authentication-endpoint-on-a-different-server/#moving-the-authenticationendpoint-from-wso2is-and-hosting-it-on-a-separate-web-server) suggest to configure as below.
```
identity.server.service.contextURL=https://localhost:9443/services/
```

But having the `/services/` cause an issue. Hence had to remove that.  Ref - https://github.com/wso2/product-is/issues/10315#issuecomment-1271213532

Then, the validate callback url during password recovery is failing due to recent change done for validating the callback url due to a security issue. That logic fails when hosting the recovery portal outside the IS.
- https://github.com/wso2/identity-apps/pull/3129

Removing those logic let the recovery portal working smoothly. But as the validate callback url is required, working on implementing an alternative implementation to do the validation.
- https://github.com/wso2/identity-apps/pull/3453
- https://github.com/wso2/carbon-identity-framework/pull/4268 

With all these fixes, still there is an improvement to be made. The email sent for the account/password recovery along with a reset link is not pointing to the remotely hosted recovery portal. It should be fixed along with this effor.
