### ISSUE TITLE
`service_url` mishandling

### ISSUE THREAD

**Issue by Manchiz** [wso2/product-is#15771]
**Describe the issue:**
Observed the following ERROR and stack trace while attempting to recover the username when the `identity_server_service_url` was configured in the deployment.toml file.

<img width="830" alt="Screenshot 2023-04-25 at 10 14 07 PM" src="https://user-images.githubusercontent.com/42811248/234442400-03c7b413-4d7d-495b-a8c4-ea49c582fad3.png">

<details open>
<summary>wso2carbon.log</summary>
<be>
    
    [2023-04-25 20:23:01,963] [81e9fce3-3024-441f-a82e-b979f9fe363d]  INFO {org.apache.axis2.transport.http.HTTPSender} - Unable to sendViaPost to url[https://localhost:9443/IdentityProviderMgtService.IdentityProviderMgtServiceHttpsSoap11Endpoint/] org.apache.axis2.AxisFault: Transport error: 401 Error: 
	at org.apache.axis2.transport.http.HTTPSender.handleResponse(HTTPSender.java:407)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:224)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:82)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:459)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:286)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:442)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.wso2.carbon.idp.mgt.stub.IdentityProviderMgtServiceStub.getResidentIdP(IdentityProviderMgtServiceStub.java:461)
	at org.wso2.carbon.identity.mgt.endpoint.util.client.CallBackValidator.isValidCallbackURL(CallBackValidator.java:77)
	at org.apache.jsp.username_002drecovery_002dcomplete_jsp._jspService(username_002drecovery_002dcomplete_jsp.java:165)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:385)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313)
	at org.apache.jsp.recovery_jsp._jspService(recovery_jsp.java:295)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:93)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:114)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

    
</details>

Upon further analysis, it has been noticed that the issue occurred when invoking the `/IdentityProviderMgtService.IdentityProviderMgtServiceHttpsSoap11Endpoint` SOAP API without the `/services` prefix since SOAP API should be hosted under the path `/services`. It was also observed that there is a mishandling at [2] while building the URL.

Also, there is a configuration difference between versions 5.10 and 5.11. Specifically, in version 5.11, the URL should not include the `/services` prefix. Additionally, it seems that the documentation for version 5.11 was misleading, as it indicated that the `identity_server_service_url` should include the `/services prefix` [1]. A separate issue has been created to address this documentation error [3].

**How to reproduce:**

1. Add the below config to the deployment.toml file

`[identity.auth_framework.endpoint]`
`identity_server_service_url = "https://localhost:9443"`

2. Attempt to recover the username.

**Expected behavior:**
The URL should be constructed correctly, such that when calling SOAP API, the `/services` prefix should be included.

**Environment information** 
 - Product Version: IS 5.11
---

[1]. https://github.com/wso2/carbon-identity-framework/blob/v5.18.187/components/identity-mgt/org.wso2.carbon.identity.mgt.endpoint.util/src/main/java/org/wso2/carbon/identity/mgt/endpoint/util/client/CallBackValidator.java#L70

[2].  https://is.docs.wso2.com/en/5.11.0/develop/hosting-authentication-endpoint-on-a-different-server/#moving-the-accountrecoveryendpoint-from-wso2is-and-hosting-it-on-a-separate-web-server:~:text=deployment.toml%20file.-,%5Bidentity.auth_framework.endpoint%5D%0Aidentity_server_service_url%3D%22https%3A//%24ref%7Bserver.hostname%7D%3A9443/services%22,-Uncomment%20and%20change

[3]. https://github.com/wso2/product-is/issues/15789

**Comment by mifrazmurthaja** [comment]
The correct configuration to be used in 5.11 is without the /service as follows,
```
[identity.auth_framework.endpoint]
identity_server_service_url = "https://test.com:9443"
```

Ref: https://github.com/wso2/product-is/issues/12741
https://github.com/wso2/product-is/issues/12577
https://github.com/wso2/product-is/issues/12138
