### ISSUE TITLE
EmptyStackException when trying to access any part of the IS

### ISSUE THREAD

**Issue by cl0ckw0rk** [wso2/product-is#15861]
**Describe the issue:**

I had a working installation of IS 5.11.0. About a day ago I observed that a weird issue comes up, here is the stacktrace from the logs:

```
TID: [-1234] [] [2023-05-12 01:10:19,230] [5d9acdfa-18b6-492d-9d56-39530a105391] ERROR {org.wso2.carbon.tomcat.ext.valves.CompositeValve} - Could not handle request: / java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:102)
	at java.base/java.util.Stack.pop(Stack.java:84)
	at org.wso2.carbon.context.internal.CarbonContextDataHolder.endTenantFlow(CarbonContextDataHolder.java:1295)
	at org.wso2.carbon.context.PrivilegedCarbonContext.endTenantFlow(PrivilegedCarbonContext.java:75)
	at org.wso2.carbon.identity.application.authentication.framework.util.FrameworkUtils.endTenantFlow(FrameworkUtils.java:1675)
	at org.wso2.carbon.identity.cors.mgt.core.dao.impl.CORSConfigurationDAOImpl.getCORSConfigurationByTenantDomain(CORSConfigurationDAOImpl.java:78)
	at org.wso2.carbon.identity.cors.service.internal.impl.CORSManagerImpl.getCORSConfiguration(CORSManagerImpl.java:93)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:81)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:102)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
I have absolutely no idea why that stack is empty. Can you please help?

**How to reproduce:**

Unfortunately I don't know how to reproduce this

**Expected behavior:**

As I said, two days ago it was working fine and yesterday it didn't. I didn't change the config or something like that, so I expect this should worked as it worked before.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0
 - OS: Linux
 - Database: H2
 - Userstore: LDAP

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
