### ISSUE TITLE
Error when trying to recover username with MSSQL

### ISSUE THREAD

**Issue by Shalindri** [wso2/product-is#15875]
**Describe the issue:**
 When a user in MSSQL JDBCUserStore tries to recover the username, with two or more claim filters(ex:- firstname and lastname| firstname, lastname, email...) it fails with the following error.

```
TID: [-1234] [api/identity/recovery/v0.9] [2023-05-15 17:14:37,739] [f6e8f00c-cbfd-4606-bbb3-858d822b4ddb] ERROR {org.wso2.carbon.identity.recovery.endpoint.impl.RecoverUsernameApiServiceImpl} - Error occurred in the server while performing the task. org.wso2.carbon.identity.recovery.IdentityRecoveryException: Error occurred while retrieving users.
	at org.wso2.carbon.identity.recovery.internal.service.impl.UserAccountRecoveryManager.getUsernameByClaims(UserAccountRecoveryManager.java:338)
	at org.wso2.carbon.identity.recovery.internal.service.impl.username.UsernameRecoveryManagerImpl.initiate(UsernameRecoveryManagerImpl.java:93)
	at org.wso2.carbon.identity.recovery.username.NotificationUsernameRecoveryManager.initiateUsernameRecovery(NotificationUsernameRecoveryManager.java:185)
	at org.wso2.carbon.identity.recovery.username.NotificationUsernameRecoveryManager.verifyUsername(NotificationUsernameRecoveryManager.java:155)
	at org.wso2.carbon.identity.recovery.endpoint.impl.RecoverUsernameApiServiceImpl.recoverUsernamePost(RecoverUsernameApiServiceImpl.java:35)
	at org.wso2.carbon.identity.recovery.endpoint.RecoverUsernameApi.recoverUsernamePost(RecoverUsernameApi.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:133)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:59)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:124)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occur while doGetUserList for multi attribute searching
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doGetUserList(JDBCUserStoreManager.java:4164)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getFilteredUsers(AbstractUserStoreManager.java:14617)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserListWithID(AbstractUserStoreManager.java:14576)
	at org.wso2.carbon.identity.recovery.internal.service.impl.UserAccountRecoveryManager.getUsernameByClaims(UserAccountRecoveryManager.java:316)
	... 67 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near ')'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:258)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1535)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:467)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:409)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7151)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2478)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:219)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:199)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:331)
	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy51.executeQuery(Unknown Source)
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doGetUserList(JDBCUserStoreManager.java:4147)
	... 70 more
```

**How to reproduce:**

1. Setup the latest IS 5.10.0 version with an MSSQL DB
2. Create a secondary JDBCUserStore 
3. Create a user in the secondary user store 
4. Configure a Service Provider with Identifier first as the first step
5. Enable Username Recovery from the management console ( Resident found under the Identity Providers --> Account Management Policies --> Account Recovery )
6. Click the Forgot Username link.
7. Enter values for two or more fields and click Submit

**RCA:**

- When we attempt the username recovery flow, the getFilteredUsers[1] method is called for each user store. In the case of having an MSSQL JDBCUserstore configured, the user list is retrieved by calling the doGetUserList method implemented in the JDBCUserStoreManager class[2].
- According to the analysis, the issue arises when there are two or more claim filters, as the getQueryString() method generates an incorrect SQL query tail [3].
- Therefore we need to fix[3] to form a proper SQL query to address this issue.

- As a solution, we can provide a fix like follows:
 ```
} else if (MSSQL.equals(dbType)) {
                if (isClaimFiltering && !isGroupFiltering && totalMultiClaimFilters > 1) {
                    StringBuilder subQuery = new StringBuilder(") As Q");
                    /*
                     * x is used to count the number of sub queries.
                     * (totalMultiClaimFilters * 2) --> totalMultiClaims are multiplied by 2 as 2 sub queries for
                     * every new claim.
                     * (totalMultiClaimFilters * 2) - 1 is deducted as there is 1 sub query in the SQL query.
                     */
                    for (int x = 0; x < (totalMultiClaimFilters * 2 - 1); x++) {
                        subQuery = subQuery.append(" ) AS Q");
                    }
                    // Handle multi attribute filtering without group filtering.
                    sqlBuilder.setTail(subQuery.toString()
                            .concat(" WHERE Q.RowNum BETWEEN ? AND ?"), limit, offset);
                }
```
[1]https://github.com/wso2/carbon-kernel/blob/4ebd8e135e2c1ef60878ff0818b7785abc5199c0/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L15244
[2]https://github.com/wso2/carbon-kernel/blob/4ebd8e135e2c1ef60878ff0818b7785abc5199c0/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java#L4104
[3]https://github.com/wso2/carbon-kernel/blob/4ebd8e135e2c1ef60878ff0818b7785abc5199c0/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/JDBCUserStoreManager.java#L4433

**Environment information:**
 - Product Version: IS 5.10.0
 - OS: Linux
 - Database: MSSQL 2017
 - Userstore: JDBCUserStoreManager

---

**Comment by asha15** [comment]
Closing this issue as it fixed with https://github.com/wso2/carbon-kernel/pull/3578
