### ISSUE TITLE
SCIM user request fails when an identity claim is used as a filter

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#15878]
**Describe the issue:**

When a identity claim is used as a filter in the SCIM request, it fails with a 500 error code. During the analysis, it was noted that the issue was occurring since the user is not available in the secondary user store's end. Furthermore, we managed to reproduce the same in our local environment by following the steps mentioned in the next sub section.

**How to reproduce:**

- Setup a WSO2 Identity Server (WSO2 IS) with an secondary user store (can use another WSO2 IS itself).
- Lock one of the secondary user store users so that the locked reason is set to `ADMIN_INITIATED`.
- Delete the user from the secondary user store.
- Restart the WSO2 IS.
- Try out the following SCIM users request.

```
curl --location --request GET 'https://localhost:9443/scim2/Users?domain=SECONDARY&attributes=id,userName,name.givenName,name.familyName,meta.created,emails&filter=urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:lockedReason+eq+ADMIN_INITIATED' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/json' \
--header 'count: 1' \
--header 'startIndex: 1'
```

```
{
"schemas": [
"urn:ietf:params:scim:api:messages:2.0:Error"
],
"detail": "Error occurred while retrieving SCIM user information",
"status": "500"
}
```

The following stack trace will be printed in the log.

```
[2023-05-16 10:57:49,208] [4a2c6ead-78fc-4051-b77e-afafcb4f97eb] ERROR {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Error occurred while accessing Java Security Manager Privilege Block when called by method getUsersClaimValuesWithID with 3 length of Objects and argTypes [interface java.util.List, interface java.util.List, class java.lang.String]
[2023-05-16 10:57:49,209] [4a2c6ead-78fc-4051-b77e-afafcb4f97eb] ERROR {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} - Error occurred while retrieving SCIM user information org.wso2.carbon.user.core.UserStoreException: Error occurred while accessing Java Security Manager Privilege Block when called by method getUsersClaimValuesWithID with 3 length of Objects and argTypes [interface java.util.List, interface java.util.List, class java.lang.String]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:230)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUsersClaimValuesWithID(AbstractUserStoreManager.java:15586)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getSCIMUsers(SCIMUserManager.java:3636)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getFilteredUserDetails(SCIMUserManager.java:2158)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getDetailedUsers(SCIMUserManager.java:1826)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.filterUsersBySingleAttribute(SCIMUserManager.java:1292)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.filterUsers(SCIMUserManager.java:1241)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsersWithGET(SCIMUserManager.java:509)
	at org.wso2.charon3.core.protocol.endpoints.UserResourceManager.listWithGET(UserResourceManager.java:354)
	at org.wso2.carbon.identity.scim2.provider.resources.UserResource.getUser(UserResource.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:659)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:93)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:135)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:204)
	... 69 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:207)
	... 71 more
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.user.core.util.UserCoreUtil.addDomainToName(UserCoreUtil.java:625)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addToUserNameCache(AbstractUserStoreManager.java:12384)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserNameFromCurrentUserStore(AbstractUserStoreManager.java:12355)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserNameFromUserID(AbstractUserStoreManager.java:12336)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUser(AbstractUserStoreManager.java:12191)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getDomainFreeUsersWithID(AbstractUserStoreManager.java:15702)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUsersClaimValuesWithID(AbstractUserStoreManager.java:15596)
	... 76 more
```

This issue occurs since the user exists in the `IDN_IDENTITY_USER_DATA` but not in the user store hence to resolve the issue, the user has to check the above table and delete the records accordingly. Furthermore, the records in the `UM_UUID_DOMAIN_MAPPER` should also be deleted and the user should wait until the cache clears.

**Expected behavior:**

Ideally, we should ignore these kinds of records and proceed with the request and provide a response. However, this flow will require additional analysis to check the best method to resolve the issue and to check whether it breaks in other locations.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0
 - OS: Ubuntu 20.04.3 LTS
 - Database: H2
 - Userstore: LDAP,

---

**Comment by jcgarciaa** [comment]
After the fix SCIM2 user request still fails with `NullPointerException`s when an identity claim is used as a filter:
```
ERROR {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} - Error occurred while retrieving SCIM user information 
org.wso2.carbon.user.core.UserStoreException: Error occurred while accessing Java Security Manager Privilege Block when called by method getRoleListOfUsersWithID with 1 length of Objects and argTypes [interface java.util.List]
   at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:230)
   at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getRoleListOfUsersWithID(AbstractUserStoreManager.java:15781)
   at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getSCIMUsers(SCIMUserManager.java:3666)
   at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getFilteredUserDetails(SCIMUserManager.java:2160)
   at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getDetailedUsers(SCIMUserManager.java:1828)
   at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.filterUsersBySingleAttribute(SCIMUserManager.java:1294)
   at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.filterUsers(SCIMUserManager.java:1243)
   at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsersWithGET(SCIMUserManager.java:511)
   at org.wso2.charon3.core.protocol.endpoints.UserResourceManager.listWithGET(UserResourceManager.java:354)
   at org.wso2.carbon.identity.scim2.provider.resources.UserResource.getUser(UserResource.java:215)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
   at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
   at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
   at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
   at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
   at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
   at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
   at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
   at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
   at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
   at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
   at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
   at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
   at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
   at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
   at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
   at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
   at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
   at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
   at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:129)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:596)
   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
   at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:107)
   at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:93)
   at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:109)
   at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:140)
   at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101)
   at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
   at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
   at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
   at org.wso2.carbon.extension.identity.x509Certificate.valve.X509CertificateAuthenticationValve.invoke(X509CertificateAuthenticationValve.java:59)
   at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
   at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
   at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
   at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
   at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
   at java.security.AccessController.doPrivileged(Native Method)
   at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:204)
   ... 70 more
Caused by: java.lang.reflect.InvocationTargetException
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
   at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:207)
   ... 72 more
Caused by: java.lang.NullPointerException
   at org.wso2.carbon.user.core.hybrid.HybridRoleManager.lambda$getHybridRoleListOfUsers$0(HybridRoleManager.java:639)
   at java.util.ArrayList.forEach(ArrayList.java:1259)
   at org.wso2.carbon.user.core.hybrid.HybridRoleManager.getHybridRoleListOfUsers(HybridRoleManager.java:638)
   at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetInternalRoleListOfUsersWithID(AbstractUserStoreManager.java:1087)
   at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetRoleListOfUsersWithID(AbstractUserStoreManager.java:15830)
   at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getRoleListOfUsersWithID(AbstractUserStoreManager.java:15793)
   ... 77 more
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
