### ISSUE TITLE
Authentication exception: remote certificate is invalid

### ISSUE THREAD

**Issue by Simkiw** [wso2/product-is#15995]
**Describe the issue:**
AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot   
This is what happens when I try to reach wso2 identity server.  
I took a look at [the official docs](https://is.docs.wso2.com/en/5.9.0/learn/logging-in-to-a-.net-application-using-the-identity-server/) in regards of .net app. But it only shows how to use OIDC which is not the issue.  
As far as i understood, my .net app wouldn't trust the certificate wso2 is using.  

Perhaps I may wanna take a look at how I can make wso2 use my dev certificate.

**How to reproduce:**
I'm using a .net app that represents the service provider which I register in wso2 identy server.  

**Expected behavior:**
When I initiate the authentication process, I expect to be redirected to wso2 login page where I type in user credentials and end up with a token which grants me access to my api (no authorization yet)

**Environment information**
 - Product Version: IS 6.1.0
 - OS:  Windows

**Comment by Simkiw** [comment]
Another thing, I can't use http. I get an error for wso2 server : **Provided Callback URL does not match with the registered one.**  

Any hint on what I can do to try wso2 without the java sample apps?  
Also, would that be challenging to use wso2 in an environment different than java? Say .net, or go?  
The documentation is rich, though, it also requires to use in-house samples. Which explains my question.

**Comment by Simkiw** [comment]
Hi again,  

It seems that somehow, it did accept my new certificate (after I created a keystore based on my certificate using the existing name ""wso2carbon.jks").  

But, it only works for localhost/carbon, if i try access /console, I get an error
`ERROR {org.wso2.carbon.identity.application.authentication.endpoint.util.AuthenticationEndpointUtil} - Sending GET request to URL : https://localhost:9443/api/identity/auth/v1.1/data/AuthRequestKey/2222b887-dc1b-46f8-b98a-794cdef17a57, failed. javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)  ...`

But let's put this aside for a moment, hmmm, i try to make my app connect before wso2. I used the well-known document, got my client creds while registering the app to wso2 carbon server.  
=> Still, it won't work. Depending on the callback i type in, i get :
- either page not found 404 error
- or the callback doesn't match the one being registered

I still don't get it. What am i doing wrong?

**Comment by Simkiw** [comment]
Hi,  

Everything is related to the certificate.  I just downloaded and trusted theirs for testing purposes.  
I'm not sure where it failed when i tried to use my own certificate.
