### ISSUE TITLE
Intermittent Error when Workflow Association Task Created with Bulk User Import.

### ISSUE THREAD

**Issue by vinumaddumage** [wso2/product-is#16067]
**Describe the issue:**
When user addition workflow association applied on a bulk user import the following error is observed intermittently.

```
ERROR {org.apache.ode.bpel.engine.BpelEngineImpl} - Scheduled job failed; jobDetail=JobDetails( instanceId: null mexId: hqejbhcnphridqttgpfhmg processId: {http://bpel.mgt.workflow.carbon.wso2.org/approvalProcess}Test-1 type: INVOKE_INTERNAL channel: null correlatorId: null correlationKeySet: null retryCount: null inMem: false detailsExt: {enqueue=false}) java.lang.NullPointerException

	at org.wso2.carbon.bpel.b4p.extension.PeopleActivity.init(PeopleActivity.java:375)
	at org.wso2.carbon.bpel.b4p.extension.PeopleActivity.<init>(PeopleActivity.java:110)
	at org.wso2.carbon.bpel.b4p.extension.BPEL4PeopleExtensionOperation.runAsync(BPEL4PeopleExtensionOperation.java:65)
	at org.apache.ode.bpel.runtime.extension.AbstractLongRunningExtensionOperation.run(AbstractLongRunningExtensionOperation.java:95)
	at jdk.internal.reflect.GeneratedMethodAccessor155.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ode.jacob.vpu.JacobVPU$JacobThreadImpl.run(JacobVPU.java:451)
	at org.apache.ode.jacob.vpu.JacobVPU.execute(JacobVPU.java:139)
	at org.apache.ode.bpel.engine.BpelRuntimeContextImpl.execute(BpelRuntimeContextImpl.java:1002)
	at org.apache.ode.bpel.engine.PartnerLinkMyRoleImpl.invokeNewInstance(PartnerLinkMyRoleImpl.java:208)
	at org.apache.ode.bpel.engine.BpelProcess$1.invoke(BpelProcess.java:283)
	at org.apache.ode.bpel.engine.BpelProcess.invokeProcess(BpelProcess.java:224)
	at org.apache.ode.bpel.engine.BpelProcess.invokeProcess(BpelProcess.java:279)
	at org.apache.ode.bpel.engine.BpelProcess.handleJobDetails(BpelProcess.java:434)
	at org.apache.ode.bpel.engine.BpelEngineImpl.onScheduledJob(BpelEngineImpl.java:558)
	at org.apache.ode.bpel.engine.BpelServerImpl.onScheduledJob(BpelServerImpl.java:467)
	at org.apache.ode.scheduler.simple.SimpleScheduler$RunJob$1.call(SimpleScheduler.java:687)
	at org.apache.ode.scheduler.simple.SimpleScheduler$RunJob$1.call(SimpleScheduler.java:681)
	at org.apache.ode.scheduler.simple.SimpleScheduler.execTransaction(SimpleScheduler.java:319)
	at org.apache.ode.scheduler.simple.SimpleScheduler.execTransaction(SimpleScheduler.java:274)
	at org.apache.ode.scheduler.simple.SimpleScheduler$RunJob.call(SimpleScheduler.java:681)
	at org.apache.ode.scheduler.simple.SimpleScheduler$RunJob.call(SimpleScheduler.java:665)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
**How to reproduce:**

1. [Enable](https://is.docs.wso2.com/en/latest/guides/identity-lifecycles/bulk-import-users/#:~:text=%5Buser_store.properties%5D%0Ais_bulk_import_supported%20%20%3D%20%20true) bulk user import.
2. Create a Workflow Definition (`Home`>`Manage`>`Workflow Definitions`>`Add`).
3. Create a Workflow Engagement for `Add User` operation using the Workflow Definition created in Step 2 (`Home`>`Manage`>`Workflow Engagements`>`Add`).
4. Import bulk user CSV file([userBulk.csv](https://github.com/wso2/product-is/files/11768111/userBulk.csv)) to apply workflow on each user created (`Home`>`Identity`>`Users and Roles`>`Add`>`Bulk Import Users`).

**Expected behavior:**
All users created with workflow tasks without error log in server.

**Environment information:**
 - Product Version: WSO2 Identity Server-6.2.0-m5-SNAPSHOT
 - OS: Mac
 - Database: H2
 - Userstore: JDBC
---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
