### ISSUE TITLE
Refresh token revocation responds with 500 when oauth token revocation publisher is enabled

### ISSUE THREAD

**Issue by isurusamarasekara** [wso2/product-is#16061]
**Describe the issue:**
When invoking a refresh token revocation while oauth token revocation publisher is enabled, an NPE would be thrown. The token is revoked properly, but due to the exception the API response will be 500 Internal Server Error.

The error occurs from [2] class. When a refresh token is being revoked the accessTokenDO object would be null and the line [3] will throw a NPE. This line can be removed.

Additionally, when an access token is being revoked, there is a duplicated line [4] and [5]. If the "if condition" fails for [4] then an NPE would be thrown for [5]. Hence [5] should be removed as well.

[1] 
```
[2023-06-15 20:19:29,387] [108b53f0-74a0-41d5-bc98-132ec4d9d5f5] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/oauth2].[OAuth2Endpoints]} - Servlet.service() for servlet [OAuth2Endpoints] in context with path [/oauth2] threw exception java.lang.NullPointerException
	at org.wso2.carbon.identity.data.publisher.oauth.listener.OAuthTokenRevocationDASPublisher.onPostTokenRevocationByClient(OAuthTokenRevocationDASPublisher.java:72)
	at org.wso2.carbon.identity.data.publisher.oauth.OAuthInterceptorHandlerProxy.onPostTokenRevocationByClient(OAuthInterceptorHandlerProxy.java:141)
	at org.wso2.carbon.identity.oauth2.OAuth2Service.invokePostRevocationListeners(OAuth2Service.java:503)
	at org.wso2.carbon.identity.oauth2.OAuth2Service.revokeTokenByOAuthClient(OAuth2Service.java:460)
	at org.wso2.carbon.identity.oauth.endpoint.revoke.OAuthRevocationEndpoint.revokeTokens(OAuthRevocationEndpoint.java:304)
	at org.wso2.carbon.identity.oauth.endpoint.revoke.OAuthRevocationEndpoint.revokeAccessToken(OAuthRevocationEndpoint.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.wso2.carbon.webapp.mgt.filter.AuthorizationHeaderFilter.doFilter(AuthorizationHeaderFilter.java:128)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:111)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:101)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:59)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:124)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```
[2] https://github.com/wso2-extensions/identity-data-publisher-oauth/blob/1.3.x/components/org.wso2.carbon.identity.data.publisher.oauth/src/main/java/org/wso2/carbon/identity/data/publisher/oauth/listener/OAuthTokenRevocationDASPublisher.java
[3] https://github.com/wso2-extensions/identity-data-publisher-oauth/blob/fbfe61a9f3ba1a00184bd19328823b2780633041/components/org.wso2.carbon.identity.data.publisher.oauth/src/main/java/org/wso2/carbon/identity/data/publisher/oauth/listener/OAuthTokenRevocationDASPublisher.java#L72
[4] https://github.com/wso2-extensions/identity-data-publisher-oauth/blob/fbfe61a9f3ba1a00184bd19328823b2780633041/components/org.wso2.carbon.identity.data.publisher.oauth/src/main/java/org/wso2/carbon/identity/data/publisher/oauth/listener/OAuthTokenRevocationDASPublisher.java#L82
[5] https://github.com/wso2-extensions/identity-data-publisher-oauth/blob/fbfe61a9f3ba1a00184bd19328823b2780633041/components/org.wso2.carbon.identity.data.publisher.oauth/src/main/java/org/wso2/carbon/identity/data/publisher/oauth/listener/OAuthTokenRevocationDASPublisher.java#L84

**How to reproduce:**
1. Stop the server and add the following configuration to deployment.toml

```
[[event_listener]]
id = "oauth_data_publisher_token_revocation"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.carbon.identity.data.publisher.oauth.listener.OAuthTokenRevocationDASPublisher"
order = 15
```
2. Obtain a refresh token,
```
curl --location --request POST 'https://localhost:9443/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic ODdhQ1lZWUVMNU4yeWRaMjZQM290b2V3eFQ4YTo3SzI5QjJDYWIxUmZ2OWpHcUg0aW5SczBhUklh' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'username=user1' \
--data-urlencode 'password=user1' \
--data-urlencode 'scope=openid'
```
3. Start the server and invoke token revocation for a refresh token,
```
curl --location --request POST 'https://wso2is10.com:9443/oauth2/revoke' \
--header 'Content-Type: application/x-www-form-urlencoded;charset=UTF-8' \
--header 'Authorization: Basic ODdhQ1lZWUVMNU4yeWRaMjZQM290b2V3eFQ4YTo3SzI5QjJDYWIxUmZ2OWpHcUg0aW5SczBhUklh' \
--data-raw 'token=fff40be5-1a35-357c-b3a3-0fb5c238ad43&token_type_hint=refresh_token'
```
5. An NPE error stack will be seen along with 500 response code for proper API invocation.

**Expected behavior:**
No NPE exception and 200 response code for proper token revocation API invocation.

**Environment information** **:**
 - Product Version: IS 5.10.0 update-level 232 (current latest)
 - OS: Mac
 - Database: MySQL
 - Userstore: JDBC

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
