### ISSUE TITLE
Identifier First + Email OTP flow is not working 

### ISSUE THREAD

**Issue by sandushi** [wso2/product-is#16279]
**Describe the issue:**
- If we configure IDF as the 2st step and Email OTP as 2nd factor, the flow is not working as expected and throw and errors.

**How to reproduce:**
- Create an application.
- Configure IDF as 1st factor and Email OTP as second factor.
- Create a user.
- Flow 1 :
   - Keep IDF to pick the identifier.
   - Try to login to the app from the user by entering the username.
   - Redirect to an error page.
```
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework java.lang.NullPointerException
	at org.wso2.carbon.utils.multitenancy.MultitenantUtils.getTenantDomain(MultitenantUtils.java:90)
	at org.wso2.carbon.extension.identity.helper.FederatedAuthenticatorUtil.isUserExistInUserStore(FederatedAuthenticatorUtil.java:116)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.publishPostEmailOTPGeneratedEvent(EmailOTPAuthenticator.java:2571)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.process(EmailOTPAuthenticator.java:139)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:688)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:419)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handleAuthenticationStep(GraphBasedSequenceHandler.java:506)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handleNode(GraphBasedSequenceHandler.java:202)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:152)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:198)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:346)
	at org.wso2.carbon.identity.application.authentication.framework.CommonAuthenticationHandler.doPost(CommonAuthenticationHandler.java:57)
	at org.wso2.carbon.identity.application.authentication.framework.CommonAuthenticationHandler.doGet(CommonAuthenticationHandler.java:46)
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:54)

```

- Flow 2 : 
   - Keep email otp to pick the identifier.
   - Try to login to the app from the user by entering the username
   - Throw an error.
   
```
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! Authentication failed. Cannot find the subject attributed step with authenticated user.
```

[Untitled_ Jul 19 2023 5_13 PM.webm](https://github.com/wso2/product-is/assets/36092400/4e235d5e-4d79-4e57-9428-9f4736cba8f5)

- In both flows, not redirected to the second step.

**Expected behavior:**
Should able to login without any error.

**Analysis**

- Debugged the flow and identified that the issue due to trying to get the authenticated user from the second step, even the second step is not executed.

https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/699f1b28792d9ff5767175bc5ca153c51324473b/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L243

**Comment by sandushi** [comment]
The explained first flow is working as expected with latest changes. 

[Untitled_ Jul 20, 2023 11_42 AM.webm](https://github.com/wso2/product-is/assets/36092400/b1214008-4344-468a-ac93-f08de2964711)

**Comment by melanisilva** [comment]
Closing this as this is fixed.
