### ISSUE TITLE
Configuring Yammer as the Federated Authenticator

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#1633]
### Steps to Re-create

1. Place the authenticator .jar file is placed in <IS_HOME>/repository/components/dropins directory and restart the IS. 
[download location](https://store.wso2.com/store/assets/isconnector/details/0e1f0ba7-c4dc-4826-afa7-ba3adef00e7b)

**Expected:** IS should be successfully started and Yammer authenticator should be found under federated authenticators is Idp creation. 

**Actual:** Following error is printed in server startup. Cannot be found the Yammer authenticator under federated authenticators. 

`java.lang.NoClassDefFoundError: org/wso2/carbon/identity/authenticator/YammerOAuth2Authenticator

	at org.wso2.carbon.identity.authenticator.internal.YammerAuthenticatorServiceComponent.activate(YammerAuthenticatorServiceComponent.java:39)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)

	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)

	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)

	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)

	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)

	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)

	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)

	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)

	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)

	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)

	at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.identity.authenticator.YammerOAuth2Authenticator cannot be found by org.wso2.carbon.identity.authenticator.yammer_1.0.0

	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:455)

	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)

	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)

	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

`

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
