### ISSUE TITLE
Iterating through all userstores when the domain is already known

### ISSUE THREAD

**Issue by isurusamarasekara** [wso2/product-is#16401]
The issue fixed in [1] can be found at [2]. But when a scim2/Me patch request is invoked on an already authenticated user (using the bearer token), the flow will go through [3] scim2 to [4] which is just before the fix implemented [2]. This will move to [5] and since the user id vs domain mapping is not added to the cache (unique_id_domain_cache_manager) or the domain mapper (UM_UUID_DOMAIN_MAPPER) table at the authentication point, the flow will start iterating through the userstores to find the domain of the user again, which will result in [6] error stack if the userstore in the chain is not accessible.

This would only happen once for a given user when the table is not populated, but since we would have already found the domain when the user is authenticated prior, iterating all the user stores to find the user again is wasting resources and is not optimal, (This issue is related to [7] as well).

Shall we populate this cache and the table as soon as we find the mapping during authentication or any other flow ?

**Reproduction steps:**
1. plug 2 or more non-unique id userstores (one with incorrect connection password),
2. invoke ROPG with domain specified in the username and obtain a token,
3. invoke scim2/Me patch to update password of the user with the bearer authentication,
4. you would observe the [6] error stack.

[1] https://github.com/wso2/product-is/issues/15203
[2] https://github.com/wso2/carbon-kernel/blob/b06d95f153f50a6967a935dbe09025da622215dc/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L12141-L12147
[3] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/cd07bee5a695518f15c7a8b8fd4dfadcad3cf6bf/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L3861
[4] https://github.com/wso2/carbon-kernel/blob/b06d95f153f50a6967a935dbe09025da622215dc/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L12129
[5] https://github.com/wso2/carbon-kernel/blob/b06d95f153f50a6967a935dbe09025da622215dc/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L7616
[6] 
```
TID: [-1234] [scim2] [2023-08-04 19:28:30,439] [f7d637f0-e132-4755-975b-9a8b0548c36e] ERROR {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Unable retrieve users from getUserListFromProperties method from the user store: JDBC31. Therefore,proceeding remaining domains org.wso2.carbon.user.core.UserStoreException: Database error occurred while listing users for a property : scimId & value : f8b092a9-dd21-430d-a3b6-e853797dcc60 & profile name : default
    at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.getUserListFromProperties(JDBCUserStoreManager.java:3055)
    at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserStoreInternalWithId(AbstractUserStoreManager.java:7056)
    at org.wso2.carbon.user.core.common.AbstractUserStoreManager.lambda$getUserStoreWithID$11(AbstractUserStoreManager.java:6936)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserStoreWithID(AbstractUserStoreManager.java:6936)
    at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValuesWithID(AbstractUserStoreManager.java:11326)
    at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:198)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:195)
    at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValuesWithID(AbstractUserStoreManager.java:11321)
    at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getSCIMUser(SCIMUserManager.java:3574)
    at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getMe(SCIMUserManager.java:2335)
    at org.wso2.charon3.core.protocol.endpoints.MeResourceManager.updateWithPATCH(MeResourceManager.java:309)
    at org.wso2.carbon.identity.scim2.provider.resources.MeResource.patchUser(MeResource.java:256)
```
[7] https://github.com/wso2/product-is/issues/15081

Product: wso2is-5.10.0
Update level: 191 ([1] issue was fixed at), 193, 240 latest

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
