### ISSUE TITLE
Facing CORS Issue after migrating wso25.10.0 to 6.1.0 

### ISSUE THREAD

**Issue by Surajmahapatra94** [wso2/product-is#16441]
**Describe the issue:**
Getting **org.wso2.carbon.identity.cors.mgt.core.exception.CORSManagementServiceServerException: CMS-65006** in wso2 after migrating from 5.10.0v to 6.1.0v. PostgreSQL Db is being used with WSO2.

**How to reproduce:**

- Deploy WSO2 v6.1.0 with the same PostgreSQL DB scripts as that of v5.10,0 . 
- Start the WSO2 IS docker service. 
- Try to access the https://wso2is:9443/carbon/ URL

**Expected behavior:**
Able to open the Carbon UI Portal with the configuration in PostgreSQL.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  IS 5.10.0, IS 6.1.0
 - OS:  Linux, Mac
 - Database:PostgreSQL
 - Userstore:  JDBC, LDAP

---

### Optional Fields

**Error**
ERROR {org.wso2.carbon.identity.cors.valve.CORSValve} - CORS management service error when intercepting an HTTP request. org.wso2.carbon.identity.cors.mgt.core.exception.CORSManagementServiceServerException: CMS-65006
         at org.wso2.carbon.identity.cors.service.internal.impl.CORSManagerImpl.getCORSConfiguration(CORSManagerImpl.java:76)
         at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:69)
         at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:167)
         at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:118)
         at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:114)
         at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
         at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:75)
         at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
         at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
         at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
         at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
         at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
         at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
         at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
         at java.base/java.lang.Thread.run(Thread.java:829)
 Caused by: org.wso2.carbon.identity.cors.mgt.core.exception.CORSManagementServiceServerException: Server encountered an error while retrieving the CORS configuration of carbon.super.
         at org.wso2.carbon.identity.cors.mgt.core.internal.util.ErrorUtils.handleServerException(ErrorUtils.java:56)
         at org.wso2.carbon.identity.cors.mgt.core.dao.impl.CORSConfigurationDAOImpl.getCORSConfigurationByTenantDomain(CORSConfigurationDAOImpl.java:76)
         at org.wso2.carbon.identity.cors.mgt.core.dao.impl.CacheBackedCORSConfigurationDAO.getCORSConfigurationByTenantDomain(CacheBackedCORSConfigurationDAO.java:66)
         at org.wso2.carbon.identity.cors.mgt.core.internal.impl.CORSManagementServiceImpl.getCORSConfiguration(CORSManagementServiceImpl.java:198)
         at org.wso2.carbon.identity.cors.service.internal.impl.CORSManagerImpl.getCORSConfiguration(CORSManagerImpl.java:73)
         ... 22 more
 Caused by: org.wso2.carbon.identity.configuration.mgt.core.exception.ConfigurationManagementClientException: Resource type with the name: CORS_CONFIGURATION does not exists.
         at org.wso2.carbon.identity.configuration.mgt.core.util.ConfigurationUtils.handleClientException(ConfigurationUtils.java:63)
         at org.wso2.carbon.identity.configuration.mgt.core.ConfigurationManagerImpl.getResourceType(ConfigurationManagerImpl.java:289)
         at org.wso2.carbon.identity.configuration.mgt.core.ConfigurationManagerImpl.getResource(ConfigurationManagerImpl.java:189)
         at org.wso2.carbon.identity.cors.mgt.core.dao.impl.CORSConfigurationDAOImpl.getResource(CORSConfigurationDAOImpl.java:123)
         at org.wso2.carbon.identity.cors.mgt.core.dao.impl.CORSConfigurationDAOImpl.getCORSConfigurationByTenantDomain(CORSConfigurationDAOImpl.java:67)
         ... 25 more

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
