### ISSUE TITLE
Error when starting the server with AWS Cognito Authenticator

### ISSUE THREAD

**Issue by asha15** [wso2/product-is#16457]
**Describe the issue:**
Observed these error logs when starting the server with AWS Cognito Authenticator connector.

```
[2023-08-15 15:34:31,919] [] ERROR {Events.Framework} - FrameworkEvent ERROR org.osgi.framework.BundleException: Could not resolve module: org.wso2.carbon.identity.application.authenticator.cognito [258]
  Unresolved requirement: Import-Package: org.wso2.carbon.extension.identity.helper.util; version="[1.0.10,2.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:457)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

```

**How to reproduce:**
Follow the steps in the [documentation](https://github.com/wso2-extensions/identity-outbound-auth-cognito/tree/master/docs).

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.1.0, IS 6.0.0
 - OS: Linux
 - Connector version:  1.0.4 
 - Database: H2

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by jithma95** [comment]
Hi Team,

Is there any update on this?

Thanks

**Comment by dhaura** [comment]
### Analysis

> Tested IS startup (including AWS Cognito Connector) for the following  setups.

#### Setup 1
- IS Version: `6.1.0`
- AWS Cognito Connector Version: `1.0.4` (latest connector from the store)
- Results: `Issue Reproducible`

#### Setup 2
- IS Version: `6.1.0`
- AWS Cognito Connector Version: `1.0.6` (built from repo)
- Results: `Issue Reproducible`

#### Setup 3
- IS Version: `6.1.0`
- AWS Cognito Connector Version: `1.0.7-SNAPSHOT` (built from repo)
- Results: `Issue Reproducible`

#### Setup 4
- IS Version: `6.2.0 alpha 5 SNAPSHOT`
- AWS Cognito Connector Version: `1.0.4` (latest connector from the store)
- Results: `Error occurs but not the one mentioned in this git issue` (But we can see the AWS Cognito form when creating a new IDP.)
```
[2023-08-21 13:27:46,015] [] ERROR {org.wso2.carbon.identity.application.authenticator.cognito} - [SCR] Found components with duplicated names inside their bundle! This component will not be processed: Component[
	name = identity.application.authenticator.cognito.component
	activate = activate
	deactivate = deactivate
	modified =
	configuration-policy = optional
	factory = null
	autoenable = true
	immediate = true
	implementation = org.wso2.carbon.identity.application.authenticator.cognito.internal.CognitoOpenIDConnectAuthenticatorServiceComponent
	state = Unsatisfied
	properties =
	serviceFactory = false
	serviceInterface = null
	references = null
	located in bundle = org.wso2.carbon.identity.application.authenticator.cognito_1.0.4 [270]
]
```

#### Setup 5
- IS Version: `6.2.0 alpha 5 SNAPSHOT`
- AWS Cognito Connector Version: `1.0.6` (built from repo)
- Results: `No Error. Issue not Reproducible`

#### Setup 6
- IS Version: `6.2.0 alpha 5 SNAPSHOT`
- AWS Cognito Connector Version: `1.0.7-SNAPSHOT` (built from repo)
- Results: `No Error. Issue not Reproducible`
