### ISSUE TITLE
Temp claims set from adaptive script gets saved in db

### ISSUE THREAD

**Issue by dhaura** [wso2/product-is#16476]
**Describe the issue:**

The following error log was observed while attempting to log in to a SP with JIT provisioning enabled.
```
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler} - User provisioning failed! org.wso2.carbon.identity.application.authentication.framework.exception.FrameworkException: Error while provisioning user : 696e771e-4cde-4b45-b916-24970e7e38f2|at org.wso2.carbon.identity.application.authentication.framework.handler.provisioning.impl.DefaultProvisioningHandler.handle(DefaultProvisioningHandler.java:339) ~[org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.handler.provisioning.impl.DefaultProvisioningHandler.handle(DefaultProvisioningHandler.java:101) ~[org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handleJitProvisioning(DefaultStepBasedSequenceHandler.java:620) [org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.callJitProvisioning(DefaultStepBasedSequenceHandler.java:573) [org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.JITProvisioningPostAuthenticationHandler.callDefaultProvisioningHandler(JITProvisioningPostAuthenticationHandler.java:889) [org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.JITProvisioningPostAuthenticationHandler.handleRequestFlow(JITProvisioningPostAuthenticationHandler.java:427) [org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.JITProvisioningPostAuthenticationHandler.handle(JITProvisioningPostAuthenticationHandler.java:161) [org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.services.PostAuthenticationMgtService.executePostAuthnHandler(PostAuthenticationMgtService.java:117) [org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.services.PostAuthenticationMgtService.handlePostAuthentication(PostAuthenticationMgtService.java:83) [org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handlePostAuthentication(DefaultAuthenticationRequestHandler.java:257) [org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:215) [org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:345) [org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.CommonAuthenticationHandler.doPost(CommonAuthenticationHandler.java:57) [org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.CommonAuthenticationHandler.doGet(CommonAuthenticationHandler.java:46) [org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doGet(CommonAuthenticationServlet.java:48) [org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) [tomcat-servlet-api_9.0.58.wso2v1.jar:?]|	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [tomcat-servlet-api_9.0.58.wso2v1.jar:?]|	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) [org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]|	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]|	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]|	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]|	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [tomcat-servlet-api_9.0.58.wso2v1.jar:?]|	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) [org.wso2.carbon.tomcat.ext_4.9.10.jar:?]|	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat_9.0.58.wso2v1.jar:?]|	at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:99) [org.wso2.carbon.identity.captcha_1.8.50.jar:?]|	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:385) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313) [tomcat_9.0.58.wso2v1.jar:?]|	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:161) [org.wso2.carbon.identity.context.rewrite.valve_1.8.20.jar:?]|	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:115) [org.wso2.carbon.identity.context.rewrite.valve_1.8.20.jar:?]|	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38) [org.wso2.carbon.tomcat.ext_4.9.10.jar:?]|	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83) [org.wso2.carbon.identity.cors.valve_1.8.20.jar:?]|	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:185) [org.wso2.carbon.identity.authz.valve_1.8.20.jar:?]|	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:120) [org.wso2.carbon.identity.auth.valve_1.8.20.jar:?]|	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110) [org.wso2.carbon.tomcat.ext_4.9.10.jar:?]|	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.9.10.jar:?]|	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71) [org.wso2.carbon.tomcat.ext_4.9.10.jar:?]|	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152) [org.wso2.carbon.tomcat.ext_4.9.10.jar:?]|	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [tomcat_9.0.58.wso2v1.jar:?]|	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63) [org.wso2.carbon.tomcat.ext_4.9.10.jar:?]|	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49) [org.wso2.carbon.tomcat.ext_4.9.10.jar:?]|	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137) [org.wso2.carbon.tomcat.ext_4.9.10.jar:?]|	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat_9.0.58.wso2v1.jar:?]|	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.58.wso2v1.jar:?]|	at java.lang.Thread.run(Thread.java:829) [?:?]|Caused by: org.wso2.carbon.user.core.UserStoreException: 30005 - Claim URI is invalid, http://wso2.org/claims/entitlements|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:258) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4762) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4748) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.handler.provisioning.impl.DefaultProvisioningHandler.handle(DefaultProvisioningHandler.java:243) ~[org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	... 59 more|Caused by: java.security.PrivilegedActionException|	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:239) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4762) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4748) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.handler.provisioning.impl.DefaultProvisioningHandler.handle(DefaultProvisioningHandler.java:243) ~[org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	... 59 more|Caused by: java.lang.reflect.InvocationTargetException|	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]|	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]|	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]|	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:242) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:239) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4762) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4748) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.handler.provisioning.impl.DefaultProvisioningHandler.handle(DefaultProvisioningHandler.java:243) ~[org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	... 59 more|Caused by: org.wso2.carbon.user.core.UserStoreException: 30005 - Claim URI is invalid, http://wso2.org/claims/entitlements|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:5030) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]|	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]|	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]|	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:242) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:239) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4762) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4748) ~[org.wso2.carbon.user.core_4.9.10.jar:?]|	at org.wso2.carbon.identity.application.authentication.framework.handler.provisioning.impl.DefaultProvisioningHandler.handle(DefaultProvisioningHandler.java:243) ~[org.wso2.carbon.identity.application.authentication.framework_5.25.265.jar:?]|	... 59 more|
```

This occurs when trying to persist the following claim value:
```
"http://wso2.org/claims/entitlements"":""A*********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************R"
```

This claim is set as a temporary claim from the adaptive script.

```
var claimMap = {};
claimMap[EMAIL_CLAIM] = "DEFAULT/" + email;
mappedUser = getUniqueUserWithClaimValues(claimMap, contextGl);
mappedUser.claims["http://wso2.org/claims/entitlements"] = entitlements;
```

From the docs: https://is.docs.wso2.com/en/latest/references/adaptive-authentication-js-api-reference/ : `user.claims[“<local_claim_url>”]`: (Read/Write) Sets a temporary claim value for the session.

- Persisting temp claim in db is wrong.

- Please note that the IDP which is involved in this flow has JIT provisioning enabled and no error is experienced by the end user who is trying out this flow..

**How to reproduce:**

- Obtaining IS local pack.
- Create an IDP (Google) with the JIT provisioning enabled.
- Create an application and add the IDP (Google) as sign-in options.
- Configure adaptive script by setting up the temp claim as follows:
```
var claimMap = {};
claimMap[EMAIL_CLAIM] = "DEFAULT/" + email;
mappedUser = getUniqueUserWithClaimValues(claimMap, contextGl);
mappedUser.claims["http://wso2.org/claims/entitlements"] = entitlements;
```
- Try to log into the configured application and observe the logs.

**Expected behavior:**
> Temp claim shouldn't update the claims in the database but should be available throughout the session.

**Environment information**
 - Product Version:
 - OS:  `macOS Ventura 13.5`
 - Database: `Default`
 - Userstore: `Default`

**Comment by dhaura** [comment]
**Debugged Code Base** - https://github.com/wso2/carbon-identity-framework
**Detailed Analysis** - https://docs.google.com/document/d/1jwOOjTeNv29mwYpFq9lLKh5ycWPhW69FfDVVw8c57Jw

In the authentication request, all the `Runtime Claims` [aka temp claims] are being added to `localUnfilteredClaims` in order to be used within the session [1]. Then these claims are straightly passed into the function that handles JIT provisioning. This in turn calls `AbstractUserStoreManager` [2] to add a new user [3] with the given set of claims. Since the given set of claims contains the runtime claims (temp claims), it tries to persist those temp claims in the db as well.

So, if the claim is not available in the DB, it throws an error and if the claim is in the db, it updates the claim value with the temp one.

*Solution* - We have to remove runtime claims from local claims before calling the method to handle JIT provisioning [4].

[1] - [https://github.com/wso2/carbon-identity-framework/blob/e47759707f473e08a8aa093a3b9997e7cb4e00f5/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/claims/impl/DefaultClaimHandler.java#L216](https://www.google.com/url?q=https://github.com/wso2/carbon-identity-framework/blob/e47759707f473e08a8aa093a3b9997e7cb4e00f5/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/claims/impl/DefaultClaimHandler.java%23L216&sa=D&source=docs&ust=1692161367457234&usg=AOvVaw0DJ1d3dxNrcAhvBlPiIqIv)
[2] - [https://github.com/wso2/carbon-kernel/blob/4.9.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java](https://www.google.com/url?q=https://github.com/wso2/carbon-kernel/blob/4.9.x/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java&sa=D&source=docs&ust=1692161367453721&usg=AOvVaw1rKSdCc5UFHg9fdXd9JTNg)
[3] - [https://github.com/wso2/carbon-identity-framework/blob/e47759707f473e08a8aa093a3b9997e7cb4e00f5/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/provisioning/impl/DefaultProvisioningHandler.java#L243](https://www.google.com/url?q=https://github.com/wso2/carbon-identity-framework/blob/e47759707f473e08a8aa093a3b9997e7cb4e00f5/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/provisioning/impl/DefaultProvisioningHandler.java%23L243&sa=D&source=docs&ust=1692161367455473&usg=AOvVaw2gP2HQjRIcyIPcGiBfqEZ2)
[4] - https://github.com/wso2/carbon-identity-framework/blob/e47759707f473e08a8aa093a3b9997e7cb4e00f5/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/JITProvisioningPostAuthenticationHandler.java#L888

**Comment by dhaura** [comment]
- **Problem Revised** - For a local authenticator, when temp claims are set, they do not get updated in the database but for a federated authenticator, when temp claims are set, they get updated in the database. (In both cases, throughout the session, updated temp claims can be seen which is the expected behaviour.)
- The root cause for this is, as mentioned above, all the `Runtime Claims` [aka temp claims] are being added to `localUnfilteredClaims` in order to be used within the session [1]. Therefore, when the user is added or updated with JIT provisioning, the database is updated with temp claims as well.
- We were able to come with a fix for this as follows.
  - Before calling JIT provisioning handler, check if any IDP remote claims were changed by the temp claims.
  - If so, revert them back to original values that came from the IDP.
  - If not, then remove the temp claim from local claims.

[1] - [https://github.com/wso2/carbon-identity-framework/blob/e47759707f473e08a8aa093a3b9997e7cb4e00f5/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/claims/impl/DefaultClaimHandler.java#L216](https://www.google.com/url?q=https://github.com/wso2/carbon-identity-framework/blob/e47759707f473e08a8aa093a3b9997e7cb4e00f5/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/claims/impl/DefaultClaimHandler.java%23L216&sa=D&source=docs&ust=1692161367457234&usg=AOvVaw0DJ1d3dxNrcAhvBlPiIqIv)
