### ISSUE TITLE
Getting error when trying to get token from refresh token (When using Email OTP authenticator)

### ISSUE THREAD

**Issue by SujanSanjula96** [wso2/product-is#16478]
**Describe the issue:**
When user from a different tenant from the application tenant domain tries to log into a SaaS app which uses Email OTP authenticator (as first factor or last factor), it logs in successfully. But when the token expires and try to get the token from refresh grant, giving 500 response with the following error.

```
[2023-08-18 07:58:33,250] [0fe75261-7b1b-4c28-beea-c18a769edc38] ERROR {org.wso2.carbon.identity.oauth2.OAuth2Service} - Error occurred while issuing the access token for Client ID : RlxYZr5nFydFizt9FvYEVFmfE4ka, User ID null, Scope : [] and Grant Type : refresh_token org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: User id is not available for user: sujansanjula1212@gmail.com@carbon.super
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.updateCacheIfEnabled(RefreshGrantHandler.java:351)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.persistNewToken(RefreshGrantHandler.java:336)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.issue(RefreshGrantHandler.java:118)
	at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.issue(AccessTokenIssuer.java:433)
	at org.wso2.carbon.identity.oauth2.OAuth2Service.issueAccessToken(OAuth2Service.java:412)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:350)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:163)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:141)
```

**How to reproduce:**
1. Configure email OTP.
2. Create a service provider and enable SaaS application option in super tenant. (Keep the access token expiry time to a less value)
3. Add email OTP as an authenticator. (As first factor or second factor)
4. Create another tenant and add a user to that tenant.
5. Try to login to that application and wait until access token expires

After expiring access token, token call with refresh grant fail with above error.

**Expected behavior:**
Should get the access token using refresh grant.

**Comment by SujanSanjula96** [comment]
The reason for this is when publishing the authentication step attempt, it set the authenticated user's tenant domain to application tenant domain for federated authenticator. Since Email OTP, SMS OTP also extended using FederatedApplicationAuthenticator class, when using them as an authentication step same thing happen.
https://github.com/wso2/carbon-identity-framework/blob/16fab4552dca2cb66c67cb47e99b83982d8f458c/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/AbstractApplicationAuthenticator.java#L276

Here username is shown as `sujansanjula1212@gmail.com@carbon.super`. But the correct one should be `sujansanjula1212@gmail.com@abc.com`

**Comment by SujanSanjula96** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/4933
