### ISSUE TITLE
Error when login using Twitter Authenticator

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-is#16689]
**Describe the issue:**
An authentication failure occurs when trying to login using the Twitter federated authenticator in the latest IS. The following backend error can be seen at the console.

```
[2023-09-18 17:13:09,908] [d2a908d1-ecad-4b59-9240-16e35a8687dd] ERROR {org.wso2.carbon.identity.authenticator.twitter.TwitterAuthenticator} - Exception while sending to the Twitter login page. 401:Authentication credentials (https://dev.twitter.com/pages/auth) were missing or incorrect. Ensure that you have set valid consumer key/secret, access token/secret, and the system clock is in sync.
message - Could not authenticate you.
code - 32

Relevant discussions can be found on the Internet at:
	http://www.google.co.jp/search?q=8e063946 or
	http://www.google.co.jp/search?q=fe607b48
TwitterException{exceptionCode=[8e063946-fe607b48], statusCode=401, message=Could not authenticate you., code=32, retryAfter=-1, rateLimitStatus=null, version=4.0.7}
	at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:170)
	at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
	at twitter4j.HttpClientBase.post(HttpClientBase.java:86)
	at twitter4j.auth.OAuthAuthorization.getOAuthRequestToken(OAuthAuthorization.java:115)
	at twitter4j.auth.OAuthAuthorization.getOAuthRequestToken(OAuthAuthorization.java:92)
	at twitter4j.TwitterBaseImpl.getOAuthRequestToken(TwitterBaseImpl.java:296)
	at org.wso2.carbon.identity.authenticator.twitter.TwitterAuthenticator.initiateAuthenticationRequest(TwitterAuthenticator.java:145)
	at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.process(AbstractApplicationAuthenticator.java:100)
```

**How to reproduce:**
1. Configure the twitter authenticator for federated login as in the docs [1].
2. Try login.

Authentication failure.

**Expected behavior:**
A user should be able to successfully login using twitter connector.

[1] https://is.docs.wso2.com/en/latest/guides/identity-federation/twitter/#set-up-a-twitter-app 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS-7.0.0-m2
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

**Comment by ImalshaG** [comment]
The above error occurred since I had used the Oauth 2.0 client ID and secret instead of the Oauth 1.0 API key and secret. 

Our docs should clearly mention what configs to use when configuring the IDP since both the above configs were available at the same page in the twitter developer portal and can be confusing for a user.

Created a doc issue to update the docs https://github.com/wso2/product-is/issues/16698
