### ISSUE TITLE
Migration Client is failing when migrating relying party URL in the registry resources to handle browser back button and bookmarked login page configurations 

### ISSUE THREAD

**Issue by ShamodyaHashantha** [wso2/product-is#16800]
**Describe the issue:**
After configuring the relying party URL in the registry resources to handle browser back button and bookmarked login page configurations [1]. Specifically, the problem arises when executing the application (SP) relying party URL migration step for a particular relying party URL in certain tenants, the migration client tries to obtain the application details (SP) for the particular relying party URL configured at the registry resources and the migration client encounters a null pointer exception, as indicated in the below stack trace

```
[```
2023-08-30 11:37:34,531] [] ERROR {org.wso2.carbon.is.migration.MigrationClientImpl} - Migration process was stopped. java.lang.NullPointerException
    at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getServiceProviderNameByClientId(ApplicationDAOImpl.java:4083)
    at org.wso2.carbon.identity.application.mgt.dao.impl.CacheBackedApplicationDAO.getServiceProviderNameByClientId(CacheBackedApplicationDAO.java:153)
    at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.getServiceProviderNameByClientId(ApplicationManagementServiceImpl.java:1074)
    at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.getServiceProviderByClientId(ApplicationManagementServiceImpl.java:1240)
    at org.wso2.carbon.is.migration.service.v600.migrator.ApplicationAccessURLMigrator.getServiceProviderByRelyingParty(ApplicationAccessURLMigrator.java:338)
    at org.wso2.carbon.is.migration.service.v600.migrator.ApplicationAccessURLMigrator.migratingRelyingPartyURL(ApplicationAccessURLMigrator.java:136)
    at org.wso2.carbon.is.migration.service.v600.migrator.ApplicationAccessURLMigrator.migrate(ApplicationAccessURLMigrator.java:204)
    at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)
    at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:76)
    at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:151)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
    at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
    at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
    at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
    at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
    at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
    at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
    at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
    at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
    at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
    at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
    at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
    at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

**How to reproduce:**

1. Set up browser back button/bookmarked login configurations in 5.11.0 
2. Setup databases (SQL) accordingly and copy the relevant migration documents to the  target version (6.0.0)
3. Start the migration 

[https://is.docs.wso2.com/en/5.11.0/develop/customizing-the-authentication-endpoint/#handling-browser-back-button-and-bookmarked-login-page](https://is.docs.wso2.com/en/5.11.0/develop/customizing-the-authentication-endpoint/#handling-browser-back-button-and-bookmarked-login-page)

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.11.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL]
 - Userstore: [e.g., LDAP, JDBC]
---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
