### ISSUE TITLE
Handle error gracefully in Scim2 patch op with large claim value

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#16856]
Description:

The following error was observed when a Scim2 patch op with large claim value is executed. Large claim values result in 500 error.

```
TID: [334] Tenant: [abbstage] [2023-09-15 08:37:17,259] [20230915T083716Z-pr0kys8q5d70p60d3f0m8w2nqg00000002v000000001xepr] : iam-cloud-carbon : ERROR {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} - Error while updating attributes of user: DEFAULT/cmfess_testing@ch.abb.com org.wso2.carbon.user.core.UserStoreException: Error occurred while updating string values to database.
 at org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager.updateProperties(UniqueIDJDBCUserStoreManager.java:2854) ~[org.wso2.carbon.user.core_4.9.12.jar:?]
 at org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager.doSetUserAttributesWithID(UniqueIDJDBCUserStoreManager.java:1892) ~[org.wso2.carbon.user.core_4.9.12.jar:?]
 at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doSetUserClaimValuesWithID(AbstractUserStoreManager.java:897) ~[org.wso2.carbon.user.core_4.9.12.jar:?]
 at org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager.doSetUserClaimValuesWithID(UniqueIDJDBCUserStoreManager.java:1866) ~[org.wso2.carbon.user.core_4.9.12.jar:?]
 at org.wso2.carbon.user.core.common.AbstractUserStoreManager.setUserClaimValuesWithID(AbstractUserStoreManager.java:13410) ~[org.wso2.carbon.user.core_4.9.12.jar:?]
 at org.wso2.carbon.user.core.common.AbstractUserStoreManager.setUserClaimValuesWithID(AbstractUserStoreManager.java:13345) ~[org.wso2.carbon.user.core_4.9.12.jar:?]
 at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.updateUserClaims(SCIMUserManager.java:5219) [org.wso2.carbon.identity.scim2.common_3.4.26.jar:?]
 at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.updateUser(SCIMUserManager.java:1266) [org.wso2.carbon.identity.scim2.common_3.4.26.jar:?]
 at org.wso2.charon3.core.protocol.endpoints.UserResourceManager.updateWithPATCH(UserResourceManager.java:712) [org.wso2.charon3.core_4.0.10.jar:?]
 at org.wso2.carbon.identity.scim2.provider.resources.UserResource.patchUser(UserResource.java:337) [classes/:?]
 at jdk.internal.reflect.GeneratedMethodAccessor873.invoke(Unknown Source) ~[?:?]
 at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
 at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
...
Caused by: java.sql.BatchUpdateException: String or binary data would be truncated in table 'sqldb-asgardeo-is-consumer-eupr.dbo.UM_USER_ATTRIBUTE', column 'UM_ATTR_VALUE'. Truncated value: 'CIAM_Portal:ui_end_user,CIAM_Portal:user,ESS:common-Directlink,ESS:common-Emailalertsetting,ESS:comm'.
 at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2116) ~[mssql-jdbc-10.2.1.jre11.jar:?]
 at jdk.internal.reflect.GeneratedMethodAccessor81.invoke(Unknown Source) ~[?:?]
 at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
 at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
 at org.wso2.carbon.ndatasource.rdbms.CorrelationLogInterceptor$StatementProxy.invoke(CorrelationLogInterceptor.java:161) ~[org.wso2.carbon.ndatasource.rdbms_4.9.12.jar:?]
 at com.sun.proxy.$Proxy55.executeBatch(Unknown Source) ~[?:?]
 at jdk.internal.reflect.GeneratedMethodAccessor81.invoke(Unknown Source) ~[?:?]
 at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
 at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
 at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118) ~[jdbc-pool_9.0.65.wso2v1.jar:?]
 at com.sun.proxy.$Proxy55.executeBatch(Unknown Source) ~[?:?]
 at org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager.updateProperties(UniqueIDJDBCUserStoreManager.java:2830) ~[org.wso2.carbon.user.core_4.9.12.jar:?]
 ... 61 more
```
How to reproduce:
1. Create a new user.
2. Create a new claim named `entitlements`. Check `display in user profile`.
3. Use the following sample curl to update the value of the claim with a large value (> 1024) 

Sample curl:
```
curl --location --request PATCH 'https://api.eu.asgardeo.io/t/abbstage/scim2/Users/ffe39244-71d4-4c99-b4ae-f31b0a063813' \
--header 'Accept: application/scim+json' \
--header 'Content-Type: application/scim+json' \
--header 'Cookie: paf=1694766433.463.1472.954825|71acb898e1e9604d7bd8c41e308eb24e' \
--data '{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp",
    "urn:scim:wso2:schema"
  ],
  "Operations": [
    {
      "op": "replace",
      "value": {
    "urn:scim:wso2:schema": {
        "entitlements": "CIAM_Portal:ui_end_user,CIAM_Portal:user,ESS:common-Directlink,ESS:common-Emailalertsetting,ESS:common-Menu,ESS:common-Privacynotice,ESS:Dashboard-Dropdownselection,ESS:Dashboard-Map,ESS:Dashboard-Vehicleinformation,ESS:Demo-Events,ESS:ESS-P3-CMU,ESS:Fleet-Diagnostic,ESS:Fleet-Events,ESS:Fleet-Overallcondition,ESS:Fleet-Overview,ESS:Fleet-Overview-Availability,ESS:Fleet-Overview-Reliability,ESS:Fleet-Overview-Stress,ESS:Fleet-Overview-Utilization,ESS:Fleet-Statistics,ESS:Fleet-Vehicleinformation,ESS:Module-P3-Temp,ESS:Module-P3-Temp-Value,ESS:Module-P3-Volt,ESS:Product-Conditionutlization,ESS:Product-Events,ESS:Product-Overallcondition,ESS:Product-Overview,ESS:Product-Overview-Availability,ESS:Product-Overview-Basicinfo,ESS:Product-Overview-Reliability,ESS:Product-Overview-Stress,ESS:Product-Overview-Utilization,ESS:Product-Timetrend,ESS:Product-Trend-Batterycontcharge,ESS:Product-Trend-Batterycontdischarge,ESS:Product-Trend-Batterycurrent,ESS:Product-Trend-Batterypeccharge,ESS:Product-Trend-Batterypecdischarge,ESS:Product-Trend-Diagnosticevent,ESS:Product-Trend-Download,ESS:Product-Trend-Feedflow,ESS:Product-Trend-Overloadcounter,ESS:Product-Trend-Power,ESS:Product-Trend-Reliability,ESS:Product-Trend-Returnflow,ESS:Product-Trend-Soc,ESS:Product-Trend-Temperature,ESS:Product-Usage,ESS:Product-Usage-DOD,ESS:Product-Usage-OH,ESS:Product-Usage-Power,ESS:Product-Usage-Soc,ESS:Product-Usage-Temperature,ESS:UCID-P3-Signals,ESS:Vehicle-Events,ESS:Vehicle-Overallcondition,ESS:Vehicle-Overview,ESS:Vehicle-Overview-Availability,,ESS:Vehicle-Overview-Reliability,ESS:Vehicle-Overview-Stress,ESS:Vehicle-Overview-Utilization,ESS:Veh-P3-batteries"
    }
      }
    }
  ]
}'
```

The maximum character count should be gracefully handled. The DB error should be caught and a 400 should be thrown indicating that the limit has been exceeded. 

Note: Inherently the character limit for the column UM_ATTR_VALUE of the table UM_USER_ATTRIBUTE is 1024. However, in Asgardeo EU this has been increased to 2048.

Asgardeo issue: https://github.com/wso2-enterprise/asgardeo-product/issues/19481

**Comment by VimukthiPerera** [comment]
@Yoshani Please send an email to dpo@wso2.com and delete this Issue and recreate after masking the data.
