### ISSUE TITLE
Invalid error message when SP created with a description length exceeding the default value

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-is#1688]
**Environment**
IS 5.4.0 standalone pack
JDK - 1.8
DB - Postgres 9.6.3
OS - ubuntu 15.10
Browser - Chrome - Version 58.0.3029.96

**Steps to recreate the issue**
1. Create an SP with Description more than 1030 characters (ex: 1056 characters in description)

**Observations**
The error message does not reflect the maximum possible description length. Rather following error message appeared 

![screenshot from 2017-12-18 16-47-31](https://user-images.githubusercontent.com/14962228/34103748-e5dab35a-e413-11e7-89b1-37cec26782c7.png)

Backend error message is as follows
```
Caused by: org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Failed to update service provider 6
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.updateApplication(ApplicationDAOImpl.java:389)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.updateApplication(ApplicationManagementServiceImpl.java:269)
	... 79 more
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(1024)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2310)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2023)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:217)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:421)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:137)
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy18.executeUpdate(Unknown Source)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.updateBasicApplicationData(ApplicationDAOImpl.java:459)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.updateApplication(ApplicationDAOImpl.java:333)
	... 80 more

```

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
