### ISSUE TITLE
Context does not exist. Probably due to invalidated cache

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1690]
[2017-12-18 17:03:03,223] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Context does not exist. Probably due to invalidated cache

Due to the above exception login script fails even for 2 loop count with a 100s rampup time and 1 thread.

Please see the attached script. Script is run only for login and logout requests.
Script can be run with no issues for one loop/thread.

[https://github.com/wso2-incubator/identity-test-integration/blob/master/solution18/src/test/jmeter/Fine-grained-acces-controlforSP.jmx](jmeter script.)

**Comment by ushanib** [comment]
In Tomcat side below exception can be seen.

`SEVERE: An error has occurred
org.wso2.carbon.identity.sso.agent.SSOAgentException: Error in unmarshalling SAML2SSO Request from the encoded String
	at org.wso2.carbon.identity.sso.agent.util.SSOAgentUtils.unmarshall(SSOAgentUtils.java:313)
	at org.wso2.carbon.identity.sso.agent.saml.SAML2SSOManager.processResponse(SAML2SSOManager.java:341)
	at org.wso2.carbon.identity.sso.agent.SSOAgentFilter.doFilter(SSOAgentFilter.java:101)
	at org.wso2.sample.is.sso.agent.SSOAgentSampleFilter.doFilter(SSOAgentSampleFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:947)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at org.wso2.carbon.identity.sso.agent.util.SSOAgentUtils.unmarshall(SSOAgentUtils.java:303)
	... 19 more
`

**Comment by sebastienratez** [comment]
I think the link for the jmeter script has changed, probably to this:

https://github.com/wso2/identity-test-integration/blob/master/scenario18/jmeter/01-Scenario-18-Fine-grained-acces-controlforSP.jmx

About this problem, it seems it happens only with internet explorer on my end.

**Comment by deki** [comment]
Similar issue was reported here: https://wso2.org/jira/browse/IDENTITY-6357

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
