### ISSUE TITLE
Unable to set "Share with only selected sub-organizations" as Application Shared Access option

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17081]
**Describe the issue:**
[recording(4).webm](https://github.com/wso2/product-is/assets/39120228/efc60187-2637-452a-9769-c8eec9fb1337)

**How to reproduce:**
Note: At least one sub-organization must already be created
Click on the created Application
Click on the "Shared Access" Tab ( Application Edit section)
Initially set "Do not share with any sub-organization" optin 
Then Attempt to set the "Share with only selected sub-organizations" option.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-m4-SNAPSHOT 
 - OS:Linux, Mac
 - Database:  MySQL, H2
 - Userstore: JDBC

---
**Error Log** wso2carbon logs
```
[2023-10-20 13:13:05,428] [fa25253f-e35f-4af4-8f6b-739a5b8d874a] ERROR {org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl} - Error in sharing application: 7 to organization: 38a7fa8c-2fd2-46e0-a2c7-82d4d94aaecf org.wso2.carbon.identity.organization.management.service.exception.OrganizationManagementServerException: Unable create oauth consumer app for fragment application
	at org.wso2.carbon.identity.organization.management.service.util.Utils.handleServerException(Utils.java:116)
	at org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl.shareApplication(OrgApplicationManagerImpl.java:605)
	at org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl.lambda$shareOrganizationApplication$1(OrgApplicationManagerImpl.java:197)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.wso2.carbon.identity.oauth.IdentityOAuthClientException: An application with the same name already exists.
	at org.wso2.carbon.identity.oauth.dao.OAuthAppDAO.addOAuthApplication(OAuthAppDAO.java:211)
	at org.wso2.carbon.identity.oauth.OAuthAdminServiceImpl.registerAndRetrieveOAuthApplicationData(OAuthAdminServiceImpl.java:362)
	at org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl.createOAuthApplication(OrgApplicationManagerImpl.java:643)
	at org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl.shareApplication(OrgApplicationManagerImpl.java:603)
	... 5 more

```

**Comment by sadilchamishka** [comment]
Fixed by - https://github.com/wso2/product-is/issues/16927
