### ISSUE TITLE
Browser refresh breaks the Console

### ISSUE THREAD

**Issue by pavinduLakshan** [wso2/product-is#17123]
**Describe the issue:**

Browser refresh shows the session expired modal and breaks the console. The following error can be seen in the browser console.

```js
Uncaught Error: Objects are not valid as a React child (found: object with keys {error_description, error}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:14887:1)
    at reconcileChildFibers (react-dom.development.js:15828:1)
    at reconcileChildren (react-dom.development.js:19167:1)
    at updateHostComponent (react-dom.development.js:19924:1)
    at beginWork (react-dom.development.js:21618:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)

react-dom.development.js:18687 The above error occurred in the <div> component:

    at div
    at div
    at div
    at div
    at NotificationItem (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:199376:5)
    at div
    at NotificationContainer (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:199273:5)
    at div
    at NotificationSystem (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:199743:5)
    at div
    at Alert (https://localhost:9001/console/static/js/main.js?036a9e5a2d1ff08d:154009:24)
    at AppView (https://localhost:9001/console/static/js/main.js?036a9e5a2d1ff08d:125235:24)
    at Route (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:204142:5)
    at Switch (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:204588:5)
    at Suspense
    at ErrorBoundary (https://localhost:9001/console/static/js/main.js?036a9e5a2d1ff08d:161898:5)
    at AppLayout (https://localhost:9001/console/static/js/main.js?036a9e5a2d1ff08d:123840:86)
    at Route (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:204142:5)
    at Switch (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:204588:5)
    at SessionManagementProvider (https://localhost:9001/console/static/js/main.js?036a9e5a2d1ff08d:185719:24)
    at AccessControlContext (https://localhost:9001/console/static/js/main.js?036a9e5a2d1ff08d:127401:83)
    at AccessProvider (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:151950:22)
    at AccessControlProvider (https://localhost:9001/console/static/js/main.js?036a9e5a2d1ff08d:127526:29)
    at ResponsiveProvider (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:423:9)
    at MediaContextProvider (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:747:43)
    at Suspense
    at DocumentationProvider (https://localhost:9001/console/static/js/main.js?036a9e5a2d1ff08d:161301:24)
    at div
    at Router (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:204295:5)
    at App (https://localhost:9001/console/static/js/src_app_tsx.chunk.js:129:75)
    at I18nextProvider (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:193812:19)
    at Suspense
    at K (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:2059:193779)
    at J (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:2059:194048)
    at ProtectedApp (https://localhost:9001/console/static/js/main.js?036a9e5a2d1ff08d:124622:93)
    at UIConfigProvider (https://localhost:9001/console/static/js/main.js?036a9e5a2d1ff08d:131070:24)
    at ResourceEndpointsProvider (https://localhost:9001/console/static/js/main.js?036a9e5a2d1ff08d:130971:24)
    at DeploymentConfigProvider (https://localhost:9001/console/static/js/main.js?036a9e5a2d1ff08d:130876:24)
    at AppConfigProvider (https://localhost:9001/console/static/js/main.js?036a9e5a2d1ff08d:130792:24)
    at W (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:2059:188401)
    at Router (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:204295:5)
    at BrowserRouter (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:203169:5)
    at Provider (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:200754:20)
    at ThemeProvider (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:52284:5)
    at ThemeProvider (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:52640:5)
    at CssVarsProvider (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:54523:5)
    at StyledEngineProvider (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:52448:5)
    at ThemeProvider (https://localhost:9001/console/static/js/vendor.js?036a9e5a2d1ff08d:68878:13)
    at RootWithConfig (https://localhost:9001/console/static/js/main.js?036a9e5a2d1ff08d:123700:60)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**How to reproduce:**

1. Sign into the console
2. Navigate to any page.
3. Perform a browser refresh.

**Expected behavior:**

A browser refresh shouldn't break the application.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
It seems like the structure of the error response has been changed recently to follows.

```js
{
    "message": {
        "error_description": "Persisted access token data not found",
        "error": "invalid_grant"
    },
    "name": "Refreshing access token failed with ",
    "code": "SPA-AUTH_HELPER-HR-SE01"
}
```

The frontend has been setup to get the error message from the `error?.message`[1] property, but now the `message` is an object, therefore React throws the above error.

[1] https://github.com/wso2/identity-apps/blob/master/apps/console/src/features/organizations/components/organization-switch/organization-switch-breadcrumb.tsx#L86

**Comment by pavinduLakshan** [comment]
Closing the issue as this is no longer reproducible
