### ISSUE TITLE
[Chaos]During the Graceful restart ldap error is printed eventhough the user store is JDBC

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#1730]
[Chaos]During the Graceful restart ldap error is printed eventhough the user store is JDBC. 

In 2 node cluster while the script is run to login with 100 threads, 1 loop and 100 s rampup, when I click on the graceful restart button in management console the node that was actively serving was shutting down and restarting. 
But the below exception is printed in the backend. User store is JDBC (MySQL). 
The below error is misleading and cannot understand how it is printed. 

`TID: [-1234] [] [2017-12-19 06:15:32,312]  INFO {org.wso2.carbon.ldap.server.configuration.LDAPConfigurationBuilder} -  KDC server is disabled. 
TID: [-1234] [] [2017-12-19 06:15:32,511] ERROR {org.apache.directory.shared.ldap.schema.loader.ldif.LdifSchemaLoader} -  ERR_10004 Expecting to find a schema.ldif file in provided baseDirectory path '/home/ubuntu/packs/ga/wso2is-5.4.0_cluster/repository/data/org.wso2.carbon.directory/schema/ou=schema.ldif' but no such file found. 
TID: [-1234] [] [2017-12-19 06:15:32,511] ERROR {org.apache.directory.shared.ldap.schema.loader.ldif.LdifSchemaLoader} -  ERR_10004 Expecting to find a schema.ldif file in provided baseDirectory path '/home/ubuntu/packs/ga/wso2is-5.4.0_cluster/repository/data/org.wso2.carbon.directory/schema/ou=schema.ldif' but no such file found. 
TID: [-1234] [] [2017-12-19 06:15:32,512] ERROR {org.wso2.carbon.apacheds.impl.ApacheLDAPServer} -  LDAP server initialization failed. 
org.wso2.carbon.ldap.server.exception.DirectoryServerException: Can not start the Default apacheds service 
	at org.wso2.carbon.apacheds.impl.ApacheLDAPServer.initializeDefaultDirectoryService(ApacheLDAPServer.java:165)
	at org.wso2.carbon.apacheds.impl.ApacheLDAPServer.init(ApacheLDAPServer.java:94)
	at org.wso2.carbon.ldap.server.DirectoryActivator.startLdapServer(DirectoryActivator.java:192)
	at org.wso2.carbon.ldap.server.DirectoryActivator.start(DirectoryActivator.java:78)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.io.FileNotFoundException: ERR_10004 Expecting to find a schema.ldif file in provided baseDirectory path '/home/ubuntu/packs/ga/wso2is-5.4.0_cluster/repository/data/org.wso2.carbon.directory/schema/ou=schema.ldif' but no such file found.
	at org.apache.directory.shared.ldap.schema.loader.ldif.LdifSchemaLoader.<init>(LdifSchemaLoader.java:113)
	at org.wso2.carbon.apacheds.impl.CarbonDirectoryServiceFactory.initSchema(CarbonDirectoryServiceFactory.java:163)
	at org.wso2.carbon.apacheds.impl.CarbonDirectoryServiceFactory.build(CarbonDirectoryServiceFactory.java:217)
	at org.wso2.carbon.apacheds.impl.CarbonDirectoryServiceFactory.init(CarbonDirectoryServiceFactory.java:119)
	at org.wso2.carbon.apacheds.impl.ApacheLDAPServer.initializeDefaultDirectoryService(ApacheLDAPServer.java:162)
	... 18 more
TID: [-1234] [] [2017-12-19 06:15:32,516] ERROR {org.wso2.carbon.ldap.server.DirectoryActivator} -  Could not start the embedded-ldap.  
org.wso2.carbon.ldap.server.exception.DirectoryServerException: Error initializing ApacheLDAPServer. 
	at org.wso2.carbon.apacheds.impl.ApacheLDAPServer.init(ApacheLDAPServer.java:102)
	at org.wso2.carbon.ldap.server.DirectoryActivator.startLdapServer(DirectoryActivator.java:192)
	at org.wso2.carbon.ldap.server.DirectoryActivator.start(DirectoryActivator.java:78)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: org.wso2.carbon.ldap.server.exception.DirectoryServerException: Can not start the Default apacheds service 
	at org.wso2.carbon.apacheds.impl.ApacheLDAPServer.initializeDefaultDirectoryService(ApacheLDAPServer.java:165)
	at org.wso2.carbon.apacheds.impl.ApacheLDAPServer.init(ApacheLDAPServer.java:94)
	... 17 more
Caused by: java.io.FileNotFoundException: ERR_10004 Expecting to find a schema.ldif file in provided baseDirectory path '/home/ubuntu/packs/ga/wso2is-5.4.0_cluster/repository/data/org.wso2.carbon.directory/schema/ou=schema.ldif' but no such file found.
	at org.apache.directory.shared.ldap.schema.loader.ldif.LdifSchemaLoader.<init>(LdifSchemaLoader.java:113)
	at org.wso2.carbon.apacheds.impl.CarbonDirectoryServiceFactory.initSchema(CarbonDirectoryServiceFactory.java:163)
	at org.wso2.carbon.apacheds.impl.CarbonDirectoryServiceFactory.build(CarbonDirectoryServiceFactory.java:217)
	at org.wso2.carbon.apacheds.impl.CarbonDirectoryServiceFactory.init(CarbonDirectoryServiceFactory.java:119)
	at org.wso2.carbon.apacheds.impl.ApacheLDAPServer.initializeDefaultDirectoryService(ApacheLDAPServer.java:162)
	... 18 more
TID: [-1] [] [2017-12-19 06:15:32,552]  INFO {org.wso2.carbon.mex.internal.Office365SupportMexComponent} -  Office365Support MexServiceComponent bundle activated successfully.. 
TID: [-1] [] [2017-12-19 06:15:32,579]  INFO {org.wso2.carbon.mex2.internal.DynamicCRMCustomMexComponent} -  DynamicCRMSupport MexServiceComponent bundle activated successfully. 

`

**Comment by ushanib** [comment]
This issue due to an user error. Accidentally ldap config has been removed. Hence closing this issue
