### ISSUE TITLE
MySQL Exception and 500 Console Error When Creating New Suborg via Console

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17387]
**Describe the issue:**
When attempting to create a new suborg via the console, Encountered  issue. While the system allows the creation of an organization, an error message is displayed: "An error occurred while adding the organization." 

Additionally, there is logs MySQL exception, and the browser's  console indicates a 500 Internal Server Error.

console Error 

<img width="1722" alt="Screenshot 2023-10-30 at 11 18 42" src="https://github.com/wso2/product-is/assets/39120228/a1430031-1cae-40b6-aeb7-600567a130b2">

Logs
```
 [fe6511e2-d61b-4475-8f94-1de3af26c114] ERROR {org.wso2.carbon.identity.api.server.organization.management.v1.service.OrganizationManagementService} - errorCode: ORG-65090 | message: null org.wso2.carbon.identity.organization.management.service.exception.OrganizationManagementServerException: Error while firing the events
	at org.wso2.carbon.identity.organization.management.ext.OrganizationManagerListenerImpl.fireEvent(OrganizationManagerListenerImpl.java:156)
	at org.wso2.carbon.identity.organization.management.ext.OrganizationManagerListenerImpl.postAddOrganization(OrganizationManagerListenerImpl.java:56)
	at org.wso2.carbon.identity.organization.management.service.OrganizationManagerImpl.addOrganization(OrganizationManagerImpl.java:175)
	at org.wso2.carbon.identity.api.server.organization.management.v1.service.OrganizationManagementService.addOrganization(OrganizationManagementService.java:237)
	at org.wso2.carbon.identity.api.server.organization.management.v1.impl.OrganizationsApiServiceImpl.organizationPost(OrganizationsApiServiceImpl.java:119)
	at org.wso2.carbon.identity.api.server.organization.management.v1.OrganizationsApi.organizationPost(OrganizationsApi.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:661)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:425)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:357)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:294)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:146)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:115)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:175)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:144)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.wso2.carbon.identity.event.IdentityEventException: An error occurred while creating shared applications in the new organization
	at org.wso2.carbon.identity.organization.management.application.listener.OrganizationCreationHandler.handleEvent(OrganizationCreationHandler.java:68)
	at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56)
	at org.wso2.carbon.identity.organization.management.ext.OrganizationManagerListenerImpl.fireEvent(OrganizationManagerListenerImpl.java:150)
	... 60 more
Caused by: org.wso2.carbon.identity.organization.management.service.exception.OrganizationManagementException: An error occurred while getting the application.
	at org.wso2.carbon.identity.organization.management.application.listener.ApplicationSharingManagerListenerImpl.getSharedUserAttributes(ApplicationSharingManagerListenerImpl.java:199)
	at org.wso2.carbon.identity.organization.management.application.listener.ApplicationSharingManagerListenerImpl.postShareApplication(ApplicationSharingManagerListenerImpl.java:76)
	at org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl.shareApplication(OrgApplicationManagerImpl.java:637)
	at org.wso2.carbon.identity.organization.management.application.listener.OrganizationCreationHandler.addSharedApplicationsToOrganization(OrganizationCreationHandler.java:115)
	at org.wso2.carbon.identity.organization.management.application.listener.OrganizationCreationHandler.handleEvent(OrganizationCreationHandler.java:66)
	... 62 more
Caused by: org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error while retrieving the fragment application details.
	at org.wso2.carbon.identity.organization.management.application.listener.FragmentApplicationMgtListener.doPostGetServiceProvider(FragmentApplicationMgtListener.java:280)
	at org.wso2.carbon.identity.application.mgt.listener.DefaultApplicationResourceMgtListener.doPostGetApplicationByResourceId(DefaultApplicationResourceMgtListener.java:189)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.getApplicationByResourceId(ApplicationManagementServiceImpl.java:2559)
	at org.wso2.carbon.identity.organization.management.application.listener.ApplicationSharingManagerListenerImpl.getSharedUserAttributes(ApplicationSharingManagerListenerImpl.java:190)
	... 66 more
Caused by: org.wso2.carbon.identity.role.v2.mgt.core.exception.IdentityRoleManagementServerException: Error while retrieving main role to shared role mappings by sub org tenant : 853853f8-b690-4dfc-ae02-2248978db592
	at org.wso2.carbon.identity.role.v2.mgt.core.dao.RoleDAOImpl.getMainRoleToSharedRoleMappingsBySubOrg(RoleDAOImpl.java:1090)
	at org.wso2.carbon.identity.role.v2.mgt.core.RoleManagementServiceImpl.getMainRoleToSharedRoleMappingsBySubOrg(RoleManagementServiceImpl.java:578)
	at org.wso2.carbon.identity.organization.management.application.listener.FragmentApplicationMgtListener.getAssociatedRolesConfigForSharedApp(FragmentApplicationMgtListener.java:332)
	at org.wso2.carbon.identity.organization.management.application.listener.FragmentApplicationMgtListener.doPostGetServiceProvider(FragmentApplicationMgtListener.java:275)
	... 69 more
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
	at jdk.internal.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy50.executeQuery(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.NamedPreparedStatement.executeQuery(NamedPreparedStatement.java:246)
	at org.wso2.carbon.identity.role.v2.mgt.core.dao.RoleDAOImpl.getMainRoleToSharedRoleMappingsBySubOrg(RoleDAOImpl.java:1080)
	... 72 more
```
[recording(4).webm](https://github.com/wso2/product-is/assets/39120228/49d87962-f9c6-459a-80da-8a258c7bb7c2)

**How to reproduce:**
1. Setup Mysql as default DB (https://is.docs.wso2.com/en/latest/deploy/change-to-mysql/#change-the-default-datasource)
2. Access the console.
3. Try to create a new suborg.
4. Observe the error message on the UI and check the console logs for errors.

**Expected behavior:**

Creating a new suborg should complete without errors, displaying a success message on the UI and confirming the addition of the organization in the backend database.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-alpha-SNAPSHOT
 - OS: Mac - 
 - Database: Mysql - 8.1.0 
 - Userstore: JDBC

---

**Comment by AnuradhaSK** [comment]
Fixed by https://github.com/wso2/carbon-identity-framework/pull/5109
