### ISSUE TITLE
Error while removing a role of a shared application with MySQL database

### ISSUE THREAD

**Issue by PasinduYeshan** [wso2/product-is#17468]
**Describe the issue:**
Following error occurred while removing role from an shared application. 

```
[2023-10-31 23:49:29,718] [5fd5f2c4-6d46-4765-8a7b-cd443bf21c73] ERROR {org.wso2.carbon.identity.api.server.application.management.v1.core.functions.Utils} - errorCode: APP-65001 | message: Error while updating shared roles related to application 4 update. org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error while updating shared roles related to application 4 update.
	at org.wso2.carbon.identity.organization.management.handler.listener.SharedRoleMgtListener.doPostUpdateApplication(SharedRoleMgtListener.java:248)
	at org.wso2.carbon.identity.application.mgt.listener.DefaultApplicationResourceMgtListener.doPostUpdateApplicationByResourceId(DefaultApplicationResourceMgtListener.java:111)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.updateApplicationByResourceId(ApplicationManagementServiceImpl.java:2620)
	at org.wso2.carbon.identity.api.server.application.management.v1.core.ServerApplicationManagementService.patchApplication(ServerApplicationManagementService.java:856)
	at org.wso2.carbon.identity.api.server.application.management.v1.impl.ApplicationsApiServiceImpl.patchApplication(ApplicationsApiServiceImpl.java:151)
	at org.wso2.carbon.identity.api.server.application.management.v1.ApplicationsApi.patchApplication(ApplicationsApi.java:934)
	....
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:146)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:115)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	...
Caused by: org.wso2.carbon.identity.role.v2.mgt.core.exception.IdentityRoleManagementServerException: Error while deleting the role name: appRole1 in the tenantDomain: carbon.super
	at org.wso2.carbon.identity.role.v2.mgt.core.dao.RoleDAOImpl.deleteRole(RoleDAOImpl.java:582)
	at org.wso2.carbon.identity.role.v2.mgt.core.RoleManagementServiceImpl.deleteRole(RoleManagementServiceImpl.java:253)
	at org.wso2.carbon.identity.organization.management.handler.listener.SharedRoleMgtListener.handleRemovedApplicationAudienceRolesOnAppUpdate(SharedRoleMgtListener.java:371)
	at org.wso2.carbon.identity.organization.management.handler.listener.SharedRoleMgtListener.doPostUpdateApplication(SharedRoleMgtListener.java:215)
	... 58 more
Caused by: org.wso2.carbon.identity.role.v2.mgt.core.exception.IdentityRoleManagementServerException: Error while deleting shared roles of role id : 9ddc51bc-3f2f-4395-93c2-c7591701c783
	at org.wso2.carbon.identity.role.v2.mgt.core.dao.RoleDAOImpl.deleteSharedHybridRoles(RoleDAOImpl.java:3025)
	at org.wso2.carbon.identity.role.v2.mgt.core.dao.RoleDAOImpl.deleteRole(RoleDAOImpl.java:550)
	... 61 more
Caused by: java.sql.SQLException: You can't specify target table 'UM_HYBRID_ROLE' for update in FROM clause
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	...
	at org.wso2.carbon.database.utils.jdbc.NamedPreparedStatement.executeUpdate(NamedPreparedStatement.java:252)
	at org.wso2.carbon.identity.role.v2.mgt.core.dao.RoleDAOImpl.deleteSharedHybridRoles(RoleDAOImpl.java:3022)
	... 62 more
```
**How to reproduce:**
- Create an application.
- Change the audience type to application.
- Create two roles associated to above created application.
- Navigate to applications section and select application. 
- Navigate to roles section.
- Try to remove one of role.

**Expected behavior:**
- Role should be removed successfully.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: MySQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by PasinduYeshan** [comment]
Fixed with
- https://github.com/wso2/carbon-identity-framework/pull/5156
