### ISSUE TITLE
Passkey authentication doesn't work when email OTP is configured as 2FA

### ISSUE THREAD

**Issue by ThaminduDilshan** [wso2/product-is#17480]
**Describe the issue:**
When the passkey authentication is configured with email OTP being the second factor authenticator, the authentication cannot be completed and following error gets thrown at the terminal. Note that first step gets completed with errors and error occurs while sending the email.

Please note that the email OTP flow works and login gets complted when I use username/ password as the first factor.

```
[2023-11-01 10:46:37,239] [52339701-c4d2-46f9-9e08-12c1a9eeccc8] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! Assertion failed while finishing the assertion to retrieve the assertion result.
[2023-11-01 10:49:27,867] [3438f69a-7ae1-418f-bf40-e075c4e97516] ERROR {org.wso2.carbon.event.output.adapter.email.EmailEventAdapter} - Exception occurred when sending email to jane@thamindudj.com. 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials ... - gsmtp
javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials ... - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:965)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:876)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:780)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.wso2.carbon.event.output.adapter.email.EmailEventAdapter$EmailSender.run(EmailEventAdapter.java:367)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[2023-11-01 10:49:27,868] [3438f69a-7ae1-418f-bf40-e075c4e97516] ERROR {org.wso2.carbon.event.output.adapter.email.EmailEventAdapter} - Event dropped at Output Adapter 'EmailPublisher' for tenant id '-1234', Error in message format, 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials ... - gsmtp
javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials ... - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:965)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:876)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:780)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.wso2.carbon.event.output.adapter.email.EmailEventAdapter$EmailSender.run(EmailEventAdapter.java:367)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

![Screenshot from 2023-11-01 10-51-51](https://github.com/wso2/product-is/assets/35653110/a42ea902-5fdb-411f-b50a-87e922f7d0dd)

https://github.com/wso2/product-is/assets/35653110/1936a0b8-c97d-4033-ac2e-e4f07a054b74

**How to reproduce:**
1. Register an application and configure authentication flow as below.
    - Step 1: Username/ password, passkey
    - Step 2: email OTP
2. Add a user and register a passkey by login into the myaccount
3. Try to login to the application

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 7.0.0 Alpha
 - OS: Linux
 - Browser: Chrome version 113.0.5672.92 (Official Build) (64-bit)/ Brave version 1.51.114 Chromium: 113.0.5672.92 (Official Build) (64-bit)

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by ThaminduDilshan** [comment]
Please note that I'm trying out the authentication flow in a tenant (`tenant1.com`) and the email provider is configured for it. I haven't configured an email provider for the super tenant.

However as per the below log, it tries to access the email provider of the super tenant. Hence the error.
`Event dropped at Output Adapter 'EmailPublisher' for tenant id '-1234', Error in message format, 535-5.7.8 Username and Password not accepted`
