### ISSUE TITLE
Cannot recreate and share application with deleted shared application name

### ISSUE THREAD

**Issue by PasinduYeshan** [wso2/product-is#17499]
**Describe the issue:**
When attempting to recreate an application with the same name as a previously deleted one that was shared with organizations, following error occurs preventing the application from being shared with sub-organizations. 

```
ERROR {org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl} - Error in sharing application: 14 to organization: db4e42b4-b659-4707-871f-dc6391555a8e org.wso2.carbon.identity.organization.management.service.exception.OrganizationManagementServerException: Unable create oauth consumer app for fragment application
	at org.wso2.carbon.identity.organization.management.service.util.Utils.handleServerException(Utils.java:116)
	at org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl.shareApplication(OrgApplicationManagerImpl.java:622)
	at org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl.lambda$shareOrganizationApplication$1(OrgApplicationManagerImpl.java:200)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.wso2.carbon.identity.oauth.IdentityOAuthClientException: An application with the same name already exists.
	at org.wso2.carbon.identity.oauth.dao.OAuthAppDAO.addOAuthApplication(OAuthAppDAO.java:211)
	at org.wso2.carbon.identity.oauth.OAuthAdminServiceImpl.registerAndRetrieveOAuthApplicationData(OAuthAdminServiceImpl.java:453)
	at org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl.createOAuthApplication(OrgApplicationManagerImpl.java:686)
	at org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl.shareApplication(OrgApplicationManagerImpl.java:620)
	... 5 more
```

**How to reproduce:**
- Create an application and share them with organizations.
- Delete the application. 
- Recreate an application with the same name like deleted one. 
- Try to share it with organizations. 

**Expected behavior:**
- Recreated application should be shared with sub-organizations. 

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by PasinduYeshan** [comment]
This issue is fixed with this PR - https://github.com/wso2-extensions/identity-organization-management/pull/282
