### ISSUE TITLE
CON_APP_KEY recovery is not triggered when correlation logs are enabled on IS 5.11.0

### ISSUE THREAD

**Issue by vfraga** [wso2/product-is#17533]
**Describe the issue:**
We're observing that when correlation logs are enabled, the `CorrelationLogInterceptor#invoke` method is throwing an `InvocationTargetException` rather than the underlying `SQLIntegrityConstraintViolationException` or `SQLException` expected in the catch blocks in the `AccessTokenDAOImpl` class [1], leading to the recovery logic not being executed:

```
TID: [-1234] [] [2023-10-09 04:00:37,964] [912a34ee-ab6a-494d-bbcd-178a3e404b80] ERROR {org.wso2.carbon.identity.oauth2.OAuth2Service} - Error occurred while issuing the access token for Client ID : xxxxxxxxxxxx, User ID xxxxxxxxxxxx, Scope : [openid] and Grant Type : password java.lang.reflect.UndeclaredThrowableException
    at com.sun.proxy.$Proxy56.execute(Unknown Source)
    at jdk.internal.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
    at com.sun.proxy.$Proxy56.execute(Unknown Source)
    at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:225)
    at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:102)
    at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:326)
    at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.storeAccessToken(AbstractAuthorizationGrantHandler.java:306)
    at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.persistAccessTokenInDB(AbstractAuthorizationGrantHandler.java:440)
    at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.generateNewAccessToken(AbstractAuthorizationGrantHandler.java:370)
    at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.issue(AbstractAuthorizationGrantHandler.java:166)
    at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.issue(AccessTokenIssuer.java:326)
    at org.wso2.carbon.identity.oauth2.OAuth2Service.issueAccessToken(OAuth2Service.java:257)
    at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:302)
    at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:122)
    at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:109)
    . . .
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
    at jdk.internal.reflect.GeneratedMethodAccessor200.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.wso2.carbon.ndatasource.rdbms.CorrelationLogInterceptor$StatementProxy.invoke(CorrelationLogInterceptor.java:154)
    ... 81 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xxxxxxxxxxxx' for key 'CON_APP_KEY'
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
    at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
    ... 85 more
```

This suggests that the fixes related to [2] weren't ported to 5.11.0.

**How to reproduce:**
1. Enable correlation logs on the product.
2. Set up a two-node cluster and generate access tokens with high concurrency.
    To increase the rate of CON_APP_KEY violation, disable Hazelcast clustering and use JWT token issuer.

**Expected behavior:**
CorrelationLogInterceptor should re-throw the exact exception thrown from the underlying DB driver.

**Environment information:**
 - Product Version: IS 5.11.0
 - Userstore: JDBC

---

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/AccessTokenDAOImpl.java#L330
[2] https://github.com/wso2/carbon-kernel/commit/105ccf17af8899c2043cc892f205a276f4cf48c6

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
