### ISSUE TITLE
Notice some error logs in the server console

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#17580]
**Describe the issue:**

I see some error logs in the IS-7 console. I don't know the scenarios when they occurred—just noted this when I opened the terminal.

An example error is as below.

```
[2023-11-03 14:22:03,574] [a44ef73b-b384-4feb-8c41-404a6ed32cce] ERROR {org.wso2.carbon.identity.application.authentication.framework.store.SessionDataStore} - Error while storing session data org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_6 ON PUBLIC.IDN_AUTH_SESSION_STORE(SESSION_ID, SESSION_TYPE, TIME_CREATED, OPERATION) VALUES ( /* key:6479 */ '548555e604079d9e050aff9dbe33e4f395e33abcccb113290f93ddbee03b9706', 'AppAuthFrameworkSessionContextCache', 1698999507891084083, 'STORE')"; SQL statement:
INSERT INTO IDN_AUTH_SESSION_STORE(SESSION_ID, SESSION_TYPE, OPERATION, SESSION_OBJECT, TIME_CREATED, EXPIRY_TIME, TENANT_ID) VALUES (?,?,?,?,?,?,?) [23505-220]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:520)
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
    at org.h2.message.DbException.get(DbException.java:223)
    at org.h2.message.DbException.get(DbException.java:199)
    at org.h2.index.Index.getDuplicateKeyException(Index.java:527)
    at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223)
    at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184)
    at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519)
    at org.h2.command.dml.Insert.insertRows(Insert.java:174)
    at org.h2.command.dml.Insert.update(Insert.java:135)
    at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
    at org.h2.command.CommandContainer.update(CommandContainer.java:169)
    at org.h2.command.Command.executeUpdate(Command.java:252)
```

Attached the 
[wso2carbon-11-03-2023.1.log](https://github.com/wso2/product-is/files/13262511/wso2carbon-11-03-2023.1.log)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
