### ISSUE TITLE
Issue in deleting and creating application role having the same name in B2B scenario

### ISSUE THREAD

**Issue by amanda-ariyaratne** [wso2/product-is#17672]
**Describe the issue:**
In the B2B scenario, if we delete an application role and then create a new application role with the same name as the previously deleted role, it is created in the primary organization but not shared to the suborganizations. Console gives the following error.
```
[2023-11-08 14:39:54,500] [acfe759a-7bdd-4f07-a38e-f6b038dc0e51] ERROR {org.wso2.carbon.identity.organization.management.handler.SharedRoleMgtHandler} - Error occurred while creating shared role in organization with id: 6aea1e37-da65-4f97-b228-e2f3c8369e35 org.wso2.carbon.identity.role.v2.mgt.core.exception.IdentityRoleManagementServerException: Error while retrieving the application for the given id: dfe5ec4b-5e52-4078-a14e-202b11e0c1a4
	at org.wso2.carbon.identity.application.mgt.listener.DefaultRoleManagementListener.validateApplicationRoleAudience(DefaultRoleManagementListener.java:475)
	at org.wso2.carbon.identity.application.mgt.listener.DefaultRoleManagementListener.preAddRole(DefaultRoleManagementListener.java:84)
	at org.wso2.carbon.identity.role.v2.mgt.core.RoleManagementServiceImpl.addRole(RoleManagementServiceImpl.java:93)
	at org.wso2.carbon.identity.organization.management.handler.SharedRoleMgtHandler.lambda$createSharedRolesOnNewRoleCreation$0(SharedRoleMgtHandler.java:210)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.wso2.carbon.identity.application.common.IdentityApplicationManagementServerException: Error while retrieving application with resourceId: dfe5ec4b-5e52-4078-a14e-202b11e0c1a4 in tenantDomain: 6aea1e37-da65-4f97-b228-e2f3c8369e35
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getApplicationByResourceId(ApplicationDAOImpl.java:5172)
	at org.wso2.carbon.identity.application.mgt.dao.impl.CacheBackedApplicationDAO.getApplicationByResourceId(CacheBackedApplicationDAO.java:435)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.getApplicationByResourceId(ApplicationManagementServiceImpl.java:2545)
	at org.wso2.carbon.identity.application.mgt.listener.DefaultRoleManagementListener.validateApplicationRoleAudience(DefaultRoleManagementListener.java:461)
	... 7 more
Caused by: org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error while retrieving associated roles for application ID: dfe5ec4b-5e52-4078-a14e-202b11e0c1a4
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getAssociatedRoles(ApplicationDAOImpl.java:2156)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getApplication(ApplicationDAOImpl.java:2119)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getApplicationByResourceId(ApplicationDAOImpl.java:5162)
	... 10 more
Caused by: org.wso2.carbon.identity.role.v2.mgt.core.exception.IdentityRoleManagementClientException: A role doesn't exist with id: f188f68e-fb02-4db2-acc8-ec1f25febe4f in the tenantDomain: 6aea1e37-da65-4f97-b228-e2f3c8369e35
	at org.wso2.carbon.identity.role.v2.mgt.core.dao.RoleDAOImpl.getRoleNameByID(RoleDAOImpl.java:2326)
	at org.wso2.carbon.identity.role.v2.mgt.core.RoleManagementServiceImpl.getRoleNameByRoleId(RoleManagementServiceImpl.java:482)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.buildAssociatedRolesWithRoleName(ApplicationDAOImpl.java:2173)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getAssociatedRoles(ApplicationDAOImpl.java:2154)
	... 12 more
```

**How to reproduce:**

https://github.com/wso2/product-is/assets/28347418/133f1a11-2fdd-4900-8ee0-756ccfb952a3

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by PasinduYeshan** [comment]
https://github.com/wso2/carbon-identity-framework/pull/5156

**Comment by PasinduYeshan** [comment]
Fixed with 
- https://github.com/wso2/carbon-identity-framework/pull/5156
