### ISSUE TITLE
Internal Server Error when adding/updating a adaptive script of an application using the management console

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#17808]
**Describe the issue:**
We can add/update the adaptive authentication of an application by adding/updating an adaptive auth script. When adding/updating the script the following page will be shown with a 500 Internal Server error.

<img width="1364" alt="image" src="https://github.com/wso2/product-is/assets/19262008/88ed4beb-313b-4535-a63a-c0d6698c8d08">

Please refer the following screencast for more details

https://github.com/wso2/product-is/assets/19262008/b20647f8-10dc-4ab2-ad57-82b9e39c09d9

Following is the stack trace of the issue.

```
[2023-11-15 15:18:16,140] [3d6c229e-a6b9-4c3b-81b4-40e4bde34b8a] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/].[bridgeservlet]} - Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception [An exception occurred processing [/application/configure-authentication-flow-finish-ajaxprocessor.jsp] at line [38]

35:     String spName = request.getParameter("spName");
36:     ApplicationBean appBean = ApplicationMgtUIUtil.getApplicationBeanFromSession(session, spName);
37:     appBean.updateOutBoundAuthenticationConfig(request);
38:     appBean.conditionalAuthentication(request);
39: %>
40:
41: <script>


Stacktrace:] with root cause java.lang.IllegalArgumentException: Illegal base64 character d
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:746)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:538)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:561)
	at org.wso2.carbon.identity.application.mgt.ui.ApplicationBean.conditionalAuthentication(ApplicationBean.java:1162)
	at org.apache.jsp.application.configure_002dauthentication_002dflow_002dfinish_002dajaxprocessor_jsp._jspService(configure_002dauthentication_002dflow_002dfinish_002dajaxprocessor_jsp.java:164)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:129)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:129)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
```

**How to reproduce:**
1. Create a service provider.
2. Go to `Local & Outbound Authentication Configuration` and go to the `Advanced Configurations`
3. Select a templated adaptive script from `Script Based Adaptive Authentication` and try to update the service provider.

**Expected behavior:**
Should be able to add the script without any issues.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0-beta
 - OS: Mac
 - Database: H2
 - Userstore: JDBC

**Comment by pamodaaw** [comment]
This is working in the latest pack. (wso2is-7.0.0-beta-SNAPSHOT: 18.10.2023)

https://github.com/wso2/product-is/assets/12439288/c39cb9fe-0db7-40c7-afb3-6c59302c0af3


@ShanChathusanda93 can you verify

**Comment by ShanChathusanda93** [comment]
Hi Pamoda,

I can still reproduce the issue in the latest build with the following java version.

```
openjdk version "11.0.18" 2023-01-17 LTS
OpenJDK Runtime Environment Zulu11.62+17-CA (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.62+17-CA (build 11.0.18+10-LTS, mixed mode)
```

Seems like a java version issue. Will debug and update the issue accordingly. Thanks for the info.

Best regards,
Shan.

**Comment by aaujayasena** [comment]
@ShanChathusanda93 is this  still reproducing ?

**Comment by ShanChathusanda93** [comment]
@aaujayasena this cannot be reproduced in the latest IS 7.0 beta2 pack. Hence closing the issue.
