### ISSUE TITLE
Unable to view users on console when CaseInsensitiveUsername and GroupAndRoleSeparation are disabled

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#17880]
**Describe the issue:**
This occures due to an invalid query in the `HybridJDBCConstants.GET_INTERNAL_ROLE_V2_LIST_OF_USERS_SQL` constant. It only selects one column, but the logic below expects two columns in the result set. This issue is not there when CaseInsensitiveUsername is enabled, since the `GET_INTERNAL_ROLE_V2_LIST_OF_USERS_SQL_CASE_INSENSITIVE` contains the correct query. 

Ref [1] [2]

Note: Disabling GroupAndRoleSeparation might not be an expected usecase in IS 7.0, but still this common method (`getRoleListOfUsersWithID()`) needs to be fixed.

[1] https://github.com/wso2/carbon-kernel/blob/202dde1c04a8645d3abcc01890e6ee4dd2532406/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/hybrid/HybridRoleManager.java#L794-L842
[2] https://github.com/wso2/carbon-kernel/pull/3700/files

**How to reproduce:**
- Set following in deployment.toml
```
[user_store]
type = "database_unique_id"
properties.CaseInsensitiveUsername = false
properties.UseCaseSensitiveUsernameForCacheKeys = false

[authorization_manager.properties]
GroupAndRoleSeparationEnabled = false

```
- Start IS and try to list users from Console
```
ERROR {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} - Error occurred while retrieving SCIM user information org.wso2.carbon.user.core.UserStoreException: Error occurred while getting hybrid role list of users : [admin, test] in domain: PRIMARY
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:258)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getRoleListOfUsersWithID(AbstractUserStoreManager.java:16275)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getSCIMUsers(SCIMUserManager.java:4055)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getUserDetails(SCIMUserManager.java:925)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsers(SCIMUserManager.java:678)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsersWithGET(SCIMUserManager.java:611)
	at org.wso2.charon3.core.protocol.endpoints.UserResourceManager.listWithGET(UserResourceManager.java:362)
	at org.wso2.carbon.identity.scim2.provider.resources.UserResource.getUser(UserResource.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	...
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while getting hybrid role list of users : [admin, test] in domain: PRIMARY
	at org.wso2.carbon.user.core.hybrid.HybridRoleManager.getHybridRoleListOfUsers(HybridRoleManager.java:871)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetInternalRoleListOfUsersWithID(AbstractUserStoreManager.java:1129)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetRoleListOfUsersWithID(AbstractUserStoreManager.java:16324)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getRoleListOfUsersWithID(AbstractUserStoreManager.java:16287)
	... 69 more
Caused by: java.sql.SQLException: Column Index out of range, 2 > 1.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.result.ResultSetImpl.checkColumnBounds(ResultSetImpl.java:461)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getString(ResultSetImpl.java:835)
	at org.wso2.carbon.user.core.hybrid.HybridRoleManager.getHybridRoleListOfUsers(HybridRoleManager.java:842)
	... 72 more
```

**Expected behavior:**

**Environment information**
 - Product Version: IS 7.0 alpha 2
 - Database: MySQL

**Comment by ShanChathusanda93** [comment]
Hi Team,

This can be reproduced from the default H2 database as well. Please follow the stack trace below.

```
ERROR {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} - Error occurred while retrieving SCIM user information org.wso2.carbon.user.core.UserStoreException: Error occurred while getting hybrid role list of users : [admin] in domain: PRIMARY
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:258)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getRoleListOfUsersWithID(AbstractUserStoreManager.java:16275)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getSCIMUsers(SCIMUserManager.java:4055)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getUserDetails(SCIMUserManager.java:925)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsers(SCIMUserManager.java:678)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsersWithGET(SCIMUserManager.java:611)
	at org.wso2.charon3.core.protocol.endpoints.UserResourceManager.listWithGET(UserResourceManager.java:362)
	at org.wso2.carbon.identity.scim2.provider.resources.UserResource.getUser(UserResource.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:661)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:425)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:357)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:294)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:146)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:115)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:179)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:144)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:239)
	... 62 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:242)
	... 64 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while getting hybrid role list of users : [admin] in domain: PRIMARY
	at org.wso2.carbon.user.core.hybrid.HybridRoleManager.getHybridRoleListOfUsers(HybridRoleManager.java:871)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetInternalRoleListOfUsersWithID(AbstractUserStoreManager.java:1129)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetRoleListOfUsersWithID(AbstractUserStoreManager.java:16324)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getRoleListOfUsersWithID(AbstractUserStoreManager.java:16287)
	... 69 more
Caused by: org.h2.jdbc.JdbcSQLDataException: Invalid value "2" for parameter "columnIndex" [90008-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:658)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:298)
	at org.h2.jdbc.JdbcResultSet.checkColumnIndex(JdbcResultSet.java:3524)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:283)
	at org.wso2.carbon.user.core.hybrid.HybridRoleManager.getHybridRoleListOfUsers(HybridRoleManager.java:842)
	... 72 more
```

**Comment by ShanChathusanda93** [comment]
Closing the issue hense the fix is merged.
