### ISSUE TITLE
User name not mapper correctly from SAML accertion in OIDC app

### ISSUE THREAD

**Issue by lpastor74** [wso2/product-is#17893]
**Describe the issue:**

I wanted to create an IDP init flow 

1. Created IDP init SAML app on Azure 
[image](https://res.cloudinary.com/practicaldev/image/fetch/s--sH0csszC--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_800/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/im16zg4edq56cjuf24y9.png)

2. In sub organization created a connector, setup with Azure SAML app and did the claim mapping 
[image](https://res.cloudinary.com/practicaldev/image/fetch/s--givdQwnp--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_800/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/z9ppewl90y82pzy4l5zl.png)

3. Start the flow with a link and everything works fine.
https://localhost:9443/samlsso?spEntityID=saml2-web-app-pickup-dispatch.com&fidp=OrganizationSSO&org=ORG_C

All claims are mapped correctly. Particularly the user name

http://wso2.org/claims/username to the bilbo@ws.....oft.com

4. Created the OIDC app and chose claims
[image](https://i.ibb.co/5xMHpjX/Screenshot-2023-11-17-at-13-03-55.png)

5. in the profile section NOT select the Username !!!
[image](https://ibb.co/FDY2HD0)

 6. Start the flow with the link and everything works fine.
https://localhost:9443/oauth2/authorize?client_id=q0BLO78BJ5O...&fidp=OrganizationSSO&org=ORG_C&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fpickup-manager%2Foauth2client&response_type=id_token&scope=openid%20email%20profile

but I was not getting the user name (it is expected because the app does not ask for it)!
[image](https://ibb.co/xCJg7Hx)

**How to reproduce:**

5a. in profile **select** the Username !!!
[image](https://ibb.co/T2tTxZw)

6a. Start the flow with the link and I get the error 
https://localhost:9443/oauth2/authorize?client_id=q0BLO78BJ5O...&fidp=OrganizationSSO&org=ORG_C&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fpickup-manager%2Foauth2client&response_type=id_token&scope=openid%20email%20profile

[image](https://ibb.co/fMJGP5B)

Error in Log :

[2023-11-17 14:02:55,384] [58effb8e-b4af-45a3-a23f-7504b5c84ad4] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/authenticationendpoint].[oauth2_consent.do]} - Servlet.service() for servlet [oauth2_consent.do] in context with path [/authenticationendpoint] threw exception [An exception occurred processing [/oauth2_consent.jsp] at line [92]

89:         String[] queryParams = queryString.split("&");
90:         for (String queryParam : queryParams) {
91:             String[] queryParamKeyValueArray = queryParam.split("=", 2);
92:                 queryParamMap.put(queryParamKeyValueArray[0], queryParamKeyValueArray[1]);
93:         }
94:     }
95:

Stacktrace:] with root cause java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.apache.jsp.oauth2_005fconsent_jsp._jspService(oauth2_005fconsent_jsp.java:1297)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.wso2.carbon.tomcat.ext.filter.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.wso2.carbon.identity.application.authentication.endpoint.util.filter.AuthenticationEndpointFilter.doFilter(AuthenticationEndpointFilter.java:190)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.wso2.carbon.identity.application.authentication.endpoint.util.filter.AuthParameterFilter.doFilter(AuthParameterFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:129)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:118)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:115)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:200)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:120)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Expected behavior:**

The expectation was to resolve the user name as in the SAML application.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: ver IS 7
 - OS: Mac
 - Database: Default
 - Userstore: default with ext IDP

**Comment by madurangasiriwardena** [comment]
Hi @lpastor74,

Can you please add the exact steps to reproduce the issue?

**Comment by hasinthaindrajee** [comment]
@madurangasiriwardena if you properly read the error message, it's due to an array index out of bounds issue. Probably this can be due to not having any values in a query parameter. When the consent page is prompted, probably, if there are no claims to be consented this issue may rise. Anyway we can't assume that query parameter may always have a value. 

https://stackoverflow.com/questions/4557387/is-a-url-query-parameter-valid-if-it-has-no-value

**Comment by AnuradhaSK** [comment]
Based on the above comments, I'm rewriting the steps to reproduce the issue.

1. Create an oauth/oidc application in the root tenant.
2. Go to User attributes section of the created application and select "username", "email" as requested attributes 
3. Create an organization and share the application with the new organization.
4. Switch to the organization. 
5. Create a SAML IDP for Azure. Do the attribute mappings (username, email likewise)
6. Connect the created SAML IDP in step 5 to the shared application in the organization.
7. Try the login flow using the following URL
```
https://localhost:9443/oauth2/authorize?client_id=<client-id-of-root-organization's-app>&fidp=OrganizationSSO&org=<created organization name>&redirect_uri=<redirect url of configured in root level application>&response_type=id_token&scope=openid%20email%20profile
```
8. Authenticate the user from Azure SAML IDP

**Comment by lpastor74** [comment]
hi team , any update on this ???

**Comment by sadilchamishka** [comment]
> hi team , any update on this ???

Working on the issue. Will share an update asap.

**Comment by sadilchamishka** [comment]
Hi @lpastor74 

Tried the following setup and did not reproduced the issue.

1 - Created OIDC app, share with organizations.
2 - Select the SP claims of the created OIDC app.
3 - Switch to an organization, created a SAML IDP connection and add to the shared app's login sequence. 
(Please note that, I used another IS running on port 9444 as my federated SAML IDP)
4 - Tried the login flow. The ID token contained all the claims including username claim.

Please share details if the steps are different with steps you tried. Will try to get an azure account for test the exact flow of having Azure AD as a SAML IDP.



Thanks,
Sadil

**Comment by lpastor74** [comment]
I will be more than happy to review the video session and debug it with you ...

https://drive.google.com/file/d/1JsEtlX8-oTZne6LDnn96oNUlkHTPSxej/view?usp=sharing

**Comment by lpastor74** [comment]
I cannot paste the full record , but I can go in meeting with you and we can review it together 
https://drive.google.com/file/d/1JsEtlX8-oTZne6LDnn96oNUlkHTPSxej/view?usp=sharing
