### ISSUE TITLE
PostgreSQL Exception and 500 Console Error When Creating New SubOrg

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#17908]
**Describe the issue:**

facing a PostgreSQL exception and encountering a 500 Console Error when attempting to create a new SubOrg via the console  with PostgreSQL configured as the primary database.

```
[ec31db08-c0bf-4c76-b66e-46cc041c0157] ERROR {org.wso2.carbon.identity.api.server.organization.management.v1.service.OrganizationManagementService} - errorCode: ORG-65090 | message: null org.wso2.carbon.identity.organization.management.service.exception.OrganizationManagementServerException: Error while firing the events
	at org.wso2.carbon.identity.organization.management.ext.OrganizationManagerListenerImpl.fireEvent(OrganizationManagerListenerImpl.java:162)
	at org.wso2.carbon.identity.organization.management.ext.OrganizationManagerListenerImpl.postAddOrganization(OrganizationManagerListenerImpl.java:59)
	at org.wso2.carbon.identity.organization.management.service.OrganizationManagerImpl.addOrganization(OrganizationManagerImpl.java:174)
	at org.wso2.carbon.identity.api.server.organization.management.v1.service.OrganizationManagementService.addOrganization(OrganizationManagementService.java:237)
	at org.wso2.carbon.identity.api.server.organization.management.v1.impl.OrganizationsApiServiceImpl.organizationPost(OrganizationsApiServiceImpl.java:119)
	at org.wso2.carbon.identity.api.server.organization.management.v1.OrganizationsApi.organizationPost(OrganizationsApi.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:661)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:425)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:357)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:294)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:146)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:115)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:179)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:144)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.wso2.carbon.identity.event.IdentityEventException: An error occurred while creating shared applications in the new organization
	at org.wso2.carbon.identity.organization.management.application.listener.OrganizationCreationHandler.handleEvent(OrganizationCreationHandler.java:78)
	at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56)
	at org.wso2.carbon.identity.organization.management.ext.OrganizationManagerListenerImpl.fireEvent(OrganizationManagerListenerImpl.java:156)
	... 60 more
Caused by: org.wso2.carbon.identity.organization.management.service.exception.OrganizationManagementServerException: Unable to link the shared application.
	at org.wso2.carbon.identity.organization.management.service.util.Utils.handleServerException(Utils.java:112)
	at org.wso2.carbon.identity.organization.management.application.dao.impl.OrgApplicationMgtDAOImpl.addSharedApplication(OrgApplicationMgtDAOImpl.java:87)
	at org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl.shareApplication(OrgApplicationManagerImpl.java:628)
	at org.wso2.carbon.identity.organization.management.application.listener.OrganizationCreationHandler.addSharedApplicationsToOrganization(OrganizationCreationHandler.java:154)
	at org.wso2.carbon.identity.organization.management.application.listener.OrganizationCreationHandler.handleEvent(OrganizationCreationHandler.java:76)
	... 62 more
Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.TransactionException: Could not commit the transaction.
	at org.wso2.carbon.database.utils.jdbc.NamedJdbcTemplate.withTransaction(NamedJdbcTemplate.java:105)
	at org.wso2.carbon.identity.organization.management.application.dao.impl.OrgApplicationMgtDAOImpl.addSharedApplication(OrgApplicationMgtDAOImpl.java:75)
	... 65 more
Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s.' INSERT INTO SP_SHARED_APP (MAIN_APP_ID, OWNER_ORG_ID, SHARED_APP_ID, SHARED_ORG_ID, SHARE_WITH_ALL_CHILDREN) VALUES (:MAIN_APP_ID;, :OWNER_ORG_ID;, :SHARED_APP_ID;, :SHARED_ORG_ID;, :SHARE_WITH_ALL_CHILDREN;);
	at org.wso2.carbon.database.utils.jdbc.NamedTemplate.executeInsert(NamedTemplate.java:83)
	at org.wso2.carbon.identity.organization.management.application.dao.impl.OrgApplicationMgtDAOImpl.lambda$addSharedApplication$1(OrgApplicationMgtDAOImpl.java:76)
	at org.wso2.carbon.database.utils.jdbc.NamedJdbcTemplate.withTransaction(NamedJdbcTemplate.java:81)
	... 66 more
Caused by: org.postgresql.util.PSQLException: ERROR: column "share_with_all_children" is of type boolean but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 143
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
	at jdk.internal.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy55.executeUpdate(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.NamedPreparedStatement.executeUpdate(NamedPreparedStatement.java:252)
	at org.wso2.carbon.database.utils.jdbc.NamedTemplate.doInternalUpdate(NamedTemplate.java:246)
	at org.wso2.carbon.database.utils.jdbc.NamedTemplate.executeInsert(NamedTemplate.java:76)
	... 68 more
```
[recording.webm](https://github.com/wso2/product-is/assets/39120228/e417b0ba-3125-464e-b686-a47c7cffd90c)

**How to reproduce:**
Configured Postgres as Primary Database
```
[user_store]
type = "database_unique_id"

[database.identity_db]
type = "postgre"
hostname = "localhost"
name = "beta18nov3"
username = "postgres"
password = "wso2carbon"
port = "5432"

[database.shared_db]
type = "postgre"
hostname = "localhost"
name = "beta18nov3"
username = "postgres"
password = "wso2carbon"
port = "5432"

[database.identity_db.pool_options]
maxActive = "80"
maxWait = "360000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1; COMMIT"
validationInterval="30000"
defaultAutoCommit=false
commitOnReturn=true

[database.shared_db.pool_options]
maxActive = "80"
maxWait = "360000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1; COMMIT"
validationInterval="30000"
defaultAutoCommit=false
commitOnReturn=true
```
Note: refer this to configured Database : https://docs.google.com/document/d/1903kgPx5Q9uOzMM1VSkfE2YJ9NjcWSopfOYPnljvpSk/edit
Log in to the console.
Navigate to the Organization Creation section.
Attempt to create a new SubOrg.
Observe the PostgreSQL exception and the 500 Console Error.

**Expected behavior:**
Creating a new SubOrg via the console with PostgreSQL as the primary database should proceed without PostgreSQL exceptions, and the console should not return a 500 error.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 7.0 Beta snapshot
 - OS: Mac
 - Database:Postgress
 - Userstore:JDBC

---

**Comment by dewniMW** [comment]
The issue with share_with_all_children column is fixed
