### ISSUE TITLE
Error in Adding Administrator Role at First Startup with MySQL

### ISSUE THREAD

**Issue by PasinduYeshan** [wso2/product-is#17976]
**Describe the issue:**
Encountered an error while initializing IS for the first time with MySQL as the database. The startup process fails when trying to add the Administrator role for the console, resulting in an IdentityApplicationManagementException.

Error Details:
The following error is observed:

```
ERROR {org.wso2.identity.apps.common.internal.AppsCommonServiceComponent} - Failed to activate identity apps common service component. org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Failed to add Administrator role for the console
at org.wso2.identity.apps.common.util.AppPortalUtils.addAdministratorRole(AppPortalUtils.java:395)
at org.wso2.identity.apps.common.util.AppPortalUtils.shareApplication(AppPortalUtils.java:376)
at org.wso2.identity.apps.common.util.AppPortalUtils.createApplication(AppPortalUtils.java:229)
at org.wso2.identity.apps.common.util.AppPortalUtils.initiatePortals(AppPortalUtils.java:302)
at org.wso2.identity.apps.common.util.AppPortalUtils.initiatePortals(AppPortalUtils.java:252)
at org.wso2.identity.apps.common.internal.AppsCommonServiceComponent.activate(AppsCommonServiceComponent.java:86)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
...
at org.wso2.carbon.identity.organization.management.application.internal.OrgApplicationMgtServiceComponent.activate(OrgApplicationMgtServiceComponent.java:74)
...
at org.wso2.carbon.identity.application.authentication.framework.internal.FrameworkServiceComponent.activate(FrameworkServiceComponent.java:362)
...
at org.wso2.carbon.identity.role.mgt.core.internal.RoleManagementServiceComponent.activate(RoleManagementServiceComponent.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
Caused by: org.wso2.carbon.identity.role.v2.mgt.core.exception.IdentityRoleManagementClientException: Application: d2ffe5c9-5d2d-451f-b98e-f3bd895a197f does not have Application role audience type
at org.wso2.carbon.identity.application.mgt.listener.DefaultRoleManagementListener.validateApplicationRoleAudience(DefaultRoleManagementListener.java:489)
at org.wso2.carbon.identity.application.mgt.listener.DefaultRoleManagementListener.preAddRole(DefaultRoleManagementListener.java:85)
at org.wso2.carbon.identity.role.v2.mgt.core.RoleManagementServiceImpl.addRole(RoleManagementServiceImpl.java:93)
at org.wso2.identity.apps.common.util.AppPortalUtils.addAdministratorRole(AppPortalUtils.java:391)
... 232 more
```

**How to reproduce:**
- Download and set up the WSO2 IS Pack.
- Configure the database to use MySQL.
- Launch the WSO2 IS Pack.

**Expected behavior:**
- The WSO2 IS should start without any errors, and the Administrator role for the console should be successfully added.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: MySQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by PasinduYeshan** [comment]
This issue is fixed with following PR.
- https://github.com/wso2/carbon-identity-framework/pull/5193
