### ISSUE TITLE
Server startup time  issue DB: Mysql : Failed to add Administrator role for the console

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18052]
**Describe the issue:**
Server startup issue Mysql DB at server startup time. DB: Mysql

Getting issue 

```
Caused by: org.wso2.carbon.identity.role.v2.mgt.core.exception.IdentityRoleManagementClientException: Application: 37a61ea9-e6c8-4938-a0c5-c000bc2b594f does not have Application role audience type
	at org.wso2.carbon.identity.application.mgt.listener.DefaultRoleManagementListener.validateApplicationRoleAudience(DefaultRoleManagementListener.java:489)
	at org.wso2.carbon.identity.application.mgt.listener.DefaultRoleManagementListener.preAddRole(DefaultRoleManagementListener.java:85)
	at org.wso2.carbon.identity.role.v2.mgt.core.RoleManagementServiceImpl.addRole(RoleManagementServiceImpl.java:93)
	at org.wso2.identity.apps.common.util.AppPortalUtils.addAdministratorRole(AppPortalUtils.java:391)
	... 232 more
```

**How to reproduce:**
1. Setup mysql
2. Start the server

**Expected behavior:**
No exception should come at serve startup time

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta2-SNAPSHOT - jenkin build: 4944
 - OS: [e.g., Windows, Linux, Mac]
 - Database: MYSQL
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by madurangasiriwardena** [comment]
Could not observe this error in the latest distribution.
