### ISSUE TITLE
[Bug] User must notfiy to update there email in user profile when using TOTP

### ISSUE THREAD

**Issue by Chankami** [wso2/product-is#1828]
**Environment**
IS 5.4.0

**Steps**
When Enable TOTP according [1]  set 1 step as Basic and step  2 as TOTP 
Create a new user and update user information without email.
Login , give Username and Password  for basic authenticator and redirect  to TOTP page.

**Issue**
As the email is not update in user profile user is not receiving email.  In the back-end below cane be seen. 
But end user should notify that email is not set to send the verification code 

```
[2017-12-20 15:04:18,546] ERROR {org.wso2.carbon.identity.mgt.mail.DefaultEmailSendingModule} -  Failed Sending Email
org.apache.axis2.AxisFault: Error generating mail message
	at org.apache.axis2.transport.base.AbstractTransportSender.handleException(AbstractTransportSender.java:226)
	at org.apache.axis2.transport.mail.MailTransportSender.sendMessage(MailTransportSender.java:184)
	at org.apache.axis2.transport.base.AbstractTransportSender.invoke(AbstractTransportSender.java:112)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:297)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:511)
	at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:488)
	at org.wso2.carbon.identity.mgt.mail.DefaultEmailSendingModule.sendEmail(DefaultEmailSendingModule.java:116)
	at org.wso2.carbon.identity.mgt.mail.AbstractEmailSendingModule.notifyUser(AbstractEmailSendingModule.java:59)
	at org.wso2.carbon.identity.mgt.NotificationSendingModule.run(NotificationSendingModule.java:33)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.axis2.AxisFault: Error creating mail message or sending it to the configured server
	at org.apache.axis2.transport.base.AbstractTransportSender.handleException(AbstractTransportSender.java:226)
	at org.apache.axis2.transport.mail.MailTransportSender.sendMail(MailTransportSender.java:505)
	at org.apache.axis2.transport.mail.MailTransportSender.sendMessage(MailTransportSender.java:175)
	... 14 more
Caused by: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
	com.sun.mail.smtp.SMTPAddressFailedException: 553 5.1.2 The recipient address <null> is not a valid RFC-5321 address. j14sm37081718pfj.93 - gsmtp

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1196)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:584)
	at javax.mail.Transport.send0(Transport.java:169)
	at javax.mail.Transport.send(Transport.java:98)
	at org.apache.axis2.transport.mail.MailTransportSender.sendMail(MailTransportSender.java:494)
	... 15 more
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 553 5.1.2 The recipient address <null> is not a valid RFC-5321 address. j14sm37081718pfj.93 - gsmtp

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1047)
	... 19 more
```

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
