### ISSUE TITLE
[DB2] Error Navigating to "Email Templates" Page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#18333]
**Describe the issue:**
encountering an issue when attempting to navigate to the "Email Templates" page with DB2 as the primary database. 

**How to reproduce:**

1. Configure DB2 as the primary database.
2. Log in to the  console.
3. Navigate to the "Email Templates" section.

**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 Product Version: wso2is-7.0.0-rc1-SNAPSHOT
OS:Mac
Database: DB2
Userstore: JDBC

<img width="1728" alt="Screenshot 2023-12-02 at 18 39 00" src="https://github.com/wso2/product-is/assets/39120228/1aebdd4c-1d00-4d7a-b834-821d4039a5c5">

```
[25043b95-f258-402a-9958-71421971ac9c] ERROR {org.wso2.carbon.identity.api.server.branding.preference.management.v1.core.BrandingPreferenceManagementService} - errorCode: BPM-65005 | message: Error while retrieving custom text preference configurations for organization: %s. org.wso2.carbon.identity.branding.preference.management.core.exception.BrandingPreferenceMgtServerException: Error while getting custom text preference configurations for tenant: carbon.super.
	at org.wso2.carbon.identity.branding.preference.management.core.util.BrandingPreferenceMgtUtils.handleServerException(BrandingPreferenceMgtUtils.java:107)
	at org.wso2.carbon.identity.branding.preference.management.core.BrandingPreferenceManagerImpl.getCustomText(BrandingPreferenceManagerImpl.java:307)
	at org.wso2.carbon.identity.api.server.branding.preference.management.v1.core.BrandingPreferenceManagementService.getCustomTextPreference(BrandingPreferenceManagementService.java:352)
	at org.wso2.carbon.identity.api.server.branding.preference.management.v1.impl.BrandingPreferenceApiServiceImpl.getCustomText(BrandingPreferenceApiServiceImpl.java:201)
	at org.wso2.carbon.identity.api.server.branding.preference.management.v1.BrandingPreferenceApi.getCustomText(BrandingPreferenceApi.java:187)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:661)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:425)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:357)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:294)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:147)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:123)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:204)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:120)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.wso2.carbon.identity.configuration.mgt.core.exception.ConfigurationManagementServerException: Error while retrieving the file: 6e15f2e0-952f-42c3-a490-bdc2d2bcc25d.
	at org.wso2.carbon.identity.configuration.mgt.core.util.ConfigurationUtils.handleServerException(ConfigurationUtils.java:105)
	at org.wso2.carbon.identity.configuration.mgt.core.dao.impl.ConfigurationDAOImpl.getFileById(ConfigurationDAOImpl.java:1439)
	at org.wso2.carbon.identity.configuration.mgt.core.dao.impl.CachedBackedConfigurationDAO.getFileById(CachedBackedConfigurationDAO.java:236)
	at org.wso2.carbon.identity.configuration.mgt.core.ConfigurationManagerImpl.getFileById(ConfigurationManagerImpl.java:967)
	at org.wso2.carbon.identity.branding.preference.management.core.BrandingPreferenceManagerImpl.getCustomText(BrandingPreferenceManagerImpl.java:292)
	... 58 more
Caused by: com.ibm.db2.jcc.am.SqlException: [jcc][10120][11936][4.26.14] Invalid operation: Lob is closed. ERRORCODE=-4470, SQLSTATE=null
	at com.ibm.db2.jcc.am.b7.a(b7.java:794)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:107)
	at com.ibm.db2.jcc.am.c6.c(c6.java:67)
	at com.ibm.db2.jcc.am.c7.v(c7.java:204)
	at com.ibm.db2.jcc.am.c7.getBinaryStream(c7.java:108)
	at org.wso2.carbon.identity.configuration.mgt.core.dao.impl.ConfigurationDAOImpl.getFileById(ConfigurationDAOImpl.java:1437)
	... 61 more
```

**Comment by ZiyamSanthosh** [comment]
This is not reproducible using the DB2 database

https://github.com/wso2/product-is/assets/50801227/d4389b61-87fb-497a-8fe8-b0071312540f

**Comment by ZiyamSanthosh** [comment]
Communicated to @NilukaSripalim. Hence closing the issue.
