### ISSUE TITLE
Application unsharing failed when b2b application is bind to the everyone organization role

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#18390]
**Describe the issue:**

<img width="689" alt="Screenshot 2023-12-04 at 10 16 08" src="https://github.com/wso2/product-is/assets/35717390/3eff72b6-f46b-40db-9dd1-68034476e368">

```
[2023-12-04 10:11:09,146] [8902ddcb-e7bb-424b-b822-acd9e9a132af] ERROR {org.wso2.carbon.identity.api.server.organization.management.v1.service.OrganizationManagementService} - errorCode: ORG-65080 | message: Server encountered an error when removing fragment app: db708c98-a3dd-442f-a7f4-41800acc3675 in organization: 5f39c270-62c8-4830-a38e-ba9462904f95. org.wso2.carbon.identity.organization.management.service.exception.OrganizationManagementServerException: Unable to remove the fragment application
	at org.wso2.carbon.identity.organization.management.service.util.Utils.handleServerException(Utils.java:112)
	at org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl.deleteSharedApplication(OrgApplicationManagerImpl.java:326)
	at org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl.deleteSharedApplication(OrgApplicationManagerImpl.java:254)
	at org.wso2.carbon.identity.api.server.organization.management.v1.service.OrganizationManagementService.deleteAllSharedApplications(OrganizationManagementService.java:320)
	at org.wso2.carbon.identity.api.server.organization.management.v1.impl.OrganizationsApiServiceImpl.sharedApplicationsAllDelete(OrganizationsApiServiceImpl.java:147)
	at org.wso2.carbon.identity.api.server.organization.management.v1.OrganizationsApi.sharedApplicationsAllDelete(OrganizationsApi.java:512)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doDelete(AbstractHTTPServlet.java:228)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:561)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:661)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:425)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:357)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:294)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:147)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:123)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:179)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:144)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error while deleting organization roles associated to the app.
	at org.wso2.carbon.identity.organization.management.handler.listener.SharedRoleMgtListener.doPreDeleteApplication(SharedRoleMgtListener.java:449)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.deleteApplication(ApplicationManagementServiceImpl.java:783)
	at org.wso2.carbon.identity.organization.management.application.OrgApplicationManagerImpl.deleteSharedApplication(OrgApplicationManagerImpl.java:320)
	... 59 more
Caused by: org.wso2.carbon.identity.role.v2.mgt.core.exception.IdentityRoleManagementClientException: Invalid operation. Role: everyone Cannot be deleted.
	at org.wso2.carbon.identity.role.v2.mgt.core.dao.RoleDAOImpl.deleteRole(RoleDAOImpl.java:544)
	at org.wso2.carbon.identity.role.v2.mgt.core.RoleManagementServiceImpl.deleteRole(RoleManagementServiceImpl.java:297)
	at org.wso2.carbon.identity.organization.management.handler.listener.SharedRoleMgtListener.handleOrganizationAudiencedSharedRoleDeletion(SharedRoleMgtListener.java:493)
	at org.wso2.carbon.identity.organization.management.handler.listener.SharedRoleMgtListener.doPreDeleteApplication(SharedRoleMgtListener.java:446)
	... 61 more
```

**How to reproduce:**

1 - Create app and share with all orgs.
2 - Change the organization as the role audience.
3 - Set the everyone role for the app.
4 - Try unshare with all orgs.

**Expected behavior:**

Application unsharing should be successfull with all the shared roles getting deleted.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 7.0.0-beta2]
 - OS: [Mac]
 - Database: [H2]
 - Userstore: [JDBC]

**Comment by sadilchamishka** [comment]
Handling `system` and `everyone` role when application unsharing can be done by the role sharing listeners. The raised PR should be closed and another PR should be raised.
