### ISSUE TITLE
[OracleDB] Error when retriving  connected application on created  connection

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#18630]
**Describe the issue:**
[OracleDB] Error when retrieving  created  connection.

![Screenshot from 2023-12-15 17-13-32](https://github.com/wso2/product-is/assets/39077751/1613cf8e-a7c4-4569-9ec0-62ab527ed5c9)

[Screencast from 2023-12-15 17_12_01.webm](https://github.com/wso2/product-is/assets/39077751/2a9262b0-15ba-44ef-ad99-173c5fdb890e)

```
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: Error : 907, Position : 580, SQL = SELECT UUID FROM (SELECT UUID, ROWNUM AS RNUM FROM ( SELECT UUID FROM (SP_AUTH_STEP INNER JOIN SP_FEDERATED_IDP ON [SP_AUTH_STEP.ID](http://sp_auth_step.id/) = [SP_FEDERATED_IDP.ID](http://sp_federated_idp.id/)) INNER JOIN SP_APP ON SP_AUTH_STEP.APP_ID = [SP_APP.ID](http://sp_app.id/) WHERE AUTHENTICATOR_ID IN ( SELECT ID FROM IDP_AUTHENTICATOR WHERE IDP_ID = ( SELECT ID FROM IDP WHERE UUID = :1 )) UNION (SELECT SP_APP.UUID FROM SP_PROVISIONING_CONNECTOR INNER JOIN SP_APP ON  SP_PROVISIONING_CONNECTOR.APP_ID = [SP_APP.ID](http://sp_app.id/) WHERE SP_APP.TENANT_ID = (SELECT TENANT_ID FROM IDP WHERE IDP.UUID = :2 AND IDP_NAME = (SELECT NAME FROM IDP WHERE IDP.UUID = :3 ))) WHERE ROWNUM <= :4 ) WHERE RNUM > :5 , Original SQL = SELECT UUID FROM (SELECT UUID, ROWNUM AS RNUM FROM ( SELECT UUID FROM (SP_AUTH_STEP INNER JOIN SP_FEDERATED_IDP ON [SP_AUTH_STEP.ID](http://sp_auth_step.id/) = [SP_FEDERATED_IDP.ID](http://sp_federated_idp.id/)) INNER JOIN SP_APP ON SP_AUTH_STEP.APP_ID = [SP_APP.ID](http://sp_app.id/) WHERE AUTHENTICATOR_ID IN ( SELECT ID FROM IDP_AUTHENTICATOR WHERE IDP_ID = ( SELECT ID FROM IDP WHERE UUID = ?)) UNION (SELECT SP_APP.UUID FROM SP_PROVISIONING_CONNECTOR INNER JOIN SP_APP ON  SP_PROVISIONING_CONNECTOR.APP_ID = [SP_APP.ID](http://sp_app.id/) WHERE SP_APP.TENANT_ID = (SELECT TENANT_ID FROM IDP WHERE IDP.UUID = ? AND IDP_NAME = (SELECT NAME FROM IDP WHERE IDP.UUID = ?))) WHERE ROWNUM <= ?) WHERE RNUM > ?, Error Message = ORA-00907: missing right parenthesis
```

**How to reproduce:**
1. Login to console (tenanted path)
2. Create connection (google)
3. Navigate to the edit of created connection
4. Disable created connection or navigate to the connected application tab 

**Expected behavior:**
No issues should be appear.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [e.g., IS 5.10.0, IS 5.9.0]
 - OS: [e.g., Windows, Linux, Mac]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by sahandilshan** [comment]
This will be fixed with https://github.com/wso2/carbon-identity-framework/pull/5327
