### ISSUE TITLE
SCIM PATCH removing a secondary userstore user from an internal role using the user Id fails

### ISSUE THREAD

**Issue by pabasara-mahindapala** [wso2/product-is#18773]
**Describe the issue:**
When trying to remove a secondary userstore user from an internal role using the user Id as explained here [1] with SCIM PATCH, following error response is received.

**How to reproduce:**
Request:
```
curl --location --request PATCH 'https://localhost:9443/scim2/Roles/4a464c4f-6ccd-4c95-ad74-0696c1ed933f' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Content-Type: application/json' \
--data '{
    "Operations": [
        {
            "op": "remove",
            "path": "users[value eq 4ce281d2-db7b-4a04-89f7-558bde569a46]"
        }
    ],
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:PatchOp"
    ]
}'
```

Response:
```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "detail": "Error occurred while getting the user id of the user: bob",
    "status": "500"
}
```

Following error stack can be observed.

```
[2023-12-29 20:36:23,980] [b75f223a-460e-49ae-bb7a-c2e60c6b120d] ERROR {org.wso2.charon3.core.protocol.endpoints.AbstractResourceManager} - Error occurred while getting the user id of the user: bob org.wso2.charon3.core.exceptions.CharonException: Error occurred while getting the user id of the user: bob
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManager.getUserIDList(SCIMRoleManager.java:867)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManager.doUpdateUsers(SCIMRoleManager.java:692)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManager.updateUsers(SCIMRoleManager.java:629)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManager.patchRole(SCIMRoleManager.java:597)
	at org.wso2.charon3.core.protocol.endpoints.RoleResourceManager.updateWithPatchOperations(RoleResourceManager.java:613)
	at org.wso2.charon3.core.protocol.endpoints.RoleResourceManager.updateWithPATCHRole(RoleResourceManager.java:385)
	at org.wso2.carbon.identity.scim2.provider.resources.RoleResource.patchRole(RoleResource.java:293)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:281)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:596)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:115)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:154)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:142)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:114)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:75)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.wso2.carbon.identity.role.mgt.core.IdentityRoleManagementClientException: A user doesn't exist with name: bob in the tenantDomain: carbon.super
	at org.wso2.carbon.identity.role.mgt.core.util.UserIDResolver.getIDByName(UserIDResolver.java:80)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManager.getUserIDByName(SCIMRoleManager.java:898)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManager.getUserIDList(SCIMRoleManager.java:865)
	... 66 more
```

**Expected behavior:**
Removing a secondary userstore user from an internal role using the user Id in SCIM PATCH should work.

**Environment information:**
 - Product Version: IS 6.1.0
 - OS: Mac
 - Database: H2
 - Userstore: LDAP

This appears to be caused since the userstore domain for the user is not correctly appended at [2] when the user Id is used in the request. This issue applies to the scim2/Groups endpoint as well.

[1] https://is.docs.wso2.com/en/latest/apis/scim2-patch-operations/#remove-users
[2] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/ab99a4d2be6c95175176ad17a991ed9c02e976db/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMRoleManager.java#L796

**Comment by piraveena** [comment]
This is already fixed in master
