### ISSUE TITLE
ID Token Decryption failing 

### ISSUE THREAD

**Issue by DimuthuKasunWP** [wso2/product-is#18783]
When trying the logout[1]  flow of an oauth/openid application, if the id token encryption is enabled[2]  the logout flow is failing with the below error.

```
TID: [-1234] [] [2023-12-21 15:23:53,709] [0ce93c31-1eeb-461e-8538-e42e1af8c440] ERROR {org.wso2.carbon.identity.oidc.session.servlet.OIDCLogoutServlet} - Error occurred while getting oauth application information. org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: Error occurred while decrypting the JWE.
	at org.wso2.carbon.identity.oidc.session.util.OIDCSessionManagementUtil.decryptWithRSA(OIDCSessionManagementUtil.java:420)
	at org.wso2.carbon.identity.oidc.session.servlet.OIDCLogoutServlet.getOpenIDConnectSkipUserConsent(OIDCLogoutServlet.java:856)
	at org.wso2.carbon.identity.oidc.session.servlet.OIDCLogoutServlet.doGet(OIDCLogoutServlet.java:202)
	at org.wso2.carbon.identity.oidc.session.servlet.OIDCLogoutServlet.doPost(OIDCLogoutServlet.java:630)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:72)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:115)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:77)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:167)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:118)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:114)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:75)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.nimbusds.jose.JOSEException: Decryption error
	at com.nimbusds.jose.crypto.impl.RSA_OAEP.decryptCEK(RSA_OAEP.java:112)
	at com.nimbusds.jose.crypto.RSADecrypter.decrypt(RSADecrypter.java:274)
	at com.nimbusds.jose.JWEObject.decrypt(JWEObject.java:415)
	at org.wso2.carbon.identity.oidc.session.util.OIDCSessionManagementUtil.decryptWithRSA(OIDCSessionManagementUtil.java:417)
	... 55 more
Caused by: javax.crypto.BadPaddingException: Decryption error
	at java.base/sun.security.rsa.RSAPadding.unpadOAEP(RSAPadding.java:488)
	at java.base/sun.security.rsa.RSAPadding.unpad(RSAPadding.java:284)
	at java.base/com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:372)
	at java.base/com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:406)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2205)
	at com.nimbusds.jose.crypto.impl.RSA_OAEP.decryptCEK(RSA_OAEP.java:104)
	... 58 more

```

How to reproduce 

1. Enable ID token encryption for a service provider and configure service provider certificate
2. Login to a sample application and get an ID token by exchanging the authorization code. You will get a encrypted ID token.
3. Initiate the logout flow  like below with the encrypted id token as the `id_token_hint`.
4. Observe the above error.

```
https://localhost:9443/oidc/logout?id_token_hint=eyJraWQiOiJaR1V6TnpCa00yTTJNRFU0WVRVME1EQXdORFkzWXprME5UaGtNR1l6TXpsbE1XSXhZbUUxWldJNVl6azBaakkwTVdFeU9HTXlOamczTWpCa1l6QTNOUSIsImN0eSI6IkpXVCIsImVuYyI6IkExMjhDQkMrSFMyNTYiLCJhbGciOiJSU0EtT0FFUCJ9.CJSa46NIL3jTxBbQqHzUL1vxq74OmkmDSQKUhgNaaHiRP5RKkPHOa1ja2mD6preY2WBQKODXeEyXz1uaDyr7fLxhXxVmIPquxCFlwiMybt1QHNMW6ItU2JYhv7qRuyzr7xVX3aZhdtlzBD1G5CAFBq4gduhLtRORqIPTG-VVKZt47KmAb8PRYd8LonLOIFkMWtD1R-KxLgHZFF4WUDGjxqFJm0Snn5DzYdX4nRkWGnUzkbl0lFqs1y_CN4folZBKNANNggtfvKc4UFMu145fbjqguvFdJ6yGQoB8dWeshG4pohRJ4DRs4OmNgrVRwGqGx9C3MUUKImQXWcfB0L4-9g.TkOJJHJ0-wwtaEBT9djKfA.EuYUV1czTzHuVx8Y4tIvTRKnuFpE979ffEbJf3f57dKDVASWDJFm3WkHIcdE_FKgVhgwBguE5xaO7jfxeJPr_u_AlVUSutrGZAqNKRTWzmFM1qE-qIFn8WbKweet59HN2__knb1dB4tckT5wqf7lz6-ax0DlKG-jCZJjwfmF9GrLiIkdqMg_4-qsetAccdEEoy2n-Gh__ZowiCJCDhMMqC8mD9iHD3zexqDGlFr90mXJg_TcMdZBa_dibsFI__U_isZ1van4xe7vS9n2IwUYJpIKsc-nxgaElZeoNwBkMuNNLWQzNtuplc0hNy3HLnVn8aYPigivzNgRujIgxszuuuLDGEoTTOqv21uKHXwOxoq4S8gpm-RWmkkJS5JsNkZQ7QQisEIul4_uPhSQ2yOEYpshQKwi6jDecev0-NxcnsYqYEfT0xLbXkRzRRnLe2jPIA3QPLkbupVvyw5iiN2rs013WEFaUMfKZQySWt2lOEMNWF48Ia_W3sABw8G_o5GFeGb00piFU8p79weIF7WF-lVwOL90PsMI1_ypmdajg1swxEchxQ244-9urXqZ_hZaAyaSIhpBJIAUu8nKqgDw3rb2Zh3DfUWW-LWQwfmbgEXORZ1htukjWorrYtcc-JAAC5WgTJ_Qw4-ySCT-qW_R9Wa66UA2An7mH-yWuUXrz-TaQRLGuQI6dT6Hs2JuC2IZWxNVf7wnEN0E8GkOUukVN9MOfsN-dLtAvkfdVkh8WjNbIfprAxNyt0MEGMqpsxZNZNG3jtgDnR1rF-jo_ZTJb3-ViiLnG4tBbgmPHUVbHEFMRq1ukf6lmn4UopH3jkCyAOX9HqqCdYGQLqQPwIU3GJu3J51MHjoKsbi9ygoJylDyCrnpZ7Vh6mmGs0mWnfBZcK1WnuNaoG17SmKgkvSrvAeVGh_tGXb5UEv34lwqkbS88bIJMb3woH8orZxnYCogqdrc8KhfSAbndeMaDqFBrVIaMuyslZKmklgL4J_weXEV5vbsAM-1Gbwnod3Yv2XY3n1aZttmWP0UjrpK6NK-fJtan10Ji6ytDL_aXU5_77Q4q07yMw0fSeCDYNBR7ALbCBwYWJbQntO_CoNGS8RPM0RD8CSv2bOXlEZAyowa-Q75xy3yc29OFPrdsn4sqvVofGe-jgBoft9GKMWT-jwQAgTDmS0GSzKQ19la6V8FO2he6NApntc4ZOKtlq-nAdO5axJZ93OAoU_TpQuNeWBBM0k3a_Xqh_VlcfFx_7nQIPKXYEhc72-90LJFwcunvOBJ4PS-h1t66MniAsGX5mqlWLaJyPt2hgp1-zTA_dysUcYB_Ky2UT3WlaZQWixOQNSGXja_pQFB4gWIhc1V_76BYsM4p4BDS7vUpd2mZMcJb12N5gGuD1V6Ma4aM59wDF2BopFxjTj9M0erImxpCav0aV0wLFNjOckvbZXO78gsZFxMAnn3eSGlOxMUv7f4Ws7njxROb5O_6byq3bzaAcoJmps3j2gI8TDtUZfQtt7C1mDz51s18ZrwntGsUzh1kfxhGlIJ5mZI--5nbsYUyPtoAr_g35EAzkO3iT5BrH_GeXLjm6EGILUnvNAMcyQW9-u1LTi9YEQYUCdAPE8_VIrn1MI6YwPqvWW3sgNg6b0nf61j4dYzchLKP2ALFmXcxV-uXuxGngevGBMVLXq9T9iRyc-Pqrer7U1LYmJFLwdd31Q.x4ybXtTCfYGRTr40tkqwUWeGLwXwvf8B2Zmz-ExFttI&post_logout_redirect_uri=http://localhost:8080/playground2/oauth2client&tenant_domain=carbon.super
```

[1]https://is.docs.wso2.com/en/latest/guides/login/oidc-logout-url-redirection/#send-a-get-logout-request
[2]https://is.docs.wso2.com/en/latest/guides/login/oidc-token-encryption/#:~:text=Once%20you%20enable%20id_token%20encryption,key%20of%20the%20service%20provider.

**Comment by piraveena** [comment]
When the application uses the encrypted id tokens in the logout flow, the app can't share its key pairs with IS to decrypt the token, the expectation in the logout flow is to 
1. decrypt the encrypted id_token by app's private key.
2. Now it is a plain id_token
3. Again encrypt the id_token by the IS public certificate 
4. Send it to IS as id_token_hint in the logout token. 
5. Then IS can decrypt it by it's own private key. An app can't share it's own key pairs with IS. 

You can check this https://github.com/wso2/product-is/issues/8676 issue for further details.  There is a open doc issue https://github.com/wso2/docs-is/issues/1926 to fix this in doc side

**Comment by DimuthuKasunWP** [comment]
Hi @piraveena ,

I believe your concern is true because identity server doesn't have the applicaiton private key.
The suggested approach would be correct.

**Comment by piraveena** [comment]
Closing this issue as this is not a product bug
