### ISSUE TITLE
Missing Character Count and Disallowed Characters Validation in Console Admin Role Input

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#19051]
**Describe the issue:**
Enhancements are needed for the console administrator role input field. Currently, character count validation is missing, and there is no validation for disallowed characters. 

https://github.com/wso2/product-is/assets/39077751/39b6fd29-4dea-4cad-afea-de84d96614e0

**How to reproduce:**

No validation for disallowed characters

1. Login to console 
2. Navigate to console setting 
3. Select Role
4. Add create
5. Add name with special characters 
6. Add permission
7. Click Add 

 Character count validation is missing

1. Login to console 
2. Navigate to console setting 
3. Select Role
4. Add create
5. Add more than 255 character set
6. Add permission
7. Click Add 

```
[2024-01-22 05:17:53,089] [3f8ddec4-6c00-41ea-b52e-062812522ec1] ERROR {org.wso2.charon3.core.protocol.endpoints.AbstractResourceManager} - Error occurred while adding a new role: 847548974848()&(*^$%^#$dw,jbfdekjhvbfejhbvefigerbuyferygfertuerteyrutyieurhiuewhriuwehr3784ry87436538756348756348756438756834756347856347856437547365bc3uyrcdhcjwdwjhcbfhdjfghefvhdsfvdghfvdgvhgdfdvuhfgjshgdjsh%#@$@$#@#$%E^%*&^(*&)(&)(*)(&(*&(*^*&%^$#%$@#%$erhfiuerhfiuerfgiergerbehubehubeirfbeyrufg3eyrgeuwygruywegruywe org.wso2.charon3.core.exceptions.CharonException: Error occurred while adding a new role: 847548974848()&(*^$%^#$dw,jbfdekjhvbfejhbvefigerbuyferygfertuerteyrutyieurhiuewhriuwehr3784ry87436538756348756348756438756834756347856347856437547365bc3uyrcdhcjwdwjhcbfhdjfghefvhdsfvdghfvdgvhgdfdvuhfgjshgdjsh%#@$@$#@#$%E^%*&^(*&)(&)(*)(&(*&(*^*&%^$#%$@#%$erhfiuerhfiuerfgiergerbehubehubeirfbeyrufg3eyrgeuwygruywegruywe
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManagerV2.createRole(SCIMRoleManagerV2.java:187)
	at org.wso2.charon3.core.protocol.endpoints.RoleResourceV2Manager.createRole(RoleResourceV2Manager.java:123)
	at org.wso2.carbon.identity.scim2.provider.resources.RoleResourceV2.createRole(RoleResourceV2.java:134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:661)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:425)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:357)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:294)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:147)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:123)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:180)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:144)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.wso2.carbon.extension.identity.x509Certificate.valve.X509CertificateAuthenticationValve.invoke(X509CertificateAuthenticationValve.java:59)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.wso2.carbon.identity.role.v2.mgt.core.exception.IdentityRoleManagementServerException: Error while creating the role: 847548974848()&(*^$%^#$dw,jbfdekjhvbfejhbvefigerbuyferygfertuerteyrutyieurhiuewhriuwehr3784ry87436538756348756348756438756834756347856347856437547365bc3uyrcdhcjwdwjhcbfhdjfghefvhdsfvdghfvdgvhgdfdvuhfgjshgdjsh%#@$@$#@#$%E^%*&^(*&)(&)(*)(&(*&(*^*&%^$#%$@#%$erhfiuerhfiuerfgiergerbehubehubeirfbeyrufg3eyrgeuwygruywegruywe in the tenantDomain: test.com
	at org.wso2.carbon.identity.role.v2.mgt.core.dao.RoleDAOImpl.addRole(RoleDAOImpl.java:272)
	at org.wso2.carbon.identity.role.v2.mgt.core.RoleManagementServiceImpl.addRole(RoleManagementServiceImpl.java:122)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMRoleManagerV2.createRole(SCIMRoleManagerV2.java:164)
	... 58 more
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2712)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2400)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:367)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:507)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
	at jdk.internal.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at jdk.proxy6/jdk.proxy6.$Proxy49.executeUpdate(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.NamedPreparedStatement.executeUpdate(NamedPreparedStatement.java:266)
	at org.wso2.carbon.identity.role.v2.mgt.core.dao.RoleDAOImpl.addRole(RoleDAOImpl.java:234)
	... 60 more
```

**Expected behavior:**
To address this, it is necessary to improve the input field by incorporating the following validations:

Implement validation for both maximum and minimum character lengths in the input field.
Restrict the use of disallowed characters in the input field."

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0-beta6 - 
 - OS: [e.g., Windows, Linux, Mac]
 - Database: Postgres
 - Userstore: [e.g., LDAP, JDBC]

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/19052

**Suggested labels:**

**Comment by pavinduLakshan** [comment]
This issue will be addressed with https://github.com/wso2/product-is/issues/19052, hence closing.
