### ISSUE TITLE
Email OTP as second factor fails when FIDO is used in first step

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#19268]
**Describe the issue:**
When FIDO in the first step and EmailOTP in the second step are used, Email OTP authenticator fails while trying to publishPostEmailOTPGeneratedEvent since getAuthenticatedSubjectIdentifier from authenticatedUser at [[1]](https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/b614696228b74da100694b1cfd91a3a692ca6ab3/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L2681) returns null. It is because the authenticatedUser is built at [[2]](https://github.com/wso2-extensions/identity-local-auth-fido/blob/48cd7fd7e981b7f8eecfed2707a56b3cca9cad66/components/org.wso2.carbon.identity.application.authenticator.fido2/src/main/java/org/wso2/carbon/identity/application/authenticator/fido2/core/WebAuthnService.java#L640-L643) does not set a value for AuthenticatedSubjectIdentifier.

This can be fixed by porting the PR https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/166.

**How to reproduce:**
- Configure an SP with FIDO in the first step and EmailOTP in the second step
- Register a FIDO device from MyAccount
- Try to login to the above SP
- The following error is thrown once you complete the first step
```
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework java.lang.NullPointerException
	at org.wso2.carbon.utils.multitenancy.MultitenantUtils.getTenantDomain(MultitenantUtils.java:90)
	at org.wso2.carbon.extension.identity.helper.FederatedAuthenticatorUtil.isUserExistInUserStore(FederatedAuthenticatorUtil.java:116)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.publishPostEmailOTPGeneratedEvent(EmailOTPAuthenticator.java:2627)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.process(EmailOTPAuthenticator.java:136)
	at com.nutanix.xi.identity.step.handler.ExtendedStepHandler.doAuthentication(ExtendedStepHandler.java:62)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:281)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:179)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:115)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:183)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:253)
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53)
```

**Environment information** 
 - Product Version: IS 5.11.0

**Comment by dhaura** [comment]
- Already fixed by https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/166
