### ISSUE TITLE
Lock wait timeout exceeded error when running migration for v7.0.0

### ISSUE THREAD

**Issue by sanjulamadurapperuma** [wso2/product-is#19291]
**Describe the issue:**

When running the migration client for WSO2 Identity Server v7.0.0 which uses the MySQL database (i.e. MySQL v8.0) the migration fails due to the following error.

```
TID: [] [] [2024-01-24 14:30:08,632] []  INFO {org.wso2.carbon.is.migration.VersionMigration} -  WSO2 Product Migration Service Task : Version : 7.0.0, Migration Step : ConsoleRoleMigrator of order : 8 is starting........................... 
TID: [] [] [2024-01-24 14:30:58,692] [] ERROR {org.wso2.carbon.is.migration.MigrationClientImpl} - Migration process was stopped. org.wso2.carbon.identity.core.migrate.MigrationClientException: Error while creating role.
	at org.wso2.carbon.is.migration.service.v700.dao.RoleV2DAO.createHybridRole(RoleV2DAO.java:291)
	at org.wso2.carbon.is.migration.service.v700.dao.RoleV2DAO.createV2Role(RoleV2DAO.java:355)
	at org.wso2.carbon.is.migration.service.v700.migrator.ConsoleRoleMigrator.migrate(ConsoleRoleMigrator.java:73)
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:76)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s.' INSERT INTO UM_HYBRID_ROLE (UM_ROLE_NAME, UM_TENANT_ID, UM_AUDIENCE_REF_ID, UM_UUID) VALUES (?, ?, ?, ?)
	at org.wso2.carbon.database.utils.jdbc.NamedJdbcTemplate.executeInsert(NamedJdbcTemplate.java:322)
	at org.wso2.carbon.database.utils.jdbc.NamedJdbcTemplate.executeInsert(NamedJdbcTemplate.java:271)
	at org.wso2.carbon.is.migration.service.v700.dao.RoleV2DAO.createHybridRole(RoleV2DAO.java:283)
	... 32 more
Caused by: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:960)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1116)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1066)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1396)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1051)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy49.executeUpdate(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.NamedPreparedStatement.executeUpdate(NamedPreparedStatement.java:266)
	at org.wso2.carbon.database.utils.jdbc.NamedJdbcTemplate.doInternalUpdate(NamedJdbcTemplate.java:397)
	at org.wso2.carbon.database.utils.jdbc.NamedJdbcTemplate.executeInsert(NamedJdbcTemplate.java:312)
	... 34 more
```

The following are the DB configurations that were added to the _deployment.toml_ file (which is located in the _<IS_HOME>/repository/conf_ directory). These configurations are those that are recommended in the documentation as well [1].

```
[database.identity_db]
type = "mysql"
hostname = "<HOSTNAME>"
name = "<DB_NAME>?useSSL=false"
username = "<USERNAME>"
password = "<PASSWORD>"
port = "3306"

[database.identity_db.pool_options]
maxActive = "80"
maxWait = "60000"
minIdle = "5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false
commitOnReturn=true

[database.shared_db]
type = "mysql"
hostname = "<HOSTNAME>"
name = "<DB_NAME>?useSSL=false"
username = "<USERNAME>"
password = "<PASSWORD>"
port = "3306"

[database.shared_db.pool_options]
maxActive = "80"
maxWait = "60000"
minIdle = "5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false
commitOnReturn=true
```

Upon further analysis, it was identified that removing the configuration "_defaultAutoCommit=false_" from the _deployment.toml_ configuration file and retrying the migration resolves the issue. It was also observed that if the relevant pool configurations were not added to the _deployment.toml_ file, the default value is true for the _defaultAutoCommit_ configuration.

This signifies that the migration client does not commit transactions correctly, eventually causing the _lock wait timeout exceeded_ error when running the migration. This needs to be fixed from the migration client side.

[1] - https://is.docs.wso2.com/en/latest/deploy/change-to-mysql/

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS v7.0.0
 - OS: Linux
 - Database: MySQL v8.0
 - Userstore: JDBC

**Comment by sadilchamishka** [comment]
Fixed by - https://github.com/wso2-enterprise/identity-migration-resources/pull/344
