### ISSUE TITLE
Mobile attribute verification on update not working as expected

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#19413]
**Describe the issue:**
When we have enabled the mobile attribute verification on update the following errors are thrown when the mobile number is updated through scim2/me endpoint.

`ERROR {org.wso2.carbon.event.stream.core.internal.EventJunction} - Error while dispatching events: Property subject is neither in the input stream attributes nor in runtime arbitrary data map. org.wso2.carbon.event.publisher.core.exception.EventPublisherStreamValidationException: Property subject is neither in the input stream attributes nor in runtime arbitrary data map.
        at org.wso2.carbon.event.publisher.core.internal.EventPublisher.changePropertyValue(EventPublisher.java:343)
        at org.wso2.carbon.event.publisher.core.internal.EventPublisher.changeDynamicEventAdapterMessageProperties(EventPublisher.java:326)
        at org.wso2.carbon.event.publisher.core.internal.EventPublisher.process(EventPublisher.java:406)
        at org.wso2.carbon.event.publisher.core.internal.EventPublisher.sendEvent(EventPublisher.java:230)
        at org.wso2.carbon.event.publisher.core.internal.EventPublisher.onEvent(EventPublisher.java:300)
        at org.wso2.carbon.event.stream.core.internal.EventJunction.sendEvent(EventJunction.java:157)
        at org.wso2.carbon.event.stream.core.internal.EventStreamRuntime.publish(EventStreamRuntime.java:92)
        at org.wso2.carbon.event.stream.core.internal.CarbonEventStreamService.publish(CarbonEventStreamService.java:356)
        at org.wso2.carbon.identity.event.handler.notification.DefaultNotificationHandler.publishToStream(DefaultNotificationHandler.java:305)
        at org.wso2.carbon.identity.event.handler.notification.DefaultNotificationHandler.handleEvent(DefaultNotificationHandler.java:66)
        at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56)
        at org.wso2.carbon.identity.recovery.handler.MobileNumberVerificationHandler.triggerNotification(MobileNumberVerificationHandler.java:203)
        at org.wso2.carbon.identity.recovery.handler.MobileNumberVerificationHandler.initNotificationForMobileNumberVerificationOnUpdate(MobileNumberVerificationHandler.java:156)
        at org.wso2.carbon.identity.recovery.handler.MobileNumberVerificationHandler.postSetUserClaimOnMobileNumberUpdate(MobileNumberVerificationHandler.java:337)
        at org.wso2.carbon.identity.recovery.handler.MobileNumberVerificationHandler.handleEvent(MobileNumberVerificationHandler.java:111)
        at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56)
        at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.handleEvent(IdentityMgtEventListener.java:1703)
        at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.handleEvent(IdentityMgtEventListener.java:1679)
        at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.handleEvent(IdentityMgtEventListener.java:1667)
        at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.doPostSetUserClaimValues(IdentityMgtEventListener.java:184)
        at org.wso2.carbon.identity.mgt.listener.IdentityUserNameResolverListener.doPostSetUserClaimValuesWithID(IdentityUserNameResolverListener.java:405)
        at org.wso2.carbon.user.core.common.AbstractUserStoreManager.setUserClaimValuesWithID(AbstractUserStoreManager.java:13953)
        at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.updateUserClaims(SCIMUserManager.java:5195)
        at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.updateUser(SCIMUserManager.java:1118)
        at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.updateMe(SCIMUserManager.java:2576)`

`ERROR {org.wso2.carbon.event.stream.core.internal.EventJunction} - Error while dispatching events: Property subject is neither in the input stream attributes nor in runtime arbitrary data map. org.wso2.carbon.event.publisher.core.exception.EventPublisherStreamValidationException: Property subject is neither in the input stream attributes nor in runtime arbitrary data map.
        at org.wso2.carbon.event.publisher.core.internal.EventPublisher.changePropertyValue(EventPublisher.java:343)
        at org.wso2.carbon.event.publisher.core.internal.EventPublisher.changeDynamicEventAdapterMessageProperties(EventPublisher.java:326)
        at org.wso2.carbon.event.publisher.core.internal.EventPublisher.process(EventPublisher.java:406)
        at org.wso2.carbon.event.publisher.core.internal.EventPublisher.sendEvent(EventPublisher.java:230)
        at org.wso2.carbon.event.publisher.core.internal.EventPublisher.onEvent(EventPublisher.java:300)
        at org.wso2.carbon.event.stream.core.internal.EventJunction.sendEvent(EventJunction.java:157)
        at org.wso2.carbon.event.stream.core.internal.EventStreamRuntime.publish(EventStreamRuntime.java:92)
        at org.wso2.carbon.event.stream.core.internal.CarbonEventStreamService.publish(CarbonEventStreamService.java:356)
        at org.wso2.carbon.identity.event.handler.notification.DefaultNotificationHandler.publishToStream(DefaultNotificationHandler.java:305)
        at org.wso2.carbon.identity.event.handler.notification.DefaultNotificationHandler.handleEvent(DefaultNotificationHandler.java:66)
        at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56)
        at org.wso2.carbon.identity.recovery.handler.MobileNumberVerificationHandler.triggerNotification(MobileNumberVerificationHandler.java:203)
        at org.wso2.carbon.identity.recovery.handler.MobileNumberVerificationHandler.initNotificationForMobileNumberVerificationOnUpdate(MobileNumberVerificationHandler.java:156)
        at org.wso2.carbon.identity.recovery.handler.MobileNumberVerificationHandler.postSetUserClaimOnMobileNumberUpdate(MobileNumberVerificationHandler.java:337)
        at org.wso2.carbon.identity.recovery.handler.MobileNumberVerificationHandler.handleEvent(MobileNumberVerificationHandler.java:111)
        at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56)
        at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.handleEvent(IdentityMgtEventListener.java:1703)
        at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.handleEvent(IdentityMgtEventListener.java:1679)
        at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.handleEvent(IdentityMgtEventListener.java:1667)
        at org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener.doPostSetUserClaimValues(IdentityMgtEventListener.java:184)
        at org.wso2.carbon.identity.mgt.listener.IdentityUserNameResolverListener.doPostSetUserClaimValuesWithID(IdentityUserNameResolverListener.java:405)
        at org.wso2.carbon.user.core.common.AbstractUserStoreManager.setUserClaimValuesWithID(AbstractUserStoreManager.java:13953)
        at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.updateUserClaims(SCIMUserManager.java:5195)
        at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.updateUser(SCIMUserManager.java:1118)
        at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.updateMe(SCIMUserManager.java:2576)
        at org.wso2.charon3.core.protocol.endpoints.MeResourceManager.updateWithPATCH(MeResourceManager.java:37`

**Comment by Thisara-Welmilla** [comment]
Possibly related to https://github.com/wso2/product-is/issues/19287

**Comment by Lakshan-Banneheke** [comment]
This issue is now fixed. However, the OTP is not being received, only the configured static payload is being received in the SMS. This is tracked via https://github.com/wso2/product-is/issues/19441
