### ISSUE TITLE
Login through Passive STS federated flow not working

### ISSUE THREAD

**Issue by Lakshan-Banneheke** [wso2/product-is#19426]
**Describe the issue:**
Followed the doc[1] to setup login to an application with WS-Federation to connect to an external IDP through passive sts. A separate IS running on port 9445 was used as the external IDP.

Unable to login to the SPA through the above configured application through the IDP. When clicked on the passive sts idp during login, user is redirected back to the login page and the network trace shows a "login_required" error.

The following logs are displayed in the IS.
```
[2024-02-07 14:32:22,374] [3c615fc1-5148-4d70-9c05-e41ccffac1f8] ERROR {org.wso2.carbon.identity.application.authenticator.passive.sts.manager.STSAgentKeyStoreCredential} - Could not parse certificate: java.io.IOException: Empty input java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:115)
	at java.base/java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:355)
	at org.wso2.carbon.identity.application.common.util.IdentityApplicationManagementUtil.decodeCertificate(IdentityApplicationManagementUtil.java:452)
	at org.wso2.carbon.identity.application.authenticator.passive.sts.manager.STSAgentKeyStoreCredential.readX509Credentials(STSAgentKeyStoreCredential.java:47)
	at org.wso2.carbon.identity.application.authenticator.passive.sts.manager.STSAgentKeyStoreCredential.init(STSAgentKeyStoreCredential.java:60)
	at org.wso2.carbon.identity.application.authenticator.passive.sts.manager.PassiveSTSManager.<init>(PassiveSTSManager.java:90)
	at org.wso2.carbon.identity.application.authenticator.passive.sts.PassiveSTSAuthenticator.initiateAuthenticationRequest(PassiveSTSAuthenticator.java:84)
        .
        .
        .
```

```
[2024-02-07 14:32:22,385] [3c615fc1-5148-4d70-9c05-e41ccffac1f8] ERROR {org.wso2.carbon.identity.application.authenticator.passive.sts.PassiveSTSAuthenticator} - Exception while building the WS-Federation request org.wso2.carbon.identity.application.authenticator.passive.sts.exception.PassiveSTSException: Error occurred while decoding public certificate of Identity Provider WS-Fed
	at org.wso2.carbon.identity.application.authenticator.passive.sts.manager.STSAgentKeyStoreCredential.readX509Credentials(STSAgentKeyStoreCredential.java:53)
	at org.wso2.carbon.identity.application.authenticator.passive.sts.manager.STSAgentKeyStoreCredential.init(STSAgentKeyStoreCredential.java:60)
	at org.wso2.carbon.identity.application.authenticator.passive.sts.manager.PassiveSTSManager.<init>(PassiveSTSManager.java:90)
	at org.wso2.carbon.identity.application.authenticator.passive.sts.PassiveSTSAuthenticator.initiateAuthenticationRequest(PassiveSTSAuthenticator.java:84)
	at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.process(AbstractApplicationAuthenticator.java:101)
        .
        .
        .
```

```
[2024-02-07 14:32:22,386] [3c615fc1-5148-4d70-9c05-e41ccffac1f8] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! Error occurred while decoding public certificate of Identity Provider WS-Fed
```

[1] https://is.docs.wso2.com/en/next/guides/authentication/standard-based-login/add-ws-federation/

**How to reproduce:**
1. Deploy an IS in port 9445
2. Create an application with passive STS with realm `PassiveSTSIdP`
3. Deploy another IS in port 9443
4. Create a connection for passive STS as per doc[1]. `Passive STS Realm` is given as PassiveSTSIdP and `Passive STS URL` is given as https://localhost:9445/passivests
5. Create an application and add the above connection to sign in options
6. Attempt to login to a sample SPA using the above application.

[1] https://is.docs.wso2.com/en/next/guides/authentication/standard-based-login/add-ws-federation/

**Expected behavior:**
Login should be successful.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-7.0.0-beta7-SNAPSHOT
 - OS: Mac

**Comment by deshankoswatte** [comment]
This occurs because we extract the identity provider's certificate [1], but we allow the creation of the WS-Federation connection without the identity provider's certificate. This issue should get resolved once the identity provider's certificate is added to the WS-Federation connection.

[1] - https://github.com/wso2-extensions/identity-outbound-auth-passive-sts/blob/master/components/org.wso2.carbon.identity.application.authenticator.passive.sts/src/main/java/org/wso2/carbon/identity/application/authenticator/passive/sts/manager/STSAgentKeyStoreCredential.java#L43
