### ISSUE TITLE
Server startup issues in the cluster when using kubernetes membership schema based clustering configuration

### ISSUE THREAD

**Issue by Yasasr1** [wso2/product-is#19634]
**Describe the issue:**
When trying to setup a kubernetes membership schema based clustering setup with the advanced deployment pattern of https://github.com/wso2/kubernetes-is, IS fails to start with the following error

```
 ERROR {Events.Framework} - FrameworkEvent ERROR org.osgi.framework.BundleException: Could not resolve module: org.wso2.carbon.identity.application.authenticator.fido [266]
  Unresolved requirement: Import-Package: org.wso2.carbon.identity.application.authenticator.fido2.core; version="5.3.30.1"
    -> Export-Package: org.wso2.carbon.identity.application.authenticator.fido2.core; bundle-symbolic-name="org.wso2.carbon.identity.application.authenticator.fido2"; bundle-version="5.3.30.2"; version="5.3.30.2"; uses:="com.fasterxml.jackson.core,org.wso2.carbon.identity.application.authentication.framework.exception,org.wso2.carbon.identity.application.authentication.framework.model,org.wso2.carbon.identity.application.authenticator.fido2.dto,org.wso2.carbon.identity.application.authenticator.fido2.exception,org.wso2.carbon.identity.application.authenticator.fido2.util"
       org.wso2.carbon.identity.application.authenticator.fido2 [267]
         Unresolved requirement: Import-Package: com.webauthn4j; version="0.19.1.wso2v2"

	at org.eclipse.osgi.container.Module.start(Module.java:457)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

This is due to incompatibility issues with the latest JDK 11 versions. According to their documentation, this issue can be fixed by adding the below lines to the wso2server.sh 
```
-Djdk.util.zip.disableZip64ExtraFieldValidation=true \
-Djdk.nio.zipfs.allowDotZipEntry=true \
```

This is already added to the 6.1 product pack. However during the cluster creation this file is overridden and the new file dosen't contain these fixes. 

**How to reproduce:**
- follow the guide at https://github.com/wso2/kubernetes-is/tree/master/advanced/is-pattern-1 to setup the cluster
- check the server logs using `kubectl logs wso2is-pattern-1-identity-server-statefulset-0 -c identity-server -n wso2 -f
`

**Expected behavior:**
Server should start

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 6.1.0
 - OS: Linux

**Comment by Yasasr1** [comment]
the issue is fixed with the above pr
