### ISSUE TITLE
 [FindBugs] Build Failure due to FindBugs Issue

### ISSUE THREAD

**Issue by PasinduYeshan** [wso2/product-is#19928]
When attempting to build the [identity-rest-dispatcher](https://github.com/wso2/identity-rest-dispatcher), the build is failing due to a findbugs issue:

```
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
     [java] Exception Details:
     [java]   Location:
     [java]     com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor.visitINVOKEDYNAMIC(Lorg/apache/bcel/generic/INVOKEDYNAMIC;)V @11: invokespecial
     [java]   Reason:
     [java]     Type 'org/apache/bcel/generic/INVOKEDYNAMIC' (current frame, stack[1]) is not assignable to 'org/apache/bcel/generic/InvokeInstruction'
     [java]   Current Frame:
     [java]     bci: @11
     [java]     flags: { }
     [java]     locals: { 'com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor', 'org/apache/bcel/generic/INVOKEDYNAMIC' }
     [java]     stack: { 'com/h3xstream/findsecbugs/taintanalysis/TaintFrameModelingVisitor', 'org/apache/bcel/generic/INVOKEDYNAMIC' }
     [java]   Bytecode:
     [java]     0x0000000: b800 32b6 00a2 9900 0b2a 2bb7 00a1 a700
     [java]     0x0000010: 082a 2bb6 007a b1                      
     [java]   Stackmap Table:
     [java]     same_frame(@17)
     [java]     same_frame(@22)
     [java]     at com.h3xstream.findsecbugs.taintanalysis.TaintAnalysis.<init>(TaintAnalysis.java:76)
     [java]     at com.h3xstream.findsecbugs.taintanalysis.TaintDataflowEngine.analyze(TaintDataflowEngine.java:183)
     [java]     at com.h3xstream.findsecbugs.taintanalysis.TaintDataflowEngine.analyze(TaintDataflowEngine.java:57)
     [java]     at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:369)
     [java]     at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:322)
     [java]     at com.h3xstream.findsecbugs.injection.AbstractTaintDetector.getTaintDataFlow(AbstractTaintDetector.java:142)
     [java]     at com.h3xstream.findsecbugs.injection.AbstractTaintDetector.analyzeMethod(AbstractTaintDetector.java:109)
     [java]     at com.h3xstream.findsecbugs.injection.AbstractTaintDetector.visitClassContext(AbstractTaintDetector.java:79)
     [java]     at edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
     [java]     at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
     [java]     at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
     [java]     at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
     [java]     at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
```

The same issue has been reported in the API-Server PR builder, resulting in build failure.

**Comment by PasinduYeshan** [comment]
Revert the linked PRs once a proper fix is introduced.
