### ISSUE TITLE
NPE in EmailOTP Authenticator when context.isRetrying() is true

### ISSUE THREAD

**Issue by ratnajothy** [wso2/product-is#20282]
**Describe the issue:** Refer $title
<img width="600" alt="image" src="https://github.com/wso2/product-is/assets/15968322/53fb0fab-7469-4601-83f4-a512730b4d30">
```log
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework java.lang.NullPointerException
        at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.publishPostEmailOTPValidatedEvent(EmailOTPAuthenticator.java:2939)
        at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.process(EmailOTPAuthenticator.java:212)
        at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:512)
        at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:268)
        at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handleAuthenticationStep(GraphBasedSequenceHandler.java:431)
        at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handleNode(GraphBasedSequenceHandler.java:174)
        at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:129)
        at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:186)
        at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:250)
        at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53)
        ...
```

This reason is OTP_GENERATED_TIME is null [1], since context.isRetrying() is true and, so these [2] properties don't set. 

[1] https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/46286e469b906838d1702ca209447b4cac582ea4/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L2722
[2] https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/46286e469b906838d1702ca209447b4cac582ea4/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L1011-L1012

**How to reproduce:**
Add MFA as follows,
Step 1 => Basic Auth
Step 2 => SMS OTP
Step 3 => Email OTP and add the below script to executeStep(3) on failure of Step 2.
```js
var onLoginRequest = function(context) {
    executeStep(1, {
        onSuccess: function (context) {
            executeStep(2, {
                onFail: function (context) {
                    executeStep(3);
                }
            });
        }        
    });
};
```
When entering incorrect SMS OTP, the error occurs without navigating to EmailOTP.

**Expected behaviour:**
executeStep(3) without exceptions.

**Environment information:**
 - Product Version: IS 5.10.0

**Comment by darksoul96** [comment]
This issue is still reproducible in v7.0.0 in latest update level

**Comment by shanggeeth** [comment]
Closing this since the new email otp authenticator is also fixed with https://github.com/wso2-support/identity-local-auth-emailotp/pull/6

**Comment by shanggeeth** [comment]
### Developer Checklist

Please review and confirm the following items for identify the migration impact of the changes.(if any checkbox is not applicable mark it as N/A)

- [ ] **[Behavioral Change]** Does this change introduce a behavioral change to the product? N/A
     - [ ] ↳ Approved by team lead
     - [ ] ↳ Label `impact/behavioral-change` added
- [ ] **[Migration Impact]** Does this change have a migration impact? N/A
     - [ ] ↳ Migration label added (e.g., `7.2.0-migration`)
     - [ ] ↳ Migration issues created and linked"
- [ ] **[New Configuration]** Does this change introduce a new configuration? N/A
     - [ ] ↳ Label `config` added
     - [ ] ↳ Configuration is properly documented
