### ISSUE TITLE
Handling duplicated records on IDN_AUTH_USER_SESSION_MAPPING table

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#20468]
**Describe the issue:**

After the authentication concludes successfully, DefaultAuthenticationRequestHandler::storeSessionData method stores the user session mapping twice: first for each IDP in the authentication chain [1] and then for local authenticated users [2] to handle cases where the user id can be different for linked accounts during federated log in [3].

In a local authentication flow where the user id is the same, the expected behavior is as follows:
1. Prior to the first occurrence of the storeUserSessionData method [1], the existence of a mapping for the given user id is checked [4].
2. The above returns `false` and the user session data is then persisted to the database.
3. Prior to the second occurrence of the storeUserSessionData method [2], the existence of a mapping for the given user id is checked again [5].
4. The above returns `true` as the user session data is already persisted the storeUserSessionData method is not called a second time.

However, it is possible for the 3rd step to return `false` if there is some latency in the creation of the mapping from the first time the storeUserSessionData was called, which could result in a second attempt to store the user session data for the given user id, resulting in a unique constraint violation error:
```
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework org.wso2.carbon.identity.application.authentication.framework.exception.FrameworkException: Error while storing session details of the authenticated user to the database
    at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.concludeFlow(DefaultAuthenticationRequestHandler.java:537)
    at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:210)
    at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:250)
    at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53)
    ...
Caused by: org.wso2.carbon.identity.application.authentication.framework.exception.UserSessionException: Error while storing session data for user: xxxx
    at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.storeSessionData(DefaultAuthenticationRequestHandler.java:800)
    at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.concludeFlow(DefaultAuthenticationRequestHandler.java:535)
    ...
Caused by: org.wso2.carbon.identity.application.authentication.framework.exception.UserSessionException: Error while storing mapping between user Id: 147101d4-b5b5-4e28-b331-8ca84b6df359 and session Id: af8d47babdf5f936ce787860a759dcb5a83e62ce6b9982a667e4f44a4d6dae99
    at org.wso2.carbon.identity.application.authentication.framework.store.UserSessionStore.storeUserSessionData(UserSessionStore.java:330)
    at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.storeSessionData(DefaultAuthenticationRequestHandler.java:793)
    ...
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "user_session_store_constraint"
  Detail: Key (user_id, session_id)=(147101d4-b5b5-4e28-b331-8ca84b6df359, af8d47babdf5f936ce787860a759dcb5a83e62ce6b9982a667e4f44a4d6dae99) already exists.
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
    at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
    at jdk.internal.reflect.GeneratedMethodAccessor155.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
    at com.sun.proxy.$Proxy51.executeUpdate(Unknown Source)
    at org.wso2.carbon.identity.application.authentication.framework.store.UserSessionStore.storeUserSessionData(UserSessionStore.java:326)
    ...
```

**How to reproduce:**

Since the issue could be caused by database latency there's no specific steps to reproduce it.

**Expected behavior:**

Handling duplicated records in the IDN_AUTH_USER_SESSION_MAPPING table should be improved to allow the user to log in when this kind of error occurs. 

**Environment information:**
 - Product Version: IS 5.10.0

---
[1] https://github.com/wso2/carbon-identity-framework/blob/0e5e1641c0ddfb928bffbefde02806bb59013c20/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/DefaultAuthenticationRequestHandler.java#L887
[2] https://github.com/wso2/carbon-identity-framework/blob/0e5e1641c0ddfb928bffbefde02806bb59013c20/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/DefaultAuthenticationRequestHandler.java#L901
[3] https://github.com/wso2/product-is/issues/12169
[4] https://github.com/wso2/carbon-identity-framework/blob/0e5e1641c0ddfb928bffbefde02806bb59013c20/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/DefaultAuthenticationRequestHandler.java#L886
[5] https://github.com/wso2/carbon-identity-framework/blob/0e5e1641c0ddfb928bffbefde02806bb59013c20/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/DefaultAuthenticationRequestHandler.java#L900

**Comment by ZiyamSanthosh** [comment]
Public fix is already merged. Hence, closing the issue.
- https://github.com/wso2/carbon-identity-framework/pull/5734
