### ISSUE TITLE
Concurrent user reads lead to constraint violation

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#20474]
**Describe the issue:**
In the user read path, we add an entry to `UM_UUID_DOMAIN_MAPPER` table with userstore domain and user id. This is done only after making sure that there is no record with the same data already in the table [1]. Also there is a unique constraint on the DB for UM_USER_ID column. In an ideal situation, this logic works fine. 

But in a high concurrent situation, this logic runs into a race condition and could lead to constraint violations on the DB as explain below in reproducing steps.  It's important to note that this issue typically occurs only once per user. Subsequent requests will find the existing record and proceed normally. 

The suggestion is to implement retry logic here to handle errors when storing the domain for a user ID at [1]. This would avoid the race condition for storing a record in this table, as subsequent retries would find the existing record due to the existence check. 

A similar fix was done in session mapping persistence logic in https://github.com/wso2/product-is/issues/9945.

There are 03 places which invokes `userUniqueIDDomainResolver.setDomainForUserId()`. I would suggest introducing a new method called `setDomainForUserIdIfNotExists()` and add the `check, insert and retry` logic there. Then update those 03 places to invoke the new method.

On a side note, it won't throw `SQLIntegrityConstraintViolationException` in all DB types. For example, MSSQL throws `com.microsoft.sqlserver.jdbc.SQLServerException`. Therefore we'll have to catch `java.sql.SQLException` and retry.

**Steps to reproduce**
- Plug an external userstore to IS as a secondary userstore
- Create a user on the external userstore directly (without getting a record added to UM_UUID_DOMAIN_MAPPER table of UM DB)
- Now try to query for this user via SCIM in two concurrent requests like below.
```
curl -k -u admin:admin "https://localhost:9443/scim2/Users?filter=userName+eq+user01" & curl -k -u admin:admin "https://localhost:9443/scim2/Users?filter=userName+eq+user01"
```
The failed thread will not return the user details and following stacktrace is logged like below.
```
ERROR {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Error occurred while getting the users list for domain: UM1 Therefore, proceeding remaining domains org.wso2.carbon.user.core.UserStoreException: Error occurred while persisting domain against the user id.
	at org.wso2.carbon.user.core.common.UserUniqueIDDomainResolver.persistDomainAgainstUserId(UserUniqueIDDomainResolver.java:217)
	at org.wso2.carbon.user.core.common.UserUniqueIDDomainResolver.setDomainForUserId(UserUniqueIDDomainResolver.java:151)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUser(AbstractUserStoreManager.java:11883)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserFromID(AbstractUserStoreManager.java:11623)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUsersFromIDs(AbstractUserStoreManager.java:12235)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetUserListWithID(AbstractUserStoreManager.java:2869)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserListWithID(AbstractUserStoreManager.java:2793)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetUserListWithID(AbstractUserStoreManager.java:2919)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserListWithID(AbstractUserStoreManager.java:2793)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:198)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:195)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserListWithID(AbstractUserStoreManager.java:2715)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getUserNames(SCIMUserManager.java:4421)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.filterUsersUsingLegacyAPIs(SCIMUserManager.java:1644)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.filterUsersBySingleAttribute(SCIMUserManager.java:1112)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.filterUsers(SCIMUserManager.java:1063)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsersWithGET(SCIMUserManager.java:517)
	at org.wso2.charon3.core.protocol.endpoints.UserResourceManager.listWithGET(UserResourceManager.java:347)
	at org.wso2.carbon.identity.scim2.provider.resources.UserResource.getUser(UserResource.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	...
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'b7a65587-1d25-42de-b4d4-e97bf32eec7b' for key 'um_uuid_domain_mapper.UM_USER_ID'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy52.execute(Unknown Source)
	at org.wso2.carbon.user.core.common.UserUniqueIDDomainResolver.persistDomainAgainstUserId(UserUniqueIDDomainResolver.java:212)
	... 82 more
```

**Environment information** 
 - Product Version: IS-KM-5.10.0
 - Database: MSSQL
 - Userstore: JDBC

[1] https://github.com/wso2/carbon-kernel/blob/b88c3dcbdc0d5305843794cd915abeb9d9d75cfb/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L13528-L13531

**Comment by rksk** [comment]
Fixed with https://github.com/wso2/carbon-kernel/pull/4010
