### ISSUE TITLE
Improve IWA Kerberos authenticator to resolve users from multi attribute login

### ISSUE THREAD

**Issue by isuruhettiarachchi** [wso2/product-is#20565]
**Describe the issue:**
When logging with IWA Kerberos authenticator, the username returned from the Kerbeos server is userPrincipalName or sAMAccountName. However, if the user exists in a AD userstore where the username is configured to mail attribute (users can login with email as username) the authentication will fail saying the user is not existing because IWA Kerberos is using isExistingUser method [1].

We need to improve the IWA Kerberos authenticator to use the multi attribute login feature to resolve the user.

**How to reproduce:**
1. Configure IWA Kerberos authentication.
2. Configure an AD where the user exists and configure username attribute to mail.
```
    <Property name="UserNameAttribute">mail</Property>
    <Property name="UserNameSearchFilter">(&amp;(objectClass=person)(mail=?))</Property>
```
3. Login with the IWA Kerberos.
4. Authentication will fail stating the user not existing.

```
[2024-06-13 15:59:23,649] [9e18d56e-3e6e-41ef-aabf-41853653d10e] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: Authentication Failed, User: John not found in any of specified userstores: PRIMARY,SECONDARY of tenant: carbon.super.
        at org.wso2.carbon.identity.application.authenticator.iwa.IWAFederatedAuthenticator.processAuthenticationResponse(IWAFederatedAuthenticator.java:124)
        at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.process(AbstractApplicationAuthenticator.java:90)
        at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:528)
```

**Expected behavior:**
User should be resolved with multi attribute login.

**Environment information:**
 - Product Version: IS 6.1.0

**Comment by Yasasr1** [comment]
Closing since the public pr is merged
