### ISSUE TITLE
Missing branding custom text metadata leads to `TypeError` in Branding UI component in the Console application

### ISSUE THREAD

**Issue by vfraga** [wso2/product-is#20593]
**Describe the issue:**
When accessing the Branding UI component [1] in the Console application after adding a custom text to the branding preferences (either through the UI or API [2]), it crashes with the following message:

<img width="530" alt="image" src="https://github.com/wso2/product-is/assets/62815192/92ec2dbd-87d2-4506-863d-83f05abf6c3e">

And the following error in the console:
```
TypeError: Cannot read properties of undefined (reading 'MULTI_LINE')
    at 64885.61f26152.chunk.js:2:16974
    at Array.map (<anonymous>)
    at render (64885.61f26152.chunk.js:2:16452)
    at l (vendor.9244f27c.js:102:1675349)
    at b (vendor.9244f27c.js:102:1678511)
    at Za (vendor.9244f27c.js:102:1605940)
    at Zl (vendor.9244f27c.js:102:1662795)
    at xc (vendor.9244f27c.js:102:1651947)
    at yc (vendor.9244f27c.js:102:1651875)
    at vc (vendor.9244f27c.js:102:1651738)
```

Further analysis shown that it crashed when trying to fetch specific metadata about the newly added custom text, which was retrieved from a file under the path `<IS_HOME>/repository/deployment/server/webapps/console/resources/branding/i18n/screens/<SCREEN_NAME>/meta.json` [3].
It seems that neither the API or the UI component updates this file after changes to these custom texts, causing the issue.
It's worth noting the custom text was retrieved successfully, it's just an issue with metadata.

**How to reproduce:**
- Create and start a Identity Server 7.0.0 instance.
- Run the cURL command below:
```sh
curl -k -X 'PUT' \
'https://localhost:9443/api/server/v1/branding-preference/text' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
    "type": "ORG",
    "name": "carbon.super",
    "locale": "en-US",
    "screen": "common",
    "preference": {
        "text": {
            "copyright": "© {{currentYear}} WSO2 LLC.",
            "site.title": "WSO2 Identity Server",
            "privacy.policy": "Privacy Policy",
            "terms.of.service": "Terms of Service",
            "custom.footer": "Custom Footer"
        }
    }
}' \
-H 'Authorization: Basic YWRtaW46YWRtaW4='
```
- Go to the Console application (`https://localhost:9443/`) and navigate to: Branding > Styles & Text > Text
- Observe the crash with the following error in the browser console:
```
TypeError: Cannot read properties of undefined (reading 'MULTI_LINE')
    at 64885.61f26152.chunk.js:2:16974
    at Array.map (<anonymous>)
    at render (64885.61f26152.chunk.js:2:16452)
    at l (vendor.9244f27c.js:102:1675349)
    at b (vendor.9244f27c.js:102:1678511)
    at Za (vendor.9244f27c.js:102:1605940)
    at Zl (vendor.9244f27c.js:102:1662795)
    at xc (vendor.9244f27c.js:102:1651947)
    at yc (vendor.9244f27c.js:102:1651875)
    at vc (vendor.9244f27c.js:102:1651738)
```

**Expected behavior:**
The Branding UI shouldn't crash if a custom branding text is added.

**Environment information:**
 - Product Version: 7.0.0

---

[1] https://is.docs.wso2.com/en/latest/guides/branding/configure-ui-branding/#text-preferences
[2] https://is.docs.wso2.com/en/latest/apis/branding-preference-rest-api/#tag/Custom-Text
[3] https://github.com/wso2/identity-apps/blob/%40wso2is/console%402.12.46/apps/console/src/features/branding/api/use-get-custom-text-preference-meta.ts#L34-L62

**Comment by asha15** [comment]
Adding custom fields to the branding preference texts is not supported and updated the doc with the relevant information [1].

[1] https://github.com/wso2/docs-is/pull/4657

**Comment by asha15** [comment]
Closing the issue since the crashing issue is fixed in the master branch [1].

[1] https://github.com/wso2/identity-apps/pull/5646

**Comment by vfraga** [comment]
Hi @asha15 ,

It doesn't make sense to say there isn't support for adding custom texts if there's an API [1] exposed for this purpose. The intention of this bug report is to address bugs in the front end logic, which is hopefully addressed by the issue mentioned [2].

Best regards,
Vinicius

[1] https://is.docs.wso2.com/en/7.0.0/apis/organization-apis/org-branding-mgt/#tag/Custom-Text/operation/addCustomText
[2] https://github.com/wso2/identity-apps/pull/5646
