### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid Access Token. Access token is not ACTIVE

### ISSUE THREAD

**Issue by ratnajothy** [wso2/product-is#20632]
**Describe the issue:**
Authentication Error due to $title happening when a user has reached his max-active-sessions-count limited by the `active-session-limit-handler`. This is because, just before User tries to terminate an existing session, the token bound to the session gets revoked via a token revocation request resulting in [1] related stack-trace [2].

**How to reproduce:**
1. Enable the `deployment.toml` config below:
```toml
[oauth.token_cleanup]
enable = false
```
2. Configure an adaptive authentication script as given below with **1st** factor as `Basic` & **2nd** factor as `active-session-limit-handler` with max-allowed-session-count as One for a Service Provider (SP).
```js
var onLoginRequest = function(context) {
    executeStep(1, {
        onSuccess: function(context) { 
             // Extracting authenticated subject from the first step
            var user = context.currentKnownSubject;
            executeStep(2, {
                authenticatorParams: {
                    local: {
                        SessionExecutor: {
                            MaxSessionCount: '1'
                        }
                    }
                }
            }, {});
        }
    });
}
```
3. Successfully establish a session via `A` browser and now login via `B` browser and it will ask for consent to terminate the session. 
<img width="470" alt="image" src="https://github.com/wso2/product-is/assets/15968322/5ac82f37-3c5c-42ea-9b27-73661af33485">

4. Get `refresh_token` for the User issued already via `A`, then revoke it via [3] API invocation.
5. Only now, provide the consent to terminate the session of `A` browser while in `B` browser.
<img width="475" alt="image" src="https://github.com/wso2/product-is/assets/15968322/f736f9b0-4363-4d5a-b44e-cf4fc0b57982">

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/12f2961da3e635eb68b0d94194ed3f143562f845/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/util/OAuth2Util.java#L1597-L1600
[2] 
```log
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework java.lang.IllegalArgumentException: Invalid Access Token. Access token is not ACTIVE.
        at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getAccessTokenDOFromTokenIdentifier(OAuth2Util.java:1715)
        at org.wso2.carbon.identity.oauth2.token.bindings.handlers.TokenBindingExpiryEventHandler.revokeTokensMappedToSession(TokenBindingExpiryEventHandler.java:296)
        at org.wso2.carbon.identity.oauth2.token.bindings.handlers.TokenBindingExpiryEventHandler.revokeAccessTokensMappedForSessions(TokenBindingExpiryEventHandler.java:132)
        at org.wso2.carbon.identity.oauth2.token.bindings.handlers.TokenBindingExpiryEventHandler.handleEvent(TokenBindingExpiryEventHandler.java:87)
        at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56)
        at org.wso2.carbon.identity.data.publisher.application.authentication.AuthnDataPublisherProxy.doPublishEvent(AuthnDataPublisherProxy.java:245)
        at org.wso2.carbon.identity.data.publisher.application.authentication.AuthnDataPublisherProxy.publishSessionTermination(AuthnDataPublisherProxy.java:211)
        at org.wso2.carbon.identity.application.authentication.framework.util.FrameworkUtils.publishSessionEvent(FrameworkUtils.java:1886)
        at org.wso2.carbon.identity.application.authentication.framework.services.SessionManagementService.terminateSession(SessionManagementService.java:96)
        ....
```
[3] https://is.docs.wso2.com/en/5.11.0/learn/oauth2-token-revocation/#oauth2-token-revocation
**Expected behavior:**
Authenticate User Successfully..

**Suggestion:** 
Handle ERROR properly without throwing an Exception.

**Environment information:**
 - Product Version: IS 5.11.0

**Comment by nilasini** [comment]
@ZiyamSanthosh are we good to close this issue?

**Comment by ZiyamSanthosh** [comment]
> [@ZiyamSanthosh](https://github.com/ZiyamSanthosh) are we good to close this issue?

Yes. The public fix is available with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1663
