### ISSUE TITLE
Error on Console App `Error occurred while retrieving Identity Provider for tenant: carbon.super`

### ISSUE THREAD

**Issue by shanggeeth** [wso2/product-is#20712]
**Describe the issue:**
Error 
**How to reproduce:**
- Intermittantly displayed on Console app
 - Backend console error log
 ```
[2024-07-18 03:52:51,207] [1cf017d7-f31c-4391-8ee1-7a339e933313] ERROR {org.wso2.carbon.identity.api.server.idp.v1.core.ServerIdpManagementService} - errorCode: IDP-65006 | message: Error wh$
le connecting database. Error occurred while retrieving Identity Provider for tenant: carbon.super org.wso2.carbon.idp.mgt.IdentityProviderManagementServerException: Error while connecting d$
tabase. Error occurred while retrieving Identity Provider for tenant: carbon.super                                                                                                             
        at org.wso2.carbon.idp.mgt.util.IdPManagementUtil.handleServerException(IdPManagementUtil.java:265)                                                                                    
        at org.wso2.carbon.idp.mgt.dao.IdPManagementDAO.getIdPsSearch(IdPManagementDAO.java:363)                                                                                               
        at org.wso2.carbon.idp.mgt.dao.CacheBackedIdPMgtDAO.getPaginatedIdPsSearch(CacheBackedIdPMgtDAO.java:147)                                                                              
        at org.wso2.carbon.idp.mgt.IdentityProviderManager.getIdPs(IdentityProviderManager.java:493)                                                                                           
        at org.wso2.carbon.identity.api.server.idp.v1.core.ServerIdpManagementService.getIDPs(ServerIdpManagementService.java:203)                                                             
        at org.wso2.carbon.identity.api.server.idp.v1.impl.IdentityProvidersApiServiceImpl.getIDPs(IdentityProvidersApiServiceImpl.java:175)                                                   
        at org.wso2.carbon.identity.api.server.idp.v1.IdentityProvidersApi.getIDPs(IdentityProvidersApi.java:434)                                                                              
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                      
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                    
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                            
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                                                                          
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)                                                                                          
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)                                                                                                      
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)                                                                                                                     
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)                                                                                                                     
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:123)
        at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
        at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:149)
at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:153)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
        at org.wso2.carbon.extension.identity.x509Certificate.valve.X509CertificateAuthenticationValve.invoke(X509CertificateAuthenticationValve.java:59)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
        at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00907: missing right parenthesis

https://docs.oracle.com/error-help/db/ora-00907/
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:709)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:609)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1347)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:1101)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:409)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:499)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:274)
        at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:1216)
        at oracle.jdbc.driver.OracleStatement.prepareDefineBufferAndExecute(OracleStatement.java:1399)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1273)
        at oracle.jdbc.driver.OracleStatement.executeSQLSelect(OracleStatement.java:1830)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1606)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3953)
        at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:4140)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1103)
        at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
        at com.sun.proxy.$Proxy49.executeQuery(Unknown Source)
        at org.wso2.carbon.idp.mgt.dao.IdPManagementDAO.getIdpQueryResultSet(IdPManagementDAO.java:572)
        at org.wso2.carbon.idp.mgt.dao.IdPManagementDAO.getIdPsSearch(IdPManagementDAO.java:357)
        ... 62 more
Caused by: Error : 907, Position : 529, SQL = SELECT ID, NAME, DESCRIPTION, IS_ENABLED, IMAGE_URL, UUID, TENANT_ID , DEFAULT_AUTHENTICATOR_NAME  FROM ( SELECT ID, NAME, DESCRIPTION, IS_ENABLE
D, IMAGE_URL, UUID, TENANT_ID , DEFAULT_AUTHENTICATOR_NAME , ROWNUM AS rnum FROM (SELECT ID, NAME, DESCRIPTION, IS_ENABLED, IMAGE_URL, UUID, TENANT_ID , DEFAULT_AUTHENTICATOR_NAME FROM IDP OR
DER BY ID ASC ) WHERE TENANT_ID = :1 AND NAME != 'LOCAL' AND IDP.ID NOT IN (SELECT IDP_ID FROM IDP_METADATA WHERE TENANT_ID = IDP.TENANT_ID AND NAME = 'isSystemReservedIdP' AND "VALUE" = 'tru
e'0 AND ROWNUM <= :2 ) WHERE rnum > :3 , Original SQL = SELECT ID, NAME, DESCRIPTION, IS_ENABLED, IMAGE_URL, UUID, TENANT_ID , DEFAULT_AUTHENTICATOR_NAME  FROM ( SELECT ID, NAME, DESCRIPTION,
 IS_ENABLED, IMAGE_URL, UUID, TENANT_ID , DEFAULT_AUTHENTICATOR_NAME , ROWNUM AS rnum FROM (SELECT ID, NAME, DESCRIPTION, IS_ENABLED, IMAGE_URL, UUID, TENANT_ID , DEFAULT_AUTHENTICATOR_NAME F
ROM IDP ORDER BY ID ASC ) WHERE TENANT_ID = ? AND NAME != 'LOCAL' AND IDP.ID NOT IN (SELECT IDP_ID FROM IDP_METADATA WHERE TENANT_ID = IDP.TENANT_ID AND NAME = 'isSystemReservedIdP' AND "VALU
E" = 'true'0 AND ROWNUM <= ?) WHERE rnum > ?, Error Message = ORA-00907: missing right parenthesis

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:717)
        ... 83 more
```

**Expected behavior:**
- There should be no error logs when accessing Console

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [7.0.1-snapshot]
 - OS: [Oracle Linux 8]
 - Database: [Oracle RAC]

**Comment by shanggeeth** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/5796
