### ISSUE TITLE
[Regression] ClassCastException when listing users from an AD userstore with binary user ID attribute

### ISSUE THREAD

**Issue by jcgarciaa** [wso2/product-is#20746]
**Describe the issue:**

After updating IS-6.1.0 to update level 180 or above a `ClassCastException` is thrown when listing users from an AD userstore with `objectGuid` defined as user ID attribute:
```
ERROR {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Error occurred while accessing Java Security Manager Privilege Block when called by method listUsers with 2 length of Objects and argTypes [class java.lang.String, int] java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
       at java.base/java.security.AccessController.doPrivileged(Native Method)
       at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:240)
       at org.wso2.carbon.user.core.common.AbstractUserStoreManager.listUsers(AbstractUserStoreManager.java:6406)
       at org.wso2.carbon.user.mgt.UserRealmProxy.listAllUsers(UserRealmProxy.java:208)
       at org.wso2.carbon.user.mgt.UserAdmin.listAllUsers(UserAdmin.java:86)
       at jdk.internal.reflect.GeneratedMethodAccessor320.invoke(Unknown Source)
       ...
Caused by: java.lang.reflect.InvocationTargetException
       at jdk.internal.reflect.GeneratedMethodAccessor282.invoke(Unknown Source)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
       at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:243)
       ... 149 more
Caused by: java.lang.ClassCastException: class [B cannot be cast to class java.lang.String ([B and java.lang.String are in module java.base of loader 'bootstrap')
       at org.wso2.carbon.user.core.ldap.UniqueIDReadOnlyLDAPUserStoreManager.doListUsersWithID(UniqueIDReadOnlyLDAPUserStoreManager.java:821)
       at org.wso2.carbon.user.core.common.AbstractUserStoreManager.listUsers(AbstractUserStoreManager.java:6490)
       ... 153 more
```

To fix https://github.com/wso2/product-is/issues/20566 it was introduced a new validation on the `UniqueIDReadOnlyLDAPUserStoreManager` class to check whether the userId attribute was null. To get this value the property is casted to String, but on AD userstores since `objectGuid` is a binary attribute this causes the ClassCastException.

**How to reproduce:**
- Define an AD userstore on IS and configure the following properties:
```
UserIDAttribute = objectGuid
UserIdSearchFilter = (&(objectClass=user)(objectGuid=?))
transformObjectGUIDToUUID = true
ImmutableAttributes = objectGuid,...
```
- List the users on the userstore (e.g. management console) --> Users will be listed
- Update the product to U2 level 180 or above
- List the users on the userstore (e.g. management console) --> Error will be thrown

**Expected behavior:**

Users should be listed regardless of the userstore.

**Environment information:**
 - Product Version: IS 6.1.0
 - Userstore: Active Directory

---

**Related issues:**
- https://github.com/wso2/product-is/issues/20566

**Comment by nilasini** [comment]
@amanda-ariyaratne are we good to close this issue?
