### ISSUE TITLE
Internal Server Error when the Request Body is Missing in Organization Discovery POST Endpoint

### ISSUE THREAD

**Issue by BimsaraBodaragama** [wso2/product-is#20886]
**Describe the issue:**

> When making a POST request to the `/organizations/discovery` endpoint without including a request body, the server returns a `500 Internal Server Error`. This behavior is not expected, as a missing body should instead trigger a `415 Unsupported Media Type` response.

**How to reproduce:**

> 1. Execute the following `curl` command without providing a body:
> 
> ```
> curl --location --request POST 'https://localhost:9443/t/wso2.com/api/server/v1/organizations/discovery' \
> --header 'Content-Type: application/json' \
> --header 'Authorization: Bearer <token>'
> ```
> 2. Alternatively, execute the following `curl` command with an empty body:
> 
> ```
> curl --location --request POST 'https://localhost:9443/t/wso2.com/api/server/v1/organizations/discovery' \
> --header 'Content-Type: application/json' \
> --header 'Authorization: Bearer 56190eb6-293f-3cd3-bfad-91f3595b9faf' \
> --data ''
> ```
> 
> 3. Observe the response and the server logs.
> 
> **Actual Response:**
> 
> The server returns a `500 Internal Server Error` with the following response body:
> 
> ```
> {
>     "code": "SE-50000",
>     "message": "Unexpected Processing Error.",
>     "description": "Server encountered an error while serving the request.",
>     "traceId": "<trace-id>"
> }
> ```
> 
> **Exception Details:**
> 
> The server logs indicate a `NullPointerException` is being thrown, specifically in the `addOrganizationDiscoveryAttributes` method. Below is the relevant log entry:
> 
> ```
> [2024-08-12 16:42:27,156] [<trace-id>] ERROR {org.wso2.carbon.identity.api.dispatcher.core.DefaultExceptionMapper} - Server encountered an error while serving the request. java.lang.NullPointerException
>     at org.wso2.carbon.identity.api.server.organization.management.v1.service.OrganizationManagementService.addOrganizationDiscoveryAttributes(OrganizationManagementService.java:388)
>     at org.wso2.carbon.identity.api.server.organization.management.v1.impl.OrganizationsApiServiceImpl.organizationDiscoveryPost(OrganizationsApiServiceImpl.java:107)
>     at org.wso2.carbon.identity.api.server.organization.management.v1.OrganizationsApi.organizationDiscoveryPost(OrganizationsApi.java:133)
>     at jdk.internal.reflect.GeneratedMethodAccessor263.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
> 	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
> 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
> 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
> 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
> 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
> 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
> 	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
> 	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
> 	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
> 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
> 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
> 	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
> 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
> 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
> 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
> 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:661)
> 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:425)
> 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:357)
> 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:294)
> 	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:147)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
> 	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:123)
> 	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
> 	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
> 	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:149)
> 	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:153)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
> 	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
> 	at org.wso2.carbon.extension.identity.x509Certificate.valve.X509CertificateAuthenticationValve.invoke(X509CertificateAuthenticationValve.java:59)
> 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
> 	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
> 	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
> 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
> 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> ```

**Expected behavior:**

> The server should return a `415 Unsupported Media Type` error instead of a `500 Internal Server Error` when the request body is missing.

**Comment by AnuradhaSK** [comment]
Fix: https://github.com/wso2/identity-api-server/pull/837


After the fix:

<img width="1287" alt="Image" src="https://github.com/user-attachments/assets/86cf7a56-8aab-450e-acb7-6ef8fad2513d" />
