### ISSUE TITLE
Unresolved requirement in UAEPass Authenticator

### ISSUE THREAD

**Issue by mifrazmurthaja** [wso2/product-is#21011]
**Describe the issue:**
The [UAEPass Authenticator](https://store.wso2.com/connector/identity-outbound-auth-uaepass) throws the following error on startup in WSO2 Identity Server 7.0.

```
[2024-08-28 19:31:44,468] [] ERROR {Events.Framework} - FrameworkEvent ERROR org.osgi.framework.BundleException: Could not resolve module: org.wso2.carbon.identity.authenticator.uaepass [274]
  Unresolved requirement: Import-Package: org.wso2.carbon.identity.application.authentication.framework; version="[5.14.0,6.0.0)"

    at org.eclipse.osgi.container.Module.start(Module.java:457)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
    at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
```

**How to reproduce:**
Deploy the UAEPass Authenticator

**Expected behavior:**
There shouldn't be any errors and the connector should work as expected.

**Environment information**
 - Product Version: IS 7.0

**Comment by lashinijay** [comment]
The latest UAEPass Authenticator containing the fix is now available in connector store.

https://store.wso2.com/connector/identity-outbound-auth-uaepass
