### ISSUE TITLE
Outbound provisioning with user exist with same name cause internal server error

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#21039]
**Describe the issue:**

```
[2024-09-03 13:06:33,039] [598a4ff5-1f84-4545-a454-480ce801caf3] ERROR {org.wso2.carbon.identity.provisioning.ProvisioningThread} -  Provisioning for Entity sakun For operation = POST org.wso2.carbon.identity.provisioning.IdentityProvisioningException: Error while creating the user : sakun
	at org.wso2.carbon.identity.provisioning.connector.scim2.SCIM2ProvisioningConnector.createUser(SCIM2ProvisioningConnector.java:184)
	at org.wso2.carbon.identity.provisioning.connector.scim2.SCIM2ProvisioningConnector.provisionUser(SCIM2ProvisioningConnector.java:149)
	at org.wso2.carbon.identity.provisioning.connector.scim2.SCIM2ProvisioningConnector.provision(SCIM2ProvisioningConnector.java:122)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:85)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:34)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.wso2.scim2.exception.IdentitySCIMException: Unable to create the User.
	at org.wso2.scim2.client.ProvisioningClient.provisionCreateUser(ProvisioningClient.java:68)
	at org.wso2.carbon.identity.provisioning.connector.scim2.SCIM2ProvisioningConnector.createUser(SCIM2ProvisioningConnector.java:182)
	... 8 more
Caused by: org.wso2.scim2.exception.IdentitySCIMException:
	at org.wso2.scim2.operation.UserOperations.createUser(UserOperations.java:78)
	at org.wso2.scim2.client.ProvisioningClient.provisionCreateUser(ProvisioningClient.java:64)
	... 9 more
Caused by: io.scim2.swagger.client.ScimApiException:
	at io.scim2.swagger.client.ScimApiClient.handleResponse(ScimApiClient.java:1152)
	at io.scim2.swagger.client.ScimApiClient.execute(ScimApiClient.java:1105)
	at io.scim2.swagger.client.api.Scimv2UsersApi.createUserWithHttpInfo(Scimv2UsersApi.java:81)
	at io.scim2.swagger.client.api.Scimv2UsersApi.createUser(Scimv2UsersApi.java:64)
	at org.wso2.scim2.operation.UserOperations.createUser(UserOperations.java:59)
	... 10 more
``

**How to reproduce:**

1. Create a user in the outbound provisioning IDP.
2. Try to create a user from the identity server which configured outbound provisioning.

**Expected behavior:**

The outbound provisioning should not happen as the user already exist. But it should not result in server error.

**Comment by sadilchamishka** [comment]
Need to check again whether handling as server error is correct or not.

For the outbound provisioning end it is a client error. For the identity server as the one who invoke the request which fails due to some reason (A user already exist in the provision end who is not tracked as provisioned user in the WSO2 identity server end) can be treated as a server error also.

![Untitled-2024-07-08-1326](https://github.com/user-attachments/assets/a70a8a29-9b93-4038-b6ec-776e6597c673)
