### ISSUE TITLE
Creating group with users who are not provisioned to the outbound fails to provision the group

### ISSUE THREAD

**Issue by sadilchamishka** [wso2/product-is#21042]
**Describe the issue:**

When provisioning group with users, if any user doesn't exist in the outbound provision end, the group creation completely failed with an server error.

```
Listening for transport dt_socket at address: 5005
[2024-09-03 18:13:42,448] [2aaf9110-4b85-48c8-a4bb-a4ee49a38d45] ERROR {org.wso2.carbon.identity.provisioning.ProvisioningThread} -  Provisioning for Entity group2 For operation = POST org.wso2.carbon.identity.provisioning.IdentityProvisioningException: Error while adding group : group2
	at org.wso2.carbon.identity.provisioning.connector.scim2.SCIM2ProvisioningConnector.createGroup(SCIM2ProvisioningConnector.java:268)
	at org.wso2.carbon.identity.provisioning.connector.scim2.SCIM2ProvisioningConnector.provisionGroup(SCIM2ProvisioningConnector.java:137)
	at org.wso2.carbon.identity.provisioning.connector.scim2.SCIM2ProvisioningConnector.provision(SCIM2ProvisioningConnector.java:124)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:85)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:34)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at org.wso2.scim2.util.SCIMDecoder.decodeListedResource(SCIMDecoder.java:59)
	at org.wso2.scim2.util.SCIMClient.decodeSCIMResponseWithListedResource(SCIMClient.java:87)
	at org.wso2.scim2.operation.AbstractOperations.listWithGet(AbstractOperations.java:113)
	at org.wso2.scim2.operation.GroupOperations.createGroup(GroupOperations.java:66)
	at org.wso2.scim2.client.ProvisioningClient.provisionCreateGroup(ProvisioningClient.java:103)
	at org.wso2.carbon.identity.provisioning.connector.scim2.SCIM2ProvisioningConnector.createGroup(SCIM2ProvisioningConnector.java:266)
	... 8 more
```

The cause for the failure is due to it tries to search the user exist, if not exist it gives an exception. It can be improved to skip the not existing users while updating the group.

**How to reproduce:**

**Expected behavior:**
At least the group should be provisioned while assigning the provisioned users to the corresponding group.

**Comment by eclrbohnhoff** [comment]
Seeing something similar.  There is no attempt to contact the SCIM server at the Groups endpoint when creating a new group:

```
[2024-12-17 15:52:44,781] [1fdcc4c3-7117-40a6-a284-4923f04bfb83] ERROR {org.wso2.carbon.identity.provisioning.ProvisioningThread} -  Provisioning for Entity group2 For operation = POST org.wso2.carbon.identity.provisioning.IdentityProvisioningException: Error while adding group : group2
        at org.wso2.carbon.identity.provisioning.connector.scim2.SCIM2ProvisioningConnector.createGroup(SCIM2ProvisioningConnector.java:268)
        at org.wso2.carbon.identity.provisioning.connector.scim2.SCIM2ProvisioningConnector.provisionGroup(SCIM2ProvisioningConnector.java:137)
        at org.wso2.carbon.identity.provisioning.connector.scim2.SCIM2ProvisioningConnector.provision(SCIM2ProvisioningConnector.java:124)
        at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:91)
        at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:34)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.wso2.scim2.exception.IdentitySCIMException: Unable to create the Group.
        at org.wso2.scim2.client.ProvisioningClient.provisionCreateGroup(ProvisioningClient.java:107)
        at org.wso2.carbon.identity.provisioning.connector.scim2.SCIM2ProvisioningConnector.createGroup(SCIM2ProvisioningConnector.java:266)
        ... 8 more
Caused by: org.wso2.scim2.exception.IdentitySCIMException:
        at org.wso2.scim2.operation.GroupOperations.createGroup(GroupOperations.java:102)
        at org.wso2.scim2.client.ProvisioningClient.provisionCreateGroup(ProvisioningClient.java:103)
        ... 9 more
Caused by: io.scim2.swagger.client.ScimApiException:
        at io.scim2.swagger.client.ScimApiClient.handleResponse(ScimApiClient.java:1152)
        at io.scim2.swagger.client.ScimApiClient.execute(ScimApiClient.java:1105)
        at io.scim2.swagger.client.api.Scimv2GroupsApi.createGroupWithHttpInfo(Scimv2GroupsApi.java:119)
        at io.scim2.swagger.client.api.Scimv2GroupsApi.createGroup(Scimv2GroupsApi.java:101)
        at org.wso2.scim2.operation.GroupOperations.createGroup(GroupOperations.java:85)
        ... 10 more
```

If I try to assign a user to this group, it will query on the SCIM server and try to add the group again but fail
(logging from my SCIM server)
```
User GET /scim/User?filter=userName%20Eq%20TestUser&startIndex=1&count=1
```

**Comment by sadilchamishka** [comment]
### There is another issue when creating user with groups

1. Create a group. That group will be outbound provisioned.
2. Create a user from the console application. Assign the group during the user creation flow.

There will be error log displayed where it fails to assign the provisioned user to the corresponding group.
