### ISSUE TITLE
Internal Server Error when refreshing token twice with pre-issue-access-token execution enabled 

### ISSUE THREAD

**Issue by ashanthamara** [wso2/product-is#21052]
**Describe the Issue:**

**How To Reproduce:**
1. Create an action for pre-issue-access-token execution.
2. Get an access token using authorization code grant.
3. Refresh the token using the refresh_token grant
4. Again refresh the token using refresg_token grant

https://github.com/user-attachments/assets/11614aae-1bc4-4270-aca4-7f903744f688

```
TID: [6613] Tenant: [ashantestableorg02] [2024-08-26 14:04:15,739] [20240826T140415Z-r17fd4bbf4fszn8xg5q79na1nn00000003zg00000000dze0] : iam-cloud-carbon : ERROR {org.wso2.carbon.identity.oauth2.OAuth2Service} - Error occurred while issuing the access token for Client ID : 2OlkmyShVuA_reX1wXgZND7VdxEa, User ID null, Scope : [] and Grant Type : refresh_token java.lang.NullPointerException: null
| at org.wso2.carbon.identity.openidconnect.DefaultOIDCClaimsCallbackHandler.getUserClaimsInOIDCDialect(DefaultOIDCClaimsCallbackHandler.java:153) ~[org.wso2.carbon.identity.oauth_7.0.146.jar:?]at org.wso2.carbon.identity.openidconnect.DefaultOIDCClaimsCallbackHandler.handleCustomClaims(DefaultOIDCClaimsCallbackHandler.java:94) ~[org.wso2.carbon.identity.oauth_7.0.146.jar:?]
| at org.wso2.carbon.identity.oauth2.token.JWTTokenIssuer.handleCustomClaims(JWTTokenIssuer.java:905) ~[org.wso2.carbon.identity.oauth_7.0.146.jar:?]
| at org.wso2.carbon.identity.oauth2.token.JWTTokenIssuer.createJWTClaimSet(JWTTokenIssuer.java:634) ~[org.wso2.carbon.identity.oauth_7.0.146.jar:?]
| at org.wso2.carbon.identity.oauth2.token.JWTTokenIssuer.buildJWTToken(JWTTokenIssuer.java:280) ~[org.wso2.carbon.identity.oauth_7.0.146.jar:?]
| at org.wso2.carbon.identity.oauth2.token.JWTTokenIssuer.accessToken(JWTTokenIssuer.java:218) ~[org.wso2.carbon.identity.oauth_7.0.146.jar:?]
| at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.createTokens(RefreshGrantHandler.java:519) ~[org.wso2.carbon.identity.oauth_7.0.146.jar:?]
| at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.setTokenData(RefreshGrantHandler.java:498) ~[org.wso2.carbon.identity.oauth_7.0.146.jar:?]
| at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.issue(RefreshGrantHandler.java:143) ~[org.wso2.carbon.identity.oauth_7.0.146.jar:?]
| at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.validateGrantAndIssueToken(AccessTokenIssuer.java:472) ~[org.wso2.carbon.identity.oauth_7.0.146.jar:?]
| at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.issue(AccessTokenIssuer.java:360) ~[org.wso2.carbon.identity.oauth_7.0.146.jar:?]
| at org.wso2.carbon.identity.oauth2.OAuth2Service.issueAccessToken(OAuth2Service.java:450) [org.wso2.carbon.identity.oauth_7.0.146.jar:?]
| at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:386) [classes/:?]
| at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:173) [classes/:?]
| at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:148) [classes/:?]
| at jdk.internal.reflect.GeneratedMethodAccessor324.invoke(Unknown Source) ~[?:?]
| at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
| at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
| at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.5.9.jar:3.5.9]
| at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.5.9.jar:3.5.9]
| at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [cxf-rt-frontend-jaxrs-3.5.9.jar:3.5.9]
| at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [cxf-rt-frontend-jaxrs-3.5.9.jar:3.5.9]
| at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.5.9.jar:3.5.9]
| at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.5.9.jar:3.5.9]
| at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) [cxf-core-3.5.9.jar:3.5.9]
| at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.5.9.jar:3.5.9]
| at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) [cxf-rt-transports-http-3.5.9.jar:3.5.9]
| at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.5.9.jar:3.5.9]
| at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.5.9.jar:3.5.9]
| at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.5.9.jar:3.5.9]
| at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) [cxf-rt-transports-http-3.5.9.jar:3.5.9]
| at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) [cxf-rt-transports-http-3.5.9.jar:3.5.9]
| at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217) [cxf-rt-transports-http-3.5.9.jar:3.5.9]
| at javax.servlet.http.HttpServlet.service(HttpServlet.java:555) [tomcat-servlet-api_9.0.82.wso2v1.jar:?]
| at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) [cxf-rt-transports-http-3.5.9.jar:3.5.9]
| at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:661) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:425) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:357) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:294) [tomcat_9.0.82.wso2v1.jar:?]
| at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:147) [org.wso2.carbon.identity.context.rewrite.valve_1.9.13.jar:?]
| at com.wso2.identity.asgardeo.throttler.request.valve.mau.MAUThrottlerValve.invoke(MAUThrottlerValve.java:94) [com.wso2.identity.asgardeo.throttler.request.valve.mau-1.1.13.jar:1.1.13]
| at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [tomcat_9.0.82.wso2v1.jar:?]
| at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:123) [org.wso2.carbon.identity.context.rewrite.valve_1.9.13.jar:?]
| at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38) [org.wso2.carbon.tomcat.ext_4.10.20.jar:?]
| at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83) [org.wso2.carbon.identity.cors.valve_1.9.13.jar:?]
| at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:177) [org.wso2.carbon.identity.authz.valve_1.9.13.jar:?]
| at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:129) [org.wso2.carbon.identity.auth.valve_1.9.13.jar:?]
| at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110) [org.wso2.carbon.tomcat.ext_4.10.20.jar:?]
| at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.10.20.jar:?]
| at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71) [org.wso2.carbon.tomcat.ext_4.10.20.jar:?]
| at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152) [org.wso2.carbon.tomcat.ext_4.10.20.jar:?]
| at org.wso2.carbon.extension.identity.x509Certificate.valve.X509CertificateAuthenticationValve.invoke(X509CertificateAuthenticationValve.java:59) [org.wso2.carbon.extension.identity.x509Certificate.valve-1.1.11.jar:?]
| at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670) [tomcat_9.0.82.wso2v1.jar:?]
| at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63) [org.wso2.carbon.tomcat.ext_4.10.20.jar:?]
| at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49) [org.wso2.carbon.tomcat.ext_4.10.20.jar:?]
| at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137) [org.wso2.carbon.tomcat.ext_4.10.20.jar:?]
| at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat_9.0.82.wso2v1.jar:?]
| at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.82.wso2v1.jar:?]
| at java.lang.Thread.run(Thread.java:829) [?:?]|

```

**Additional Context**

External Endpoint has following logic for the action requests.

```
    resource function post preIssueAccessTokenUpdateScopes(http:Request req) returns http:Response|error? {

        ActionSuccessResponse respBody;
        http:Response resp = new;
        log:printInfo("Request Received to Update Scopes of the access token");
        json requestPayload = <json> check req.getJsonPayload();
        json grantType = check requestPayload.toJson().event.request.grantType;
        if (grantType == "refresh_token") {
            log:printInfo("Grant Type is refresh_token");
            respBody = {
                "actionStatus": SUCCESS,
                "operations": [
                    {
                        op: REMOVE,
                        path: "/accessToken/scopes/0"
                    }
                ]
            };
        } else {
            respBody = {
                "actionStatus": SUCCESS,
                "operations": [
                    {
                        op: ADD,
                        path: "/accessToken/scopes/-",
                        value: "test_api_perm_3"
                    },
                    {
                        op: ADD,
                        path: "/accessToken/scopes/0",
                        value: "test_api_perm_2"
                    },
                    {
                        op: REMOVE,
                        path: "/accessToken/scopes/0"
                    },
                    {
                        op: REPLACE,
                        path: "/accessToken/scopes/1",
                        value: "test_api_perm_1"
                    }
                ]
            };
        }
        resp.statusCode = 200;
        resp.setJsonPayload(respBody.toJson());

        return resp;
    }
```

**Expected behavior:**
1. An access token should be issued.

**Related Issue**
-

**Comment by ashanthamara** [comment]
This issue was reproducible only with the actions configured in a tenant. 
However this was fixed with the other improvements carried out in the extensions. 
Hence closing the issue since it is not reproducing.
