### ISSUE TITLE
Getting NPE on session nonce cookie validation failure

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#21298]
**Describe the issue:**
Getting NPE when session none cookie validation fails more than once.

```
"  WARN {org.wso2.carbon.identity.application.authentication.framework.CommonAuthenticationHandler} - Session nonce cookie validation has failed for the sessionDataKey: 9694b08d-e401-49a0-8976-4e6f039dc094. Hence, restarting the login flow."

ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework java.lang.NullPointerException: null|
at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:246) [org.wso2.carbon.identity.application.authentication.framework_7.5.26.jar:?]|
at org.wso2.carbon.identity.application.authentication.framework.CommonAuthenticationHandler.doPost(CommonAuthenticationHandler.java:62) [org.wso2.carbon.identity.application.authentication.framework_7.5.26.jar:?]|
at org.wso2.carbon.identity.application.authentication.framework.CommonAuthenticationHandler.doGet(CommonAuthenticationHandler.java:46) [org.wso2.carbon.identity.application.authentication.framework_7.5.26.jar:?]|
at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:54) [org.wso2.carbon.identity.application.authentication.framework_7.5.26.jar:?]|
at javax.servlet.http.HttpServlet.service(HttpServlet.java:555) [tomcat-servlet-api_9.0.82.wso2v1.jar:?]|
at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) [tomcat-servlet-api_9.0.82.wso2v1.jar:?]|
at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) [org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]|
at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]|
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]|
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]|
at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) [tomcat-servlet-api_9.0.82.wso2v1.jar:?]|
at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) [org.wso2.carbon.tomcat.ext_4.10.22.jar:?]|
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [tomcat_9.0.82.wso2v1.jar:?]|
at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:99) [org.wso2.carbon.identity.captcha_1.11.3.jar:?]|
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [tomcat_9.0.82.wso2v1.jar:?]|
at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:72) [csrfguard_3.1.0.wso2v4.jar:?]|
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [tomcat_9.0.82.wso2v1.jar:?]|
at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65) [org.wso2.carbon.tomcat.ext_4.10.22.jar:?]|
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:129) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) [tomcat_9.0.82.wso2v1.jar:?]|
at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119) [org.wso2.carbon.identity.context.rewrite.valve_1.9.13.jar:?]|
at com.wso2.identity.asgardeo.throttler.request.valve.mau.MAUThrottlerValve.invoke(MAUThrottlerValve.java:94) [com.wso2.identity.asgardeo.throttler.request.valve.mau-1.1.13.jar:1.1.13]|
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [tomcat_9.0.82.wso2v1.jar:?]|
at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:123) [org.wso2.carbon.identity.context.rewrite.valve_1.9.13.jar:?]|
at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38) [org.wso2.carbon.tomcat.ext_4.10.22.jar:?]|
at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:77) [org.wso2.carbon.identity.cors.valve_1.9.13.jar:?]|
at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:177) [org.wso2.carbon.identity.authz.valve_1.9.13.jar:?]|
at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:129) [org.wso2.carbon.identity.auth.valve_1.9.13.jar:?]|
at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110) [org.wso2.carbon.tomcat.ext_4.10.22.jar:?]|
at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.10.22.jar:?]|
at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71) [org.wso2.carbon.tomcat.ext_4.10.22.jar:?]|
at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152) [org.wso2.carbon.tomcat.ext_4.10.22.jar:?]|
at org.wso2.carbon.extension.identity.x509Certificate.valve.X509CertificateAuthenticationValve.invoke(X509CertificateAuthenticationValve.java:59) [org.wso2.carbon.extension.identity.x509Certificate.valve-1.1.11.jar:?]|
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670) [tomcat_9.0.82.wso2v1.jar:?]|
at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63) [org.wso2.carbon.tomcat.ext_4.10.22.jar:?]|
at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49) [org.wso2.carbon.tomcat.ext_4.10.22.jar:?]|
at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137) [org.wso2.carbon.tomcat.ext_4.10.22.jar:?]|
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat_9.0.82.wso2v1.jar:?]|
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.82.wso2v1.jar:?]|
at java.lang.Thread.run(Thread.java:829) [?:?]|"
```

**How to reproduce:**
1. In IS console create an app and add 3 login steps (can use IDF + username/password + email otp)
2. Setup a sample app for logging in
3. Add a new user
4. In your browser access the sample app login page and complete the first login step
5. Copy the browser url and paste it in an incognito window
6. Complete the second login step (since nonce cookie validation fails, you will be asked to restart from 1st step). Complete only upto 2nd step.
7. Copy the browser url and paste it in another browser window
8. Try to complete the login process

You will end up in a blank page, and the server logs will indicate an NPE.

**Comment by Yoshani** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/6004
