### ISSUE TITLE
Wrong error is returned when a tenat is created with invalid claims

### ISSUE THREAD

**Issue by hwupathum** [wso2/product-is#21346]
**Describe the issue:**
When a tenant is created via api with an invalid claim (where claim validation fails). The tenant is created without the invalid claim, but  an internal server error (500) is returned.

**How to reproduce:**
Try the following curl command to create a tenant with an invalid telephone number.
```
curl --location 'https://localhost:9443/api/server/v1/tenants' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
    "domain": "wso2.com",
    "owners": [
        {
            "username": "kim1",
            "firstname": "kimber",
            "lastname": "noo",
            "password": "kim123",
            "email": "kim@wso2.com",
            "provisioningMethod": "inline-password",
            "additionalClaims": [
                {
                    "claim": "http://wso2.org/claims/telephone",
                    "value": "+94 562 8723"
                }
            ]
        }
    ]
}'
```

Following error is thrown, and 500 code is returned as the API response.
```
[2024-10-14 13:16:29,458] [308e75e9-636c-45a6-a4d3-23ff8fa9850c] ERROR {org.wso2.carbon.identity.api.server.tenant.management.v1.core.ServerTenantManagementService} - errorCode: TM-65002 | message: Server encountered an error while adding the tenant. org.wso2.carbon.stratos.common.exception.TenantManagementServerException: Error in adding claims to the user.
	at org.wso2.carbon.tenant.mgt.util.TenantMgtUtil.addAdditionalClaimsToUserStoreManager(TenantMgtUtil.java:535)
	at org.wso2.carbon.tenant.mgt.services.TenantMgtImpl.addAdditionalClaimsToUserStore(TenantMgtImpl.java:405)
	at org.wso2.carbon.tenant.mgt.services.TenantMgtImpl.registerTenant(TenantMgtImpl.java:115)
	at org.wso2.carbon.tenant.mgt.services.TenantMgtImpl.addTenant(TenantMgtImpl.java:77)
	at org.wso2.carbon.identity.api.server.tenant.management.v1.core.ServerTenantManagementService.addTenant(ServerTenantManagementService.java:95)
	at org.wso2.carbon.identity.api.server.tenant.management.v1.impl.TenantsApiServiceImpl.addTenant(TenantsApiServiceImpl.java:42)
	at org.wso2.carbon.identity.api.server.tenant.management.v1.TenantsApi.addTenant(TenantsApi.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:123)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:149)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:153)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.wso2.carbon.extension.identity.x509Certificate.valve.X509CertificateAuthenticationValve.invoke(X509CertificateAuthenticationValve.java:59)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.wso2.carbon.user.core.UserStoreClientException: Telephone is not in the correct format.
	at org.wso2.carbon.identity.scim2.common.listener.SCIMUserOperationListener.validateClaimValueForRegex(SCIMUserOperationListener.java:272)
	at org.wso2.carbon.identity.scim2.common.listener.SCIMUserOperationListener.validateClaimValue(SCIMUserOperationListener.java:555)
	at org.wso2.carbon.identity.scim2.common.listener.SCIMUserOperationListener.doPreSetUserClaimValuesWithID(SCIMUserOperationListener.java:369)
	at org.wso2.carbon.identity.mgt.listener.IdentityUserIdResolverListener.doPreSetUserClaimValues(IdentityUserIdResolverListener.java:389)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.setUserClaimValues(AbstractUserStoreManager.java:4612)
	at org.wso2.carbon.tenant.mgt.util.TenantMgtUtil.addAdditionalClaimsToUserStoreManager(TenantMgtUtil.java:530)
	... 63 more
```

**Comment by hwupathum** [comment]
With the following PR https://github.com/wso2/identity-api-server/pull/704, the error response code is changed to 206 and the following error response it returned.
```
{
    "code": "TM-60021",
    "message": "Tenant creation / update was completed with errors.",
    "description": "Tenant creation / update was completed with error: Telephone is not in the correct format.",
    "traceId": "b4d7d5c4-525c-43e0-917a-fd03dbe52628"
}
```
