### ISSUE TITLE
Assigned Users of Groups Not Loading After Update

### ISSUE THREAD

**Issue by Pratheesha97** [wso2/product-is#21397]
**Describe the issue:**

After updating WSO2 IS 7.0.0 to update level 73, users do not appear when viewing the "Assigned Users" of a specific group in the "Groups" interface. The user list keeps loading indefinitely due to an IndexOutOfBoundsException.

Below is the relevant stack trace:

```
[2024-10-17 22:51:51,621] [1b66d13f-c0a3-4b26-b619-65362ba5cc98]  WARN {org.apache.cxf.phase.PhaseInterceptorChain} - Exception in handleFault on interceptor org.apache.cxf.jaxrs.interceptor.JAXRSDefaultFaultOutInterceptor@6c4da24f org.apache.cxf.interceptor.Fault: toIndex = 2147483647
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:162)
........
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 2147483647
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
```

```
[2024-10-17 22:51:51,626] [1b66d13f-c0a3-4b26-b619-65362ba5cc98] ERROR {org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver} - An unexpected error occurred during error handling. No further error processing will occur. org.apache.cxf.interceptor.Fault: toIndex = 2147483647
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:162)
.......
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 2147483647
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1138)
```

```
[2024-10-17 22:51:51,632] [1b66d13f-c0a3-4b26-b619-65362ba5cc98] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/scim2].[SCIM2Servlet]} - Servlet.service() for servlet [SCIM2Servlet] threw exception java.lang.IndexOutOfBoundsException: toIndex = 2147483647
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1138)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.paginateUsers(SCIMUserManager.java:4918)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.filterUsersByGroup(SCIMUserManager.java:1639)
```

```
[2024-10-17 22:51:51,637] [1b66d13f-c0a3-4b26-b619-65362ba5cc98] ERROR {org.wso2.carbon.tomcat.ext.valves.CompositeValve} - Could not handle request: /t/carbon.super/scim2/Users java.lang.IndexOutOfBoundsException: toIndex = 2147483647
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:507)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1138)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.paginateUsers(SCIMUserManager.java:4918)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.filterUsersByGroup(SCIMUserManager.java:1639)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getFilteredUsersCount(SCIMUserManager.java:1696)
```

**How to reproduce:**

1. Navigate to the Console.
2. Create a user and assign that user to a group.
3. Go to User Management -> Groups and select the relevant group.
4. Click on the "Users" tab to view the assigned users.
5. The "Assigned Users" list does not load.

**Expected behavior:**

Users assigned to the group should be listed under the "Users" tab of the selected group.

**Environment information:**
 - Product Version: IS 7.0.0

---

**Comment by sadilchamishka** [comment]
Tracked with https://github.com/wso2/product-is/issues/21410
