### ISSUE TITLE
Error during password reset

### ISSUE THREAD

**Issue by Yoshani** [wso2/product-is#21488]
**Describe the issue:**
NPE thrown during password reset flow.

```
TID: [7489] Tenant: [xxxxxxxxx] [2024-10-24 20:25:46,616] [1234] : iam-cloud-carbon : ERROR {org.wso2.carbon.identity.recovery.endpoint.impl.RecoverPasswordApiServiceImpl} - Error occurred in the server while performing the task. java.lang.NullPointerException: null| at org.wso2.carbon.identity.event.handler.notification.util.NotificationUtil.buildNotification(NotificationUtil.java:732) ~[org.wso2.carbon.identity.event.handler.notification_1.9.11.jar:?]| at org.wso2.carbon.identity.event.handler.notification.NotificationHandler.handleEvent(NotificationHandler.java:95) ~[org.wso2.carbon.identity.event.handler.notification_1.9.11.jar:?]| at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56) ~[org.wso2.carbon.identity.event_7.5.72.jar:?]| at org.wso2.carbon.identity.recovery.password.NotificationPasswordRecoveryManager.triggerNotification(NotificationPasswordRecoveryManager.java:1062) ~[org.wso2.carbon.identity.recovery_1.11.8.jar:?]| at org.wso2.carbon.identity.recovery.password.NotificationPasswordRecoveryManager.sendRecoveryNotification(NotificationPasswordRecoveryManager.java:209) ~[org.wso2.carbon.identity.recovery_1.11.8.jar:?]| at org.wso2.carbon.identity.recovery.endpoint.impl.RecoverPasswordApiServiceImpl.recoverPasswordPost(RecoverPasswordApiServiceImpl.java:84) [org.wso2.carbon.identity.api.user.recovery-1.11.8.jar:1.11.8]| at org.wso2.carbon.identity.recovery.endpoint.RecoverPasswordApi.recoverPasswordPost(RecoverPasswordApi.java:45) [org.wso2.carbon.identity.api.user.recovery-1.11.8.jar:1.11.8]| at jdk.internal.reflect.GeneratedMethodAccessor1402.invoke(Unknown Source) ~[?:?]| at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]| at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]| at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.5.9.jar:3.5.9]| at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.5.9.jar:3.5.9]| at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [cxf-rt-frontend-jaxrs-3.5.9.jar:3.5.9]| at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [cxf-rt-frontend-jaxrs-3.5.9.jar:3.5.9]| at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.5.9.jar:3.5.9]| at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.5.9.jar:3.5.9]| at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) [cxf-core-3.5.9.jar:3.5.9]| at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.5.9.jar:3.5.9]| at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) [cxf-rt-transports-http-3.5.9.jar:3.5.9]| at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.5.9.jar:3.5.9]| at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.5.9.jar:3.5.9]| at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.5.9.jar:3.5.9]| at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) [cxf-rt-transports-http-3.5.9.jar:3.5.9]| at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) [cxf-rt-transports-http-3.5.9.jar:3.5.9]| at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217) [cxf-rt-transports-http-3.5.9.jar:3.5.9]| at javax.servlet.http.HttpServlet.service(HttpServlet.java:555) [tomcat-servlet-api_9.0.82.wso2v1.jar:?]| at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) [cxf-rt-transports-http-3.5.9.jar:3.5.9]| at
```

**Comment by Yoshani** [comment]
The NPE occurs do to the error code being null and the equality is not checked in the correct order at [1]. The thrown NPE hides the true root cause.

To correctly identify the root cause we need to fix the NPE and add some debug logs.

[1] https://github.com/wso2-extensions/identity-event-handler-notification/blob/d4cddcaf67ce6996a0dec4077d46e994f82f62fa/components/event-handler-notification/org.wso2.carbon.identity.event.handler.notification/src/main/java/org/wso2/carbon/identity/event/handler/notification/util/NotificationUtil.java#L732

**Comment by Yoshani** [comment]
The issue occurs due to an erroneous value set as locale by the user.

**Comment by Yoshani** [comment]
Fixes:
- https://github.com/wso2-extensions/identity-event-handler-notification/pull/270
- https://github.com/wso2-extensions/identity-event-handler-notification/pull/271
