### ISSUE TITLE
`httpGet` fails silently if response is not a JSON object

### ISSUE THREAD

**Issue by edokan** [wso2/product-is#21497]
**Describe the issue:**
I developed a service that returns a JSON array and called that service within a conditional authentication script via `httpGet.` It never executes `onSuccess` or `onFail`; instead, it executes undocumented `onTimeout`. Logs show the following line:

    This is a continuation of long wait process: 58bc0122-7e66-47a1-b0ae-41ff2855a861. The long wait status is WAITING

After removing some of my hair, I tried returning a simple object with a property that contained the intended array result. It started working like a charm.

**How to reproduce:**

  * Develop a service that returns a JSON array
  * Call that service using `httpGet` and observe neither `onSuccess` or `onFail` is called.

**Expected behavior:**

Error logs indicating that it somehow could not parse the JSON and documentation indicates method expects a JSON object.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0
 - OS: Windows 11 Pro, MacOS Ventura, Ubuntu Linux 20.04
 - Database: H2 on Windows and Mac, MSSQL on Linux
 - Userstore: JDBC, default primary user store

---

### Optional Fields

**Related issues:**

**Suggested labels:**
[Component/Adaptive Auth](https://github.com/wso2/product-is/labels/Component%2FAdaptive%20Auth)
[Type/Bug](https://github.com/wso2/product-is/issues?q=is%3Aopen+label%3AType%2FBug)
[Type/Docs](https://github.com/wso2/product-is/issues?q=is%3Aopen+label%3AType%2FDocs)

**Comment by janakamarasena** [comment]
I tested this with the current master branch and it gives the following stacktrace and triggers the onFail block. The change in the behaviour should be due to switching scripting engine to GraalJs. However I noticed that the was a loop happening during this flow as I saw the same error printing multiple times before proceeding. We need to check whats happening there. Given this is happening in an erroneous flow and we have clearly documented what is being accepted as the response I am reducing the severity of this issue.

```
[2025-01-21 12:46:41,975] [9226ae73-243c-40d7-aaf1-272b9715b5cf]  INFO {org.wso2.carbon.identity.application.authentication.framework.config.model.graph.js.JsLogger} - org.wso2.carbon.identity.application.authentication.framework.config.model.graph.js.graaljs.JsGraalWritableParameters@31b065bd
[2025-01-21 12:47:41,157] [e8bd2e9d-0ef6-4c33-8a85-e1ed57ec7d86] ERROR {org.wso2.carbon.identity.conditional.auth.functions.http.AbstractHTTPFunction} - Error while calling endpoint. java.lang.ClassCastException: class org.json.simple.JSONArray cannot be cast to class org.json.simple.JSONObject (org.json.simple.JSONArray and org.json.simple.JSONObject are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @19bad5ec)
	at org.wso2.carbon.identity.conditional.auth.functions.http.AbstractHTTPFunction.executeRequest(AbstractHTTPFunction.java:207)
	at org.wso2.carbon.identity.conditional.auth.functions.http.AbstractHTTPFunction.lambda$executeHttpMethod$0(AbstractHTTPFunction.java:126)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.AsyncSequenceExecutor$ObservingAsyncProcess.call(AsyncSequenceExecutor.java:160)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.AsyncSequenceExecutor$ObservingAsyncProcess.access$100(AsyncSequenceExecutor.java:144)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.AsyncSequenceExecutor$AsyncCallerTask.run(AsyncSequenceExecutor.java:96)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.wso2.carbon.identity.core.ThreadLocalAwareThreadPoolExecutor.lambda$wrapWithMdcContext$0(ThreadLocalAwareThreadPoolExecutor.java:90)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
