### ISSUE TITLE
Error when loading Policy Administration in Carbon Console

### ISSUE THREAD

**Issue by JeethJJ** [wso2/product-is#21526]
**Describe the issue:**
Policy Administration in carbon console directs to an empty page when the url is `https://localhost:9443/carbon/entitlement/index.jsp?region=region1&item=policy_pap_menu`. 

<img width="1512" alt="Screenshot 2024-10-29 at 09 43 17" src="https://github.com/user-attachments/assets/a4fbbcf8-7b01-4ded-b991-fcefc4547862">

But the url `https://localhost:9443/carbon/entitlement/index.jsp` views the page. 

So, with params the following stacktrace is observed.

```
Caused by: org.apache.jasper.JasperException: An exception occurred processing [/entitlement/index.jsp] at line [35]

32: <%@ page import="org.owasp.encoder.Encode" %>
33: <jsp:useBean id="entitlementPolicyBean" type="org.wso2.carbon.identity.entitlement.ui.EntitlementPolicyBean"
34:              class="org.wso2.carbon.identity.entitlement.ui.EntitlementPolicyBean" scope="session"/>
35: <jsp:setProperty name="entitlementPolicyBean" property="*" />
36: <jsp:include page="../dialog/display_messages.jsp"/>
37: 
38: <%


Stacktrace:
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:610)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:489)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:379)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:327)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:661)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:537)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:480)
	at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:37)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor$RequestDispatcherAdaptor.include(ContextPathServletAdaptor.java:369)
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:994)
	at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:479)
	at org.apache.tiles.jsp.context.JspUtil.doInclude(JspUtil.java:98)
	... 97 more
Caused by: org.apache.jasper.JasperException: org.apache.jasper.JasperException: Cannot find any information on property [region] in a bean of type [org.wso2.carbon.identity.entitlement.ui.EntitlementPolicyBean]
	at org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(JspRuntimeLibrary.java:376)
	at org.apache.jasper.runtime.JspRuntimeLibrary.introspect(JspRuntimeLibrary.java:310)
	at org.apache.jsp.entitlement.index_jsp._jspService(index_jsp.java:201)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:466)
	... 119 more
Caused by: org.apache.jasper.JasperException: Cannot find any information on property [region] in a bean of type [org.wso2.carbon.identity.entitlement.ui.EntitlementPolicyBean]
	at org.apache.jasper.runtime.JspRuntimeLibrary.getWriteMethod(JspRuntimeLibrary.java:813)
	at org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(JspRuntimeLibrary.java:325)
	... 124 more
```

**How to reproduce:**
1. Start IS pack
2. Load management console
3. Navigate to Main -> Entitlement -> PAP -> Policy Administration

**Comment by Thumimku** [comment]
We removed this UI with https://github.com/wso2/product-is/issues/21675, hence we don't need to fix this.

**Comment by JeethJJ** [comment]
This can be closed as the feature is removed from the management console.
