### ISSUE TITLE
Username recovery faliure with Oracle DB due to incorrect SQL 

### ISSUE THREAD

**Issue by LahiruLS** [wso2/product-is#21564]
**Describe the issue:**
Setup WSO2 IS 7.0.0 with Oracle 19c and try username recovery flow.

During the UserName recovery flow with IS 7.0.0 and Oracle 19c database, It was observed an Internal Server error from the UI. At the wso2 carbon logs below exception was logged,

```
TID: [-1234] [api] [2024-10-25 09:58:50,043] [xxxxxxxxxxxxx] DEBUG {org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager} - Error occurred while fetching user list for multi-attribute searching java.sql.SQLSyntaxErrorException: ORA-00904: "UA"."UM_ATTR_VALUE": invalid identifier

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:526)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:462)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:553)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:270)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:91)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:807)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:991)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1176)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3671)
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1426)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3718)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1167)
	at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy49.executeQuery(Unknown Source)
	at org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager.executeQueryAndGetUsers(UniqueIDJDBCUserStoreManager.java:3539)
	at org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager.doGetUserListWithID(UniqueIDJDBCUserStoreManager.java:3471)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getFilteredUsers(AbstractUserStoreManager.java:16734)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserListWithID(AbstractUserStoreManager.java:16615)
	at org.wso2.carbon.identity.recovery.internal.service.impl.UserAccountRecoveryManager.getUsernameByClaims(UserAccountRecoveryManager.java:316)
	at org.wso2.carbon.identity.recovery.internal.service.impl.username.UsernameRecoveryManagerImpl.initiate(UsernameRecoveryManagerImpl.java:93)
	at org.wso2.carbon.identity.recovery.username.NotificationUsernameRecoveryManager.initiateUsernameRecovery(NotificationUsernameRecoveryManager.java:185)
	at org.wso2.carbon.identity.recovery.username.NotificationUsernameRecoveryManager.verifyUsername(NotificationUsernameRecoveryManager.java:155)
	at org.wso2.carbon.identity.recovery.endpoint.impl.RecoverUsernameApiServiceImpl.recoverUsernamePost(RecoverUsernameApiServiceImpl.java:35)
	at org.wso2.carbon.identity.recovery.endpoint.RecoverUsernameApi.recoverUsernamePost(RecoverUsernameApi.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:555)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:123)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:211)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:146)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.wso2.carbon.extension.identity.x509Certificate.valve.X509CertificateAuthenticationValve.invoke(X509CertificateAuthenticationValve.java:59)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: Error : 904, Position : 360, Sql = SELECT UM_USER_ID, UM_USER_NAME FROM (SELECT UM_USER_ID, UM_USER_NAME, rownum AS rnum FROM (SELECT U.UM_USER_ID, U.UM_USER_NAME FROM UM_ROLE R INNER JOIN UM_USER_ROLE UR ON R.UM_ID = UR.UM_ROLE_ID INNER JOIN UM_USER U ON UR.UM_USER_ID =U.UM_ID WHERE U.UM_TENANT_ID = :1  AND UA.UM_TENANT_ID = :2  AND UA.UM_PROFILE_ID = :3  AND UA.UM_ATTR_NAME = :4  AND LOWER(UA.UM_ATTR_VALUE) = LOWER(:5 ) INTERSECT SELECT UM_USER_ID, UM_USER_NAME FROM (SELECT UM_USER_ID, UM_USER_NAME, rownum AS rnum FROM (SELECT U.UM_USER_ID, U.UM_USER_NAME FROM UM_ROLE R INNER JOIN UM_USER_ROLE UR ON R.UM_ID = UR.UM_ROLE_ID INNER JOIN UM_USER U ON UR.UM_USER_ID =U.UM_ID WHERE U.UM_TENANT_ID = :6  AND UA.UM_TENANT_ID = :7  AND UA.UM_PROFILE_ID = :8  AND UA.UM_ATTR_NAME = :9  AND LOWER(UA.UM_ATTR_VALUE) = LOWER(:10 ) INTERSECT SELECT UM_USER_ID, UM_USER_NAME FROM (SELECT UM_USER_ID, UM_USER_NAME, rownum AS rnum FROM (SELECT U.UM_USER_ID, U.UM_USER_NAME FROM UM_ROLE R INNER JOIN UM_USER_ROLE UR ON R.UM_ID = UR.UM_ROLE_ID INNER JOIN UM_USER U ON UR.UM_USER_ID =U.UM_ID WHERE U.UM_TENANT_ID = :11  AND UA.UM_TENANT_ID = :12  AND UA.UM_PROFILE_ID = :13  AND UA.UM_ATTR_NAME = :14  AND LOWER(UA.UM_ATTR_VALUE) = LOWER(:15 )) ) ) )ORDER BY UM_USER_NAME ) where rownum <= :16 ) WHERE  rnum > :17 , OriginalSql = SELECT UM_USER_ID, UM_USER_NAME FROM (SELECT UM_USER_ID, UM_USER_NAME, rownum AS rnum FROM (SELECT U.UM_USER_ID, U.UM_USER_NAME FROM UM_ROLE R INNER JOIN UM_USER_ROLE UR ON R.UM_ID = UR.UM_ROLE_ID INNER JOIN UM_USER U ON UR.UM_USER_ID =U.UM_ID WHERE U.UM_TENANT_ID = ? AND UA.UM_TENANT_ID = ? AND UA.UM_PROFILE_ID = ? AND UA.UM_ATTR_NAME = ? AND LOWER(UA.UM_ATTR_VALUE) = LOWER(?) INTERSECT SELECT UM_USER_ID, UM_USER_NAME FROM (SELECT UM_USER_ID, UM_USER_NAME, rownum AS rnum FROM (SELECT U.UM_USER_ID, U.UM_USER_NAME FROM UM_ROLE R INNER JOIN UM_USER_ROLE UR ON R.UM_ID = UR.UM_ROLE_ID INNER JOIN UM_USER U ON UR.UM_USER_ID =U.UM_ID WHERE U.UM_TENANT_ID = ? AND UA.UM_TENANT_ID = ? AND UA.UM_PROFILE_ID = ? AND UA.UM_ATTR_NAME = ? AND LOWER(UA.UM_ATTR_VALUE) = LOWER(?) INTERSECT SELECT UM_USER_ID, UM_USER_NAME FROM (SELECT UM_USER_ID, UM_USER_NAME, rownum AS rnum FROM (SELECT U.UM_USER_ID, U.UM_USER_NAME FROM UM_ROLE R INNER JOIN UM_USER_ROLE UR ON R.UM_ID = UR.UM_ROLE_ID INNER JOIN UM_USER U ON UR.UM_USER_ID =U.UM_ID WHERE U.UM_TENANT_ID = ? AND UA.UM_TENANT_ID = ? AND UA.UM_PROFILE_ID = ? AND UA.UM_ATTR_NAME = ? AND LOWER(UA.UM_ATTR_VALUE) = LOWER(?)) ) ) )ORDER BY UM_USER_NAME ) where rownum <= ?) WHERE  rnum > ?, Error Msg = ORA-00904: "UA"."UM_ATTR_VALUE": invalid identifier

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:530)
	... 86 more
```

This issue is a regression issue caused by [1]. The join with the user attribute table (UM_USER_ATTRIBUTE UA) was removed but the "where" is still referencing it [2]. 

[1] https://github.com/wso2-support/carbon-kernel/pull/2522
[2] https://github.com/wso2-support/carbon-kernel/blob/support-4.10.9.x-full/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/jdbc/UniqueIDJDBCUserStoreManager.java#L4412

**How to reproduce:**
Setup WSO2 IS 7.0.0 with Oracle 19c and try username recovery flow.

**Expected behavior:**
Able to recover username

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.0.0
 - OS: Any
 - Database: Oracle 19
 - Userstore: JDBC

**Comment by sahandilshan** [comment]
This is fixed in public with https://github.com/wso2/carbon-kernel/pull/4046
