### ISSUE TITLE
Error When Starting Server with Oracle DB - Invalid Column Name

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#21593]
**Describe the Issue:**

An error occurs when starting WSO2 Identity Server with Oracle DB. The error is logged in the server logs as follows:

`[2024-11-04 03:29:14,757] ERROR {org.wso2.carbon.identity.api.server.application.management.v1.core.functions.Utils} - errorCode: APP-65001 | message: Error while loading applications from DB: ORA-17006: Invalid column name`

Stack Trace: The error occurs when the server attempts to load application information from the database. The relevant portion of the stack trace is:

```

2024-11-04 03:29:14,757] [bfedab46-7eb7-4242-847f-ce52371c3eda] ERROR {org.wso2.carbon.identity.api.server.application.management.v1.core.functions.Utils} - errorCode: APP-65001 | message: Error while loading applications from DB: ORA-17006: Invalid column name
https://docs.oracle.com/error-help/db/ora-17006/ org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error while loading applications from DB: ORA-17006: Invalid column name
https://docs.oracle.com/error-help/db/ora-17006/
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getApplicationBasicInfo(ApplicationDAOImpl.java:2173)
	at org.wso2.carbon.identity.application.mgt.dao.impl.CacheBackedApplicationDAO.getApplicationBasicInfo(CacheBackedApplicationDAO.java:355)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.getApplicationBasicInfo(ApplicationManagementServiceImpl.java:607)
	at org.wso2.carbon.identity.api.server.application.management.v1.core.ServerApplicationManagementService.getAllApplications(ServerApplicationManagementService.java:291)
	at org.wso2.carbon.identity.api.server.application.management.v1.impl.ApplicationsApiServiceImpl.getAllApplications(ApplicationsApiServiceImpl.java:82)
	at org.wso2.carbon.identity.api.server.application.management.v1.ApplicationsApi.getAllApplications(ApplicationsApi.java:486)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:119)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.wso2.carbon.identity.context.rewrite.valve.OrganizationContextRewriteValve.invoke(OrganizationContextRewriteValve.java:123)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:83)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:177)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:153)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:110)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:71)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:152)
	at org.wso2.carbon.extension.identity.x509Certificate.valve.X509CertificateAuthenticationValve.invoke(X509CertificateAuthenticationValve.java:59)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLException: ORA-17006: Invalid column name
https://docs.oracle.com/error-help/db/ora-17006/
	at oracle.jdbc.driver.OracleStatement.getColumnIndexPrimitive(OracleStatement.java:4990)
	at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.java:4948)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.findColumn(InsensitiveScrollableResultSet.java:385)
	at oracle.jdbc.driver.GeneratedResultSet.getString(GeneratedResultSet.java:648)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.buildApplicationBasicInfo(ApplicationDAOImpl.java:6339)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getApplicationBasicInfo(ApplicationDAOImpl.java:2168)
	... 62 more
```

**How To Reproduce:**

- Configure WSO2 Identity Server to use an Oracle database.
- Start the server.
- Check the server logs for errors.
- 
**Expected behavior:**
No issues should be server startup

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 7.1.0-M1
 - OS: Ubuntu 22.04
 - Database: Oracle 19c
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by aaujayasena** [comment]
This is reproducible when you attempt to retrieve the applications.

**Comment by darshanasbg** [comment]
Fails when trying to get the APP_NAME.
https://github.com/wso2/carbon-identity-framework/blob/v7.5.89/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/dao/impl/ApplicationDAOImpl.java#L6339

**Comment by nilasini** [comment]
@mpmadhavig Suspecting the latest change regarding the APP version can be cause this issue? Did we test the fix with oracle? If not shall we check it?
