### ISSUE TITLE
Deadlock occur with concurrent request for session extend API with the same session

### ISSUE THREAD

**Issue by Tiffany-silva** [wso2/product-is#21670]
**Describe the issue:**
When concurrent session extending requests for the same session are received, deadlocks occur with the following exception in the `IDN_AUTH_SESSION_META_DATA` table:
```
ERROR {org.wso2.carbon.identity.application.authentication.framework.util.FrameworkUtils} - Updating session meta data failed. org.wso2.carbon.identity.application.authentication.framework.exception.UserSessionException: Error while updating Last Access Time of session:9797sdsdhsf0ef233a1ea52ae4925374d7b8fbcfcd30ef6ea849b18b0952 in table `IDN_AUTH_SESSION_META_DATA`.
	at org.wso2.carbon.identity.application.authentication.framework.store.UserSessionStore.updateSessionMetaData(UserSessionStore.java:722)
	at org.wso2.carbon.identity.application.authentication.framework.util.FrameworkUtils.updateSessionLastAccessTimeMetadata(FrameworkUtils.java:2857)
```

Although this is an edge case, this behaviour could occur when the session extend API is invoked multiple times concurrently with the same session data key. 
Analysing the error, we identified that the `UserSessionStore`[1] doesn't use a synchronise block similar to the `sessionDataStore` [2]. Therefore, we need to use an approach similar to the `sessionDataStore`[2] to avoid such behaviours leading to a pool exhaustion. 

[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/UserSessionStore.java#L78

[2] https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/SessionDataStore.java#L299

**How to reproduce:**
1. Invoke the session extend API with the same session data key concurrently.

**Expected behavior:**
1. Deadlocks shouldn't occur.

**Environment information:**
 - Product Version: IS 5.11.0

**Comment by Tiffany-silva** [comment]
Not applicable as eager initialisation is used [1].
[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/UserSessionStore.java#L59
