### ISSUE TITLE
PUT `/api/users/v1/{user-id}/idv/claims` API Fails to Update Identity Verification Claims Properly

### ISSUE THREAD

**Issue by AfraHussaindeen** [wso2/product-is#22120]
## **Description**:  
The **Identity Verification Claim Management API** `PUT /api/users/v1/{user-id}/idv/claims`[[1]](https://github.com/wso2/identity-api-user/blob/89a1bc51e5f0b56b4d25bde8ce6ff22de12142c2/components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/main/resources/idv.yaml#L353-L417) does not handle updates to identity verification claims correctly.  

---

## **Issue 1: Updating Existing Claims**  

- **Current Behavior:**  

When attempting to update an existing identity verification claim, the following error response is returned:  
```json
{
    "code": "IDV-10004",
    "message": "Identity verification claim data already exists.",
    "description": "Identity verification claim data already exists for the user: e6095866-68b8-44ed-a506-5ad7fa7a7961.",
    "traceId": "6ae691bd-503e-43bb-930a-fde43ec0fab0"
}
```
<img width="1061" alt="Screenshot 2024-12-30 at 14 08 16" src="https://github.com/user-attachments/assets/783d0838-c540-495a-9be7-404fc4918460" />

- **Expected Behavior:**  

Since the identity verification claim already exists, the update operation should be successful. The API should return the **updated claim details** as the response.   If the update fails, the response should indicate the reason for failure with the appropriate error code.  

- **Root Cause:**  

The issue occurs because the `updateIdVClaims`method [[2](https://github.com/wso2-extensions/identity-verification/blob/67a61a7d9498b037dad05f0a351bf057a6eee49b/components/org.wso2.carbon.extension.identity.verification.mgt/src/main/java/org/wso2/carbon/extension/identity/verification/mgt/IdentityVerificationManagerImpl.java#L167)] applies the **same validation logic** used for `POST` requests.  

As a result, when a claim is already present, the API treats it as a duplicate and throws the error `"IDV-10004"`. However, for a `PUT` request, the claim **should already exist** to be updated, so this validation logic during the claim update is incorrect.

Note : Even after fixing the validation logic the update operation still fails with the following response and error logs:

**API Response:**

```
{
    "code": "SE-50000",
    "message": "Unexpected Processing Error.",
    "description": "Server encountered an error while serving the request.",
    "traceId": "3b3aba52-0578-4412-b4f8-e4d5a39fef53"
}
```

**Error Logs:**

```
ERROR {org.wso2.carbon.identity.api.dispatcher.core.DefaultExceptionMapper} - Server encountered an error while serving the request. java.lang.NullPointerException
	at org.wso2.carbon.extension.identity.verification.mgt.cache.IdVClaimCacheKey.hashCode(IdVClaimCacheKey.java:55)
	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111)
	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102)
	at org.wso2.carbon.caching.impl.CacheImpl.removeLocal(CacheImpl.java:545)
	at org.wso2.carbon.caching.impl.CacheImpl.remove(CacheImpl.java:521)
	at org.wso2.carbon.identity.core.cache.BaseCache.clearCacheEntry(BaseCache.java:282)
	at org.wso2.carbon.extension.identity.verification.mgt.dao.CachedBackedIdVClaimDAO.deleteIdVPFromCache(CachedBackedIdVClaimDAO.java:191)
	at org.wso2.carbon.extension.identity.verification.mgt.dao.CachedBackedIdVClaimDAO.updateIdVClaim(CachedBackedIdVClaimDAO.java:61)
	at org.wso2.carbon.extension.identity.verification.mgt.IdentityVerificationManagerImpl.updateIdVClaims(IdentityVerificationManagerImpl.java:168)
	at org.wso2.carbon.identity.rest.api.user.idv.v1.core.IdentityVerificationService.updateIdVClaims(IdentityVerificationService.java:172)```

	at org.wso2.carbon.identity.rest.api.user.idv.v1.impl.DefaultApiServiceImpl.updateIdVClaims(DefaultApiServiceImpl.java:78)
	at org.wso2.carbon.identity.rest.api.user.idv.v1.DefaultApi.updateIdVClaims(DefaultApi.java:168)
```

The above issue occurs because the cache clearing process in the `updateIdVClaim` method [[3]](https://github.com/wso2-extensions/identity-verification/blob/67a61a7d9498b037dad05f0a351bf057a6eee49b/components/org.wso2.carbon.extension.identity.verification.mgt/src/main/java/org/wso2/carbon/extension/identity/verification/mgt/dao/CachedBackedIdVClaimDAO.java#L61) attempts to delete the cache entry based on the `UUID` of the identity verification claim [[4]](https://github.com/wso2-extensions/identity-verification/blob/67a61a7d9498b037dad05f0a351bf057a6eee49b/components/org.wso2.carbon.extension.identity.verification.mgt/src/main/java/org/wso2/carbon/extension/identity/verification/mgt/dao/CachedBackedIdVClaimDAO.java#L185). However, the UUID is missing from the idvClaim object passed during the update request, leading to a `NullPointerException` when trying to remove the cache entry.

---

## **Issue 2: Updating Non-Existing Claims**  

- **Current Behavior:**  

When trying to update a **non-existing** identity verification claim, the following error response is returned:  
```json
{
    "code": "SE-50000",
    "message": "Unexpected Processing Error.",
    "description": "Server encountered an error while serving the request.",
    "traceId": "10b5de61-e5c1-4e3e-9f71-9c664aa09cfb"
}
```

<img width="1070" alt="Screenshot 2024-12-30 at 14 06 29" src="https://github.com/user-attachments/assets/4c0fde4f-b193-4db0-9e58-1bb0b1f744b1" />

Error Logs:
```
ERROR {org.wso2.carbon.identity.api.dispatcher.core.DefaultExceptionMapper} - Server encountered an error while serving the request. java.lang.NullPointerException
	at org.wso2.carbon.extension.identity.verification.mgt.cache.IdVClaimCacheKey.hashCode(IdVClaimCacheKey.java:55)
	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111)
	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102)
	at org.wso2.carbon.caching.impl.CacheImpl.removeLocal(CacheImpl.java:545)
	at org.wso2.carbon.caching.impl.CacheImpl.remove(CacheImpl.java:521)
	at org.wso2.carbon.identity.core.cache.BaseCache.clearCacheEntry(BaseCache.java:282)
	at org.wso2.carbon.extension.identity.verification.mgt.dao.CachedBackedIdVClaimDAO.deleteIdVPFromCache(CachedBackedIdVClaimDAO.java:191)
	at org.wso2.carbon.extension.identity.verification.mgt.dao.CachedBackedIdVClaimDAO.updateIdVClaim(CachedBackedIdVClaimDAO.java:61)
	at org.wso2.carbon.extension.identity.verification.mgt.IdentityVerificationManagerImpl.updateIdVClaims(IdentityVerificationManagerImpl.java:168)
	at org.wso2.carbon.identity.rest.api.user.idv.v1.core.IdentityVerificationService.updateIdVClaims(IdentityVerificationService.java:172)```

	at org.wso2.carbon.identity.rest.api.user.idv.v1.impl.DefaultApiServiceImpl.updateIdVClaims(DefaultApiServiceImpl.java:78)
	at org.wso2.carbon.identity.rest.api.user.idv.v1.DefaultApi.updateIdVClaims(DefaultApi.java:168)
```

- **Expected Behavior:** 
 
If the identity verification claim does **not exist**, the API should return a **404 Not Found** response with an appropriate error message indicating that the resource does not exist.

- **Root Cause:**  

A **`NullPointerException`** is thrown because the cache key (`IdVClaimCacheKey`) tries to remove a non-existent entry, leading to an unexpected error (`SE-50000`).  
The API should instead **validate whether the resource exists** before attempting an update and return an error response if it is missing.

---

### **References**:  

[1] https://github.com/wso2/identity-api-user/blob/89a1bc51e5f0b56b4d25bde8ce6ff22de12142c2/components/org.wso2.carbon.identity.api.user.idv/org.wso2.carbon.identity.api.user.idv.v1/src/main/resources/idv.yaml#L353-L417

[2] https://github.com/wso2-extensions/identity-verification/blob/67a61a7d9498b037dad05f0a351bf057a6eee49b/components/org.wso2.carbon.extension.identity.verification.mgt/src/main/java/org/wso2/carbon/extension/identity/verification/mgt/IdentityVerificationManagerImpl.java#L167

[3]https://github.com/wso2-extensions/identity-verification/blob/67a61a7d9498b037dad05f0a351bf057a6eee49b/components/org.wso2.carbon.extension.identity.verification.mgt/src/main/java/org/wso2/carbon/extension/identity/verification/mgt/dao/CachedBackedIdVClaimDAO.java#L61

[4] https://github.com/wso2-extensions/identity-verification/blob/67a61a7d9498b037dad05f0a351bf057a6eee49b/components/org.wso2.carbon.extension.identity.verification.mgt/src/main/java/org/wso2/carbon/extension/identity/verification/mgt/dao/CachedBackedIdVClaimDAO.java#L185

[5] https://github.com/wso2-extensions/identity-verification/blob/67a61a7d9498b037dad05f0a351bf057a6eee49b/components/org.wso2.carbon.extension.identity.verification.mgt/src/main/java/org/wso2/carbon/extension/identity/verification/mgt/IdentityVerificationManagerImpl.java#L237

---

## Steps to Reproduce

1. **Set up the Onfido Connector for WSO2 Identity Server:**  
   - Follow the [[Onfido Connector Setup Guide](https://github.com/wso2-extensions/identity-verification-onfido/blob/main/docs/config.md#setting-up-and-installing-the-onfido-connector).  
   - **Note:** Skip **Step 3** from the guide.

2. **Create an Onfido Connection in the Console:**  
   - Refer to the [[Configuring Onfido Identity Verification Provider](https://github.com/wso2-extensions/identity-verification-onfido/blob/main/docs/config.md#configuring-onfido-identity-verification-provider-in-wso2-identity-server-console).  
   - Follow the steps **until Step 4** and provide **dummy values** for the required configuration fields.  
   - Copy the **IDVP ID** displayed in the **Settings tab** of the Onfido connector's edit page.

3. **Create a User in the Console:**  
   - After creating the user, copy the **User ID** for later use.

4. **Create an M2M (Machine-to-Machine) Application:**  
   - Add **`Identity Verification Claim Management API`** as an API resource.  
   - Grant permissions for **all scopes** related to this resource.

5. **Generate an Access Token:**  
   - Generate a token for the **Identity Verification Claim Management API** using the M2M application created earlier.  
   - Copy the **token** for later use.

6. **Add an Identity Verification Claim:**  
   - Execute the following `curl` command:  
     Replace `{TOKEN}`, `{USER-ID}`, and `{ONFIDO-IDVP-ID}` with the respective values.

```bash
curl --location 'https://localhost:9443/api/users/v1/{USER-ID}/idv/claims' \
--header 'Authorization: Bearer {TOKEN}' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '[
  {
    "uri": "http://wso2.org/claims/givenname",
    "isVerified": true,
    "idVProviderId": "{ONFIDO-IDVP-ID}",
    "claimMetadata": {
      "source": "ONFIDO",
      "trackingId": "123e4567-****-12d3-****-556642440000"
    }
  }
]'
```

7. **Update the Identity Verification Claim:**  
   - Execute the following `curl` command:  
     Replace `{TOKEN}`, `{USER-ID}`, and `{ONFIDO-IDVP-ID}` with the respective values.

```bash
curl --location --request PUT 'https://localhost:9443/api/users/v1/{USER-ID}/idv/claims' \
--header 'Authorization: Bearer {TOKEN}' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '[
  {
    "uri": "http://wso2.org/claims/givenname",
    "isVerified": false,
    "idVProviderId": "{ONFIDO-IDVP-ID}",
    "claimMetadata": {
      "source": "ONFIDO",
      "trackingId": "123e4567-****-12d3-****-556642440000"
    }
  }
]'
```

8. **Observe the Issue:**  
   - Check the API response and logs for errors during both **Add** and **Update** operations.  
   - Verify the expected behavior described in the issue report.

## Version

IS 7.1

**Comment by AfraHussaindeen** [comment]
### Verification performed

<img width="1069" alt="Image" src="https://github.com/user-attachments/assets/ba09d913-0e8a-4d8f-8d54-e41a405dc064" />

<img width="1066" alt="Image" src="https://github.com/user-attachments/assets/c2e9571e-43b7-413e-a394-a8f307475f11" />
