### ISSUE TITLE
[IS-541] Invalid object name 'REG_LOG' error observed while server startup with -Dsetup

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-is#2301]
Observed the error[1] when server startup with -Dsetup parameter. Even though this error occurred, when checked the DB, the table is created.

Environment:
IS-541 and IS-540 ga reproduce the same
MSSQL 14
UM,IDN,REG datasource configured
gov/config registry is mounted 

[1]
`[2018-02-12 14:56:41,812] ERROR {org.wso2.carbon.registry.core.jdbc.dao.JDBCLogsDAO} -  Failed to update log batch records . Invalid object name 'REG_LOG'.
java.sql.BatchUpdateException: Invalid object name 'REG_LOG'.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:1178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy21.executeBatch(Unknown Source)
	at org.wso2.carbon.registry.core.jdbc.dao.JDBCLogsDAO.addLogRecords(JDBCLogsDAO.java:159)
	at org.wso2.carbon.registry.core.jdbc.dao.JDBCLogsDAO.saveLogBatch(JDBCLogsDAO.java:123)
	at org.wso2.carbon.registry.core.utils.LogWriter.logWrite(LogWriter.java:106)
	at org.wso2.carbon.registry.core.utils.LogWriter.run(LogWriter.java:91)
[2018-02-12 14:56:41,819] ERROR {org.wso2.carbon.registry.core.utils.LogWriter} -  Unable to save log records
org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to update log batch records . Invalid object name 'REG_LOG'.
	at org.wso2.carbon.registry.core.jdbc.dao.JDBCLogsDAO.addLogRecords(JDBCLogsDAO.java:176)
	at org.wso2.carbon.registry.core.jdbc.dao.JDBCLogsDAO.saveLogBatch(JDBCLogsDAO.java:123)
	at org.wso2.carbon.registry.core.utils.LogWriter.logWrite(LogWriter.java:106)
	at org.wso2.carbon.registry.core.utils.LogWriter.run(LogWriter.java:91)
Caused by: java.sql.BatchUpdateException: Invalid object name 'REG_LOG'.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:1178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy21.executeBatch(Unknown Source)
	at org.wso2.carbon.registry.core.jdbc.dao.JDBCLogsDAO.addLogRecords(JDBCLogsDAO.java:159)
	... 3 more`

**Comment by sagara-gunathunga** [comment]
-Dsetup is not production ready feature so we will get rid of this feature, please refer "[Dev] How to create database tables with -Dsetup in Carbon 5?" thread. Please reopen the issue if this error occur when connecting to manually created database without using -Dsetup option.
