### ISSUE TITLE
MySQL Error is thrown mysql 5.7 scripts as -Dsetup when starting the pack

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2323]
MySQL Error is thrown mysql 5.7 scripts as -Dsetup when starting the pack

`[2018-02-14 11:42:24,086] ERROR {org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent} -  Error occurred while populating identity configuration properties
org.wso2.carbon.identity.base.IdentityRuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VALUES VARCHAR(255) , PRIMARY KEY (ID), FOREIGN KEY (REQ_OBJECT_CLAIMS_ID) REFER' at line 1
	at org.wso2.carbon.identity.base.IdentityRuntimeException.error(IdentityRuntimeException.java:71)
	at org.wso2.carbon.identity.core.persistence.IdentityDBInitializer.executeSQL(IdentityDBInitializer.java:351)
	at org.wso2.carbon.identity.core.persistence.IdentityDBInitializer.executeSQLScript(IdentityDBInitializer.java:264)
	at org.wso2.carbon.identity.core.persistence.IdentityDBInitializer.createIdentityDatabase(IdentityDBInitializer.java:141)
	at org.wso2.carbon.identity.core.persistence.JDBCPersistenceManager.initializeDatabase(JDBCPersistenceManager.java:112)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:515)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:291)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:847)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VALUES VARCHAR(255) , PRIMARY KEY (ID), FOREIGN KEY (REQ_OBJECT_CLAIMS_ID) REFER' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2618)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2568)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:842)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:681)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy18.execute(Unknown Source)
	at org.wso2.carbon.identity.core.persistence.IdentityDBInitializer.executeSQL(IdentityDBInitializer.java:318)
	... 31 more
[2018-02-14 11:42:24,178]  INFO {org.wso2.carbon.humantask.core.HumanTaskSchedulerInitializer} -  Starting HumanTasks Scheduler
[2018-02-14 11:42:24,191]  INFO {openjpa.Runtime} -  Starting OpenJPA 2.2.0-wso2v1

`

Same issue can be seen even if you run the mysql 5.7 script in identity folder,  against the mysql DB .

```
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1064 (42000) at line 739: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VALUES VARCHAR(255) ,
  PRIMARY KEY (ID),
  FOREIGN KEY (REQ_OBJECT_CLAIMS_ID) R' at line 4
```

**Comment by ushanib** [comment]
Below is the tables created.

mysql> show tables;
+--------------------------------+
| Tables_in_WSO2CarbonDB         |
+--------------------------------+
| CM_CONSENT_RECEIPT_PROPERTY    |
| CM_PII_CATEGORY                |
| CM_PURPOSE                     |
| CM_PURPOSE_CATEGORY            |
| CM_PURPOSE_PII_CAT_ASSOC       |
| CM_RECEIPT                     |
| CM_RECEIPT_SP_ASSOC            |
| CM_SP_PURPOSE_ASSOC            |
| CM_SP_PURPOSE_PII_CAT_ASSOC    |
| CM_SP_PURPOSE_PURPOSE_CAT_ASSC |
| FIDO_DEVICE_STORE              |
| IDN_ASSOCIATED_ID              |
| IDN_AUTH_SESSION_STORE         |
| IDN_BASE_TABLE                 |
| IDN_CLAIM                      |
| IDN_CLAIM_DIALECT              |
| IDN_CLAIM_MAPPED_ATTRIBUTE     |
| IDN_CLAIM_MAPPING              |
| IDN_CLAIM_PROPERTY             |
| IDN_IDENTITY_META_DATA         |
| IDN_IDENTITY_USER_DATA         |
| IDN_OAUTH1A_ACCESS_TOKEN       |
| IDN_OAUTH1A_REQUEST_TOKEN      |
| IDN_OAUTH2_ACCESS_TOKEN        |
| IDN_OAUTH2_ACCESS_TOKEN_SCOPE  |
| IDN_OAUTH2_AUTHORIZATION_CODE  |
| IDN_OAUTH2_RESOURCE_SCOPE      |
| IDN_OAUTH2_SCOPE               |
| IDN_OAUTH2_SCOPE_BINDING       |
| IDN_OAUTH_CONSUMER_APPS        |
| IDN_OIDC_REQ_OBJECT_CLAIMS     |
| IDN_OIDC_REQ_OBJECT_REFERENCE  |
| IDN_OPENID_ASSOCIATIONS        |
| IDN_OPENID_REMEMBER_ME         |
| IDN_OPENID_USER_RPS            |
| IDN_PASSWORD_HISTORY_DATA      |
| IDN_RECOVERY_DATA              |
| IDN_SAML2_ASSERTION_STORE      |
| IDN_SCIM_GROUP                 |
| IDN_STS_STORE                  |
| IDN_THRIFT_SESSION             |
| IDN_USER_ACCOUNT_ASSOCIATION   |
| IDP                            |
| IDP_AUTHENTICATOR              |
| IDP_AUTHENTICATOR_PROPERTY     |
| IDP_CLAIM                      |
| IDP_CLAIM_MAPPING              |
| IDP_LOCAL_CLAIM                |
| IDP_METADATA                   |
| IDP_OIDC_PROPERTY              |
| IDP_PROVISIONING_CONFIG        |
| IDP_PROVISIONING_ENTITY        |
| IDP_PROV_CONFIG_PROPERTY       |
| IDP_ROLE                       |
| IDP_ROLE_MAPPING               |
| REG_ASSOCIATION                |
| REG_CLUSTER_LOCK               |
| REG_COMMENT                    |
| REG_CONTENT                    |
| REG_CONTENT_HISTORY            |
| REG_LOG                        |
| REG_PATH                       |
| REG_PROPERTY                   |
| REG_RATING                     |
| REG_RESOURCE                   |
| REG_RESOURCE_COMMENT           |
| REG_RESOURCE_HISTORY           |
| REG_RESOURCE_PROPERTY          |
| REG_RESOURCE_RATING            |
| REG_RESOURCE_TAG               |
| REG_SNAPSHOT                   |
| REG_TAG                        |
| SP_APP                         |
| SP_AUTH_SCRIPT                 |
| SP_AUTH_STEP                   |
| SP_CLAIM_MAPPING               |
| SP_FEDERATED_IDP               |
| SP_INBOUND_AUTH                |
| SP_METADATA                    |
| SP_PROVISIONING_CONNECTOR      |
| SP_REQ_PATH_AUTHENTICATOR      |
| SP_ROLE_MAPPING                |
| UM_ACCOUNT_MAPPING             |
| UM_CLAIM                       |
| UM_DIALECT                     |
| UM_DOMAIN                      |
| UM_HYBRID_REMEMBER_ME          |
| UM_HYBRID_ROLE                 |
| UM_HYBRID_USER_ROLE            |
| UM_MODULE                      |
| UM_MODULE_ACTIONS              |
| UM_PERMISSION                  |
| UM_PROFILE_CONFIG              |
| UM_ROLE                        |
| UM_ROLE_PERMISSION             |
| UM_SHARED_USER_ROLE            |
| UM_SYSTEM_ROLE                 |
| UM_SYSTEM_USER                 |
| UM_SYSTEM_USER_ROLE            |
| UM_TENANT                      |
| UM_USER                        |
| UM_USER_ATTRIBUTE              |
| UM_USER_PERMISSION             |
| UM_USER_ROLE                   |
| WF_BPS_PROFILE                 |
| WF_REQUEST                     |
| WF_REQUEST_ENTITY_RELATIONSHIP |
| WF_WORKFLOW                    |
| WF_WORKFLOW_ASSOCIATION        |
| WF_WORKFLOW_CONFIG_PARAM       |
| WF_WORKFLOW_REQUEST_RELATION   |
+--------------------------------+
111 rows in set (0.00 sec)

**Comment by sagara-gunathunga** [comment]
-Dsetup is not production ready feature so we will get rid of this feature, please refer "[Dev] How to create database tables with -Dsetup in Carbon 5?" thread. Please reopen the issue if this error occur when connecting to manually created database without using -Dsetup option.
