### ISSUE TITLE
config.json file path is taken in to a wrong location when you run forget-me tool

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2477]
config.json file path is taken in to a wrong location when you run forget-me tool as per this [1] doc

[1] https://docs.wso2.com/display/ADMIN44x/Removing+References+to+Deleted+User+Identities+in+WSO2+Products#RemovingReferencestoDeletedUserIdentitiesinWSO2Products-MasterConfig

./forget-me -U <username>

./forget-me -U ushani2
2018-02-19 16:22:38 INFO  ForgetMeTool:167 - Generating pseudonym as pseudo name is not provided : 742878f2-ff35-49d3-9c4f-39b6d60c374a
Exception in thread "main" org.wso2.carbon.privacy.forgetme.runtime.ForgetMeExecutionException: Could not read the config files related to : /home/ushani/WSO2_WORK/Products/IS/5.5.0/alpha/identity-anonymization-tool/components/org.wso2.carbon.privacy.forgetme.tool/target/org.wso2.carbon.privacy.forgetme.tool-1.0.3-SNAPSHOT/config.json
	at org.wso2.carbon.privacy.forgetme.ConfigReader.readSystemConfig(ConfigReader.java:117)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:185)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:128)
Caused by: java.io.FileNotFoundException: /home/ushani/WSO2_WORK/Products/IS/5.5.0/alpha/identity-anonymization-tool/components/org.wso2.carbon.privacy.forgetme.tool/target/org.wso2.carbon.privacy.forgetme.tool-1.0.3-SNAPSHOT/config.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at org.wso2.carbon.privacy.forgetme.ConfigReader.readSystemConfig(ConfigReader.java:96)
	... 2 more

config.json is inside conf folder. Below is displayed without /conf
**home/ushani/WSO2_WORK/Products/IS/5.5.0/alpha/identity-anonymization-tool/components/org.wso2.carbon.privacy.forgetme.tool/target/org.wso2.carbon.privacy.forgetme.tool-1.0.3-SNAPSHOT/config.json**

**Comment by JKAUSHALYA** [comment]
Fixed in https://github.com/wso2/identity-anonymization-tool/pull/47

**Comment by ushanib** [comment]
This issue exists in alpha3

**Comment by emswbandara** [comment]
Fixed with beta
