### ISSUE TITLE
DB lock issues occurs even for MYSQL when the server is online while running forgetme tool for a deleted user

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2682]
DB lock issues occurs even for MYSQL when the server is online while running forgetme tool for a deleted user.

It is not feasible for a user to shutdown the instance when they want to run forget me tool.

```

 ./forgetme.sh -U user1
2018-02-27 17:20:28 INFO  ForgetMeTool:167 - Generating pseudonym as pseudo name is not provided : 260039bd-117b-40e7-9ec7-9b62f9da6c57
2018-02-27 17:20:28 INFO  HikariDataSource:72 - HikariPool-0 - is starting.
2018-02-27 17:20:28 INFO  HikariDataSource:72 - HikariPool-1 - is starting.
2018-02-27 17:20:30 INFO  HikariPool:244 - HikariPool-1 - is closing down.
Exception in thread "main" com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Database may be already in use: "Locked by another process". Possible solutions: close all other connection(s); use the server mode; SQL statement:
null/161d7179802728681fe56945d57de059c88b7390d33 [90020-140]
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:581)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:152)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:73)
	at org.wso2.carbon.datasource.rdbms.hikari.HikariRDBMSDataSource.getDataSource(HikariRDBMSDataSource.java:56)
	at org.wso2.carbon.datasource.rdbms.hikari.HikariDataSourceReader.createDataSource(HikariDataSourceReader.java:74)
	at org.wso2.carbon.datasource.core.DataSourceBuilder.buildDataSourceObject(DataSourceBuilder.java:64)
	at org.wso2.carbon.datasource.core.DataSourceBuilder.buildCarbonDataSource(DataSourceBuilder.java:44)
	at org.wso2.carbon.datasource.core.DataSourceManager.initDataSource(DataSourceManager.java:163)
	at org.wso2.carbon.datasource.core.DataSourceManager.initDataSources(DataSourceManager.java:137)
	at org.wso2.carbon.datasource.core.DataSourceManager.initDataSources(DataSourceManager.java:109)
	at org.wso2.carbon.privacy.forgetme.sql.instructions.DatasourceProcessorConfigReader.readProcessorConfig(DatasourceProcessorConfigReader.java:45)
	at org.wso2.carbon.privacy.forgetme.sql.instructions.DatasourceProcessorConfigReader.readProcessorConfig(DatasourceProcessorConfigReader.java:32)
	at org.wso2.carbon.privacy.forgetme.ConfigReader.loadExtensions(ConfigReader.java:204)
	at org.wso2.carbon.privacy.forgetme.ConfigReader.readSystemConfig(ConfigReader.java:107)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:185)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:128)
Caused by: org.h2.jdbc.JdbcSQLException: Database may be already in use: "Locked by another process". Possible solutions: close all other connection(s); use the server mode; SQL statement:
null/161d7179802728681fe56945d57de059c88b7390d33 [90020-140]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.store.FileLock.getExceptionAlreadyInUse(FileLock.java:436)
	at org.h2.store.FileLock.lockFile(FileLock.java:331)
	at org.h2.store.FileLock.lock(FileLock.java:129)
	at org.h2.engine.Database.open(Database.java:523)
	at org.h2.engine.Database.openDatabase(Database.java:207)
	at org.h2.engine.Database.<init>(Database.java:202)
	at org.h2.engine.Engine.openSession(Engine.java:56)
	at org.h2.engine.Engine.openSession(Engine.java:146)
	at org.h2.engine.Engine.getSession(Engine.java:125)
	at org.h2.engine.Session.createSession(Session.java:122)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:241)
	at org.h2.engine.SessionRemote.createSession(SessionRemote.java:219)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:111)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:95)
	at org.h2.Driver.connect(Driver.java:73)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496)
	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565)
	... 15 more
```

**Comment by ruwanta** [comment]
How the stack trace has "org.h2.Driver" ? which means some datasource connects to H2.
Docs is clear on this. Do not run on h2 in online mode.

This stack trace does not have anything related to MySql even it mentions about locking on mysql.

Marking this as Invalid.

**Comment by ushanib** [comment]
Hi Ruwan,
This is the same concern I have raised. Please find my master-datasources.xml config. I have not configured any h2 DB connection. But this exception is reproducible. Hence reopening the issue. Please let me know if there is any place that we need to configure to connect to MySQL db other than master-datasources.xml when we use forget me tool since I cannot find it in the doc.

Thanks,

     <datasource>
        <name>WSO2_CARBON_DB</name>
        <description>The datasource used for registry and user manager</description>
        <jndiConfig>
                <name>jdbc/WSO2CarbonDB</name>
        </jndiConfig>
        <definition type="RDBMS">
                <configuration>
                        <url>jdbc:mysql://localhost:3306/WSO2CarbonDB?useSSL=false</url>
                        <username>root</username>
                        <password>password</password>
                        <driverClassName>com.mysql.jdbc.Driver</driverClassName>
                        <maxActive>50</maxActive>
                        <maxWait>60000</maxWait>
                        <testOnBorrow>true</testOnBorrow>
                        <validationQuery>SELECT 1</validationQuery>
                        <validationInterval>30000</validationInterval>
           </configuration>
        </definition>
</datasource>

**Comment by JKAUSHALYA** [comment]
If you are pointing to a data sources folder, then any data sources (XML) file inside the folder will be picked. This is the normal data sources behavior. Please check if you have any data sources (XML) remains in that folder other than the master-datasource.xml, it'll also will be picked.

**Comment by ushanib** [comment]
I have bps-datasources.xml and metrics-datasources.xml pointed to h2. Can that be the reason for this issue?

**Comment by JKAUSHALYA** [comment]
Yes. They will be active when server is running. Hence external tool cannot access them.

**Comment by ruwanta** [comment]
We better add this is documentation. Some Q&A section on the tool would do.

**Comment by dilinisg** [comment]
Reopening to track documenting the said details

**Comment by Nashaath** [comment]
Checked with Jayanga and resolving this since we have added the following as a note:

This tool is designed to run in offline mode (i.e., the server should be shut down or run on another machine) to prevent unnecessary load to the server. If you run the tool in online mode (i.e., when the server is running), DB lock situations on the H2 databases may occur.
