### ISSUE TITLE
MySQLSyntaxErrorException when running forget me tool in offline mode

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2683]
MySQLSyntaxErrorException when running forget me tool in offline mode.
Due to this issue [https://github.com/wso2/product-is/issues/2673] (https://github.com/wso2/product-is/issues/2673)  I used this [this](https://github.com/wso2/carbon-identity-framework/tree/5.11.x/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts) script to create tables.

Steps
-------
1. DB is JDBC - Mysql 5.7
2. Created a user as user1
3. Deleted the user.
4. Shutdown the server.
5. Run forgetme tool as below.

` ./forgetme.sh -U user1
2018-02-27 17:21:33 INFO  ForgetMeTool:167 - Generating pseudonym as pseudo name is not provided : 19110664-b6bf-4fcb-bbdb-1c4c6dfd17fc
2018-02-27 17:21:33 INFO  HikariDataSource:72 - HikariPool-0 - is starting.
2018-02-27 17:21:33 INFO  HikariDataSource:72 - HikariPool-1 - is starting.
2018-02-27 17:21:33 INFO  HikariDataSource:72 - HikariPool-2 - is starting.
2018-02-27 17:21:34 INFO  ForgetMeExecutionEngine:218 - Processor execution completed. Processor : log-file
2018-02-27 17:21:34 ERROR ForgetMeExecutionEngine:112 - Interrupted while executing the processor thread : java.util.concurrent.FutureTask@69b794e2
java.util.concurrent.ExecutionException: org.wso2.carbon.privacy.forgetme.api.runtime.InstructionExecutionException: Error occurred while executing sql from : /home/ushani/WSO2_WORK/Products/IS/5.5.0/alpha2/wso2is-5.5.0-alpha2/repository/components/tools/forget-me/conf/sql/identity
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.waitForCompletion(ForgetMeExecutionEngine.java:109)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.execute(ForgetMeExecutionEngine.java:91)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:188)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:128)
Caused by: org.wso2.carbon.privacy.forgetme.api.runtime.InstructionExecutionException: Error occurred while executing sql from : /home/ushani/WSO2_WORK/Products/IS/5.5.0/alpha2/wso2is-5.5.0-alpha2/repository/components/tools/forget-me/conf/sql/identity
	at org.wso2.carbon.privacy.forgetme.sql.instructions.RdbmsForgetMeInstruction.execute(RdbmsForgetMeInstruction.java:107)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:216)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:188)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.privacy.forgetme.sql.exception.SQLModuleException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'WSO2CarbonDB.CM_RECEIPT' doesn't exist
	at org.wso2.carbon.privacy.forgetme.sql.module.DomainAppendedSQLExecutionModule.execute(DomainAppendedSQLExecutionModule.java:100)
	at org.wso2.carbon.privacy.forgetme.sql.module.DomainAppendedSQLExecutionModule.execute(DomainAppendedSQLExecutionModule.java:37)
	at org.wso2.carbon.privacy.forgetme.sql.instructions.RdbmsForgetMeInstruction.execute(RdbmsForgetMeInstruction.java:103)
	... 6 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'WSO2CarbonDB.CM_RECEIPT' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.execute(PreparedStatementProxy.java:44)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.execute(HikariPreparedStatementProxy.java)
	at org.wso2.carbon.privacy.forgetme.sql.module.DomainAppendedSQLExecutionModule.execute(DomainAppendedSQLExecutionModule.java:94)
	... 8 more
2018-02-27 17:21:34 INFO  ForgetMeExecutionEngine:115 - All processors have been properly shut-down
`

**Comment by omindu** [comment]
[1] contains only identity related tables. The error says `WSO2CarbonDB.CM_RECEIPT` is missing. Seem you have not created the consent management related tables. Hence the error. Please make sure the consent related DB scripts are  executed. The script can be found under `<IS_HOME>/dbscripts/consent`

[1] https://github.com/wso2/carbon-identity-framework/blob/5.11.x/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/mysql-5.7.sql

**Comment by ushanib** [comment]
Can we include this in the documentation? That we should run consent DB script as well?

**Comment by JKAUSHALYA** [comment]
There is a separate issue track that https://github.com/wso2/product-is/issues/2321 Hence closing this issue.

**Comment by sherenewso2** [comment]
Added the consent db script location to [1] and the page has been linked to from [2]. Did not close out [#2321 ](https://github.com/wso2/product-is/issues/2321) yet because the data tables still need to be added to the data dictionary. 

[1] https://docs.wso2.com/display/IS550/Setting+Up+Separate+Databases+for+Clustering
[2] https://docs.wso2.com/display/IS550/Product+Administration#ProductAdministration-Changingthedefaultdatabase
