### ISSUE TITLE
Typo error 'usernmae' causes 'java.util.regex.PatternSyntaxException'

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2758]
Typo error 'usernmae' causes 'java.util.regex.PatternSyntaxException'

`./forget-me -U user2 -d /home/ushani/WSO2_WORK/Products/IS/5.5.0/alpha3/wso2is-5.5.0-alpha3/repository/components/tools/forget-me/conf/
2018-03-05 14:48:47 INFO  ForgetMeTool:167 - Generating pseudonym as pseudo name is not provided : 49bcbd31-b7d8-4212-b91d-56b9ca81641b
2018-03-05 14:48:48 INFO  HikariDataSource:72 - HikariPool-0 - is starting.
2018-03-05 14:48:51 INFO  HikariDataSource:72 - HikariPool-1 - is starting.
2018-03-05 14:48:53 INFO  HikariDataSource:72 - HikariPool-2 - is starting.
2018-03-05 14:48:54 INFO  ForgetMeExecutionEngine:219 - Processor execution completed. Processor : rdbms
2018-03-05 14:48:54 ERROR ForgetMeExecutionEngine:112 - Interrupted while executing the processor thread : java.util.concurrent.FutureTask@6e509ffa
java.util.concurrent.ExecutionException: java.util.regex.PatternSyntaxException: Illegal repetition near index 46
(.)*Retrieving user roles by retrieving user '${usernmae}'.
                                              ^
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.waitForCompletion(ForgetMeExecutionEngine.java:109)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.execute(ForgetMeExecutionEngine.java:91)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:188)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:128)
Caused by: java.util.regex.PatternSyntaxException: Illegal repetition near index 46
(.)*Retrieving user roles by retrieving user '${usernmae}'.
                                              ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.closure(Pattern.java:3157)
	at java.util.regex.Pattern.sequence(Pattern.java:2134)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at org.wso2.carbon.privacy.forgetme.logs.processor.LogFileProcessor.compile(LogFileProcessor.java:117)
	at org.wso2.carbon.privacy.forgetme.logs.processor.LogFileProcessor.processFiles(LogFileProcessor.java:63)
	at org.wso2.carbon.privacy.forgetme.logs.instructions.LogFileInstruction.execute(LogFileInstruction.java:67)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:217)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:188)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2018-03-05 14:48:54 INFO  ForgetMeExecutionEngine:115 - All processors have been properly shut-down
`

Error is in  sp-patterns.xml,

    <pattern key="carbon-analytics-common-11">
        <detectPattern>(.)*Retrieving user roles by retrieving user '${**usernmae**}'.</detectPattern>
        <replacePattern>${username}</replacePattern>
    </pattern>

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
