### ISSUE TITLE
java.util.regex.PatternSyntaxException near  domain:${userDomain} when you run forget me tool

### ISSUE THREAD

**Issue by ushanib** [wso2/product-is#2764]
java.util.regex.PatternSyntaxException near  domain:${userDomain} when you run forget me tool.

This issue comes when you fix the typo error in [https://github.com/wso2/product-is/issues/2758](https://github.com/wso2/product-is/issues/2758) 
manually.

 ./forget-me -U user2 -d /home/ushani/WSO2_WORK/Products/IS/5.5.0/alpha3/wso2is-5.5.0-alpha3/repository/components/tools/forget-me/conf/
2018-03-05 15:50:52 INFO  ForgetMeTool:167 - Generating pseudonym as pseudo name is not provided : ea7d3809-5181-4bd6-834d-5aead8ccf682
2018-03-05 15:50:53 INFO  HikariDataSource:72 - HikariPool-0 - is starting.
2018-03-05 15:50:56 INFO  HikariDataSource:72 - HikariPool-1 - is starting.
2018-03-05 15:50:59 INFO  HikariDataSource:72 - HikariPool-2 - is starting.
2018-03-05 15:50:59 INFO  ForgetMeExecutionEngine:219 - Processor execution completed. Processor : rdbms
2018-03-05 15:50:59 ERROR ForgetMeExecutionEngine:112 - Interrupted while executing the processor thread : java.util.concurrent.FutureTask@10d68fcd
java.util.concurrent.ExecutionException: java.util.regex.PatternSyntaxException: Illegal repetition near index 58
(.)*a user logged into the portal username: user2, domain:${userDomain}
                                                          ^
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.waitForCompletion(ForgetMeExecutionEngine.java:109)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.execute(ForgetMeExecutionEngine.java:91)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:188)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:128)
Caused by: java.util.regex.PatternSyntaxException: Illegal repetition near index 58
(.)*a user logged into the portal username: user2, domain:${userDomain}
                                                          ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.closure(Pattern.java:3157)
	at java.util.regex.Pattern.sequence(Pattern.java:2134)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at org.wso2.carbon.privacy.forgetme.logs.processor.LogFileProcessor.compile(LogFileProcessor.java:117)
	at org.wso2.carbon.privacy.forgetme.logs.processor.LogFileProcessor.processFiles(LogFileProcessor.java:63)
	at org.wso2.carbon.privacy.forgetme.logs.instructions.LogFileInstruction.execute(LogFileInstruction.java:67)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:217)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:188)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2018-03-05 15:50:59 INFO  ForgetMeExecutionEngine:115 - All processors have been properly shut-down

**Comment by ushanib** [comment]
should be changed as userstoreDomain

**Comment by JKAUSHALYA** [comment]
Fixed with https://github.com/wso2/identity-anonymization-tool/pull/47
