### ISSUE TITLE
Provide a meaningful log when the email could not be sent when self registering a user

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2774]
The following error will be thrown when self registering feature is enabled and the email could not be sent if Google blocks signing in to the gmail account. Better if we can provide a more meaningful error with the root cause

```
[2018-03-05 16:35:00,007] ERROR {org.wso2.carbon.event.output.adapter.email.EmailEventAdapter} -  Event dropped at Output Adapter 'EmailPublisher' for tenant id '1', Error in message format, null
javax.mail.AuthenticationFailedException
	at javax.mail.Service.connect(Service.java:306)
	at javax.mail.Service.connect(Service.java:156)
	at javax.mail.Service.connect(Service.java:105)
	at javax.mail.Transport.send0(Transport.java:168)
	at javax.mail.Transport.send(Transport.java:98)
	at org.wso2.carbon.event.output.adapter.email.EmailEventAdapter$EmailSender.run(EmailEventAdapter.java:306)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
