### ISSUE TITLE
User Self Registration issue with DB2 when there are consents.

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#2880]
This issue is occurring only in a database where tables are created, dropped and re-created situations. 

How to reproduce.

1. Create consent with multiple PII categories.
2. Try to self register the user. 

There will be an error. Stack trace added below.

As per H.E @omindu this occurred due to DEFAULT purpose id category is assumed to be 1 but in scenarios where multiple table drop and creations, this won't be 1.

Back end stack trace:

`org.wso2.carbon.identity.recovery.IdentityRecoveryServerException: Error while adding consent for user %s.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:103)
	at org.wso2.carbon.identity.recovery.util.Utils.handleServerException(Utils.java:160)
	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.addUserConsent(UserSelfRegistrationManager.java:225)
	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.registerUser(UserSelfRegistrationManager.java:186)
	at org.wso2.carbon.identity.user.endpoint.impl.MeApiServiceImpl.mePost(MeApiServiceImpl.java:78)
	at org.wso2.carbon.identity.user.endpoint.MeApi.mePost(MeApi.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:191)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:189)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:303)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:278)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:91)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:82)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.consent.mgt.core.exception.ConsentManagementClientException: Invalid purpose category Id: 1
	at org.wso2.carbon.consent.mgt.core.util.ConsentUtils.handleClientException(ConsentUtils.java:85)
	at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.getPurposeCategory(ConsentManagerImpl.java:296)
	at org.wso2.carbon.consent.mgt.core.util.LambdaExceptionUtils.lambda$rethrowConsumer$0(LambdaExceptionUtils.java:103)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.validateRequiredParametersInPurpose(ConsentManagerImpl.java:967)
	at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.lambda$null$7(ConsentManagerImpl.java:902)
	at org.wso2.carbon.consent.mgt.core.util.LambdaExceptionUtils.lambda$rethrowConsumer$0(LambdaExceptionUtils.java:103)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.lambda$validateInputParameters$8(ConsentManagerImpl.java:901)
	at org.wso2.carbon.consent.mgt.core.util.LambdaExceptionUtils.lambda$rethrowConsumer$0(LambdaExceptionUtils.java:103)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.validateInputParameters(ConsentManagerImpl.java:899)
	at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.addConsent(ConsentManagerImpl.java:502)
	at org.wso2.carbon.consent.mgt.core.InterceptingConsentManager$19.execute(InterceptingConsentManager.java:501)
	at org.wso2.carbon.consent.mgt.core.InterceptingConsentManager$19.execute(InterceptingConsentManager.java:497)
	at org.wso2.carbon.consent.mgt.core.model.ConsentInterceptorTemplate.executeWith(ConsentInterceptorTemplate.java:56)
	at org.wso2.carbon.consent.mgt.core.InterceptingConsentManager.addConsent(InterceptingConsentManager.java:497)
	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.addConsent(UserSelfRegistrationManager.java:500)
	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.addUserConsent(UserSelfRegistrationManager.java:223)
	... 63 more`

**Comment by omindu** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/pull/1469/files
