### ISSUE TITLE
TokenManagementDAOImpl.findTenantAndScopeOfResource() method does not for support Oracle database

### ISSUE THREAD

**Issue by omindu** [wso2/product-is#2882]
From: https://github.com/wso2-extensions/identity-inbound-auth-oauth/issues/850

**Description:**
Hi,

Following error is thrown in APIM when Oracle is used as the database

```
org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: Error getting scopes for resource - /pizzashack/1.0.0/1.0.0/menu:GET
	at org.wso2.carbon.identity.oauth2.dao.TokenManagementDAOImpl.findTenantAndScopeOfResource(TokenManagementDAOImpl.java:225)
	at org.wso2.carbon.identity.oauth2.validators.JDBCScopeValidator.validateScope(JDBCScopeValidator.java:98)
	at org.wso2.carbon.apimgt.keymgt.handlers.DefaultKeyValidationHandler.validateScopes(DefaultKeyValidationHandler.java:177)
	at org.wso2.carbon.apimgt.keymgt.service.APIKeyValidationService.validateKey(APIKeyValidationService.java:184)
	at org.wso2.carbon.apimgt.keymgt.service.thrift.APIKeyValidationServiceImpl.validateKey(APIKeyValidationServiceImpl.java:132)
	at org.wso2.carbon.apimgt.impl.generated.thrift.APIKeyValidationService$Processor$validateKey.getResult(APIKeyValidationService.java:352)
	at org.wso2.carbon.apimgt.impl.generated.thrift.APIKeyValidationService$Processor$validateKey.getResult(APIKeyValidationService.java:340)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:32)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:34)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)

```

SQL script in https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/5.6.x/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/TokenManagementDAOImpl.java#L206 needs to support other database types.

For example, for ORACLE, it needs to be 
SELECT Scopes.NAME, Scopes.TENANT_ID FROM IDN_OAUTH2_SCOPE Scopes, IDN_OAUTH2_RESOURCE_SCOPE ScopeResources WHERE RESOURCE_PATH = ? AND ScopeResources.SCOPE_ID = Scopes.SCOPE_ID

Please check for other databases as well

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chamilaadhi** [comment]
OAuthScopeDAOImpl.getBindingsOfScopeByScopeName() method is also not written for Oracle

`[2018-03-10 17:44:37,274] ERROR - DefaultKeyValidationHandler ERROR while validating token scope Error getting bindings of scope - admin-key
org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: Error getting bindings of scope - admin-key
	at org.wso2.carbon.identity.oauth2.dao.OAuthScopeDAOImpl.getBindingsOfScopeByScopeName(OAuthScopeDAOImpl.java:535)
	at org.wso2.carbon.identity.oauth2.validators.JDBCScopeValidator.validateScope(JDBCScopeValidator.java:144)
	at org.wso2.carbon.apimgt.keymgt.handlers.DefaultKeyValidationHandler.validateScopes(DefaultKeyValidationHandler.java:177)
	at org.wso2.carbon.apimgt.keymgt.service.APIKeyValidationService.validateKey(APIKeyValidationService.java:184)
	at org.wso2.carbon.apimgt.keymgt.service.thrift.APIKeyValidationServiceImpl.validateKey(APIKeyValidationServiceImpl.java:132)
	at org.wso2.carbon.apimgt.impl.generated.thrift.APIKeyValidationService$Processor$validateKey.getResult(APIKeyValidationService.java:352)
	at org.wso2.carbon.apimgt.impl.generated.thrift.APIKeyValidationService$Processor$validateKey.getResult(APIKeyValidationService.java:340)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:32)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:34)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended
`

**Comment by chamilaadhi** [comment]
seems like any of the scope related queries below this https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/5.6.x/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/dao/SQLQueries.java#L508 are compatible with ORACLE database. 

For example,  ....FROM IDN_OAUTH2_SCOPE AS Scopes... section, **AS** keyword is not compatible with ORACLE
