### ISSUE TITLE
[Sporadic] The default consent purpose is not created in a Oracle 12c setup

### ISSUE THREAD

**Issue by dilinisg** [wso2/product-is#2917]
Pack - Beta2

**Steps**
1. Create carbon, bps, metrics databases on Oracle 12C
2. Enable self registration
3. Try to self sign up a user by approving all the claims and Register

**Issue**
The following error will be shown to the user
![70](https://user-images.githubusercontent.com/1845370/37325164-b7c68368-26b2-11e8-8f45-e496f06f3f3a.png)

The following error is logged. When I checked, the DEFAULT purpose was not created
```
[2018-03-13 11:13:53,943] ERROR {org.wso2.carbon.identity.user.endpoint.impl.MeApiServiceImpl} -  Error occurred in the server while performing the task.
org.wso2.carbon.identity.recovery.IdentityRecoveryServerException: Error while adding consent for user %s.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:103)
	at org.wso2.carbon.identity.recovery.util.Utils.handleServerException(Utils.java:160)
	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.addUserConsent(UserSelfRegistrationManager.java:225)
	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.registerUser(UserSelfRegistrationManager.java:186)
	at org.wso2.carbon.identity.user.endpoint.impl.MeApiServiceImpl.mePost(MeApiServiceImpl.java:78)
	at org.wso2.carbon.identity.user.endpoint.MeApi.mePost(MeApi.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:191)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:189)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:303)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:278)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:91)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:82)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.consent.mgt.core.exception.ConsentManagementClientException: Invalid purpose category Id: 1
	at org.wso2.carbon.consent.mgt.core.util.ConsentUtils.handleClientException(ConsentUtils.java:85)
	at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.getPurposeCategory(ConsentManagerImpl.java:296)
	at org.wso2.carbon.consent.mgt.core.util.LambdaExceptionUtils.lambda$rethrowConsumer$0(LambdaExceptionUtils.java:103)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.validateRequiredParametersInPurpose(ConsentManagerImpl.java:967)
	at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.lambda$null$7(ConsentManagerImpl.java:902)
	at org.wso2.carbon.consent.mgt.core.util.LambdaExceptionUtils.lambda$rethrowConsumer$0(LambdaExceptionUtils.java:103)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.lambda$validateInputParameters$8(ConsentManagerImpl.java:901)
	at org.wso2.carbon.consent.mgt.core.util.LambdaExceptionUtils.lambda$rethrowConsumer$0(LambdaExceptionUtils.java:103)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.validateInputParameters(ConsentManagerImpl.java:899)
	at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.addConsent(ConsentManagerImpl.java:502)
	at org.wso2.carbon.consent.mgt.core.InterceptingConsentManager$19.execute(InterceptingConsentManager.java:505)
	at org.wso2.carbon.consent.mgt.core.InterceptingConsentManager$19.execute(InterceptingConsentManager.java:501)
	at org.wso2.carbon.consent.mgt.core.model.ConsentInterceptorTemplate.executeWith(ConsentInterceptorTemplate.java:56)
	at org.wso2.carbon.consent.mgt.core.InterceptingConsentManager.addConsent(InterceptingConsentManager.java:501)
	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.addConsent(UserSelfRegistrationManager.java:500)
	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.addUserConsent(UserSelfRegistrationManager.java:223)
	... 63 more

```

The pack can be found in [1] (configure the email in output-event-adapters.xml)
username - admin@wso2.com
pwd - admin
[1] https://drive.google.com/file/d/1oUCOb49X5yc2sjBxOWyWk4PP-59PL1oY/view?usp=sharing

**Comment by omindu** [comment]
There was an issue in beta2 where we did not check the existence of default purpose category. https://github.com/wso2/product-is/issues/2880

Fixed with: https://github.com/wso2/carbon-identity-framework/pull/1469/files
