### ISSUE TITLE
Exception in Authentication Framework - java.lang.NullPointerException of Identity Server

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-is#2984]
**Description:**
When sending two commonauth POST requests at the same time we were able to recreate below stack trace.

`
[2018-03-19 15:17:24,720] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework java.lang.NullPointerException at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:105) at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:121) at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:137) at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53) at javax.servlet.http.HttpServlet.service(HttpServlet.java:650) at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60) at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:61) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47) at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57) at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956) at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1756) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1715) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748)
`

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
IS 5.2.0

**Steps to reproduce:**

1. Configure a service provider.(I configured travelocity.com as the service provider)
2. Login to the travelocity.com app.
3. Click to login the Identity Server dashboard.
4. Send two commonauth requests at the same time using below curl command.

`curl -X POST -H --compressed -H 'Referer: https://localhost:9443/authenticationendpoint/login.do?SigAlg=http%3A%2F%2Fwww.w3.org%2F2000%2F09%2Fxmldsig%23rsa-sha1&Signature=jlmKUp%2BFXmng9u3XpJRiTxwJCBw5LU1UdSGmoN6o3AYc2E58GE%2F1xYy1ZbUcpp6R4VZCwaqVXpCBoaBHreH06fQwj6WW7c2PTbeujNM71IE2it1gHxnzQf%2BWHPDOjIjd27zfoF7tEUcRH8c06ksLtC7hCb0gC1ykq4sisHvmFWA%3D&commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&tenantDomain=carbon.super&sessionDataKey=a53f4d01-f58a-4885-811e-0aa0c13abde8&relyingParty=travelocity.com&type=samlsso&sp=travelocity.com&isSaaSApp=false&authenticators=GoogleOIDCAuthenticator:test;BasicAuthenticator:LOCAL:LOCAL' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Cookie: menuPanel=visible; menuPanelType=config; samlssoTokenId=9c2d8fd7-194b-4029-b4b0-71a5770cc709' --data 'username=admin&password=admin&sessionDataKey=a53f4d01-f58a-4885-811e-0aa0c13abde8' https://localhost:9443/commonauth -k`

- When analyzing the access logs we can find two commonauth requests at the same time as the below.

127.0.0.1 - - [19/Mar/2018:15:17:24 +0530] "POST /commonauth HTTP/1.1" 302 - "https://localhost:9443/authenticationendpoint/login.do?SigAlg=http%3A%2F%2Fwww.w3.org%2F2000%2F09%2Fxmldsig%23rsa-sha1&Signature=jlmKUp%2BFXmng9u3XpJRiTxwJCBw5LU1UdSGmoN6o3AYc2E58GE%2F1xYy1ZbUcpp6R4VZCwaqVXpCBoaBHreH06fQwj6WW7c2PTbeujNM71IE2it1gHxnzQf%2BWHPDOjIjd27zfoF7tEUcRH8c06ksLtC7hCb0gC1ykq4sisHvmFWA%3D&commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&tenantDomain=carbon.super&sessionDataKey=a53f4d01-f58a-4885-811e-0aa0c13abde8&relyingParty=travelocity.com&type=samlsso&sp=travelocity.com&isSaaSApp=false&authenticators=GoogleOIDCAuthenticator:test;BasicAuthenticator:LOCAL:LOCAL" "curl/7.52.1"

127.0.0.1 - - [19/Mar/2018:15:17:24 +0530] "POST /commonauth HTTP/1.1" 302 - "https://localhost:9443/authenticationendpoint/login.do?SigAlg=http%3A%2F%2Fwww.w3.org%2F2000%2F09%2Fxmldsig%23rsa-sha1&Signature=jlmKUp%2BFXmng9u3XpJRiTxwJCBw5LU1UdSGmoN6o3AYc2E58GE%2F1xYy1ZbUcpp6R4VZCwaqVXpCBoaBHreH06fQwj6WW7c2PTbeujNM71IE2it1gHxnzQf%2BWHPDOjIjd27zfoF7tEUcRH8c06ksLtC7hCb0gC1ykq4sisHvmFWA%3D&commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&tenantDomain=carbon.super&sessionDataKey=a53f4d01-f58a-4885-811e-0aa0c13abde8&relyingParty=travelocity.com&type=samlsso&sp=travelocity.com&isSaaSApp=false&authenticators=GoogleOIDCAuthenticator:test;BasicAuthenticator:LOCAL:LOCAL" "curl/7.52.1"

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
