### ISSUE TITLE
Error when getting available consent receipt for a user, when default public key is an EC public key 

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3038]
Steps to reproduce:
1) Change the default primary wso2carbon key store to a different one, with an ECDSA certificate and configure that in the carbon.xml as follows.
        ```<KeyStore>```
            ```<Location>${carbon.home}/repository/resources/security/keystore.jks</Location>```
           ```<Type>JKS</Type>```
            ```<Password>password</Password>```
            ```<KeyAlias>ec</KeyAlias>```
            ```<KeyPassword>password</KeyPassword>```
        ```</KeyStore>```
2) Configure travelocity and login
3) If the user already has a consent receipt, following exception is throwing in back end. 

> ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Error occurred while evaluating post authentication
org.wso2.carbon.identity.application.authentication.framework.exception.PostAuthenticationFailedException: Error occurred while retrieving consent data of user: indunil for service provider: sp_travelocity in tenant domain: carbon.super.
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.consent.ConsentMgtPostAuthnHandler.handlePreConsent(ConsentMgtPostAuthnHandler.java:201)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.consent.ConsentMgtPostAuthnHandler.handle(ConsentMgtPostAuthnHandler.java:106)
..........
Caused by: org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.consent.exception.SSOConsentServiceException: Error while retrieving user consents.
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.consent.SSOConsentServiceImpl.getReceipt(SSOConsentServiceImpl.java:988)
.............
Caused by: org.wso2.carbon.consent.mgt.core.exception.ConsentManagementServerException: Error while getting public cert of tenant: carbon.super.
	at org.wso2.carbon.consent.mgt.core.util.ConsentUtils.handleServerException(ConsentUtils.java:43)
	at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.getPublicKey(ConsentManagerImpl.java:863)

**Comment by IndunilRathnayake** [comment]
Fixed with https://github.com/wso2/carbon-consent-management/pull/89

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
