### ISSUE TITLE
 Error occurred while executing SQL script for migrating database when migrating from ISKM5.3.0 to 5.5.0

### ISSUE THREAD

**Issue by shavantha** [wso2/product-is#3047]
Noticed the below exception when migrating Identity key manager 5.3.0 to 5.5.0
```
[2018-04-05 13:24:52,578]  INFO {org.wso2.carbon.is.migration.service.SchemaMigrator} -   WSO2 Product Migration Service Task : Executing Identity Migration Scripts.
[2018-04-05 13:24:52,589] ERROR {org.wso2.carbon.is.migration.service.SchemaMigrator} -  Error occurred while executing SQL script for migrating database
java.lang.Exception: Error occurred while executing :  CREATE TABLE CM_PII_CATEGORY ( ID           INTEGER AUTO_INCREMENT, NAME         VARCHAR(255) NOT NULL, DESCRIPTION  VARCHAR(1023), DISPLAY_NAME VARCHAR(255), IS_SENSITIVE INTEGER      NOT NULL, TENANT_ID    INTEGER DEFAULT '-1234', UNIQUE KEY (NAME, TENANT_ID), PRIMARY KEY (ID) )
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:231)
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:162)
	at org.wso2.carbon.is.migration.service.SchemaMigrator.migrate(SchemaMigrator.java:75)
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:41)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:80)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:515)
	at org.wso2.carbon.core.init.CarbonServerManager.start(CarbonServerManager.java:220)
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.activate(CarbonCoreServiceComponent.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)
	at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1230)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1174)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1066)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5370)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5668)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1700)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1690)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Table "CM_PII_CATEGORY" already exists; SQL statement:
 CREATE TABLE CM_PII_CATEGORY ( ID           INTEGER AUTO_INCREMENT, NAME         VARCHAR(255) NOT NULL, DESCRIPTION  VARCHAR(1023), DISPLAY_NAME VARCHAR(255), IS_SENSITIVE INTEGER      NOT NULL, TENANT_ID    INTEGER DEFAULT '-1234', UNIQUE KEY (NAME, TENANT_ID), PRIMARY KEY (ID) ) [42101-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:109)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:181)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy21.execute(Unknown Source)
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:201)
	... 65 more
[2018-04-05 13:24:52,603] ERROR {org.wso2.carbon.is.migration.service.SchemaMigrator} -  java.lang.Exception: Error occurred while executing SQL script for migrating database
[2018-04-05 13:24:52,605]  INFO {org.wso2.carbon.is.migration.VersionMigration} -   WSO2 Product Migration Service Task : Version : 5.5.0, Migration Step : OAuthDataMigrator starting........................... 
[2018-04-05 13:24:52,660]  INFO {org.wso2.carbon.is.migration.service.v550.migrator.OAuthDataMigrator} -   WSO2 Product Migration Service Task : Migration starting on OAuth2 access token table.
[2018-04-05 13:24:52,672]  WARN {org.wso2.carbon.identity.oauth.config.OAuthServerConfiguration} -  Empty configuration element for <Type> under <RequestObjectBuilder> configuration.
[2018-04-05 13:24:52,672]  INFO {org.wso2.carbon.identity.oauth.config.OAuthServerConfiguration} -  'RequestObjectBuilder' element for Type: request_param_value_builderis not configured in identity.xml. Therefore instantiating default request object builder: org.wso2.carbon.identity.openidconnect.RequestParamRequestObjectBuilder
[2018-04-05 13:24:52,673]  INFO {org.wso2.carbon.is.migration.service.v550.migrator.OAuthDataMigrator} -   WSO2 Product Migration Service Task : Migration starting on OAuth2 authorization code table.
[2018-04-05 13:24:52,673]  INFO {org.wso2.carbon.is.migration.service.v550.migrator.OAuthDataMigrator} -   WSO2 Product Migration Service Task : Migration starting on OAuth2 consumer apps table.
[2018-04-05 13:24:52,673]  INFO {org.wso2.carbon.is.migration.VersionMigration} -   WSO2 Product Migration Service Task : Version : 5.5.0, Migration Step : BPSProfileDataMigrator starting........................... 
[2018-04-05 13:24:52,673]  INFO {org.wso2.carbon.is.migration.service.v550.migrator.BPSProfileDataMigrator} -   WSO2 Product Migration Service Task : Migration starting on BPS profile table.
[2018-04-05 13:24:52,882]  INFO {org.wso2.carbon.is.migration.VersionMigration} -   WSO2 Product Migration Service Task : Version : 5.5.0, Migration Step : UserStorePasswordMigrator starting........................... 
[2018-04-05 13:24:52,882]  INFO {org.wso2.carbon.is.migration.service.v550.migrator.UserStorePasswordMigrator} -   WSO2 Product Migration Service Task : Migration starting on Secondary User Stores
[2018-04-05 13:24:52,887]  INFO {org.wso2.carbon.is.migration.VersionMigration} -   WSO2 Product Migration Service Task : Version : 5.5.0, Migration Step : SysLogPropertiesMigrator starting........................... 
[2018-04-05 13:24:52,887]  INFO {org.wso2.carbon.is.migration.service.v550.migrator.SysLogPropertiesMigrator} -   WSO2 Product Migration Service Task : Migration starting on SYSLOG_PROPERTIES file
[2018-04-05 13:24:52,925]  INFO {org.wso2.carbon.is.migration.service.v550.RegistryDataManager} -  Sys log property password migrated for tenant : carbon.super
[2018-04-05 13:24:52,929]  INFO {org.wso2.carbon.is.migration.VersionMigration} -   WSO2 Product Migration Service Task : Version : 5.5.0, Migration Step : SchemaMigrator starting........................... 
[2018-04-05 13:24:52,929]  INFO {org.wso2.carbon.is.migration.service.SchemaMigrator} -   WSO2 Product Migration Service Task : Executing Identity Migration Scripts.

```

**Comment by shavantha** [comment]
Doc Impact :N/A

**Comment by radutache1** [comment]
Error occurred while executing :  CREATE TABLE CM_PII_CATEGORY ( ID           INTEGER AUTO_INCREMENT, NAME         VARCHAR(255) NOT NULL, DESCRIPTION  VARCHAR(1023), DISPLAY_NAME VARCHAR(255), IS_SENSITIVE INTEGER      NOT NULL, TENANT_ID    INTEGER DEFAULT '-1234', UNIQUE KEY (NAME, TENANT_ID), PRIMARY KEY (ID) ),

 I had the same issue. 
To solve it I modified in h2.sql file from migration-resources folder on CREATE TABLE CM_PII_CATEGORY to CREATE TABLE IF NOT EXIST CM_PII_CATEGORY. You have to check what DB you are using, default wso2 uses embedded H2 database, you might need to change in a diferent sql file.

**Comment by DMHP** [comment]
This issue is solved by now. Hence resolving the issue.
