### ISSUE TITLE
Cannot provision user with roles when many roles assigned to the user

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3098]
When we try to provision user who has more roles assigned then while provisioning there will be an exception regarding column length as follows. 
`Caused by: java.sql.BatchUpdateException: ORA-12899: value too large for column "M_ISU_X"."UM_USER_ATTRIBUTE"."UM_ATTR_VALUE" (actual: 260, maximum: 255)

	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:10500)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:230)
	at sun.reflect.GeneratedMethodAccessor150.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy20.executeBatch(Unknown Source)
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.addProperties(JDBCUserStoreManager.java:2993)`

This is because while provisoning the role claim is saved with all the roles assigned to that user in UM_USER_ATTRIBUTE. Ideally we should not save the role value in UM_USER_ATTRIBUTE.

**Comment by malithie** [comment]
This is fixed such that when role mapping is done only mapped roles gets stored in UM_USER_ATTRIBUTE. 
Need to exactly verify if role claim is configured whether there is a need to treat the role as an attribute.
