### ISSUE TITLE
NullPointers when unsupported operations are performed with SCIM2

### ISSUE THREAD

**Issue by yasassri** [wso2/product-is#3297]
When we send some unsupported requests to SCIM endpoint a NullPointer is thrown and the Error is propagated to the client. We need to handle these nullPointers.

**Endpoint**
https://localhost:9443/scim2/Bulk

**Request Payload**
```
{
     "schemas": ["urn:ietf:params:scim:api:messages:2.0:BulkRequest"],
     "Operations": [
       {
         "method": "POST",
         "path": "/Users",
         "bulkId": "qwerty",
         "data": {
           "schemas": ["urn:ietf:params:scim:schemas:core:2.0:User"],
           "userName": "Alice",
           "password": "password"
         }
       },
       {
         "method": "POST",
         "path": "/Groups",
         "bulkId": "ytrewq",
         "data": {
           "schemas": ["urn:ietf:params:scim:schemas:core:2.0:Group"],
           "displayName": "TourGuides",
           "members": [
             {
               "type": "User",
               "value": "bulkId:qwerty"
             }
           ]
         }
       }
     ]
   }
```

**Exception**

**Server Side**

```
ERROR {org.apache.catalina.core.StandardWrapperValve} -  Servlet.service() for servlet [SCIM2Servlet] in context with path [/scim2] threw exception
wso2_1      | java.lang.RuntimeException: org.apache.cxf.interceptor.Fault
wso2_1      | 	at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:116)
wso2_1      | 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:336)
wso2_1      | 	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
wso2_1      | 	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:249)
wso2_1      | 	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)
wso2_1      | 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)
wso2_1      | 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)
wso2_1      | 	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
wso2_1      | 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)
wso2_1      | 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:209)
wso2_1      | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
wso2_1      | 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:265)
wso2_1      | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
wso2_1      | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
wso2_1      | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
wso2_1      | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
wso2_1      | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
wso2_1      | 	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
wso2_1      | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
wso2_1      | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
wso2_1      | 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
wso2_1      | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
wso2_1      | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
wso2_1      | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
wso2_1      | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
wso2_1      | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:607)
wso2_1      | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
wso2_1      | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
wso2_1      | 	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
wso2_1      | 	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:83)
wso2_1      | 	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:82)
wso2_1      | 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
wso2_1      | 	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
wso2_1      | 	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
wso2_1      | 	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
wso2_1      | 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
wso2_1      | 	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
wso2_1      | 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
wso2_1      | 	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
wso2_1      | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
wso2_1      | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
wso2_1      | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
wso2_1      | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
wso2_1      | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
wso2_1      | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
wso2_1      | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
wso2_1      | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
wso2_1      | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
wso2_1      | 	at java.lang.Thread.run(Thread.java:748)
wso2_1      | Caused by: org.apache.cxf.interceptor.Fault
wso2_1      | 	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:170)
wso2_1      | 	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:136)
wso2_1      | 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)
wso2_1      | 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
wso2_1      | 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
wso2_1      | 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)
wso2_1      | 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
wso2_1      | 	... 47 more
wso2_1      | Caused by: java.lang.NullPointerException
wso2_1      | 	at org.wso2.charon3.core.objects.Group.getMembersWithDisplayName(Group.java:110)
wso2_1      | 	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.createGroup(SCIMUserManager.java:635)
wso2_1      | 	at org.wso2.charon3.core.protocol.endpoints.GroupResourceManager.create(GroupResourceManager.java:143)
wso2_1      | 	at org.wso2.charon3.core.protocol.BulkRequestProcessor.getBulkResponseContent(BulkRequestProcessor.java:134)
wso2_1      | 	at org.wso2.charon3.core.protocol.BulkRequestProcessor.processBulkRequests(BulkRequestProcessor.java:110)
wso2_1      | 	at org.wso2.charon3.core.protocol.endpoints.BulkResourceManager.processBulkData(BulkResourceManager.java:69)
wso2_1      | 	at org.wso2.carbon.identity.scim2.provider.resources.BulkResource.createUser(BulkResource.java:74)
wso2_1      | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
wso2_1      | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
wso2_1      | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
wso2_1      | 	at java.lang.reflect.Method.invoke(Method.java:498)
wso2_1      | 	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:188)
wso2_1      | 	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104)
wso2_1      | 	... 52 more
```

**Client Side** 

```
<html><head><title>Apache Tomcat/7.0.85 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 500 - org.apache.cxf.interceptor.Fault</h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u>org.apache.cxf.interceptor.Fault</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>java.lang.RuntimeException: org.apache.cxf.interceptor.Fault
	org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:116)
	org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:336)
	org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:249)
	org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)
	org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:209)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:265)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
</pre></p><p><b>root cause</b> <pre>org.apache.cxf.interceptor.Fault
	org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:170)
	org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:136)
	org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)
	org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
	org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
	org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)
	org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:249)
	org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)
	org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:209)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:265)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
</pre></p><p><b>root cause</b> <pre>java.lang.NullPointerException
	org.wso2.charon3.core.objects.Group.getMembersWithDisplayName(Group.java:110)
	org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.createGroup(SCIMUserManager.java:635)
	org.wso2.charon3.core.protocol.endpoints.GroupResourceManager.create(GroupResourceManager.java:143)
	org.wso2.charon3.core.protocol.BulkRequestProcessor.getBulkResponseContent(BulkRequestProcessor.java:134)
	org.wso2.charon3.core.protocol.BulkRequestProcessor.processBulkRequests(BulkRequestProcessor.java:110)
	org.wso2.charon3.core.protocol.endpoints.BulkResourceManager.processBulkData(BulkResourceManager.java:69)
	org.wso2.carbon.identity.scim2.provider.resources.BulkResource.createUser(BulkResource.java:74)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:188)
	org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104)
	org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)
	org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
	org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
	org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)
	org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:249)
	org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)
	org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)
	org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:209)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:265)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.85 logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.85</h3></body></html>
```

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
