### ISSUE TITLE
Issue with trying to setup both SMSOTP and EmailOTP for MFA

### ISSUE THREAD

**Issue by kimaniv** [wso2/product-is#3298]
I have been trying to set up wso2is to allow the user to select between using email or sms to handle mfa. I followed this [guide](https://docs.wso2.com/display/IS550/Configuring+SMS+OTP) for SMS and this [guide](https://docs.wso2.com/display/IS550/Configuring+Email+OTP) for Email. Separately, they work, however when I include both options in the "Step Two" for the authentication setup for the travelocity sample Service Provider, only SMSOTP works, while EmailOTP fails.

This is my "Advanced Authentication Configuration":
![image](https://user-images.githubusercontent.com/4153842/41357398-b64dc6f0-6eeb-11e8-9909-3c70498f118a.png)

When I try to use EmailOTP when this configuration is set up, I receive an email with the code, and I can enter it into the next screen just fine. However, once I enter that code, I see the following stacktrace appear:

> [2018-06-13 09:18:02,472] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} -  Error while sending the HTTP request.
org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: Error while sending the HTTP request.
	at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.proceedWithOTP(SMSOTPAuthenticator.java:475)
	at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.initiateAuthenticationRequest(SMSOTPAuthenticator.java:155)
	at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.process(SMSOTPAuthenticator.java:98)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:487)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handleResponse(DefaultStepHandler.java:461)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:164)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:176)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:132)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:145)
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:91)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:60)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.MalformedURLException: no protocol:
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.sendRESTCall(SMSOTPAuthenticator.java:858)
	at org.wso2.carbon.identity.authenticator.smsotp.SMSOTPAuthenticator.proceedWithOTP(SMSOTPAuthenticator.java:452)
	... 60 more

I currently have the EmailOTP set up with AWS SES, which means I'm skipping the "Configure the Email OTP provider" step for the "Configuring Email OTP" tutorial. However, I am able to receive emails and properly authenticate with the emailed code IF only EmailOTP is set up for that service provider.

I saw someone else with this error on StackOverflow (See [here](https://stackoverflow.com/questions/48058476/does-wso2-support-smsotp-and-emailotp-together)), but I didn't see a proper resolution for the issue.

Interestingly, when I set up the EmailOTP Identity Provider to use both Email and SMS as Federated Authenticators, the email prompt works, but forces the user to also answer the SMS OTP challenge as well.

**Comment by dilin993** [comment]
This error occurs due to invalid "SMS URL" in "SMS OTP Configuration". With the proper configuration both SMS OTP and Email OTP will work. Please recheck your configuration.

**Comment by kimaniv** [comment]
To clarify, I have two identity providers at the moment:

The first one is called SMS IDP, and it only has SMS OTP enabled as a federated authenticator. The configuration looks like this: 
![image](https://user-images.githubusercontent.com/4153842/41659055-d8aa17c2-745d-11e8-8518-ee32144ee9e8.png)
Following the steps listed here: [(https://docs.wso2.com/display/IS550/Configuring+SMS+OTP#ConfiguringSMSOTP-Configuringtheidentityprovider)]


The second one is called Email IDP, and it only has Email OTP enabled as a federated authenticator. The configuration looks like this:
![image](https://user-images.githubusercontent.com/4153842/41659168-22661c9e-745e-11e8-86e6-7acae7e088f0.png)
Following the steps listed here: [https://docs.wso2.com/display/IS550/Configuring+Email+OTP]


With the travelocity Service Provider "Advanced Authentication Configuration" set up as in the original post (with both identity providers listed as a federated authenticator), I see this screen after the initial prompt for username and password:
![image](https://user-images.githubusercontent.com/4153842/41659324-93dd6b02-745e-11e8-87e0-82fce9c81146.png)
When I choose "SMS IDP", I receive the SMS with the token, and am able to properly log in.
When I choose "Email IDP", I receive an email with the token, however, after entering in the email with the code, I am redirected back to the "IDP Choice screen" in the above screenshot, and in the terminal window running wso2, the error I dumped in the original post shows up.


However, when I set up the "Advanced Authentication Configuration" of the travelocity Service Provider to look like this:
![image](https://user-images.githubusercontent.com/4153842/41659547-36ded7c8-745f-11e8-9450-635c17860161.png)
with only the Email IDP enabled, I am able to use the emailed code to successfully log in.


It looks like for some reason, when I have both the SMS IDP and Email IDP listed in the Advanced Authentication Configuration, when Email IDP is chosen, wso2 is trying to also send an SMS OTP after the initial Email OTP succeeded, but fails because I set up the Email IDP to only have Email OTP. This only seems to happen IF both IDPs are set up. Having only one or the other set up leads to expected results.

I am using wso2is version 5.3.0 in this situation

**Comment by kimaniv** [comment]
UPDATE:

I switched to using wso2is version 5.5.0 and the problem appears to have gone away. I am now able to use both SMS and Email properly for MFA options.
