### ISSUE TITLE
Cannot access registry->browse to create a custom scope to group together custom claims for user info. JSP exception thrown

### ISSUE THREAD

**Issue by djphan** [wso2/product-is#3445]
Hi,

I am creating some custom claims that I'm verifying I can retrieve in the user info endpoint. I was able to do so by setting the subject URI to point to my custom claim URI and display my custom values in the subject field.

In reading online I found guide here: https://medium.com/@dewni.matheesha/claim-mapping-and-retrieving-end-user-information-in-wso2is-cffd5f3937ff

To create a custom scope or edit the existing scopes to allow for my custom claim values to be displayed. When I go and to Registry->Browse I get a blank page and  a long stack trace error of the app trying to render the JSP attached below.

I don't know where to begin to debug this and can require assistance in moving forward.

I am running 5.5.0 inside a docker image on Mac for reference.

```
[2018-07-18 23:50:31,716] ERROR -  Servlet.service() for servlet bridgeservlet threw exception {org.apache.catalina.core.ApplicationDispatcher}
org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: 105 in the jsp file: /resources/resource_tree_ajaxprocessor.jsp
The method forHtml(String) in the type Encode is not applicable for the arguments (boolean)
102:                                                 class="picked-path-textbox" <%= (expansionPath != null) ? "value=\"" + expansionPath + "\"" : ""%> style="width:500px;"
103:                                                 onfocus="setResolvedResourcePathOnConsumer('<%=Encode.forHtml(resourceConsumer)%>','<%=Encode.forHtml(synapseRegistryRoot)%>');" onchange="setResolvedResourcePathOnConsumer('<%=Encode.forHtml(resourceConsumer)%>','<%=Encode.forHtml(synapseRegistryRoot)%>')"/>
104:                                             <input type="button" class="button" value="<fmt:message key="ok"/>"
105:                                                    onclick="if ((typeof(isMediationLocalEntrySelected) == undefined )|| !isMediationLocalEntrySelected) { if (validateResoucePath()) { handle<%= Encode.forHtml(relativeRoot) ? "Relative" : "" %>WindowOk(<%= Encode.forHtml(relativeRoot) ? "'" + Encode.forHtml(displayPath) + "', " : "" %>'<%=Encode.forJavaScript(textBoxId)%>'<%= onOKCallback != null ? ", " + Encode.forJavaScript(onOKCallback) : ""%>); CARBON.closeWindow(); return true; } return false; }; CARBON.closeWindow(); return true;"/>
106:     </div>
107:     </fmt:bundle>
108:     <%      } %>


An error occurred at line: 105 in the jsp file: /resources/resource_tree_ajaxprocessor.jsp
The method forHtml(String) in the type Encode is not applicable for the arguments (boolean)
102:                                                 class="picked-path-textbox" <%= (expansionPath != null) ? "value=\"" + expansionPath + "\"" : ""%> style="width:500px;"
103:                                                 onfocus="setResolvedResourcePathOnConsumer('<%=Encode.forHtml(resourceConsumer)%>','<%=Encode.forHtml(synapseRegistryRoot)%>');" onchange="setResolvedResourcePathOnConsumer('<%=Encode.forHtml(resourceConsumer)%>','<%=Encode.forHtml(synapseRegistryRoot)%>')"/>
104:                                             <input type="button" class="button" value="<fmt:message key="ok"/>"
105:                                                    onclick="if ((typeof(isMediationLocalEntrySelected) == undefined )|| !isMediationLocalEntrySelected) { if (validateResoucePath()) { handle<%= Encode.forHtml(relativeRoot) ? "Relative" : "" %>WindowOk(<%= Encode.forHtml(relativeRoot) ? "'" + Encode.forHtml(displayPath) + "', " : "" %>'<%=Encode.forJavaScript(textBoxId)%>'<%= onOKCallback != null ? ", " + Encode.forJavaScript(onOKCallback) : ""%>); CARBON.closeWindow(); return true; } return false; }; CARBON.closeWindow(); return true;"/>
106:     </div>
107:     </fmt:bundle>
108:     <%      } %>


Stacktrace:
	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:103)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:366)
	at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:498)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:379)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:341)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:660)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:364)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:603)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:542)
	at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:37)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor$RequestDispatcherAdaptor.include(ContextPathServletAdaptor.java:369)
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:905)
	at org.apache.jsp.resources.tree_005fview_005fajaxprocessor_jsp._jspService(tree_005fview_005fajaxprocessor_jsp.java:130)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
```

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
