### ISSUE TITLE
Getting org.wso2.carbon.registry.core.exceptions.ResourceNotFoundException when trying to delete old captcha details from the registry

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#3482]
**Product version**: wso2is-5.1.0

### Steps to reproduce:

1. Create a captcha image using the soap API getCaptcha() of service https://localhost:9443/services/UserInformationRecoveryService?wsdl

1. Delete only the captcha image from the registry after 20mins
(management console -> Registry -> Browse -> _system -> config -> repository -> components -> org.wso2.carbon.captcha-images)

1. Now try to call the getCaptcha() API. 

1. You will end up with the below error in the IS server
```
[2018-07-26 12:21:10,198] ERROR {org.wso2.carbon.captcha.mgt.util.CaptchaUtil} -  Error in cleaning old captchas.
org.wso2.carbon.registry.core.exceptions.RegistryException: Could not delete the remote resource. Resource does not exist at path /_system/is_config/repository/components/org.wso2.carbon.captcha-images/cf0469fc-507f-4ec0-8e5d-268e33387fa8.jpg
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.delete(MountHandler.java:515)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.delete(HandlerManager.java:2627)
	at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.delete(UserDefinedHandlerManager.java:215)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.delete(HandlerLifecycleManager.java:443)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.delete(EmbeddedRegistry.java:843)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.delete(CacheBackedRegistry.java:554)
	at org.wso2.carbon.registry.core.session.UserRegistry.deleteInternal(UserRegistry.java:866)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$1100(UserRegistry.java:60)
	at org.wso2.carbon.registry.core.session.UserRegistry$12.run(UserRegistry.java:841)
	at org.wso2.carbon.registry.core.session.UserRegistry$12.run(UserRegistry.java:838)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.delete(UserRegistry.java:838)
	at org.wso2.carbon.captcha.mgt.util.CaptchaUtil$1.run(CaptchaUtil.java:90)
Caused by: org.wso2.carbon.registry.core.exceptions.ResourceNotFoundException: Resource does not exist at path /_system/is_config/repository/components/org.wso2.carbon.captcha-images/cf0469fc-507f-4ec0-8e5d-268e33387fa8.jpg
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.get(EmbeddedRegistry.java:532)
	at org.wso2.carbon.identity.entitlement.policy.finder.registry.RegistryPolicyMediaTypeMatcher.handleDelete(RegistryPolicyMediaTypeMatcher.java:49)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.delete(HandlerManager.java:2622)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.delete(HandlerLifecycleManager.java:447)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.delete(EmbeddedRegistry.java:843)
	at org.wso2.carbon.registry.core.session.UserRegistry.deleteInternal(UserRegistry.java:866)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$1100(UserRegistry.java:60)
	at org.wso2.carbon.registry.core.session.UserRegistry$12.run(UserRegistry.java:841)
	at org.wso2.carbon.registry.core.session.UserRegistry$12.run(UserRegistry.java:838)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.delete(UserRegistry.java:838)
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.delete(MountHandler.java:508)
	... 12 more
```

**Comment by bastienS31** [comment]
Hello, I use the soap API getCaptcha(), and I have this problem even without manually deleting the image file. I think WSO2IS 5.8 got lost.

As things progress, occasionaly, i have this kind of error :
`TID: [2020-05-21 00:07:11,501] ERROR {wso2is.Wso2isServiceManager} -  Read timed out {wso2is.Wso2isServiceManager}
org.apache.axis2.AxisFault: Read timed out
	at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:203)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:81)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:459)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:286)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:442)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.wso2.carbon.identity.mgt.stub.UserInformationRecoveryServiceStub.getCaptcha(UserInformationRecoveryServiceStub.java:4339)`

After a WSO2IS restart, all is ok for a short time (few days), and we still have this error.
How can we fix this permanently?
Thanks :)

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
