### ISSUE TITLE
jdbc.SQLServerException occurred in org.wso2.identity.integration.test.consent.SelfSignUpConsentTest class when running against MSSQL Server Database

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#3564]
**Product:** wso2is-5.7.0-alpha2
**Database:** MSSQL Server
**OS:** CentOS
**JDK:** Oracle JDK

Following error occurs in the org.wso2.identity.integration.test.consent.SelfSignUpConsentTest class for selfSignUpWithConsents, testPurposesWithoutConfiguredPurposes, testForValidUsername, testWithPurposes, getPurposes methods while running the IS Integration tests against **MS SQL Server database.** 

> ERROR {org.wso2.carbon.consent.mgt.endpoint.impl.ConsentsApiServiceImpl} -  Error occurred while listing purpose from DB for group: SELF-SIGNUP, groupType: SYSTEM limit: 1 and offset: 100.
> 
> Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s'SELECT ID, NAME, DESCRIPTION, PURPOSE_GROUP, GROUP_TYPE, TENANT_ID FROM (SELECT ID, NAME, DESCRIPTION, TENANT_ID, ROW_NUMBER() OVER (ORDER BY ID) AS RowNum FROM CM_PURPOSE) AS P WHERE P.TENANT_ID = ? AND PURPOSE_GROUP LIKE ? AND GROUP_TYPE LIKE ? AND P.RowNum BETWEEN ? AND ?
> 
> [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'PURPOSE_GROUP'.

Find the full stack trace below. 

```
automation.log:2018-08-14 05:16:53,235 INFO  [org.wso2.carbon.automation.engine.testlisteners.TestManagerListener] - =================== Running the test method org.wso2.identity.integration.test.consent.SelfSignUpConsentTest.selfSignUpWithConsents ===================
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-08-14 05:16:53,452] admin@wso2.com [1] [IS]ERROR {org.wso2.carbon.identity.user.endpoint.impl.MeApiServiceImpl} -  Error occurred in the server while performing the task.
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - org.wso2.carbon.identity.recovery.IdentityRecoveryServerException: Error while retrieving System purposes for self registration
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.validateAndFilterFromReceipt(UserSelfRegistrationManager.java:250)
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.registerUser(UserSelfRegistrationManager.java:154)
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.identity.user.endpoint.impl.MeApiServiceImpl.mePost(MeApiServiceImpl.java:78)
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.identity.user.endpoint.MeApi.mePost(MeApi.java:60)
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.lang.reflect.Method.invoke(Method.java:498)
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:191)
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
automation.log-2018-08-14 05:16:53,454 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:189)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:303)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:222)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:278)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:76)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:410)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:101)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:83)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:84)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:63)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
automation.log-2018-08-14 05:16:53,455 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.lang.Thread.run(Thread.java:748)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Caused by: org.wso2.carbon.consent.mgt.core.exception.ConsentManagementServerException: Error occurred while listing purpose from DB for group: SELF-SIGNUP, groupType: SYSTEM limit: 1 and offset: 100.
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.consent.mgt.core.dao.impl.PurposeDAOImpl.listPurposes(PurposeDAOImpl.java:249)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.listPurposes(ConsentManagerImpl.java:258)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.consent.mgt.core.InterceptingConsentManager$5.execute(InterceptingConsentManager.java:250)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.consent.mgt.core.InterceptingConsentManager$5.execute(InterceptingConsentManager.java:246)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.consent.mgt.core.model.ConsentInterceptorTemplate.executeWith(ConsentInterceptorTemplate.java:56)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.consent.mgt.core.InterceptingConsentManager.listPurposes(InterceptingConsentManager.java:246)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.identity.recovery.signup.UserSelfRegistrationManager.validateAndFilterFromReceipt(UserSelfRegistrationManager.java:243)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	... 63 more
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s'SELECT ID, NAME, DESCRIPTION, PURPOSE_GROUP, GROUP_TYPE, TENANT_ID FROM (SELECT ID, NAME, DESCRIPTION, TENANT_ID, ROW_NUMBER() OVER (ORDER BY ID) AS RowNum FROM CM_PURPOSE) AS P WHERE P.TENANT_ID = ? AND PURPOSE_GROUP LIKE ? AND GROUP_TYPE LIKE ? AND P.RowNum BETWEEN ? AND ?
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.executeQuery(JdbcTemplate.java:168)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.consent.mgt.core.dao.impl.PurposeDAOImpl.listPurposes(PurposeDAOImpl.java:233)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	... 69 more
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'PURPOSE_GROUP'.
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1547)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:548)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:479)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7344)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2713)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:401)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.lang.reflect.Method.invoke(Method.java:498)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.sun.proxy.$Proxy21.executeQuery(Unknown Source)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.executeQuery(JdbcTemplate.java:153)
automation.log-2018-08-14 05:16:53,456 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	... 70 more
automation.log:2018-08-14 05:16:53,482 INFO  [org.wso2.carbon.automation.engine.testlisteners.TestManagerListener] - =================== On test failure org.wso2.identity.integration.test.consent.SelfSignUpConsentTest.selfSignUpWithConsents ===================
```

Affected-version: 5.7.0 alpha2
Priority/ Highest
Severity/ Critical
Type/ Bug

**Comment by oscarvesga** [comment]
Hi, I get this error in the docker image `wso2/wso2is:5.10.0` when I try to activated and tested the selft register proceed.
```
identity-server_1  | [2020-04-07 02:50:12,673] [125d4bd4-ad4f-4b99-925f-c18181e66686] ERROR {org.wso2.carbon.consent.mgt.endpoint.impl.ConsentsApiServiceImpl} - Error occurred while listing purpose from DB for group: SELF-SIGNUP, groupType: SYSTEM limit: 100 and offset: 0. org.wso2.carbon.consent.mgt.core.exception.ConsentManagementServerException: Error occurred while listing purpose from DB for group: SELF-SIGNUP, groupType: SYSTEM limit: 100 and offset: 0.
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.dao.impl.PurposeDAOImpl.listPurposes(PurposeDAOImpl.java:249)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.ConsentManagerImpl.listPurposes(ConsentManagerImpl.java:262)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.PrivilegedConsentManagerImpl$5.execute(PrivilegedConsentManagerImpl.java:226)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.PrivilegedConsentManagerImpl$5.execute(PrivilegedConsentManagerImpl.java:222)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.model.ConsentInterceptorTemplate.executeWith(ConsentInterceptorTemplate.java:56)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.PrivilegedConsentManagerImpl.listPurposes(PrivilegedConsentManagerImpl.java:222)
identity-server_1  |    at org.wso2.carbon.consent.mgt.endpoint.impl.ConsentsApiServiceImpl.getPurposeListResponseDTO(ConsentsApiServiceImpl.java:420)
.
.
.
identity-server_1  | Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s'SELECT ID, NAME, DESCRIPTION, PURPOSE_GROUP, GROUP_TYPE, TENANT_ID FROM CM_PURPOSE WHERE TENANT_ID = ? AND PURPOSE_GROUP LIKE ? AND GROUP_TYPE LIKE ? ORDER BY ID ASC LIMIT ? OFFSET ?
identity-server_1  |    at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.executeQuery(JdbcTemplate.java:169)
identity-server_1  |    at org.wso2.carbon.consent.mgt.core.dao.impl.PurposeDAOImpl.listPurposes(PurposeDAOImpl.java:233)
identity-server_1  |    ... 61 more
identity-server_1  | Caused by: java.sql.SQLSyntaxErrorException: Table 'WSO2IS_IDENTITY_DB.CM_PURPOSE' doesn't exist
identity-server_1  |    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
identity-server_1  |    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
```
