### ISSUE TITLE
[IS-Integration Tests]User claim does not get deleted when oracle database is used 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-is#3606]
While running IS Integration Tests, user does not get deleted since there is pending workflow, which is user claim is yet to be deleted. 

**OS**: CentOS 7.4
**Database**: Oracle 12c
**JDK**: Oracle JDK 8
**Product**: wso2is-5.7.0-alpha3
**Test class**: org.wso2.identity.integration.test.workflow.mgt.WorkflowManagementTestCase
**Testcase**: testDeleteUserOperation

```
java.lang.AssertionError: Failed to delete claim of user
	at org.wso2.identity.integration.test.workflow.mgt.WorkflowManagementTestCase.testDeleteUserOperation(WorkflowManagementTestCase.java:524)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

Please find the full automation log below. 

```
automation.log:2018-08-21 14:47:51,741 INFO  [org.wso2.carbon.automation.engine.testlisteners.TestManagerListener] - =================== Running the test method org.wso2.identity.integration.test.workflow.mgt.WorkflowManagementTestCase.testDeleteUserOperation ===================
automation.log-2018-08-21 14:47:51,827 WARN  [org.apache.commons.httpclient.HttpMethodBase] - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
automation.log-2018-08-21 14:47:51,899 WARN  [org.apache.commons.httpclient.HttpMethodBase] - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
automation.log-2018-08-21 14:47:52,001 WARN  [org.apache.commons.httpclient.HttpMethodBase] - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
automation.log-2018-08-21 14:47:52,084 WARN  [org.apache.commons.httpclient.HttpMethodBase] - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
automation.log-2018-08-21 14:47:52,165 WARN  [org.apache.commons.httpclient.HttpMethodBase] - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
automation.log-2018-08-21 14:47:52,227 WARN  [org.apache.commons.httpclient.HttpMethodBase] - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
automation.log-2018-08-21 14:47:52,341 WARN  [org.apache.commons.httpclient.HttpMethodBase] - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
automation.log-2018-08-21 14:47:52,551 WARN  [org.apache.commons.httpclient.HttpMethodBase] - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
automation.log-2018-08-21 14:47:52,656 WARN  [org.apache.commons.httpclient.HttpMethodBase] - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
automation.log-2018-08-21 14:47:52,795 WARN  [org.apache.commons.httpclient.HttpMethodBase] - Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
automation.log-2018-08-21 14:49:32,709 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-08-21 14:47:57,801]  INFO {org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl} -  Deploying BPEL archive: TestWorkflowAddUser1.zip
automation.log-2018-08-21 14:49:32,712 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-08-21 14:47:57,805]  INFO {openjpa.Runtime} -  Starting OpenJPA 2.2.0-wso2v1
automation.log-2018-08-21 14:49:32,714 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-08-21 14:47:57,806]  INFO {openjpa.jdbc.JDBC} -  Using dictionary class "org.apache.openjpa.jdbc.sql.OracleDictionary" (Oracle Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
automation.log-2018-08-21 14:49:32,715 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options ,Oracle JDBC driver 12.2.0.1.0).
automation.log-2018-08-21 14:49:32,709 ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Cannot read edition.properties file located using ClassLoader org.eclipse.core.runtime.internal.adaptor.ContextFinder@1c2678cd - continuing
automation.log-2018-08-21 14:49:32,715 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-08-21 14:47:58,042]  INFO {org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl} -  Starting deployment of processes from directory /Users/IsuruUyanage/Documents/ISIntegration/clone/integration-tests/product-is/modules/integration/tests-integration/tests-backend/target/carbontmp1534842954930/wso2is-5.7.0-alpha3/repository/bpel/-1234/TestWorkflowAddUser1-1
automation.log-2018-08-21 14:49:32,715 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-08-21 14:47:58,582]  INFO {org.wso2.carbon.bpel.core.ode.integration.config.EndpointConfigBuilder} -  Endpoint reference file:callbackService.epr
automation.log-2018-08-21 14:49:32,715 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-08-21 14:47:58,584]  INFO {org.wso2.carbon.bpel.core.ode.integration.config.EndpointConfigBuilder} -  Endpoint reference file:taskService.epr
automation.log-2018-08-21 14:49:32,716 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-08-21 14:47:58,965]  INFO {org.wso2.carbon.core.deployment.DeploymentInterceptor} -  Deploying Axis2 service: TestWorkflowAddUser1Service {super-tenant}
automation.log-2018-08-21 14:49:32,716 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-08-21 14:47:58,977]  INFO {org.wso2.carbon.core.deployment.DeploymentInterceptor} -  Deploying Axis2 service: TestWorkflowAddUser1TaskServiceCB {super-tenant}
automation.log-2018-08-21 14:49:32,717 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-08-21 14:47:59,792]  INFO {org.wso2.carbon.humantask.deployer.HumanTaskDeployer} -  Deploying HumanTask archive [ TestWorkflowAddUser1Task.zip ]
automation.log-2018-08-21 14:49:32,717 INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2018-08-21 14:47:59,893]  INFO {org.wso2.carbon.core.deployment.DeploymentInterceptor} -  Deploying Axis2 service: TestWorkflowAddUser1TaskService {super-tenant}
automation.log-2018-08-21 14:49:32,715 ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 
automation.log-2018-08-21 14:49:32,717 ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Cannot read edition.properties file located using ClassLoader org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader@93797ed[saxon.he:9.4.0.wso2v1(id=535)] - continuing
automation.log-2018-08-21 14:49:32,718 ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 
automation.log:2018-08-21 14:53:18,108 INFO  [org.wso2.carbon.automation.engine.testlisteners.TestManagerListener] - =================== On test failure org.wso2.identity.integration.test.workflow.mgt.WorkflowManagementTestCase.testDeleteUserOperation ===================

```

Type/Bug
Severity/Major
Priority/Highest
Affected/5.7.0-alpha3

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
