### ISSUE TITLE
Couldn't add service provider with postgresql

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3664]
**Affected/wso2is-5.7.0-beta2-SNAPSHOT**
1. Configure postgre sql as the database
2. Adding a new service provider through management console.
3. Following exception occurs.
`[2018-09-02 10:15:30,019] ERROR {org.wso2.carbon.identity.application.mgt.ApplicationManagementAdminService} -  Error while getting all the application template basic info for tenant: carbon.super.
org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error while Loading all the application template basic info of tenant: carbon.super
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationTemplateDAOImpl.getAllApplicationTemplateInfo(ApplicationTemplateDAOImpl.java:210)
........................................
	... 142 more

Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:150)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:113)
	at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy19.executeQuery(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.executeQuery(JdbcTemplate.java:153)
	... 143 more

Caused by: org.postgresql.util.PSQLException: ERROR: relation "sp_template" does not exist
  Position: 31
	... 156 more
`

**Comment by nilasini** [comment]
According to [1] changing the masterdatasources.xml file configuration from

`<defaultAutoCommit>false</defaultAutoCommit>`

to

`<defaultAutoCommit>true</defaultAutoCommit>`

solves the issue.

[1] https://medium.com/@circlee7/postgresql-hibernate-error-cannot-change-transaction-isolation-level-in-the-middle-of-a-ddc92252fb8e
