### ISSUE TITLE
Java Security Manager Privilege Block Error

### ISSUE THREAD

**Issue by wijith7** [wso2/product-is#3769]
Description:

Error [1] comes when useing identity-outbound-auth-passwordPolicy-1.0.7 with the IS 5.6.0.

When we adding a new user or changing a password it shows the error.

[1] ERROR {org.wso2.carbon.user.mgt.UserRealmProxy} - Error occurred while accessing Java
Security Manager Privilege Block

Error log

[2018-09-20 12:15:20,754] ERROR {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Error occurred while accessing Java Security Manager Privilege Block
[2018-09-20 12:15:20,756] ERROR {org.wso2.carbon.user.mgt.ui.UserAdminClient} - Error occurred while accessing Java Security Manager Privilege Block
org.wso2.carbon.user.mgt.stub.UserAdminUserAdminException: UserAdminUserAdminException
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at java.lang.Class.newInstance(Class.java:442)
at org.wso2.carbon.user.mgt.stub.UserAdminStub.changePasswordByUser(UserAdminStub.java:674)
at org.wso2.carbon.user.mgt.ui.UserAdminClient.changePasswordByUser(UserAdminClient.java:244)
at org.apache.jsp.user.change_002dpasswd_002dfinish_002dajaxprocessor_jsp._jspService(change_002dpasswd_002dfinish_002dajaxprocessor_jsp.java:143)
at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)

**Comment by edwardsj89** [comment]
I see this issue is closed but I don't see any reason given as to the cause so just to add how I fixed my issue and perhaps it will help someone else.

So basically I had written a custom User Store Manager and on some of the overrides I wanted to call out to an external Api, I had written an Api Client using okhttp and the client itself was working fine but as soon as I called anything referencing the client I got the **Java Security Manager Privilege Block Error**.

It turns out the cause of the error was some missing dependencies that needed to be copied into the `<WSO2IS_HOME/repository/components/lib/>` directory in this case (`okhttp` and `okio`) after doing that my Api call was successful and no more error
