### ISSUE TITLE
NPE when testing retry flow with MFA authentication + conditional authentication script

### ISSUE THREAD

**Issue by hastef88** [wso2/product-is#3819]
## Purpose

When trying out MFA authentication with conditional auth script enabled, if the user enters the wrong OTP code at the EmailOTP screen, they are not redirected to the retry attempt. Instead they are taken to the retry.do page with following exception : 

```
TID: [-1234] [] [2018-10-11 12:05:57,577] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Exception in Authentication Framework
java.lang.NullPointerException
        at org.wso2.carbon.extension.identity.helper.FederatedAuthenticatorUtil.setUsernameFromFirstStep(FederatedAuthenticatorUtil.java:399)
        at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.initiateAuthenticationRequest(EmailOTPAuthenticator.java:160)
        at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.process(AbstractApplicationAuthenticator.java:71)
        at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.process(EmailOTPAuthenticator.java:125)
        at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:490)
        at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:256)
        at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handleAuthenticationStep(GraphBasedSequenceHandler.java:271)
        at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handleNode(GraphBasedSequenceHandler.java:120)
        at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:105)
        at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:132)
        at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:159)
```

Samle auth script : 

```
function onInitialRequest(context) {
    retryCount = 5;
    executeBasicAuth(context, retryCount);
}

function executeBasicAuth(context, retryCount) {
    Log.info('--------------- executeBasicAuth retryCount ' + retryCount);

    executeStep(1, {
        onSuccess: function(context) {
            emailRetryCount = 5;
            executeEmailOTP(context, emailRetryCount);
        },
        onFail: function(context) {
            Log.info('--------------- fail retryCount ' + retryCount);
            --retryCount;
            if (retryCount > 0) {
                executeBasicAuth(context, retryCount);
            } else {
                Log.info('--------------- login failed ');
            }
        }
    });
}

function executeEmailOTP(context, emailRetryCount) {
    Log.info('--------------- executeEmailOTP retryCount ' + emailRetryCount);

    executeStep(2, {
        onSuccess: function(context) {
            Log.info('--------------- Email OTP Sucessful !');
        },
        onFail: function(context) {
            Log.info('--------------- fail retryCount ' + emailRetryCount);
            --emailRetryCount;
            if (emailRetryCount > 0) {
                executeEmailOTP(context, emailRetryCount);
            } else {
                Log.info('--------------- Email login failed ');
            }
        }
    });
}
```

## Approach

Possible Fix : Fixed the NPE by checking if each step has an authenticatedAuthenticator populated, and retrieve the username from first non-null occurance.

https://github.com/wso2-extensions/identity-extension-utils/pull/13

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
