### ISSUE TITLE
When adding secondary user store, Delete User Property contains a wrong SQL query

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3838]
**Steps to reproduce the error**

1. Create a secondary user store with "Case Insensitive Username"  enabled
2. Add a user through scim2
3. Patch the user using following curl.
`curl -v -k --user admin:admin -X PATCH -d '{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"replace","path":"emails[type eq home].value","value":"vinudla.info@gmail.com"}]}' --header "Content-Type:application/json" https://localhost:9443/scim2/Users/cee3ada2-361c-49d0-9e33-dc9ad80287b3`
4. You will get the following exception
`[2018-10-09 20:10:27,124] DEBUG -  Error occurred while updating string values to database. {org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager}
com.microsoft.sqlserver.jdbc.SQLServerException: The value is not set for the parameter number 6.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:227)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.buildParamTypeDefinitions(SQLServerPreparedStatement.java:307)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.buildPreparedStrings(SQLServerPreparedStatement.java:259)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:440)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:409)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7151)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2478)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:219)`

**Root cause:-** 

Delete User Property SQL query has to be changed from

`Delete User Property SQL :- UPDATE UM_USER_ATTRIBUTE SET UM_ATTR_VALUE=? WHERE UM_USER_ID=(SELECT UM_ID FROM UM_USER WHERE UM_USER_NAME=? AND UM_TENANT_ID=?) AND UM_ATTR_NAME=? AND UM_PROFILE_ID=? AND UM_TENANT_ID=?
`

to

`DELETE FROM UM_USER_ATTRIBUTE WHERE UM_USER_ID=(SELECT UM_ID FROM UM_USER WHERE UM_USER_NAME=? AND UM_TENANT_ID=?) AND UM_ATTR_NAME=? AND UM_PROFILE_ID=? AND UM_TENANT_ID=?
`

**Comment by madurangasiriwardena** [comment]
Keeping the issue open until the kernel is released with the fix.

**Comment by malithie** [comment]
Reopening as to be closed with https://github.com/wso2/product-is/issues/4894
