### ISSUE TITLE
Client credential grant with enabling Use tenant domain in local subject identifier

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#3875]
**Reproduce steps**

1. Create a service provider and configure openid connect as the inbound protocol
2. Tick "Use tenant domain in local subject identifier" from Local & Outbound Authentication Configuration
3. Use following curl command and try to get the access token with client  credential grant
`curl -u <client_id>:<client_secret> -k -d "grant_type=client_credentials" -H "Content-Type:application/x-www-form-urlencoded" https://localhost:9443/oauth2/token`

You will get the response as 
**{"error_description":"Internal Server Error.","error":"server_error"}**
`ERROR {org.wso2.carbon.identity.oauth2.OAuth2Service} -  Error occurred while issuing the access token for Client ID : z7aQtjrbWj4SHFU458JoeZtPEtYa, User ID null, Scope : [] and Grant Type : client_credentials
java.lang.IllegalArgumentException
	at org.wso2.carbon.user.core.util.UserCoreUtil.addTenantDomainToEntry(UserCoreUtil.java:558)
	at org.wso2.carbon.identity.application.authentication.framework.model.AuthenticatedUser.setAuthenticatedSubjectIdentifier(AuthenticatedUser.java:184)
	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.getLatestAccessToken(AccessTokenDAOImpl.java:433)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.getExistingTokenFromDB(AbstractAuthorizationGrantHandler.java:639)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.getExistingToken(AbstractAuthorizationGrantHandler.java:630)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.issue(AbstractAuthorizationGrantHandler.java:114)
	at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.issue(AccessTokenIssuer.java:275)
	at org.wso2.carbon.identity.oauth2.OAuth2Service.issueAccessToken(OAuth2Service.java:225)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:300)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
`

**Comment by DMHP** [comment]
https://github.com/wso2/carbon-identity-framework/pull/1958
