### ISSUE TITLE
Error when retrieving the application certificate

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3900]
Following error throws in IS, when there are issues retrieving the application certificate from keystore.
```
Caused by: java.util.MissingFormatArgumentException: Format specifier '%s'
at java.util.Formatter.format(Formatter.java:2519)
at java.util.Formatter.format(Formatter.java:2455)
at java.lang.String.format(String.java:2940)
at org.wso2.carbon.identity.core.KeyStoreCertificateRetriever.getCertificate(KeyStoreCertificateRetriever.java:60)
```

This is due to a bug in [1] where format specifier are not correctly defined.
[1] https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/KeyStoreCertificateRetriever.java#L60

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
