### ISSUE TITLE
Error in IDN_CERTIFICATE table creation script in postgres SQL 

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#3917]
Following error occurred while inserting application certificate in postgres.

```
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "id" violates not-null constraint
  Detail: Failing row contains (null, 1_8, -1234, -----BEGIN CERTIFICATE-----
MIIF1zCCBL+gAwIBAgIQUEqMZuco6Ar1zvh...).
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
......
org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.persistApplicationCertificate(ApplicationDAOImpl.java:523)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.updateApplicationCertificate(ApplicationDAOImpl.java:475)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.updateApplication(ApplicationDAOImpl.java:342)
	... 79 more
```
This error has occurred, since sequence IDN_CERTIFICATE_PK_SEQ is not associated with the ID column in IDN_CERTIFICATE table.

Add following script into the 5.3.0 migration client.
DROP TABLE IF EXISTS IDN_CERTIFICATE;
DROP SEQUENCE IF EXISTS IDN_CERTIFICATE_PK_SEQ;
CREATE SEQUENCE IDN_CERTIFICATE_PK_SEQ;
CREATE TABLE IDN_CERTIFICATE (
ID INTEGER DEFAULT NEXTVAL('IDN_CERTIFICATE_PK_SEQ'),
NAME VARCHAR(100),
CERTIFICATE_IN_PEM VARCHAR(4096),
TENANT_ID INTEGER DEFAULT 0,
CONSTRAINT CERTIFICATE_UNIQUE_KEY UNIQUE (NAME, TENANT_ID),
PRIMARY KEY (ID)
);

Please check the other IS versions that the feature of storing application certificate in DB is back ported and update migration client for those versions as well.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
