### ISSUE TITLE
SAML SSO logout not working when SLO is false. 

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#4010]
Getting following error when SLO is not enabled. This is happening due to session index is not passed with the saml logout request when SLO is disabled. It is required to check sessionIndex only when the SLO is enabled. 

`java.lang.NullPointerException
	at org.wso2.carbon.identity.sso.saml.processors.SPInitLogoutRequestProcessor.process(SPInitLogoutRequestProcessor.java:116)
	at org.wso2.carbon.identity.sso.saml.SAMLSSOService.validateSPInitSSORequest(SAMLSSOService.java:99)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleSPInitSSO(SAMLSSOProviderServlet.java:484)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleRequest(SAMLSSOProviderServlet.java:236)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.doPost(SAMLSSOProviderServlet.java:128)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)`

**Comment by LahiruLS** [comment]
Duplicate issue reported here: https://github.com/wso2/product-is/issues/4895

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
