### ISSUE TITLE
IS-KM-5.6.0 with EC certificate throws Error in secure vault flow

### ISSUE THREAD

**Issue by aselarbd** [wso2/product-is#4176]
IS-KM-5.6.0 throws following error in secure vault flow. As the algorithm used ECIESWITHAES-CBC encryption with PKCS5PADDING padding.

To setup, change carbon.properties in <IS_HOME>/repository/conf to
`org.wso2.CipherTransformation=ECIESWITHAES-CBC/NONE/PKCS5PADDING`

**Error**

> Exception in thread "main" org.wso2.ciphertool.exception.CipherToolException: Error initializing Cipher 
	at org.wso2.ciphertool.utils.KeyStoreUtil.initializeCipher(KeyStoreUtil.java:66)
	at org.wso2.ciphertool.CipherTool.main(CipherTool.java:53)
Caused by: java.security.InvalidKeyException: No installed provider supports this key: sun.security.ec.ECPublicKeyImpl
	at javax.crypto.Cipher.chooseProvider(Cipher.java:892)
	at javax.crypto.Cipher.init(Cipher.java:1724)
	at javax.crypto.Cipher.init(Cipher.java:1617)
	at org.wso2.ciphertool.utils.KeyStoreUtil.initializeCipher(KeyStoreUtil.java:58)
	... 1 more

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
