### ISSUE TITLE
Startup error occurs when JDBC Interceptors are used in the data sources.

### ISSUE THREAD

**Issue by rushmin** [wso2/product-is#4178]
**Configuration** 
```
<jdbcInterceptors>org.apache.tomcat.jdbc.pool.interceptor.QueryTimeoutInterceptor(queryTimeout=60); org.apache.tomcat.jdbc.pool.interceptor.SlowQueryReport(threshold=10000)</jdbcInterceptors>
```
**Error**
```
Caused by: java.lang.NumberFormatException: For input string: "10000)org.wso2.carbon.ndatasource.rdbms.CorrelationLogIntercepto"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.apache.tomcat.jdbc.pool.interceptor.SlowQueryReport.setProperties(SlowQueryReport.java:242)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:466)
```
**Workaround**

Adding a semicolon after the last interceptor.
```
<jdbcInterceptors>org.apache.tomcat.jdbc.pool.interceptor.QueryTimeoutInterceptor(queryTimeout=60); org.apache.tomcat.jdbc.pool.interceptor.SlowQueryReport(threshold=10000);</jdbcInterceptors>
```
**Cause**

Concatenating the configured interceptors with the OOTB observability interceptor happens without the delimiter (semicolon) [1]

[1] - https://github.com/wso2/carbon-kernel/blob/4.4.x/core/org.wso2.carbon.ndatasource.rdbms/src/main/java/org/wso2/carbon/ndatasource/rdbms/RDBMSDataSource.java#L65

**Comment by DMHP** [comment]
https://github.com/wso2/carbon-kernel/pull/1890

**Comment by isharailanga** [comment]
Fixed in https://github.com/wso2-support/carbon4-kernel/pull/527
