### ISSUE TITLE
Invocation of AccountRecoveryRESTEndpointURL leads to 401 http status code (Unauthorized)

### ISSUE THREAD

**Issue by PavelKaliadziuk** [wso2/product-is#4196]
**Description:**
After certificates were changed and WSO2IS was fronted by a load balancer (which redirects every incoming request from external IP to internal one) we faced the issue with resending confirmation email. It worked correctly before changes mentioned above. After user is successfully registered, there is an attempt to login. As a result the user sees warning message ("Account is unverified") and the link which allows to resend confirmation email in order to activate the account. After clicking on it the user sees error message "Email sent fail". 
It is the only place where we have an error, other functionality works correctly.

Http access logs contain the following row:

` "POST /t/carbon.super/api/identity/user/v0.9/resend-code HTTP/1.1" 401 - "-" "Apache CXF 2.7.16"
`

wso2carbon.log contains NPE:

```
ERROR {org.wso2.carbon.tomcat.ext.valves.CompositeValve} -  Could not handle request: /t/carbon.super/api/identity/user/v0.9/resend-code 
java.lang.NullPointerException
	at org.wso2.carbon.identity.auth.service.handler.HandlerManager.getFirstPriorityHandler(HandlerManager.java:153)
	at org.wso2.carbon.identity.auth.service.AuthenticationManager.authenticate(AuthenticationManager.java:97)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:76)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:958)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1756)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1715)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)`RROR {org.wso2.carbon.tomcat.ext.valves.CompositeValve} 
```
Seems that the reason of such behavior is the absence of 'Authorization' header.

**Steps to reproduce:**
- Register new user
- Try to login with new user
- Click on 'Re-send' link

**Affected Product Version:**
IS 5.3.0

**Comment by isharak** [comment]
Thank you for your contribution!
We are closing this issue since it has not been prioritized for a long time. Chances are that it has already been solved in more recent versions. If not, we will be re-evaluating this when it becomes a priority.
