### ISSUE TITLE
Null Pointer Exception when there is a Service Provider Claim as a Mandatory Claim 

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#4278]
How to reproduce:
1. Create a service provider.
2. Select claim mapping dialect as "Define Custom Claim Dialect"
3. Add some "Service Provider Claim"s and mark them as mandatory.
4. Try to login to the service provider.
Following stack trace will be printed in the backend. 

`ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Exception in Authentication Framework
java.lang.NullPointerException
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.PostAuthnMissingClaimHandler.handlePostAuthenticationForMissingClaimsRequest(PostAuthnMissingClaimHandler.java:152)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.PostAuthnMissingClaimHandler.handle(PostAuthnMissingClaimHandler.java:109)
	at org.wso2.carbon.identity.application.authentication.framework.services.PostAuthenticationMgtService.executePostAuthnHandler(PostAuthenticationMgtService.java:116)
	at org.wso2.carbon.identity.application.authentication.framework.services.PostAuthenticationMgtService.handlePostAuthentication(PostAuthenticationMgtService.java:82)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handlePostAuthentication(DefaultAuthenticationRequestHandler.java:169)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:138)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:162)
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53)`

**Comment by JKAUSHALYA** [comment]
Fixed in https://github.com/wso2/carbon-identity-framework/pull/1897
