### ISSUE TITLE
Can't add SP permissions from a user with all the permissions

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/product-is#4400]
Following error has been encountered in IS 5.5.0 latest WUM updated pack.

```
WARN {org.wso2.carbon.registry.core.jdbc.Repository} -  Failed to add new resource /_system/governance/permission/applications/ddd. User user1 is not authorized to update the parent collection /_system/governance/permission/applications.
    ERROR {org.wso2.carbon.identity.application.mgt.ApplicationManagementAdminService} -  Error while updating application: app1 for tenant: carbon.super
    org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error occurred while updating the application: app1. Error while storing permissions
        at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.updateApplication(ApplicationManagementServiceImpl.java:321)
        at org.wso2.carbon.identity.application.mgt.ApplicationManagementAdminService.updateApplication(ApplicationManagementAdminService.java:137)
    ....
    Caused by: org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error while storing permissions
        at org.wso2.carbon.identity.application.mgt.ApplicationMgtUtil.updatePermissions(ApplicationMgtUtil.java:369)
        at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.updateApplication(ApplicationManagementServiceImpl.java:316)
        ... 78 more
    Caused by: org.wso2.carbon.registry.core.secure.AuthorizationFailedException: Failed to add new resource /_system/governance/permission/applications/app1. User user1 is not authorized to update the parent collection /_system/governance/permission/applications.
        at org.wso2.carbon.registry.core.jdbc.Repository.add(Repository.java:1024)
        at org.wso2.carbon.registry.core.jdbc.Repository.put(Repository.java:305)
        at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:717)
        at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:591)
        at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:828)
        at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:796)
        at org.wso2.carbon.registry.core.session.UserRegistry.access$900(UserRegistry.java:61)
        at org.wso2.carbon.registry.core.session.UserRegistry$10.run(UserRegistry.java:786)
        at org.wso2.carbon.registry.core.session.UserRegistry$10.run(UserRegistry.java:783)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:783)
        at org.wso2.carbon.identity.application.mgt.ApplicationMgtUtil.updatePermissions(ApplicationMgtUtil.java:339)
        ... 79 more

```

This error has occurred, when trying out the following scenario.
1) Create a user(user1).
2) Create a role(role1) and assign all the permissions in permission tree. And assign user1 to role1.
3) Login as user1 and create a service provider (app1).
4) Update app1, with SP permissions in Role/Permission Configuration.
5) As per the error log, user1 cannot update the registry with SP permissions, since user1 doesn't have the root permisison "/_system/governance/permission/applications".

Checked the role permissions through getRolePermissions of UserAdmin service, to validate whether the " /_system/governance/permission/applications" permission is assign to role1. Verified that the permission is assigned.

    <ax2733:nodeList xsi:type="ax2733:UIPermissionNode">
                   <ax2733:displayName>Applications</ax2733:displayName>
                   <ax2733:resourcePath>/permission/applications</ax2733:resourcePath>
                   <ax2733:selected>true</ax2733:selected>
    </ax2733:nodeList>

**Comment by emswbandara** [comment]
This issue is occurring since the role of the user you are logged into management console, not having registry write permissions assigned.

Therefore in order to assign registry write permissions, please follow the below steps.

Log into management console as super admin.
Go to Main > Registry section and click 'browse'.
In the location box type '/_system/governance/permission/applications' and click on 'Go' button. This will open up the applications registry collection view page.
Click on the '+' mark next to 'permissions' tab. This will expand the 'New Role Permissions' section.
Now select the subjective role from the drop down list and choose 'Write' as the action and click on 'Add Permission'
Now that role should be visible under 'Defined Role Permissions'. Make sure that 'write' permission is allowed for that role.



Thanks,
Sathya

**Comment by malithie** [comment]
@emswbandara , as per the explanation above this seems to have some doc impact.
Could you please create another issue to address the docs and resolve this one with proper resolution

**Comment by emswbandara** [comment]
Created a doc issue to track the documentation improvement in https://github.com/wso2/product-is/issues/4528
