### ISSUE TITLE
Migration client doesn't work on Mysql 5.5

### ISSUE THREAD

**Issue by yasassri** [wso2/product-is#4493]
Following exception was observed while performing migration on MySQL 5.5.

```
ERROR {org.wso2.carbon.is.migration.service.SchemaMigrator} -  Error occurred while executing SQL script for migrating database

java.lang.Exception: Error occurred while executing :   CREATE TABLE IDN_SAML2_ARTIFACT_STORE ( ID INT(11) NOT NULL AUTO_INCREMENT, SOURCE_ID VARCHAR(255) NOT NULL, MESSAGE_HANDLER VARCHAR(255) NOT NULL, AUTHN_REQ_DTO BLOB NOT NULL, SESSION_ID VARCHAR(255) NOT NULL, EXP_TIMESTAMP TIMESTAMP NOT NULL, INIT_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ASSERTION_ID VARCHAR(255), PRIMARY KEY (`ID`) )ENGINE INNODB

	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:231)

	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:162)

	at org.wso2.carbon.is.migration.service.SchemaMigrator.migrate(SchemaMigrator.java:75)

	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:41)

	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:83)

	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:147)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)

	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)

	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)

	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)

	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)

	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)

	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)

	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)

	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)

	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)

	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)

	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)

	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)

	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:515)

	at org.wso2.carbon.core.init.CarbonServerManager.start(CarbonServerManager.java:220)

	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.activate(CarbonCoreServiceComponent.java:105)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)

	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)

	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)

	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)

	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)

	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)

	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)

	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)

	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)

	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)

	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)

	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)

	at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)

	at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)

	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)

	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)

	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1230)

	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1174)

	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1066)

	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5370)

	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5668)

	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)

	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1700)

	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1690)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

Caused by: java.sql.SQLException: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)

	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)

	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)

	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)

	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)

	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)

	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)

	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)

	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)

	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)

	at com.sun.proxy.$Proxy26.execute(Unknown Source)

	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:201)

	... 65 more

[2019-02-26 11:58:10,900] ERROR {org.wso2.carbon.is.migration.service.SchemaMigrator} -  Error occurred while executing SQL script for migrating database

java.lang.Exception: Error occurred while executing SQL script for migrating database

	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:172)

	at org.wso2.carbon.is.migration.service.SchemaMigrator.migrate(SchemaMigrator.java:75)

	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:41)

	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:83)

	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:147)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)

	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)

	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)

	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)

	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)

	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)

	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)

	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)

	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)

	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)

	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)

	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)

	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)

	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:515)

	at org.wso2.carbon.core.init.CarbonServerManager.start(CarbonServerManager.java:220)

	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.activate(CarbonCoreServiceComponent.java:105)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)

	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)

	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)

	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)

	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)

	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)

	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)

	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)

	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)

	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)

	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)

	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)

	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)

	at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)

	at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)

	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)

	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)

	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1230)

	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1174)

	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1066)

	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5370)

	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5668)

	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)

	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1700)

	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1690)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.Exception: Error occurred while executing :   CREATE TABLE IDN_SAML2_ARTIFACT_STORE ( ID INT(11) NOT NULL AUTO_INCREMENT, SOURCE_ID VARCHAR(255) NOT NULL, MESSAGE_HANDLER VARCHAR(255) NOT NULL, AUTHN_REQ_DTO BLOB NOT NULL, SESSION_ID VARCHAR(255) NOT NULL, EXP_TIMESTAMP TIMESTAMP NOT NULL, INIT_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, ASSERTION_ID VARCHAR(255), PRIMARY KEY (`ID`) )ENGINE INNODB

	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:231)

	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:162)

	... 64 more

Caused by: java.sql.SQLException: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)

	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)

	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)

	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)

	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)

	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)

	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)

	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)

	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)

	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)

	at com.sun.proxy.$Proxy26.execute(Unknown Source)

	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:201)

	... 65 more
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
