### ISSUE TITLE
Getting exceptions when trying to add a sample code of custom random password generator for the Ask password 

### ISSUE THREAD

**Issue by DilsiChandrasena** [wso2/product-is#4509]
Followed the steps mentioned in Git Issue [1] using Identity Server 5.6.0 and received below exception.

```
ERROR {org.wso2.carbon.user.mgt.ui.Util} -  Error while loading random password generator class. Default random password generator would be used 
java.lang.ClassNotFoundException: com.wso2.password.policy.CustomPasswordGenerator cannot be found by org.wso2.carbon.user.mgt.ui_5.11.256
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.wso2.carbon.user.mgt.ui.Util.getAskPasswordTempPassGenerator(Util.java:340)
	at org.wso2.carbon.user.mgt.ui.Util.generateRandomPassword(Util.java:283)
	at org.apache.jsp.user.add_002dfinish_002dajaxprocessor_jsp._jspService(add_002dfinish_002dajaxprocessor_jsp.java:161)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)

```
[1]. https://github.com/wso2/product-is/issues/2501

**Comment by mefarazath** [comment]
Since this extension point is considered to be redundant one, recommended approach is to use a custom event listener to achieve the same functionality

Sample: https://github.com/kasun-bandara/CustomUserOperationEventListener
