### ISSUE TITLE
Have detailed exception message while missing required configurations in federated email OTP authenticator

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#4517]
Product IS 5.7.0

When we configure federated Email OTP authenticator using Gmail or Sendgrid as the email providers, we required to configure the fields Email API and Email as mentioned in the document [1]. 

![image](https://user-images.githubusercontent.com/11737221/53619273-c2662f80-3c14-11e9-853b-7961ef88dee4.png)

When these fields are not configured, the email OTP authenticator will be consider the email provider as SMTP [2] and look for the axis2 SMTP related configuration. If the configurations are missing then throws the below exception.

```
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} -  Email OTP authentication failed for the local user new
org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: Email OTP authentication failed for the local user new
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.handleEmailOTPForLocalUser(EmailOTPAuthenticator.java:1078)
....

Caused by: org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: Authentication Failed: Authenticator Properties may be null 
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.processEmailOTPFlow(EmailOTPAuthenticator.java:741)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.handleEmailOTPForLocalUser(EmailOTPAuthenticator.java:1069)
	... 60 more
Caused by: org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: Error while getting the SMTP configuration
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.sendOTP(EmailOTPAuthenticator.java:1725)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.checkEmailOTPBehaviour(EmailOTPAuthenticator.java:332)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.processEmailOTPFlow(EmailOTPAuthenticator.java:728)
	... 61 more
```

The exception message "Authentication Failed: Authenticator Properties may be null" is not enough for the users to understand that missing the EmailAPI and Email configuration is the reason this exception. 

So it would be better to have more specific exception message to indicated that the EmailAPI and Email fields need to be configured when Gmail or Sendgrid used as the email provider. 

[1] https://docs.wso2.com/display/IS570/Configuring+Email+OTP#ConfiguringEmailOTP-ConfiguringtheidentityproviderConfiguretheIdentityProvider
[2]https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L1747

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
