### ISSUE TITLE
Rampart Certificates are Invalidated.

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#4635]
We need to change the certificates in rampart module to have longer validity periods. Invalidated certificates cause build failures with the following exception.
```
org.apache.ws.security.WSSecurityException: The signature or decryption was invalid (The provided certificate is invalid); nested exception is: 
        java.security.cert.CertificateExpiredException: NotAfter: Tue Mar 20 05:29:59 IST 2018
        at org.apache.ws.security.processor.SignatureProcessor.verifyXMLSignature(SignatureProcessor.java:509)
        at org.apache.ws.security.processor.SignatureProcessor.handleToken(SignatureProcessor.java:124)
        at org.apache.ws.security.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:332)
        at org.apache.ws.security.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:249)
        at org.apache.rampart.RampartEngine.process(RampartEngine.java:217)
        at org.apache.rampart.RampartEngineTest.testValidSOAP12Message(RampartEngineTest.java:118)
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Tue Mar 20 05:29:59 IST 2018
        at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:274)
        at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:629)
        at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:602)
        at org.apache.ws.security.processor.SignatureProcessor.verifyXMLSignature(SignatureProcessor.java:506)
        ... 27 more
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
