### ISSUE TITLE
Logout failure when single logout is enabled for federated IdP

### ISSUE THREAD

**Issue by sachiniWettasinghe** [wso2/product-is#4637]
Following error is thrown when logging out from a service provider configured with a SAML federated IdP. 

```
[2019-03-14 17:11:32,805] ERROR {org.apache.catalina.core.StandardWrapperValve} -  Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception
java.lang.NullPointerException
	at org.wso2.carbon.identity.sso.saml.util.SAMLSSOUtil.decode(SAMLSSOUtil.java:385)
	at org.wso2.carbon.identity.sso.saml.util.SAMLSSOUtil.decodeSamlLogoutRequest(SAMLSSOUtil.java:1985)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.extractSessionIndex(SAMLSSOProviderServlet.java:1401)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleLogoutResponseFromFramework(SAMLSSOProviderServlet.java:1163)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleRequest(SAMLSSOProviderServlet.java:231)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.doGet(SAMLSSOProviderServlet.java:129)
```

**Comment by emswbandara** [comment]
Fixed with 
[1] https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/215
[2] https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/216
