### ISSUE TITLE
Once the CaseInsensitiveUsername property enable, existing users are get effected. 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#4655]
**Suggested labels:**
Affected: 5.8-m27
Severity: Major
Priority: Medium
Component:User Mgt
Type: Bug/QATesting

**Use case:** 
System have existing users who have same user IDs but  different in cases (ex: user/USER) which create when the CaseInsensitiveUsername property at the user-mgt.xml was false status.
But once the configuration change in to true and after trying to do some action with those mentioned users system gives error. (Ex: add user role for those users who have same userIds but different from cases.) 

**Steps to reproduce:**
1. Set CaseInsensitiveUsername property  to fail and start the server
2. Add usersfrom user IDs , TestUser and testuser
3. Set CaseInsensitiveUsername property  to true and restart the server
4. Add role to user, TestUser

**UI error message:** 
`Could not update role list of user TEST. Error: Using sql : INSERT INTO UM_USER_ROLE (UM_ROLE_ID, UM_USER_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_USER WHERE LOWER(UM_USER_NAME)=LOWER(?) AND UM_TENANT_ID=?), ?) Scalar subquery contains more than one row; SQL statement: INSERT INTO UM_USER_ROLE (UM_ROLE_ID, UM_USER_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_USER WHERE LOWER(UM_USER_NAME)=LOWER(?) AND UM_TENANT_ID=?), ?) -- ((SELECT UM_ID FROM PUBLIC.UM_ROLE /* PUBLIC.CONSTRAINT_INDEX_19: UM_ROLE_NAME = ?1 AND UM_TENANT_ID = ?2 */ /* scanCount: 2 */ WHERE (UM_ROLE_NAME = ?1) AND (UM_TENANT_ID = ?2)), (SELECT UM_ID FROM PUBLIC.UM_USER /* PUBLIC.UM_USER.tableScan */ /* scanCount: 3 */ WHERE (UM_TENANT_ID = ?4) AND (LOWER(UM_USER_NAME) = LOWER(?3))), ?5) [90053-175]`

**Carbon console Error:**
```
  Initializing of policy store is finished at :  Mon Mar 18 18:03:38 IST 2019
[2019-03-18 18:03:51,986] ERROR {org.wso2.carbon.user.mgt.ui.UserAdminClient} -  Using sql : INSERT INTO UM_USER_ROLE (UM_ROLE_ID, UM_USER_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_USER WHERE LOWER(UM_USER_NAME)=LOWER(?) AND UM_TENANT_ID=?), ?) Scalar subquery contains more than one row; SQL statement:
INSERT INTO UM_USER_ROLE (UM_ROLE_ID, UM_USER_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_USER WHERE LOWER(UM_USER_NAME)=LOWER(?) AND UM_TENANT_ID=?), ?) -- ((SELECT
    UM_ID
FROM PUBLIC.UM_ROLE
    /* PUBLIC.CONSTRAINT_INDEX_19: UM_ROLE_NAME = ?1
        AND UM_TENANT_ID = ?2
     */
    /* scanCount: 2 */
WHERE (UM_ROLE_NAME = ?1)
    AND (UM_TENANT_ID = ?2)), (SELECT
    UM_ID
FROM PUBLIC.UM_USER
    /* PUBLIC.UM_USER.tableScan */
    /* scanCount: 3 */
WHERE (UM_TENANT_ID = ?4)
    AND (LOWER(UM_USER_NAME) = LOWER(?3))), ?5) [90053-175]
org.wso2.carbon.user.mgt.stub.UserAdminUserAdminException: UserAdminUserAdminException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.wso2.carbon.user.mgt.stub.UserAdminStub.addRemoveRolesOfUser(UserAdminStub.java:3960)
        at org.wso2.carbon.user.mgt.ui.UserAdminClient.addRemoveRolesOfUser(UserAdminClient.java:254)
        at org.apache.jsp.user.edit_002duser_002droles_002dfinish_002dajaxprocessor_jsp._jspService(edit_002duser_002droles_002dfinish_002dajaxprocessor_jsp.java:229)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:472)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
        at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:71)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:91)
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:65)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
        at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1780)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1739)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by DMHP** [comment]
@aaujayasena 
It is not recommended to change the value of CaseInsensitiveUsername property in the middle.
If we validate the steps you have mentioned above,

1. Set CaseInsensitiveUsername property to fail and start the server
2. Add usersfrom user IDs , TestUser and testuser
3. Set CaseInsensitiveUsername property to true and restart the server
The step 3 is not recommended as we can not make this property to true at this point as the system contains two users with the same name (with different caps)

I am closing the issue. Please re-open the issue of you have any other concerns.

**Comment by aaujayasena** [comment]
Opening a doc issue to add needful detail in parameter changes. [1]
Re opening the issue since customer not receive a meaning full error message.  

Error message:
`Could not update role list of user TEST. Error: Using sql : INSERT INTO UM_USER_ROLE (UM_ROLE_ID, UM_USER_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_USER WHERE LOWER(UM_USER_NAME)=LOWER(?) AND UM_TENANT_ID=?), ?) Scalar subquery contains more than one row; SQL statement: INSERT INTO UM_USER_ROLE (UM_ROLE_ID, UM_USER_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_USER WHERE LOWER(UM_USER_NAME)=LOWER(?) AND UM_TENANT_ID=?), ?) -- ((SELECT UM_ID FROM PUBLIC.UM_ROLE /* PUBLIC.CONSTRAINT_INDEX_19: UM_ROLE_NAME = ?1 AND UM_TENANT_ID = ?2 */ /* scanCount: 2 */ WHERE (UM_ROLE_NAME = ?1) AND (UM_TENANT_ID = ?2)), (SELECT UM_ID FROM PUBLIC.UM_USER /* PUBLIC.UM_USER.tableScan */ /* scanCount: 3 */ WHERE (UM_TENANT_ID = ?4) AND (LOWER(UM_USER_NAME) = LOWER(?3))), ?5) [90053-175]`

[1]https://github.com/wso2/product-is/issues/4686
