### ISSUE TITLE
Apache Directory Studio doesn't show users in WSO2 IS 

### ISSUE THREAD

**Issue by IshikaGodage** [wso2/product-is#4807]
**Steps to reproduce:**

1. Login to WSO2 Management Console.
2. Create users in PRIMARY LDAP user store.
3. Create connection in Apache Directory Studio with LDAP user store.
4. View users in Apache Directory Studio -> only shows the admin.

It throws this exception in Apache Directory Studio side. [1]

**Users in WSO2 IS:**
<img width="1205" alt="Screen Shot 2019-03-25 at 3 55 12 PM" src="https://user-images.githubusercontent.com/18381642/54912360-7c9c3e80-4f16-11e9-8e71-c97fa6266500.png">

**Users in Apache Directory Studio:**
<img width="844" alt="Screen Shot 2019-03-25 at 3 57 46 PM" src="https://user-images.githubusercontent.com/18381642/54912512-c5ec8e00-4f16-11e9-8363-7bcf79fa083e.png">

[1] Exception stack trace in Apache Directory Studio side

> javax.naming.NamingException
	at org.apache.directory.studio.connection.core.io.api.CursorStudioNamingEnumeration.next(CursorStudioNamingEnumeration.java:317)
	at org.apache.directory.studio.connection.core.io.api.CursorStudioNamingEnumeration.next(CursorStudioNamingEnumeration.java:1)
	at org.apache.directory.studio.ldapbrowser.core.jobs.SearchRunnable.searchAndUpdateModel(SearchRunnable.java:323)
	at org.apache.directory.studio.ldapbrowser.core.jobs.InitializeChildrenRunnable.executeSearch(InitializeChildrenRunnable.java:359)
	at org.apache.directory.studio.ldapbrowser.core.jobs.InitializeChildrenRunnable.initializeChildren(InitializeChildrenRunnable.java:210)
	at org.apache.directory.studio.ldapbrowser.core.jobs.InitializeChildrenRunnable.run(InitializeChildrenRunnable.java:169)
	at org.apache.directory.studio.connection.core.jobs.StudioConnectionJob.run(StudioConnectionJob.java:109)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

**Comment by madurangasiriwardena** [comment]
Similar question raised in https://stackoverflow.com/questions/52734861/apache-directory-studio-doesnt-show-new-created-in-wso2-is-users

**Comment by sarubi** [comment]
I also came across a similar issue regarding the resource type claim mapping. 
Steps to reproduce it,

1. Configure external LDAP with WSO2 IS server. 
2. Try to list the users via the management console, no users were listed even though users are in LDAP.
3. Try to create a new user, it was failed with a generic error says " Error: Cannot access the directory context or user already exists in the system for user..... "

As a fix I map the "Mapped Local Claim” to http://wso2.org/claims/userType for the “urn:ietf:params:scim:schemas:core:2.0:meta.resourceType” and able over the issue.
