### ISSUE TITLE
Integration tests are failing when DB type changed to a mysql NDB cluster

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#4843]
Following XACML related test cases are failing..

```
testValidateTokenWithInValidScope(org.wso2.identity.integration.test.oauth2.OAuth2XACMLScopeValidatorTestCase)  Time elapsed: 0.236 sec  <<< FAILURE!
java.lang.AssertionError: Introspection is true. expected:<false> but was:<true>
        at org.testng.Assert.fail(Assert.java:89)
        at org.testng.Assert.failNotEquals(Assert.java:489)
        at org.testng.Assert.assertFalse(Assert.java:58)
        at org.wso2.identity.integration.test.oauth2.OAuth2XACMLScopeValidatorTestCase.testValidateTokenWithInValidScope(OAuth2XACMLScopeValidatorTestCase.java:158)

testGetDecision(org.wso2.identity.integration.test.entitlement.EntitlementRestServiceTestCase)  Time elapsed: 5.065 sec  <<< FAILURE!
java.lang.AssertionError: Response for PDP decision request does not return 'Permit' expected:<Permit> but was:<NotApplicable>
        at org.testng.Assert.fail(Assert.java:89)
        at org.testng.Assert.failNotEquals(Assert.java:489)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:171)
        at org.wso2.identity.integration.test.entitlement.EntitlementRestServiceTestCase.testGetDecision(EntitlementRestServiceTestCase.java:219)

addSPMetadata(org.wso2.identity.integration.test.saml.SPMetadataTestCase)  Time elapsed: 0.32 sec  <<< FAILURE!
java.lang.AssertionError: Lists differ at element [0]: https://metadata-sp:8080/federation/Consumer1/metaAlias/sp != https://metadata-sp:8080/federation/Consumer2/metaAlias/sp expected:<https://metadata-sp:8080/federation/Consumer1/metaAlias/sp> but was:<https://metadata-sp:8080/federation/Consumer2/metaAlias/sp>
        at org.testng.Assert.fail(Assert.java:89)
        at org.testng.Assert.failNotEquals(Assert.java:489)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:544)
        at org.testng.Assert.assertEquals(Assert.java:567)
        at org.testng.Assert.assertEquals(Assert.java:626)
        at org.wso2.identity.integration.test.saml.SPMetadataTestCase.addSPMetadata(SPMetadataTestCase.java:86)

testUnauthorizedSAMLSSOLogin(org.wso2.identity.integration.test.application.authz.ApplicationAuthzTestCase)  Time elapsed: 0.236 sec  <<< FAILURE!
java.lang.AssertionError: SAML SSO Login should be unsuccessful and page should have a message "Authorization failed for" nonAzTestUser expected:<true> but was:<false>
        at org.testng.Assert.fail(Assert.java:89)
        at org.testng.Assert.failNotEquals(Assert.java:489)
        at org.testng.Assert.assertTrue(Assert.java:37)
        at org.wso2.identity.integration.test.application.authz.ApplicationAuthzTestCase.testUnauthorizedSAMLSSOLogin(ApplicationAuthzTestCase.java:212)

testUnauthorizedTenantSAMLSSOLogin(org.wso2.identity.integration.test.application.authz.ApplicationAuthzTenantTestCase)  Time elapsed: 0.228 sec  <<< FAILURE!
java.lang.AssertionError: SAML SSO Login should be unsuccessful and page should have a message "Authorization failed for nonAzTestTenantUser" expected:<true> but was:<false>
        at org.testng.Assert.fail(Assert.java:89)
        at org.testng.Assert.failNotEquals(Assert.java:489)
        at org.testng.Assert.assertTrue(Assert.java:37)
        at org.wso2.identity.integration.test.application.authz.ApplicationAuthzTenantTestCase.testUnauthorizedTenantSAMLSSOLogin(ApplicationAuthzTenantTestCase.java:192)
```
Due to the following exception when publishing policies..

```
ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Exception in thread "pool-25-thread-2" java.lang.NumberFormatException: For input string: "false"
ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   at java.lang.Integer.parseInt(Integer.java:580)
ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   at java.lang.Integer.parseInt(Integer.java:615)
ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   at org.wso2.carbon.identity.entitlement.dto.PublisherDataHolder.<init>(PublisherDataHolder.java:67)
ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   at org.wso2.carbon.identity.entitlement.policy.publisher.PolicyPublisher.retrieveSubscriber(PolicyPublisher.java:241)
ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   at org.wso2.carbon.identity.entitlement.policy.publisher.PolicyPublishExecutor.publish(PolicyPublishExecutor.java:124)
ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   at org.wso2.carbon.identity.entitlement.policy.publisher.PolicyPublishExecutor.run(PolicyPublishExecutor.java:87)
ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ERROR [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   at java.lang.Thread.run(Thread.java:748)
```

And following test case is failing as well,

```
testAddClaimConfiguration(org.wso2.identity.integration.test.sts.TestPassiveSTS)  Time elapsed: 0.126 sec  <<< FAILURE!
java.lang.AssertionError: Failed update given name claim uri expected:<http://wso2.org/claims/givenname> but was:<http://wso2.org/claims/emailaddress>
        at org.testng.Assert.fail(Assert.java:89)
        at org.testng.Assert.failNotEquals(Assert.java:489)
        at org.testng.Assert.assertEquals(Assert.java:118)
        at org.testng.Assert.assertEquals(Assert.java:171)
        at org.wso2.identity.integration.test.sts.TestPassiveSTS.testAddClaimConfiguration(TestPassiveSTS.java:141)
```

**Comment by ashensw** [comment]
These XACML tests are failing since the MySQL NDB cluster does not guarantee the select query results order. As it changes the functionality is failing since it is expecting to preserve the same order. So we have added the **order by** to relevant SQL queries to fix the issue.

**Comment by ashensw** [comment]
Need to update the kernel version in the product-is which includes the fix in order to close this issue.
