### ISSUE TITLE
Error while creating an IdP with a role mapping with invalid local role

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#4878]
Create an IdP with a non-existing role in the role mapping.

IdP is not created - with no meaningful error.  

Need to handle this gracefully.

Caused by: java.lang.NullPointerException
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserStoreInternal(AbstractUserStoreManager.java:4838)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.access$400(AbstractUserStoreManager.java:86)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$7.run(AbstractUserStoreManager.java:4823)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$7.run(AbstractUserStoreManager.java:4820)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserStore(AbstractUserStoreManager.java:4820)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.isExistingRole(AbstractUserStoreManager.java:3700)
	... 88 more

**Comment by prabath** [comment]
Looks we get the same error even for an existing role, when trying to create the IdP and role mapping in the first step.
