### ISSUE TITLE
NoClassDefFoundError while starting the WSO2 IS as a Windows service

### ISSUE THREAD

**Issue by vihanga-liyanage** [wso2/product-is#4963]
### Steps to Reproduce

1. Take an IS 5.3.0 latest WUM in windows 10.
2. Follow this doc (https://docs.wso2.com/display/IS530/Installing+as+a+Windows+Service)
3. Observe the error when executing runConsole.bat

```
TID: [-1234] [] [2019-04-04 10:21:34,267] ERROR {org.wso2.carbon.email.mgt.internal.I18nMgtServiceComponent} - Error while activating I18n Management bundle 
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
at org.wso2.carbon.email.mgt.util.I18nEmailUtil.getEmailContent(I18nEmailUtil.java:151)
at org.wso2.carbon.email.mgt.util.I18nEmailUtil.getDefaultEmailTemplates(I18nEmailUtil.java:106)
at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.addDefaultEmailTemplates(EmailTemplateManagerImpl.java:276)
at org.wso2.carbon.email.mgt.internal.I18nMgtServiceComponent.loadDefaultEmailTemplates(I18nMgtServiceComponent.java:96)
at org.wso2.carbon.email.mgt.internal.I18nMgtServiceComponent.activate(I18nMgtServiceComponent.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by ayshsandu** [comment]
Fixed with https://github.com/wso2-support/identity-event-handler-notification/pull/13
