### ISSUE TITLE
SSL Handshake Exception when trying to call WSO2 Web Services

### ISSUE THREAD

**Issue by AnujaK** [wso2/product-is#505]
I'm using WSO2 Identity Server 5.1 for SSO. I'm trying to call WSO2 web services from my Spring boot application that uses spring-security-saml2 (built using Oracle JDK 1.7).

I hit my application URL, it takes me to WSO2 authentication. I see in browser the following:

![rsz_screenshot_from_2016-06-07_090925](https://cloud.githubusercontent.com/assets/1309080/15848261/8b878edc-2ca9-11e6-88ca-c2469f176ec6.png)

WSO2 authenticates me but throws Axis2 error for any web service call. Here is stack trace:
_org.apache.axis2.AxisFault: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
    at org.apache.axis2.AxisFault.makeFault(AxisFault.java:430) ~[axis2-kernel-1.7.2.jar:1.7.2]
    at org.apache.axis2.transport.http.SOAPMessageFormatter.writeTo(SOAPMessageFormatter.java:78) ~[axis2-kernel-1.7.2.jar:na]
    at org.apache.axis2.transport.http.AxisRequestEntity.writeRequest(AxisRequestEntity.java:84) ~[axis2-1.6.1.wso2v12.jar:na]
    at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:499) ~[commons-httpclient-3.1.jar:na]
    at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114) ~[commons-httpclient-3.1.jar:na]
    at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096) ~[commons-httpclient-3.1.jar:na]
    at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398) ~[commons-httpclient-3.1.jar:na]
    at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) ~[commons-httpclient-3.1.jar:na]
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[commons-httpclient-3.1.jar:na]
    at org.apache.axis2.transport.http.AbstractHTTPSender.executeMethod(AbstractHTTPSender.java:630) ~[axis2-1.6.1.wso2v12.jar:na]
    at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:195) [axis2-1.6.1.wso2v12.jar:na]
    at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:77) [axis2-1.6.1.wso2v12.jar:na]
    at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:451) [axis2-1.6.1.wso2v12.jar:na]
    at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:278) [axis2-1.6.1.wso2v12.jar:na]
    at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:431) [axis2-kernel-1.7.2.jar:1.7.2]
    at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:399) [axis2-kernel-1.7.2.jar:1.7.2]
    at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225) [axis2-kernel-1.7.2.jar:1.7.2]
    at org.apache.axis2.client.OperationClient.execute(OperationClient.java:150) [axis2-kernel-1.7.2.jar:1.7.2]
    at org.wso2.carbon.service.mgt.stub.ServiceAdminStub.getNumberOfActiveServices(ServiceAdminStub.java:4810) [org.wso2.carbon.service.mgt.stub-4.0.0.jar:na]__

I had created certificate using OpenSSL as well as using trial certificate from Comodo and face the same issue. I'd referred https://docs.wso2.com/display/IS510/Creating+New+Keystores for certificate creation and installation.

Any help is highly appreciated.

**Comment by pratikq23** [comment]
we are also facing same issue.Did you get solution for it??

**Comment by AnujaK** [comment]
@omindu Any clue on this issue? We are stuck up. 

I'm getting logged in user attributes in application.

**Comment by darshanasbg** [comment]
Error you see in the browser and error log shown in the console cause due to two different issues.

Since you are using a new self signed keystore in the identity server, browser doesn't trust the cert issues by the IS hence you see the warning in the browser. It's ok to have that warning in the test environments.

But you shouldn't get an error in the console. It seems there some other back channel call triggered (maybe you invoke web services in IS) and it's failing while initiating the SSL handshake.

Need to know what exactly IS receiving as the request\ what endpoint it's getting invoked when failing this backchannel request. Can you please share that information? You can refer `<IS_HOME>/repository/logs/http_access_<date>.log` to get information on requests received to IS. Please mention any logs that get added when you try your scenario.

And if you enable SSL debug logs on in the IS, it will show you more information on the handshake failure. Todo that, you can start wso2 server with `-Djavax.net.debug=all:handshake:verbose` parameter.

Ex : >> `sh wso2server.sh -Djavax.net.debug=all:handshake:verbose`

**Comment by AnujaK** [comment]
Hi @darshanasbg , here is what I get on console after starting WSO2 IS in debug mode 
_http-nio-9443-exec-8, READ: TLSv1 Alert, length = 2
http-nio-9443-exec-8, RECV TLSv1 ALERT:  fatal, certificate_unknown
http-nio-9443-exec-8, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
http-nio-9443-exec-8, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
http-nio-9443-exec-8, called closeOutbound()
http-nio-9443-exec-8, closeOutboundInternal()_


And in the file mentioned (**http_access_2016-06-17.log**) 
_127.0.0.1 - - [17/Jun/2016:15:23:37 +0530] "POST /samlsso HTTP/1.1" 302 - "http://localhost:8080/s" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
127.0.0.1 - - [17/Jun/2016:15:23:38 +0530] "GET /authenticationendpoint/login.do;jsessionid=085306AC3AF017ADC970BBF3842CFB8B?commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&tenantDomain=carbon.super&sessionDataKey=86e3b1ec-fcfc-4bcf-a850-2844e0683435&relyingParty=com%3A%3Asample&type=samlsso&sp=Angular&isSaaSApp=false&authenticators=BasicAuthenticator:LOCAL HTTP/1.1" 200 1667 "http://localhost:8080/s" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
127.0.0.1 - - [17/Jun/2016:15:23:38 +0530] "GET /authenticationendpoint/css/Roboto.css HTTP/1.1" 200 301 "https://localhost:9443/authenticationendpoint/login.do;jsessionid=085306AC3AF017ADC970BBF3842CFB8B?commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&tenantDomain=carbon.super&sessionDataKey=86e3b1ec-fcfc-4bcf-a850-2844e0683435&relyingParty=com%3A%3Asample&type=samlsso&sp=Angular&isSaaSApp=false&authenticators=BasicAuthenticator:LOCAL" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
127.0.0.1 - - [17/Jun/2016:15:23:38 +0530] "GET /authenticationendpoint/libs/bootstrap_3.3.5/css/bootstrap.min.css HTTP/1.1" 200 20162 "https://localhost:9443/authenticationendpoint/login.do;jsessionid=085306AC3AF017ADC970BBF3842CFB8B?commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&tenantDomain=carbon.super&sessionDataKey=86e3b1ec-fcfc-4bcf-a850-2844e0683435&relyingParty=com%3A%3Asample&type=samlsso&sp=Angular&isSaaSApp=false&authenticators=BasicAuthenticator:LOCAL" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"
127.0.0.1 - - [17/Jun/2016:15:23:40 +0530] "GET /authenticationendpoint/js/index.js HTTP/1.1" 200 740 "https://localhost:9443/authenticationendpoint/login.do;jsessionid=085306AC3AF017ADC970BBF3842CFB8B?commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&tenantDomain=carbon.super&sessionDataKey=86e3b1ec-fcfc-4bcf-a850-2844e0683435&relyingParty=com%3A%3Asample&type=samlsso&sp=Angular&isSaaSApp=false&authenticators=BasicAuthenticator:LOCAL" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"_

Looking forward to hear.
