### ISSUE TITLE
Authorization Code revocation fails in DB2

### ISSUE THREAD

**Issue by IsurangaPerera** [wso2/product-is#5228]
When deleting a user to whom access token and an auth code are issued, the token is successfully revoked. But authorization code is not revoked with the following exception.

> [2019-05-09 09:44:12,160] ERROR {org.wso2.carbon.identity.oauth.listener.IdentityOathEventListener} -  Error occurred while revoking Access Token : f5cf9934-f288-3612-b54a-95fb41873a21
> org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: Error occurred while revoking Access Token : [f5cf9934-f288-3612-b54a-95fb41873a21]
> 	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.revokeAccessTokensInBatch(AccessTokenDAOImpl.java:1017)
> 	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.revokeAccessTokens(AccessTokenDAOImpl.java:943)
> 	at org.wso2.carbon.identity.oauth.listener.IdentityOathEventListener.revokeTokens(IdentityOathEventListener.java:292)
> 	at org.wso2.carbon.identity.oauth.listener.IdentityOathEventListener.doPreDeleteUser(IdentityOathEventListener.java:88)
> 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.deleteUser(AbstractUserStoreManager.java:2204)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:168)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:165)
> 	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.deleteUser(AbstractUserStoreManager.java:2141)
> 	at org.wso2.carbon.user.mgt.UserRealmProxy.deleteUser(UserRealmProxy.java:866)
> 	at org.wso2.carbon.user.mgt.UserAdmin.deleteUser(UserAdmin.java:244)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212)
> 	at org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic(RPCMessageReceiver.java:117)
> 	at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40)
> 	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
> 	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
> 	at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:170)
> 	at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:82)
> 	at org.wso2.carbon.core.transports.local.CarbonLocalTransportSender.finalizeSendWithToAddress(CarbonLocalTransportSender.java:45)
> 	at org.apache.axis2.transport.local.LocalTransportSender.invoke(LocalTransportSender.java:77)
> 	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
> 	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:442)
> 	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228)
> 	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
> 	at org.wso2.carbon.user.mgt.stub.UserAdminStub.deleteUser(UserAdminStub.java:5661)
> 	at org.wso2.carbon.user.mgt.ui.UserAdminClient.deleteUser(UserAdminClient.java:128)
> 	at org.apache.jsp.user.delete_002dfinish_002dajaxprocessor_jsp._jspService(delete_002dfinish_002dajaxprocessor_jsp.java:120)
> 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
> 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:472)
> 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
> 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
> 	at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)
> 	at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
> 	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
> 	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
> 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
> 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
> 	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
> 	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
> 	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:91)
> 	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:65)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
> 	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
> 	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
> 	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
> 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
> 	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
> 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
> 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1780)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1739)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-206, SQLSTATE=42703, SQLERRMC=REFRESH_TOKEN_TIME_CREATED, DRIVER=3.71.22
> 	at com.ibm.db2.jcc.am.gd.a(gd.java:813)
> 	at com.ibm.db2.jcc.am.gd.a(gd.java:66)
> 	at com.ibm.db2.jcc.am.gd.a(gd.java:140)
> 	at com.ibm.db2.jcc.am.gp.c(gp.java:2788)
> 	at com.ibm.db2.jcc.am.gp.d(gp.java:2776)
> 	at com.ibm.db2.jcc.am.gp.a(gp.java:2220)
> 	at com.ibm.db2.jcc.am.hp.a(hp.java:7546)
> 	at com.ibm.db2.jcc.t4.bb.i(bb.java:148)
> 	at com.ibm.db2.jcc.t4.bb.b(bb.java:41)
> 	at com.ibm.db2.jcc.t4.p.a(p.java:32)
> 	at com.ibm.db2.jcc.t4.vb.i(vb.java:145)
> 	at com.ibm.db2.jcc.am.gp.ib(gp.java:2189)
> 	at com.ibm.db2.jcc.am.hp.vc(hp.java:3586)
> 	at com.ibm.db2.jcc.am.hp.a(hp.java:4464)
> 	at com.ibm.db2.jcc.am.hp.b(hp.java:4062)
> 	at com.ibm.db2.jcc.am.hp.lc(hp.java:2779)
> 	at com.ibm.db2.jcc.am.hp.execute(hp.java:2759)
> 	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
> 	at com.sun.proxy.$Proxy24.execute(Unknown Source)
> 	at org.wso2.carbon.identity.oauth2.dao.OldTokensCleanDAO.saveTokenInAuditTable(OldTokensCleanDAO.java:137)
> 	at org.wso2.carbon.identity.oauth2.dao.OldTokensCleanDAO.cleanupTokenByTokenValue(OldTokensCleanDAO.java:99)
> 	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.revokeAccessTokensInBatch(AccessTokenDAOImpl.java:1010)
> 	... 92 more

**Comment by IsurangaPerera** [comment]
Cannot reproduce
