### ISSUE TITLE
SAML2 Bearer Assertion fails for tenant SP

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#5255]
**Steps to reproduce:**
1. Configure SAML2 Bearer Assertion following the doc [1]
2. Configure 'Identity Provider Entity ID' at OpenID Connect resident IdP with the tenant domain `https://localhost:9443/oauth2/token?tenantDomain=wso2.com`
3. Request OAuth2 access token 

**Error:**
UI:
```Server returned HTTP response code: 400 for URL: https://localhost:9443/oauth2/token```

Tomcat:
```
org.wso2.carbon.identity.sso.agent.SSOAgentException: Error occurred while executing SAML2 grant request to OAuth2 Token URL
	at org.wso2.carbon.identity.sso.agent.oauth2.SAML2GrantManager.executePost(SAML2GrantManager.java:126)
	at org.wso2.carbon.identity.sso.agent.oauth2.SAML2GrantManager.getAccessToken(SAML2GrantManager.java:68)
	at org.wso2.carbon.identity.sso.agent.SSOAgentFilter.doFilter(SSOAgentFilter.java:157)
	at org.wso2.sample.is.sso.agent.SSOAgentSampleFilter.doFilter(SSOAgentSampleFilter.java:107)
```

Identity Server:
```
DEBUG {org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer} -  Error occurred while validating grant
org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: SAML Assertion Audience Restriction validation failed
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.saml.SAML2BearerGrantHandler.validateAudience(SAML2BearerGrantHandler.java:726)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.saml.SAML2BearerGrantHandler.validateConditions(SAML2BearerGrantHandler.java:670)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.saml.SAML2BearerGrantHandler.validateGrant(SAML2BearerGrantHandler.java:157)
	at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.issue(AccessTokenIssuer.java:227)
	at org.wso2.carbon.identity.oauth2.OAuth2Service.issueAccessToken(OAuth2Service.java:247)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:305)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:91)
```
**Reason:**

During SAML assertion validation, 'Token Endpoint URL' from the OIDC resident IdP has been picked as the tokenEndpointAlias and the audience and the recipient in the assertion are validated against the tokenEndpointAlias [2]. But 'Identity Provider Entity ID' in the resident IdP has been expected to be considered as tokenEndpointAlias. 

[1]https://docs.wso2.com/display/IS580/Setting+up+a+SAML2+Bearer+Assertion+Profile+for+OAuth+2.0
[2]https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/handlers/grant/saml/SAML2BearerGrantHandler.java#L744

**Comment by mefarazath** [comment]
In which tenant was the SAML SP that issues the assertion created?
Also did we have the correct configurations in the SAML SP to include the expected audience value.

**Comment by Abilashini** [comment]
> In which tenant was the SAML SP that issues the assertion created?
Both the token request and SAML request sent to the same SP created in a tenant.

> Also did we have the correct configurations in the SAML SP to include the expected audience value.
yes, we have. According to the doc, tenant-based SP, audience value should contain the tenant domain as a query parameter. eg: https://localhost:9443/oauth2/token?tenantDomain=wso2.com
The flow works fine if we don't include the tenant domain in the audience URL above since the audience value will be validated by comparing to the token endpoint.

**Comment by mefarazath** [comment]
Actually we do not need to include the tenantDomain in the token URL. Tenant domain is resolved internally using the client_id. This is possible since the client_id is unique across all tenants.

Shall we get the docs fixed please?

**Comment by Abilashini** [comment]
Even though, the audience value should be something that user can configure. Isn't it? 
By default, we can say it should be https://localhost:9443/oauth2/token. If the user has a requirement to use a different one, then they can configure it as **Identity Provider Entity ID** at Resident IdP and add it as the audience and recipient values. WDYT?
