### ISSUE TITLE
PostgreSQL errors when starting WSO2IS

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#5295]
When we are is using postgresql 10.6 with IS-KM-5.7.0. Here we have all the tables in a single database. 
The error logs in postgres db are given below.

2019-05-07 15:26:19.163 GMT [673] ERROR:  relation "sp" does not exist
2019-05-07 15:26:19.163 GMT [673] STATEMENT:  SELECT pg_get_serial_sequence($1, $2)
2019-05-07 15:26:19.163 GMT [673] ERROR:  relation "sp_inbound" does not exist
2019-05-07 15:26:19.163 GMT [673] STATEMENT:  SELECT pg_get_serial_sequence($1, $2)
2019-05-07 15:26:19.163 GMT [673] ERROR:  relation "sp" does not exist
2019-05-07 15:26:19.163 GMT [673] STATEMENT:  SELECT pg_get_serial_sequence($1, $2)
2019-05-07 15:26:19.164 GMT [673] ERROR:  relation "sp" does not exist
2019-05-07 15:26:19.164 GMT [673] STATEMENT:  SELECT pg_get_serial_sequence($1, $2)
2019-05-07 15:26:19.164 GMT [673] ERROR:  relation "sp_auth" does not exist
2019-05-07 15:26:19.164 GMT [673] STATEMENT:  SELECT pg_get_serial_sequence($1, $2)
2019-05-07 15:26:19.164 GMT [673] ERROR:  relation "sp" does not exist
2019-05-07 15:26:19.164 GMT [673] STATEMENT:  SELECT pg_get_serial_sequence($1, $2)
2019-05-07 15:26:19.164 GMT [673] ERROR:  relation "sp_claim" does not exist
2019-05-07 15:26:19.164 GMT [673] STATEMENT:  SELECT pg_get_serial_sequence($1, $2)
2019-05-07 15:26:19.165 GMT [673] ERROR:  relation "sp" does not exist
2019-05-07 15:26:19.165 GMT [673] STATEMENT:  SELECT pg_get_serial_sequence($1, $2)
2019-05-07 15:26:19.165 GMT [673] ERROR:  relation "sp_claim" does not exist

We were able to reproduce this issue when the same database is pointed in bps-datasource.xml file and master-datasource.xml file. But when we configure two different dbs in the bps-datasource file and master-datasource file, we are not getting those error logs. When we analyze the JDBC calls from the backend server, we observed that when a DB sequence is getting created, it is trying to execute the prepared statement query with a table or column that is not existing.

TID: [-1234] [] [2019-05-14 20:29:37,238] ERROR {jdbc.sqlonly} -  1. PreparedStatement.execute() SELECT pg_get_serial_sequence('sp', 'claim_mapping') 
org.postgresql.util.PSQLException: ERROR: relation "sp" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:132)
	at net.sf.log4jdbc.PreparedStatementSpy.execute(PreparedStatementSpy.java:413)
	at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy20.execute(Unknown Source)
	at org.apache.openjpa.lib.jdbc.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:367)
	at org.apache.openjpa.lib.jdbc.LoggingConnectionDecorator$LoggingConnection$LoggingPreparedStatement.execute(LoggingConnectionDecorator.java:1256)
	at org.apache.openjpa.lib.jdbc.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:367)
	at org.apache.openjpa.jdbc.sql.PostgresDictionary.queryOwnership(PostgresDictionary.java:465)
	at org.apache.openjpa.jdbc.sql.PostgresDictionary.isOwnedSequence(PostgresDictionary.java:430)
	at org.apache.openjpa.jdbc.sql.PostgresDictionary.isSystemSequence(PostgresDictionary.java:396)
	at org.apache.openjpa.jdbc.schema.SchemaGenerator.generateSequences(SchemaGenerator.java:960)
	at org.apache.openjpa.jdbc.schema.SchemaGenerator.generateSchema(SchemaGenerator.java:367)

 When we debug the code, we observed that the error comes from this PostgresDictionary.java class [1]. From this isOwnedSequence(..) method, it getting different permutations for the name of the sequence and trying to get names for table and column from the name of the sequence. For example,

if the sequence name is reg_log_pk_seq,
then it  takes table name as <reg> and column name as <log_pk> and execute SELECT pg_get_serial_sequence. Since there is no table exist as reg, it throws an error. Similarly, it takes different combinations and executes the query.  

We tried to change the sequence name to an existing table and column. In that case also, we are getting errors since it executes  SELECT pg_get_serial_sequence query for all the permutations which may not be a table or column in the DB. But we are not getting this error when two different databases are pointed in master-datasources.xml and bps-datasources.xml.

[1]https://github.com/wso2/wso2-openjpa/blob/master/openjpa-jdbc/src/main/java/org/apache/openjpa/jdbc/sql/PostgresDictionary.java
[2]https://github.com/wso2/wso2-openjpa/blob/master/openjpa-jdbc/src/main/java/org/apache/openjpa/jdbc/sql/PostgresDictionary.java#L409

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
