### ISSUE TITLE
SAML Authentication request validation fails when Comparison element is missing

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#5302]
#### Description
The "Comparison" is not a mandatory field according to the SAML [specification](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) [1].
When a SAML request is sent to the identity server without comparison attribute, the following null pointer exception is thrown.
```
[2019-05-17 10:16:16,691] ERROR {org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet} -  Error when processing the authentication request!
org.wso2.carbon.identity.base.IdentityException: Error validating the authentication request
	at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:60)
	at org.wso2.carbon.identity.sso.saml.validators.SPInitSSOAuthnRequestValidator.validate(SPInitSSOAuthnRequestValidator.java:154)
	at org.wso2.carbon.identity.sso.saml.SAMLSSOService.validateSPInitSSORequest(SAMLSSOService.java:92)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleSPInitSSO(SAMLSSOProviderServlet.java:473)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleRequest(SAMLSSOProviderServlet.java:226)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.doGet(SAMLSSOProviderServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:91)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:60)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.identity.sso.saml.validators.SPInitSSOAuthnRequestValidator.setRequestedAuthnContext(SPInitSSOAuthnRequestValidator.java:161)
	at org.wso2.carbon.identity.sso.saml.validators.SPInitSSOAuthnRequestValidator.validate(SPInitSSOAuthnRequestValidator.java:144)
	... 58 more
```

[1] [https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf)

**Comment by pamodaaw** [comment]
#### Steps to reproduce the issue

1. Start the identity server.
2. Register a service provider for Travelocity.com sample application
3. Enter the following URL in the browser

[https://localhost:9443/samlsso?SAMLRequest=nZNPb9NAEMXvSHwHa%2B%2BOnT%2BCdhW7CokqIhUUEpcDt%2B16XK%2B73jU747T99qztBAKCKOI6nvnN7HvP85uXWgd7cKisSdh4FLMAjLS5Mo8Ju89uwyt2k759M0dR64YvWirNFr63gBQsEMGRn1tag20NbgduryTcb%2B8SVhI1PIq0lUKXFolfx9dxRE7swdcUvY6kraPS1jCqsGHByhOVEdSf0Q3j79Oz2TTqbkC0LLi1TkJ%2FS8IKoRFYsF4l7KnMhVG2Kh9NI6FuciNUofJSVqa2dQVl8ZQX1YPftsaNQFR7%2BDWP2MLaIAlDCZvE46swfh%2BOx9l4yuOYT2ej2fTdNxZsnCUrrf6gzKBR6wy3AhVyI2pATpLvFp%2Fu%2BGQU84ehCfnHLNuEW8iVA0ks%2BHrUe9Lp7R0wyHuBz%2BOaw26WHuzoj3aXA8TRMZb%2B4cQ8OiUO%2FEnDP3vEerWxWsnXYKG1fV46EORlI9dCb0Qt6PzSrqLysOhbedM9HQmMl2G36fhfWqG9TeASNmw%2FVWRyqSTRz5sP8YS8D4jPJsEL%2FQ9yIPJTzFJ7CbdQnOAuVvxsm%2BSyQ%2FtyF8xn6%2FIuaD4skGdOGGyso8Gjv96TDt%2F%2B9fr0aO%2Fp%2F5v%2BAA%3D%3D&SigAlg=http%3A%2F%2Fwww.w3.org%2F2000%2F09%2Fxmldsig%23rsa-sha1&Signature=gRE6Wn%2Bm%2BwfMK0mrC6vhNEHYal%2FuGcsDaG1VVHJDmBq7JUP8hg%2FMPJsz2RMKUR6mMaFdErmasybKoxErg0SQFf8ruweZTLoYXoIKgUnWehM9cOMXdhleV%2Fw8DgpFGRxMi2kHJOKnGbXmAs8UaCVmaHWU7l07g%2B4%2B%2FK8p3VTg3zb9Y10WIqfol0cRgMRJ4cOzBZObWF3YTLVd%2BgTWC7TfAAw1pvBWypA%2B62nUVmHAwWKaPmjjpcJPilBQ1BaBq4Mgh4AUzoIpJ%2FSl8jy4HDlWbHoP96zUdXPLmeduosDZqnPVmEpfbZM7V0HDaM%2Bnkamae76yQzwTHGb6BskYuYeqvQ%3D%3D](https://localhost:9443/samlsso?SAMLRequest=nZNPb9NAEMXvSHwHa%2B%2BOnT%2BCdhW7CokqIhUUEpcDt%2B16XK%2B73jU747T99qztBAKCKOI6nvnN7HvP85uXWgd7cKisSdh4FLMAjLS5Mo8Ju89uwyt2k759M0dR64YvWirNFr63gBQsEMGRn1tag20NbgduryTcb%2B8SVhI1PIq0lUKXFolfx9dxRE7swdcUvY6kraPS1jCqsGHByhOVEdSf0Q3j79Oz2TTqbkC0LLi1TkJ%2FS8IKoRFYsF4l7KnMhVG2Kh9NI6FuciNUofJSVqa2dQVl8ZQX1YPftsaNQFR7%2BDWP2MLaIAlDCZvE46swfh%2BOx9l4yuOYT2ej2fTdNxZsnCUrrf6gzKBR6wy3AhVyI2pATpLvFp%2Fu%2BGQU84ehCfnHLNuEW8iVA0ks%2BHrUe9Lp7R0wyHuBz%2BOaw26WHuzoj3aXA8TRMZb%2B4cQ8OiUO%2FEnDP3vEerWxWsnXYKG1fV46EORlI9dCb0Qt6PzSrqLysOhbedM9HQmMl2G36fhfWqG9TeASNmw%2FVWRyqSTRz5sP8YS8D4jPJsEL%2FQ9yIPJTzFJ7CbdQnOAuVvxsm%2BSyQ%2FtyF8xn6%2FIuaD4skGdOGGyso8Gjv96TDt%2F%2B9fr0aO%2Fp%2F5v%2BAA%3D%3D&SigAlg=http%3A%2F%2Fwww.w3.org%2F2000%2F09%2Fxmldsig%23rsa-sha1&Signature=gRE6Wn%2Bm%2BwfMK0mrC6vhNEHYal%2FuGcsDaG1VVHJDmBq7JUP8hg%2FMPJsz2RMKUR6mMaFdErmasybKoxErg0SQFf8ruweZTLoYXoIKgUnWehM9cOMXdhleV%2Fw8DgpFGRxMi2kHJOKnGbXmAs8UaCVmaHWU7l07g%2B4%2B%2FK8p3VTg3zb9Y10WIqfol0cRgMRJ4cOzBZObWF3YTLVd%2BgTWC7TfAAw1pvBWypA%2B62nUVmHAwWKaPmjjpcJPilBQ1BaBq4Mgh4AUzoIpJ%2FSl8jy4HDlWbHoP96zUdXPLmeduosDZqnPVmEpfbZM7V0HDaM%2Bnkamae76yQzwTHGb6BskYuYeqvQ%3D%3D)

This is the sample SAML request omitting the comparison element
```
<?xml version="1.0" encoding="UTF-8"?>
<samlp:AuthnRequest AssertionConsumerServiceURL="http://localhost:9090/travelocity.com/home.jsp" Destination="https://localhost:9443/samlsso" ForceAuthn="false" ID="khdaniojhgnpcempdnaifidhcjnmomjehfkdfjbp" IsPassive="false" IssueInstant="2018-07-11T13:00:34.436Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Version="2.0"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <samlp:Issuer
        xmlns:samlp="urn:oasis:names:tc:SAML:2.0:assertion">travelocity.com
    </samlp:Issuer>
    <saml2p:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" SPNameQualifier="Issuer"
        xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"/>
        <saml2p:RequestedAuthnContext
            xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol">
            <saml:AuthnContextClassRef
                xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
            </saml:AuthnContextClassRef>
        </saml2p:RequestedAuthnContext>
    </samlp:AuthnRequest>
```
4. Then the above error will be logged
