### ISSUE TITLE
WSO2 IS 5.8.0 GA released pack does not start in windows

### ISSUE THREAD

**Issue by samanthiL** [wso2/product-is#5355]
$subject please
WSO2 IS 5.8.0 pack taken from the product download page (Binary distribution) dies not start on Windows 

Windows version - Windows 10 Pro
JDK version - JDK "1.8.0_111"

E:\sliit\wso2is-5.8.0\bin>wso2server.bat --start
JAVA_HOME environment variable is set to C:\Program Files\Java\jdk1.8.0_111
CARBON_HOME environment variable is set to E:\sliit\wso2is-5.8.0\bin\..
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Could not load Logmanager "org.apache.juli.ClassLoaderLogManager"
java.lang.ClassNotFoundException: org.apache.juli.ClassLoaderLogManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.util.logging.LogManager$1.run(LogManager.java:195)
        at java.util.logging.LogManager$1.run(LogManager.java:181)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.util.logging.LogManager.<clinit>(LogManager.java:181)
        at java.util.logging.Logger.demandLogger(Logger.java:448)
        at java.util.logging.Logger.getLogger(Logger.java:502)
        at com.sun.jmx.remote.util.ClassLogger.<init>(ClassLogger.java:55)
        at sun.management.jmxremote.ConnectorBootstrap.<clinit>(ConnectorBootstrap.java:846)
        at sun.management.Agent.startLocalManagementAgent(Agent.java:138)
        at sun.management.Agent.startAgent(Agent.java:260)
        at sun.management.Agent.startAgent(Agent.java:447)
Error: Could not find or load main class org.wso2.carbon.bootstrap.Bootstrap
E:\sliit\wso2is-5.8.0\bin>

Thank you,
Samanthi

**Comment by ruwanta** [comment]
Hi @samanthiL ,
It looks like you are using unsupported command line option "--start".
the following options are the ones only supported "--run" "--restart" "--debug" and "--version" according to "wso2server.bat".
However this does not explain the error you are getting.

It looks like the jar in the location "CARBON_HOME\bin\tomcat-juli-7.0.93.jar" is not loaded properly. Can you please check of the "tomcat-juli-7.0.93.jar" is present and it is not corrupted.

If the above is all right, then it would be something wrong in the "wso2server.bat", specifically the line 167 (i.e. -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager)

Cheers,
Ruwan

**Comment by samanthiL** [comment]
Hi Ruwan,
           Thank you for the update seem like jars to be corrupted , I took a fresh download again from the  distribution page and it will working fine.
 sorry for the noise

Thank you,
Samanthi

**Comment by ruwanta** [comment]
Hi @samanthiL,
Thank you for trying out WSO2 IS. Glad you sorted out the issue.
Any feedback is always appreciated, and never considered a noise.

Cheers,
Ruwan
