### ISSUE TITLE
Getting error when updating user in Outbound provisioning with SCIM when enabling Password Provisioning

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5505]
Steps to Reproduce:
1) Add IDP and configure scim outbound provisioning with password provisioning enabled
2) Configure outbound provisioning in resident SP
3) Use following commands to add and update users

**Create User:**
`curl -v -k --user admin:admin --data "{"schemas":[],"name":{"familyName":"user","givenName":"test"},"userName":"testUser","password":"testuser"}" --header "Content-Type:application/json" https://localhost:9443/scim2/Users`

This command creates a user in both Identity Servers.

**Response**
`{"meta":{"created":"2019-06-09T04:20:24.960Z","location":"https://localhost:9443/scim2/Users/f72df4cf-a747-4760-9083-cf9bc36a904a","lastModified":"2019-06-09T04:20:24.960Z","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],"roles":[{"type":"default","value":"Internal/everyone"}],"name":{"givenName":"test","familyName":"user"},"id":"f72df4cf-a747-4760-9083-cf9bc36a904a","userName":"testUser"}`

Now try to update the above user.
**Update User**
`curl -v -k --user admin:admin -X PUT -d "{"schemas":[],"name":{"familyName":"user102","givenName":"test102"},"userName":"testUser"}" --header "Content-Type:application/json" https://localhost:9443/scim2/Users/f72df4cf-a747-4760-9083-cf9bc36a904a`

**Response**
`{"meta":{"created":"2019-06-09T04:20:24.960Z","location":"https://localhost:9443/scim2/Users/f72df4cf-a747-4760-9083-cf9bc36a904a","lastModified":"2019-06-09T04:27:36.523Z","resourceType":"User"},"schemas":["urn:ietf:params:scim:schemas:core:2.0:User","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"],"roles":[{"type":"default","value":"Internal/everyone"}],"name":{"givenName":"test102","familyName":"user102"},"id":"f72df4cf-a747-4760-9083-cf9bc36a904a","userName":"testUser"}`

    

This updates the user details in the Internal IS but does not update details in external IS.
Even though user is updated, follow error can be seen.

   
`[2019-06-09 09:57:36,522]  INFO {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} -  User: testUser is retrieved through SCIM.
[2019-06-09 09:57:36,534]  INFO {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} -  User: testUser is retrieved through SCIM.
[2019-06-09 09:57:36,568]  INFO {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} -  User: testUser updated through SCIM.
[2019-06-09 09:57:36,582]  INFO {org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager} -  User: testUser is retrieved through SCIM.
[2019-06-09 09:57:36,629]  INFO {org.wso2.carbon.identity.scim.common.impl.ProvisioningClient} -  SCIM update user operation returned with response code: 500
[2019-06-09 09:57:36,629]  INFO {org.wso2.carbon.identity.scim.common.impl.ProvisioningClient} -  SCIM update user operation returned with response code: 500
[2019-06-09 09:57:36,629] ERROR {org.wso2.carbon.identity.provisioning.ProvisioningThread} -   Provisioning for Entity testUser For operation = PATCH
org.wso2.carbon.identity.provisioning.IdentityProvisioningException: Error while creating the user
	at org.wso2.carbon.identity.provisioning.connector.scim.SCIMProvisioningConnector.updateUser(SCIMProvisioningConnector.java:222)
	at org.wso2.carbon.identity.provisioning.connector.scim.SCIMProvisioningConnector.provision(SCIMProvisioningConnector.java:113)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:68)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.identity.scim.common.impl.ProvisioningClient.provisionPatchUser(ProvisioningClient.java:459)
	at org.wso2.carbon.identity.provisioning.connector.scim.SCIMProvisioningConnector.updateUser(SCIMProvisioningConnector.java:218)
	... 7 more
[2019-06-09 09:57:36,631]  INFO {org.wso2.carbon.identity.scim.common.impl.ProvisioningClient} -  SCIM update user operation returned with response code: 500
[2019-06-09 09:57:36,631] ERROR {org.wso2.carbon.identity.provisioning.ProvisioningThread} -   Provisioning for Entity testUser For operation = PUT
org.wso2.carbon.identity.provisioning.IdentityProvisioningException: Error while creating the user
	at org.wso2.carbon.identity.provisioning.connector.scim.SCIMProvisioningConnector.updateUser(SCIMProvisioningConnector.java:222)
	at org.wso2.carbon.identity.provisioning.connector.scim.SCIMProvisioningConnector.provision(SCIMProvisioningConnector.java:111)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:68)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.identity.scim.common.impl.ProvisioningClient.provisionPatchUser(ProvisioningClient.java:459)
	at org.wso2.carbon.identity.provisioning.connector.scim.SCIMProvisioningConnector.updateUser(SCIMProvisioningConnector.java:218)
	... 7 more
[2019-06-09 09:57:36,633] ERROR {org.wso2.carbon.identity.provisioning.ProvisioningThread} -   Provisioning for Entity testUser For operation = PATCH
org.wso2.carbon.identity.provisioning.IdentityProvisioningException: Error while creating the user
	at org.wso2.carbon.identity.provisioning.connector.scim.SCIMProvisioningConnector.updateUser(SCIMProvisioningConnector.java:222)
	at org.wso2.carbon.identity.provisioning.connector.scim.SCIMProvisioningConnector.provision(SCIMProvisioningConnector.java:113)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:68)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.identity.scim.common.impl.ProvisioningClient.provisionPatchUser(ProvisioningClient.java:459)
	at org.wso2.carbon.identity.provisioning.connector.scim.SCIMProvisioningConnector.updateUser(SCIMProvisioningConnector.java:218)
	... 7 more
`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
