### ISSUE TITLE
IDENTITY-6366 After enabling 'enable.relyingParty' property in client.properties sts client throws an exception.

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#5654]
Steps to reproduce:

1. Configure IS to run STS client.
2. Use the 'echo' service of AS 5.3.0 and configure this endpoint as 'address.relyingParty in client.properties file '.
3. Make 'enable.relyingParty' true in client.properties file 
4. Run the STS client and it throws following exception.

It generates saml token successfully. After it throws following exception.
```
java.lang.ClassCastException: org.apache.axiom.om.impl.llom.OMElementImpl cannot be cast to org.w3c.dom.Element
at org.apache.rampart.builder.BindingBuilder.handleSupportingTokens(BindingBuilder.java:392)
at org.apache.rampart.builder.SymmetricBindingBuilder.doSignBeforeEncrypt(SymmetricBindingBuilder.java:499)
at org.apache.rampart.builder.SymmetricBindingBuilder.build(SymmetricBindingBuilder.java:86)
at org.apache.rampart.MessageBuilder.build(MessageBuilder.java:144)
at org.apache.rampart.handler.RampartSender.invoke(RampartSender.java:65)
at org.apache.axis2.engine.Phase.invokeHandler(Phase.java:340)
at org.apache.axis2.engine.Phase.invoke(Phase.java:313)
at org.apache.axis2.engine.AxisEngine.invoke(AxisEngine.java:262)
at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:427)
at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:406)
at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
at org.apache.axis2.client.ServiceClient.sendReceive(ServiceClient.java:555)
at org.apache.axis2.client.ServiceClient.sendReceive(ServiceClient.java:531)
at org.wso2.carbon.identity.samples.sts.Client.run(Client.java:242)
at org.wso2.carbon.identity.samples.sts.Client.main(Client.java:94)
```

**Labels**
Type: Bug
Priority: Normal
Component/s: samples, ws-security
Severity: Major
Estimated Complexity: Moderate

_Issue migrated from: https://wso2.org/jira/browse/IDENTITY-6366_

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
