### ISSUE TITLE
LoggedInSessionBean Serialization Error

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5690]
the LoggedInSessionBean of the component

<dependency>
<groupId>org.wso2.carbon.identity.agent.sso.java</groupId>
<artifactId>org.wso2.carbon.identity.sso.agent</artifactId>
<version>5.1.3</version>
</dependency>

has serialization errors:

java.lang.NullPointerException
at org.wso2.carbon.identity.sso.agent.bean.LoggedInSessionBean$SAML2SSO.readObject(LoggedInSessionBean.java:211)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2136)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
at org.apache.catalina.session.StandardSession.readObject(StandardSession.java:1609)
at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1075)
at org.apache.catalina.session.StandardManager.doLoad(StandardManager.java:259)
at org.apache.catalina.session.StandardManager.load(StandardManager.java:176)
at org.apache.catalina.session.StandardManager.startInternal(StandardManager.java:465)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5643)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1571)
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1561)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

The side effect is that tomcat clustering cannot be used

**Comment by DMHP** [comment]
[test-case-bug.zip](url)

**Comment by DMHP** [comment]
https://wso2.org/jira/browse/IDENTITY-6893

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
