### ISSUE TITLE
Error when Handling browser back button and bookmarked login page when there is no tenantDomain parameter in the authentication request

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#5698]
Steps to reproduce:

1. Follow this doc and enabled booked maked login page [1].
2. bookmarked/saved the authentication endpoint URL to file (Referring as url1).
3. Logout the service provider
4. Remove the tenantDomain request parameter in the url1 if it has tenant domain.
5. Alter the sessionDatakey with some random characters and paste it into the browser again and hit.
6. Try to login to the service provider

The modified sessionDataKey is used as it is (not generating a new sessionDataKey), and when provided with valid credentials, the user is directed to the https://localhost:9443/authenticationendpoint/retry.do with the Authentication error message.

It will fail with the following error.

<img width="1232" alt="Screen Shot 2019-06-12 at 6 04 53 PM" src="https://user-images.githubusercontent.com/17597293/59351695-9cd0e200-8d3c-11e9-8aeb-122479958a43.png">

Sample login request:  
`https://localhost:9443/authenticationendpoint/login.do?SSOAuthSessionID=CAAB0BA2C67A90257EA35B4EC1C4F2ACBD8BA8C52007D8639618976CBB8D60E2C0681A2211EDE4970EC254684F51F2F734E6DAF1EDED6BC578D7B37D20E0B5503935E824ED2EAB4C43F145D00A9D7E2F5AEE9C7690610A36A934E99F412C3D29595BBFD6D8EDC1510C60D7F4875B44D0A6D1EB616C42BE6EE3C6F92CC6E5F780&commonAuthCallerPath=%2Fsamlsso&forceAuth=false&passiveAuth=false&sessionDataKey=31e4rre19-618c-45c0-a8e6-d2502bc8c435&relyingParty=wso2.my.dashboard&type=samlsso&sp=wso2_sp_dashboard&isSaaSApp=true&authenticators=BasicAuthenticator:LOCAL`

Since it does not have tenant domain,  loginContext Url will have tenatDomain request parameter as null.

sample loginContext request:
`https://localhost:9443/logincontext?sessionDataKey=31e4rre19-618c-45c0-a8e6-d2502bc8c435&relyingParty=wso2.my.dashboard&tenantDomain=null`

```
[2019-06-12 17:02:54,145] DEBUG {org.wso2.carbon.identity.application.authentication.framework.util.LoginContextManagementUtil} -  retrieving configured url against relying party : wso2.my.dashboardfor tenant domain : null
[2019-06-12 17:02:54,191] ERROR {org.apache.catalina.core.StandardWrapperValve} -  Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception
org.wso2.carbon.identity.base.IdentityRuntimeException: Invalid tenant domain null
	at org.wso2.carbon.identity.base.IdentityRuntimeException.error(IdentityRuntimeException.java:152)
	at org.wso2.carbon.identity.core.util.IdentityTenantUtil.getTenantId(IdentityTenantUtil.java:242)
	at org.wso2.carbon.identity.application.authentication.framework.util.LoginContextManagementUtil.getRelyingPartyRedirectUrl(LoginContextManagementUtil.java:106)
	at org.wso2.carbon.identity.application.authentication.framework.util.LoginContextManagementUtil.handleLoginContext(LoginContextManagementUtil.java:68)
	at org.wso2.carbon.identity.application.authentication.framework.servlet.LoginContextServlet.doGet(LoginContextServlet.java:40)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.CSRFPreventionFilter.doFilter(CSRFPreventionFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.ui.filters.CRLFPreventionFilter.doFilter(CRLFPreventionFilter.java:59)
```
This error comes from this line of code [2]. Here instead of returning null, if we return an empty string, it will work. The fix is given below
```
function getParameterByName(name, url) {
             if (!url) {
                url = window.location.href;
             }
             name = name.replace(/[\[\]]/g, '\\$&');
             var regex = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)'),
             results = regex.exec(url);
             if (!results) return "";
             if (!results[2]) return "";
             return decodeURIComponent(results[2].replace(/\+/g, ' '));
         }
```
[1]https://docs.wso2.com/display/IS570/Customizing+the+Authentication+Endpoint#CustomizingtheAuthenticationEndpoint-Handlingbrowserbackbuttonandbookmarkedloginpage
[2]https://github.com/wso2/carbon-identity-framework/blob/master/components/authentication-framework/org.wso2.carbon.identity.application.authentication.endpoint/src/main/webapp/login.jsp#L163

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
