### ISSUE TITLE
STS TokenRequest using "UsernameToken" with PublicKey KeyType throws org.apache.rahas.TrustException: Error in creating a SAMLToken using Opensaml library. Details see Description.

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#5749]
Setting up the service "wso2carbon-sts" secured using "UsernameToken”, follows direction at https://docs.wso2.com/display/IS500/Configuring+STS+for+Obtaining+Tokens+with+Holder-Of-Key+Subject+Confirmation to configure Holder-of-Key subject confirmation. Supplying HoK service provider at trusted service endpoint address with certificate alias as “my_cert_alias”. WSO2 STS did not use that alias (i.e. my_cert_alias) to retrieve cert. It throws following exception:

org.apache.rahas.TrustException: Error in creating a SAMLToken using Opensaml library
at org.apache.rahas.impl.SAMLTokenIssuer.createHoKAssertion(SAMLTokenIssuer.java:453)
at org.apache.rahas.impl.SAMLTokenIssuer.issue(SAMLTokenIssuer.java:173)
at org.apache.rahas.TokenRequestDispatcher.handle(TokenRequestDispatcher.java:69)
at org.apache.rahas.STSMessageReceiver.invokeBusinessLogic(STSMessageReceiver.java:57)
at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40)
at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
at org.apache.axis2.transport.http.HTTPTransportUtils.processHTTPPostRequest(HTTPTransportUtils.java:172)
at org.apache.axis2.transport.http.AxisServlet.doPost(AxisServlet.java:146)
at org.wso2.carbon.core.transports.CarbonServlet.doPost(CarbonServlet.java:231)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)

WSO2 Identity Server STS Service actually uses “my_username” as cert retrieval alias defined in my RequestSecurityToken xml to load PublicKey create STS Token.
part of RequestSecurityToken xml:

```...
<wsse:Security 
xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
<wsu:Timestamp>
<wsu:Created>2015-05-28T20:33:25Z</wsu:Created>
<wsu:Expires>2016-05-28T20:33:55Z</wsu:Expires>
</wsu:Timestamp>
<wsse:UsernameToken>
<wsse:Username>my_username</wsse:Username>
<wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">my_password</wsse:Password>
</wsse:UsernameToken>
</wsse:Security>
...
<wst:KeyType>http://schemas.xmlsoap.org/ws/2005/02/trust/PublicKey</wst:KeyType>
```

OT Jira: https://wso2.org/jira/browse/IDENTITY-3406

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
