### ISSUE TITLE
NPE when opening the Service Provider through management console after updated the service provider through soap service

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#5757]
**Environment**
IS-KM 5.7.0, Oracle DB

**Steps to reproduce**

1. Configure IS with oracle DB.
2. Add a dummy service provider and update the service provider using IdentityApplicationManagementService.
3. Go to the management console and try to edit the service provider. It throws the stack trace [1]

**Cause:**  In SP_AUTH_SCRIPT, the content is saved as null in Oracle. But in the default pack (H2) this is saved as empty string. Therefore it is throwing the NPE when retrieving the authentication script.

When executing this query,
SELECT * FROM SP_AUTH_SCRIPT;

<img width="642" alt="Screen Shot 2019-06-13 at 2 57 41 PM" src="https://user-images.githubusercontent.com/17597293/59421097-ad8c6100-8deb-11e9-8ea6-6a102bed07b9.png">

[1]

```
[2019-06-13 13:10:20,669]  INFO {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} -  'admin@carbon.super [-1234]' logged in at [2019-06-13 13:10:20,669+0530]
[2019-06-13 13:10:23,476] ERROR {org.wso2.carbon.identity.application.mgt.dao.impl.CacheBackedApplicationDAO} -  Error occurred while retrieving the application, testsp
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1906)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:778)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:759)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getScriptConfiguration(ApplicationDAOImpl.java:2657)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getLocalAndOutboundAuthenticationConfig(ApplicationDAOImpl.java:2588)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getApplication(ApplicationDAOImpl.java:1672)
	at org.wso2.carbon.identity.application.mgt.dao.impl.CacheBackedApplicationDAO.getApplication(CacheBackedApplicationDAO.java:77)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.getApplicationExcludingFileBasedSPs(ApplicationManagementServiceImpl.java:187)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementAdminService.getApplication(ApplicationManagementAdminService.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212)
	at org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic(RPCMessageRece

```
Similar issue is reported in https://github.com/wso2/product-is/issues/5458 also. 

Fixed in master. https://github.com/wso2/carbon-identity-framework/blob/master/components/application-mgt/org.wso2.carbon.identity.application.mgt/src/main/java/org/wso2/carbon/identity/application/mgt/dao/impl/ApplicationDAOImpl.java#L2657

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
