### ISSUE TITLE
Issue while managing service providers with multiple tabs

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#5759]
**Steps to reproduce**

1. Create a service provider and add SAML2 Web SSO Configuration
2. Go to edit page of the same service provider
3. Open another tab and delete the "SAML2 Web SSO Configuration" (keep it as is)
4. Click "Update" on the first tab
5. Goto second tab again (do not refresh or reload the page) and try to register "SAML2 Web SSO Configuration" with the same previous issuer
6. The following error is logged and an empty page is displayed

```
[2019-06-14 00:48:45,334] ERROR {org.apache.catalina.core.ApplicationDispatcher} -  Servlet.service() for servlet bridgeservlet threw exception
java.lang.NullPointerException
	at org.wso2.carbon.identity.application.mgt.ui.ApplicationBean.update(ApplicationBean.java:1118)
	at org.apache.jsp.application.update_002dapplication_002dbean_jsp._jspService(update_002dapplication_002dbean_jsp.java:179)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
```
7. Later, it is not possible to register the same issuer until we delete the issuer from the registry "/_system/config/repository/identity/SAMLSSO" path

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
