### ISSUE TITLE
Latest server startup throws an error

### ISSUE THREAD

**Issue by DMHP** [wso2/product-is#5867]
Steps to reproduce:

1. Build wso2is-5.9.0-m2-SNAPSHOT.zip pack
2. Open the carbon.xml.j2 and close the file. (Just open it. No need to edit it.)
3. Server start up fails with following error.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:70)
	at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)
Caused by: com.hubspot.jinjava.interpret.FatalTemplateErrorsException: TemplateSyntaxException: Error parsing '217, 235}, {770, 636': syntax error at position 112, encountered ',', expected '}'
	at com.hubspot.jinjava.Jinjava.render(Jinjava.java:155)
	at org.wso2.carbon.nextgen.config.JinjaParser.lambda$parse$0(JinjaParser.java:57)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by ashensw** [comment]
Issue is not reproducible in the latest pack.
