### ISSUE TITLE
smsotp_disabled attribute should have mapped attributed out of the box

### ISSUE THREAD

**Issue by prabath** [wso2/product-is#5933]
All the connectors we ship out of the box - need to work with minimal configuration.

Caused by: org.wso2.carbon.user.core.UserStoreException: org.wso2.carbon.user.core.UserStoreException: Mapped attribute cannot be found for claim : http://wso2.org/claims/identity/smsotp_disabled in user store : PRIMARY
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetUserClaimValues(AbstractUserStoreManager.java:5201)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValues(AbstractUserStoreManager.java:959)
	... 70 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Mapped attribute cannot be found for claim : http://wso2.org/claims/identity/smsotp_disabled in user store : PRIMARY

**Comment by dqvn** [comment]
is this issues fixed? I meet the same problem with 4.2.0.0 now. Please help to share your solution if existed! Thanks

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
