### ISSUE TITLE
Multiple server startup issues

### ISSUE THREAD

**Issue by tharindu1st** [wso2/product-is#5936]
**Environment**
1. Mysql 5.7
2. IS 5.9.0-m2 with fixes [1] ,[2]

Server goes with following exceptions attached when starting two servers get the start at once.

[erros.txt](https://github.com/wso2/product-is/files/3404854/erros.txt)

[1]  - https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1140
[2] - https://github.com/wso2/carbon-kernel/pull/2120

**Comment by tharindu1st** [comment]
Fix for Email templates https://github.com/wso2-extensions/identity-event-handler-notification/pull/95

**Comment by senthalan** [comment]
Still the following errors not fixed,
```
[2019-07-15 17:03:42,358] ERROR {org.wso2.carbon.identity.entitlement.EntitlementUtil} -  Error while adding sample XACML policies
java.lang.NullPointerException
	at java.lang.String.<init>(String.java:515)
	at org.wso2.carbon.identity.entitlement.pap.store.PAPPolicyStoreReader.readPolicyDTO(PAPPolicyStoreReader.java:116)
	at org.wso2.carbon.identity.entitlement.EntitlementUtil.addFilesystemPolicy(EntitlementUtil.java:459)
	at org.wso2.carbon.identity.entitlement.EntitlementUtil.addSamplePolicies(EntitlementUtil.java:391)
	at org.wso2.carbon.identity.entitlement.internal.EntitlementServiceComponent.activate(EntitlementServiceComponent.java:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
```
[2019-07-15 17:03:45,780] ERROR {org.wso2.carbon.identity.scim.common.internal.SCIMCommonComponent} -  Error occurred while setting SCIM attributes for the Admin
org.wso2.carbon.user.core.UserStoreException: Error in adding SCIM metadata to the admin in tenant domain: carbon.super
	at org.wso2.carbon.identity.scim.common.utils.SCIMCommonUtils.setAdminSCIMAttributes(SCIMCommonUtils.java:250)
	at org.wso2.carbon.identity.scim.common.internal.SCIMCommonComponent.activate(SCIMCommonComponent.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
```
```
[2019-07-15 17:03:46,099] ERROR {org.wso2.carbon.identity.scim2.common.utils.AdminAttributeUtil} -  Error occurred while updating the admin user's attributes in Tenant ID : -1234, Error : org.wso2.carbon.user.core.UserStoreException: Mapped attribute cannot be found for claim : urn:ietf:params:scim:schemas:core:2.0:id in user store : PRIMARY
org.wso2.carbon.user.core.UserStoreException: org.wso2.carbon.user.core.UserStoreException: Mapped attribute cannot be found for claim : urn:ietf:params:scim:schemas:core:2.0:id in user store : PRIMARY
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:181)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValue(AbstractUserStoreManager.java:771)
	at org.wso2.carbon.identity.scim2.common.utils.AdminAttributeUtil.updateAdminUser(AdminAttributeUtil.java:75)
	at org.wso2.carbon.identity.scim2.common.internal.SCIMCommonComponent.activate(SCIMCommonComponent.java:92)
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
