### ISSUE TITLE
Error when invoking OIDC federated Authenticator

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#6013]
Steps to reproduce: 
Built a product-is 5.9.0-m5-snapshot.
Federated IPD and Primary IDP are WSO2 IS 5.9.0-m5-snapshot
onfigured playground2 as service provider in Primary IS.
Configure Primary IS as service provider in Federated IPD.

Playground2 returned the with the following error:
http://localhost:8080/playground2/oauth2client?error_description=Authentication+required&error=login_required&session_state=e66ee0dcbac956444b47d808fc865d69c774a45f302f847df1ceebf23f68b5c2.MPK7c92ogoQMstjB2Rlhng

Error logs in Federated IDP:
```
[2019-07-29 12:20:44,990] DEBUG {org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService} -  Retrieving registered OAuth client authenticator list.
[2019-07-29 12:20:44,991] DEBUG {org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService} -  Evaluating canAuthenticate of authenticator : MutualTLSClientAuthenticator
[2019-07-29 12:20:44,991] DEBUG {org.wso2.carbon.identity.oauth2.token.handler.clientauth.mutualtls.MutualTLSClientAuthenticator} -  Client ID exists in request body parameters and a valid certificate found in request attributes. Hence returning true.
[2019-07-29 12:20:44,991] DEBUG {org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService} -  MutualTLSClientAuthenticator authenticator can handle incoming request.
[2019-07-29 12:20:44,991] DEBUG {org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService} -  Authenticator MutualTLSClientAuthenticator can authenticate the client request.  Hence trying to evaluate authentication
[2019-07-29 12:20:44,991] DEBUG {org.wso2.carbon.identity.oauth2.token.handler.clientauth.mutualtls.MutualTLSClientAuthenticator} -  Authenticating client : NYYXQcGzydaEt2InUFaTjRcIveYa with public certificate.
[2019-07-29 12:20:44,992] DEBUG {org.wso2.carbon.identity.oauth2.token.handler.clientauth.mutualtls.MutualTLSClientAuthenticator} -  Public certificate configured for Service Provider with client_id: NYYXQcGzydaEt2InUFaTjRcIveYa of tenantDomain: carbon.super. Using public certificate  for validating request certificate
[2019-07-29 12:20:44,992] DEBUG {org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService} -  Error while evaluating client authenticator : MutualTLSClientAuthenticator
org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnException: server_error
	at org.wso2.carbon.identity.oauth2.token.handler.clientauth.mutualtls.MutualTLSClientAuthenticator.authenticateClient(MutualTLSClientAuthenticator.java:156)
	at org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService.authenticateClient(OAuthClientAuthnService.java:211)
	at org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService.executeAuthenticator(OAuthClientAuthnService.java:106)
	at org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService.lambda$executeClientAuthenticators$0(OAuthClientAuthnService.java:149)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService.executeClientAuthenticators(OAuthClientAuthnService.java:148)
	at org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService.authenticateClient(OAuthClientAuthnService.java:63)
	at org.wso2.carbon.identity.oauth.client.authn.filter.OAuthClientAuthenticatorProxy.handleMessage(OAuthClientAuthenticatorProxy.java:74)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at 
Caused by: org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: Public certificate not configured for Service Provider with client_id: NYYXQcGzydaEt2InUFaTjRcIveYa of tenantDomain: carbon.super
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getX509CertOfOAuthApp(OAuth2Util.java:2558)
	at org.wso2.carbon.identity.oauth2.token.handler.clientauth.mutualtls.MutualTLSClientAuthenticator.authenticateClient(MutualTLSClientAuthenticator.java:151)
	... 60 more
[2019-07-29 12:20:44,997] DEBUG {org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService} -  Setting error to client authentication context : Error code : Error occurred while retrieving public certificate of client ID: NYYXQcGzydaEt2InUFaTjRcIveYa, Error message : server_error
[2019-07-29 12:20:44,997] DEBUG {org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService} -  Evaluating canAuthenticate of authenticator : BasicOAuthClientCredAuthenticator
[2019-07-29 12:20:44,997] DEBUG {org.wso2.carbon.identity.oauth2.client.authentication.BasicAuthClientAuthenticator} -  Basic auth credentials present as body params. Hence returning true
[2019-07-29 12:20:44,998] DEBUG {org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService} -  BasicOAuthClientCredAuthenticator authenticator can handle incoming request.
[2019-07-29 12:20:44,998] DEBUG {org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService} -  Previously an authenticator is evaluated. Hence authenticator BasicOAuthClientCredAuthenticator is not evaluating
[2019-07-29 12:20:44,998] DEBUG {org.wso2.carbon.identity.oauth2.client.authentication.OAuthClientAuthnService} -  Authenticator BasicOAuthClientCredAuthenticator can authenticate the client request.  Hence trying to evaluate authentication
```
**Error logs in Primary IS:** 
```
[2019-07-29 12:20:44,815] DEBUG {org.wso2.carbon.identity.application.authentication.framework.util.FrameworkUtils} -  No authenticators found.
[2019-07-29 12:20:44,815] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} -  Receive a response from the external party
[2019-07-29 12:20:44,815] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} -  OpenIDConnectAuthenticator can handle the request.
[2019-07-29 12:20:45,145] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} -  Authentication failed exception!
org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: invalid_request, The client MUST NOT use more than one authentication method in each
	at org.wso2.carbon.identity.application.authenticator.oidc.OpenIDConnectAuthenticator.getOauthResponse(OpenIDConnectAuthenticator.java:609)
	at org.wso2.carbon.identity.application.authenticator.oidc.OpenIDConnectAuthenticator.processAuthenticationResponse(OpenIDConnectAuthenticator.java:367)
	at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.process(AbstractApplicationAuthenticator.java:77)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:502)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handleResponse(DefaultStepHandler.java:476)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:175)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:185)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:111)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:142)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:239)
Caused by: OAuthProblemException{error='invalid_request', description='The client MUST NOT use more than one authentication method in each', uri='null', state='null', scope='null', redirectUri='null', responseStatus=0, parameters={}}
	at org.apache.oltu.oauth2.common.exception.OAuthProblemException.error(OAuthProblemException.java:59)
	at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validateErrorResponse(OAuthClientValidator.java:63)
	at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validate(OAuthClientValidator.java:48)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.validate(OAuthClientResponse.java:64)
	at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:59)
	at org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse.init(OAuthAccessTokenResponse.java:52)
[2019-07-29 12:20:45,153] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.GraphBasedStepHandler} -  Authentication flow status set to 'FAIL_COMPLETED' for authentication attempt made to service provider: playground2
[2019-07-29 12:20:45,153] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler} -  Authentication has failed in the Step 1
[2019-07-29 12:20:45,153] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler} -  Handling post authentication
[2019-07-29 12:20:45,154] DEBUG {org.wso2.carbon.identity.application.authentication.framework.ser
```

**Comment by piraveena** [comment]
This error is because this MutualTLSAuthenticator  connector is shipped into droppins by default. So this authenticator is always enabled. During token request from oidc-connector, it sends the the certificate to the federated IDP and tries to authenticate with MutualTLSAuthenticator

**Comment by mefarazath** [comment]
@piraveena So if someone has a requirement to keep the mutual tls authenticator enabled, then we will again face this issue right?

**Comment by piraveena** [comment]
@mefarazath Now in IS5.9.0-alpha pack, we keep mutualtls authenticator as enabled. We didn't disable that. 
According to the spec, client can't use more than one authentication mechanisms [1]. So if the client wants to use mutualtls authenticator, then client should not send client_secret in the token request, instead it has to send the x509 certificate. Then the default basicAuthCLientAuthenticator won't authenticate the client. 

The above issue occurred since the client (primary IS) sent both the x509 certifciate and client secret. So both mutualtls-authenticator and basicclientAuthenticator tried to authenticate in the federated IDP.

[1]https://tools.ietf.org/html/rfc6749#section-2.3
