### ISSUE TITLE
MySQL userstore and trailing spaces in role names

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#6126]
Steps to reproduce
* Configure MySQL JDBC user store
* Try to assign role "admin " to user "admin" using `RemoteUserStoreManagerService.updateRoleListOfUser()` (Note the trailing spaces in role name)

Following is returned
```
Using sql : INSERT INTO UM_USER_ROLE (UM_ROLE_ID, UM_USER_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_USER WHERE UM_USER_NAME=? AND UM_TENANT_ID=?), ?) Duplicate entry '1-1--1234' for key 'UM_USER_ID'
```

Following stack trace is logged
```
DEBUG {org.wso2.carbon.user.core.util.DatabaseUtil} -  Using sql : INSERT INTO UM_USER_ROLE (UM_ROLE_ID, UM_USER_ID, UM_TENANT_ID) VALUES ((SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?),(SELECT UM_ID FROM UM_USER WHERE UM_USER_NAME=? AND UM_TENANT_ID=?), ?) Duplicate entry '1-1--1234' for key 'UM_USER_ID'
java.sql.BatchUpdateException: Duplicate entry '1-1--1234' for key 'UM_USER_ID'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.util.Util.handleNewInstance(Util.java:210)
	at com.mysql.cj.util.Util.getInstance(Util.java:185)
	at com.mysql.cj.util.Util.getInstance(Util.java:192)
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:218)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:864)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:453)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:839)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy21.executeBatch(Unknown Source)
	at org.wso2.carbon.user.core.util.DatabaseUtil.udpateUserRoleMappingInBatchMode(DatabaseUtil.java:837)
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doUpdateRoleListOfUser(JDBCUserStoreManager.java:2034)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.updateRoleListOfUserInternal(AbstractUserStoreManager.java:3415)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.access$300(AbstractUserStoreManager.java:91)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$6.run(AbstractUserStoreManager.java:3231)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$6.run(AbstractUserStoreManager.java:3228)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.updateRoleListOfUser(AbstractUserStoreManager.java:3228)
	...
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '1-1--1234' for key 'UM_USER_ID'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:115)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:960)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1116)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:843)
	... 77 more
```

Here, we are checking whether the role is a valid one and whether the user is already having it before assigning the role to given user.

When we are checking the existence for the role name with the whitespace, MySQL returns true as below.

```
mysql> SELECT * FROM UM_ROLE;
+-------+--------------+--------------+----------------+
| UM_ID | UM_ROLE_NAME | UM_TENANT_ID | UM_SHARED_ROLE |
+-------+--------------+--------------+----------------+
|     1 | admin        |        -1234 |              0 |
+-------+--------------+--------------+----------------+
1 row in set (0.01 sec)

mysql> SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME="admin" AND UM_TENANT_ID=-1234;
+-------+
| UM_ID |
+-------+
|     1 |
+-------+
1 row in set (0.00 sec)

mysql> SELECT UM_ID FROM UM_ROLE WHERE UM_ROLE_NAME="admin " AND UM_TENANT_ID=-1234;
+-------+
| UM_ID |
+-------+
|     1 |
+-------+
1 row in set (0.00 sec)
```

Then, we are checking whether the user is already having the given role in the Java level by getting the role list of the user `AbstractUserStoreManager.isUserInRole()`. Therefore, it considers the two role names as different ones and decides the user is not assigned to the role name with whitespace. Therefore, it continues adding the role to the user and fails in the user store level due to a DB constraint.

This issue is specific to MySQL because it considers "role" = "role ". The best solution for this issue will be trimming the role names to eliminate leading and trailing spaces before using them for any operation.

Related https://github.com/wso2/product-is/issues/4325

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
