### ISSUE TITLE
[TOML Configus] "NullPointerException" when try to set Primary User store as JDBC

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6141]
Affected version: wso2is-5.9.0-m7
Severity: High
Priority: High
Type: Bug

Using version wso2is-5.9.0-m7, and the try to set Primary User store as JDBC throws this exception:

[2019-08-18 03:57:42,913] ERROR {org.wso2.carbon.core.internal.permission.update.PermissionUpdater} -  Error when updating the permission cache for tenant : -1234
java.lang.NullPointerException
	at org.wso2.carbon.core.internal.permission.update.PermissionUpdater.update(PermissionUpdater.java:72)
	at org.wso2.carbon.core.internal.permission.update.PermissionUpdateServiceComponent.activate(PermissionUpdateServiceComponent.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:915)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:464)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:482)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:515)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:291)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:903)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

Configured Deployment.toml
==========================
[server]
pattern = "DEV"  #possible values, DEV,HA,HA_WITH_ANALYTICS
hostname = "localhost"
node_ip = "127.0.0.1"
 
[super_admin]
username = "admin"
password = "admin"
create_admin_account = true
 
 
[user_store]
type = "database"
TenantManager="org.wso2.carbon.user.core.tenant.JDBCTenantManager"
ReadOnly=false
ReadGroups=true
WriteGroups=true
UsernameJavaRegEx = "^[\\S]{3,30}$"
UsernameJavaScriptRegEx = "^[\\S]{3,30}$"
UsernameJavaRegExViolationErrorMsg = "Username pattern policy violated"
PasswordJavaRegEx = "^[\\S]{5,30}$"
PasswordJavaScriptRegEx="^[\\S]{5,30}$"
PasswordJavaRegExViolationErrorMsg="Password length should be within 5 to 30 characters"
RolenameJavaRegEx="^[\\S]{3,30}$"
RolenameJavaScriptRegEx="^[\\S]{3,30}$"
CaseInsensitiveUsername=false
SCIMEnabled=true
IsBulkImportSupported=false
PasswordDigest="SHA-256"
StoreSaltedPassword=true
MultiAttributeSeparator=","
MaxUserNameListLength="100"
MaxRoleNameListLength="100"
UserRolesCacheEnabled=true
UserNameUniqueAcrossTenants=false
LeadingOrTrailingSpaceAllowedInUserName=false
#connection_url = "ldap://localhost:${Ports.EmbeddedLDAP.LDAPServerPort}"
#connection_name = "uid=admin,ou=system"
#connection_password = "admin"
#base_dn = "dc=wso2,dc=org"      #refers the base dn on which the user and group search bases will be generated
#class ="org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager"
#[realm_manager.properties]
#isCascadeDeleteEnabled=true
#initializeNewClaimManager=true
#[user_store.properties]
 
 
[database.identity_db]
#type = "mysql"         # Infers the local H2 DB connection details for 'DEV' pattern. SHOULD BE CHANGED TO PRODUCTION READY DB FOR PRODUCTION
url = "jdbc:mysql://localhost:3306/IAMtest?useSSL=false"
username = "root"
password = "root"
driver = "com.mysql.jdbc.Driver"
[database.identity_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false
 
[database.shared_db]
#type = "mysql"         # Infers the local DB connection details. SHOULD BE CHANGED TO PRODUCTION READY DB FOR PRODUCTION
url = "jdbc:mysql://localhost:3306/IAMtest?useSSL=false"
username = "root"
password = "root"
driver = "com.mysql.jdbc.Driver"
[database.shared_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false
[keystore.tls]
name = "wso2carbon.jks"
password = "wso2carbon"

====================================

user-mgt.xml
<?xml version="1.0" encoding="UTF-8"?>

<UserManager xmlns:svns="http://org.wso2.securevault/configuration">
   <Realm>
       <Configuration>
           <AddAdmin>true</AddAdmin>
           <AdminRole>admin</AdminRole>
           <AdminUser>
               <UserName>admin</UserName>
               <Password>admin</Password>
           </AdminUser>
           <EveryOneRoleName>everyone</EveryOneRoleName>
 
           <OverrideUsernameClaimFromInternalUsername>true</OverrideUsernameClaimFromInternalUsername>
           
           <Property name="isCascadeDeleteEnabled">true</Property>
           <Property name="initializeNewClaimManager">true</Property>
           <Property name="dataSource">jdbc/SHARED_DB</Property>
       </Configuration>
       <UserStoreManager class="org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager">
           <Property name="IsBulkImportSupported">true</Property>
           <Property name="MaxUserNameListLength">100</Property>
           <Property name="MultiAttributeSeparator">,</Property>
           <Property name="UserNameUniqueAcrossTenants">false</Property>
           <Property name="StoreSaltedPassword">true</Property>
           <Property name="TenantManager">org.wso2.carbon.user.core.tenant.JDBCTenantManager</Property>
           <Property name="CaseInsensitiveUsername">true</Property>
           <Property name="UsernameJavaRegEx">^[\S]{3,30}$</Property>
           <Property name="WriteGroups">true</Property>
           <Property name="RolenameJavaScriptRegEx">^[\S]{3,30}$</Property>
           <Property name="RolenameJavaRegEx">^[\S]{3,30}$</Property>
           <Property name="PasswordJavaRegEx">^[\S]{5,30}$</Property>
           <Property name="ReadGroups">true</Property>
           <Property name="PasswordJavaRegExViolationErrorMsg">Password length should be within 5 to 30 characters</Property>
           <Property name="MaxRoleNameListLength">100</Property>
           <Property name="PasswordJavaScriptRegEx">^[\S]{5,30}$</Property>
           <Property name="UsernameJavaRegExViolationErrorMsg">Username pattern policy violated</Property>
           <Property name="UserRolesCacheEnabled">true</Property>
           <Property name="SCIMEnabled">false</Property>
           <Property name="PasswordDigest">SHA-256</Property>
           <Property name="UsernameJavaScriptRegEx">^[\S]{5,30}$</Property>
           <Property name="ReadOnly">false</Property>
       </UserStoreManager>
 
       <AuthorizationManager class="org.wso2.carbon.user.core.authorization.JDBCAuthorizationManager">
           <Property name="AdminRoleManagementPermissions">/permission</Property>
           <Property name="AuthorizationCacheEnabled">true</Property>
           <Property name="GetAllRolesOfUserEnabled">false</Property>
       </AuthorizationManager>
   </Realm>
</UserManager>

**Comment by senthalan** [comment]
Not reproduced with the kernel alpha 3 pack
