### ISSUE TITLE
OIDC Federation Fails with CertificateException

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#6147]
Configure OIDC federation with another Identity Server and import that server's certificate to primary IS client-trustore.jks. Authentication is successful but after that it fails with the following error.

Caused by: java.security.cert.CertificateException: No name matching localhost found
	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:221)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:95)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:200)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
	... 78 more

**Comment by piraveena** [comment]
This was tested by having primary IS in openstack instance and federated IDP in local machine. The hostname of primary IS is changed. In the primary IS, the token endpoint is configured as http://localhost:9443/oauth/token. when the primary is trying to send token request as a post request to http://localhost:9443/oauth/token endpoint, it calls its localhost's token endpoint instead of calling federated IDP's token endpoint with a cert with different CN name
