### ISSUE TITLE
Error creating app from dcr request when authenticating from user in secondary userstore[DB2]

### ISSUE THREAD

**Issue by janakamarasena** [wso2/product-is#6157]
Error creating app from dcr request when authenticating from user in secondary userstore(DB2).

IS590-m7
authenticating user in DB2 file-based jdbc secondary userstore

```
curl -k -X POST -H "Authorization: Basic U0VDT05EQVJZL2phbmFrQHdzbzIuY29tOmFkbWlu" -H "Content-Type: application/json" -d '{ "client_name": "application_test1", "grant_types": ["password"], "ext_param_client_id":"provided_client_id004", "ext_param_client_secret":"provided_client_secret0001" }' "https://localhost:9443/t/wso2.com/api/identity/oauth2/dcr/v1.1/register" -v
```

Error

```
[2019-08-19 21:04:47,357] SECONDARY/janak@wso2.com [1] [IS]ERROR {org.wso2.carbon.identity.oauth.OAuthUtil} -  Error while retrieving the app information using consumerKey: provided_client_id0045
[2019-08-19 21:04:47,360] SECONDARY/janak@wso2.com [1] [IS]ERROR {org.wso2.carbon.identity.oauth.dcr.service.DCRMService} -  Error while retrieving oauth application with client id: provided_client_id0045
[2019-08-19 21:04:47,510] SECONDARY/janak@wso2.com [1] [IS]ERROR {org.wso2.carbon.identity.oauth2.dcr.endpoint.impl.RegisterApiServiceImpl} -  Internal Server Error
org.wso2.carbon.identity.oauth.dcr.exception.DCRMServerException: Error occurred while updating service provider application_test21
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:103)
	at org.wso2.carbon.identity.oauth.dcr.util.DCRMUtils.generateServerException(DCRMUtils.java:118)
	at org.wso2.carbon.identity.oauth.dcr.service.DCRMService.updateServiceProvider(DCRMService.java:451)
	at org.wso2.carbon.identity.oauth.dcr.service.DCRMService.updateServiceProviderWithOAuthAppDetails(DCRMService.java:329)
	at org.wso2.carbon.identity.oauth.dcr.service.DCRMService.createOAuthApplication(DCRMService.java:286)
	at org.wso2.carbon.identity.oauth.dcr.service.DCRMService.registerApplication(DCRMService.java:121)
	at org.wso2.carbon.identity.oauth2.dcr.endpoint.impl.RegisterApiServiceImpl.registerApplication(RegisterApiServiceImpl.java:76)
	at org.wso2.carbon.identity.oauth2.dcr.endpoint.RegisterApi.registerApplication(RegisterApi.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:410)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:101)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:92)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:93)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:63)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:112)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1780)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1739)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error occurred while updating the application: application_test21. Error while assigning application role: Application/application_test21 to the user: janak
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.updateApplication(ApplicationManagementServiceImpl.java:463)
	at org.wso2.carbon.identity.oauth.dcr.service.DCRMService.updateServiceProvider(DCRMService.java:449)
	... 58 more
Caused by: org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error while assigning application role: Application/application_test21 to the user: janak
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.assignApplicationRole(ApplicationManagementServiceImpl.java:1747)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.updateApplication(ApplicationManagementServiceImpl.java:436)
	... 59 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while updating hybrid role list of user : janak
	at org.wso2.carbon.user.core.hybrid.HybridRoleManager.updateHybridRoleListOfUser(HybridRoleManager.java:623)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.updateRoleListOfUserInternal(AbstractUserStoreManager.java:3394)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.access$300(AbstractUserStoreManager.java:92)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$6.run(AbstractUserStoreManager.java:3237)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$6.run(AbstractUserStoreManager.java:3234)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.updateRoleListOfUser(AbstractUserStoreManager.java:3234)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.assignApplicationRole(ApplicationManagementServiceImpl.java:1740)
	... 60 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Using sql : INSERT INTO UM_HYBRID_USER_ROLE (UM_ROLE_ID, UM_USER_NAME, UM_TENANT_ID, UM_DOMAIN_ID) VALUES ((SELECT UM_ID FROM UM_HYBRID_ROLE WHERE UM_ROLE_NAME=? AND UM_TENANT_ID=?), ?, ?,(SELECT UM_DOMAIN_ID FROM UM_DOMAIN WHERE UM_TENANT_ID=? AND UM_DOMAIN_NAME=?)) [jcc][t4][102][10040][4.25.13] Batch failure.  The batch was submitted, but at least one exception occurred on an individual member of the batch.
Use getNextException() to retrieve the exceptions for specific batched elements. ERRORCODE=-4229, SQLSTATE=null
	at org.wso2.carbon.user.core.util.DatabaseUtil.udpateUserRoleMappingInBatchMode(DatabaseUtil.java:848)
	at org.wso2.carbon.user.core.hybrid.HybridRoleManager.updateHybridRoleListOfUser(HybridRoleManager.java:613)
	... 67 more
Caused by: com.ibm.db2.jcc.am.BatchUpdateException: [jcc][t4][102][10040][4.25.13] Batch failure.  The batch was submitted, but at least one exception occurred on an individual member of the batch.
Use getNextException() to retrieve the exceptions for specific batched elements. ERRORCODE=-4229, SQLSTATE=null
	at com.ibm.db2.jcc.am.b6.a(b6.java:502)
	at com.ibm.db2.jcc.am.Agent.endBatchedReadChain(Agent.java:434)
	at com.ibm.db2.jcc.am.k4.a(k4.java:5452)
	at com.ibm.db2.jcc.am.k4.c(k4.java:5026)
	at com.ibm.db2.jcc.am.k4.executeBatch(k4.java:3058)
	at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy24.executeBatch(Unknown Source)
	at org.wso2.carbon.user.core.util.DatabaseUtil.udpateUserRoleMappingInBatchMode(DatabaseUtil.java:837)
	... 68 more
```

Seems like the app is not created so the role is not available. 
When trying to add an already created application . role to the same user it works.

**Comment by janakamarasena** [comment]
Cannot reproduce. Tested with DB2 and IS590-alpha.
