### ISSUE TITLE
Error while retrieving data from cache in tenant mode.

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#6277]
Following stack trace can be visible whenever we try to retrieve data from the cache. (Tested in the SAML flow) and operation will be **not successful**. 
How to reproduce:
1. Configure SAML service provider (Travelocity) with single logout.
2. Login.
3. Try to logout.

Following stack trace will be visible in the logs. 

`TID: [-1234] [] [2019-08-31 07:14:21,625] [470764a7-83c2-4d1c-ae53-acafaa1a05ed] ERROR {org.wso2.carbon.identity.sso.saml.processors.SPInitLogoutRequestProcessor} - An error occurred while retrieving the application certificate for file based SAML service provider with the issuer name 'travelocity.com:urn:sp:qualifier:jayanga_sp_travelocity'. The service provider will NOT be loaded. org.wso2.carbon.identity.base.IdentityException: Error while reading Service Provider configurations
	at org.wso2.carbon.identity.sso.saml.processors.SPInitLogoutRequestProcessor.getServiceProviderConfig(SPInitLogoutRequestProcessor.java:257)
	at org.wso2.carbon.identity.sso.saml.processors.SPInitLogoutRequestProcessor.setX509Certificate(SPInitLogoutRequestProcessor.java:186)
	at org.wso2.carbon.identity.sso.saml.processors.SPInitLogoutRequestProcessor.process(SPInitLogoutRequestProcessor.java:143)
	at org.wso2.carbon.identity.sso.saml.SAMLSSOService.validateSPInitSSORequest(SAMLSSOService.java:108)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleSPInitSSO(SAMLSSOProviderServlet.java:716)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleRequest(SAMLSSOProviderServlet.java:274)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.doPost(SAMLSSOProviderServlet.java:156)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:72)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:112)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.SecurityException: Illegal access attempt to cache ] owned by tenant {[wso2.com],[1]} by tenant {[wso2.com],[-1234]}
	at org.wso2.carbon.caching.impl.Util.checkAccess(Util.java:46)
	at org.wso2.carbon.caching.impl.CarbonCacheManager.getCache(CarbonCacheManager.java:115)
	at org.wso2.carbon.registry.core.utils.RegistryUtils.getResourceCache(RegistryUtils.java:288)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.getDistributedCache(CacheBackedRegistry.java:76)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.getCache(CacheBackedRegistry.java:285)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.resourceExists(CacheBackedRegistry.java:372)
	at org.wso2.carbon.registry.core.session.UserRegistry.resourceExistsInternal(UserRegistry.java:774)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$800(UserRegistry.java:61)
	at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:757)
	at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:754)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.resourceExists(UserRegistry.java:754)
	at org.wso2.carbon.identity.core.dao.SAMLSSOServiceProviderDAO.getServiceProvider(SAMLSSOServiceProviderDAO.java:556)
	at org.wso2.carbon.identity.core.persistence.IdentityPersistenceManager.getServiceProvider(IdentityPersistenceManager.java:273)
	at org.wso2.carbon.identity.sso.saml.processors.SPInitLogoutRequestProcessor.getServiceProviderConfig(SPInitLogoutRequestProcessor.java:253)
	... 58 more`

**Comment by senthalan** [comment]
The particular line which added the tenant domain to the carbon context is removed with https://github.com/wso2-extensions/identity-inbound-auth-saml/pull/250/files#diff-b2923a6c20c2ec60fb4ca8e6ff085b77L219. This issue didn't reproduce after this fix
