### ISSUE TITLE
Error while outbound provisioning to external IDP when IS is configured with a custom keystore

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#6285]
Step to reproduce.

- Generate a new keystore for IS
- Setup outbound provisioning pointing to a different IS as in this [doc.](https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/outbound-provisioning-with-scim/)
- provisioning fails and getting below error.

`TID: [1] [] [2019-08-31 09:58:27,744] [13f7f8e6-cdf0-4112-9617-e473e5edcda5] ERROR {org.wso2.carbon.identity.provisioning.ProvisioningThread} -  Provisioning for Entity aysh_2_tn For operation = POST org.wso2.carbon.identity.provisioning.IdentityProvisioningException: Error while creating the user
	at org.wso2.carbon.identity.provisioning.connector.scim.SCIMProvisioningConnector.createUser(SCIMProvisioningConnector.java:281)
	at org.wso2.carbon.identity.provisioning.connector.scim.SCIMProvisioningConnector.provision(SCIMProvisioningConnector.java:109)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:68)
	at org.wso2.carbon.identity.provisioning.ProvisioningThread.call(ProvisioningThread.java:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.identity.scim.common.utils.IdentitySCIMException: Error in invoking provisioning operation for the user with id: admin
	at org.wso2.carbon.identity.scim.common.impl.ProvisioningClient.provisionCreateUser(ProvisioningClient.java:172)
	at org.wso2.carbon.identity.provisioning.connector.scim.SCIMProvisioningConnector.createUser(SCIMProvisioningConnector.java:257)
	... 7 more
Caused by: javax.net.ssl.SSLPeerUnverifiedException: SSL peer failed hostname validation for name: null
	at org.opensaml.ws.soap.client.http.TLSProtocolSocketFactory.verifyHostname(TLSProtocolSocketFactory.java:233)
	at org.opensaml.ws.soap.client.http.TLSProtocolSocketFactory.createSocket(TLSProtocolSocketFactory.java:186)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at org.wso2.carbon.identity.scim.common.impl.ProvisioningClient.provisionCreateUser(ProvisioningClient.java:146)
	... 8 more`

- note that public certificate of the remote idp is imported to the client-trustore.jks when the issue is reproducing

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
