### ISSUE TITLE
Getting Exception : SAML2 IdP Initiated Single Logout with WSO2 Identity Server Tenant

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#6336]
Tested environment:
IS 5.9.0 Alpha, Oracle12c

Complexity: Low
Severity; Medium
Priority : Medium

Steps :
1. Created SAML service provider in tenant mode (wso2.com) and Enable IDP initiated SLO : My SLO URL is as follows : http://localhost:8080/travelocity.com/slo

2. **Select Logout Method as "Front-Channel Logout (HTTP Redirect Binding)"**

2. Login to travelocity  

3.Open up a new tab in same browser
4. Do the IDP initiated SLO - https://localhost:9443/samlsso?slo=true&spEntityID=travelocity.com&tenantDomain=wso2.com

Exception :
ERROR {org.wso2.carbon.core.util.KeyStoreManager} - Error loading the private key from the key store : wso2-com.jks
[2019-09-01 17:53:51,494] [5a5468ef-501d-41cd-b04e-b979dba4e075] ERROR {org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet} - Error when processing the authentication request! org.wso2.carbon.identity.base.IdentityException: Error retrieving private key and the certificate for tenant wso2.com
	at org.wso2.carbon.identity.sso.saml.builders.X509CredentialImpl.initCredentialForTenant(X509CredentialImpl.java:214)
	at org.wso2.carbon.identity.sso.saml.builders.X509CredentialImpl.<init>(X509CredentialImpl.java:102)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.createHttpQueryStringForRedirect(SAMLSSOProviderServlet.java:1925)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.doFrontChannelSLO(SAMLSSOProviderServlet.java:1800)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.sendLogoutRequestToSessionParticipant(SAMLSSOProviderServlet.java:1268)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleLogoutResponseFromFramework(SAMLSSOProviderServlet.java:1205)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleRequest(SAMLSSOProviderServlet.java:255)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.doGet(SAMLSSOProviderServlet.java:143)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.sendRequestToFramework(SAMLSSOProviderServlet.java:1610)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.sendToFrameworkForLogout(SAMLSSOProviderServlet.java:905)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleIdPInitSSO(SAMLSSOProviderServlet.java:639)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleRequest(SAMLSSOProviderServlet.java:272)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.doGet(SAMLSSOProviderServlet.java:143)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:72)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:112)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.SecurityException: Error loading the private key from the key store : wso2-com.jks
	at org.wso2.carbon.core.util.KeyStoreManager.getPrivateKey(KeyStoreManager.java:208)
	at org.wso2.carbon.identity.sso.saml.builders.X509CredentialImpl.initCredentialForTenant(X509CredentialImpl.java:210)
	... 64 more
Caused by: java.lang.SecurityException: Illegal access attempt to cache ] owned by tenant {[wso2.com],[1]} by tenant {[wso2.com],[-1234]}
	at org.wso2.carbon.caching.impl.Util.checkAccess(Util.java:46)
	at org.wso2.carbon.caching.impl.CarbonCacheManager.getCache(CarbonCacheManager.java:115)
	at org.wso2.carbon.registry.core.utils.RegistryUtils.getResourceCache(RegistryUtils.java:288)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.getDistributedCache(CacheBackedRegistry.java:76)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.getCache(CacheBackedRegistry.java:285)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.resourceExists(CacheBackedRegistry.java:372)
	at org.wso2.carbon.registry.core.session.UserRegistry.resourceExistsInternal(UserRegistry.java:774)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$800(UserRegistry.java:61)
	at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:757)
	at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:754)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.resourceExists(UserRegistry.java:754)
	at org.wso2.carbon.core.util.KeyStoreManager.getPrivateKey(KeyStoreManager.java:179)
	... 65 more

**Comment by dewniMW** [comment]
Tested SAML2 IdP Initiated Single Logout with WSO2 Identity Server Tenant and couldn't reproduce the above issue. Please follow the blog [1] as testing Front-Channel Logout with travelocity webapp is not recommended.
[1] https://medium.com/@swettasinghe23/configuring-saml2-front-channel-logout-on-wso2-identity-server-13ce4cf3dc38
