### ISSUE TITLE
Unable to update service provider when owner does not exist

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#6639]
**Steps to reproduce**
1. Create a service provider with userA
2. Assign new application role to userB
3. Delete userA (application owner)
4. Login as userB and try to update the above sp
5. Following stack trace is thrown and sp update fails with an error message with the same text as following.

```ERROR {org.wso2.carbon.identity.application.mgt.ApplicationManagementAdminService} -  Error while updating application: myServiceProvider for tenant: carbon.super 
org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error occurred while updating the application: myServiceProvider. User validation failed for owner update in the application: myServiceProvider
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.updateApplication(ApplicationManagementServiceImpl.java:457)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementAdminService.updateApplication(ApplicationManagementAdminService.java:238)
	at sun.reflect.GeneratedMethodAccessor489.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

For now, we have two workarounds to resolve this issue.
1. Update the sp owner using admin service IdentityApplicationManagementService.updateApplication()
2. Update the SP_APP table directly and change the owner

**Comment by thanujalk** [comment]
This can be reproduced in 5.11.0-beta2 pack.
