### ISSUE TITLE
Error when uploading IdP meta data downloaded from a service provider

### ISSUE THREAD

**Issue by NatashaWso2** [wso2/product-is#6706]
**Scenario**
1) Manually register a service provider and configure it with SAML2 web SSO
2) Download the IdP metadata after configuring
3) Create a new service provider
4) Upload the downloaded metadata file in the previous step when configuring SAML2 web SSO gives the following error: **Metadata uploading failed. Error while uploading the service provider**

I have attached the metadata file downloaded (The file is with the txt extension since xml files cannot be uploaded : [metadata.txt](https://github.com/wso2/product-is/files/3762478/metadata.txt)

**Error**
`org.wso2.carbon.identity.sso.saml.ui.exception.IdentitySAML2SSOUiException: Error while uploading the service provider
	at org.wso2.carbon.identity.sso.saml.ui.client.SAMLSSOConfigServiceClient.uploadServiceProvider(SAMLSSOConfigServiceClient.java:97)
	at org.wso2.carbon.identity.sso.saml.ui.client.SamlSPMetadataUploadExecutor.execute(SamlSPMetadataUploadExecutor.java:88)
	at org.wso2.carbon.ui.transports.fileupload.AbstractFileUploadExecutor.executeGeneric(AbstractFileUploadExecutor.java:104)
	at org.wso2.carbon.ui.transports.fileupload.FileUploadExecutorManager$CarbonXmlFileUploadExecHandler.execute(FileUploadExecutorManager.java:436)
	at org.wso2.carbon.ui.transports.fileupload.FileUploadExecutorManager$FileUploadExecutionHandlerManager.startExec(FileUploadExecutorManager.java:320)
	at org.wso2.carbon.ui.transports.fileupload.FileUploadExecutorManager.execute(FileUploadExecutorManager.java:127)
	at org.wso2.carbon.ui.transports.FileUploadServlet.doPost(FileUploadServlet.java:57)`

`Caused by: org.apache.axis2.AxisFault: org.opensaml.saml2.metadata.impl.IDPSSODescriptorImpl cannot be cast to org.opensaml.saml2.metadata.SPSSODescriptor
	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:382)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:457)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.wso2.carbon.identity.sso.saml.stub.IdentitySAMLSSOConfigServiceStub.uploadRPServiceProvider(IdentitySAMLSSOConfigServiceStub.java:3033)
	at org.wso2.carbon.identity.sso.saml.ui.client.SAMLSSOConfigServiceClient.uploadServiceProvider(SAMLSSOConfigServiceClient.java:95)`

**Comment by omindu** [comment]
Hi Natasha,

IDP metadata exports SAML IDP configurations of identity server. This metadata is used when configuring IS as a SAML IDP in a Service Provider. Therefore, the IDP metadata cannot be uploaded when configuring a service provider.

IS doesn't have the capability to export SP metadata as of now.

**Comment by johannnallathamby** [comment]
Hi Omindu,

To be clear we can download SAML metadata in the SAML service provider section of a registered service provider. We can download SAML metadata in Resident IdP as well. What is the difference between the two?

**Comment by omindu** [comment]
Hi Johann,

This is for UX, so the IdP metadata can be downloaded during SP creation rather than going to resident IdP settings. There's no difference.

**Comment by darshanasbg** [comment]
Closing as answered.
