### ISSUE TITLE
NPE during logout when SSO login to the management console is enabled

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#6712]
This issue happens only if we update management console configs after logging into it and then logout from the management console.

Found in IS 5.8.0

Steps to reproduce:

- Enable the SSO login to the management console in latest WUM updated IS pack (IS-5.8.0)
- Create the Service provider and configure it as the SAML2 Web SSO configured SP in inbound authentication configurations.
- Enable the "Signature Validation in Authentication Requests and Logout Requests" feature in SAML2 Web SSO configurations.
- log out from the management console
- login to the management console again.
- Disable the "Signature Validation in Authentication Requests and Logout Requests" feature in SAML2 Web SSO configurations.
- logout from the management console 

The following error can be observed in the carbon console.

```
[2019-10-22 10:38:15,915] DEBUG {org.wso2.carbon.identity.sso.saml.util.SAMLSSOUtil} -  Error while validating XML signature.
java.lang.NullPointerException
	at org.wso2.carbon.identity.sso.saml.builders.X509CredentialImpl.<init>(X509CredentialImpl.java:258)
	at org.wso2.carbon.identity.sso.saml.util.SAMLSSOUtil.validateXMLSignature(SAMLSSOUtil.java:1235)
	at org.wso2.carbon.identity.sso.saml.util.SAMLSSOUtil.validateLogoutRequestSignature(SAMLSSOUtil.java:1061)
	at org.wso2.carbon.identity.sso.saml.processors.SPInitLogoutRequestProcessor.validateSignature(SPInitLogoutRequestProcessor.java:461)
	at org.wso2.carbon.identity.sso.saml.processors.SPInitLogoutRequestProcessor.process(SPInitLogoutRequestProcessor.java:144)
	at org.wso2.carbon.identity.sso.saml.SAMLSSOService.validateSPInitSSORequest(SAMLSSOService.java:108)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleSPInitSSO(SAMLSSOProviderServlet.java:712)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleRequest(SAMLSSOProviderServlet.java:270)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.doPost(SAMLSSOProviderServlet.java:156)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.A
```

This is because, during the authentication flow, the serviceproviderDO object is persisted in the SAMLSSOParticipantCache against the sessionIndex. So when we update the managementconsole service provider in the middle, those changes in the serviceproviderDO obeject will be persisted in the registry object and that will not be reflected in the DO object cache. So during logout flow, the changes in the cache will be taken and the DO object in the cache does not have the changes that happened in the SP after the logoin flow.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
