### ISSUE TITLE
JWT not returned when Con App Key violation happens

### ISSUE THREAD

**Issue by Manukam** [wso2/product-is#6942]
Scenario - 
When using self-contained access token (JWT) and when CON_APP_KEY violation happens, a JWT is not returned but a GUID is returned.
A JWT is not generated after the con app key recovery process takes place.

Suggested labels: wso2is-km-5.5.0
Type: Bug

**Comment by isharac** [comment]
While testing the above fix encountered below error.

[2020-01-29 14:53:41,880] ERROR - OAuth2Service Error occurred while issuing the access token for Client ID : fhLWBOgc_FvAd9sWfQtwMzq57l0a, User ID null, Scope : [] and Grant Type : client_credentials
org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: Error occurred while storing new access token : eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlpqUm1ZVE13TlRKak9XVTVNbUl6TWpnek5ESTNZMkl5TW1JeVkyRXpNamRoWmpWaU1qYzBaZz09In0.eyJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJiYWNrZW5kSnd0IjoiZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKU1V6STFOaUlzSW5nMWRDSTZJbHBxVW0xWlZFMTNUbFJLYWs5WFZUVk5iVWw2VFdwbmVrNUVTVE5aTWtsNVRXMUplVmt5UlhwTmFtUm9XbXBXYVUxcVl6QmFaejA5SW4wPS5leUpvZEhSd09sd3ZYQzkzYzI4eUxtOXlaMXd2WTJ4aGFXMXpYQzkxYzJWeWJtRnRaU0k2SW1Ga2JXbHVJaXdpYUhSMGNEcGNMMXd2ZDNOdk1pNXZjbWRjTDJOc1lXbHRjMXd2Y205c1pTSTZXeUpCY0hCc2FXTmhkR2x2Ymx3dllXUnRhVzVmWVdSdGFXNWZjSFZpYkdsemFHVnlJaXdpUVhCd2JHbGpZWFJwYjI1Y0wyRmtiV2x1WDNSbGMzUmZVRkpQUkZWRFZFbFBUaUlzSWtsdWRHVnlibUZzWEM5bGRtVnllVzl1WlNJc0ltRmtiV2x1SWl3aVFYQndiR2xqWVhScGIyNWNMMkZrYldsdVgyNXZaR1V5WVhCd1gxQlNUMFJWUTFSSlQwNGlMQ0pKYm5SbGNtNWhiRnd2YzNWaWMyTnlhV0psY2lJc0lrbHVkR1Z5Ym1Gc1hDOWpjbVZoZEc5eUlpd2lRWEJ3YkdsallYUnBiMjVjTDJGa2JXbHVYMFJsWm1GMWJIUkJjSEJzYVdOaGRHbHZibDlRVWs5RVZVTlVTVTlPSWl3aVFYQndiR2xqWVhScGIyNWNMMkZrYldsdVgyRmtiV2x1WDNOMGIzSmxJaXdpUVhCd2JHbGpZWFJwYjI1Y0wyRmtiV2x1WDJwM2RHRndjRjlRVWs5RVZVTlVTVTlPSWl3aVNXNTBaWEp1WVd4Y0wzQjFZbXhwYzJobGNpSXNJa2x1ZEdWeWJtRnNYQzloYm1Gc2VYUnBZM01pTENKQmNIQnNhV05oZEdsdmJsd3ZZV1J0YVc1ZmJtVjNZWEJ3WDFCU1QwUlZRMVJKVDA0aVhTd2lhSFIwY0RwY0wxd3ZkM052TWk1dmNtZGNMMk5zWVdsdGMxd3ZZWEJ3YkdsallYUnBiMjUwYVdWeUlqb2lNVEJRWlhKTmFXNGlMQ0pvZEhSd09sd3ZYQzkzYzI4eUxtOXlaMXd2WTJ4aGFXMXpYQzl6ZFdKelkzSnBZbVZ5SWpvaVlXUnRhVzRpTENKb2RIUndPbHd2WEM5M2MyOHlMbTl5WjF3dlkyeGhhVzF6WEM5clpYbDBlWEJsSWpvaVVGSlBSRlZEVkVsUFRpSXNJbWx6Y3lJNkluZHpiekl1YjNKblhDOXdjbTlrZFdOMGMxd3ZZVzBpTENKb2RIUndPbHd2WEM5M2MyOHlMbTl5WjF3dlkyeGhhVzF6WEM5aGNIQnNhV05oZEdsdmJtNWhiV1VpT2lKcWQzUmhjSEFpTENKb2RIUndPbHd2WEM5M2MyOHlMbTl5WjF3dlkyeGhhVzF6WEM5bGJtUjFjMlZ5SWpvaVlXUnRhVzVBWTJGeVltOXVMbk4xY0dWeUlpd2lhSFIwY0RwY0wxd3ZkM052TWk1dmNtZGNMMk5zWVdsdGMxd3ZaVzVrZFhObGNsUmxibUZ1ZEVsa0lqb2lMVEV5TXpRaUxDSmxlSEFpT2pFMU9EQXlPVEEzTWpFc0ltaDBkSEE2WEM5Y0wzZHpiekl1YjNKblhDOWpiR0ZwYlhOY0wyRndjR3hwWTJGMGFXOXVhV1FpT2lJMElpd2lhSFIwY0RwY0wxd3ZkM052TWk1dmNtZGNMMk5zWVdsdGMxd3ZZWEJ3YkdsallYUnBiMjVWVlVsa0lqb2lOVFV4TmpSaU5UUXRPVGhrWWkwMFlqSmhMV0k0TjJNdE56UXhaakJsTldFMVpUVTRJbjA9Lmh6WkdfOExteXAxQUhvZTBoWG9NNWFhNXRRWTR0WFEyek8wd2Nwa0ZEYXBrVHBraThhbjc1Q0JPNnhXMmg0QTBxa0NJZ0hsY3NfLXJJdnFIeVFDc0RTeE9ZMjdEUVQ1S19YTkw3b0FoQkZ2cXBONHNBbEl3R0Q5ZV92aVhFSEw1TE5iQzFsV1N3SDI2U0xHdU83eTBIcF9CVmcxVmRka0I3VWRKSTNsZVJtWFpiRnhQUDBRQVNubzdraUE2SGN1dk1tMElxR25waUk3MXVWNUsyS0JHTDNzRkYwd08zUFhmRGp5c1pkb1NybURyY0VjOE9LNU1wMFpsYm1VWjVDT1lPRHcyZXZ1NF91YVozejhkbmFGdWJWWi1pNFRGNnhZeUxpdmF2dHhFRm84WkZXSzVBamQyODJSUU9ZcDY4RHM2ZE9WckxJNWRaelV1UDd3WWpGeUxwUT09IiwiaXNzIjoiaHR0cHM6XC9cL2xvY2FsaG9zdDo5NDQzXC9vYXV0aDJcL3Rva2VuIiwidGllckluZm8iOnt9LCJrZXl0eXBlIjoiUFJPRFVDVElPTiIsInN1YnNjcmliZWRBUElzIjpbXSwiYXVkIjoiaHR0cDpcL1wvb3JnLndzbzIuYXBpbWd0XC9nYXRld2F5IiwiYXBwbGljYXRpb24iOnsib3duZXIiOiJhZG1pbiIsInRpZXIiOiIxMFBlck1pbiIsIm5hbWUiOiJqd3RhcHAiLCJpZCI6NCwidXVpZCI6bnVsbH0sInNjb3BlIjoiYW1fYXBwbGljYXRpb25fc2NvcGUgZGVmYXVsdCIsImNvbnN1bWVyS2V5IjoiZmhMV0JPZ2NfRnZBZDlzV2ZRdHdNenE1N2wwYSIsImV4cCI6MTU4MDI4OTgzMSwiaWF0IjoxNTgwMjg5ODIxLCJqdGkiOiJkZjViZTU3YS00NjY2LTQ0MWQtOGFhYS1kN2I1MGJjN2Y2OWYifQ.JEIztse6amOil5OwYtOM_5IrJ3fc72SCiZt-8VBHvFoxlfUcysv_5OSSNVb3UmviQoykv7tL_rF_fOc4NuOlJ2Vc8wksc_b1MM7dQcav2NhMz1MN7KRbb8cOSESlF2xWTuuHSYG_BhZ1OD6O2HgDvq51yUo0MFsxtNmAszr86-oa4xjcnTW9B2KDFslvWCmUa8o-HsKtRLTtckexCGtNb0MAv5IDkek4blLfa_KI53SsD1pBOguqcYcYtCT_canEVGt7OCbM8dV93_4UYwKyrkhtzYy6O1whlijnNwNsU3TC5rE1irVbmqRPsnSA53PLnHOtT5A0lC7yKB6eRUCGsg
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.storeAccessToken(AbstractAuthorizationGrantHandler.java:294) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.persistAccessTokenInDB(AbstractAuthorizationGrantHandler.java:395) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.generateNewAccessTokenResponse(AbstractAuthorizationGrantHandler.java:326) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.issue(AbstractAuthorizationGrantHandler.java:167) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.issue(AccessTokenIssuer.java:276) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	at org.wso2.carbon.identity.oauth2.OAuth2Service.issueAccessToken(OAuth2Service.java:244) [org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:305) [classes/:?]
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:91) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103) [cxf-rt-frontend-jaxrs-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-core-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276) [cxf-rt-transports-http-3.2.8.jar:3.2.8]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.webapp.mgt.filter.AuthorizationHeaderFilter.doFilter(AuthorizationHeaderFilter.java:85) [org.wso2.carbon.webapp.mgt_4.9.11.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53) [org.wso2.carbon.ui_4.5.1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80) [org.wso2.carbon.identity.context.rewrite.valve_1.3.6.jar:?]
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100) [org.wso2.carbon.identity.authz.valve_1.3.6.jar:?]
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74) [org.wso2.carbon.identity.auth.valve_1.3.6.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [tomcat_9.0.22.wso2v1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat_9.0.22.wso2v1.jar:?]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.22.wso2v1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.22.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: An rolling back transactions error occurred while trying to recover 'CON_APP_KEY' constraint violation . 
	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.recoverFromConAppKeyConstraintViolation(AccessTokenDAOImpl.java:1902) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:238) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:97) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:299) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.storeAccessToken(AbstractAuthorizationGrantHandler.java:291) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	... 68 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Can't call rollback when autocommit=true
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4556) ~[mysql-connector-java-5.1.47.jar:5.1.47]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at org.apache.tomcat.jdbc.pool.interceptor.ConnectionState.invoke(ConnectionState.java:152) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:40) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81) ~[jdbc-pool_9.0.16.wso2v1.jar:?]
	at com.sun.proxy.$Proxy48.rollback(Unknown Source) ~[?:?]
	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.recoverFromConAppKeyConstraintViolation(AccessTokenDAOImpl.java:1899) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:238) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:97) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:299) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.storeAccessToken(AbstractAuthorizationGrantHandler.java:291) ~[org.wso2.carbon.identity.oauth_6.2.25.jar:?]
	... 68 more

**Comment by madurangasiriwardena** [comment]
The above issue is reported in [here](https://github.com/wso2/product-is/issues/7421).
