### ISSUE TITLE
Issue when running the IS migration client in IS-as-KM for 5.5 to 5.9 migration

### ISSUE THREAD

**Issue by npamudika** [wso2/product-is#7024]
Got the following issue, when running the IS-5.9.0 migration client in API-M 2.2.0 with IS-as-KM 5.5.0 to API-M 3.0.0 with IS-as-KM 5.9.0 migration setup.

```
[2019-12-05 11:53:00,025] []  INFO {org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator} -  WSO2 Product Migration Service Task : Started to migrate OIDC scopes
[2019-12-05 11:53:00,079] [] ERROR {org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator} -  WSO2 Product Migration Service Task : Error while obtaining registry collection from registry path:/oidc org.wso2.carbon.registry.core.exceptions.ResourceNotFoundException: Resource does not exist at path /_system/config/oidc
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.get(MountHandler.java:449)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.get(HandlerManager.java:2446)
	at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.get(UserDefinedHandlerManager.java:199)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.get(HandlerLifecycleManager.java:915)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.get(EmbeddedRegistry.java:512)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.getGhostResourceFromCache(CacheBackedRegistry.java:225)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.get(CacheBackedRegistry.java:198)
	at org.wso2.carbon.registry.core.session.UserRegistry.getInternal(UserRegistry.java:617)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$400(UserRegistry.java:61)
	at org.wso2.carbon.registry.core.session.UserRegistry$5.run(UserRegistry.java:597)
	at org.wso2.carbon.registry.core.session.UserRegistry$5.run(UserRegistry.java:594)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.get(UserRegistry.java:594)
	at org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator.getOIDCScopeProperties(OIDCScopeDataMigrator.java:143)
	at org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator.migrateOIDCScopes(OIDCScopeDataMigrator.java:77)
	at org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator.migrate(OIDCScopeDataMigrator.java:69)
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:42)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:83)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
[2019-12-05 11:53:00,093] [] ERROR {org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator} -  WSO2 Product Migration Service Task : OIDC scope resource cannot be found at /oidc for tenantDomain: carbon.super
[2019-12-05 11:53:00,285] []  INFO {org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator} -  WSO2 Product Migration Service Task : Started to migrate OIDC scopes for tenant: wso2.com
[2019-12-05 11:53:00,346] []  INFO {org.wso2.carbon.registry.core.internal.RegistryCoreServiceComponent} - Tenant 1 is not initialized correctly. Hence initializing the tenant registry
[2019-12-05 11:53:00,432] []  INFO {org.wso2.carbon.registry.core.jdbc.EmbeddedRegistryService} - Connected to mount at govregistry in 0ms
[2019-12-05 11:53:00,468] []  INFO {org.wso2.carbon.registry.core.jdbc.EmbeddedRegistryService} - Connected to mount at configregistry in 0ms
[2019-12-05 11:53:00,513] [] ERROR {org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator} -  WSO2 Product Migration Service Task : Error while obtaining registry collection from registry path:/oidc org.wso2.carbon.registry.core.exceptions.ResourceNotFoundException: Resource does not exist at path /_system/config/oidc
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.get(MountHandler.java:449)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.get(HandlerManager.java:2446)
	at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.get(UserDefinedHandlerManager.java:199)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.get(HandlerLifecycleManager.java:915)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.get(EmbeddedRegistry.java:512)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.getGhostResourceFromCache(CacheBackedRegistry.java:225)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.get(CacheBackedRegistry.java:198)
	at org.wso2.carbon.registry.core.session.UserRegistry.getInternal(UserRegistry.java:617)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$400(UserRegistry.java:61)
	at org.wso2.carbon.registry.core.session.UserRegistry$5.run(UserRegistry.java:597)
	at org.wso2.carbon.registry.core.session.UserRegistry$5.run(UserRegistry.java:594)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.get(UserRegistry.java:594)
	at org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator.getOIDCScopeProperties(OIDCScopeDataMigrator.java:143)
	at org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator.migrateOIDCScopes(OIDCScopeDataMigrator.java:89)
	at org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator.migrate(OIDCScopeDataMigrator.java:69)
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:42)
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:83)
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
[2019-12-05 11:53:00,518] [] ERROR {org.wso2.carbon.is.migration.service.v570.migrator.OIDCScopeDataMigrator} -  WSO2 Product Migration Service Task : OIDC scope resource cannot be found at /oidc for tenantDomain: wso2.com
```
Only the scopes related to super tenant have been added in the IDN_OIDC_SCOPE table as below.

![db](https://user-images.githubusercontent.com/8363838/70233103-ec401a00-1783-11ea-946b-c054c59cdc72.png)

**Comment by npamudika** [comment]
Observed the same error while doing the **5.3.0 to 5.9.0** migration for the IS-as-KM using the DB2 databases.

**Comment by JKAUSHALYA** [comment]
This issue is occurring due to default scopes are missing in the "/_system/config/oidc" location. For tenant other than the super tenant this resource is created whenever the tenant is getting created by using tenant creation listiners. If the tenant is created from the APIM side, these listeners won't be fired as those are in the IS-KM. So in such scenario this can happen.
