### ISSUE TITLE
SCIM Groups GET fails if a userstore got removed while users had assigned hybrid roles

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#7025]
**Steps to reproduce**
* Add a secondary userstore & create a user abcd
* Create a service provider and assign the sp role to abcd
* Now remove or disable the secondary userstore
* Try to invoke SCIM2 Groups GET without any filters

**Observation**
Following cause can be seen if we enable debug logs for `org.wso2.charon3`
```
Caused by: org.wso2.carbon.user.core.UserStoreException: Invalid Domain Name
at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserStoreInternal(AbstractUserStoreManager.java:4892)
at org.wso2.carbon.user.core.common.AbstractUserStoreManager.access$400(AbstractUserStoreManager.java:86)
at org.wso2.carbon.user.core.common.AbstractUserStoreManager$7.run(AbstractUserStoreManager.java:4851)
at org.wso2.carbon.user.core.common.AbstractUserStoreManager$7.run(AbstractUserStoreManager.java:4848)
at java.security.AccessController.doPrivileged(Native Method)
at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserStore(AbstractUserStoreManager.java:4848)
at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValue(AbstractUserStoreManager.java:771)
```

**Root cause**
Even though the secondary userstore is removed, the role assignment for Application role is still in the UM_HYBRID_USER_ROLE table. Then it fails while trying to get members for the Application role since the particular userstore is not available.

Reproducible in IS 5.8.0

--------
Please refer to the [comment[1]](https://github.com/wso2/product-is/issues/7025#issuecomment-572446014), before closing this issue.

[1] https://github.com/wso2/product-is/issues/7025#issuecomment-572446014

--------

**Comment by tharindu-bandara** [comment]
As per the offline discussion with @thushaaanthan,

In the public codebase, the framework PR[1] will not take effect as file-based artifacts are disabled, thus the dependency on the kernel PR[2] also will not take effect.

Thus this issue **can only be closed**, once the kernel fix[2] is merged, and the product-is kernel version is updated accordingly. Because, only then, the possibility of this issue occurring when the file-based artifacts are enabled, is eliminated.

[1] https://github.com/wso2/carbon-identity-framework/pull/2657
[2] https://github.com/wso2/carbon-kernel/pull/2509

**Comment by rksk** [comment]
This issue is still reproducible in 5.10.0, if we remove the userstore XML file instead of deleting/disabling it from the management console.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
