### ISSUE TITLE
No error logs for Charon Exceptions

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#7026]
For example, if we got the issue https://github.com/wso2/product-is/issues/7025, there are not error logs, we have to enable debug for the charon3 package to see what is going on.

```
DEBUG {org.wso2.charon3.core.protocol.endpoints.AbstractResourceManager}
- Error in obtaining role names from user store.Invalid Domain Name
org.wso2.charon3.core.exceptions.CharonException: Error in obtaining role names from user store.Invalid Domain Name
at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listGroups(SCIMUserManager.java:1865)
at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listGroupsWithGET(SCIMUserManager.java:1803)
at org.wso2.charon3.core.protocol.endpoints.GroupResourceManager.listWithGET(GroupResourceManager.java:374)
at org.wso2.carbon.identity.scim2.provider.resources.GroupResource.processRequest(GroupResource.java:339)
at org.wso2.carbon.identity.scim2.provider.resources.GroupResource.getGroup(GroupResource.java:191)
```

org.wso2.carbon.identity.scim2.provider.resources.AbstractResource
```
    protected Response handleCharonException(CharonException e, JSONEncoder encoder) {
        if (logger.isDebugEnabled()) {
            logger.debug(e.getMessage(), e);
        }
```

https://github.com/wso2/charon/blob/master/modules/charon-impl/src/main/java/org/wso2/charon3/impl/provider/resources/AbstractResource.java#L69

**Comment by ayshsandu** [comment]
Fixed in https://github.com/wso2/charon/pull/292
