### ISSUE TITLE
ActiveSessionLimitHandler not working if user has never logged in before

### ISSUE THREAD

**Issue by holgrs** [wso2/product-is#7176]
Use Case: Enable ActiveSessionLimitHandler for a SP configuration.
-> Try to login with an user that was just created and never logged in before
-> Expected: Result: Sessions of the user are checked whether session limit is reached. Since user is new and never logged in before,  no sessions should be found and the user should be able to log in.
-> Result: Error occurs and an exception is thrown because there is no entry in table IDN_AUTH_USER 

          `      {
                    "class": "org.wso2.carbon.identity.application.authentication.handler.session.ActiveSessionsLimitHandler",
                    "exact": false,
                    "file": "ActiveSessionsLimitHandler.java",
                    "line": 113,
                    "location": "org.wso2.carbon.identity.application.authentication.handler.session-6.2.4.jar",
                    "method": "process",
                    "version": "?"
                }
            ],
            "localizedMessage": "Error occurred while retrieving sessions for userId: null",
            "message": "Error occurred while retrieving sessions for userId: null",
            "name": "org.wso2.carbon.identity.application.authentication.handler.session.exception.UserSessionRetrievalException"
        },`

Select statement that leads to the error:
`"SELECT USER_ID FROM IDN_AUTH_USER WHERE USER_NAME =? AND TENANT_ID =? AND DOMAIN_NAME =? AND IDP_ID = ?";`

**Fix is to provide something like the following code in ActiveSessionLimitHandler.java**

`String userId = getUserId(context.getSubject());

 List<UserSession> userSessions = null;
                **if (userId != null) {**
                    userSessions = getUserSessions(userId);
                }
                if (userSessions != null && userSessions.size() >= maxSessionCount) {
                    prepareEndpointParams(context, maxSessionCountParamValue, userSessions);
                    return super.process(request, response, context);
                } else {
                    this.publishAuthenticationStepAttempt(request, context, context.getSubject(), true);
                    return AuthenticatorFlowStatus.SUCCESS_COMPLETED;
                }`

Please note: it works if you logging in with an user that already logged in before.

**Comment by darshanasbg** [comment]
Tried the same in a 5.10.0 snapshot and getting following error log in the backend.

```
[2019-12-23 22:07:05,838] [2d19ea5c-782c-4eca-b29d-ef940c3efd5e] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: Error occurred while retrieving user sessions.
	at org.wso2.carbon.identity.application.authentication.handler.session.ActiveSessionsLimitHandler.process(ActiveSessionsLimitHandler.java:126)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:506)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:271)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:185)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:111)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:158)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:240)
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.identity.application.authentication.handler.session.exception.UserSessionRetrievalException: Error occurred while retrieving sessions for userId: null
	at org.wso2.carbon.identity.application.authentication.handler.session.ActiveSessionsLimitHandler.getUserSessions(ActiveSessionsLimitHandler.java:233)
	at org.wso2.carbon.identity.application.authentication.handler.session.ActiveSessionsLimitHandler.process(ActiveSessionsLimitHandler.java:113)
	... 59 more
Caused by: org.wso2.carbon.identity.application.authentication.framework.exception.session.mgt.SessionManagementClientException: Invalid user
	at org.wso2.carbon.identity.application.authentication.framework.internal.impl.UserSessionManagementServiceImpl.handleSessionManagementClientException(UserSessionManagementServiceImpl.java:357)
	at org.wso2.carbon.identity.application.authentication.framework.internal.impl.UserSessionManagementServiceImpl.getSessionsByUserId(UserSessionManagementServiceImpl.java:112)
	at org.wso2.carbon.identity.application.authentication.handler.session.ActiveSessionsLimitHandler.getUserSessions(ActiveSessionsLimitHandler.java:228)
	... 60 more
```

**Comment by darshanasbg** [comment]
Done the fix as suggested by @holgrs...
@holgrs, @gayashanbc: Please check and approve the PR https://github.com/wso2-extensions/identity-local-auth-basicauth/pull/65

**Comment by darshanasbg** [comment]
@tharindu-bandara: Can't we avoid userId being null with the new `user id` improvements?

**Comment by tharindu-bandara** [comment]
@darshanasbg 

> @tharindu-bandara: Can't we avoid userId being null with the new `user id` improvements?

I had a quick look at the [code line to get the user id](https://github.com/wso2/carbon-identity-framework/blob/1d8e580ba121ebd2ed90e92010d033e977c10a57/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/store/UserSessionStore.java#L145).

According to that, the user id used here is IdP qualified, thus requires context information about the IdP, in addition to unique user representation. Therefore what is represented by the user id here, differs from the new user unique id improvement. 

Because of that, it looks like we need to expect the `userId` being `null` situation(as the scenario described by @holgrs), then to handle it accordingly(@Abilashini could you please confirm this?).
