### ISSUE TITLE
NullPointer exception when fidp is sent in request parameter for Saml SSO

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#7206]
There is a possible NPE in this line [1]  and We could reproduce this NPE issue for the following two scenarios.

Steps to reproduce: 
1. Configure a Identity Provider. (Don't configure any Home Realm Identifier)
2. Create a service provider for travelocity application with entity ID travelocity.com
3. Configure IDP initiated SSO

Make a IDP initiated SSO as follows:

`https://localhost:9443/samlsso?fidp=wso2is&spEntityID=travelocity.com
`
The below error logs were found:

```
[2020-01-03 12:50:48,414] DEBUG {org.wso2.carbon.identity.application.authentication.framework.config.ConfigurationFacade} -  A registered IdP was not found the given realm
[2020-01-03 12:50:48,414] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} -  An IdP was not found for the sent domain. Sending to the domain page
[2020-01-03 12:50:48,415] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler} -  Step is not complete yet. Redirecting to outside.
[2020-01-03 12:50:48,415] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Context id: 9c044f96-4ba2-4d97-b5fe-edab4ad40244 left the thread with id: 189
[2020-01-03 12:50:48,488] DEBUG {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Context with id: 9c044f96-4ba2-4d97-b5fe-edab4ad40244 added to the cache.
[2020-01-03 12:50:49,216] DEBUG {org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet} -  Query string : fidp=wso2is&spEntityID=travelocity.com
[2020-01-03 12:51:16,385] ERROR {org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet} -  Cannot find AuthenticationResult from the cache
[2020-01-03 12:51:24,948] DEBUG {org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet} -  Authentication result data not found for key : 8b6a8e38-0bf2-432f-a0eb-19d584e2260a
[2020-01-03 12:51:24,957] ERROR {org.apache.catalina.core.StandardWrapperValve} -  Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception
java.lang.NullPointerException
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleAuthenticationReponseFromFramework(SAMLSSOProviderServlet.java:695)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleRequest(SAMLSSOProviderServlet.java:192)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.doGet(SAMLSSOProviderServlet.java:105)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.sendRequestToFramework(SAMLSSOProviderServlet.java:1077)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.sendToFrameworkForAuthentication(SAMLSSOProviderServlet.java:470)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleIdPInitSSO(SAMLSSOProviderServlet.java:312)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleRequest(SAMLSSOProviderServlet.java:207)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.doGet(SAMLSSOProviderServlet.java:105)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
```

The similar issue already reported and fixed with 5.3.0 [2][3]
1]https://github.com/wso2-support/identity-inbound-auth-saml/blob/support-5.1.2/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/servlet/SAMLSSOProviderServlet.java#L695
[2]https://wso2.org/jira/browse/IDENTITY-5882
[3]https://wso2.org/jira/browse/IDENTITY-6863

**Comment by mefarazath** [comment]
This fix is already present in master
