### ISSUE TITLE
Getting an error log while email confirmation sending with self registration via user portal 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7248]
Affected is version: wso2is-5.10.0-alpha2-SNAPSHOT
JDK : 1.8.0_231
User store type = "read_write_ldap_unique_id"
Type: BUG

Step to reproduced:
add configuration in deployment toml:
[output_adapter.email]
from_address= "xxxxx@gmail.com"
username="xxxxx"
password="xxxxxxx"

server startup 
enabled User Self Registration 
 navigate to user portal -https://localhost:9443/user-portal/login
Click on "Create Account", provide user name and Proceed to self signup
provide all fields / manadtory on registration 
checked I hereby confirm that I have read and understood the Privacy Policy
and clicked "Register"
Clicked on "Close " on Confirmation link has been sent to your email message box
 got bellow error log 

[2020-01-09 15:50:31,863] [020176f9-a763-4f7c-ad06-98c3a7e5d277] ERROR {org.wso2.carbon.event.output.adapter.email.EmailEventAdapter} - Event dropped at Output Adapter 'EmailPublisher' for tenant id '-1234', Error in message format, 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials b42sm2639724pjc.27 - gsmtp
javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials b42sm2639724pjc.27 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:965)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:876)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:780)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.wso2.carbon.event.output.adapter.email.EmailEventAdapter$EmailSender.run(EmailEventAdapter.java:347)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

followed document: https://is.docs.wso2.com/en/5.9.0/learn/self-registration-and-account-confirmation/#!

**Note: user does not get ant email conformation**

**Comment by NilukaSripalim** [comment]
working , afret restart the server
