### ISSUE TITLE
Listing the already created AD Users via SCIM2 for plugged read-only secondary user store by mapping objectGUID(binary attribute) attribute with UserID claim.

### ISSUE THREAD

**Issue by kasuniranasinghe14** [wso2/product-is#7303]
Please find the steps to reproduce the issue.

1- Configure a ReadOnlyAD as a secondary user store in IS.
2 - AD's ObjectGUID  property is stored in AD as an octetSting format. Hence we need to do the data type conversion if we are going to map it in IS. This can be achieved by adding the following property in user store configurations.
`<Property name="java.naming.ldap.attributes.binary">ObjectGUID</Property>`

3- Add a claim mapping for http://wso2.org/claims/UserID with Secondary User store attribute "objectGUID".

4 - List users using following scim command.
`curl -v -k --user admin:admin https://localhost:9443/scim2/Users?`

Affected Versions- IS- 5.8.0 and IS-5.9.0

**Comment by emswbandara** [comment]
@kasuniranasinghe14 can you please update any stack-traces or errors you observed in the server backend with this issue?

**Comment by kasuniranasinghe14** [comment]
**The following error log can be observed when listing users through scim2 after the claim mapping with objectGUID attribute.**

`
[2020-01-21 21:39:07,224] [fade94e9-948d-41c3-8b64-13fb7e347c63] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Invoking the get user list for domain: TESTNEW.COM for claim: http://wso2.org/claims/userid value: TESTNEW.COM/*
[2020-01-21 21:39:07,226] [fade94e9-948d-41c3-8b64-13fb7e347c63] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Listing users who having value as TESTNEW.COM/* for the claim http://wso2.org/claims/userid
[2020-01-21 21:39:07,227] [fade94e9-948d-41c3-8b64-13fb7e347c63] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Domain: TESTNEW.COM is passed with the claim and user store manager is loaded for the given domain name.
[2020-01-21 21:39:07,229] [fade94e9-948d-41c3-8b64-13fb7e347c63] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Pre listener user list: [] for domain: TESTNEW.COM
[2020-01-21 21:39:07,231] [fade94e9-948d-41c3-8b64-13fb7e347c63] DEBUG {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Domain found in claim value. Searching only in the TESTNEW.COM for possible matches
[2020-01-21 21:39:07,232] [fade94e9-948d-41c3-8b64-13fb7e347c63] ERROR {org.wso2.carbon.user.core.common.AbstractUserStoreManager} - Error occurred while accessing Java Security Manager Privilege Block when called by method getUserList with 3 length of Objects and argTypes [class java.lang.String, class java.lang.String, class java.lang.String]
[2020-01-21 21:39:07,234] [fade94e9-948d-41c3-8b64-13fb7e347c63] DEBUG {org.wso2.charon3.core.protocol.endpoints.AbstractResourceManager} - Error while listing usernames across all domains. org.wso2.charon3.core.exceptions.CharonException: Error while listing usernames across all domains. 
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsernamesAcrossAllDomainsUsingLegacyAPIs(SCIMUserManager.java:523)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsers(SCIMUserManager.java:385)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsersWithGET(SCIMUserManager.java:341)
	at org.wso2.charon3.core.protocol.endpoints.UserResourceManager.listWithGET(UserResourceManager.java:347)
	at org.wso2.carbon.identity.scim2.provider.resources.UserResource.getUser(UserResource.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:607)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:92)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:93)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while accessing Java Security Manager Privilege Block when called by method getUserList with 3 length of Objects and argTypes [class java.lang.String, class java.lang.String, class java.lang.String]
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:196)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserList(AbstractUserStoreManager.java:1346)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsernamesAcrossAllDomainsUsingLegacyAPIs(SCIMUserManager.java:519)
	... 63 more
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:174)
	... 65 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:177)
	... 67 more
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: *
	at java.util.UUID.fromString(UUID.java:194)
	at org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager.transformUUIDToObjectGUID(ReadOnlyLDAPUserStoreManager.java:3406)
	at org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager.getUserListFromProperties(ReadOnlyLDAPUserStoreManager.java:2616)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetUserList(AbstractUserStoreManager.java:1504)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserList(AbstractUserStoreManager.java:1442)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.doGetUserList(AbstractUserStoreManager.java:1556)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserList(AbstractUserStoreManager.java:1442)
	... 72 more

`
