### ISSUE TITLE
Unique ID read only Ldap backend error found in scenario POST/ Search Users SCIM 2 

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#7312]
For the SCIM 2  POST/ Search Users scenarios, found and errors in UniqueID read only Ldap logs

Steps to re create:
1. Get two wso2is packs and change the off set  (1)of server1 and start. Then create users.
2. Change the server2 toml configuration to unique ID  read only Ldap by configuring  server1 Ldap as unique ID read only Ldap (Primary) 

```
[user_store]
type = "read_only_ldap_unique_id"
connection_url = "ldap://localhost:10390"
connection_name = "uid=admin,ou=system"
connection_password = "admin"
base_dn = "dc=wso2,dc=org"
```
3. Start the server2 as well.
4. Execute  POST/ Search user scenario .
Request:

`curl -v -k --user admin:admin --data '{"schemas": ["urn:ietf:params:scim:api:messages:2.0:SearchRequest"],"attributes": ["name.familyName", "userName"],"filter":"userName sw ki and name.familyName co ack","domain":"PRIMARY","startIndex": 1,"count": 10}' --header "Content-Type:application/scim+json"  'https://localhost:9443/scim2/Users/.search'`

Response :

`{"totalResults":1,"startIndex":1,"itemsPerPage":1,"schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],"Resources":[{"name":{"familyName":"jackson"},"id":"c8c821ba-1200-495e-a775-79b260e717bd","userName":"kim"}]}
`

Error log at ldap server logs:
```
[2020-01-17 13:50:50,576] [] ERROR {org.apache.directory.server.ldap.LdapSession} - ERR_172 Failing on cursor close : ERR_538 RecordManager has been closed

[2020-01-17 13:50:56,800] [] ERROR {org.apache.directory.server.ldap.handlers.request.UnbindRequestHandler} - ERR_169 failed to unbind session properly java.lang.IllegalStateException: ERR_538 RecordManager has been closed
	at jdbm.recman.BaseRecordManager.checkIfClosed(BaseRecordManager.java:607)
	at jdbm.recman.BaseRecordManager.close(BaseRecordManager.java:267)
	at org.apache.directory.server.core.shared.SortedEntryCursor.deleteFile(SortedEntryCursor.java:272)
	at org.apache.directory.server.core.shared.SortedEntryCursor.close(SortedEntryCursor.java:222)
	at org.apache.directory.server.ldap.LdapSession.closeAllPagedSearches(LdapSession.java:568)
	at org.apache.directory.server.ldap.handlers.request.UnbindRequestHandler.handle(UnbindRequestHandler.java:49)
	at org.apache.directory.server.ldap.handlers.request.UnbindRequestHandler.handle(UnbindRequestHandler.java:38)
	at org.apache.directory.server.ldap.handlers.LdapRequestHandler.handleMessage(LdapRequestHandler.java:207)
	at org.apache.directory.server.ldap.handlers.LdapRequestHandler.handleMessage(LdapRequestHandler.java:56)
	at org.apache.mina.handler.demux.DemuxingIoHandler.messageReceived(DemuxingIoHandler.java:243)
	at org.apache.directory.server.ldap.LdapProtocolHandler.messageReceived(LdapProtocolHandler.java:223)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:997)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:641)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1114)
	at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:87)
	at org.apache.mina.core.session.IoEvent.run(IoEvent.java:88)
	at org.apache.mina.filter.executor.UnorderedThreadPoolExecutor$Worker.runTask(UnorderedThreadPoolExecutor.java:541)
	at org.apache.mina.filter.executor.UnorderedThreadPoolExecutor$Worker.run(UnorderedThreadPoolExecutor.java:493)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
