### ISSUE TITLE
 Need to fix the account suspension flow to use identity claim  "http://wso2.org/claims/identity/lastLogonTime"

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/product-is#7491]
Identity Server 5.8.0

According to [1] in the account suspension flow, even though there is an identity claim referred to as  http://wso2.org/claims/identity/lastLogonTime that we can use for the account suspension feature, we are using the non-identity claim http://wso2.org/claims/lastLogin.

This is causing issues for users who are using read-only LDAP user stores and account suspension feature enabled

Once a user login is triggered and while updating the claim http://wso2.org/claims/lastLoginTime following issue occurred

ERROR {org.wso2.carbon.identity.account.suspension.notification.task.handler.AccountSuspensionNotificationHandler} -  Error occurred while updating last login claim for user:
org.wso2.carbon.user.core.UserStoreException: 30002 - InvalidOperation Invalid operation. User store is read only

Due to configured read-only LDAP user-store and we cannot update the value of the above non-identity claim http://wso2.org/claims/lastLoginTime.

Therefore, we need to fix the account suspension flow to use identity claim  "http://wso2.org/claims/identity/lastLogonTime"

[1] https://github.com/wso2-extensions/identity-governance/blob/master/components/org.wso2.carbon.identity.account.suspension.notification.task/src/main/java/org/wso2/carbon/identity/account/suspension/notification/task/handler/AccountSuspensionNotificationHandler.java#L71

**Comment by nilasini** [comment]
Config PR \[1] and migration doc issue \[2]

\[1] https://github.com/wso2/carbon-identity-framework/pull/2740
\[2] https://github.com/wso2/product-is/issues/7532

**Comment by rksk** [comment]
This fix has to be improved. We are still searching in UM tables (for JDBC) and LDAP userstores even though the config is enabled. We need to search on IDN tables for the identity claim value.

**Comment by LahiruLS** [comment]
In the Oracle database, the below exception occurs.
```
TID: [-1234] [] [2020-08-31 16:09:00,306] ERROR {org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread} -  Error occurred while retrieving notification receivers 
org.wso2.carbon.identity.account.suspension.notification.task.exception.AccountSuspensionNotificationException: ORA-01722: invalid number

	at org.wso2.carbon.identity.account.suspension.notification.task.util.NotificationReceiversRetrievalUtil.getNotificationReceiversFromIdentityClaim(NotificationReceiversRetrievalUtil.java:243)
	at org.wso2.carbon.identity.account.suspension.notification.task.ldap.LDAPNotificationReceiversRetrieval.getNotificationReceivers(LDAPNotificationReceiversRetrieval.java:88)
	at org.wso2.carbon.identity.account.suspension.notification.task.NotificationReceiversRetrievalManager.getReceivers(NotificationReceiversRetrievalManager.java:65)
	at org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread.notifyUsers(AccountValidatorThread.java:177)
	at org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread.handleTask(AccountValidatorThread.java:156)
	at org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread.run(AccountValidatorThread.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLSyntaxErrorException: ORA-01722: invalid number

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:774)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:925)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1111)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:4845)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1501)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy20.executeQuery(Unknown Source)
	at org.wso2.carbon.identity.account.suspension.notification.task.util.NotificationReceiversRetrievalUtil.getNotificationReceiversFromIdentityClaim(NotificationReceiversRetrievalUtil.java:208)
	... 12 more
TID: [-1234] [] [2020-08-31 16:09:00,314] ERROR {org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread} -  Unable to disable user accounts 
org.wso2.carbon.identity.base.IdentityException: Error occurred while retrieving users for account disable
	at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:60)
	at org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread.lockAccounts(AccountValidatorThread.java:205)
	at org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread.handleTask(AccountValidatorThread.java:158)
	at org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread.run(AccountValidatorThread.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.identity.account.suspension.notification.task.exception.AccountSuspensionNotificationException: ORA-01722: invalid number

	at org.wso2.carbon.identity.account.suspension.notification.task.util.NotificationReceiversRetrievalUtil.getNotificationReceiversFromIdentityClaim(NotificationReceiversRetrievalUtil.java:243)
	at org.wso2.carbon.identity.account.suspension.notification.task.ldap.LDAPNotificationReceiversRetrieval.getNotificationReceivers(LDAPNotificationReceiversRetrieval.java:88)
	at org.wso2.carbon.identity.account.suspension.notification.task.NotificationReceiversRetrievalManager.getReceivers(NotificationReceiversRetrievalManager.java:65)
	at org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread.lockAccounts(AccountValidatorThread.java:201)
	... 9 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-01722: invalid number

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:774)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:925)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1111)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:4845)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1501)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy20.executeQuery(Unknown Source)
	at org.wso2.carbon.identity.account.suspension.notification.task.util.NotificationReceiversRetrievalUtil.getNotificationReceiversFromIdentityClaim(NotificationReceiversRetrievalUtil.java:208)
	... 12 more
```

I believe the issue is that In Oracle, we need to set this as an Integer since in the schema TENANT_ID is an Integer. Below is the DB schema for 5.8.0 
```
CREATE TABLE IDN_IDENTITY_USER_DATA (
TENANT_ID INTEGER DEFAULT -1234,
USER_NAME VARCHAR(255) NOT NULL,
DATA_KEY VARCHAR(255) NOT NULL,
DATA_VALUE VARCHAR(2048),
PRIMARY KEY (TENANT_ID, USER_NAME, DATA_KEY))
/
```
