### ISSUE TITLE
Error logs , while updating BPS Profile(Server Profile Name) in a Workflow definition

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#7555]
Tested Environment:
Prostgres 11.6, Jdbc unique User store
"Description"
Error logs , while updating BPS Profile(Server Profile Name) in a Workflow definition

Step to Reproduce:

1. Add under Workflow Definitions in the Manage section.
2. Enter the name
3. proceed the Add Approval Step, 
4. Click Finish to complete the process.
5. Create other Workflow Definition and proceed and Finish.
6. Update the Workflow Definition name, which same with previous
7. See erro and error log, 
8.But, in Workflow Definitions > List under the Manage Section, there are 2 Workflow Definitions are listed with same name.

![image](https://user-images.githubusercontent.com/39120228/74403003-d6b63300-4e4b-11ea-929d-b8f1eaf0bed2.png)

![image](https://user-images.githubusercontent.com/39120228/74403022-ea619980-4e4b-11ea-956c-cf8b2a0dcc63.png)

`ERROR {org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl} - Aborting deployment. Duplicate Deployment unit WorkflowNew-3.
[2020-02-13 10:19:50,012] [67d76264-7027-49e9-8e48-694a870158a2] ERROR {org.wso2.carbon.bpel.deployer.BPELDeployer} - Error deploying BPEL package: WorkflowNew.zip org.wso2.carbon.bpel.core.ode.integration.store.BPELDeploymentException: Aborting deployment. Duplicate Deployment unit WorkflowNew-3.
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.deployBPELPackageInODE(TenantProcessStoreImpl.java:721)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.deploy(TenantProcessStoreImpl.java:296)
	at org.wso2.carbon.bpel.deployer.BPELDeployer.deploy(BPELDeployer.java:107)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Expected Output:**
1. There should be proper error message display and should not allow to add Workflow definitions with same name, because this may issue while add this Workflow definition to Workflow Engagement

**Comment by IsuraD** [comment]
Duplicate with https://github.com/wso2/product-is/issues/7595
