### ISSUE TITLE
Possible null pointer error when updating the secondary user store from management console.

### ISSUE THREAD

**Issue by pathberiya** [wso2/product-is#7565]
Following null pointer error has been seen when updating the secondary user store.  This null pointer can be caused when user store properties could not be loaded from the user store object.  It is not correct to load the user store properties from user store object & it must be used the realm configuration. Because user store object may not be initized properly due to some initilization failures.

[1] Caused by: java.lang.NullPointerException
        at org.wso2.carbon.identity.user.store.configuration.utils.SecondaryUserStoreConfigurator.encryptPlainText(SecondaryUserStoreConfigurator.java:146)
        at org.wso2.carbon.identity.user.store.configuration.utils.SecondaryUserStoreConfigurationUtil.encryptPlainText(SecondaryUserStoreConfigurationUtil.java:60)
        at org.wso2.carbon.identity.user.store.configuration.UserStoreConfigAdminService.addProperties(UserStoreConfigAdminService.java:576)
        at org.wso2.carbon.identity.user.store.configuration.UserStoreConfigAdminService.writeUserMgtXMLFile(UserStoreConfigAdminService.java:906)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
