### ISSUE TITLE
StringUtils class not found exception when logging with Post Binding and user credentials in travelocity sample

### ISSUE THREAD

**Issue by custardpie** [wso2/product-is#758]
This is with version 5.2.0 of the identity server, and the Travelocity.com sample. When I tried to login using post binding and user credentials in the client form, I get the following exceptions in the wso2carbon.log

```
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Exception in Authentication Framework 
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
    at org.wso2.carbon.identity.application.authenticator.requestpath.basicauth.BasicAuthRequestPathAuthenticator.processAuthenticationResponse(BasicAuthRequestPathAuthenticator.java:91)
..
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils cannot be found by org.wso2.carbon.identity.application.authenticator.requestpath.basicauth_5.1.2
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
```

**Comment by GDRDABARERA** [comment]
@sagara-gunathunga  - Can I know how this became fixed and closed? There is no explanation.
