### ISSUE TITLE
Account locking does not work after the no:of failed attempts are reached.

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#7619]
**Description:**
Configured account locking for the single sign-on flow and logged in with invalid credentials till the maximum number of failed attempts reached or passed. Still the user can log into the webapp without any problem, the account does not get locked.

**Suggested Labels:**
5.10.0-Beta2, Priority/High, Severity/Blocker

**Suggested Assignees:**
N/A

**Affected Product Version:**
5.10.0-Beta2

**OS, DB, other environment details and versions:**  
User - Tenant (Secondary User Store - JDBC(h2)) 
Ubuntu 18.04 
webapp - travelocity

**Steps to reproduce:**
- Create tenant.
- Log in to the management console with the tenant admin.
- Create a secondary h2 user store.
- Create a service provider for the webapp.
- Add a user to the secondary user store.
- Setup account locking as mentioned in [1].
- Try invalid log in attempts till the specified number is passed.
- Account does not get locked.

[1] - https://is.docs.wso2.com/en/latest/learn/configuring-account-locking-due-to-failed-login-attempts/

**Comment by SwatiNEC** [comment]
Hi @deshankoswatte 

I have tried the steps mentioned above to reproduce the error but I am facing issue in Step5(Add a user to the secondary user store).Please find the error logs below:
```
TID: [1] [] [2020-04-17 13:33:53,066] [9330c242-ae37-4839-87bc-4995cd54ae38] ERROR {org.wso2.carbon.user.mgt.UserRealmProxy} - Error while persisting user : demouser org.wso2.carbon.user.core.UserStoreException: Error while persisting user : demouser
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:201)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4371)
	at org.wso2.carbon.user.mgt.UserRealmProxy.addUser(UserRealmProxy.java:784)
	at org.wso2.carbon.user.mgt.UserAdmin.addUser(UserAdmin.java:200)
Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:191)
	... 96 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:194)
	... 98 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error while persisting user : demouser
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.persistUser(JDBCUserStoreManager.java:1541)
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doAddUser(JDBCUserStoreManager.java:1390)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4640)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.addUser(AbstractUserStoreManager.java:4397)
	... 103 more
Caused by: org.wso2.carbon.user.core.UserStoreException: Error occurred while updating string values to database.
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.updateStringValuesToDatabase(JDBCUserStoreManager.java:2555)
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.persistUser(JDBCUserStoreManager.java:1436)
	... 106 more
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "UM_USER_ID"; SQL statement:
INSERT INTO UM_USER (UM_USER_NAME, UM_USER_PASSWORD, UM_SALT_VALUE, UM_REQUIRE_CHANGE, UM_CHANGED_TIME, UM_TENANT_ID) VALUES (?, ?, ?, ?, ?, ?) [23502-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 107 more
```

But when I have tried to reproduce the issue with user of primary user store and the functionality works properly.

**Comment by deshankoswatte** [comment]
Hey @SwatiNEC, can I know the type User Store Manager Class which you used? I think you have configured it as `org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager` which should be `org.wso2.carbon.user.core.jdbc.UniqueIDJDBCUserStoreManager`.

**Comment by SwatiNEC** [comment]
Hi @deshankoswatte 

Thanks for your response. After updating the above I am able to create a user in secondary user store. But I am not able to login with the newly created user even with correct credentials. I am getting below logs:

 ```
INFO {org.wso2.carbon.core.services.authentication.AuthenticationAdmin} - 'test@demo.com [2]' logged out at [2020-04-17 17:09:02,0461]
 WARN {org.wso2.carbon.core.services.util.CarbonAuthenticationUtil} - Login failed. Unauthorized login attempt 'userDemo[-1234]' at [2020-04-17 17:09:08,901+0530]
```
I have also assigned all roles and permission but even after that I am getting same message.

**Comment by deshankoswatte** [comment]
@SwatiNEC what were the credentials you used?

**Comment by deshankoswatte** [comment]
@SwatiNEC Can I know the credentials which you used?

**Comment by SwatiNEC** [comment]
@deshankoswatte yes this is a user in the secondary user store and credentials are `username: userDemo and Password: 123456`

**Comment by deshankoswatte** [comment]
Where are you trying to login into a web app or the management console?

**Comment by SwatiNEC** [comment]
@deshankoswatte I have tried on management console.

**Comment by deshankoswatte** [comment]
@SwatiNEC this should be a permission issue as it seems. Log into your tenant admin and follow the steps as follows:

![Peek 2020-04-20 11-42](https://user-images.githubusercontent.com/33062368/79719423-2dccfe00-82fc-11ea-83f2-707a37780140.gif)

And then login to you tenant with:
`username: userDemo@tenant.com and password: 123456`

**Comment by deshankoswatte** [comment]
Closing since this issue belongs to a lower product-is version.
