### ISSUE TITLE
Generic error response is returned during RPT request in UMA with expired permission ticket

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#7649]
Tried to obtain a requesting party token (https://is.docs.wso2.com/en/next/learn/user-managed-access-with-wso2-identity-server/#obtain-the-requesting-party-token) with an expired permission ticket. 

Response: 
```
{"error_description":"Provided Authorization Grant is invalid","error":"invalid_grant"}
```
Server logs:
```
DEBUG {org.wso2.carbon.identity.oauth.uma.grant.UMA2GrantHandler} - Error while requesting Requesting Party Token (RPT). Invalid permission ticket: 130f9608-6d15-40f6-9bc8-63c12e2c5649 org.wso2.carbon.identity.oauth.uma.common.exception.UMAClientException: Invalid permission ticket.
	at org.wso2.carbon.identity.oauth.uma.permission.service.dao.PermissionTicketDAO.checkPermissionTicketExpiration(PermissionTicketDAO.java:197)
	at org.wso2.carbon.identity.oauth.uma.permission.service.dao.PermissionTicketDAO.validatePermissionTicket(PermissionTicketDAO.java:352)
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
