### ISSUE TITLE
NoClassDefFoundError when trying to deploy Yammer Authenticator from connector store

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#7675]
**Description:**
When trying to start the IS after deploying the Yammer Autheticator artifacts downloaded from [https://store.wso2.com/store/assets/isconnector/details/0e1f0ba7-c4dc-4826-afa7-ba3adef00e7b](https://store.wso2.com/store/assets/isconnector/details/0e1f0ba7-c4dc-4826-afa7-ba3adef00e7b), the following error occurs. 

When the connector built from [https://github.com/wso2-extensions/identity-outbound-auth-yammer](https://github.com/wso2-extensions/identity-outbound-auth-yammer) is used, this error does not occur. Hence, the connector store needs to be updated with the connector built from source. 

`FATAL {org.wso2.carbon.identity.authenticator.internal.YammerAuthenticatorServiceComponent} - Error while activating the Yammer authenticator java.lang.NoClassDefFoundError: org/wso2/carbon/identity/authenticator/YammerOAuth2Authenticator
	at org.wso2.carbon.identity.authenticator.internal.YammerAuthenticatorServiceComponent.activate(YammerAuthenticatorServiceComponent.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.identity.authenticator.YammerOAuth2Authenticator cannot be found by org.wso2.carbon.identity.authenticator.yammer_1.0.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 16 more`

**Related Issues:**
[https://github.com/wso2/product-is/issues/1633](https://github.com/wso2/product-is/issues/1633)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
