### ISSUE TITLE
NoClassDefFoundError when trying to deploy Inwebo Authenticator from connector store

### ISSUE THREAD

**Issue by DinikaSen** [wso2/product-is#7676]
**Description:**
When trying to start the IS after deploying the Inwebo Autheticator artifacts downloaded from [https://store.wso2.com/store/assets/isconnector/details/a6d17625-a179-4f6a-8e93-6910b719e6c8](https://store.wso2.com/store/assets/isconnector/details/a6d17625-a179-4f6a-8e93-6910b719e6c8), the following error occurs.

`FATAL {org.wso2.carbon.identity.authenticator.internal.InweboAuthenticatorServiceComponent} - Error while activating the Inwebo authenticator java.lang.NoClassDefFoundError: org/wso2/carbon/identity/authenticator/InweboAuthenticator
	at org.wso2.carbon.identity.authenticator.internal.InweboAuthenticatorServiceComponent.activate(InweboAuthenticatorServiceComponent.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.identity.authenticator.InweboAuthenticator cannot be found by org.wso2.carbon.extension.identity.authenticator.inwebo.connector_1.0.1
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 16 more`

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
