### ISSUE TITLE
IWA NTLM authenticator does not work with IS-5.9.0 due to tomcat version upgrade

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#7718]
**Description:**
In the tomcat jar file which is shipped with IS-5.9.0, the org.apache.catalina.deploy.LoginConfig class is missing in the jar, in the newer tomcat versions, these classes have been removed. Therefore the following class not found exception is seen.
```java.lang.ClassNotFoundException: org.apache.catalina.deploy.LoginConfig cannot be found by waffle-jna_1.6.0.wso2v6```

After building the waffle-jna_1.6.0.wso2v6 by adding the correct tomcat9 dependencies and waffle version solves this error

**Affected Product Version:**
IS-5.9.0

**OS, DB, other environment details and versions:**    
org.wso2.carbon.identity.application.authenticator.iwa.ntlm-5.2.1-SNAPSHOT.
OS Windows 2012 R2
JAVA 8
oracle db

**Steps to reproduce:**
Setup IWA NTLM authenticator[1][2]

[1]https://is.docs.wso2.com/en/5.9.0/learn/configuring-iwa-single-sign-on/
[2]https://github.com/wso2-extensions/identity-local-auth-iwa-ntlm/tree/v5.2.1

**Comment by ruwanta** [comment]
We need to upgrade the IWA

**Comment by vihanga-liyanage** [comment]
Update.
The issue has nothing to do with https://github.com/wso2-extensions/identity-local-auth-iwa-ntlm/tree/v5.2.1. This issue comes from the org.wso2.carbon.identity.application.authenticator.iwa JAR.

We tried updating the tomcat artifact to waffle-tomcat8 and waffle-tomcat9 and the waffle version to 1.8.1 but then we got a new error as below.
```
[2020-02-28 17:21:28,653] [3c91c835-f4a2-46be-9f36-750d41ea0f9f] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost]} - Exception Processing /carbon/admin/index.jsp java.lang.AbstractMethodError: org.apache.catalina.authenticator.AuthenticatorBase.doAuthenticate(Lorg/apache/catalina/connector/Request;Ljavax/servlet/http/HttpServletResponse;)Z
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:572)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100)
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116)
        at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

[2020-02-28 17:21:28,944] [be9ffdba-bb72-4e96-b92d-8a58563c71ba] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost]} - Exception Processing /favicon.ico java.lang.AbstractMethodError: org.apache.catalina.authenticator.AuthenticatorBase.doAuthenticate(Lorg/apache/catalina/connector/Request;Ljavax/servlet/http/HttpServletResponse;)Z
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:572)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100)
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116)
        at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
