### ISSUE TITLE
Self-registration breaks when using another locale than en_us

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#7732]
**Description:**
If we send the self registration request with a locale other than `en_us` with the claim `http://wso2.org/claims/locality` while we have not defined the an email/sms template for the specific locale, the flow breaks with a stackoveflow.
```
curl -kv -X POST -u admin:admin -H "Content-Type: application/json" -d '{"user": {"username": "kim5","realm": "PRIMARY", "password": "Password12!","claims": [{"uri": "http://wso2.org/claims/givenname","value": "kim" },{"uri": "http://wso2.org/claims/emailaddress","value": "kim.anderson@gmail.com"},{"uri": "http://wso2.org/claims/identity/phoneVerified","value": "true"},{"uri": "http://wso2.org/claims/lastname","value": "Anderson"},{"uri": "http://wso2.org/claims/identity/preferredChannel","value": "SMS"}, {"uri": "http://wso2.org/claims/mobile","value": "+123456890"} , {"uri": "http://wso2.org/claims/locality","value": "en_gb"} ] },"properties": []}' "https://localhost:9443/api/identity/user/v1.0/me"
```

```
[2020-02-21 22:54:49,793] FATAL {org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager} -  Unable to proceed with simulation
java.lang.StackOverflowError
...
        at org.wso2.carbon.registry.core.session.UserRegistry.resourceExistsInternal(UserRegistry.java:774)
        at org.wso2.carbon.registry.core.session.UserRegistry.access$800(UserRegistry.java:61)
        at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:757)
        at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:754)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.wso2.carbon.registry.core.session.UserRegistry.resourceExists(UserRegistry.java:754)
        at org.wso2.carbon.identity.core.persistence.registry.RegistryResourceMgtServiceImpl.getIdentityResource(RegistryResourceMgtServiceImpl.java:105)
        at org.wso2.carbon.identity.core.persistence.registry.RegistryResourceMgtServiceImpl.getIdentityResource(RegistryResourceMgtServiceImpl.java:60)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:282)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
        at org.wso2.carbon.email.mgt.EmailTemplateManagerImpl.getNotificationTemplate(EmailTemplateManagerImpl.java:316)
```

This issue is reproducible in IS 5.7.0 since the recursion at [1] is passing the parms incorrectly to fetch the template for the default locale.

5.7 has following line at [1].
```
return getNotificationTemplate(templateType, defaultLocale, notificationChannel, tenantDomain);
```

It should be updated as follows.
```
return getNotificationTemplate(notificationChannel, templateType, defaultLocale, tenantDomain);
```

[1] https://github.com/wso2-extensions/identity-event-handler-notification/blob/7bca172121a96c0f88f477ebdbe0dfd041d7df22/components/email-mgt/org.wso2.carbon.email.mgt/src/main/java/org/wso2/carbon/email/mgt/EmailTemplateManagerImpl.java#L379

**Comment by Kanapriya** [comment]
This is already fixed in the master [1]. Hence close this issue.

[1] https://github.com/wso2-extensions/identity-event-handler-notification/blob/master/components/email-mgt/org.wso2.carbon.email.mgt/src/main/java/org/wso2/carbon/email/mgt/EmailTemplateManagerImpl.java#L379
