### ISSUE TITLE
NullPointerException when attempting to reset password via e-mail

### ISSUE THREAD

**Issue by ChamathNS** [wso2/product-is#7736]
**Description:**
The following stack trace is produced when trying to reset the password via email.
```
ERROR {org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve} - Could not handle request: /accountrecoveryendpoint/completepasswordreset.do java.lang.NullPointerException
	at org.wso2.carbon.tomcat.ext.internal.Utils.getAppNameFromRequest(Utils.java:101)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.initCarbonContext(CarbonContextCreatorValve.java:80)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:56)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Affected Product Version:**
5.10.0-Beta2

**OS, DB, other environment details and versions:**    
Ubuntu 18.04
MSSQL

**Steps to reproduce:**
1. Configure reset password with email option []https://is.docs.wso2.com/en/5.9.0/learn/configuring-password-reset-with-email
2. attempt to reset the password by clicking on `forgot password`, then `recover with mail`
3. Log in to the email specified for the user, find the Password Reset mail and click on reset password.

**Comment by ChamathNS** [comment]
From a private session, clicking on reset password button doesn't trigger the exception.

![Screenshot from 2020-02-24 12-09-42](https://user-images.githubusercontent.com/25428696/75133140-9b471e80-56ff-11ea-9f0d-91681ed0d1d6.png)
