### ISSUE TITLE
WSO2 Identity Server Analytics engine default value correction

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#7783]
Default configurations of the WSO2 Identity Server Analytics engine's **Target Host** is **HTTP** URL as shown below.

![analytics-engine](https://user-images.githubusercontent.com/5061791/75469991-f609a000-59b5-11ea-9e74-e00814fbf88e.png)

BUt the correct configuration should be **HTTPS** URL.
![analytics-https](https://user-images.githubusercontent.com/5061791/75470172-47199400-59b6-11ea-8763-e7af7723281c.png)

Let's make the URL **HTTPs** by default. Otherwise, [Risk Based adaptive authentication](https://is.docs.wso2.com/en/latest/learn/configuring-risk-based-adaptive-authentication/) scenario fails and below error is getting printed in the Stream Processor log.

```
[2020-02-27 22:54:48,354]  WARN {io.netty.channel.DefaultChannelPipeline} - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 504f5354202f5269736b42617365644c6f67696e2f496e70757453747265616d20485454502f312e310d0a4163636570743a206170706c69636174696f6e2f6a736f6e0d0a436f6e74656e742d547970653a206170706c69636174696f6e2f6a736f6e0d0a417574686f72697a6174696f6e3a204261736963205957527461573436595752746157343d0d0a436f6e74656e742d4c656e6774683a2033310d0a486f73743a206c6f63616c686f73743a383238300d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a557365722d4167656e743a204170616368652d487474704173796e63436c69656e742f342e302e3220286a61766120312e35290d0a0d0a7b226576656e74223a7b22757365726e616d65223a22617965736861227d7d
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 504f5354202f5269736b42617365644c6f67696e2f496e70757453747265616d20485454502f312e310d0a4163636570743a206170706c69636174696f6e2f6a736f6e0d0a436f6e74656e742d547970653a206170706c69636174696f6e2f6a736f6e0d0a417574686f72697a6174696f6e3a204261736963205957527461573436595752746157343d0d0a436f6e74656e742d4c656e6774683a2033310d0a486f73743a206c6f63616c686f73743a383238300d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a557365722d4167656e743a204170616368652d487474704173796e63436c69656e742f342e302e3220286a61766120312e35290d0a0d0a7b226576656e74223a7b22757365726e616d65223a22617965736861227d7d
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1106)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
```

**Comment by omindu** [comment]
is 8280 is an SSL port ? usually the SSL port is 8443 ?
