### ISSUE TITLE
About the Upgrading guide

### ISSUE THREAD

**Issue by snipking** [wso2/product-is#782]
1. Lost some configuration file when copy `conf` floder
2. Should add a step to change the `Version` in `repository/conf/carbon.xml`

**Comment by mefarazath** [comment]
Is this about the migration guide? Could you give some more details?

**Comment by snipking** [comment]
@mefarazath Yes as following: 

1. Following the migration guide, lost `<wso2_ids>/repository/conf/identity/oidc-scope-config.xml` in the upgraded server.

2. Following the migration guide, the upgraded server still show `version 5.1.0` in the web console and log. I fix this by change the version num in `<wso2_ids>/repository/conf/carbon.xml` and `<wso2_ids>/repository/conf/axis2/axis2.xml` manually.

**Comment by mefarazath** [comment]
@snipking 

#1 is a valid concern. We are in the process of upgrading the migration guides due to few improvements/shortcoming we noticed. Will update once it's done.

#2 is harmless I guess. Will look into the possibility to incorporate that into the guide as well.

**Comment by mefarazath** [comment]
Hey @snipking,

We've updated the upgrade guide[1]. Please check it out and let us know if you find any shortcomings.

[1] https://docs.wso2.com/display/IS520/Upgrading+from+a+Previous+Release

**Comment by snipking** [comment]
@mefarazath 

Thanks for the update.

I was following the `Configuration changes in IS 5.2.0` part and change my 5.1.0 configuration to the 5.2.0 ver. There are several mistake in the table and I will figure it out later. But first of all, after disable OAuthCache, my two nodes cluster always throw following error when request OAuth token first time.

```
[2016-11-16 23:20:39,145] ERROR {org.wso2.carbon.identity.oauth2.OAuth2Service} -  Error occurred while issuing the access token for Client ID : erT5tDqGr5lXfWVkklJlvyielr0a, User ID null, Scope : [] and Grant Type : authorization_code
org.wso2.carbon.identity.oauth2.IdentityOAuth2Exception: Access token based information is not available in cache or database
	at org.wso2.carbon.identity.openidconnect.DefaultIDTokenBuilder.getAccessTokenIssuedTime(DefaultIDTokenBuilder.java:584)
	at org.wso2.carbon.identity.openidconnect.DefaultIDTokenBuilder.buildIDToken(DefaultIDTokenBuilder.java:230)
	at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.issue(AccessTokenIssuer.java:268)
	at org.wso2.carbon.identity.oauth2.OAuth2Service.issueAccessToken(OAuth2Service.java:219)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.getAccessToken(OAuth2TokenEndpoint.java:246)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:188)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:249)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:209)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:265)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
	at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1756)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1715)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

I've checked the exception code and there are trying to get accessToken from OAuthCache, if failed then trying to get accessToken from database, if failed again then throw the exception.

I guess following config related to this issue:

identity.xml file stored in the <PRODUCT_HOME>/repository/conf/identity/ directory.   
The following elements were added under the <OAuth> element:   
```
<EnableOAuthCache>false</EnableOAuthCache>
```

The <CacheConfig> was replaced:
```
<CacheConfig>
    <CacheManager name="IdentityApplicationManagementCacheManager">
        <Cache name="AppAuthFrameworkSessionContextCache" enable="false" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="AuthenticationContextCache" enable="false" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="AuthenticationRequestCache" enable="false" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="AuthenticationResultCache" enable="false" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="AppInfoCache" enable="true" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="AuthorizationGrantCache" enable="false" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="OAuthCache" enable="false" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="OAuthSessionDataCache" enable="false" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="SAMLSSOParticipantCache" enable="false" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="SAMLSSOSessionIndexCache" enable="false" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="SAMLSSOSessionDataCache" enable="false" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="ServiceProviderCache" enable="true" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="ProvisioningConnectorCache" enable="true" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="ProvisioningEntityCache" enable="false" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="ServiceProviderProvisioningConnectorCache" enable="true" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="IdPCacheByAuthProperty" enable="true" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="IdPCacheByHRI" enable="true" timeout="1" capacity="5000" isDistributed="false" />
        <Cache name="IdPCacheByName" enable="true" timeout="1" capacity="5000" isDistributed="false" />
    </CacheManager>
</CacheConfig>
```

Also what's the difference between `EnableOAuthCache` under the `<OAuth>` element and `OAuthCache` & `OAuthSessionDataCache` under the `<CacheConfig>` element.

**Comment by snipking** [comment]
@mefarazath 

For the updated upgrade guide: 

1. The step `12` alert `if you are using MySQL 5.7 ...` but there's no `mysql_57.sql` in `<IS5.2.0_MIGRATION_TOOL_HOME>/dbscripts/identity/migration­5.1.0_to_5.2.0/` directory in the downloaded `migration_dbscripts-5.1.0_to_5.2.0_.zip` or `migrationscripts.zip` or `org.wso2.carbon.is.migrate.client-5.1.0-migration.zip` file. Also no `migration­5.1.0_to_5.2.0` folder in `<IS5.2.0_MIGRATION_TOOL_HOME>/dbscripts/identity/` directory. There's `migration-5.0.0_to_5.1.0` folder in `org.wso2.carbon.is.migrate.client-5.1.0-migration.zip` so I guess this file uploaded with wrong version.
2. In the `Configuration changes in IS 5.2.0` part. `EndpointConfig.properties` New Configuration should not start with `#`.
3. In the `Configuration changes in IS 5.2.0` part. `identity.xml` part did not point out where to set `<ISAnalytics>`.
4. In the `Configuration changes in IS 5.2.0` part. `identity.xml` `<OAuth>` part`<OIDCConsentPage>${carbon.protocol}://${carbon.host}:${carbon.management.port}/authenticationendpoint/oauth2_consent.do</OIDCConsentPage>` already exist in version 5.1.0
5. In the `Configuration changes in IS 5.2.0` part. The three added `<Claim>` did not explain which file to add. I guess it's `claim-config.xml` under `<Dialect dialectURI="http://wso2.org/claims">`.
6. `application-authentication.xml` part should inform add config under `<AuthenticatorConfigs>`.
7. `output-event-adapters.xml` part should inform add config under `<outputEventAdaptersConfig>`.
8. `registry.xml` part should inform add config under `<wso2registry>`.

**Comment by darshanasbg** [comment]
@shereneM Can you please check on these and update documentation as needed?

**Comment by isharak** [comment]
Since these two product versions are in maintenance mode those documents may not get updated, but related document concerns have addressed in the latest migration guides accordingly.
