### ISSUE TITLE
Delete user error

### ISSUE THREAD

**Issue by hefesita** [wso2/product-is#7825]
**Description:**
If the org.wso2.carbon.identity logger is put on debug an error will be presented on the administration interface. In the logs the most relevant error is :

Caused by: java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2519)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at org.wso2.carbon.identity.consent.mgt.handler.ConsentDeletionUserEventHandler.lambda$handleEvent$0(ConsentDeletionUserEventHandler.java:140)
        at org.wso2.carbon.identity.core.util.LambdaExceptionUtils.lambda$rethrowConsumer$0(LambdaExceptionUtils.java:144)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.wso2.carbon.identity.consent.mgt.handler.ConsentDeletionUserEventHandler.handleEvent(ConsentDeletionUserEventHandler.java:138) 
 
seems like a typo in the debug message in the class at line 140 there is a plus instead of a comma:

log.debug(String.format("Deleting receipt with ID : %s, issued for application %s" +
                            receiptListResponse.getConsentReceiptId(), receiptListResponse.getSpDisplayName())); 

**Affected Product Version:**
WSO2 IS 5.9.0

**Comment by janakamarasena** [comment]
Hi @hefesita, Thank you for reporting, this is fixed for the latest carbon-identity-framework master with https://github.com/wso2/carbon-identity-framework/pull/2810. Hence closing the issue.
