### ISSUE TITLE
IS-5.9.0 ADFS SAML federation fails with NPE

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-is#7833]
**Description:**
IS-5.9.0
WUM - 1582130771549
Stack trace
`
TID: [-1234] [] [2020-03-03 21:40:30,558] [15c9c327-4802-43a4-a332-683771781ee3] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework java.lang.NullPointerException
	at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.publishAuthenticationStepAttempt(AbstractApplicationAuthenticator.java:170)
	at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.process(AbstractApplicationAuthenticator.java:94)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:502)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handleResponse(DefaultStepHandler.java:476)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:175)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handleAuthenticationStep(GraphBasedSequenceHandler.java:417)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handleNode(GraphBasedSequenceHandler.java:172)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:127)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:155)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:239)
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53)`

Whenever the processAuthenticationResponse method of the outbound SAML authenticator throws an **AuthenticationFailedException** this might happen.
In this particular case, subject identifier is not available in the received SAML response. Therefore, we throw an exception. But later in the framework, we try to obtain the user name from the exception object. As assuming username is there in all the time is wrong, we have to do a null check before publishing the authentication step attempt.
`protected void publishAuthenticationStepAttempt(HttpServletRequest request, AuthenticationContext context,
                                                  User user, boolean success) {

        AuthenticationDataPublisher authnDataPublisherProxy = FrameworkServiceDataHolder.getInstance()
                .getAuthnDataPublisherProxy();
        if (authnDataPublisherProxy != null && authnDataPublisherProxy.isEnabled(context)) {
            boolean isFederated = this instanceof FederatedApplicationAuthenticator;
            Map<String, Object> paramMap = new HashMap<>();
            paramMap.put(FrameworkConstants.AnalyticsAttributes.USER, user);
            if (isFederated) {
                // Setting this value to authentication context in order to use in AuthenticationSuccess Event
                context.setProperty(FrameworkConstants.AnalyticsAttributes.HAS_FEDERATED_STEP, true);
                paramMap.put(FrameworkConstants.AnalyticsAttributes.IS_FEDERATED, true);
                paramMap.put(FrameworkConstants.AUTHENTICATOR, getName());
                user.setTenantDomain(context.getTenantDomain());`
In the above shared, last line should contain a null check as user not being avaialble is a common case in a federation failure flow.

Also, the data publishers should also not rely on user object upon a failure attempt publication. Checked the **AbstractAuthenticationDataPublisher** for this and it seem to have proper null check there.

**Solution**
Add null check in the **AbstractApplicationAuthenticator.publishAuthenticationStepAttempt()** method.

**Affected Product Version:**
5.9.0

**Comment by janakamarasena** [comment]
Related https://github.com/wso2/product-is/issues/7690
