### ISSUE TITLE
Throwing NULL pointer exception in SAML flow when trying to invoke the "updateCredentialByAdmin" admin service.

### ISSUE THREAD

**Issue by ShamodyaHashantha** [wso2/product-is#7838]
**Description:**
```
Caused by: java.lang.NullPointerException
        at org.wso2.carbon.identity.sso.saml.SAMLLogoutHandler.handleEvent(SAMLLogoutHandler.java:71)
        at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56)
        at org.wso2.carbon.identity.data.publisher.application.authentication.AuthnDataPublisherProxy.doPublishEvent(AuthnDataPublisherProxy.java:245)
        at org.wso2.carbon.identity.data.publisher.application.authentication.AuthnDataPublisherProxy.publishSessionTermination(AuthnDataPublisherProxy.java:211)
        at org.wso2.carbon.identity.application.authentication.framework.util.FrameworkUtils.publishSessionEvent(FrameworkUtils.java:1626)
        at org.wso2.carbon.identity.application.authentication.framework.services.SessionManagementService.terminateSession(SessionManagementService.java:96)
        at org.wso2.carbon.identity.application.authentication.framework.services.SessionManagementService.removeSession(SessionManagementService.java:43)
        at org.wso2.carbon.identity.application.authentication.framework.internal.impl.UserSessionManagementServiceImpl.terminateSessionsOfUser(UserSessionManagementServiceImpl.java:94)
        at org.wso2.carbon.identity.application.authentication.framework.internal.impl.UserSessionManagementServiceImpl.terminateSessionsOfUser(UserSessionManagementServiceImpl.java:67)
        at org.wso2.carbon.identity.mgt.listener.UserSessionTerminationListener.terminateSessionsOfUser(UserSessionTerminationListener.java:140)
        at org.wso2.carbon.identity.mgt.listener.UserSessionTerminationListener.doPostUpdateCredentialByAdmin(UserSessionTerminationListener.java:76)
        at org.wso2.carbon.user.core.common.AbstractUserStoreManager.updateCredentialByAdmin(AbstractUserStoreManager.java:2093)
        ... 66 more
```

When trying to update the credentials using **updateCredentialByAdmin** method in admin service it is throwing a null pointer exception.
This scenario is happening in the SAML flow. When a particular user is logged in to the SAML application (Dashboard) and admin try to update the credentials by invoking the admin service. Then it throws the null pointer and this happens only in the DEBUG enabling mode for SAML component(org.wso2.carbon.identity.sso.saml). As per the analyze the reason for this is, When updating credentials by admin service it terminates all user sessions and triggers the doPostUpdateCredentialByAdmin listener [1] & [2]. 
Then publish that session termination data as an event to AuthnDataPublisherProxy class in the identity data publisher authentication component. Once obtained the event it handles by the handleEvent method which is in the same component [3]. Thus as per the stack trace, this handleEvent method is calling from the handleEvent method in the identity-inbound-auth-SAML component [[4].
According to the handleEvent method implementation in the identity-inbound-auth-saml component, it checks the session termination event and retrieves the samlssoTokenId value from the particular event and it prints DEBUG logs when samlssoTokenId value is being null. Hence, when enabling DEBUG for the identity-inbound-auth-saml component it throws null pointer.

**Affected Product Version:**
IS-5.9.0

**Steps to reproduce:**
1- Start the WSO2IS-5.9.0 pack.
2- Enable the DEBUG mode for org.wso2.carbon.identity.sso.saml component. (By default this is in INFO mode).
2-Log into the management console and create a user.
4 - Log in to the IS dashboard by the created user.
5 - Try to update the user credentials by invoking "updateCredentialByAdmin" admin call.

[1] - https://github.com/wso2/carbon-kernel/blob/9e8dab23a45e7cb5ce9e038ff2d452c2ca9f14d1/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L2093
[2] - https://github.com/wso2/carbon-identity-framework/blob/cbc6f62748ee799b4deca1fe96fbd739c2b694c7/components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/listener/UserSessionTerminationListener.java#L76
[3] - https://github.com/wso2-extensions/identity-data-publisher-authentication/blob/fdf06c516b2db31528a083405fb27cd5de68caeb/components/org.wso2.carbon.identity.data.publisher.application.authentication/src/main/java/org/wso2/carbon/identity/data/publisher/application/authentication/AuthnDataPublisherProxy.java#L245
[4] - https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/e57267a425ff61c4254fcc2a90e160991aa82d57/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/SAMLLogoutHandler.java#L68

**Comment by rksk** [comment]
The same can be reproduced with the following steps in 5.10.0
- Enable debug for saml inbound
```
logger.org-wso2-carbon-identity-sso-saml.name=org.wso2.carbon.identity.sso.saml
logger.org-wso2-carbon-identity-sso-saml.level=DEBUG
```
- Create a new user and log into user-portal
- Try to change the password from the management console

**Comment by nipunthilakshan** [comment]
I will work on this
