### ISSUE TITLE
Admin portal login get broken when there are incorrect claims

### ISSUE THREAD

**Issue by darshanasbg** [wso2/product-is#7892]
**Description:**
Add claim through admin portal local claim section.
https://localhost:9443/admin-portal/local-dialect

Leave "Display Order" field blank.

Logout to the admin portal and login again.

Login get failed printing the following log in the backend

```
[2020-03-16 05:10:37,022] [703cc884-70c3-4dd7-8860-6df7b98b012a] ERROR {org.wso2.carbon.identity.recovery.endpoint.impl.ClaimsApiServiceImpl} - Error occurred in the server while performing the task. java.lang.NumberFormatException: For input string: "null"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.wso2.carbon.identity.claim.metadata.mgt.util.ClaimMetadataUtils.convertLocalClaimToClaimMapping(ClaimMetadataUtils.java:235)
	at org.wso2.carbon.identity.claim.metadata.mgt.DefaultClaimMetadataStore.getAllClaimMappings(DefaultClaimMetadataStore.java:484)
	at org.wso2.carbon.identity.core.IdentityClaimManager.getAllSupportedClaims(IdentityClaimManager.java:106)
	at org.wso2.carbon.identity.recovery.username.NotificationUsernameRecoveryManager.getIdentitySupportedClaims(NotificationUsernameRecoveryManager.java:121)
	at org.wso2.carbon.identity.recovery.endpoint.impl.ClaimsApiServiceImpl.claimsGet(ClaimsApiServiceImpl.java:50)
	at org.wso2.carbon.identity.recovery.endpoint.ClaimsApi.claimsGet(ClaimsApi.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor454.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
```

**Comment by darshanasbg** [comment]
Need to fix
1. Admin Portal UI
2. Backend claim validation

**Comment by emswbandara** [comment]
@AnuradhaSK will work on the backend validation.
