### ISSUE TITLE
Error occurs if 2 step authentication configured with identifier-first and basic authenticators in order

### ISSUE THREAD

**Issue by Abilashini** [wso2/product-is#7918]
**Description:**
If identifier-first and basic authenticators are configured in order, authentication fails after the 1st step. 
![image](https://user-images.githubusercontent.com/11737221/76879699-9f98ce80-689c-11ea-82b5-cd4b24232e15.png)

The below error stack can be observed in the server,
```
[2020-03-17 22:10:29,513] [8b4d6eb3-e012-47d2-802f-e69aa67d3cd8] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework java.lang.IllegalArgumentException: Invalid argument. authenticatedSubject : 
	at org.wso2.carbon.identity.application.authentication.framework.util.FrameworkUtils.prependUserStoreDomainToName(FrameworkUtils.java:1483)
	at org.wso2.carbon.identity.application.authentication.handler.identifier.IdentifierHandler.processAuthenticationResponse(IdentifierHandler.java:360)
	at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.process(AbstractApplicationAuthenticator.java:77)
	at org.wso2.carbon.identity.application.authentication.handler.identifier.IdentifierHandler.process(IdentifierHandler.java:132)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:506)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handleResponse(DefaultStepHandler.java:480)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:179)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:185)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:111)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:158)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:240)
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53)

```

**Comment by Abilashini** [comment]
This issue has been already reported at https://github.com/wso2/product-is/issues/7888
