### ISSUE TITLE
[ISSUE] updateCredentialByAdmin fails when SCIM is enabled for AD

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#7966]
**Describe the issue:**
We have "urn:ietf:params:scim:schemas:core:2.0:meta.lastModified" claim is mapped with AD immutable attribute "whenChanged". Since this attribute is automatically generated and maintained by the AD itself we have provided a new configuration to include a set of immutable attributes in https://github.com/wso2/product-is/issues/6949, so WSO2 IS will not try to update them.

But there, we have missed excluding those immutable attributes in the `doSetUserClaimValue()` method. Hence, we try to update a user password from the management console, the following error is logged.

```
TID: [-1234] [] [2020-03-27 06:36:28,874] DEBUG {org.wso2.carbon.user.core.ldap.ActiveDirectoryUserStoreManager} - One or more attribute values provided are incompatible for user : abcPlease check and try again.
javax.naming.directory.InvalidAttributeValueException: [LDAP: error code 21 - 00000057: LdapErr: DSID-0C090D6F, comment: Error in attribute conversion operation, data 0, v2580]; remaining name 'CN=abc'
at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3148)
at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3081)
at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2888)
at com.sun.jndi.ldap.LdapCtx.c_modifyAttributes(LdapCtx.java:1408)
at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_modifyAttributes(ComponentDirContext.java:257)
at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.modifyAttributes(PartialCompositeDirContext.java:167)
at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.modifyAttributes(PartialCompositeDirContext.java:156)
at org.wso2.carbon.user.core.ldap.ActiveDirectoryUserStoreManager.doSetUserClaimValue(ActiveDirectoryUserStoreManager.java:712)
at org.wso2.carbon.user.core.common.AbstractUserStoreManager.setUserClaimValue(AbstractUserStoreManager.java:2390)
at org.wso2.carbon.identity.scim2.common.listener.SCIMUserOperationListener.doPostUpdateCredentialByAdmin(SCIMUserOperationListener.java:125)
at org.wso2.carbon.user.core.common.AbstractUserStoreManager.updateCredentialByAdmin(AbstractUserStoreManager.java:2102)
at org.wso2.carbon.user.core.common.AbstractUserStoreManager.updateCredentialByAdmin(AbstractUserStoreManager.java:1952)
```

**How to reproduce:**
1. Configure an AD userstore
2. Enable SCIM
3. Map "urn:ietf:params:scim:schemas:core:2.0:meta.lastModified" claim  with AD immutable attribute "whenChanged"
4. Try to update user password from the management console

**Environment information** 
 - Product Version: IS 5.7.0
 - Userstore: AD

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/6949

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
