### ISSUE TITLE
Calling template API GET request gives 500 instead 404

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#7986]
**Describe the issue:**
When template GET request[1] made to the server without creating any template, API gives 500 Internal Server error. This should be HTTP 404 not found.

**How to reproduce:**
1. Configure fresh WSO2 IS pack [to use Configuration Management REST APIs](https://is.docs.wso2.com/en/next/develop/using-the-configuration-management-rest-apis/)(run the DB scripts).
2. Make a GET request to the following URL[1]. 500 internal server error is retrieved, and the following log can be observed.
```
[2020-03-30 14:37:35,251] [0229e493-7a99-455a-ba3d-2ddc3682c0da] ERROR {org.wso2.carbon.identity.api.server.idp.v1.core.ServerIdpManagementService} - errorCode: IDP-65050 | message: Error occured while listing identity provider templates. org.wso2.carbon.identity.template.mgt.exception.TemplateManagementServerException: Error occurred while retrieving templates of type IDP_TEMPLATE of the tenant: carbon.super from the database.
	at org.wso2.carbon.identity.template.mgt.util.TemplateMgtUtils.handleServerException(TemplateMgtUtils.java:69)
	at org.wso2.carbon.identity.template.mgt.TemplateManagerImpl.listTemplates(TemplateManagerImpl.java:304)
	at org.wso2.carbon.identity.api.server.idp.v1.core.ServerIdpManagementService.getIDPTemplates(ServerIdpManagementService.java:841)
	at org.wso2.carbon.identity.api.server.idp.v1.impl.IdentityProvidersApiServiceImpl.getIDPTemplates(IdentityProvidersApiServiceImpl.java:129)
	at org.wso2.carbon.identity.api.server.idp.v1.IdentityProvidersApi.getIDPTemplates(IdentityProvidersApi.java:325)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:168)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:233)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:110)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:94)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.identity.configuration.mgt.core.exception.ConfigurationManagementClientException: Resource type with the name: IDP_TEMPLATE does not exists.
	at org.wso2.carbon.identity.configuration.mgt.core.util.ConfigurationUtils.handleClientException(ConfigurationUtils.java:58)
	at org.wso2.carbon.identity.configuration.mgt.core.ConfigurationManagerImpl.getResourceType(ConfigurationManagerImpl.java:238)
	at org.wso2.carbon.identity.configuration.mgt.core.ConfigurationManagerImpl.getResourcesByType(ConfigurationManagerImpl.java:134)
	at org.wso2.carbon.identity.template.mgt.TemplateManagerImpl.listTemplates(TemplateManagerImpl.java:298)
	... 59 more
```
[1] [https://localhost:9443/t/{{tenant-domain}}/api/server/v1/identity-providers/templates](https://localhost:9443/t/{{tenant-domain}}/api/server/v1/identity-providers/templates)

**Expected behavior:**
This happend since the Resource Type `IDP_TEMPLATE` is not created yet; It gets created with the first template creation request. The expected scenario is to have an HTTP 404 response instead of HTTP 500 error, for this scenario.
 
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0-m11
 - OS: Ubuntu 18.04
 - Database: H2
---

**Comment by emswbandara** [comment]
IMO, saying that applications/templates does not exist (404) implies to the client that the invoked endpoint is wrong. Since this error is reproduced due to a configuration issue, i think the better solution is to return an empty response if template type is not created yet. WDYT?

**Comment by tharindu-bandara** [comment]
> IMO, saying that applications/templates does not exist (404) implies to the client that the invoked endpoint is wrong. Since this error is reproduced due to a configuration issue, i think the better solution is to return an empty response if template type is not created yet. WDYT?

+1 for the empty response.
