### ISSUE TITLE
[ISSUE] Error on SAML2.0 Artifact Binding

### ISSUE THREAD

**Issue by hefesita** [wso2/product-is#8002]
**Describe the issue:**
Trying to connect an SP using SAML 2.0 Artifact Binding and I get the following error:
ERROR {org.wso2.carbon.identity.sso.saml.processors.SPInitSSO Authn RequestProcessor} - Error processing the authentication request org.wso2.carbon.identity.sso.saml.exception.ArtifactBindingException: Error while storing SAML2 artifact information.
We are using IS5.9.0 and a PostgreSQL 11 database created with the scripts provided by you..

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.9.0
 - OS: Centos 7
 - Database: PostgreSQL

**Comment by mefarazath** [comment]
Will you be able to post a full stack trace?

**Comment by hefesita** [comment]
This is the PostgreSQL server error log:
ERROR:  relation "idn_saml2_artifact_store" does not exist at character 13
STATEMENT:  INSERT INTO IDN_SAML2_ARTIFACT_STORE(SOURCE_ID, MESSAGE_HANDLER, AUTHN_REQ_DTO, SESSION_ID, INIT_TIMESTAMP, EXP_TIMESTAMP, ASSERTION_ID) VALUES ($1, $2, $3, $4, $5, $6, $7)
        RETURNING "id"

On WSO2IS log there is no other detail:
[9702d3cd-72fb-4025-b4d1-676db3b1ae82] ERROR {org.wso2.carbon.identity.sso.saml.processors.SPInitSSOAuthnRequestProcessor} - Error processing the authentication request org.wso2.carbon.identity.sso.saml.exception.ArtifactBindingException: Error while storing SAML2 artifact information.
        at org.wso2.carbon.identity.sso.saml.dao.impl.SAML2ArtifactInfoDAOImpl.storeArtifactInfo(SAML2ArtifactInfoDAOImpl.java:72)
        at org.wso2.carbon.identity.sso.saml.builders.SAMLArtifactBuilder.persistSAML2ArtifactInfo(SAMLArtifactBuilder.java:137)
        at org.wso2.carbon.identity.sso.saml.builders.SAMLArtifactBuilder.buildSAML2Artifact(SAMLArtifactBuilder.java:110)
        at org.wso2.carbon.identity.sso.saml.processors.SPInitSSOAuthnRequestProcessor.process(SPInitSSOAuthnRequestProcessor.java:147)
        at org.wso2.carbon.identity.sso.saml.SAMLSSOService.authenticate(SAMLSSOService.java:178)
        at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleAuthenticationReponseFromFramework(SAMLSSOProviderServlet.java:1155)
        at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleRequest(SAMLSSOProviderServlet.java:253)
        at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.doGet(SAMLSSOProviderServlet.java:143)
        at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.sendRequestToFramework(SAMLSSOProviderServlet.java:1561)
        at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.handleRequest(SAMLSSOProviderServlet.java:210)
        at org.wso2.carbon.identity.sso.saml.servlet.SAMLSSOProviderServlet.doPost(SAMLSSOProviderServlet.java:156)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:81)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:72)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100)
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116)
        at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by mefarazath** [comment]
Looks like its the same issue reported in https://github.com/wso2/product-is/issues/3735

**Comment by hefesita** [comment]
The dbscripts in IS 5.9.0 have corrected the issue so it is not about the sequence. could you please tell me in which database does the SAML2.0 artifact binding event tries to write data?

**Comment by hefesita** [comment]
looking at my PostgreSQL server transactions codes, I see the event going into the consent db:

```
2020-04-01 12:36:44.362 UTC [**6815**] LOG:  connection received: host=xxx port=xx
2020-04-01 12:36:44.364 UTC [**6815**] LOG:  connection authorized: user=xxx database=consent_mgt_db
2020-04-01 12:41:35.430 UTC [7092] LOG:  connection received: host=xxx port=xx
2020-04-01 12:41:35.431 UTC [7092] LOG:  connection authorized: user=xxx database=identity_db
2020-04-01 12:57:25.778 UTC [**6815**] ERROR:  relation "idn_saml2_artifact_store" does not exist at character 13
2020-04-01 12:57:25.778 UTC [**6815**] STATEMENT:  INSERT INTO IDN_SAML2_ARTIFACT_STORE(SOURCE_ID, MESSAGE_HANDLER, AUTHN_REQ_DTO, SESSION_ID, INIT_TIMESTAMP, EXP_TIMESTAMP, ASSERTION_ID) VALUES ($1, $2, $3, $4, $5, $6, $7)
        RETURNING "id"
2020-04-01 12:59:01.729 UTC [**6815**] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2020-04-01 12:59:01.729 UTC [6815] STATEMENT:  SELECT 1
```

Looking at the second line from the log, the database shouldn't be in the identity db?

**Comment by mefarazath** [comment]
It would try to write the data to the database pointed in [database.identity_db] section of the deployment.toml file. ie.

**Comment by mefarazath** [comment]
@hefesita Can you verify whether the table IDN_SAML2_ARTIFACT_STORE is present in the identity_db?

**Comment by hefesita** [comment]
yes, it is present there, I checked it

**Comment by mefarazath** [comment]
Hmm.. strange. A quick search led me to https://stackoverflow.com/questions/41202225/postgresql-error-relation-does-not-exist-on-insert-statement

Can you give the explanations and solutions here a try?

**Comment by hefesita** [comment]
I already checked this post and all the tables are all public. Also other events in the system work ok.

**Comment by hefesita** [comment]
I have created the table in the consent_mgt_db and now the artifact is stored, but I think it is a bug since it should not be stored there.

**Comment by mefarazath** [comment]
@hefesita 
Yes; it Looks like your observation was right. There is a bug in the code that tries to get a connection to consent management DBs and persist the SAML artifact there.

https://github.com/wso2-extensions/identity-inbound-auth-saml/blob/7f7aba8691433a776e39b533d1dbbea076c3cd74/components/org.wso2.carbon.identity.sso.saml/src/main/java/org/wso2/carbon/identity/sso/saml/dao/impl/SAML2ArtifactInfoDAOImpl.java#L54

JdbcUtils class belongs to the consent management related components.

This needs to be fixed. The same bug should be there in the other versions (5.10.0 and master) as well.

**Comment by mefarazath** [comment]
@hefesita As a workaround, the functionality should work with the table created in the consent DB since both store and query paths use the same database util class hence the same data source.

**Comment by hefesita** [comment]
Yes, we will leave the table created in the consent db.
