### ISSUE TITLE
[ISSUE] Username recovery fails when user is on a secondary userstore

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8014]
**Describe the issue:**
Username recovery fails with following log when user is on a secondary userstore. The cause is that it tries to invoke `getUserClaimValues()` by passing username with userstore domain (TEST/sajith) to `userStoreManager` object which was created from `AbstractUserStoreManager.getSecondaryUserStoreManager()` at `org.wso2.carbon.identity.event.handler.notification.util.NotificationUtil.getUserClaimValues()`.

```
[2020-04-03 01:46:30,941] DEBUG {org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager} -  User: TEST/sajith exist: false
[2020-04-03 01:46:30,943] ERROR {org.wso2.carbon.identity.event.handler.notification.util.NotificationUtil} -  Error occurred while retrieving user claim values for user TEST/sajith in user store test in tenant carbon.super
org.wso2.carbon.user.core.UserStoreException: 30007 - UserNotFound: User TEST/sajith does not exist in: test
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:185)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValues(AbstractUserStoreManager.java:920)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValues(AbstractUserStoreManager.java:94)
	at org.wso2.carbon.identity.event.handler.notification.util.NotificationUtil.getUserClaimValues(NotificationUtil.java:68)
	at org.wso2.carbon.identity.event.handler.notification.util.NotificationUtil.getUserClaimValues(NotificationUtil.java:109)
	at org.wso2.carbon.identity.event.handler.notification.util.NotificationUtil.buildNotification(NotificationUtil.java:247)
	at org.wso2.carbon.identity.event.handler.notification.NotificationHandler.handleEvent(NotificationHandler.java:64)
	at org.wso2.carbon.identity.event.services.IdentityEventServiceImpl.handleEvent(IdentityEventServiceImpl.java:56)
	at org.wso2.carbon.identity.recovery.internal.service.impl.username.UsernameRecoveryManagerImpl.triggerNotification(UsernameRecoveryManagerImpl.java:301)
	at org.wso2.carbon.identity.recovery.internal.service.impl.username.UsernameRecoveryManagerImpl.initiate(UsernameRecoveryManagerImpl.java:87)
	at org.wso2.carbon.identity.recovery.username.NotificationUsernameRecoveryManager.initiateUsernameRecovery(NotificationUsernameRecoveryManager.java:183)
	at org.wso2.carbon.identity.recovery.username.NotificationUsernameRecoveryManager.verifyUsername(NotificationUsernameRecoveryManager.java:152)
	at org.wso2.carbon.identity.recovery.endpoint.impl.RecoverUsernameApiServiceImpl.recoverUsernamePost(RecoverUsernameApiServiceImpl.java:36)
	at org.wso2.carbon.identity.recovery.endpoint.RecoverUsernameApi.recoverUsernamePost(RecoverUsernameApi.java:48)

Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:175)
	... 74 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:178)
	... 76 more
Caused by: org.wso2.carbon.user.core.UserStoreException: 30007 - UserNotFound: User TEST/sajith does not exist in: test
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValues(AbstractUserStoreManager.java:937)
	... 81 more

```

**How to reproduce:**
* Try username recovery for a user on a secondary userstore

**Environment information** (_Please complete the following information; remove  any unnecessary fields_)
 - Product Version: IS 5.7.0

**Comment by madurangasiriwardena** [comment]
Depends on https://github.com/wso2/product-is/issues/7677
