### ISSUE TITLE
[ISSUE] IWA Kerberos Authenticator will not work with IS-5.9.0 due to a bug in the Tomcat version used

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#8028]
**Describe the issue:**
IWA Kerberos Authenticator will not work with IS-5.9.0 due to a bug in the Tomcat version used

**How to reproduce:**
Setup IWA Kerberos Authenticator by following the document[1], try out the authenticator.
you will observe the following error even though the client initiating the authentication flow is not on the same machine that the Identity Server is running on.
```
[2020-04-03 20:12:04,844] [1584e6e6-4044-4260-9513-adbddceda0a1] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/].[bridgeservlet]} - Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception [Cannot handle IWA authentication request from the same host as the KDC] with root cause javax.servlet.ServletException: Cannot handle IWA authentication request from the same host as the KDC
	at org.wso2.carbon.identity.application.authenticator.iwa.servlet.IWAServlet.doPost(IWAServlet.java:68)
	at org.wso2.carbon.identity.application.authenticator.iwa.servlet.IWAServlet.doGet(IWAServlet.java:47)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
```

**Cause:**
In the IWA Kerberos authenticator, there is a validation carried out to prevent the client and Identity server from running on the same host[2] but due to a bug[3] in the tomcat version(9.0.22)  used, the req.getLocalAddr() returns the remote address, therefore, the check in[2] always returns true causing the above error.

[1]https://is.docs.wso2.com/en/latest/learn/configuring-iwa-on-linux/
[2]https://github.com/wso2-extensions/identity-local-auth-iwa-kerberos/blob/master/components/org.wso2.carbon.identity.application.authenticator.iwa/src/main/java/org/wso2/carbon/identity/application/authenticator/iwa/servlet/IWAServlet.java#L65
[3]https://bz.apache.org/bugzilla/show_bug.cgi?id=63570

**Comment by madurangasiriwardena** [comment]
This issue is not reproducible in the 5.10.0 or later versions since the Tomcat version is upgraded to 9.0.31 [1].

[1] https://github.com/wso2/orbit/pull/410
