### ISSUE TITLE
Add New Purpose gives "Error while loading purposes info."

### ISSUE THREAD

**Issue by gokkep** [wso2/product-is#8040]
[wso2carbon.log](https://github.com/wso2/product-is/files/4439290/wso2carbon.log)
**Description:**
I am trying to follow the guide how to configure Self registration.
I am using the latest docker images from Github and using the GA releases.
Everything is used out of the box, following the documentation, but getting the error.

**Note**
The error only seems to be presented in the user interface, not in the log.

**Suggested Labels:**
Self registration failure

**Suggested Assignees:**

**Affected Product Version:**
WSO2 Identity Server 5.10.0

**OS, DB, other environment details and versions:**    
Docker on Linux

**Steps to reproduce:**
Check out docker files to be able to use docker-compose up
Add the following lines to <IS_HOME>/repository/conf/deployment.toml

[event.default_listener.identity_mgt]
priority= "50"
enable = false
[event.default_listener.governance_identity_mgt]
priority= "95"
enable = true
[event.default_listener.governance_identity_store]
priority= "97"
enable = true

[identity_mgt.user_onboarding]
enable_email_verification = true 
lock_on_creation=true

[output_adapter.email]
from_address= "xxxxxxx"
username= "xxxxxxx"
password= "xxxxxxxx"
hostname= "smtp.gmail.com"
port= 587
enable_start_tls= true
enable_authentication= true

Then restart the docker containers, go into the carbon portal and follow the steps in the documentation. When executing the step 6.e in this doc https://is.docs.wso2.com/en/next/learn/self-registration/ , I get the error of this issue.

**Comment by senthalan** [comment]
Could you update the issue with the complete error trace from the wso2carbon.log file

**Comment by gokkep** [comment]
I attached the log file in the original issue, although it seems that there is nothing reported.

**Comment by senthalan** [comment]
According to the logs, the issue seems to the consent related tables are not created in the database.

```
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s'SELECT R.CONSENT_RECEIPT_ID, R.LANGUAGE, R.PII_PRINCIPAL_ID, R.PRINCIPAL_TENANT_ID, R.STATE,RS.SP_DISPLAY_NAME,RS.SP_DESCRIPTION FROM CM_RECEIPT R INNER JOIN CM_RECEIPT_SP_ASSOC RS ON R.CONSENT_RECEIPT_ID=RS.CONSENT_RECEIPT_ID WHERE PII_PRINCIPAL_ID LIKE ? AND PRINCIPAL_TENANT_ID =? AND SP_NAME LIKE ? AND STATE LIKE ? ORDER BY ID  ASC LIMIT ? OFFSET ?
	at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.executeQuery(JdbcTemplate.java:169)
	at org.wso2.carbon.consent.mgt.core.dao.impl.ReceiptDAOImpl.searchWithoutSpTenant(ReceiptDAOImpl.java:382)
	at org.wso2.carbon.consent.mgt.core.dao.impl.ReceiptDAOImpl.searchReceipts(ReceiptDAOImpl.java:293)
	... 63 more
Caused by: java.sql.SQLSyntaxErrorException: Table 'WSO2IS_IDENTITY_DB.CM_RECEIPT' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy55.executeQuery(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.executeQuery(JdbcTemplate.java:154)
```

**How to fix**
To fix this issue make sure you have executed the <IS-HOME>/dbscripts/consent/mysql.sql scripts to the WSO2_IDENTITY_DB. Refer to this [documentation](https://is.docs.wso2.com/en/latest/setup/changing-to-mysql/) for more information

**Comment by ruwanta** [comment]
Hi All,
It would be better ti use dev mailing list or slack channel to ask questions like this.
Better to keep git issue for bug reporting or feature/improvement discussions.

**Comment by gokkep** [comment]
Okay I moved the conversation about this issue to Slack channel WSO2IS. Other people were having the same issue. Thanks for the info about the communication channels, this slack channel is not quite clear from your web sites.
