### ISSUE TITLE
IS crashed on NULL pointer exception when password starts with '&" character in output_adapter.email conf

### ISSUE THREAD

**Issue by gokkep** [wso2/product-is#8095]
**Describe the issue:**
When the deployment.toml configuration file is extended with a configuration for self registration and the [output_adapter.email] part has a '&' as the first character for the password and IS is rebooted, it will crash.

**How to reproduce:**
First setup IS with the docker containers and the default deployment.toml. Everything will startup fine.

Then change the deployment.toml for a configuration for self registration (see, https://is.docs.wso2.com/en/next/learn/self-registration/) and using the following for the email smtp config:

[output_adapter.email]
from_address= "xxxxx"
username= "xxxxx"
password= "&blablabl"
hostname= "smtp.xx.xxx"
port= xxxx
enable_start_tls= true
enable_authentication= true

Restart the docker containers and IS will crash.

**Expected behavior:**
Password should be able to contain this character and IS should not crash.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
Docker based on Ubuntu.

---

### Optional Fields

**Log**
TID: [-1234] [] [2020-04-15 14:06:54,464] []  INFO {openjpa.Runtime} - Starting OpenJPA 2.2.0-wso2v1
TID: [-1234] [] [2020-04-15 14:06:54,465] []  INFO {openjpa.jdbc.JDBC} - Using dictionary class "org.apache.openjpa.jdbc.sql.H2Dictionary" (H2 1.4.199 (2019-03-13) ,H2 JDBC Driver 1.4.199 (2019-03-13)).
TID: [-1234] [] [2020-04-15 14:06:54,547] []  INFO {org.wso2.carbon.core.internal.StartupFinalizerServiceComponent} - Server           :  WSO2 Identity Server-5.10.0
TID: [-1234] [] [2020-04-15 14:06:54,548] []  INFO {org.wso2.carbon.core.internal.StartupFinalizerServiceComponent} - WSO2 Carbon started in 66 sec
TID: [-1234] [] [2020-04-15 14:06:55,359] []  INFO {org.apache.jasper.servlet.TldScanner} - At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
TID: [-1234] [] [2020-04-15 14:06:55,415] []  INFO {org.wso2.carbon.ui.internal.CarbonUIServiceComponent} - Mgt Console URL  : https://localhost:9443/carbon/
TID: [2020-04-15 14:07:51,420]  WARN {org.wso2.config.mapper.ConfigParser} - Configurations Changed in :repository/conf/deployment.toml {org.wso2.config.mapper.ConfigParser}
TID: [2020-04-15 14:07:51,423]  WARN {org.wso2.config.mapper.ConfigParser} - Overriding files in configuration directory /home/wso2carbon/wso2is-5.10.0 {org.wso2.config.mapper.ConfigParser}
TID: [2020-04-15 14:07:52,262]  INFO {org.wso2.config.mapper.ConfigParser} - Writing Metadata Entries... {org.wso2.config.mapper.ConfigParser}
TID: [-1234] [] [2020-04-15 14:07:59,589] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Starting WSO2 Carbon...
TID: [-1234] [] [2020-04-15 14:07:59,601] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Operating System : Linux 5.5.13-arch2-1, amd64
TID: [-1234] [] [2020-04-15 14:07:59,602] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Home        : /opt/java/openjdk
TID: [-1234] [] [2020-04-15 14:07:59,602] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Version     : 11.0.6
TID: [-1234] [] [2020-04-15 14:07:59,603] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java VM          : OpenJDK 64-Bit Server VM 11.0.6+10,AdoptOpenJDK
TID: [-1234] [] [2020-04-15 14:07:59,603] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Carbon Home      : /home/wso2carbon/wso2is-5.10.0
TID: [-1234] [] [2020-04-15 14:07:59,603] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Temp Dir    : /home/wso2carbon/wso2is-5.10.0/tmp
TID: [-1234] [] [2020-04-15 14:07:59,603] []  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - User             : wso2carbon, en-US, GMT
TID: [-1] [] [2020-04-15 14:07:59,305] []  INFO {org.ops4j.pax.logging.spi.support.EventAdminConfigurationNotifier} - Sending Event Admin nofification (configuration successful) to org/ops4j/pax/logging/Configuration
TID: [-1] [] [2020-04-15 14:07:59,840] []  INFO {org.wso2.carbon.crypto.provider.internal.DefaultCryptoProviderComponent} - 'CryptoService.Secret' property has not been set. 'org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider' won't be registered as an internal crypto provider. Please set the secret if the provider needs to be registered.
TID: [-1] [] [2020-04-15 14:08:00,077] []  INFO {org.wso2.carbon.event.output.adapter.kafka.internal.ds.KafkaEventAdapterServiceDS} - Successfully deployed the Kafka output event adaptor service
TID: [-1] [] [2020-04-15 14:08:00,851] []  INFO {org.wso2.carbon.identity.oauth.uma.grant.internal.UMA2GrantServiceComponent} - Policy evaluator registered successfully: DefaultPolicyEvaluator
TID: [-1] [] [2020-04-15 14:08:00,851] []  INFO {org.wso2.carbon.identity.oauth.uma.grant.internal.UMA2GrantServiceComponent} - UMA Grant component activated successfully.
TID: [-1234] [] [2020-04-15 14:08:01,403] []  INFO {org.wso2.carbon.ldap.server.configuration.LDAPConfigurationBuilder} - KDC server is disabled.
TID: [-1234] [] [2020-04-15 14:08:04,529] []  INFO {org.apache.directory.server.KERBEROS_LOG} - KeyDerivation Interceptor initialized
TID: [-1] [] [2020-04-15 14:08:04,878] []  INFO {org.wso2.carbon.mex.internal.Office365SupportMexComponent} - Office365Support MexServiceComponent bundle activated successfully..
TID: [-1] [] [2020-04-15 14:08:04,897] []  INFO {org.wso2.carbon.mex2.internal.DynamicCRMCustomMexComponent} - DynamicCRMSupport MexServiceComponent bundle activated successfully.
TID: [-1] [] [2020-04-15 14:08:05,247] [] ERROR {org.wso2.carbon.event.output.adapter.core} - [SCR] Exception occurred while unbinding reference Reference[name = output.event.adapter.tracker.service, interface = org.wso2.carbon.event.output.adapter.core.OutputEventAdapterFactory, policy = dynamic, cardinality = 0..n, target = null, bind = setEventAdapterType, unbind = unSetEventAdapterType]
	Details:
	Problematic reference = Reference[name = output.event.adapter.tracker.service, interface = org.wso2.carbon.event.output.adapter.core.OutputEventAdapterFactory, policy = dynamic, cardinality = 0..n, target = null, bind = setEventAdapterType, unbind = unSetEventAdapterType]
	of service component = event.output.adapter.service
	component implementation class = org.wso2.carbon.event.output.adapter.core.internal.ds.OutputEventAdapterServiceDS
	located in bundle with symbolic name = org.wso2.carbon.event.output.adapter.core
	bundle location = reference:file:../plugins/org.wso2.carbon.event.output.adapter.core_5.2.24.jar java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ComponentReference.unbind(ComponentReference.java:476)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.unbindReference(ServiceComponentProp.java:617)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.unbind(ServiceComponentProp.java:262)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:350)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.securevault.internal.SecretManagerInitializerComponent.activate(SecretManagerInitializerComponent.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.event.output.adapter.core.internal.ds.OutputEventAdapterServiceDS.unSetEventAdapterType(OutputEventAdapterServiceDS.java:111)
	... 38 more

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
