### ISSUE TITLE
NPE in Email OTP authenticator

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8406]
**Describe the issue:**
With wso2/product-is#7474 we have added BackupCode support for Email OTP authenticator. Hence the following property has to be added in the OTP configuration. Currently, if the config is not there, it throws an NPE when we enter an invalid OTP.
```
BackupCode = ture
```

```
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework java.lang.NullPointerException
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.isBackupCodeEnabled(EmailOTPAuthenticator.java:435)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.processAuthenticationResponse(EmailOTPAuthenticator.java:313)
	at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.process(AbstractApplicationAuthenticator.java:77)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.process(EmailOTPAuthenticator.java:139)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:506)
```

**Environment information** 
 - Product Version: IS 5.10.0

**Related**
Doc issue: https://github.com/wso2/docs-is/issues/1731

**Comment by rksk** [comment]
This has been fixed with the PR https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/79

Now we handle this null correctly at https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blame/7ea4913f5aae447ff6caf0f8bbf25954fac42ffa/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L456
