### ISSUE TITLE
EmailOTP is not working for secondary users if usecase config is not added

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#8416]
EmailOTP is not working for secondary users if `usecase` property is not added in deployment.toml file.

```
[2020-05-28 11:10:03,234] [31a693c9-94b4-475f-aa40-bf8e5d686aa5] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: Email OTP authentication failed for the local user usert
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.handleEmailOTPForLocalUser(EmailOTPAuthenticator.java:1234)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.initiateAuthenticationRequest(EmailOTPAuthenticator.java:218)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.process(EmailOTPAuthenticator.java:127)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:506)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:271)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handleAuthenticationStep(GraphBasedSequenceHandler.java:417)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handleNode(GraphBasedSequenceHandler.java:172)
	at
Caused by: org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: Failed while trying to access userRealm of the user : usert
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.isEmailOTPDisableForUser(EmailOTPAuthenticator.java:1189)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.handleEmailOTPForLocalUser(EmailOTPAuthenticator.java:1215)
	... 62 more
Caused by: org.wso2.carbon.user.core.UserStoreException: 30007 - UserNotFound: User usert does not exist in: PRIMARY
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:205)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValues(AbstractUserStoreManager.java:1758)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.isEmailOTPDisableForUser(EmailOTPAuthenticator.java:1178)

```

If usecase property is not configured then it will go through this https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L193 line. Here the usename does not have userstore domain. So logging with secondary users is failing

According to the comments, this usecase property is not mandatory. https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L181.

**Comment by JenniferJohnson89** [comment]
I noticed that there is a similar problem at https://github.com/wso2/product-is. Perhaps we can refer to [this issue](https://github.com/wso2/product-is/issues/4557) to find more context about the bug. 
Or maybe this can help us find the faulty lines and we can also refer to the [fix](https://github.com/wso2/carbon-identity-framework/pull/2430) for the bug?

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
