### ISSUE TITLE
Email OTP works only on super tenant primary userstore

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#8433]
**Describe the issue:**
The following error is thrown for any user who is not on the super tenant and primary userstore.

At [1], we are getting `authenticatedUser.getUserName();` which does not include tenant domain nor userstore domain. Hence the flow breaks while trying to get user email.

The line should be fixed as follows.
```
username = authenticatedUser.toFullQualifiedUsername();
```

```
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} - Authentication failed exception! org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: Email OTP authentication failed for the local user sajith2
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.handleEmailOTPForLocalUser(EmailOTPAuthenticator.java:1234)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.initiateAuthenticationRequest(EmailOTPAuthenticator.java:218)
	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.process(EmailOTPAuthenticator.java:127)

	... 65 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:194)
	... 67 more
Caused by: org.wso2.carbon.user.core.UserStoreException: 30007 - UserNotFound: User sajith2 does not exist in: PRIMARY
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValue(AbstractUserStoreManager.java:1575)
	... 72 more
```

**How to reproduce:**
* try out Email OTP for a user on a secondary userstore

**Environment information**
 - Product Version: IS 5.10.0

[1] https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/382dceabc57bfd154eea6ddbb71a3b06e90df550/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L193

**Comment by rksk** [comment]
closing duplicate
