### ISSUE TITLE
Idle account suspension doesn't work for embedded ldap

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#8476]
**Describe the issue:**
[Idle account suspension](https://is.docs.wso2.com/en/latest/learn/user-account-suspension) feature does not work with embedded LDAP. 

**How to reproduce:**
1. Configure the idle account suspension feature as in the [document](https://is.docs.wso2.com/en/latest/learn/user-account-suspension).
2. Change the idle account suspension and notification time as per your preference.
3. Create a claim non-identity claim **http://wso2.org/claims/lastLogin** and map It to lastLoginTime attribute.
4. Create a few user accounts in the primary user store and set the last login time of those accounts to a value that matches cases in step 2. 
5. Set account suspension trigger time to the desired time.
6. Start the server
7. At the suspension trigger time below exception is thrown.
```
   [2020-06-09 20:16:00,640] [] ERROR {org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread} - Unable to disable user accounts org.wso2.carbon.identity.base.IdentityException: Error occurred while retrieving users for account disable
	at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:60)
	at org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread.lockAccounts(AccountValidatorThread.java:205)
	at org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread.handleTask(AccountValidatorThread.java:158)
	at org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread.run(AccountValidatorThread.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.identity.account.suspension.notification.task.exception.AccountSuspensionNotificationException: Failed to filter users from LDAP user store.
	at org.wso2.carbon.identity.account.suspension.notification.task.ldap.LDAPNotificationReceiversRetrieval.getNotificationReceivers(LDAPNotificationReceiversRetrieval.java:137)
	at org.wso2.carbon.identity.account.suspension.notification.task.NotificationReceiversRetrievalManager.getReceivers(NotificationReceiversRetrievalManager.java:65)
	at org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread.lockAccounts(AccountValidatorThread.java:201)
	... 9 more
Caused by: javax.naming.NamingException: [LDAP: error code 80 - OTHER: failed for MessageType : SEARCH_REQUEST
Message ID : 2
    SearchRequest
        baseDn : 'ou=Users,dc=wso2,dc=org'
        filter : '(&(lastLoginTime>=1590331560000:[∞])(lastLoginTime<=1590417960000:[∞]))'
        scope : whole subtree
        typesOnly : false
        Size Limit : no limit
        Time Limit : no limit
        Deref Aliases : deref Always
        attributes : 
org.apache.directory.api.ldap.model.message.SearchRequestImpl@353d438    ManageDsaITImpl Control
        Type OID    : '2.16.840.1.113730.3.4.2'
        Criticality : 'false'
'
: null]; remaining name 'ou=Users,dc=wso2,dc=org'
	at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3198)
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3100)
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2891)
	at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1846)
	at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1769)
	at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:392)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:358)
	at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:341)
	at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:267)
	at org.wso2.carbon.identity.account.suspension.notification.task.ldap.LDAPNotificationReceiversRetrieval.getNotificationReceivers(LDAPNotificationReceiversRetrieval.java:111)
	... 11 more
```

**Expected behavior:**
Account suspension notifications should be sent to the user.

_Note:_ `deployment.toml` I used can be found [here](https://gist.github.com/ayshsandu/54f77c52ba1b193e1af99a0009050299.js)

- At this time, AccountSuspension.UseIdentityClaims is set to false, in order to make sure lastLoginTime is stored in the leap. 
- Alternatively you can change the below setting
`[event.default_listener.governance_identity_store]
data_store = "org.wso2.carbon.identity.governance.store.UserStoreBasedIdentityDataStore"
`
**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: wso2is-5.11.0-m23-SNAPSHOT

**Comment by dewniMW** [comment]
I was able to reproduce the same issue in IS 5.9.0 (with Last login Time as a default claim)
