### ISSUE TITLE
The identity server runs just only at the first time by using sudo wso2is command

### ISSUE THREAD

**Issue by usespring** [wso2/product-is#8547]
**Describe the issue:**

I'm using Debian 10 and wso2sever version 5.10.0 as well.
I've tried to run the wso2 server several times by using `sudo wso2is-5.10.0` command but the problem is: this works only for the first time after that, It will never run again and raises the following error (although, other ways such as run the _wso2server.sh_ files manually works all the time)
```

Using Java memory options: -Xms256m -Xmx1024m
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:70)
	at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)
Caused by: java.lang.RuntimeException: Error initializing storage.
	at org.wso2.carbon.server.CarbonLauncher.launch(CarbonLauncher.java:115)
	at org.wso2.carbon.server.Main.launchCarbon(Main.java:172)
	at org.wso2.carbon.server.Main.main(Main.java:105)
	... 6 more
```

**Comment by ruwanta** [comment]
it is not correct to run any user space programs in root mode. Especially it is not correct to run a server which serves web traffic as root, as it is severe security violation in Linux best practices.

"sudo" command forces the program to be run on root privileges.
Please run the wso2server.sh.
Please do a reveres proxy or use external load balancer, to remap the ports, if you want to serve port 443 instead of default 9443.

**Comment by usespring** [comment]
@ruwanta  thank you. I tried without "sudo" but the problem not fixed.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
