### ISSUE TITLE
Forgot Password throwing an error if there are similar users

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#8674]
**Describe the issue:**
When having more than one secondary user store and having same username in both user stores, when using forgot password option getting the following exception.

```
Caused by: org.wso2.carbon.user.core.UserStoreException: Error updating SCIM metadata in doPostUpdateCredentialByAdmin listener
	at org.wso2.carbon.identity.scim2.common.listener.SCIMUserOperationListener.doPostUpdateCredentialByAdminWithID(SCIMUserOperationListener.java:135)
	at org.wso2.carbon.identity.mgt.listener.IdentityUserIdResolverListener.doPostUpdateCredentialByAdmin(IdentityUserIdResolverListener.java:266)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.updateCredentialByAdmin(AbstractUserStoreManager.java:3526)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.updateCredentialByAdmin(AbstractUserStoreManager.java:3358)
	... 74 more
Caused by: org.wso2.carbon.user.core.UserStoreException: More than one user presents with the same user unique id.
	at org.wso2.carbon.user.core.common.UserUniqueIDManger.getUser(UserUniqueIDManger.java:73)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.setUserClaimValueWithID(AbstractUserStoreManager.java:12296)
	at org.wso2.carbon.identity.scim2.common.listener.SCIMUserOperationListener.doPostUpdateCredentialByAdminWithID(SCIMUserOperationListener.java:127)
```

**How to reproduce:**
1. Configure two secondary JDBC user stores (org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager)
2. Create a user with same username in both user stores.
3. Click forgot password option
4. Give the username with the secondary user store which you have created first.
5. Click on the forgot password reset link in the email
6. Once reset the password you will receive the following error in the UI.
`The server encountered an Internal error. Please contact administrator. `

**Expected behavior:**
No error should be shown in the UI

Suggested fix https://github.com/wso2-support/carbon-kernel/pull/1039

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.10.0
 - OS: Linux
 - Database: MYSQL, POSTGRES
 - Userstore:JDBC

---

### Optional Fields

**Related issues:**
https://github.com/wso2/product-is/issues/8297 (This issue is with uniqued ID user store, the current issue is with default JDBC user store)

**Comment by IsuraD** [comment]
Tested this in wso2is-5.11.0-m35 and it is working fine.

**Comment by IsuraD** [comment]
Probably this could have happened when you point the same database as two different user stores in the Identity Server. Tested that flow in the latest pack and it is also working fine.
