### ISSUE TITLE
Passwords which do not meet regex configured can be used during self registration when workflows are enabled

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#9148]
**Describe the issue:**
Passwords that do not meet the regex pattern configured in user-mgt.xml can be used during self-registration when workflows are enabled. There would be no errors shown in the UI preventing the registration saying that the password does not meet the criteria. The workflow is engaged.

Once the workflow is approved by an admin user because the password does not meet the regex pattern, the user addition fails silently without any errors shown to the user approving the request.

**How to reproduce:**

1. Enable self-registration with email confirmation
2. Access user-portal and register new user with password "123" (this does not meet the regex configured in user-mgt.xml).
3. The user would get an error message "Password length should be within 5 to 30 characters".
4. Log in to the management console and enable a workflow engagement for 'Add User' operation where `admin' role is authorized to approve the task.
5. Access user-portal and register a new user with password "123" (this does not meet the regex configured in user-mgt.xml).
6. User does not get the confirmation email yet.
7. Login to user-portal as a user with 'admin' role.
8. Approve the pending task for 'Add User'
9. The newly registered user does not get a confirmation email or the user approving the request does not get an error message. The user is not created.

**Expected behavior:**
Ideally during the initial self-registration if the password does not match the regex configured the workflow should not be engaged.

Currently, this does not happen because this validation[1] is done after the workflow listener[2] is called.

**Environment information** **:**
 - Product Version: [IS 5.10.0]

[1]https://github.com/wso2/carbon-kernel/blob/v4.6.0/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L4567
[2]https://github.com/wso2/carbon-kernel/blob/v4.6.0/core/org.wso2.carbon.user.core/src/main/java/org/wso2/carbon/user/core/common/AbstractUserStoreManager.java#L4520

**Comment by yuniet87** [comment]
Still not working properly. Check the password size but with the pattern set it shows the error:
`[2020-08-24 01:17:38,762] [f4d6a254-41f9-4ba9-b4b0-cdbda0fd3338] ERROR {org.wso2.carbon.identity.workflow.mgt.callback.WSWorkflowCallBackService} - Error when handling callback for the workflow, id: c16aed28-6a6d-462e-9fbb-7042c79f1547, status:APPROVED org.wso2.carbon.identity.workflow.mgt.exception.WorkflowException: Patrón de contraseña incorrecto. La contraseña debe contener como mínimo un dígito[0-9], una letra minúscula[a-z], una letra mayúscula[A-Z], uno de los caracteres !@#$%&*'
	at org.wso2.carbon.user.mgt.workflow.userstore.AddUserWFRequestHandler.onWorkflowCompletion(AddUserWFRequestHandler.java:265)
	at org.wso2.carbon.identity.workflow.mgt.extension.AbstractWorkflowRequestHandler.onWorkflowCompletion(AbstractWorkflowRequestHandler.java:199)
	at org.wso2.carbon.identity.workflow.mgt.WorkFlowExecutorManager.handleCallback(WorkFlowExecutorManager.java:187)
	at org.wso2.carbon.identity.workflow.mgt.WorkFlowExecutorManager.handleCallback(WorkFlowExecutorManager.java:236)
	at org.wso2.carbon.identity.workflow.mgt.callback.WSWorkflowCallBackService.onCallback(WSWorkflowCallBackService.java:56)`

Env: Docker 19.07
