### ISSUE TITLE
Null pointer is generated with password grant when Analytics Publishing is enabled

### ISSUE THREAD

**Issue by pathberiya** [wso2/product-is#9153]
Get the latest IS pack (5.7.0 with WUM)
Create a service provider
Enable Password Grant Analytics Publishing
<PublishPasswordGrantLogin>true</PublishPasswordGrantLogin>
Give request for a password grant
Null point is generared

[2020-08-06 21:38:49,047] ERROR {org.wso2.carbon.identity.oauth2.OAuth2Service} -  Error occurred while issuing the access token for Client ID : 3Yj5ZF15EJppxhtBu_l1D4pNzMUa, User ID admin, Scope : [test1] and Grant Type : password
java.lang.NullPointerException
	at org.wso2.carbon.identity.core.util.IdentityUtil.getClientIpAddress(IdentityUtil.java:1018)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.PasswordGrantHandler.publishAuthenticationData(PasswordGrantHandler.java:220)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.PasswordGrantHandler.validateUserCredentials(PasswordGrantHandler.java:179)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.PasswordGrantHandler.validateGrant(PasswordGrantHandler.java:93)
	at org.wso2.carbon.apimgt.keymgt.handlers.ExtendedPasswordGrantHandler.validateGrant_aroundBody2(ExtendedPasswordGrantHandler.java:103)
	at org.wso2.carbon.apimgt.keymgt.handlers.ExtendedPasswordGrantHandler.validateGrant(ExtendedPasswordGrantHandler.java:95)
	at org.wso2.carbon.identity.oauth2.token.AccessTokenIssuer.issue(AccessTokenIssuer.java:227)
	at org.wso2.carbon.identity.oauth2.OAuth2Service.issueAccessToken(OAuth2Service.java:221)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:304)
	at org.wso2.carbon.identity.oauth.endpoint.token.OAuth2TokenEndpoint.issueAccessToken(OAuth2TokenEndpoint.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)

**Comment by vihanga-liyanage** [comment]
Fixed by https://github.com/wso2/product-is/issues/8599
