### ISSUE TITLE
Certificate-based authentication does not work with X509 connector version 2.0.21

### ISSUE THREAD

**Issue by tharakawijekoon** [wso2/product-is#9179]
**Describe the issue:**
Certificate-based authentication does not work with X509 connector version 2.0.21.

**How to reproduce:**

- Configure certificate-based authentication with X509 connector version 2.0.21.(org.wso2.carbon.extension.identity.authenticator.x509Certificate.connector-2.0.21.jar)
- Try to login by providing the certificate. eg: CN=tharaka
- The following error is observed.

<img width="1271" alt="Screenshot 2020-08-10 at 9 48 05 PM" src="https://user-images.githubusercontent.com/47600906/89805444-4a16d400-db53-11ea-89d5-60f8fb6defd1.png">

when debug logs are enabled the following logs are seen in the wso2carbon.log

```
[2020-08-10 14:47:22,942] [310e7adc-2813-4280-bc29-8f27fa79d816] DEBUG {org.wso2.carbon.identity.authenticator.x509Certificate.X509CertificateUtil} - Error while calling the account lock service for user anuragCrt org.wso2.carbon.identity.handler.event.account.lock.exception.AccountLockServiceException: Invalid tenant domain: null
	at org.wso2.carbon.identity.handler.event.account.lock.service.AccountLockServiceImpl.getUserStoreManager(AccountLockServiceImpl.java:104)
	at org.wso2.carbon.identity.handler.event.account.lock.service.AccountLockServiceImpl.isAccountLocked(AccountLockServiceImpl.java:40)
	at org.wso2.carbon.identity.authenticator.x509Certificate.X509CertificateUtil.isAccountLock(X509CertificateUtil.java:425)
	at org.wso2.carbon.identity.authenticator.x509Certificate.X509CertificateAuthenticator.addOrValidateCertificate(X509CertificateAuthenticator.java:290)
	at org.wso2.carbon.identity.authenticator.x509Certificate.X509CertificateAuthenticator.validateUsingSubject(X509CertificateAuthenticator.java:547)
	at org.wso2.carbon.identity.authenticator.x509Certificate.X509CertificateAuthenticator.processAuthenticationResponse(X509CertificateAuthenticator.java:196)
	at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.process(AbstractApplicationAuthenticator.java:77)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:508)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handleResponse(DefaultStepHandler.java:482)
	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:180)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:185)
	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:111)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:158)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:240)
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53)
	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doGet(CommonAuthenticationServlet.java:43)
```

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0]

**Issue**:
https://github.com/wso2-extensions/identity-outbound-auth-x509/blob/2.0.x/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/x509Certificate/X509CertificateUtil.java#L416

---

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
