### ISSUE TITLE
x509 authenticator fails in the 2.0.21 version

### ISSUE THREAD

**Issue by emswbandara** [wso2/product-is#9182]
x509 authenticator fails with the exception [2] which is a regression caused by the fix [1]

[1] https://github.com/wso2-extensions/identity-outbound-auth-x509/pull/50
[2]
[2020-08-10 12:48:42,322] [e8f54810-96cf-4021-8024-56a6d0301564] DEBUG {org.wso2.carbon.identity.authenticator.x509Certificate.X509CertificateUtil} - Adding the X509 certificate with serial num: 1 as a user claim.\
[2020-08-10 12:48:42,324] [e8f54810-96cf-4021-8024-56a6d0301564] DEBUG {org.wso2.carbon.identity.authenticator.x509Certificate.X509CertificateUtil} - Error while calling the account lock service for user kla org.wso2.carbon.identity.handler.event.account.lock.exception.AccountLockServiceException: Invalid tenant domain: null\
at org.wso2.carbon.identity.handler.event.account.lock.service.AccountLockServiceImpl.getUserStoreManager(AccountLockServiceImpl.java:104)\
at org.wso2.carbon.identity.handler.event.account.lock.service.AccountLockServiceImpl.isAccountLocked(AccountLockServiceImpl.java:40)\
at org.wso2.carbon.identity.authenticator.x509Certificate.X509CertificateUtil.isAccountLock(X509CertificateUtil.java:425)\
at org.wso2.carbon.identity.authenticator.x509Certificate.X509CertificateAuthenticator.addOrValidateCertificate(X509CertificateAuthenticator.java:290)\
at org.wso2.carbon.identity.authenticator.x509Certificate.X509CertificateAuthenticator.validateUsingSubject(X509CertificateAuthenticator.java:547)\
at org.wso2.carbon.identity.authenticator.x509Certificate.X509CertificateAuthenticator.processAuthenticationResponse(X509CertificateAuthenticator.java:196)\
at org.wso2.carbon.identity.application.authentication.framework.AbstractApplicationAuthenticator.process(AbstractApplicationAuthenticator.java:77)\
at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:508)\
at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handleResponse(DefaultStepHandler.java:482)\
at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:180)\
at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:185)\
at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:111)\
at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:158)\
at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:240)\
at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53)\
at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doGet(CommonAuthenticationServlet.java:43)\
at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)\
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)\
at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)\
at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)\
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)\
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)\
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)\
at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)\
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)\
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)\
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\
at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:66)\
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\
at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:72)\
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\
at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)\
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\
at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)\
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)\
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)\
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)\
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)\
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)\
at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)\
at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)\
at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:75)\
at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)\
at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)\
at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)\
at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)\
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)\
at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)\
at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)\
at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)\
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)\
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)\
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)\
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)\
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)\
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\
at java.lang.Thread.run(Thread.java:748)\
\
[2020-08-10 12:48:42,332] [e8f54810-96cf-4021-8024-56a6d0301564] DEBUG {org.wso2.carbon.identity.authenticator.x509Certificate.X509CertificateAuthenticator} - Redirect to error page:

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
