### ISSUE TITLE
SAML2 Artifact Binding not working

### ISSUE THREAD

**Issue by lemoinem** [wso2/product-is#9195]
**Describe the issue:**
When tring SAML2 Artifact Binding the following error occured

```
TID: [-1234] [] [2020-08-12 16:43:51,488] [7cafdaf1-3ccc-46e0-ad87-f10e5930a8aa] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/].[bridgeservlet]} - Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception [Error while extracting SOAP body from the request.] with root cause javax.xml.soap.SOAPException: Unable to create message factory for SOAP: Unable to create SAAJ meta-factory: Provider com.sun.xml.internal.messaging.saaj.soap.SAAJMetaFactoryImpl not found
	at javax.xml.soap.MessageFactory.newInstance(MessageFactory.java:90)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLArtifactResolveServlet.handleRequest(SAMLArtifactResolveServlet.java:105)
	at org.wso2.carbon.identity.sso.saml.servlet.SAMLArtifactResolveServlet.doPost(SAMLArtifactResolveServlet.java:86)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:72)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:75)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**How to reproduce:**
1. Configure a SAML SSO Service Provider, enable  Enable "SAML2 Artifact Binding"
2. Try logging in.
3. At Artifact Resolution steps, WSO2 IS returns a 500 and the above message appears in the logs.

**Expected behavior:**
We'd expect artifact resolution to work

**Environment information:**
 - Product Version: IS 5.10.0
 - OS: Windows Server 2012 R2
 - Database: H2

JVM:

Java Home | C:\AdoptOpenJDK\jdk-11.0.6.10-hotspot
Java Runtime Name | OpenJDK Runtime Environment
Java Version | 11.0.6
Java Vendor | AdoptOpenJDK
Java VM Version | 11.0.6+10

A WSO2 installation using the following JVM works just fine. This looks like a JVM version issue:

Java Home | C:\Program Files\Java\jdk1.8.0_181\jre
Java Runtime Name | Java(TM) SE Runtime Environment
Java Version | 1.8.0_181
Java Vendor | Oracle Corporation
Java VM Version | 25.181-b13

---

### Optional Fields

**Related issues:**
This seems to be a regression of #6770

Similar issues that gave us the idea that this might be related to the JVM version:
https://stackoverflow.com/questions/48626824/java-lang-noclassdeffounderror-javax-xml-soap-soapexception
https://stackoverflow.com/questions/47199846/unable-to-create-saaj-meta-factory-after-packaging-as-jar

**Comment by lemoinem** [comment]
The server with our WSO2 instance is running with AdoptOpenJDK version 11.0.6+10. In order for Artifact binding to work with WSO2 on JDK11, we needed to:

- download saaj-impl-1.5.0.jar from https://repo1.maven.org/maven2/com/sun/xml/messaging/saaj/saaj-impl/1.5.0
- download stax-ex-1.8.3.jar from https://repo1.maven.org/maven2/org/jvnet/staxex/stax-ex/1.8.3/
- save both files in C:\WSO2\5.10.0\lib
- restart WSO2

Maybe it's simply a matter of including these jar in the packaging. In the meantime, this can be used as a workaround by anyone else having the same problem.

**Comment by nilasini** [comment]
The tests should be added. Created an issue to track it

https://github.com/wso2/product-is/issues/11285
