### ISSUE TITLE
User Disable Notification is not working with PostgreSQL

### ISSUE THREAD

**Issue by yuniet87** [wso2/product-is#9217]
**Describe the issue:**
When I configure the account suspension notifications module in IS-5.10.0 with PostgreSQL it does not show the following error:

`[2020-08-12 20:00:04,456] [] ERROR {org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread} - Error occurred while retrieving notification receivers org.wso2.carbon.identity.account.suspension.notification.task.exception.AccountSuspensionNotificationException: ERROR: operator does not exist: integer = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 240
	at org.wso2.carbon.identity.account.suspension.notification.task.jdbc.JDBCNotificationReceiversRetrieval.getNotificationReceivers(JDBCNotificationReceiversRetrieval.java:145)
	at org.wso2.carbon.identity.account.suspension.notification.task.NotificationReceiversRetrievalManager.getReceivers(NotificationReceiversRetrievalManager.java:65)
	at org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread.notifyUsers(AccountValidatorThread.java:177)
	at org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread.handleTask(AccountValidatorThread.java:156)
	at org.wso2.carbon.identity.account.suspension.notification.task.AccountValidatorThread.run(AccountValidatorThread.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: integer = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 240
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:153)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:103)
	at jdk.internal.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy58.executeQuery(Unknown Source)`

**How to reproduce:**
Configure account suspension using [User Account Suspension](https://is.docs.wso2.com/en/latest/learn/user-account-suspension/) docs.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0]
 - OS: [Docker]
 - Database: [PostgreSQL]
 - Userstore: [JDBC]

**Comment by emswbandara** [comment]
Duplicate of https://github.com/wso2/product-is/issues/10507
