### ISSUE TITLE
Internal Workflow User Add not working when restart the pods in k8s.

### ISSUE THREAD

**Issue by yuniet87** [wso2/product-is#9266]
**Describe the issue:**

When the internal workflow is enabled to add a user, everything works correctly.
When the pod restarts it shows the following error:

`[2020-08-20 16:00:39,662] []  WARN {org.wso2.carbon.bpel.core.ode.integration.store.ProcessStoreImpl} - Cannot find deployment unit information on DB for deployment unit User_Approval_HR-1`
`[2020-08-20 16:00:39,663] [] ERROR {org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl} - Cannot find DeploymentUnitDAO instance for package User_Approval_HR-1.`
`[2020-08-20 16:00:39,664] [] ERROR {org.wso2.carbon.bpel.deployer.BPELDeployer} - Error deploying BPEL package: User_Approval_HR.zip org.wso2.carbon.bpel.core.ode.integration.store.BPELDeploymentException: Cannot find DeploymentUnitDAO instance for package User_Approval_HR-1.
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.loadExistingBPELPackage(TenantProcessStoreImpl.java:824)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.reloadExistingVersionsOfBPELPackage(TenantProcessStoreImpl.java:672)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.reloadExistingVersions(TenantProcessStoreImpl.java:1091)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.deploy(TenantProcessStoreImpl.java:261)
	at org.wso2.carbon.bpel.deployer.BPELDeployer.deploy(BPELDeployer.java:107)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.DeploymentEngine.loadServices(DeploymentEngine.java:135)
	at org.wso2.carbon.core.CarbonAxisConfigurator.deployServices(CarbonAxisConfigurator.java:568)
	at org.wso2.carbon.core.internal.DeploymentServerStartupObserver.completingServerStartup(DeploymentServerStartupObserver.java:51)
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.notifyBefore(CarbonCoreServiceComponent.java:258)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:166)
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:323)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.server.admin.internal.ServerAdminServiceComponent.activate(ServerAdminServiceComponent.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)`

and when I invoke it with Self Registry it shows me the following:
`[2020-08-20 16:05:28,506] [31c8c085-35fa-4c1f-8337-2595d2093b1b] ERROR {org.apache.axis2.engine.AxisEngine} - The service cannot be found for the endpoint reference (EPR) https://ids.local/services/User_Approval_HRService org.apache.axis2.AxisFault: The service cannot be found for the endpoint reference (EPR) https://ids.local/services/User_Approval_HRService`

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0]
 - OS: [k8s]
 - Database: [PostgreSQL 12.2]
 - Userstore: [JDBC]

---

**Comment by ruwanta** [comment]
Looks like the case of deployment folder being immutable.

@yuniet87 There is a workaround.
Can you check if this works if you do volume mount for the  folder <IS_HOME>/repository/deployment/server/bpel

In fact this is a current limitation on containerized deployments where some of the data is held in the file system. Hence the respective deployment folders needs to be mounted externally as a data volume.

**Comment by yuniet87** [comment]
I am using PostgreSQL 11.7 because in 12.2 there is an error loading the script to create the database related to the "ABSTIME" data type. I used the configuration that comes here [1]. When I load the script to create the DB everything works correctly and when the IS starts everything also without problems but when I add the "Workflow Definition" I get this:
`[2020-08-23 23:55:01,884] [] ERROR {org.wso2.carbon.bpel.deployer.BPELDeployer} - Error deploying BPEL package: User_Approval_WF.zip org.apache.ode.bpel.iapi.ContextException: DbError
	at org.wso2.carbon.bpel.core.ode.integration.store.ProcessStoreImpl.exec(ProcessStoreImpl.java:793)
	at org.wso2.carbon.bpel.core.ode.integration.store.ProcessStoreImpl.getDeploymentUnitDAO(ProcessStoreImpl.java:303)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.loadExistingBPELPackage(TenantProcessStoreImpl.java:819)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.reloadExistingVersionsOfBPELPackage(TenantProcessStoreImpl.java:672)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.deployBPELPackageInODE(TenantProcessStoreImpl.java:728)
	at org.wso2.carbon.bpel.core.ode.integration.store.TenantProcessStoreImpl.deploy(TenantProcessStoreImpl.java:296)
	at org.wso2.carbon.bpel.deployer.BPELDeployer.deploy(BPELDeployer.java:107)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:144)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.runAxisDeployment(CarbonDeploymentSchedulerTask.java:93)
	at org.wso2.carbon.core.deployment.CarbonDeploymentSchedulerTask.run(CarbonDeploymentSchedulerTask.java:138)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`
`Caused by: java.util.concurrent.ExecutionException: <openjpa-2.2.0-wso2v1-r128166:129108 fatal general error> org.apache.openjpa.persistence.PersistenceException: Cannot change transaction isolation level in the middle of a transaction.`
`FailedObject: User_Approval_WF-1 [org.apache.openjpa.util.StringId] [java.lang.String]
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.wso2.carbon.bpel.core.ode.integration.store.ProcessStoreImpl.exec(ProcessStoreImpl.java:791)
	... 22 more`

By the way, the PostgreSQL driver is this:
**PostgreSQL JDBC Driver 42.2.14**
[1] https://is.docs.wso2.com/en/latest/setup/changing-datasource-bpsds/

**Comment by ruwanta** [comment]
Hi yuniet87,
Looks like the database creation script for PostgreSQL is still contains scripts for very old version of PostgreSQL

Can you try replacing all ABSTIME with TIMESTAMP data type?
Better create a new issue on this PostgreSQL error.
Also can you send a pull request or the corrected DB scripts, if it works for you.

**Comment by rksk** [comment]
DB script issue is tracked in https://github.com/wso2/product-is/issues/10414
