### ISSUE TITLE
Refresh grant returns 500 after CON_APP_KEY recovery

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#9272]
**Describe the issue:**

During the CON_APP_KEY recovery flow, we have the following two cases;
- For JWT tokens, always issue a new token expiring the existing token.
- If the last active token in the database is expired, update the token status in the database.

In both cases, if a client tries to use the above-expired refresh token for refresh grant; there will be another active token pair that is issued later and it will go brought the logic at [1].

During that flow, we have following method. The access token is the 3rd parameter at [2].
```
private void clearCache(String clientId, String authorizedUser, String[] scopes, String accessToken,
                            String authenticatedIDP, String tokenBindingReference) {
```

But at [3], we are invoking that method with a different parameter order, the access token is passed as the 4th parameter and IDP name is passed as the 3rd parameter.
```
clearCache(tokenReq.getClientId(), validationBean.getAuthorizedUser().toString(),
      validationBean.getScope(), validationBean.getAuthorizedUser().getFederatedIdPName(),
      validationBean.getAccessToken(), validationBean.getTokenBindingReference());
```

Due to that, an NPE occurs while trying to remove the cache entry when IDP name becomes null.

**How to reproduce:**
- Have two access token entries for a given user with given client id and same scope where the older one is in EXPIRED state and later one is in the ACTIVE state. 
- Invoke the refresh grant with older refresh token
- In will return a 500 response code

**Environment information** 
 - Product Version: IS 5.10.0

---

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/ce229f3d04c7ad896e186f89859cab708f069b19/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/handlers/grant/RefreshGrantHandler.java#L215
[2] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/ce229f3d04c7ad896e186f89859cab708f069b19/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/handlers/grant/RefreshGrantHandler.java#L412
[3] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/ce229f3d04c7ad896e186f89859cab708f069b19/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/token/handlers/grant/RefreshGrantHandler.java#L227

**Comment by rksk** [comment]
Adding the error log to improve visibility when searching
```
ERROR {org.wso2.carbon.identity.oauth2.OAuth2Service} - Error occurred while issuing the access token for Client ID : xxx, User ID null, Scope : [] and Grant Type : refresh_token java.lang.NullPointerException
	at org.wso2.carbon.identity.oauth.cache.OAuthCacheKey.hashCode(OAuthCacheKey.java:45)
	at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
	at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
	at org.wso2.carbon.caching.impl.CacheImpl.removeLocal(CacheImpl.java:540)
	at org.wso2.carbon.caching.impl.CacheImpl.remove(CacheImpl.java:521)
	at org.wso2.carbon.identity.application.common.cache.BaseCache.clearCacheEntry(BaseCache.java:201)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.clearCache(RefreshGrantHandler.java:401)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.removeIfCached(RefreshGrantHandler.java:205)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.isLatestRefreshToken(RefreshGrantHandler.java:197)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.validateRefreshTokenInRequest(RefreshGrantHandler.java:168)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.RefreshGrantHandler.validateGrant(RefreshGrantHandler.java:78)
```
