### ISSUE TITLE
Error when filtering users by multi attributes through SCIM2 /Users endpoint

### ISSUE THREAD

**Issue by ShanChathusanda93** [wso2/product-is#9286]
**Describe the issue:**
When filtering the users by multi attributes like user claims and user groups the following error response is returned.

> {
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "detail": "Error in filtering users by multi attributes in domain: PRIMARY",
    "status": "500"
}

In the console also there is a SQL error as follows.

> DEBUG {org.wso2.charon3.core.protocol.endpoints.AbstractResourceManager} - Error in filtering users by multi attributes in domain: PRIMARY org.wso2.charon3.core.exceptions.CharonException: Error in filtering users by multi attributes in domain: PRIMARY
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getFilteredUsersFromMultiAttributeFiltering(SCIMUserManager.java:1444)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getMultiAttributeFilteredUsers(SCIMUserManager.java:1269)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.filterUsers(SCIMUserManager.java:747)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.listUsersWithGET(SCIMUserManager.java:344)...

> Caused by: org.wso2.carbon.user.core.UserStoreException: Error occur while doGetUserList for multi attribute searching
	at org.wso2.carbon.user.core.jdbc.JDBCUserStoreManager.doGetUserList(JDBCUserStoreManager.java:3995)
	at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserList(AbstractUserStoreManager.java:6945)
	at org.wso2.carbon.identity.scim2.common.impl.SCIMUserManager.getFilteredUsersFromMultiAttributeFiltering(SCIMUserManager.java:1440)
	... 64 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'HAVING COUNT(DISTINCT UA.UM_ATTR_VALUE) = 2 ORDER BY UM_USER_NAME ASC LIMIT 10 O' at line 1

**How to reproduce:**
* Start IS.
* Create a user(**alex**) and add a role (**manager**).
* Execute the following endpoint.
* curl -v -k --user <USERNAME>:<PASSWORD>  -X GET --header "Content-Type:application/json" 'https://localhost:9443/scim2/Users?startIndex=1&count=10&filter=userName+co+alex+groups+eq+manager'

**Expected behavior:**
* Response has to be the filtered users list.

**Environment information** **:**
 - Product Version: IS 5.9.0
 - OS: Mac
 - Database: H2
 - Userstore: JDBC (MYSQL)

**Comment by vihanga-liyanage** [comment]
Same issue reported in https://github.com/wso2/product-is/issues/8170
