### ISSUE TITLE
SCIM search failes when count is zero or not specified

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#9303]
**Describe the issue:**

If we do a SCIM search without specifying (or specifying as zero) the `count` property as below the following exception is occurred.
```
POST https://localhost:9443/scim2/Users/.search
{
    "schemas": [ "urn:ietf:params:scim:api:messages:2.0:SearchRequest" ],
    "filter": "userName co admin",
    "startIndex": 1
}
```
```
POST https://localhost:9443/scim2/Users/.search
{
    "schemas": [ "urn:ietf:params:scim:api:messages:2.0:SearchRequest" ],
    "filter": "userName co admin",
    "startIndex": 1,
    "count": 0
}
```

```
ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/scim2].[SCIM2Servlet]} - Servlet.service() for servlet [SCIM2Servlet] in context with path [/scim2] threw exception java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454)
	at org.wso2.charon3.core.protocol.endpoints.UserResourceManager.listWithPOST(UserResourceManager.java:511)
	at org.wso2.carbon.identity.scim2.provider.resources.UserResource.getUsersByPost(UserResource.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

We when we don't specify the `count`, it is taken as zero and an empty list is returned at [1].
```
        } else if (count != null && count == 0) {
            return Collections.emptyList();
        }
```

Then we are getting the first element at [2] as below. 
```
totalResults = (int) tempList.get(0);
tempList.remove(0);
```

Ideally, the first element should be the total results count. But in this case, we are returning an empty list and there are no elements in it to get the total results count.

**Environment information** 
 - Product Version: IS 5.10.0

[1] https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/master/components/org.wso2.carbon.identity.scim2.common/src/main/java/org/wso2/carbon/identity/scim2/common/impl/SCIMUserManager.java#L438
[2] https://github.com/wso2/charon/blob/master/modules/charon-core/src/main/java/org/wso2/charon3/core/protocol/endpoints/UserResourceManager.java#L511

**Comment by rksk** [comment]
Additionally, we need to concentrate on the case of not specifying the `count` parameter, whether to return zero results or return all the results with a threshold.

**Comment by rksk** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/pull/426
