### ISSUE TITLE
After the migration, workflows definitions are not getting deployed/started for tenants

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#9308]
**Describe the issue:**
After the migration, workflows definitions are not getting deployed/started for tenants

**How to reproduce:**
1. Create a 5.10.0 setup
2. Create a tenant
3. Create a workflow definition and engagement in the tenant.
4. Peform migration to 5.11.0
5. Login to the tenant

**Expected behavior:**
Ideally at the 1st tenant loading, created WF services should be initiated. But in this setup it doesn't happen. Hence, workflows for tenants do not work.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [ IS 5.11.0]
 - OS: [Mac]
 - Database: [MySQL]
 - Userstore: [LDAP, JDBC]

---

### Optional Fields
- Observed while testing symmetric key encryption migration

**Comment by Buddhimah** [comment]
Below Error, log occurs in approval 

`[2020-10-22 13:24:23,415] [a3649938-ab49-4163-8248-e96e2ee8a73e] ERROR {org.wso2.carbon.humantask.core.engine.commands.Start} - User[admin] cannot perform [class org.wso2.carbon.humantask.core.engine.commands.Start] operation on task[1651] as the task is in state[IN_PROGRESS]. [class org.wso2.carbon.humantask.core.engine.commands.Start] operation can be performed only on tasks in [RESERVED] state
[2020-10-22 13:24:23,580] [a3649938-ab49-4163-8248-e96e2ee8a73e] ERROR {org.wso2.carbon.humantask.core.api.client.TaskOperationsImpl} - org.wso2.carbon.humantask.core.engine.runtime.api.HumanTaskIllegalStateException: User[admin] cannot perform [class org.wso2.carbon.humantask.core.engine.commands.Start] operation on task[1651] as the task is in state[IN_PROGRESS]. [class org.wso2.carbon.humantask.core.engine.commands.Start] operation can be performed only on tasks in [RESERVED] state
[2020-10-22 13:24:23,613] [a3649938-ab49-4163-8248-e96e2ee8a73e] ERROR {org.wso2.carbon.identity.rest.api.user.approval.v1.core.UserApprovalService} - errorCode: HTA-10006 | message: Invalid state change is requested for the given task. org.wso2.carbon.humantask.client.api.IllegalStateFault: User[admin] cannot perform [class org.wso2.carbon.humantask.core.engine.commands.Start] operation on task[1651] as the task is in state[IN_PROGRESS]. [class org.wso2.carbon.humantask.core.engine.commands.Start] operation can be performed only on tasks in [RESERVED] state
	at org.wso2.carbon.humantask.core.api.client.TaskOperationsImpl.handleException(TaskOperationsImpl.java:1770)
	at org.wso2.carbon.humantask.core.api.client.TaskOperationsImpl.start(TaskOperationsImpl.java:695)
	at org.wso2.carbon.identity.rest.api.user.approval.v1.core.UserApprovalService.completeTask(UserApprovalService.java:204)
	at org.wso2.carbon.identity.rest.api.user.approval.v1.core.UserApprovalService.updateStatus(UserApprovalService.java:178)
	at org.wso2.carbon.identity.rest.api.user.approval.v1.impl.MeApiServiceImpl.updateStateOfTask(MeApiServiceImpl.java:50)
	at org.wso2.carbon.identity.rest.api.user.approval.v1.MeApi.updateStateOfTask(MeApi.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPut(AbstractHTTPServlet.java:232)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:663)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:135)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:122)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by Buddhimah** [comment]
Respective tenant folder needs to be copied from the OLD-IS to NEW-IS before migration. Also tenant needs to be loaded. If those two requirements met this issue will be not reproducible.
