### ISSUE TITLE
CON_APP_KEY recovery is not triggered when CorrelationLogs are enabled

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#9350]
**Describe the issue:**

If CorrelationLogs are enabled, the CON_APP_KEY recovery does not work. If fails with the following log upon the constrain violation.

```
ERROR {org.wso2.carbon.ndatasource.rdbms.CorrelationLogInterceptor} - Unable get query run-time java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.ndatasource.rdbms.CorrelationLogInterceptor$StatementProxy.invoke(CorrelationLogInterceptor.java:152)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1-admin--1234-PRIMARY-APPLICATION_USER-369db21a386ae433e65c0ff34' for key 'CON_APP_KEY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2818)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2157)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379)

ERROR {org.wso2.carbon.identity.oauth2.OAuth2Service} - Error occurred while issuing the access token for Client ID : f_BHaibaTu9QtyIfI0Xx1RXbCvoa, User ID admin, Scope : [1, openid] and Grant Type : password java.lang.NullPointerException
	at com.sun.proxy.$Proxy54.execute(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy54.execute(Unknown Source)
	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:212)
	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:98)
	at org.wso2.carbon.identity.oauth2.dao.AccessTokenDAOImpl.insertAccessToken(AccessTokenDAOImpl.java:301)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.storeAccessToken(AbstractAuthorizationGrantHandler.java:284)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.persistAccessTokenInDB(AbstractAuthorizationGrantHandler.java:410)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.generateNewAccessToken(AbstractAuthorizationGrantHandler.java:341)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.renewAccessToken(AbstractAuthorizationGrantHandler.java:315)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.issue(AbstractAuthorizationGrantHandler.java:143)

```

The reason is, CorrelationLogInterceptor is throwing a wrapped exception and the CON_APP_KEY recovery flow is not getting triggered.

**How to reproduce:**
Set up a two-node cluster and generate access tokens with a high concurrency.
To increase the rate of CON_APP_KEY violation, do not enable hazelcast clustering and use JWT token issuer.

**Expected behavior:**
CorrelationLogInterceptor should re-throw the exact exception thrown from the underlying DB driver.

**Environment information** 
 - Product Version: IS 5.9.0
 - Database: MySQL

**Related issues:**
https://github.com/wso2/product-apim/issues/5285

**Comment by rksk** [comment]
Addressed with https://github.com/wso2/carbon-kernel/pull/2782
