### ISSUE TITLE
Getting Null point Exception when adding claim dialects using the configuration file

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9475]
**Describe the issue:**
```ERROR {org.wso2.carbon.user.core.claim.DefaultClaimManager} - Error while initializing claim manager
[2020-09-16 16:17:06,546] [] ERROR {org.wso2.carbon.user.core.internal.Activator} - Cannot start User Manager Core bundle org.wso2.carbon.user.core.UserStoreException: Cannot initialize the realm.
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:286)
	at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:102)
	at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:115)
	at org.wso2.carbon.user.core.internal.Activator.startDeploy(Activator.java:72)
	at org.wso2.carbon.user.core.internal.BundleCheckActivator.start(BundleCheckActivator.java:61)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:598)
	at org.eclipse.osgi.container.Module.start(Module.java:462)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.user.core.claim.inmemory.InMemoryClaimManager.<init>(InMemoryClaimManager.java:67)
	at org.wso2.carbon.user.core.common.DefaultRealm.init(DefaultRealm.java:130)
	at org.wso2.carbon.user.core.common.DefaultRealmService.initializeRealm(DefaultRealmService.java:276)
	... 22 more
```

**How to reproduce:**
1. Open the claim-config.xml file found in the <IS_HOME>/repository/conf/ folder.
To add a new claim dialect, add the following configuration to the file along with the new claims you want to add under the dialect.  example, the new claim dialect is named SampleAppClaims .

```<Dialect dialectURI="http://wso2.org/SampleAppClaims">
    <Claim>
        <ClaimURI>http://wso2.org/SampleAppClaims/givenname</ClaimURI>
        <DisplayName>First Name</DisplayName>
        <MappedLocalClaim>http://wso2.org/claims/givenname</MappedLocalClaim>
    </Claim>
    <Claim>
        <ClaimURI>http://wso2.org/SampleAppClaims/nickName</ClaimURI>
        <DisplayName>Nick Name</DisplayName>
        <MappedLocalClaim>http://wso2.org/claims/nickname</MappedLocalClaim>
    </Claim>
</Dialect> ```
3. Once you have edited the claim-config. xml file, start WSO2 Identity Server.
NOTE: did this before the first start-up of the IS product.

**Expected behavior:**
The configurations should be applied and should able to view the new claim dialect via the console > Manage.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11 m36 snapshot
 - OS: mac
 - Database: H2
 - Userstore:Ldap
---
Refer : https://is.docs.wso2.com/en/5.11.0/learn/adding-claim-dialects/

**Comment by IsuraD** [comment]
Cannot reproduce. 

Added following and it works as expected. 

			```
<Dialect dialectURI="http://asgardio.org/claims">
				<Claim>
					<ClaimURI>http://asgardio.org/claims/legalperson/SIC</ClaimURI>
					<DisplayName>Standard Industrial Classification</DisplayName>
					<AttributeID>nickName</AttributeID>
					<Description>Standard Industrial Classification</Description>
					<Required />
					<DisplayOrder>1</DisplayOrder>
					<SupportedByDefault />
					<MappedLocalClaim>http://wso2.org/claims/nickname</MappedLocalClaim>
				</Claim>
			</Dialect>
```
