### ISSUE TITLE
Getting an exception while creating a secondary user store with Oracle19c in Windows ENV

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9538]
**Describe the issue:**
Getting an error log and error message while try to Finish secondary user store creation (Add JDBC Userstore wizard), in windows.

**How to reproduce:**
Add Oracle jdbc driver (components > lib)
Login to Console > Mange
1. Create new user store > JDBC
2. Add necessary details for ORACLE DB pointed
3.Check the connection 
4. Validate other config
5. Click on Finish

``` [b913c9dc-2602-4927-93eb-fa35a0ec222b] ERROR {org.wso2.carbon.identity.user.store.configuration.utils.SecondaryUserStoreConfigurationUtil} - Error while creating 'userstores' directory to store configurations for tenant = 1
[2020-09-22 23:20:54,357] [b913c9dc-2602-4927-93eb-fa35a0ec222b] ERROR {org.wso2.carbon.identity.api.server.userstore.v1.core.ServerUserStoreService} - errorCode: SUS-65001 | message: Server Encountered an error while adding secondary user store. org.wso2.carbon.identity.user.store.configuration.utils.IdentityUserStoreMgtException:  Error occurred while creating or closing the output stream from C:\511~1.0-A\WSO2IS~1.0-A\bin\..\repository\tenants\1\userstores\Ora19C511.xml
        at org.wso2.carbon.identity.user.store.configuration.dao.impl.FileBasedUserStoreDAOImpl.writeToUserStoreConfigurationFile(FileBasedUserStoreDAOImpl.java:149)
        at org.wso2.carbon.identity.user.store.configuration.dao.impl.FileBasedUserStoreDAOImpl.doAddUserStore(FileBasedUserStoreDAOImpl.java:295)
        at org.wso2.carbon.identity.user.store.configuration.dao.AbstractUserStoreDAO.addUserStore(AbstractUserStoreDAO.java:42)
        at org.wso2.carbon.identity.user.store.configuration.UserStoreConfigServiceImpl.addUserStore(UserStoreConfigServiceImpl.java:76)
        at org.wso2.carbon.identity.api.server.userstore.v1.core.ServerUserStoreService.addUserStore(ServerUserStoreService.java:95)
        at org.wso2.carbon.identity.api.server.userstore.v1.impl.UserstoresApiServiceImpl.addUserStore(UserstoresApiServiceImpl.java:46)
        at org.wso2.carbon.identity.api.server.userstore.v1.UserstoresApi.addUserStore(UserstoresApi.java:73)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:215)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:135)
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:122)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834) 
```

![image](https://user-images.githubusercontent.com/39120228/93974358-54073600-fd93-11ea-9823-d574911bc86e.png)

![image](https://user-images.githubusercontent.com/39120228/93974395-61242500-fd93-11ea-99ab-557fb5d5ae4e.png)

**Comment by nilasini** [comment]
@ShanikaWickramasinghe did you encounter this issue while testing with latest pack? Could you please verify?

**Comment by nilasini** [comment]
With 5.12.0-alpha20 the issue is not reproducible with oracle 19c in the windows environment
