### ISSUE TITLE
validate-answer API throwing exception

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9662]
**Describe the issue:**
When calling the rest endpoint https://<host_name>:<port>/t/wso2.com/api/identity/recovery/v0.9/validate-answer[1] getting following exception
```
 ERROR {org.wso2.carbon.identity.recovery.endpoint.impl.ValidateAnswerApiServiceImpl} - Error occurred in the server while performing the task. java.lang.UnsupportedOperationException: User Functionality properties are not configured.
	at org.wso2.carbon.identity.recovery.handler.ConfigStoreFunctionalityLockPropertyHandler.getConfigStoreProperties(ConfigStoreFunctionalityLockPropertyHandler.java:71)
	at org.wso2.carbon.identity.recovery.password.SecurityQuestionPasswordRecoveryManager.handleAnswerVerificationFailInFunctionalityLockMode(SecurityQuestionPasswordRecoveryManager.java:765)
	at org.wso2.carbon.identity.recovery.password.SecurityQuestionPasswordRecoveryManager.validateUserChallengeQuestions(SecurityQuestionPasswordRecoveryManager.java:479)
	at org.wso2.carbon.identity.recovery.endpoint.impl.ValidateAnswerApiServiceImpl.validateAnswerPost(ValidateAnswerApiServiceImpl.java:29)
	at org.wso2.carbon.identity.recovery.endpoint.ValidateAnswerApi.validateAnswerPost(ValidateAnswerApi.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.identity.captcha.filter.CaptchaFilter.doFilter(CaptchaFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:135)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:122)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java
```
**How to reproduce:**
1. Call validate-answer API[1] as below.
`curl -k -X POST -H "Authorization: Basic YWRtaW5Ad3NvMi5jb206YWRtaW4=" -H "Content-Type: application/json" -d '{"key": "3746d03f-c570-493b-aaea-40925e6ab37a","answers": [{ "question-set-id": "http://wso2.org/claims/challengeQuestion2","answer": "netball"},{"question-set-id": "http://wso2.org/claims/challengeQuestion1","answer": "dosai"}],"properties": []}' "https://localhost:9443/t/wso2.com/api/identity/recovery/v0.9/validate-answer"`

2. You will receive above stack trace and following response.
`{"code":"18013","message":"Internal server error","description":"The server encountered an internal error. Please contact administrator."}`

It is happening if the property EnablePerUserFunctionalityLocking is true in identity.xml (By default value for EnablePerUserFunctionalityLocking is true)

[1] https://docs.wso2.com/display/IS510/apidocs/account-recovery/#!/operations#PasswordRecovery#validateAnswerPost

**Expected behavior:**
No errors should be thrown

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS-5.11.0-alpha]
 - OS: [ Linux]
 - Database: [Postgresql]
 - Userstore: [JDBC]

---

**Comment by sachiniWettasinghe** [comment]
Tested with a wso2is-5.11.0-beta4-SNAPSHOT and the issue could not be reproduced. @nilasini could you please verify?
