### ISSUE TITLE
Internal server error when creating a script library with a name which contains spaces

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#9681]
**Describe the issue:**
Tried to add a script library using postman, with a name which contains spaces. It returns an internal server error, but the library has been added to the database.
```
POST https://localhost:9443/api/server/v1/script-libraries
name: math lib.js
content: var a ="5" ;
description: library related to maths
```
<img width="956" alt="function library save" src="https://user-images.githubusercontent.com/25483865/95181212-dcb0a980-0777-11eb-976e-6d88ad0b1076.PNG">
Even though it gives an internal server error, script library will be added to the database.

![imageedit_2_8543510519](https://user-images.githubusercontent.com/25483865/95182891-0ff43800-077a-11eb-8170-238b6ebff866.png)

Therefore, retrieving script libraries after adding such library  returns 500 internal server error.

carbon log:
`
[2020-10-06 02:03:31,592] [8c000383-7e4a-49fd-9d9b-1cd1364d39b4] ERROR {org.wso2.carbon.identity.api.dispatcher.DefaultExceptionMapper} - Server encountered an error while serving the request. java.lang.IllegalArgumentException: Illegal character in path at index 73: https://localhost:9443/t/carbon.super/api/server/v1/script-libraries/math lib.js                                                                                                                        at java.net.URI.create(URI.java:852)                                                                                                                                                                                                  at org.wso2.carbon.identity.api.server.common.ContextLoader.buildURIForHeader(ContextLoader.java:105)                                                                                                                                 at org.wso2.carbon.identity.api.server.script.library.v1.impl.ScriptLibrariesApiServiceImpl.addScriptLibrary(ScriptLibrariesApiServiceImpl.java:49)                                                                                   at org.wso2.carbon.identity.api.server.script.library.v1.ScriptLibrariesApi.addScriptLibrary(ScriptLibrariesApi.java:69)                                                                                                              at sun.reflect.GeneratedMethodAccessor261.invoke(Unknown Source)                                                                                                                                                                      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                                                              at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                                                                                                   at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)                                                                                                                                         at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)                                                                                                                                                     at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)                                                                                                                                                                    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)                                                                                                                                                                    at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)                                                                                                                                      at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)                                                                                                                              at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)                                                                                                                                             at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)                                                                                                                                       at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)                                                                                                                                     at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)                                                                                                                                   at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)                                                                                                                                              at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)                                                                                                                                              at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)                                                                                                                                          at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)                                                                                                                                   at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:215)                                                                                                                                          at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)                                                                                                                                                                       at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)                                                                                                                                         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)                                                                                                                                  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)                                                                                                                                          at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)                                                                                                                                                             at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)                                                                                                                                  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)                                                                                                                                          at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)                                                                                                                                                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)                                                                                                                                                 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)                                                                                                                                             at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)                                                                                                                                                      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)                                                                                                                                                       at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)                                                                                                                                                            at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:105)                                                                                                                at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)                                                                                                                                        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:122)                                                                                                                                       at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)                                                                                                                                        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)                                                                                                                                  at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)                                                                                                                                                    at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)                                                                                                                 at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)                                                                                                                                          at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)                                                                                                                              at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)                                                                                                                                        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)                                                                                                                             at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)                                                                                                                                                   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)                                                                                                                                                        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)                                                                                                                                                         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)                                                                                                                                                   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)                                                                                                                                            at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)                                                                                                                                                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)                                                                                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                                                                                    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)                                                                                                                                                 at java.lang.Thread.run(Thread.java:748)                                                                                                                                                                                      Caused by: java.net.URISyntaxException: Illegal character in path at index 73: https://localhost:9443/t/carbon.super/api/server/v1/script-libraries/math lib.js                                                                               at java.net.URI$Parser.fail(URI.java:2847)                                                                                                                                                                                            at java.net.URI$Parser.checkChars(URI.java:3020)                                                                                                                                                                                      at java.net.URI$Parser.parseHierarchical(URI.java:3104)                                                                                                                                                                               at java.net.URI$Parser.parse(URI.java:3052)                                                                                                                                                                                           at java.net.URI.<init>(URI.java:588)                                                                                                                                                                                                  at java.net.URI.create(URI.java:850)                                                                                                                                                                                                  ... 56 more 
 `

**How to reproduce:**
1. Create a script library using REST API. Keep spaces in the script library name.
sample:
```
POST https://localhost:9443/api/server/v1/script-libraries
name: math lib.js
content: var a ="5" ;
description: library related to maths
```
2. Navigate to management console > Main Menu > Manage tab > Function Libraries > List. You can see the added library.
3. Try to retrieve all libraries using REST API.
`GET https://localhost:9443/api/server/v1/script-libraries`

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:IS 5.11.0-alpha3
 - OS: Windows
 - Database: Postgres
 - Userstore: JDBC

**Comment by AnjanaSamindraPerera** [comment]
I'm working on this issue
