### ISSUE TITLE
[DB2] The console and the Myaccount applications will not be visible to tenants 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9710]
**Describe the issue:*
The console and the Myaccount applications will not be visible to the tenant user when configured primary user store as  DB2.

**How to reproduce:**
Configure deployment.toml and put JDBC driver for the version <IS_HOME>/repository/components/lib folder 
Start the IS server
Configure a Tenant
Login to Console > Manage as a Tenant user
*No issue while accessing My account

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0 alpha4 Snapshot
 - OS: Windows & Mac
 - Database: DB2 (DB2 v11.5.4.0)
 - Userstore: JDBC
- Browsers Google Chrome, Microft Edge, Firefox

```[user_store]
type = "database_unique_id"

[database.identity_db]

url = "jdbc:db2://localhost:50000/alpha33"
username = "db2inst1"
password = "wso2carbon"
driver = "com.ibm.db2.jcc.DB2Driver"
[database.identity_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1 FROM SYSIBM.SYSDUMMY1"
validationInterval="30000"
defaultAutoCommit=false

[database.shared_db]

url = "jdbc:db2://localhost:50000/alpha33"
username = "db2inst1"
password = "wso2carbon"
driver = "com.ibm.db2.jcc.DB2Driver"
[database.shared_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1 FROM SYSIBM.SYSDUMMY1"
validationInterval="30000"
defaultAutoCommit=false
```
*Note - Error logs server start-up in windows  --
```
ERROR {org.wso2.carbon.identity.rest.api.user.application.v1.core.ApplicationService} - errorCode: APP-15001 | message: Server Encountered an error while retrieving applications. org.wso2.carbon.identity.application.common.IdentityApplicationManagementServerException: Error while getting application basic information for discoverable applications in tenantDomain: wso2.com
        at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getDiscoverableApplicationBasicInfo(ApplicationDAOImpl.java:4917)
        at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getDiscoverableApplicationBasicInfo(ApplicationDAOImpl.java:4759)
        at org.wso2.carbon.identity.application.mgt.dao.impl.CacheBackedApplicationDAO.getDiscoverableApplicationBasicInfo(CacheBackedApplicationDAO.java:400)
        at org.wso2.carbon.identity.application.mgt.internal.impl.DiscoverableApplicationManagerImpl.getDiscoverableApplicationBasicInfo(DiscoverableApplicationManagerImpl.java:38)
        at org.wso2.carbon.identity.rest.api.user.application.v1.core.ApplicationService.getApplications(ApplicationService.java:106)
        at org.wso2.carbon.identity.rest.api.user.application.v1.impl.MeApiServiceImpl.getApplications(MeApiServiceImpl.java:44)
        at org.wso2.carbon.identity.rest.api.user.application.v1.MeApi.getApplications(MeApi.java:85)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:220)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:135)
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:122)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: [jcc][10145][10844][4.25.13] Invalid parameter 2: Parameter index is out of range. ERRORCODE=-4461, SQLSTATE=42815
        at com.ibm.db2.jcc.am.b6.a(b6.java:810)
        at com.ibm.db2.jcc.am.b6.a(b6.java:66)
        at com.ibm.db2.jcc.am.b6.a(b6.java:116)
        at com.ibm.db2.jcc.am.k4.l(k4.java:6373)
        at com.ibm.db2.jcc.am.k4.j(k4.java:6328)
        at com.ibm.db2.jcc.am.k4.f(k4.java:1077)
        at com.ibm.db2.jcc.am.k4.setInt(k4.java:1070)
        at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy58.setInt(Unknown Source)
        at org.wso2.carbon.database.utils.jdbc.NamedPreparedStatement.setInt(NamedPreparedStatement.java:127)
        at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.getDiscoverableApplicationBasicInfo(ApplicationDAOImpl.java:4907)
        ... 58 more
```
![image](https://user-images.githubusercontent.com/39120228/95392219-01db1e80-0916-11eb-9fdc-cd1a63488377.png)

**Comment by thanujalk** [comment]
This is fixed now.
