### ISSUE TITLE
Getting  400 status code with Challenge Question Rest API (/me/challenge-answers ) Answer to a collection of new challenges.

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/product-is#9732]
**Describe the issue:**
Provide an answer to one challenge question set available in the system for the authenticated user. Getting 400 status code.

{
    "code": "CQM-18017",
    "message": "Unable to set user challenge answers.",
    "description": "No challenge question found. Error persisting user challenge answers for user. Challenge question answered is not registered with wso2.com domain.",
    "traceId": "ec5ee783-3440-462c-8064-1628fba45289"
}

```
 [ec5ee783-3440-462c-8064-1628fba45289] ERROR {org.wso2.carbon.identity.rest.api.user.challenge.v1.core.UserChallengeService} - errorCode: CQM-10005 | message: Server encountered an error while setting answers to the user challenges. org.wso2.carbon.identity.recovery.IdentityRecoveryClientException: No challenge question found. Error persisting user challenge answers for user. Challenge question answered is not registered with wso2.com domain.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:78)
        at org.wso2.carbon.identity.recovery.util.Utils.handleClientException(Utils.java:319)
        at org.wso2.carbon.identity.recovery.ChallengeQuestionManager.checkChallengeQuestionExists(ChallengeQuestionManager.java:1097)
        at org.wso2.carbon.identity.recovery.ChallengeQuestionManager.setChallengesOfUser(ChallengeQuestionManager.java:587)
        at org.wso2.carbon.identity.rest.api.user.challenge.v1.core.UserChallengeService.setChallengeAnswersOfUser(UserChallengeService.java:94)
        at org.wso2.carbon.identity.rest.api.user.challenge.v1.impl.MeApiServiceImpl.addChallengeAnswersForLoggedInUser(MeApiServiceImpl.java:38)
        at org.wso2.carbon.identity.rest.api.user.challenge.v1.MeApi.addChallengeAnswersForLoggedInUser(MeApi.java:96)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:215)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:135)
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:122)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
        at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**How to reproduce:**
curl -X POST "https://localhost:9443/t/carbon.super/api/users/v1/me/challenge-answers" -H "accept: application/json" -H "authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d "[ { \"questionSetId\": \"challengeQuestionSet1\", \"challengeQuestion\": { \"locale\": \"en_US\", \"question\": \"What is your favorite travel destination ?\", \"questionId\": \"question1\" }, \"answer\": \"Colombo\" }]"

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: 5.11.0 alpha4 Snapshot
 - OS:Windows, Mac
 - Database: DB2, H2
 - Userstore: LDAP, JDBC

**Comment by sachiniWettasinghe** [comment]
The reason for this 400 bad request error is that the used sample challenge is invalid. If a valid registered challenge as follows is passed, this will return a 201.

Sample Request:
```
curl -X POST \
  https://localhost:9443/t/wso2.com/api/users/v1/me/challenge-answers \
  -H 'Authorization: Basic a2ltQHdzbzIuY29tOmtpbTEyMw==' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 2a7d746a-a4a2-42f1-9c1f-1f5534577ae1' \
  -H 'cache-control: no-cache' \
  -d '[
  {
    "questionSetId": "challengeQuestion1",
    "challengeQuestion": {
      "locale": "en_US",
      "question": "Favorite vacation location ?",
      "questionId": "question4"
    },
    "answer": "Colombo"
  }
]'
```
However, the REST API doc should be updated with valid samples.
