### ISSUE TITLE
PassiveSTS web app not working

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9811]
**Describe the issue:**
Once deploy the Passive sts war file mentioned in [1] and go to http://localhost:8080/PassiveSTSSampleApp/index.jsp you will be redirected to Identity server for login. Once the login successfull you will be redirected to the following page and in the tomcat console following stack trace has been printed.

![1](https://user-images.githubusercontent.com/20336761/95822497-ab247900-0d49-11eb-8ccf-700015f91b1d.png)

13-Oct-2020 11:37:10.769 SEVERE [http-nio-8080-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/PassiveSTSSampleApp] threw exception
 java.lang.NullPointerException
	at org.wso2.identity.passivests.sample.AuthFilter.handleResponse(AuthFilter.java:121)
	at org.wso2.identity.passivests.sample.AuthFilter.doFilter(AuthFilter.java:94)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

[1] https://is.docs.wso2.com/en/latest/learn/deploying-the-sample-app/#deploying-the-passivestssampleapp-webapp
**How to reproduce:**
Deploy pasivestst web app and go to http://localhost:8080/PassiveSTSSampleApp/index.jsp

**Expected behavior:**
No errors should be thrown, successfully redirected to the passive sts page.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS-5.11.0-beta]
 - OS: [Linux]
 - Database: [e.g., MySQL, H2]
 - Userstore: [e.g., LDAP, JDBC]

---

**Comment by nilasini** [comment]
It is a config issue. Once the configuration is done properly working fine.

**Comment by Yoshani** [comment]
Faced the same issue and resolved by making sure that the Passive STS Realm and Passive STS WReply URL are identical in the management console SP config and in the sample app configs (<TOMCAT_HOME>/apache-tomcat-<version>/webapps/PassiveSTSSampleApp/WEB-INF/web.xml if using the WSO2 sample app)

**Comment by brionmario** [comment]
> Faced the same issue and resolved by making sure that the Passive STS Realm and Passive STS WReply URL are identical in the management console SP config and in the sample app configs (`<TOMCAT_HOME>/apache-tomcat-<version>/webapps/PassiveSTSSampleApp/WEB-INF/web.xml` if using the WSO2 sample app)

Ex:

```xml
<!-- URL to which responses are directed -->
<init-param>
  <param-name>replyUrl</param-name>
  <param-value>http://localhost:8080/PassiveSTSSampleApp/</param-value>
</init-param>

<!-- URI of the requesting realm -->
<init-param>
  <param-name>realm</param-name>
  <param-value>http://localhost:8080/PassiveSTSSampleApp/</param-value>
</init-param>
```
