### ISSUE TITLE
Couldn't configure WS-Trust as a connector 

### ISSUE THREAD

**Issue by nilasini** [wso2/product-is#9853]
**Describe the issue:**
Build the repo [1]  and get the wso2is-sts-connector-5.6.3.zip. Follow the setup.sh and put all the required jars in relevant places. During the server startup getting following exception.
[1] https://github.com/wso2-extensions/identity-inbound-auth-sts
```
[2020-10-14 15:36:15,397] []  INFO {org.wso2.carbon.humantask.deployer.HumanTaskDeployer} - Initializing HumanTask Deployer for tenant -1234.
[2020-10-14 15:36:15,412] [] FATAL {org.wso2.carbon.core.init.CarbonServerManager} - WSO2 Carbon initialization Failed java.lang.NoClassDefFoundError: org/apache/xml/security/Init
	at org.opensaml.SAMLConfig.<init>(Unknown Source)
	at org.opensaml.SAMLConfig.instance(Unknown Source)
	at org.opensaml.XML$ParserPool.<init>(Unknown Source)
	at org.apache.rahas.impl.util.AxiomParserPool.<init>(AxiomParserPool.java:31)
	at org.apache.rahas.Rahas.init(Rahas.java:44)
	at org.apache.axis2.context.ConfigurationContextFactory.initModules(ConfigurationContextFactory.java:252)
	at org.apache.axis2.context.ConfigurationContextFactory.init(ConfigurationContextFactory.java:230)
	at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:93)
	at org.wso2.carbon.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:65)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:415)
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305)
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.ClassNotFoundException: org.apache.xml.security.Init cannot be found by opensaml_2.6.6.wso2v3
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```
**How to reproduce:**
Build the repo [1]  and get the wso2is-sts-connector-5.6.3.zip. Follow the setup.sh and put all the required jars in relevant places. During the server startup getting above exception.

**Expected behavior:**
No exception should be thrown server should startup without any issue.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.11.0-alpha]
 - OS: [Linux]
 - Database: [Postgresql]
 - Userstore: [JDBC]

---

**Comment by IsuraD** [comment]
@SachiniSiriwardene we need to change the version range of org.apache.xml.security.version as follows. [1]


<org.apache.xml.security.version>[1.4.2,1.6.0)</org.apache.xml.security.version>

[1] https://github.com/wso2/orbit/blob/master/opensaml/2.6.6.wso2v3/pom.xml#L337
