### ISSUE TITLE
Error in SCIM Role search

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#9859]
**Describe the issue:**
SCIM Role search doesn't work in the console. SCIM request returns 500 Internal Server error as follows.

![Screenshot from 2020-10-14 20-43-56](https://user-images.githubusercontent.com/25483865/96009910-d3ea6280-0e5e-11eb-947e-db47f4750c98.png)

Carbon log for that error:
```
[2020-10-14 20:48:19,846] [bba259d2-f332-4966-96e3-5dde26eec9f8] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/scim2].[SCIM2Servlet]} - Servlet.service() for servlet [SCIM2Servlet] in context with path [/scim2] threw exception java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4456)
	at org.wso2.charon3.core.protocol.endpoints.RoleResourceManager.listWithPOSTRole(RoleResourceManager.java:320)
	at org.wso2.carbon.identity.scim2.provider.resources.RoleResource.getRolesByPOST(RoleResource.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:666)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:105)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:122)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
![Screenshot from 2020-10-14 20-43-56](https://user-images.githubusercontent.com/25483865/96009771-b1584980-0e5e-11eb-8228-3acb30766473.png)
![Screenshot from 2020-10-14 20-43-56](https://user-images.githubusercontent.com/25483865/96009809-bae1b180-0e5e-11eb-99df-4ae6fba26175.png)
![Screenshot from 2020-10-14 20-43-56](https://user-images.githubusercontent.com/25483865/96009837-c03efc00-0e5e-11eb-85a5-610aeff44974.png)
![Screenshot from 2020-10-14 20-43-56](https://user-images.githubusercontent.com/25483865/96009875-c9c86400-0e5e-11eb-93f3-55e881dc128f.png)
![Screenshot from 2020-10-14 20-43-56](https://user-images.githubusercontent.com/25483865/96009893-cdf48180-0e5e-11eb-9fed-d45c8574fb03.png)



```

**How to reproduce:**

1. Login to console https://localhost:9443/console/
2. Navigate to Manage > Roles and click on the search bar
3. Provide filter details as appropriate.

 eg: Filter attribute: select Name, Filter condition: starts with, filter value: admin 

Something can be reproduced using API requests:

Request Path:  `https://localhost:9443/t/{{tenant-domain}}/scim2/Roles/.search`

1. successful
```
{
    "filter":"displayName sw admin",
    "schemas":["urn:ietf:params:scim:api:messages:2.0:SearchRequest"],
    "startIndex":1,
    "count": 10
}
```
2. Error - If the "count" attribute is missing
Response 200 OK but no output and give the above carbon error log
```
{
    "filter":"displayName sw admin",
    "schemas":["urn:ietf:params:scim:api:messages:2.0:SearchRequest"],
    "startIndex":1
    
}
```
3. Error - If the "count"  and "startIndex" attributes are missing
Response - 200 OK but no content. Gives error
```
{
    "filter":"displayName sw admin",
    "schemas":["urn:ietf:params:scim:api:messages:2.0:SearchRequest"]
    
}
```
**Expected behavior:**
List the roles which match the conditions without an error. 
"startIndex", "count" are optional parameters. If they are missing should return the results without pagination.
If both params are missing -> Return all the matching roles for the filter up to the supported default count
If count is missing -> Return the matching roles starting from the given index up to the supported default count
If startIndex is missing -> Take 1 as the default value

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11.0-Beta
 - OS: Windows, Linux
 - Database: H2, Postgres
 - Userstore: LDAP, JDBC

**Comment by ashendes** [comment]
This affects the SCIM Users and Groups as well.
