### ISSUE TITLE
IllegalArgumentException occur when updating the OIDC configurations of an application 

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#9933]
When we try to update the OIDC configurations of an application with an empty value for the allowedOrigins attribute in the payload the server throws an illegalArgumentException. The stack trace is given in below.

**Stack trace:** 

```
[2020-10-19 09:28:11,591] [edd1d564-376c-43d8-8c2a-f3a1aacaa55e] ERROR {org.wso2.carbon.identity.api.dispatcher.DefaultExceptionMapper} - Server encountered an error while serving the request. java.lang.IllegalArgumentException: The origin value must not be null.
	at org.wso2.carbon.identity.cors.mgt.core.model.Origin.<init>(Origin.java:45)
	at org.wso2.carbon.identity.cors.mgt.core.model.ValidatedOrigin.<init>(ValidatedOrigin.java:64)
	at org.wso2.carbon.identity.cors.mgt.core.internal.impl.CORSManagementServiceImpl.originsToValidatedOrigins(CORSManagementServiceImpl.java:301)
	at org.wso2.carbon.identity.cors.mgt.core.internal.impl.CORSManagementServiceImpl.setCORSOrigins(CORSManagementServiceImpl.java:94)
	at org.wso2.carbon.identity.api.server.application.management.v1.core.functions.application.inbound.oauth2.OAuthInboundFunctions.putOAuthInbound(OAuthInboundFunctions.java:76)
	at org.wso2.carbon.identity.api.server.application.management.v1.core.ServerApplicationManagementService.putInbound(ServerApplicationManagementService.java:949)
	at org.wso2.carbon.identity.api.server.application.management.v1.core.ServerApplicationManagementService.putInboundOAuthConfiguration(ServerApplicationManagementService.java:491)
	at org.wso2.carbon.identity.api.server.application.management.v1.impl.ApplicationsApiServiceImpl.updateInboundOAuthConfiguration(ApplicationsApiServiceImpl.java:263)
	at org.wso2.carbon.identity.api.server.application.management.v1.ApplicationsApi.updateInboundOAuthConfiguration(ApplicationsApi.java:910)

```

**Sample Request:**

URL: https://localhost:9443/api/server/v1/applications/97c8024d-0a7c-4040-b657-2efdfffc1daf/inbound-protocols/oidc
Method: PUT

Payload: 

```
{
  "clientId": "string",
  "clientSecret": "string",
  "grantTypes": [
    "authorization_code",
    "password"
  ],
  "callbackURLs": [
    "https://app.example.com/callback1",
    "https://app.example.com/callback2"
  ],
  "allowedOrigins": [
    ""
  ],
  "publicClient": false,
  "pkce": {
    "mandatory": false,
    "supportPlainTransformAlgorithm": true
  },
  "accessToken": {
    "type": "JWT",
    "userAccessTokenExpiryInSeconds": 3600,
    "applicationAccessTokenExpiryInSeconds": 3600,
    "bindingType": [
      "sso-session",
      "cookie"
    ],
    "revokeTokensWhenIDPSessionTerminated": true
  },
  "refreshToken": {
    "expiryInSeconds": 86400,
    "renewRefreshToken": true
  },
  "idToken": {
    "expiryInSeconds": 3600,
    "audience": [
      "http://idp.xyz.com",
      "http://idp.abc.com"
    ],
    "encryption": {
      "enabled": false,
      "algorithm": "RSA-OAEP",
      "method": "A128CBC+HS256"
    }
  },
  "logout": {
    "backChannelLogoutUrl": "https://app.example.com/backchannel/callback",
    "frontChannelLogoutUrl": "https://app.example.com/frontchannel/callback"
  },
  "validateRequestObjectSignature": false,
  "scopeValidators": [
    "XACMLScopeValidator",
    "RoleBasedScopeValidator"
  ]
}
```

**Comment by janakamarasena** [comment]
related https://github.com/wso2/product-is/issues/9918
