### ISSUE TITLE
Concurrent SSO requests fail with primary key violation

### ISSUE THREAD

**Issue by rksk** [wso2/product-is#9945]
**Describe the issue:**
When two SSO requests come to IS at the same time, a primary key violation occurs while trying to insert a record into IDN_AUTH_SESSION_APP_INFO table. We check the existence of the record at [1] before inserting, but in a concurrent scenario, this would not be enough.
```
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} - Exception in Authentication Framework org.wso2.carbon.identity.application.authentication.framework.exception.FrameworkException: Error while storing session details of the authenticated user to the database
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.concludeFlow(DefaultAuthenticationRequestHandler.java:470)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:165)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:239)
	at org.wso2.carbon.identity.application.authentication.framework.CommonAuthenticationHandler.doPost(CommonAuthenticationHandler.java:46)
	at org.wso2.carbon.identity.application.authentication.framework.CommonAuthenticationHandler.doGet(CommonAuthenticationHandler.java:37)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleAuthFlowThroughFramework(OAuth2AuthzEndpoint.java:2391)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.handleInitialAuthorizationRequest(OAuth2AuthzEndpoint.java:807)
	at org.wso2.carbon.identity.oauth.endpoint.authz.OAuth2AuthzEndpoint.authorize(OAuth2AuthzEndpoint.java:234)
	....
Caused by: org.wso2.carbon.identity.application.authentication.framework.exception.UserSessionException: Error while storing Application session data in the database.
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.storeSessionData(DefaultAuthenticationRequestHandler.java:598)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.concludeFlow(DefaultAuthenticationRequestHandler.java:468)
	... 71 more
Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error while storing application data for session in the database.
	at org.wso2.carbon.identity.application.authentication.framework.store.UserSessionStore.storeAppSessionData(UserSessionStore.java:504)
	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.storeSessionData(DefaultAuthenticationRequestHandler.java:595)
	... 72 more
Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s'INSERT INTO IDN_AUTH_SESSION_APP_INFO(SESSION_ID,SUBJECT,APP_ID,INBOUND_AUTH_TYPE)VALUES (?,?,?,?)
	at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.executeUpdate(JdbcTemplate.java:230)
	at org.wso2.carbon.identity.application.authentication.framework.store.UserSessionStore.storeAppSessionData(UserSessionStore.java:497)
	... 73 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "idn_auth_session_app_info_pkey"
  Detail: Key (session_id, subject, app_id, inbound_auth_type)=(xxx, xx, xx, oauth2/authorize) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2510)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2245)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:311)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:125)
	at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy54.executeUpdate(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.JdbcTemplate.executeUpdate(JdbcTemplate.java:223)
	... 74 more
```

**How to reproduce:**
- Configure two Oauth2 SPs
- Login to one SP and get the commonauthId cookie
- Send two concurrent requests to "oauth2/authorize" with two curl requests like below (use commonauthId of above step and use client id of the SP; consents has to be approved for SP2 already)
```
curl -k 'https://localhost:9443/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2Flocalhost&scope=openid&client_id=gRQs0T4j8gpU7tINlIDtgVV9e0Ea' -H 'Cookie: commonAuthId=a0eecb43-70f5-4733-bbaf-0282be41cc89' & curl -k 'https://localhost:9443/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2Flocalhost&scope=openid&client_id=gRQs0T4j8gpU7tINlIDtgVV9e0Ea' -H 'Cookie: commonAuthId=a0eecb43-70f5-4733-bbaf-0282be41cc89'
```

**Expected behavior:**
we might be able to handle primary key violations inside the store method and skip them.

**Environment information**
 - Product Version: IS 5.9.0 IS 5.10.0

[1] https://github.com/wso2/carbon-identity-framework/blob/v5.14.97/components/authentication-framework/org.wso2.carbon.identity.application.authentication.framework/src/main/java/org/wso2/carbon/identity/application/authentication/framework/handler/request/impl/DefaultAuthenticationRequestHandler.java#L592-L596

**Comment by rksk** [comment]
Still, this issue can be reproduced when the amount of data in the IDN_AUTH_SESSION_APP_INFO table is high since the insert operation slows down. As mentioned in [1], the statements like Oracle Merge do not help in concurrent situations. IMO, it is required to have application-level synchronization or catch and ignore the constraint violations in this flow.

[1] https://stackoverflow.com/questions/38245727/oracle-merge-statements-executed-in-parallel-transactions-how-to-prevent-duplic
