### ISSUE TITLE
Creating the Identity provider using the Expert Mode give error

### ISSUE THREAD

**Issue by Sathiyakugan** [wso2/product-is#9949]
when creating the Identity provider using the Expert Mode got the error in the server console. Also able to reproducible when typing the Identity Provider Name filed and deleting it. 

```
[2020-10-19 14:46:57,163] [820e7157-13f3-453a-bde6-e66c1ea443ee] ERROR {org.wso2.carbon.identity.api.server.idp.v1.core.ServerIdpManagementService} - errorCode: IDP-60021 | message: Server encountered an error while listing the identity providers. org.wso2.carbon.idp.mgt.IdentityProviderManagementClientException: Error while getting the Identity Provider: Error occurred while validate filter, filter: name eq .
	at org.wso2.carbon.idp.mgt.util.IdPManagementUtil.handleClientException(IdPManagementUtil.java:217)
	at org.wso2.carbon.idp.mgt.IdentityProviderManager.getExpressionNodes(IdentityProviderManager.java:1141)
	at org.wso2.carbon.idp.mgt.IdentityProviderManager.getIdPs(IdentityProviderManager.java:1095)
	at org.wso2.carbon.identity.api.server.idp.v1.core.ServerIdpManagementService.getIDPs(ServerIdpManagementService.java:160)
	at org.wso2.carbon.identity.api.server.idp.v1.impl.IdentityProvidersApiServiceImpl.getIDPs(IdentityProvidersApiServiceImpl.java:139)
	at org.wso2.carbon.identity.api.server.idp.v1.IdentityProvidersApi.getIDPs(IdentityProvidersApi.java:356)
	at sun.reflect.GeneratedMethodAccessor235.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:135)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:102)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:122)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:126)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.identity.base.IdentityException: Given filter operator is not supported. Filter attribute:  name eq
	at org.wso2.carbon.identity.core.model.FilterTreeBuilder.validateAndBuildFilterExpression(FilterTreeBuilder.java:239)
	at org.wso2.carbon.identity.core.model.FilterTreeBuilder.factor(FilterTreeBuilder.java:164)
	at org.wso2.carbon.identity.core.model.FilterTreeBuilder.term(FilterTreeBuilder.java:137)
	at org.wso2.carbon.identity.core.model.FilterTreeBuilder.expression(FilterTreeBuilder.java:122)
	at org.wso2.carbon.identity.core.model.FilterTreeBuilder.buildTree(FilterTreeBuilder.java:113)
	at org.wso2.carbon.idp.mgt.IdentityProviderManager.getExpressionNodes(IdentityProviderManager.java:1135)
	... 55 more
```

**How to reproduce:**

1. Go to the console. https://localhost:9443/console login using the tenant admin
2. Go to Identity Providers-> New Identity Provider -> Expert Mode 
3. Type something in Identity Provider Name filed and delete it

**Expected behaviour:**
It should not prompt any error on the server console.

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
- Product Version: IS 5.11.0-Beta2
- OS: Linux
- Database: Postgres
- User store: JDBC

---

### Optional Fields

**Suggested labels:**
Bug, Priority/High Severity/Minor, UI Component/Identity Provider Management

**Comment by nilasini** [comment]
duplicates https://github.com/wso2/product-is/issues/9885
